% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  singlecolumn]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=20mm,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal effect of Psychopathy on Partner Well-Being: A National Longitudinal Study},
  pdfauthor={Aaron Hissey; Hedwig Eisenbarth; Chris G. Sibley; Matthew Hammond; Joseph A. Bulbulia},
  pdfkeywords={Causal
Inference, Relationships, Panel, Psychopathy, Personality, Well-being, Outcome-wide},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal effect of Psychopathy on Partner Well-Being: A National
Longitudinal Study}
\author{Aaron Hissey \and Hedwig Eisenbarth \and Chris G.
Sibley \and Matthew Hammond \and Joseph A. Bulbulia}
\date{2024-02-28}

\begin{document}
\maketitle

\subsection{Introduction}\label{introduction}

A central question in psychopathy research is how it affects
relationships.

Here, to address this question, we develop an outcome-wide longitudinal
study using a national longitudinal probability sample in New Zealand.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of The New Zealand Attitudes and Values
Study (NZAVS) is an annual longitudinal national probability panel study
of social attitudes, personality, ideology and health outcomes. The
NZAVS began in 2009. It includes questionnaire responses from over
72,000 New Zealand residents. The study includes researchers from many
New Zealand universities, including the University of Auckland, Victoria
University of Wellington, the University of Canterbury, the University
of Otago, and Waikato University. Because the survey asks the same
people to respond each year, it can track subtle changes in attitudes
and values over time and is an important resource for researchers in New
Zealand and worldwide. The NZAVS is university-based, not-for-profit and
independent of political or corporate
funding.https://doi.org/10.17605/OSF.IO/75SNB

\hyperref[appendix-measures]{Appendix A} provides statistical
information about the measures used in this study.

\hyperref[appendix-demographics]{Appendix B} provides information about
demographic covariates used for confounding control (NZAVS time 10,
years 2018-2019).

\hyperref[appendix-exposures]{Appendix C} provides information about the
treatment responses at baseline (NZAVS time 10) and in the treatment
wave (NZAVS time 11, years 2019-2020).

\hyperref[appendix-outcomes]{Appendix D} provides information about
about the outcome variables responses at baseline (NZAVS time 10) and in
the treatment wave (NZAVS time 12, years 2020-2021).

\subsubsection{Eligibility criteria}\label{eligibility-criteria}

The sample consisted of respondents to NZAVS times 10 (baseline, years
2018-2019), time 11 (treatment wave, years 2019-2020), and time 12
(outcome wave) (years 2020-2021).

Criteria for inclusion were pre-specified and pre-registered in advance
of the analysis at:\url{https://osf.io/ce4t9/}

\paragraph{Included:}\label{included}

\begin{itemize}
\tightlist
\item
  Participants who were identified as being in couples.\\
\item
  Participants who provided full information to the psychopathy
  measures.
\end{itemize}

\subparagraph{Excluded}\label{excluded}

\begin{itemize}
\tightlist
\item
  Participants who had missing responses to the treatment variables at
  baseline or in the treatment wave, or both.
\item
  We allowed loss-to-follow-up in the outcome wave (NZAVS wave 2020)
\item
  Missing data for all variables at baseline were allowed. Missing data
  at baseline were imputed through the \texttt{mice} package
  (\citeproc{ref-vanbuuren2018}{Van Buuren 2018}).
\item
  Inverse probability of censoring weights were calculated as part of
  estimation in \texttt{lmtp} to adjust for missing outcomes at NZAVS
  Time 12 (years 2020-2021, the outcome wave
  (\citeproc{ref-williams2021}{Williams and Díaz 2021}))
\end{itemize}

There were 1070 NZAVS participants who met these criteria.

\subsubsection{Causal Contrast}\label{causal-contrast}

Here, we leverage panel data to estimate potential outcomes in a
hypothetical world in which partners in couples were shifted up or down
on a one-point scale for psychopathic personality.

Our causal estimand takes a ``shift function'' or ``modified treatment
policy'':

\[ \text{Average Treatment Effect} = E[Y(a^*)|\textcolor{red}{f(A)},L] - E[Y(a)|A,L] \]

\textbf{Intervention Functionals:}

\begin{itemize}
\item
  \textbf{Shift up by +1 point:} \[
   f(A = a) = \begin{cases} a^* & \text{shift up by +1 point} \\ 
   \tilde{a} & \text{observed value of the exposure} \end{cases}
   \]
\item
  \textbf{Shift down by -1 point:} \[
   f(A = a) = \begin{cases} a^* & \text{shift up by -1 point} \\ 
   \tilde{a} & \text{observed value of the exposure} \end{cases}
   \]
\end{itemize}

\subsubsection{Identification
Assumptions}\label{identification-assumptions}

To consistently estimate causal effects, we rely on three key
assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal Consistency:} potential outcomes must align with
  observed outcomes under the treatments in our data. Essentially, we
  assume potential outcomes do not depend on the specific way treatment
  was administered, as long as we consider measured covariates.
\item
  \textbf{Conditional Exchangeability:} given the observed covariates,
  we assume treatment assignment is independent of potential outcomes.
  In simpler terms, this means ``no unmeasured confounding'' -- any
  factors influencing both treatment assignment and outcomes must be
  included in our measured covariates.
\item
  \textbf{Positivity:} for unbiased estimation, every subject must have
  a non-zero chance of receiving the treatment, regardless of their
  covariate values. We evaluate this assumption in each study by
  examining changes in psychopathy ``treatments'' from baseline (NZAVS
  time 10) to the treatment wave (NZAVS time 11). It is the initiation
  of a psychopathic trait and their combinations, whose causal effect we
  seek to quantify
\end{enumerate}

\textbf{Considerations:}

Neither causal consistency nor conditional exchangeability can be
directly tested with data. Because unmeasured confounding cannot be
tested, we perform sensitivity analysis by estimating the magnitude of
unmeasured confounding required to explain away a result (E-values).

\subsubsection{Analysis}\label{analysis}

Criteria for analysis were pre-specified and pre-registered in advance
of the analysis at:\url{https://osf.io/ce4t9/}, and followed standard
NZAVS protocols for three-wave causal inference designs
(\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024}).

\subsubsection{Confounding Control
Strategy}\label{confounding-control-strategy}

We followed VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020})'s \emph{minimally modified
disjunctive criteria} for confounding control.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Initial identify confounders}: using causal diagrams, we began
  by enumerating all covariates that may influence either the treatment
  (exposure) or outcomes, spanning five domains. This includes variables
  directly affecting the exposure or outcome, as well as potential
  consequences of these variables (i.e.~proxies.)
\item
  \textbf{Remove instrumental variables}: we removed variables that are
  identified as instrumental variables, i.e., those influencing the
  exposure but not the outcome. Their inclusion can reduce the
  efficiency of the analysis.
\item
  \textbf{Inclusion of proxy variables}: for unmeasured variables that
  affect both the exposure and outcome, include proxy variables wherever
  possible. These proxies act as indicators for the unmeasured common
  causes. \hyperref[appendix-demographics]{Appendix B} lists covariates
  we used for confounding control. These protocols follow advice in
  (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024}) as prespecified
  in \url{https://osf.io/ce4t9/}.
\item
  \textbf{Baseline exposure control}: we included baseline measures of
  the outcome to adjust for unmeasured confounding
  (\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).
  Accounting for prior exposure also allowed us to recover an incident
  exposure effect as opposed to a prevalent exposure effect: that is, we
  were able to focus on the one-year effect on partner well-being from
  initiation to psychopathy or a psychopathic trait
  (\citeproc{ref-danaei2012}{Danaei \emph{et al.} 2012};
  \citeproc{ref-hernan2023}{Hernan and Robins 2023}).
\item
  \textbf{Baseline outcome control}: we also included baseline measures
  of the outcome to adjust for unmeasured confounding
  (\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). This
  strategy also minimises the possibility of reverse causation.
\end{enumerate}

Additionally, we adopted the following confounding-control strategies:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
  \textbf{Partner's covariates}: because the effect of changes in one
  individual's variables on their partner's outcomes is assessed, we
  include baseline measures for the partner's covariates, as we as of
  the focal partner. Additionally, we clustered individuals with their
  dyadic partnerships, which helps adjust for unmeasured features that
  might affect results.
\item
  \textbf{Handling missing data}: to better ensure that the analyses
  were robust to potential biases introduced by missing data, we adopted
  the following strategies:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  \textbf{Baseline missingness}: we imputed missing data to recover
  baseline missing data (\texttt{mice} package in R)
  (\citeproc{ref-vanbuuren2018}{Van Buuren 2018}).
\item
  \textbf{Follow-up missingness}: we used the \texttt{lmtp} packages
  build-in censoring weighting to adjust for loss-to-follow-up/sample
  attrition (\citeproc{ref-williams2021}{Williams and Díaz 2021}).
\end{itemize}

\paragraph{Estimator}\label{estimator}

We employ a semi-parametric estimator known as Targeted Minimum
Loss-based Estimation (TMLE), which is able to estimate the causal
effect of modified treatment policies on outcomes over time
(\citeproc{ref-vanderlaan2011}{Van Der Laan and Rose 2011},
\citeproc{ref-vanderlaan2018}{2018}). Estimation was performed using
\texttt{lmtp} package (\citeproc{ref-duxedaz2021}{Díaz \emph{et al.}
2021}; \citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023};
\citeproc{ref-williams2021}{Williams and Díaz 2021}). TMLE is a robust
method that combines machine learning techniques with traditional
statistical models to estimate causal effects while providing valid
statistical uncertainty measures for these estimates.

TMLE operates through a two-step process involving outcome and treatment
(exposure) models. Initially, it employes machine learning algorithms to
flexibly model the relationship between treatments, covariates, and
outcomes. This flexibility allows TMLE to account for complex,
high-dimensional covariate spaces without imposing restrictive model
assumptions. The outcome of this step is a set of initial estimates for
these relationships.

The second step of TMLE involves ``targeting'' these initial estimates
by incorporating information about the observed data distribution to
improve the accuracy of the causal effect estimate. This is achieved
through an iterative updating process, which adjusts the initial
estimates towards the true causal effect. This updating process is
guided by the efficient influence function, ensuring that the final TMLE
estimate is as close as possible to the true causal effect while
remaining robust to model misspecification in either the outcome or
treatment model.

A central feature of TMLE is its double-robustness property, meaning
that if either the model for the treatment or the outcome is correctly
specified, the TMLE estimator will still consistently estimate the
causal effect. Additionally, TMLE uses cross-validation to avoid
overfitting and ensure that the estimator performs well in finite
samples. Each of these steps contributes to a robust methodology for
examining the \emph{causal} effects on of interventions on outcomes. The
marriage of TMLE and machine learning technologies reduces the
dependence on restrictive modelling assumptions and introduces an
additional layer of robustness. For further details see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023})

\paragraph{Estimation}\label{estimation}

We used the \texttt{lmtp} R package to estimate treatments' causal
effects on well-being outcomes for each of the four trait dimensions and
the composite measure. Measurements of the treatments and outcomes were
included with baseline covariates. Our models included an indicator for
censorship in the next wave (C) which adjusted for loss to
follow-up/attrition conditional on measured covariates. As mentioned,
models estimated the effects of shifting the treatment variable by one
unit (both increase and decrease) using custom shift functions (f and
f\_1), which adjust the treatment variable within the observed range.
Two custom shift functions were defined to model the hypothetical
intervention of increasing or decreasing the treatment variable by one
unit, and these were contrasted against the expectation from a `null'
model.

\begin{itemize}
\tightlist
\item
  \textbf{increase +1 function}: increases the treatment variable by one
  unit, capped at the maximum observed score.
\item
  \textbf{decrease -1 function}: decreases the treatment variable by one
  unit, floored at the minimum observed score.
\item
  \textbf{`null' model:} the null model was specified identically to the
  treatment effect models in terms of the included covariates, outcome
  variable, and model structure but without applying any shift to the
  treatment variable. This ensured that any differences observed between
  the treatment models and the null model can be attributed to the
  treatment effect rather than differences in model specification. By
  estimating a model under the assumption of no change in the treatment
  status, we obtained clear baselines against which the effects of
  treatment shifts could be assessed.
\end{itemize}

\texttt{lmtp} draws on the the \texttt{SuperLearner} library, which
comprises various machine learning algorithms
(\citeproc{ref-SuperLearner2023}{Polley \emph{et al.} 2023}). Given the
relatively sample (N=1070) we used the \texttt{Ranger} and
\texttt{randomForest} estimators - both causal forest estimators -- a
subset of non-parametric estimators distinguished by their resilience
against overfitting {[}Ranger2017; randomForest2002{]}. Causal forests
excel in identifying complex, non-linear relationships between variables
without presupposing a specific model form, and thus making fewer
assumptions about the underlying data distribution.

\paragraph{Cross-Validation}\label{cross-validation}

We implemented a 10-fold cross-validation. This method partitions the
data into ten subsets of approximately equal size. During the
cross-validation process, nine subsets are used to train the model, and
the remaining subset is used for testing. This process is repeated ten
times, with each of the ten subsets used exactly once as the test set.
Using different subsets for training and validation, minimises the risk
of the model being overly complex and fitting the noise in the training
dataset, which can lead to poor performance on new data. Moreover, each
observation is used for training and validation, which is particularly
beneficial in scenarios where the amount of data is limited. The
cross-validation process results in ten estimates of model accuracy,
which can be averaged to provide a more comprehensive measure of model
performance.

\paragraph{Sensitiviy Analysis Using the
E-value}\label{sensitiviy-analysis-using-the-e-value}

To measure senstivity to unmeasured confounding, we report VanderWeele
and Ding's ``E-value'' for all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to
explain-away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). For
example, if the E-value were 1.3, it would mean an unmeasured confounder
associated with both the treatment and outcome by a risk ratio of 1.3
each (or 30\% increase in risk) could explain away the observed effect.
Weaker confounding would not suffice. We also report the bound of the
E-value closest to 1. If the lower bound of the CI were 1.1, to explain
away the result, the strength of an unmeasured confounder in its
association with both the treatment and the outcome would need to be at
least 1.1 on the risk ratio scale (or a 10\% increase in risk) to
explain away the result (\citeproc{ref-vanderweele2017}{VanderWeele and
Ding 2017}).

\subsection{Study 1: Antagonism}\label{study-1-antagonism}

\paragraph{Histogram of Exposure}\label{histogram-of-exposure}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-histogram-antagonism-1.pdf}

}

\caption{\label{fig-histogram-antagonism}Histogram of exposure variable
(possible response scale = 1-7)}

\end{figure}%

\paragraph{Transition table}\label{transition-table}

Table~\ref{tbl-transition-antagonism} shows a transition matrix captures
stability and movement between antagonism responses from the baseline
(NZAVS time 10) wave and exposure wave (NZAVS time 11). Entries on the
diagonal (in bold) indicate the number of individuals who stayed in
their initial state. In contrast, the off-diagonal shows the transitions
from the initial state (bold) to another state the following wave
(off-diagonal). A cell located at the intersection of row \(i\) and
column \(j\), where \(i \neq j\), shows the count of individuals moving
from state \(i\) to state \(j\).

\begin{longtable}[]{@{}ccccccc@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave}\label{tbl-transition-antagonism}\tabularnewline
\toprule\noalign{}
From & State 1 & State 2 & State 3 & State 4 & State 5 & State 6 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & State 1 & State 2 & State 3 & State 4 & State 5 & State 6 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 1 & \textbf{0} & 0 & 0 & 1 & 0 & 0 \\
State 2 & 0 & \textbf{1} & 3 & 3 & 0 & 0 \\
State 3 & 0 & 2 & \textbf{28} & 49 & 6 & 0 \\
State 4 & 0 & 2 & 38 & \textbf{463} & 118 & 2 \\
State 5 & 0 & 0 & 10 & 137 & \textbf{181} & 6 \\
State 6 & 0 & 0 & 1 & 3 & 13 & \textbf{3} \\
\end{longtable}

\subsubsection{Results Study 1 A: Antagonism Results
Gain}\label{results-study-1-a-antagonism-results-gain}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-antagonism-gain-1.pdf}

}

\caption{\label{fig-results-antagonism-gain}Results for antagonism gain
on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

Average Treatment Effect (ATE) represents the expected difference in
outcomes between treatment and control groups for the population.

For the outcome `Gain psychopathy antagonism: partner conflict in a
relationship', the ATE causal contrast is 0.082. The E-value for this
outcome is 1.366; The confidence interval ranges from 0.014 to 0.15.
Overall, we find reliable evidence for causality.

For the outcome `Gain psychopathy antagonism: partner Kessler 6
depression', the ATE causal contrast is 0.018. The E-value for this
outcome is 1.147; The confidence interval ranges from -0.033 to 0.069.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy antagonism: partner Kessler 6
distress', the ATE causal contrast is 0.012. The E-value for this
outcome is 1.117; The confidence interval ranges from -0.04 to 0.065.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy antagonism: partner Kessler 6
anxiety', the ATE causal contrast is 0.008. The E-value for this outcome
is 1.095; The confidence interval ranges from -0.048 to 0.065. Overall,
we find no reliable evidence for causality.

For the outcome `Gain psychopathy antagonism: partner pers. wellbeing',
the ATE causal contrast is 0. The E-value for this outcome is 1.022; The
confidence interval ranges from -0.053 to 0.054. Overall, we find no
reliable evidence for causality.

For the outcome `Gain psychopathy antagonism: partner self-esteem', the
ATE causal contrast is -0.009. The E-value for this outcome is 1.098;
The confidence interval ranges from -0.066 to 0.048. Overall, we find no
reliable evidence for causality.

For the outcome `Gain psychopathy antagonism: partner relationship
satisfaction', the ATE causal contrast is -0.074. The E-value for this
outcome is 1.342; The confidence interval ranges from -0.152 to 0.005.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy antagonism: partner life
satisfaction', the ATE causal contrast is -0.122. The E-value for this
outcome is 1.481; The confidence interval ranges from -0.192 to -0.053.
Overall, we find reliable evidence for causality.

\newpage{}

\subsubsection{Results Study 1 B: Antagonism Results
Loss}\label{results-study-1-b-antagonism-results-loss}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-antagonism-loss-1.pdf}

}

\caption{\label{fig-results-antagonism-loss}Results for antagonism loss
on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5586}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1441}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0541}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0631}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0721}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1081}}@{}}

\caption{\label{tbl-results-antagonism-loss}Table for antagonism loss on
partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Loss psychopathy antagonism: partner conflict in relationship & -0.06 &
-0.14 & 0.02 & 1.30 & 1 \\
Loss psychopathy antagonism: partner relationship satisfacton & 0.02 &
-0.06 & 0.09 & 1.14 & 1 \\
Loss psychopathy antagonism: partner Kessler 6 distress & -0.01 & -0.06
& 0.04 & 1.09 & 1 \\
Loss psychopathy antagonism: partner Kessler 6 depression & -0.03 &
-0.09 & 0.02 & 1.21 & 1 \\
Loss psychopathy antagonism: partner Kessler 6 anxiety & 0.00 & -0.06 &
0.06 & 1.06 & 1 \\
Loss psychopathy antagonism: partner self-esteem & 0.02 & -0.04 & 0.07 &
1.14 & 1 \\
Loss psychopathy antagonism: partner pers. wellbeing & -0.02 & -0.08 &
0.03 & 1.17 & 1 \\
Loss psychopathy antagonism: partner life satisfaction & 0.01 & -0.05 &
0.07 & 1.10 & 1 \\

\end{longtable}

For the outcome `Loss psychopathy antagonism: partner self-esteem', the
ATE causal contrast is 0.017. The E-value for this outcome is 1.141; The
confidence interval ranges from -0.036 to 0.07. Overall, we find no
reliable evidence for causality.

For the outcome `Loss psychopathy antagonism: partner relationship
satisfaction', the ATE causal contrast is 0.016. The E-value for this
outcome is 1.138; The confidence interval ranges from -0.058 to 0.09.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy antagonism: partner life
satisfaction', the ATE causal contrast is 0.01. The E-value for this
outcome is 1.103; The confidence interval ranges from -0.046 to 0.065.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy antagonism: partner Kessler 6
anxiety', the ATE causal contrast is 0.003. The E-value for this outcome
is 1.059; The confidence interval ranges from -0.056 to 0.063. Overall,
we find no reliable evidence for causality.

For the outcome `Loss psychopathy antagonism: partner Kessler 6
distress', the ATE causal contrast is -0.008. The E-value for this
outcome is 1.092; The confidence interval ranges from -0.058 to 0.042.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy antagonism: partner pers. wellbeing',
the ATE causal contrast is -0.025. The E-value for this outcome is
1.175; The confidence interval ranges from -0.082 to 0.032. Overall, we
find no reliable evidence for causality.

For the outcome `Loss psychopathy antagonism: partner Kessler 6
depression', the ATE causal contrast is -0.033. The E-value for this
outcome is 1.207; The confidence interval ranges from -0.089 to 0.024.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy antagonism: partner conflict in a
relationship', the ATE causal contrast is -0.06. The E-value for this
outcome is 1.299; The confidence interval ranges from -0.144 to 0.025.
Overall, we find no reliable evidence for causality.

\subsection{Study 2 Disinhibition}\label{study-2-disinhibition}

\paragraph{Histogram of Exposure}\label{histogram-of-exposure-1}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-histogram-disinhibition-1.pdf}

}

\caption{\label{fig-histogram-disinhibition}Histogram of exposure
variable (possible response scale = 1-7)}

\end{figure}%

\paragraph{Transition table}\label{transition-table-1}

Table~\ref{tbl-transition-disinhibition} shows a transition matrix
captures stability and movement between disinhibition responses from the
baseline (NZAVS time 10) wave and exposure wave (NZAVS time 11). Entries
on the diagonal (in bold) indicate the number of individuals who stayed
in their initial state. In contrast, the off-diagonal shows the
transitions from the initial state (bold) to another state the following
wave (off-diagonal). A cell located at the intersection of row \(i\) and
column \(j\), where \(i \neq j\), shows the count of individuals moving
from state \(i\) to state \(j\).

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}
  >{\centering\arraybackslash}p{(\columnwidth - 12\tabcolsep) * \real{0.1429}}@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave}\label{tbl-transition-disinhibition}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 1 & \textbf{0} & 0 & 0 & 1 & 0 & 0 \\
State 2 & 0 & \textbf{1} & 3 & 3 & 0 & 0 \\
State 3 & 0 & 2 & \textbf{28} & 49 & 6 & 0 \\
State 4 & 0 & 2 & 38 & \textbf{463} & 118 & 2 \\
State 5 & 0 & 0 & 10 & 137 & \textbf{181} & 6 \\
State 6 & 0 & 0 & 1 & 3 & 13 & \textbf{3} \\
\end{longtable}

\subsubsection{Results Study 2 A: Disinhibition Results
Gain}\label{results-study-2-a-disinhibition-results-gain}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-disinhibition-gain-1.pdf}

}

\caption{\label{fig-results-disinhibition-gain}Results for disinhibition
gain on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5739}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1391}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0522}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0609}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0696}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1043}}@{}}

\caption{\label{tbl-results-disinhibition-gain}Table for disinhibition
gain on partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Loss psychopathy disinhibition: partner conflict in relationship & -0.02
& -0.08 & 0.04 & 1.16 & 1 \\
Loss psychopathy disinhibition: partner relationship satisfacton & 0.01
& -0.05 & 0.08 & 1.12 & 1 \\
Loss psychopathy disinhibition: partner Kessler 6 distress & 0.00 &
-0.06 & 0.05 & 1.05 & 1 \\
Loss psychopathy disinhibition: partner Kessler 6 depression & 0.01 &
-0.05 & 0.06 & 1.09 & 1 \\
Loss psychopathy disinhibition: partner Kessler 6 anxiety & -0.01 &
-0.07 & 0.05 & 1.09 & 1 \\
Loss psychopathy disinhibition: partner self-esteem & -0.03 & -0.08 &
0.03 & 1.18 & 1 \\
Loss psychopathy disinhibition: partner pers. wellbeing & -0.02 & -0.08
& 0.04 & 1.15 & 1 \\
Loss psychopathy disinhibition: partner life satisfaction & 0.00 & -0.05
& 0.06 & 1.07 & 1 \\

\end{longtable}

For the outcome `Gain psychopathy disinhibition: partner life
satisfaction', the ATE causal contrast is 0.025. The E-value for this
outcome is 1.175;The confidence interval ranges from -0.016 to 0.065.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy disinhibition: partner Kessler 6
anxiety', the ATE causal contrast is 0.022. The E-value for this outcome
is 1.163;The confidence interval ranges from -0.021 to 0.065. Overall,
we find no reliable evidence for causality.

For the outcome `Gain psychopathy disinhibition: partner Kessler 6
distress', the ATE causal contrast is 0.017. The E-value for this
outcome is 1.143;The confidence interval ranges from -0.027 to 0.062.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy disinhibition: partner conflict in
relationship', the ATE causal contrast is 0.013. The E-value for this
outcome is 1.121;The confidence interval ranges from -0.041 to 0.066.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy disinhibition: partner Kessler 6
depression', the ATE causal contrast is 0.01. The E-value for this
outcome is 1.105;The confidence interval ranges from -0.032 to 0.052.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopath disinhibition: partner relationship
satisfaction', the ATE causal contrast is 0.009. The E-value for this
outcome is 1.099;The confidence interval ranges from -0.039 to 0.056.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy disinhibition: partner self-esteem',
the ATE causal contrast is 0.004. The E-value for this outcome is
1.068;The confidence interval ranges from -0.036 to 0.045. Overall, we
find no reliable evidence for causality.

For the outcome `Gain psychopathy disinhibition: partner pers.
wellbeing', the ATE causal contrast is -0.01. The E-value for this
outcome is 1.105;The confidence interval ranges from -0.052 to 0.032.
Overall, we find no reliable evidence for causality.

\subsubsection{Results Study 2 B: Disinhibition Results
Loss}\label{results-study-2-b-disinhibition-results-loss}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-disinhibition-loss-1.pdf}

}

\caption{\label{fig-results-disinhibition-loss}Results for disinhibition
loss on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5739}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1391}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0522}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0609}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0696}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1043}}@{}}

\caption{\label{tbl-results-disinhibition-loss}Table for disinhibition
loss on partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Loss psychopathy disinhibition: partner conflict in relationship & -0.02
& -0.08 & 0.04 & 1.16 & 1 \\
Loss psychopathy disinhibition: partner relationship satisfacton & 0.01
& -0.05 & 0.08 & 1.12 & 1 \\
Loss psychopathy disinhibition: partner Kessler 6 distress & 0.00 &
-0.06 & 0.05 & 1.05 & 1 \\
Loss psychopathy disinhibition: partner Kessler 6 depression & 0.01 &
-0.05 & 0.06 & 1.09 & 1 \\
Loss psychopathy disinhibition: partner Kessler 6 anxiety & -0.01 &
-0.07 & 0.05 & 1.09 & 1 \\
Loss psychopathy disinhibition: partner self-esteem & -0.03 & -0.08 &
0.03 & 1.18 & 1 \\
Loss psychopathy disinhibition: partner pers. wellbeing & -0.02 & -0.08
& 0.04 & 1.15 & 1 \\
Loss psychopathy disinhibition: partner life satisfaction & 0.00 & -0.05
& 0.06 & 1.07 & 1 \\

\end{longtable}

Average Treatment Effect (ATE) represents the expected difference in
outcomes between treatment and control groups for the population.

For the outcome `Loss psychopathy disinhibition: partner relationship
satisfaction', the ATE causal contrast is 0.013. The E-value for this
outcome is 1.122;The confidence interval ranges from -0.05 to 0.076.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy disinhibition: partner Kessler 6
depression', the ATE causal contrast is 0.008. The E-value for this
outcome is 1.09;The confidence interval ranges from -0.049 to 0.064.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy disinhibition: partner life
satisfaction', the ATE causal contrast is 0.005. The E-value for this
outcome is 1.069;The confidence interval ranges from -0.05 to 0.059.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy disinhibition: partner Kessler 6
distress', the ATE causal contrast is -0.002. The E-value for this
outcome is 1.049;The confidence interval ranges from -0.056 to 0.051.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy disinhibition: partner Kessler 6
anxiety', the ATE causal contrast is -0.008. The E-value for this
outcome is 1.095;The confidence interval ranges from -0.068 to 0.052.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy disinhibition: partner pers.
wellbeing', the ATE causal contrast is -0.02. The E-value for this
outcome is 1.154;The confidence interval ranges from -0.08 to 0.041.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy disinhibition: partner conflict in
relationship', the ATE causal contrast is -0.021. The E-value for this
outcome is 1.16;The confidence interval ranges from -0.083 to 0.041.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy disinhibition: partner self-esteem',
the ATE causal contrast is -0.025. The E-value for this outcome is
1.178;The confidence interval ranges from -0.083 to 0.032. Overall, we
find no reliable evidence for causality.

\subsection{Study 3 Emotional
Stability}\label{study-3-emotional-stability}

\paragraph{Histogram of Exposure}\label{histogram-of-exposure-2}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-histogram-emotional-1.pdf}

}

\caption{\label{fig-histogram-emotional}Histogram of exposure variable
(possible response scale = 1-7)}

\end{figure}%

\paragraph{Transition table}\label{transition-table-2}

Table~\ref{tbl-transition-emotional} shows a transition matrix captures
stability and movement between emotional stability responses from the
baseline (NZAVS time 10) wave and exposure wave (NZAVS time 11). Entries
on the diagonal (in bold) indicate the number of individuals who stayed
in their initial state. In contrast, the off-diagonal shows the
transitions from the initial state (bold) to another state the following
wave (off-diagonal). A cell located at the intersection of row \(i\) and
column \(j\), where \(i \neq j\), shows the count of individuals moving
from state \(i\) to state \(j\).

\begin{longtable}[]{@{}ccccccc@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave}\label{tbl-transition-emotional}\tabularnewline
\toprule\noalign{}
From & State 2 & State 3 & State 4 & State 5 & State 6 & State 7 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & State 2 & State 3 & State 4 & State 5 & State 6 & State 7 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 2 & \textbf{13} & 7 & 4 & 0 & 0 & 0 \\
State 3 & 7 & \textbf{17} & 20 & 5 & 1 & 0 \\
State 4 & 4 & 26 & \textbf{124} & 75 & 21 & 0 \\
State 5 & 0 & 3 & 69 & \textbf{140} & 107 & 3 \\
State 6 & 0 & 0 & 21 & 86 & \textbf{251} & 21 \\
State 7 & 0 & 0 & 1 & 5 & 30 & \textbf{9} \\
\end{longtable}

\subsubsection{Results Study 3 A: Emotional Stability Results
Gain}\label{results-study-3-a-emotional-stability-results-gain}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-emotional-gain-1.pdf}

}

\caption{\label{fig-results-emotional-gain}Results for emotional
stability gain on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5950}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1322}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0496}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0579}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0661}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0992}}@{}}

\caption{\label{tbl-results-emotional-gain}Table for emotional stability
gain on partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Gain psychopathy emotional stability: partner conflict in relationship &
-0.02 & -0.06 & 0.02 & 1.16 & 1 \\
Gain psychopathy emotional stability: partner relationship satisfaction
& 0.03 & -0.02 & 0.07 & 1.18 & 1 \\
Gain psychopathy emotional stability: partner Kessler 6 distress & -0.01
& -0.05 & 0.03 & 1.09 & 1 \\
Gain psychopathy emotional stability: partner Kessler 6 depression &
0.03 & -0.01 & 0.07 & 1.19 & 1 \\
Gain psychopathy emotional stability: partner Kessler 6 anxiety & -0.03
& -0.07 & 0.01 & 1.18 & 1 \\
Gain psychopathy emotional stability: partner self-esteem & -0.02 &
-0.06 & 0.02 & 1.15 & 1 \\
Gain psychopathy emotional stability: partner pers. wellbeing & 0.00 &
-0.04 & 0.05 & 1.07 & 1 \\
Gain psychopathy emotional stability: partner life satisfaction & 0.00 &
-0.04 & 0.05 & 1.06 & 1 \\

\end{longtable}

For the outcome `Gain psychopathy emotional stability: partner Kessler 6
depression', the ATE causal contrast is 0.029. The E-value for this
outcome is 1.194; The confidence interval ranges from -0.01 to 0.069.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy emotional stability: partner
relationship satisfaction', the ATE causal contrast is 0.027. The
E-value for this outcome is 1.183; The confidence interval ranges from
-0.021 to 0.075. Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy emotional stability: partner pers.
wellbeing', the ATE causal contrast is 0.004. The E-value for this
outcome is 1.066; The confidence interval ranges from -0.038 to 0.047.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy emotional stability: partner life
satisfaction', the ATE causal contrast is 0.003. The E-value for this
outcome is 1.058; The confidence interval ranges from -0.042 to 0.049.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy emotional stability: partner Kessler 6
distress', the ATE causal contrast is -0.007. The E-value for this
outcome is 1.085; The confidence interval ranges from -0.047 to 0.033.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy emotional stability: partner
self-esteem', the ATE causal contrast is -0.019. The E-value for this
outcome is 1.153; The confidence interval ranges from -0.059 to 0.02.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy emotional stability: partner conflict
in relationship', the ATE causal contrast is -0.02. The E-value for this
outcome is 1.157; The confidence interval ranges from -0.064 to 0.024.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy emotional stability: partner Kessler 6
anxiety', the ATE causal contrast is -0.026. The E-value for this
outcome is 1.181; The confidence interval ranges from -0.066 to 0.014.
Overall, we find no reliable evidence for causality.

\subsubsection{Results Study 3 B: Emotional Stability Results
Loss}\label{results-study-3-b-emotional-stability-results-loss}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-emotional-loss-1.pdf}

}

\caption{\label{fig-results-emotional-loss}Results for emotional
stability loss on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5917}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1333}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0500}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0583}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0667}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}@{}}

\caption{\label{tbl-results-emotional-loss}Table for emotional stability
loss on partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Loss psychopathy emotional stability: partner conflict in relationship &
0.04 & -0.01 & 0.08 & 1.22 & 1 \\
Loss psychopathy emotional stability: partner relationship satisfacton &
-0.03 & -0.07 & 0.01 & 1.19 & 1 \\
Loss psychopathy emotional stability: partner Kessler 6 distress & 0.01
& -0.02 & 0.05 & 1.12 & 1 \\
Loss psychopathy emotional stability: partner Kessler 6 depression &
0.00 & -0.03 & 0.04 & 1.06 & 1 \\
Loss psychopathy emotional stability: partner Kessler 6 anxiety & 0.01 &
-0.03 & 0.05 & 1.11 & 1 \\
Loss psychopathy emotional stability: partner self-esteem & 0.00 & -0.04
& 0.03 & 1.04 & 1 \\
Loss psychopathy emotional stability: partner pers. wellbeing & -0.01 &
-0.04 & 0.03 & 1.08 & 1 \\
Loss psychopathy emotional stability: partner life satisfaction & -0.01
& -0.04 & 0.03 & 1.10 & 1 \\

\end{longtable}

Average Treatment Effect (ATE) represents the expected difference in
outcomes between treatment and control groups for the population.

For the outcome `Loss psychopathy emotional stability: partner conflict
in relationship', the ATE causal contrast is 0.036. The E-value for this
outcome is 1.217;The confidence interval ranges from -0.014 to 0.085.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy emotional stability: partner Kessler 6
distress', the ATE causal contrast is 0.014. The E-value for this
outcome is 1.125;The confidence interval ranges from -0.021 to 0.048.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy emotional stability: partner Kessler 6
anxiety', the ATE causal contrast is 0.011. The E-value for this outcome
is 1.108;The confidence interval ranges from -0.027 to 0.048. Overall,
we find no reliable evidence for causality.

For the outcome `Loss psychopathy emotional stability: partner Kessler 6
depression', the ATE causal contrast is 0.004. The E-value for this
outcome is 1.06;The confidence interval ranges from -0.032 to 0.039.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy emotional stability: partner
self-esteem', the ATE causal contrast is -0.002. The E-value for this
outcome is 1.04;The confidence interval ranges from -0.036 to 0.033.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy emotional stability: partner pers.
wellbeing', the ATE causal contrast is -0.007. The E-value for this
outcome is 1.084;The confidence interval ranges from -0.044 to 0.031.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy emotional stability: partner life
satisfaction', the ATE causal contrast is -0.009. The E-value for this
outcome is 1.099;The confidence interval ranges from -0.044 to 0.027.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy emotional stability: partner
relationship satisfacton', the ATE causal contrast is -0.028. The
E-value for this outcome is 1.188;The confidence interval ranges from
-0.068 to 0.013. Overall, we find no reliable evidence for causality

\subsection{Study 4 Narcissism}\label{study-4-narcissism}

\paragraph{Histogram of Exposure}\label{histogram-of-exposure-3}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-histogram-narcissism-1.pdf}

}

\caption{\label{fig-histogram-narcissism}Histogram of exposure variable
(possible response scale = 1-7)}

\end{figure}%

\paragraph{Transition table}\label{transition-table-3}

Table~\ref{tbl-transition-narcissism} shows a transition matrix captures
stability and movement between narcissism responses from the baseline
(NZAVS time 10) wave and exposure wave (NZAVS time 11). Entries on the
diagonal (in bold) indicate the number of individuals who stayed in
their initial state. In contrast, the off-diagonal shows the transitions
from the initial state (bold) to another state the following wave
(off-diagonal). A cell located at the intersection of row \(i\) and
column \(j\), where \(i \neq j\), shows the count of individuals moving
from state \(i\) to state \(j\).

\begin{longtable}[]{@{}ccccccc@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave}\label{tbl-transition-narcissism}\tabularnewline
\toprule\noalign{}
From & State 1 & State 2 & State 3 & State 4 & State 5 & State 6 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & State 1 & State 2 & State 3 & State 4 & State 5 & State 6 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 1 & \textbf{32} & 42 & 3 & 0 & 0 & 0 \\
State 2 & 49 & \textbf{350} & 100 & 12 & 0 & 0 \\
State 3 & 5 & 111 & \textbf{171} & 41 & 3 & 0 \\
State 4 & 0 & 12 & 59 & \textbf{53} & 6 & 0 \\
State 5 & 0 & 0 & 4 & 9 & \textbf{4} & 0 \\
State 6 & 0 & 0 & 0 & 1 & 1 & \textbf{0} \\
\end{longtable}

\subsubsection{Results Study 4 A: Narcissism Results
Gain}\label{results-study-4-a-narcissism-results-gain}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-narcissism-gain-1.pdf}

}

\caption{\label{fig-results-narcissism-gain}Results for Narcissism
stability gain on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5625}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1429}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0536}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0625}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1071}}@{}}

\caption{\label{tbl-results-narcissism-gain}Table for Narcissism gain on
partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Gain psychopathy narcissism: partner conflict in relationship & 0.05 &
-0.02 & 0.12 & 1.27 & 1 \\
Gain psychopathy narcissism: partner relationship satisfaction & -0.02 &
-0.09 & 0.04 & 1.17 & 1 \\
Gain psychopathy narcissism: partner Kessler 6 distress & 0.00 & -0.04 &
0.05 & 1.06 & 1 \\
Gain psychopathy narcissism: partner Kessler 6 depression & 0.01 & -0.04
& 0.05 & 1.10 & 1 \\
Gain psychopathy narcissism: partner Kessler 6 anxiety & 0.00 & -0.05 &
0.04 & 1.03 & 1 \\
Gain psychopathy narcissism: partner self-esteem & 0.03 & -0.01 & 0.07 &
1.18 & 1 \\
Gain psychopathy narcissism: partner pers. wellbeing & 0.03 & -0.02 &
0.07 & 1.18 & 1 \\
Gain psychopathy narcissism: partner life satisfaction & 0.01 & -0.03 &
0.05 & 1.11 & 1 \\

\end{longtable}

For the outcome `Gain psychopathy narcissism: partner conflict in
relationship', the ATE causal contrast is 0.05. The E-value for this
outcome is 1.266;The confidence interval ranges from -0.021 to 0.12.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy narcissism: partner self-esteem', the
ATE causal contrast is 0.027. The E-value for this outcome is 1.184;The
confidence interval ranges from -0.014 to 0.068. Overall, we find no
reliable evidence for causality.

For the outcome `Gain psychopathy narcissism: partner pers. wellbeing',
the ATE causal contrast is 0.025. The E-value for this outcome is
1.176;The confidence interval ranges from -0.019 to 0.069. Overall, we
find no reliable evidence for causality.

For the outcome `Gain psychopathy narcissism: partner life
satisfaction', the ATE causal contrast is 0.01. The E-value for this
outcome is 1.106;The confidence interval ranges from -0.031 to 0.051.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy narcissism: partner Kessler 6
depression', the ATE causal contrast is 0.009. The E-value for this
outcome is 1.097;The confidence interval ranges from -0.035 to 0.053.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy narcissism: partner Kessler 6
distress', the ATE causal contrast is 0.003. The E-value for this
outcome is 1.059;The confidence interval ranges from -0.04 to 0.046.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy narcissism: partner Kessler 6
anxiety', the ATE causal contrast is -0.001. The E-value for this
outcome is 1.03;The confidence interval ranges from -0.045 to 0.044.
Overall, we find no reliable evidence for causality.

For the outcome `Gain psychopathy narcissism: partner relationship
satisfaction', the ATE causal contrast is -0.025. The E-value for this
outcome is 1.175;The confidence interval ranges from -0.089 to 0.04.
Overall, we find no reliable evidence for causality.

\subsubsection{Results Study 4 B: Narcissism Results
Loss}\label{results-study-4-b-narcissism-results-loss}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-narcissism-loss-1.pdf}

}

\caption{\label{fig-results-narcissism-loss}Results for Narcissism loss
on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5586}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1441}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0541}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0631}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0721}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1081}}@{}}

\caption{\label{tbl-results-narcissism-loss}Table for Narcissism loss on
partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Loss psychopathy narcissism: partner conflict in relationship & -0.04 &
-0.10 & 0.03 & 1.22 & 1 \\
Loss psychopathy narcissism: partner relationship satisfacton & 0.00 &
-0.05 & 0.05 & 1.02 & 1 \\
Loss psychopathy narcissism: partner Kessler 6 distress & 0.02 & -0.03 &
0.07 & 1.17 & 1 \\
Loss psychopathy narcissism: partner Kessler 6 depression & 0.01 & -0.03
& 0.06 & 1.11 & 1 \\
Loss psychopathy narcissism: partner Kessler 6 anxiety & 0.04 & -0.02 &
0.09 & 1.22 & 1 \\
Loss psychopathy narcissism: partner self-esteem & -0.01 & -0.05 & 0.03
& 1.10 & 1 \\
Loss psychopathy narcissism: partner pers. wellbeing & -0.01 & -0.05 &
0.03 & 1.11 & 1 \\
Loss psychopathy narcissism: partner life satisfaction & -0.02 & -0.06 &
0.02 & 1.15 & 1 \\

\end{longtable}

For the outcome `Loss psychopathy narcissism: partner Kessler 6
anxiety', the ATE causal contrast is 0.037. The E-value for this outcome
is 1.222;The confidence interval ranges from -0.016 to 0.089. Overall,
we find no reliable evidence for causality.

For the outcome `Loss psychopathy narcissism: partner Kessler 6
distress', the ATE causal contrast is 0.022. The E-value for this
outcome is 1.165;The confidence interval ranges from -0.026 to 0.07.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy narcissism: partner Kessler 6
depression', the ATE causal contrast is 0.011. The E-value for this
outcome is 1.11;The confidence interval ranges from -0.035 to 0.056.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy narcissism: partner relationship
satisfacton', the ATE causal contrast is 0. The E-value for this outcome
is 1.019;The confidence interval ranges from -0.048 to 0.049. Overall,
we find no reliable evidence for causality.

For the outcome `Loss psychopathy narcissism: partner self-esteem', the
ATE causal contrast is -0.01. The E-value for this outcome is 1.105;The
confidence interval ranges from -0.05 to 0.03. Overall, we find no
reliable evidence for causality.

For the outcome `Loss psychopathy narcissism: partner pers. wellbeing',
the ATE causal contrast is -0.011. The E-value for this outcome is
1.11;The confidence interval ranges from -0.053 to 0.031. Overall, we
find no reliable evidence for causality.

For the outcome `Loss psychopathy narcissism: partner life
satisfaction', the ATE causal contrast is -0.018. The E-value for this
outcome is 1.147;The confidence interval ranges from -0.061 to 0.024.
Overall, we find no reliable evidence for causality.

For the outcome `Loss psychopathy narcissism: partner conflict in a
relationship', the ATE causal contrast is -0.036. The E-value for this
outcome is 1.22;The confidence interval ranges from -0.1 to 0.027.
Overall, we find no reliable evidence for causality.

\subsection{Study 5: Psychopathy Combined
Score}\label{study-5-psychopathy-combined-score}

\paragraph{Histogram of Exposure}\label{histogram-of-exposure-4}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-histogram-psychopathy-1.pdf}

}

\caption{\label{fig-histogram-psychopathy}Histogram of exposure variable
(possible response scale = 1-7)}

\end{figure}%

\paragraph{Transition table}\label{transition-table-4}

\begin{longtable}[]{@{}ccccc@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave}\label{tbl-transition-psychopathy}\tabularnewline
\toprule\noalign{}
From & State 2 & State 3 & State 4 & State 5 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & State 2 & State 3 & State 4 & State 5 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 2 & \textbf{4} & 6 & 1 & 0 \\
State 3 & 1 & \textbf{338} & 107 & 0 \\
State 4 & 0 & 144 & \textbf{455} & 3 \\
State 5 & 0 & 0 & 10 & \textbf{1} \\
\end{longtable}

Table~\ref{tbl-transition-psychopathy} shows a transition matrix
captures stability and movement between psychopathy combined-score
responses from the baseline (NZAVS time 10) wave and exposure wave
(NZAVS time 11). Entries on the diagonal (in bold) indicate the number
of individuals who stayed in their initial state. In contrast, the
off-diagonal shows the transitions from the initial state (bold) to
another state the following wave (off diagonal). A cell located at the
intersection of row \(i\) and column \(j\), where \(i \neq j\), shows
the count of individuals moving from state \(i\) to state \(j\).

\subsubsection{Results Study 5 A: Psychopathy Combined Measure
Gain}\label{results-study-5-a-psychopathy-combined-measure-gain}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-psychopathy-gain-1.pdf}

}

\caption{\label{fig-results-psychopathy-gain}Results for Narcissism
stability gain on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5149}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1584}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0594}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0693}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0792}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1188}}@{}}

\caption{\label{tbl-results-psychopathy-gain}Table for Psychopathy gain
on partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Gain psychopathy: partner conflict in relationship & 0.01 & -0.05 & 0.07
& 1.11 & 1.00 \\
Gain psychopathy: partner relationship satisfaction & 0.00 & -0.06 &
0.06 & 1.04 & 1.00 \\
Gain psychopathy: partner Kessler 6 distress & 0.09 & 0.04 & 0.15 & 1.40
& 1.24 \\
Gain psychopathy: partner Kessler 6 depression & 0.10 & 0.05 & 0.15 &
1.43 & 1.27 \\
Gain psychopathy: partner Kessler 6 anxiety & 0.07 & 0.02 & 0.11 & 1.32
& 1.16 \\
Gain psychopathy: partner self-esteem & -0.01 & -0.06 & 0.05 & 1.08 &
1.00 \\
Gain psychopathy: partner pers. wellbeing & -0.02 & -0.07 & 0.03 & 1.15
& 1.00 \\
Gain psychopathy: partner life satisfaction & 0.02 & -0.03 & 0.06 & 1.15
& 1.00 \\

\end{longtable}

Average Treatment Effect (ATE) represents the expected difference in
outcomes between treatment and control groups for the population.

For the outcome `Gain psychopathy: partner Kessler 6 depression', the
ATE causal contrast is 0.106. The E-value for this outcome is 1.434;The
confidence interval ranges from 0.053 to 0.158. Overall, we find
reliable evidence for causality.

For the outcome `Gain psychopathy: partner Kessler 6 distress', the ATE
causal contrast is 0.088. The E-value for this outcome is 1.385;The
confidence interval ranges from 0.036 to 0.14. Overall, we find reliable
evidence for causality.

For the outcome `Gain psychopathy: partner Kessler 6 anxiety', the ATE
causal contrast is 0.074. The E-value for this outcome is 1.341;The
confidence interval ranges from 0.024 to 0.123. Overall, we find
reliable evidence for causality.

For the outcome `Gain psychopathy: partner life satisfaction', the ATE
causal contrast is 0.018. The E-value for this outcome is 1.146;The
confidence interval ranges from -0.029 to 0.064. Overall, we find no
reliable evidence for causality.

For the outcome `Gain psychopathy: partner conflict in relationship',
the ATE causal contrast is 0.003. The E-value for this outcome is
1.055;The confidence interval ranges from -0.061 to 0.067. Overall, we
find no reliable evidence for causality.

For the outcome `Gain psychopathy: partner self-esteem', the ATE causal
contrast is 0.003. The E-value for this outcome is 1.052;The confidence
interval ranges from -0.046 to 0.051. Overall, we find no reliable
evidence for causality.

For the outcome `Gain psychopathy: partner relationship satisfaction',
the ATE causal contrast is -0.011. The E-value for this outcome is
1.112;The confidence interval ranges from -0.073 to 0.05. Overall, we
find no reliable evidence for causality.

For the outcome `Gain psychopathy: partner pers. wellbeing', the ATE
causal contrast is -0.024. The E-value for this outcome is 1.171;The
confidence interval ranges from -0.075 to 0.028. Overall, we find no
reliable evidence for causality.

\subsubsection{Results Study 5 B: Psychopathy Combined Score Results
Loss}\label{results-study-5-b-psychopathy-combined-score-results-loss}

\begin{figure}

\centering{

\includegraphics{24-manuscript-aaron-psychopathy_files/figure-pdf/fig-results-psychopathy-loss-1.pdf}

}

\caption{\label{fig-results-psychopathy-loss}Results for Psychopathy
loss on partner multi-dimensional well-being: z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5100}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1600}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0600}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0700}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0800}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1200}}@{}}

\caption{\label{tbl-results-psychopathy-loss}Table for Psychopathy loss
on partner multi-dimensional well-being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Loss psychopathy: partner conflict in relationship & -0.05 & -0.12 &
0.02 & 1.26 & 1 \\
Loss psychopathy: partner relationship satisfacton & -0.02 & -0.08 &
0.05 & 1.15 & 1 \\
Loss psychopathy: partner Kessler 6 distress & 0.00 & -0.05 & 0.04 &
1.07 & 1 \\
Loss psychopathy: partner Kessler 6 depression & -0.02 & -0.07 & 0.03 &
1.16 & 1 \\
Loss psychopathy: partner Kessler 6 anxiety & 0.01 & -0.03 & 0.06 & 1.13
& 1 \\
Loss psychopathy: partner self-esteem & 0.01 & -0.04 & 0.05 & 1.09 &
1 \\
Loss psychopathy: partner pers. wellbeing & -0.01 & -0.06 & 0.04 & 1.12
& 1 \\
Loss psychopathy: partner life satisfaction & -0.03 & -0.08 & 0.02 &
1.20 & 1 \\

\end{longtable}

For the outcome `Loss psychopathy: partner Kessler 6 anxiety', the ATE
causal contrast is 0.008. The E-value for this outcome is 1.093;The
confidence interval ranges from -0.043 to 0.059. Overall, we find no
reliable evidence for causality.

For the outcome `Loss psychopathy: partner Kessler 6 distress', the ATE
causal contrast is 0.002. The E-value for this outcome is 1.046;The
confidence interval ranges from -0.047 to 0.051. Overall, we find no
reliable evidence for causality.

For the outcome `Loss psychopathy: partner self-esteem', the ATE causal
contrast is 0. The E-value for this outcome is 1.019;The confidence
interval ranges from -0.045 to 0.044. Overall, we find no reliable
evidence for causality.

For the outcome `Loss psychopathy: partner pers. wellbeing', the ATE
causal contrast is -0.011. The E-value for this outcome is 1.113;The
confidence interval ranges from -0.06 to 0.037. Overall, we find no
reliable evidence for causality.

For the outcome `Loss psychopathy: partner Kessler 6 depression', the
ATE causal contrast is -0.025. The E-value for this outcome is 1.175;The
confidence interval ranges from -0.073 to 0.024. Overall, we find no
reliable evidence for causality.

For the outcome `Loss psychopathy: partner life satisfaction', the ATE
causal contrast is -0.038. The E-value for this outcome is 1.225;The
confidence interval ranges from -0.087 to 0.011. Overall, we find no
reliable evidence for causality.

For the outcome `Loss psychopathy: partner relationship satisfaction',
the ATE causal contrast is -0.039. The E-value for this outcome is
1.229;The confidence interval ranges from -0.104 to 0.027. Overall, we
find no reliable evidence for causality.

For the outcome `Loss psychopathy: partner conflict in relationship',
the ATE causal contrast is -0.039. The E-value for this outcome is
1.231;The confidence interval ranges from -0.118 to 0.039. Overall, we
find no reliable evidence for causality.

\subsection{Discussion}\label{discussion}

We observe that gains and losses in psychopathy traits differently
affect partner well-being and relationship dynamics.

When focussing on the effects of individual psychopathy traits, the
results indicate that individual psychopathy traits, by themselves, do
not reliably affect partner well-being in a measurable manner.

An exception to this pattern is the trait of antagonism. An increase in
antagonism decreases partner life satisfaction and an increases
perceived relationship conflict. This suggests that antagonism, among
the various facets of psychopathy, has a uniquely adverse effect on
relationship dynamics, exacerbating conflict and diminishing partner
satisfaction.

Notably a reduction in antagonism did not exert a corresponding
reduction in perceived relationship conflict or an increase in life
satisfaction. Speculating, perhaps habituation plays a role. The finding
that individual features of psychopathy affect outcomes differently is
notably consistent with Eisenbarth \emph{et al.}
(\citeproc{ref-eisenbarth2022aspects}{2022}).

However, our findings also reveal that the whole of psychopathy is
greater -- and different in its causal effects on well-being -- than the
sum of its parts. An increase in the composite measure of psychopathy
reliably increases partner distress, as shown by the gains in
psychopathy showing a marked increase in Kessler 6 depression and
anxiety (as well as the composite score). This effect is absent when
psychopathy traits decrease, suggesting that the presence or
augmentation of such traits has a more pronounced negative impact on
partner well-being than their reduction, speculating again, perhaps from
habituation. The effects are present in embodied features of well-being
-- anxiety and depression -- but not in higher-order reflective
concepts, such as life satisfaction and relationship conflict. Thus the
effects we obtain for antagonism are obscured by the movement of the
composite trait, and new effects are evident.

The discovery that compound effects of these psychopathy affect
`embodied' well-being, more than higher-order reflective dimensions has
clinical importance and merits future research.

Future research should explore using more objective measures for the
questions raised in this study. Self-reports introduce possibilities for
both systematic and random measurement errors. True effect sizes may
differ from those estimated. They might be larger or smaller, than those
we observe. We therefore advise caution when interpreting these findings
which are preliminary and exploratory.

Finally, we caution against generalising findings outside the New
Zealand population from which the data were sourced. Although our study
consists of a random probability sample of couples in New Zealand who
participated in the New Zealand Attitudes and Values Study in two waves
(time 10 and time 11) -- couples that were not recruited as couples --we
cannot extrapolate to different populations or sociocultural settings.
This limitation merits future comparative research.

Despite these limitations, we believe our study demonstrates the
interest and power of combining longitudinal data with methods for
causal inference to address causal questions inaccessible to experiments
that lie at the heart of our interest in the statistical associations we
find in observational data. We hope this work will inspire psychological
scientists to embrace these tools and approaches more broadly, pushing
the boundaries of what we can discover about human behaviour and
relationships from observational studies.

\newpage{}

\subsubsection{Ethics}\label{ethics}

The NZAVS is reviewed every three years by the University of Auckland
Human Participants Ethics Committee. Our most recent ethics approval
statement is as follows: The New Zealand Attitudes and Values Study was
approved by the University of Auckland Human Participants Ethics
Committee on 26/05/2021 for six years until 26/05/2027, Reference Number
UAHPEC22576.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the TempletoReligion Trust (TRT0196; TRT0418). JB received support from
the Max Planck Institute for the Science of Human History. The funders
had no role in preparing the manuscript or the decision to publish.

\subsubsection{Author Statement}\label{author-statement}

TBA\ldots{} e.g.~

\begin{itemize}
\tightlist
\item
  AH conceived of the study, led the validation study, and developed the
  theory
\item
  HE \ldots{} MH \ldots contributed to the theory.
\item
  CS led data collection.
\item
  JB developed the inferential approach and did the analysis.\\
\item
  All authors contributed to writing the final version of the
  manuscript, which was substantially AH's work.
\end{itemize}

\newpage{}

\subsection{References}\label{references}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, J (2024) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-eisenbarth2022aspects}
Eisenbarth, H, Hart, CM, Zubielevitch, E, \ldots{} Sedikides, C (2022)
Aspects of psychopathic personality relate to lower subjective and
objective professional success. \emph{Personality and Individual
Differences}, \textbf{186}, 111340.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a new zealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-hernan2023}
Hernan, MA, and Robins, JM (2023) \emph{Causal inference}, Taylor \&
Francis. Retrieved from
\url{https://books.google.co.nz/books?id=/_KnHIAAACAAJ}

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-SuperLearner2023}
Polley, E, LeDell, E, Kennedy, C, and van der Laan, M (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://github.com/ecpolley/SuperLearner}

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vanderlaan2011}
Van Der Laan, MJ, and Rose, S (2011) \emph{Targeted Learning: Causal
Inference for Observational and Experimental Data}, New York, NY:
Springer. Retrieved from
\url{https://link.springer.com/10.1007/978-1-4419-9782-1}

\bibitem[\citeproctext]{ref-vanderlaan2018}
Van Der Laan, MJ, and Rose, S (2018) \emph{Targeted Learning in Data
Science: Causal Inference for Complex Longitudinal Studies}, Cham:
Springer International Publishing. Retrieved from
\url{http://link.springer.com/10.1007/978-3-319-65304-4}

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the e-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 120.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437466.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{Lmtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\end{CSLReferences}

\newpage{}

\subsection{Appendix A: Measurues}\label{appendix-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' age in an open-ended question (``What is your
age?'' or ``What is your date of birth'').

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

Participants were asked ``What is your highest level of
qualification?''. We coded participans highest finished degree according
to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG
codes (with overseas school quals coded as Level 3, and all other
ancillary categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Ethnicity (waves: 3)}\label{ethnicity-waves-3}

Based on the New Zealand Census, we asked participants ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Gender (waves: 1-15)}\label{gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked ``Please estimate your total household income
(before tax) for the year XXXX''. To stablise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Parent (waves: 5-15)
--\textgreater{}}\label{parent-waves-5-15}

Participants were asked ``If you are a parent, what is the birth date of
your eldest child?'' or ``If you are a parent, in which year was your
eldest child born?'' (waves: 10-15). Parents were coded as 1, while the
others were coded as 0. --\textgreater{}

\paragraph{Political Orientation}\label{political-orientation}

We measured participants' political orientation using a single item
adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{NZSEI-13 (waves: 8-15)}\label{nzsei-13-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017}). This index uses the income, age, and education of
a reference group, in this case, the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

Participants were asked ``If you are a parent, what is the birth date of
your eldest child?''.

\paragraph{Living with Partner}\label{living-with-partner}

Participants were asekd ``Do you live with your partner?'' (1 = Yes, 0 =
No).

\paragraph{Living in an Urban Area (waves:
1-15)}\label{living-in-an-urban-area-waves-1-15}

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.8043}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1957}}@{}}
\caption{Baseline demography
statistics}\label{tbl-table-demography}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{N = 1,070}
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{N = 1,070}
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & 55 (45, 61) \\
\textbf{Education Level Coarsen} & NA \\
1 & 15 (1.4\%) \\
2 & 306 (29\%) \\
3 & 125 (12\%) \\
4 & 304 (29\%) \\
5 & 138 (13\%) \\
6 & 129 (12\%) \\
7 & 46 (4.3\%) \\
\textbf{Eth Cat} & NA \\
1 & 922 (86\%) \\
2 & 78 (7.3\%) \\
3 & 25 (2.3\%) \\
4 & 41 (3.8\%) \\
\textbf{Hours Housework log} & 2.20 (1.61, 2.71) \\
\textbf{Hours Work log} & 3.58 (1.95, 3.78) \\
\textbf{Kessler Latent Anxiety} & 1.00 (0.67, 1.67) \\
\textbf{Kessler Latent Depression} & 0.33 (0.00, 0.67) \\
\textbf{Kessler6 Sum} & 4 (2, 7) \\
\textbf{Male} & 552 (52\%) \\
\textbf{Nz Dep2018} & 4.00 (2.00, 6.00) \\
\textbf{How many children have you given birth to, fathered, and/or
parented?} & 813 (76\%) \\
\textbf{Political Conservative} & NA \\
1 & 63 (6.2\%) \\
2 & 251 (25\%) \\
3 & 238 (23\%) \\
4 & 233 (23\%) \\
5 & 146 (14\%) \\
6 & 73 (7.1\%) \\
7 & 19 (1.9\%) \\
\textbf{Religion Church Coarsen} & NA \\
zero & 866 (83\%) \\
one & 29 (2.8\%) \\
less\_four & 56 (5.3\%) \\
four\_up & 98 (9.3\%) \\
\textbf{Urban} & 867 (81\%) \\
\end{longtable}

Table~\ref{tbl-table-demography} presents baseline demographic
statistics for couples who met inclusion criteria.

\subsection{Appendix C: Baseline and Treatment Wave Exposure
Statistics}\label{appendix-exposures}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4366}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2817}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2817}}@{}}
\caption{Baseline demography
statistics}\label{tbl-table-demography}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,070
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 1,070
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,070
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 1,070
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Aaron Antagonism} & 4.33 (4.00, 4.67) & 4.33 (3.88, 4.67) \\
Unknown & 0 & 0 \\
\textbf{Aaron Disinhibition} & 2.17 (1.67, 2.83) & 2.17 (1.67, 2.67) \\
Unknown & 0 & 0 \\
\textbf{Aaron Emotional Stability} & 5.17 (4.40, 5.83) & 5.17 (4.50,
5.83) \\
Unknown & 0 & 0 \\
\textbf{Aaron Narcissism} & 2.50 (2.00, 3.00) & 2.50 (2.00, 3.00) \\
Unknown & 0 & 1 \\
\textbf{Aaron Psychopathy Combined} & 3.54 (3.29, 3.79) & 3.50 (3.29,
3.75) \\
Unknown & 0 & 0 \\
\textbf{Alert Level Combined} & NA & NA \\
no\_alert & 1,070 (100\%) & 831 (78\%) \\
early\_covid & 0 (0\%) & 88 (8.2\%) \\
alert\_level\_1 & 0 (0\%) & 72 (6.7\%) \\
alert\_level\_2 & 0 (0\%) & 27 (2.5\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 16 (1.5\%) \\
alert\_level\_4 & 0 (0\%) & 36 (3.4\%) \\
Unknown & 0 & 0 \\
\end{longtable}

Table~\ref{tbl-table-exposures} presents baseline and wave 1 statistics
for the exposure variables. Because the exposure wave occurred to New
Zealand's COVID-19 pandemic, we all models adjusted for the pandemic
alert-level. The pandemic is a not a confounder because a confounder
must be related to both the treatment and the outcome. At the end of
study measurement, all had be exposed to the pandemic. However, to
satisfy the causal consistency assumption, all treatments must be
conditionally equivalent within levels of all covariates
(\citeproc{ref-vanderweele2013}{VanderWeele and Hernan 2013}). To better
ensure validation of this assumption we therefore included the lead
value of covid-alert level in all models.

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4366}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2817}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2817}}@{}}
\caption{Baseline demography
statistics}\label{tbl-table-exposures}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,070
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 1,070
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,070
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 1,070
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Aaron Antagonism} & 4.33 (4.00, 4.67) & 4.33 (3.88, 4.67) \\
Unknown & 0 & 0 \\
\textbf{Aaron Disinhibition} & 2.17 (1.67, 2.83) & 2.17 (1.67, 2.67) \\
Unknown & 0 & 0 \\
\textbf{Aaron Emotional Stability} & 5.17 (4.40, 5.83) & 5.17 (4.50,
5.83) \\
Unknown & 0 & 0 \\
\textbf{Aaron Narcissism} & 2.50 (2.00, 3.00) & 2.50 (2.00, 3.00) \\
Unknown & 0 & 1 \\
\textbf{Aaron Psychopathy Combined} & 3.54 (3.29, 3.79) & 3.50 (3.29,
3.75) \\
Unknown & 0 & 0 \\
\textbf{Alert Level Combined} & NA & NA \\
no\_alert & 1,070 (100\%) & 831 (78\%) \\
early\_covid & 0 (0\%) & 88 (8.2\%) \\
alert\_level\_1 & 0 (0\%) & 72 (6.7\%) \\
alert\_level\_2 & 0 (0\%) & 27 (2.5\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 16 (1.5\%) \\
alert\_level\_4 & 0 (0\%) & 36 (3.4\%) \\
Unknown & 0 & 0 \\
\end{longtable}

Table~\ref{tbl-table-exposures} presents baseline and wave 1 statistics
for the exposure variables. Because the exposure wave occurred during
New Zealand's COVID-19 pandemic, all models adjusted for the pandemic
alert level. The pandemic is not a confounder because a confounder must
be related to both the treatment and the outcome. At the end of the
study measurement, all had been exposed to the pandemic. However, to
satisfy the causal consistency assumption, all treatments must be
conditionally equivalent within levels of all covariates
(\citeproc{ref-vanderweele2013}{VanderWeele and Hernan 2013}). To better
ensure validation of this assumption, we included the lead value of the
covid-alert level in all models.



\end{document}
