% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal Effects of Religious Service Attendance on Prosocial Behaviour: Evidence from a Longitudinal Study in New Zealand.},
  pdfauthor={Joseph A. Bulbulia; Don E Davis; Kenneth G. Rice; Chris G. Sibley; Geoffrey Troughton},
  pdfkeywords={Use, use},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal Effects of Religious Service Attendance on Prosocial
Behaviour: Evidence from a Longitudinal Study in New Zealand.}

\usepackage{academicons}
\usepackage{xcolor}

  \author{Joseph A. Bulbulia}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5861-2056 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Don E Davis}
            \affil{%
             \small{     Georgia State University, Matheny Center for
the Study of Stress, Trauma, and Resilience
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0003-3169-6576 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Kenneth G. Rice}
            \affil{%
             \small{     Georgia State University, Matheny Center for
the Study of Stress, Trauma, and Resilience
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-0558-2818 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Chris G. Sibley}
            \affil{%
             \small{     School of Psychology, University of Auckland
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-4064-8800 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Geoffrey Troughton}
            \affil{%
             \small{     School of Social and Cultural Studies, Victoria
University of Wellington
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0001-7423-0640 }
              }
      


\date{2024-10-11}
\begin{document}
\maketitle
\begin{abstract}
We investigate the causal effects of religious service attendance on
prosocial behaviours, using longitudinal data from a nationally
representative sample of 33,198 New Zealanders collected between 2018
and 2021. Our study departs from traditional approaches in three ways:
(1) we utilise longitudinal data rather than relying exclusively on
cross-sectional data; (2) we supplement self-reported measures of giving
with measures of help received; and (3) our statistical models are
designed to address causal questions rather than merely describe change
over time. We model causal contrasts for three types of hypothetical
interventions --- increasing, decreasing, or maintaining religious
service attendance --- and assess their effects on eight distinct
prosocial domains.

Study 1 focuses on self-reported charitable donations and volunteering.
Studies 2 and 3 examine receiving help---both personal and
financial---from family, friends, and the wider community, which are
novel measures of prosociality not previously used in this context.
Across all analyses, we find that the causal effects of religious
attendance are notably smaller than cross-sectional associations
typically suggest. However, a modest increase in regular attendance
would nevertheless result in charitable donations equivalent to
approximately 4\% of the New Zealand Government's annual spending,
revealing a significant public benefit.

Overall, these findings underscore the importance of precise causal
analyses for clarifying the social functions of religious participation
in a manner relevant to inform public policy. By employing robust causal
inference techniques, our research advances a methodological framework
for studying cultural practices and their social consequences.

\textbf{KEYWORDS}: \emph{Causal Inference}; \emph{Charity};
\emph{Church}; \emph{Cooperation}; \emph{Cross-validation};
\emph{Longitudinal}; \emph{Machine Learning}; \emph{Religion};
\emph{Semi-parametric}; \emph{SWIGs}; \emph{Targeted Learning};
\emph{TMLE}; \emph{Volunteering}.
\end{abstract}

\subsection{Introduction}\label{introduction}

A central question in the scientific study of religion is whether
religion fosters prosociality (\citeproc{ref-decoulanges1903}{De
Coulanges 1903}; \citeproc{ref-johnson2005}{Johnson 2005};
\citeproc{ref-norenzayan2016}{Norenzayan \emph{et al.} 2016};
\citeproc{ref-schloss2011evolutionary}{Schloss and Murray 2011};
\citeproc{ref-sosis2003cooperation}{Sosis and Bressler 2003};
\citeproc{ref-swanson1967}{Swanson 1967}; \citeproc{ref-watts2015}{Watts
\emph{et al.} 2015}; \citeproc{ref-watts2016}{Watts \emph{et al.} 2016};
\citeproc{ref-wheatley1971}{Wheatley 1971};
\citeproc{ref-whitehouse2023}{Whitehouse \emph{et al.} 2023}). However,
quantifying causal effects for religion presents significant challenges
(\citeproc{ref-major2023exploring}{Major-Smith 2023}). Investigators
have limited scope to randomise supernatural beliefs, community worship,
and personal prayer. On the other hand, valid causal inferences from
non-experimental, ``real world'' data must combine high-resolution
repeated-measures time-series data with robust methods for causal
inference. Few studies meet this standard. A recent survey of the
religion and prosociality literature reveals that nearly all
non-experimental studies assessing links between prosociality and
religion, including several longitudinal studies, are associational
Kelly \emph{et al.} (\citeproc{ref-kelly2024religiosity}{2024}).
Presently, studies using longitudinal (panel) data have yet to
appropriately leverage their repeated measures to obtain reliable causal
inferences.

Here, to obtain causal inferences from time-series data, we leverage
comprehensive panel data from 33,198 participants in the New Zealand
Attitudes and Values Study from 2018-2021 and quantify the effects of
clearly defined interventions in religious attendance across the
population of New Zealanders assessed on eight outcome domains of
charitable financial donations and volunteering. We obtain causal
inferences by contrasting inferred population averages under different
modified treatment policies (\citeproc{ref-duxedaz2021}{Díaz \emph{et
al.} 2021}, \citeproc{ref-diaz2023lmtp}{2023};
\citeproc{ref-haneuse2013estimation}{Haneuse and Rotnitzky 2013};
\citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023}).

Our initial causal contrast investigates: ``What would be the average
difference across the New Zealand population if everyone attended
religious services regularly (at least four times per month) versus if
no one attended?'' This theoretical question simulates a hypothetical
experiment with random assignment to regular or non-attendance. This
contrast addresses the scientifically interesting all/none contrast that
is common in experimental designs (\citeproc{ref-hernuxe1n2016}{Hernán
\emph{et al.} 2016}).

A second causal contrast investigates: ``What would be the average
difference across the New Zealand population if everyone attended
religious services regularly compared with maintaining the status quo?''
Here, we contrast regular religious service and New Zealand society as
it was at the end of the study (2021) without modification. This causal
contrast may inform practical policies relevant to non-regular attendees
who might start.

Our third causal contrast examines: ``What would be the average
difference across the New Zealand population if no one attended
religious services compared with the status quo?'' Here, we contrast the
loss of any religious service with New Zealand society as it was at the
end of the study (2021), again without modification. This causal
contrast may inform practical policies relevant to regular attendees who
stop attending.

Although the set of causal contrasts analysts might consider is
unbounded, those we have selected address these specific scientific and
policy interests.

Note that our approach does not focus on testing specific hypotheses;
instead, we aim to compute our pre-specified causal contrasts accurately
and consistently (\citeproc{ref-hernan2024stating}{Hernán and Greenland
2024}).

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

We collected data from the New Zealand Attitudes and Values Study
(NZAVS), an annual longitudinal national probability panel assessing
social attitudes, personality, ideology, and health outcomes among New
Zealand residents. The panel started in 2009, the NZAVS has expanded to
include over fifty researchers and has gathered responses from 72,910
participants to date. The study operates independently of political or
corporate funding and is based in a university setting. Data summaries
for all measures used in this study are provided in \textbf{Appendices
B-D}. For more information about the NZAVS, see:
\href{https://doi.org/10.17605/OSF.IO/75SNB}{OSF.IO/75SNB}

\subsubsection{Treatment Indicator}\label{treatment-indicator}

We assessed religious service attendance using the question:

\begin{verbatim}
-   *Do you identify with a religion and/or spiritual group? If yes, how many times did you attend a church or place of worship during the last month?*
\end{verbatim}

Responses were rounded to the nearest whole number. Because few
participants reported attending more than eight times, we capped
responses above eight at eight (see Appendix B, variable
\texttt{religion\_church\_round}). In the regular church service
condition, we did not intervene on responses greater than four to reduce
computational burden during estimation.

\subsubsection{Measures of Prosociality}\label{measures-of-prosociality}

We assessed prosocial behaviour using the following measures:

\textbf{Study 1: Self-Reported Charity}

Participants reported:

\begin{verbatim}
•   Volunteering: *"Please estimate how many hours you spent doing each of the following things last week…Volunteer/charitable work."*
•   Annual Charitable Financial Donations: *"How much money have you donated to charity in the last year?"*
\end{verbatim}

\textbf{Study 2: Help received from others in the last week: \emph{time}
}

Participants estimated the amount of help they received in the past week
in hours from:

\begin{itemize}
\tightlist
\item
  \emph{Family\ldots TIME (hours)}
\item
  \emph{Friends\ldots TIME (hours)}
\item
  \emph{Community\ldots TIME (hours)}
\end{itemize}

Due to high variability, we transformed responses into binary
indicators: 0 = none; 1 = any.

\textbf{Study 3: Help received from others in the last week:
\emph{money} }

Similarly, participants were asked:

Participants estimated the monetary help they received in the past week
from:

\begin{itemize}
\tightlist
\item
  \emph{Family\ldots MONEY (dollars)}
\item
  \emph{Friends\ldots MONEY (dollars)}
\item
  \emph{Community\ldots MONEY (dollars)}
\end{itemize}

Again, due to high variability, responses were converted to binary
indicators: 0 = none; 1 = any.

Studies 2 and 3 employed revealed measures of prosocial exposure to
minimise self-presentation bias. We assumed that if religious
institutions foster prosociality, initiation into regular
attendance---controlling for past attendance, baseline prosocial
measures, and a range of demographic, personality, and health
factors---would increase exposure to prosocial behaviours. By focusing
on help received, these measures are less susceptible to
self-presentation biases that could otherwise confound associations
between religious attendance and prosocial indicators. Including
baseline outcomes and treatments in our analyses mitigates the threat of
undirected correlated errors.

Comprehensive details of all measures are provided in \textbf{Appendix
A}.

\subsubsection{Causal Interventions}\label{causal-interventions}

We defined three targeted causal contrasts based on prespecified
modified treatment policies:

\begin{verbatim}
1.  Regular Religious Service Treatment: Simulating a scenario where everyone attends religious services regularly. For individuals attending less than four times per month, their attendance was shifted to four; those already attending four or more times per month remained unchanged.
2.  Zero Religious Service Treatment: Simulating a scenario where no one attends religious services. For individuals attending more than zero times per month, their attendance was shifted to zero; those already not attending remained unchanged.
3.  Status Quo—No Treatment: Using each individual’s observed level of religious service attendance without any modification.
\end{verbatim}

\subsubsection{Causal Contrasts}\label{causal-contrasts}

Based on these policies, we computed three causal contrasts:

\begin{verbatim}
1.  Regular vs. Zero Attendance: Comparing average prosocial outcomes in a society where everyone attends religious services regularly to one where no one attends. This simulates a hypothetical experiment where individuals are randomised to either regular attendance or no attendance, allowing us to assess differences in prosociality one year after the intervention.
2.  Regular Attendance vs. Status Quo: Comparing a society where everyone attends religious services regularly to the current state. This contrast examines the potential effect of transitioning non-regular attendees to regular attendance.
3.  Zero Attendance vs. Status Quo: Comparing a society where no one attends religious services to the current state. This contrast examines the potential impact of eliminating religious service attendance entirely.
\end{verbatim}

\subsubsection{Identification
Assumptions}\label{identification-assumptions}

To consistently estimate a causal effect, investigators must satisfy
three assumptions (refer to Bulbulia
(\citeproc{ref-bulbulia2023}{2024c})):

\begin{verbatim}
1.  Causal Consistency: Potential outcomes correspond to the observed outcomes under the treatments in our data. We assume that, conditional on measured covariates, potential outcomes do not depend on how the treatment was administered [@vanderweele2009; @vanderweele2013].
2.  Conditional Exchangeability: Given observed covariates, treatment assignment is independent of the potential outcomes being compared (no unmeasured confounding) [@hernan2024WHATIF; @chatton2020].
3.  Positivity: Every individual has a non-zero probability of receiving each treatment level, regardless of their covariate values. We evaluated this by examining changes in religious service attendance from baseline to the treatment wave [@westreich2010].
\end{verbatim}

\subsubsection{Target Population}\label{target-population}

Our target population comprises New Zealand residents represented in the
baseline wave of the NZAVS during 2018--2019, weighted by New Zealand
Census data for age, gender, and ethnicity
(\citeproc{ref-sibley2021}{Sibley 2021}). While the NZAVS is a national
probability study designed to reflect the broader New Zealand
population, it tends to under-sample males and individuals of Asian
descent, and over-sample females and Māori (the indigenous people of New
Zealand). To address these disparities and enhance the accuracy of our
findings, we applied survey weights adjusting for age, gender, and
ethnicity. Survey weights were integrated into our statistical models
using the weights option in \texttt{lmtp}
(\citeproc{ref-williams2021}{Williams and Díaz 2021}), following
established protocols (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia
2024a}).

\subsubsection{Eligibility Criteria}\label{eligibility-criteria}

Participants were included in the analysis if they:

\begin{verbatim}
•   Were enrolled in the 2018 wave of the NZAVS (Time 10).
•   Provided responses to the religious service attendance question at both Time 10 (baseline) and Time 11 (treatment wave).
\end{verbatim}

Participants with missing covariate data at baseline were included, with
missing data imputed using information available at baseline.
Participants may have been lost to follow-up by the end of the study
(Time 12); we adjusted for attrition and non-response using censoring
weights, as described below.

A total of 33,198 individuals met these criteria and were included in
the study.

\subsubsection{Missing Data}\label{missing-data}

To address missing data:

\begin{verbatim}
*   Baseline Missingness: We used the predictive mean matching algorithm from the mice package in R [@vanbuuren2018] to impute missing baseline data (<2% of covariate values). We performed single imputation, using only baseline data for imputation [@zhang2023shouldMultipleImputation].
*   Outcome Missingness: To account for confounding and selection bias from missing responses and panel attrition, we applied censoring weights obtained using nonparametric machine learning ensembles via the lmtp package in R [@williams2021].
\end{verbatim}

\subsubsection{Confounding Control}\label{confounding-control}

To address confounding, we followed the modified disjunctive cause
criterion (\citeproc{ref-vanderweele2019}{VanderWeele 2019}), which
involved:

\begin{verbatim}
1.  Identifying all common causes of both the treatment and outcomes.
2.  Excluding instrumental variables that affect the exposure but not the outcome.
3.  Including proxies for unmeasured confounders affecting both exposure and outcome.
4.  Controlling for baseline exposure and baseline outcome, serving as proxies for unmeasured common causes [@vanderweele2020].
\end{verbatim}

The covariates included for confounding control are detailed in
\hyperref[appendix-demographics]{Appendix B} These methods adhere to the
guidelines provided in (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia
2024a}) and were pre-specified in our study protocol
\url{https://osf.io/ce4t9/}. Table~\ref{tbl-02} presents a causal
diagramme of our identification strategy.

\begin{table}

\caption{\label{tbl-02}This table presents three Single World
Intervention Graphs (SWIGs), one for each treatment condition we
compare, refer to (\citeproc{ref-richardson2013}{Richardson and Robins
2013a}).}

\centering{

\lmtptablethree

}

\end{table}%

Table~\ref{tbl-02} presents three Single World Intervention Graphs
(SWIGs) that describe our identification strategy. We follow
(\citeproc{ref-richardson2013}{Richardson and Robins 2013a})'s
convention for explicitly representing a conditional treatment
intervention using Single World Intervention Graphs (SWIGs). Refer to
(\citeproc{ref-richardson2013}{Richardson and Robins 2013a};
\citeproc{ref-richardson2013swigsprimer}{Richardson and Robins 2013b},
\citeproc{ref-richardson2023potential}{2023},
\citeproc{ref-richardson2023potential}{2023};
\citeproc{ref-robins2010alternative}{Robins and Richardson 2010};
\citeproc{ref-shpitser2016causal}{Shpitser and Tchetgen 2016}). On
modified treatment policies refer to
(\citeproc{ref-bulbulia2024swigstime}{Bulbulia 2024d};
\citeproc{ref-diaz2021nonparametric}{Dı́az \emph{et al.} 2021};
\citeproc{ref-diaz2012population}{Muñoz and Van Der Laan 2012};
\citeproc{ref-richardson2013}{Richardson and Robins 2013a};
\citeproc{ref-young2014identification}{Young \emph{et al.} 2014}).

\subsubsection{Statistical Estimation}\label{statistical-estimation}

We used Targeted Minimum Loss-based Estimation (TMLE) to estimate causal
effects while providing valid statistical uncertainty measures
(\citeproc{ref-van2012targeted}{Laan and Gruber 2012};
\citeproc{ref-van2014targeted}{Van der Laan 2014}). TMLE is a
semi-parametric approach that combines machine learning algorithms with
statistical inference to produce robust estimates, even in the presence
of high-dimensional data and complex relationships.

In the first step, we modelled the relationships between treatments,
covariates, and outcomes using machine learning algorithms, allowing for
flexible modelling without restrictive assumptions. In the second step,
we refined these initial estimates through an iterative updating process
guided by the ``efficient influence function,'' improving the accuracy
of the causal effect estimates (\citeproc{ref-van2014discussion}{Laan
\emph{et al.} 2014}).

We used the \texttt{lmtp} package in R
(\citeproc{ref-williams2021}{Williams and Díaz 2021}) for estimation,
employing the \texttt{SuperLearner} library with predefined algorithms
\texttt{SL.ranger}, \texttt{SL.glmnet}, and \texttt{SL.xgboost}
(\citeproc{ref-xgboost2023}{Chen \emph{et al.} 2023};
\citeproc{ref-polley2023}{Polley \emph{et al.} 2023};
\citeproc{ref-Ranger2017}{Wright and Ziegler 2017}). Cross-validation
was used to prevent overfitting.

We generated graphs, tables, and output reports using the margot package
(\citeproc{ref-margot2024}{Bulbulia 2024b}).

\subsubsection{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess the sensitivity of results to unmeasured confounding, we
report VanderWeele and Ding's ``E-value'' in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure--outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). We used
the bound of the E-value 95\% confidence interval closest to 1 to
evaluate the strength of evidence, providing a clear metric for
understanding the robustness of our findings in the presence of
potential unmeasured confounding.

\subsubsection{Scope of Interventions}\label{scope-of-interventions}

To illustrate the magnitude of the interventions, we provide histograms
(See Figure~\ref{fig-hist}) showing the distribution of religious
service attendance during the treatment wave. In Figure~\ref{fig-hist}
\emph{A}, the intervention for regular religious service affects a
larger portion of the sample than the zero religious service
intervention depicted in Figure Figure~\ref{fig-hist} \emph{B}. The
`Regular vs.~Zero' comparison addresses the question: what is the
difference in effects between a society where religious service is
universal versus one where it is completely absent?

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/graph_density_of_exposure_both
Object size: 27.03 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{figure}

\centering{

\includegraphics{24_bulbulia_lmtp_coop_church_files/figure-pdf/fig-hist-1.pdf}

}

\caption{\label{fig-hist}This figure shows a histogram of responses to
religious service frequency in the baseline + 1 wave. Responses above
eight were assigned to eight, and values were rounded to the nearest
whole number. The red dashed line shows the population average. (A)
Responses in the gold bars are shifted to four on the Regular Religious
Service intervention. All those responses in grey (four and above)
remain unchanged. (B) On the zero-intervention, responses in the blue
bars denote those shifted under the zero-intervention treatment.}

\end{figure}%

\newpage{}

\subsubsection{Changes in Religious Service
Attendance}\label{changes-in-religious-service-attendance}

Table Table~\ref{tbl-transition} shows the transitions in religious
service attendance from baseline to the treatment wave. Assessing
changes in the treatment variable is essential for evaluating the
positivity assumption and understanding the potential effect of changes
in exposure (\citeproc{ref-danaei2012}{Danaei \emph{et al.} 2012};
\citeproc{ref-hernan2024WHATIF}{Hernan and Robins 2024};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). We
observe that attendance levels at 0 (no attendance) and 4 (weekly
attendance) were most common, but transitions between states indicate
variation in attendance over time.

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/transition_table.rds
Object size: 0.00 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1196}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}@{}}

\caption{\label{tbl-transition}This transition matrix captures stability
and change in religious service between the baseline and treatment wave.
Each cell in the matrix represents the count of individuals
transitioning from one state to another. The rows correspond to the
state at baseline (From), and the columns correspond to the state at the
treatment wave (To). \textbf{Diagonal entries} (in \textbf{bold})
signify the number of individuals who remained in their initial state
across both waves. \textbf{Off-diagonal entries} signify the transitions
of individuals from their baseline state to a different state in the
treatment wave. A higher number on the diagonal relative to the
off-diagonal entries in the same row indicates greater stability in a
state. Conversely, higher off-diagonal numbers suggest more frequent
shifts in the sample from the baseline state to other states.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 0 & \textbf{26762} & 405 & 174 & 71 & 126 & 26 & 13 & 8 & 68 \\
State 1 & 647 & \textbf{235} & 85 & 44 & 46 & 5 & 2 & 3 & 10 \\
State 2 & 236 & 105 & \textbf{188} & 104 & 96 & 12 & 13 & 2 & 21 \\
State 3 & 112 & 54 & 110 & \textbf{164} & 173 & 18 & 8 & 4 & 15 \\
State 4 & 150 & 71 & 127 & 205 & \textbf{881} & 124 & 64 & 16 & 91 \\
State 5 & 24 & 7 & 17 & 17 & 145 & \textbf{61} & 25 & 7 & 33 \\
State 6 & 14 & 5 & 13 & 17 & 84 & 22 & \textbf{29} & 5 & 37 \\
State 7 & 9 & 0 & 6 & 3 & 16 & 6 & 9 & \textbf{6} & 19 \\
State 8 & 74 & 14 & 17 & 14 & 105 & 34 & 42 & 17 & \textbf{351} \\

\end{longtable}

\newpage{}

\subsection{Results}\label{results}

\subsubsection{Study 1: Causal Effects of Regular Church Attendance on
Self-Reported Volunteering and Self-Reported Volunteering and
Donations}\label{study-1-causal-effects-of-regular-church-attendance-on-self-reported-volunteering-and-self-reported-volunteering-and-donations}

\paragraph{Regular Religious Service vs.~Zero Treatment Contrast for
Donations and
Volunteering}\label{regular-religious-service-vs.-zero-treatment-contrast-for-donations-and-volunteering}

Results for the treatment contrasts between Regular Religious Service
and Zero Religious Service, focusing on self-reported volunteering and
charitable donations, are displayed in Figure~\ref{fig-1_1} \emph{A} and
Table~\ref{tbl-1_1}. These results are measured on the difference scale.

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-1_1}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~a universal loss of weekly religious service on reported
charitable behaviours at the end of the study. Contrasts are expressed
in standard deviation units.}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.132 & 0.102 & 0.161 & 1.507 & 1.426 \\
hours volunteer & 0.123 & 0.090 & 0.156 & 1.482 & 1.389 \\

\end{longtable}

For `donations', the effect estimate is 0.132 {[}0.102, 0.161{]}. The
E-value for this estimate is 1.507, with a lower bound of 1.426. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1.426 to
negate the observed effect. Weaker associations would not overturn it.
We infer \textbf{evidence for causality}. On the data scale, this
intervention represents a difference of \textbf{NZD 656.58 per adult per
year} in charitable giving compared with the zero attendance
intervention.

The effect estimate for `hours volunteer' is 0.123 {[}0.09, 0.156{]}.
The E-value for this estimate is 1.482, with a lower bound of 1.389. We
infer \textbf{evidence for causality}. On the data scale, this
intervention represents a difference of \textbf{NZD 30.21 minutes} per
adult per week in volunteering compared with the zero attendance
intervention.

\paragraph{Regular Religious Service vs.~Status Quo Treatment Contrast
for Donations and
Volunteering}\label{regular-religious-service-vs.-status-quo-treatment-contrast-for-donations-and-volunteering}

Figure~\ref{fig-1_1} \emph{B} and Table~\ref{tbl-1_2} present results
for the treatment contrasts between Regular Religious Service and Status
Quo, focusing on self-reported volunteering and charitable donations.
These results are measured on the difference scale.

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-1_2}This table reports results of model estimates
for the causal effects of a universal gain of weekly religious service
vs.~the status quo on reported charitable behaviours at the end of the
study. Contrasts are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.121 & 0.102 & 0.140 & 1.477 & 1.422 \\
hours volunteer & 0.095 & 0.066 & 0.123 & 1.404 & 1.317 \\

\end{longtable}

For `donations', the effect estimate is 0.121 {[}0.102, 0.14{]}. The
E-value for this estimate is 1.477, with a lower bound of 1.422. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1.422 to
negate the observed effect. Weaker confounding would not overturn it. We
infer \textbf{evidence for causality}. On the data scale, this
intervention represents an increase of \textbf{NZD 601.87 per adult per
year} in expected charitable giving over the status quo.

For `hours volunteer', the effect estimate is 0.095 {[}0.066, 0.123{]}.
The E-value for this estimate is 1.404, with a lower bound of 1.317. At
this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.317 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}. On the data
scale, this intervention represents an increase of \textbf{23.33 minutes
} per adult per week in hours volunteering over the status quo.

\paragraph{Zero Religious Service vs.~The Status Quo Treatment Contrast
for Donations and
Volunteering}\label{zero-religious-service-vs.-the-status-quo-treatment-contrast-for-donations-and-volunteering}

Figure~\ref{fig-1_1} \emph{C} and Table~\ref{tbl-1_3} present results
for the treatment contrasts between Zero Religious Service and Status
Quo, focusing on self-reported volunteering and charitable donations.
These results are measured on the difference scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1212}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1818}}@{}}

\caption{\label{tbl-1_3}This table reports the results of model
estimates for the causal effects of a universal loss of weekly religious
service vs.~the status quo on reported charitable behaviours at the end
of the study. Contrasts are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & -0.011 & -0.029 & 0.008 & 1.111 & 1.000 \\
hours volunteer & -0.028 & -0.042 & -0.014 & 1.189 & 1.128 \\

\end{longtable}

For `donations', the effect estimate is -0.011 {[}-0.029, 0.008{]}. The
E-value for this estimate is 1.111, with a lower bound of 1. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1 to negate
the observed effect. Weaker confounding would not overturn it. We infer
that \textbf{the evidence for causality is not reliable}. On the data
scale, this intervention represents a difference of NZD -54.72 per adult
per year in charitable giving compared to the status quo. Still, again,
this effect is not reliable.

The effect estimate for `hours volunteer' is -0.028 {[}-0.042,
-0.014{]}. The E-value for this estimate is 1.189, with a lower bound of
1.128. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.128 to negate the observed effect. Again, weaker confounding would not
overturn it. We infer \textbf{evidence for causality}. \textbf{On the
data scale, this intervention represents a difference of -6.88 in
volunteering minutes compared with the status quo.}

\begin{figure}

\centering{

\includegraphics{24_bulbulia_lmtp_coop_church_files/figure-pdf/fig-1_1-1.pdf}

}

\caption{\label{fig-1_1}This figure graphs the results of model
estimates for the causal effects of the three causal contrasts of
interest on reported charitable behaviours at the study's end. The
causal contrasts are: (A) Regular vs.~Zero Religious Service, (B)
Regular Religious Service vs.~Status Quo, and (C) Zero Religious Service
vs.~Status Quo. Contrasts are expressed in standard deviation units.}

\end{figure}%

\newpage{}

\subsubsection{Study 2: Causal Effects of Regular Church Attendance on
Support Received From Others --
Time}\label{study-2-causal-effects-of-regular-church-attendance-on-support-received-from-others-time}

\paragraph{Regular vs.~Zero Causal Treatment Contrast for Time Received
From
Others}\label{regular-vs.-zero-causal-treatment-contrast-for-time-received-from-others}

Figure~\ref{fig-study2} \emph{A} and Table~\ref{tbl-study2A} present
results for the treatment contrasts between Regular Religious Service
and Zero, focusing on voluntary help received from others during the
past week (yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}

\caption{\label{tbl-study2A}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~a universal loss of weekly religious service on voluntary
help received from others during the past week (yes/no) at the end of
the study. Contrasts are expressed on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 0.950 & 0.901 & 1.003 & 1.288 & 1.000 \\
friends give time & 1.187 & 1.108 & 1.271 & 1.658 & 1.454 \\
community gives time & 1.378 & 1.231 & 1.541 & 2.100 & 1.764 \\

\end{longtable}

For `community gives time', the effect estimate is 1.378 {[}1.231,
1.541{]}. The E-value for this estimate is 2.1, with a lower bound of
1.764. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.764 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends give time', the effect estimate is 1.187 {[}1.108,
1.271{]}. The E-value for this estimate is 1.658, with a lower bound of
1.454. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.454 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives time', the effect estimate is 0.95 {[}0.901, 1.003{]}.
The E-value for this estimate is 1.288, with a lower bound of 1. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1 to negate
the observed effect. Weaker confounding would not overturn it. We infer
\textbf{that evidence for causality is not reliable}.

\paragraph{Regular Religious Service vs.~Status Quo Treatment Contrast
for Time Received From
Others}\label{regular-religious-service-vs.-status-quo-treatment-contrast-for-time-received-from-others}

Figure~\ref{fig-study2}\emph{B} and Table~\ref{tbl-2-2} present results
for the treatment contrasts between Regular Religious Service and Status
Quo, focusing on voluntary help received from others during the past
week (yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}

\caption{\label{tbl-2-2}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~the status quo on voluntary help received from others during
the past week (yes/no) at the end of the study. Contrasts are expressed
on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 0.958 & 0.913 & 1.006 & 1.258 & 1.000 \\
friends give time & 1.128 & 1.061 & 1.199 & 1.508 & 1.315 \\
community gives time & 1.289 & 1.174 & 1.415 & 1.899 & 1.626 \\

\end{longtable}

For `community gives time', the effect estimate is 1.289 {[}1.174,
1.415{]}. The E-value for this estimate is 1.899, with a lower bound of
1.626. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.626 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends give time', the effect estimate is 1.128 {[}1.061,
1.199{]}. The E-value for this estimate is 1.508, with a lower bound of
1.315. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.315 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives time', the effect estimate is 0.958 {[}0.913,
1.006{]}. The E-value for this estimate is 1.258, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

\paragraph{Zero Religious Service vs.~Status Quo Treatment Contrast for
Time Received From
Others}\label{zero-religious-service-vs.-status-quo-treatment-contrast-for-time-received-from-others}

Figure~\ref{fig-study2} \emph{C} and Table~\ref{tbl-2_3} present results
for the treatment contrasts between Zero Religious Service and Status
Quo, focusing on voluntary help received from others during the past
week (yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}

\caption{\label{tbl-2_3}This table reports results of model estimates
for the causal effects of a universal loss of weekly religious service
vs.~the status quo on voluntary help received from others during the
past week (yes/no) at the end of the study. Contrasts are expressed on
the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 1.008 & 0.991 & 1.026 & 1.098 & 1.000 \\
friends give time & 0.950 & 0.928 & 0.973 & 1.288 & 1.197 \\
community gives time & 0.936 & 0.889 & 0.985 & 1.339 & 1.140 \\

\end{longtable}

For `family gives time', the effect estimate is 1.008 {[}0.991,
1.026{]}. The E-value for this estimate is 1.098, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

For `friends give time', the effect estimate is 0.95 {[}0.928, 0.973{]}.
The E-value for this estimate is 1.288, with a lower bound of 1.197. At
this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.197 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `community gives time', the effect estimate is 0.936 {[}0.889,
0.985{]}. The E-value for this estimate is 1.339, with a lower bound of
1.14. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.14 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

\begin{figure}

\centering{

\includegraphics{24_bulbulia_lmtp_coop_church_files/figure-pdf/fig-study2-1.pdf}

}

\caption{\label{fig-study2}This figure reports the results of model
estimates for the three causal contrasts of interest on help received
from others during the past week (yes/no). The causal contrasts are (A)
Regular vs.~Zero Religious Service, (B) Regular Religious Service
vs.~Status Quo, and (C) Zero Religious Service vs.~Status Quo. Contrasts
are expressed on the risk ratio scale.}

\end{figure}%

\newpage{}

\subsubsection{Study 3: Causal Effects of Regular Church Attendance on
Support Received From Others --
Money}\label{study-3-causal-effects-of-regular-church-attendance-on-support-received-from-others-money}

\paragraph{Regular vs.~Zero Causal Contrast on Money Received From
Others}\label{regular-vs.-zero-causal-contrast-on-money-received-from-others}

Figure~\ref{fig-study_3} \emph{A} and Table~\ref{tbl-3_1} present
results for the treatment contrasts between Regular Religious Service
and Zero, focusing on money received from others during the past week
(yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_1}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~a universal loss of weekly religious service on financial
help received from others during the past week (yes/no) at the end of
the study. Contrasts are expressed on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.137 & 1.028 & 1.258 & 1.532 & 1.198 \\
friends give money & 1.137 & 0.964 & 1.342 & 1.532 & 1.000 \\
community gives money & 1.376 & 1.112 & 1.703 & 2.095 & 1.465 \\

\end{longtable}

For `community gives money', the effect estimate is 1.376 {[}1.112,
1.703{]}. The E-value for this estimate is 2.095, with a lower bound of
1.465. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.465 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives money', the effect estimate is 1.137 {[}1.028,
1.258{]}. The E-value for this estimate is 1.532, with a lower bound of
1.198. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.198 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends give money', the effect estimate is 1.137 {[}0.964,
1.342{]}. The E-value for this estimate is 1.532, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

\paragraph{Regular vs.~Status Quo Causal Contrast on Money Received From
Others}\label{regular-vs.-status-quo-causal-contrast-on-money-received-from-others}

Figure~\ref{fig-study_3} \emph{B} and Table~\ref{tbl-3_2} present
results for the treatment contrasts between Regular Religious Service
and Status Quo, focusing on money received from others during the past
week (yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_2}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~the status quo on financial help received from others during
the past week (yes/no) at the end of the study. Contrasts are expressed
on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.130 & 1.037 & 1.232 & 1.513 & 1.233 \\
friends give money & 1.041 & 0.951 & 1.139 & 1.248 & 1.000 \\
community gives money & 1.254 & 1.098 & 1.432 & 1.818 & 1.426 \\

\end{longtable}

For `community gives money', the effect estimate is 1.254 {[}1.098,
1.432{]}. The E-value for this estimate is 1.818, with a lower bound of
1.426. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.426 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives money', the effect estimate is 1.13 {[}1.037,
1.232{]}. The E-value for this estimate is 1.513, with a lower bound of
1.233. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.233 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends give money', the effect estimate is 1.041 {[}0.951,
1.139{]}. The E-value for this estimate is 1.248, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

\paragraph{Zero vs.~Status Quo Causal Contrast on Money Received From
Others}\label{zero-vs.-status-quo-causal-contrast-on-money-received-from-others}

Figure~\ref{fig-study_3} \emph{C} and Table~\ref{tbl-3_3} present
results for the treatment contrasts between Zero Religious Service and
Status Quo, focusing on money received from others during the past week
(yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_3}Table reports results of model estimates for the
causal effects of a universal loss of weekly religious service vs.~the
status quo on financial help received from others during the past week
(yes/no) at the end of study. Contrasts are expressed on the risk ratio
scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 0.993 & 0.953 & 1.035 & 1.091 & 1 \\
friends gives money & 0.915 & 0.809 & 1.036 & 1.412 & 1 \\
community gives money & 0.911 & 0.796 & 1.042 & 1.425 & 1 \\

\end{longtable}

For `family gives money', the effect estimate on the risk ratio scale is
0.993 {[}0.953, 1.035{]}. The E-value for this estimate is 1.091, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{that evidence for causality is not
reliable}.

For `friends give money', the effect estimate on the risk ratio scale is
0.915 {[}0.809, 1.036{]}. The E-value for this estimate is 1.412, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{that evidence for causality is not
reliable}.

For `community gives money', the effect estimate on the risk ratio scale
is 0.911 {[}0.796, 1.042{]}. The E-value for this estimate is 1.425,
with a lower bound of 1. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1 to negate the observed effect. Weaker
confounding would not overturn it. We infer \textbf{that evidence for
causality is not reliable}.

\begin{figure}

\centering{

\includegraphics{24_bulbulia_lmtp_coop_church_files/figure-pdf/fig-study_3-1.pdf}

}

\caption{\label{fig-study_3}This figure reports the results of model
estimates for the three causal contrasts of interest on help received
from others during the past week (yes/no). The causal contrasts are: (A)
Regular vs.~Zero Religious Service (B) Regular Religious Service
vs.~Status Quo; (C) Zero Religious Service vs.~Status Quo. Contrasts are
expressed on the risk ratio scale.}

\end{figure}%

\newpage{}

\subsubsection{Additional Study: Comparison of Causal Inference Results
with Cross-Sectional
Regressions}\label{additional-study-comparison-of-causal-inference-results-with-cross-sectional-regressions}

To better evaluate the contributions of our methodology to current
practice, we conducted a series of cross-sectional analyses using the
baseline wave data. We quantified the statistical associations between
religious service attendance and our focal prosocial outcomes. We
included all regression covariates from the causal models (including
sample weights) for each analysis, obviously omitting the outcome
measured at baseline, i.e.~the response variable.

\textbf{Cross-sectional volunteering result}: the change in expected
hours of volunteer work for a one-unit increase in religious service
attendance is b = 0.31; (95\% CI 0.28, 0.34). Multiplying this by 4.2
gives a monthly estimate of 77.95 minutes. This result is 2.58 percent
greater than the effect estimated from the `regular vs.~zero' causal
contrast, indicating an \textbf{overstatement in the cross-sectional
regression model}.

\textbf{Cross-sectional charitable donations result}: The coefficient
for religious service on annual charitable donations suggests a change
in expected donation amount per unit increase in attendance is b = 451;
(95\% CI 408, 494). When adjusted to a monthly rate by multiplying by
4.2, this value equals NZ Dollars 1894.45. It is 2.89 percent greater
than our causal contrast estimate, again indicating an
\textbf{overstatement in the cross-sectional regression model}.

For Studies 2 and 3, which focus on community help received, we adjusted
our analysis for the non-collapsibility of odds ratios by assuming a
Poisson distribution for the outcome variables, obtaining a rate ratio
that approximates a risk ratio
(\citeproc{ref-huitfeldt2019collapsibility}{Huitfeldt \emph{et al.}
2019}; \citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}):

\textbf{Cross-sectional community assistance received result: Time}: the
exponentiated change in expectation for a one-unit change in religious
service attendance is b = 1.17; (95\% CI 1.14, 1.19) approximate risk
rate ratio. The monthly rate ratio derived by multiplying this
coefficient by 4.2 is 1.921. This estimate is 1.39 percent greater than
the `regular vs.~zero' causal estimate, pointing to an
\textbf{overstatement in the cross-sectional regression model}.

\textbf{Cross-sectional community assistance received result: Money}:
similarly, the exponentiated change for money received yields an
approximate risk ratio of b = 1.18; (95\% CI 1.08, 1.27). The monthly
risk ratio, after adjustment, is 1.996. This rate ratio is 1.45 percent
greater than the causal estimate, again revealing an
\textbf{overstatement in the cross-sectional regression model}.

\emph{These findings underscore that the results of cross-sectional
regressions, although suggestive, can considerably diverge from those
obtained from the causal analysis of panel data.}

\newpage{}

\subsubsection{Economic Impact of Religious Service Attendance on
Charitable
Donations}\label{economic-impact-of-religious-service-attendance-on-charitable-donations}

We leveraged results to estimate the approximate economic value of
religious service attendance under different scenarios---`Regular
Religious Service', `Zero Religious Service', and the `Status Quo',
focusing on charitable donations.

\begin{itemize}
\tightlist
\item
  \textbf{Regular Religious Service}: An increase in religious service
  attendance yields an individual average donation sum of \textbf{NZD
  1638.98}.
\item
  \textbf{Zero Religious Service}: Reducing religious service attendance
  to zero yields an average donation sum of \textbf{NZD 984.59}.
\item
  \textbf{Status Quo}: The expected individual average donation sum is
  currently \textbf{NZD 1037.14}.
\end{itemize}

With 3,989,000 adult residents in New Zealand in 2021:\footnote{\href{https://www.stats.govt.nz/information-releases/national-population-estimates-at-30-june-2021}{National
  Population Estimates at 30 June 2021}}

\begin{itemize}
\tightlist
\item
  Multiplying the adult population by the average donation sum gives a
  status quo national estimate for charitable giving of \textbf{NZD
  4,137,151,460}.
\item
  The net gain to charity from country-wide regular attendance at
  religious services, compared to the status quo, is \textbf{NZD
  2,400,739,760}.
\item
  Conversely, although the net cost to charity from a complete cessation
  of regular religious service attendance is \textbf{NZD -209,621,950},
  recall the confidence interval crosses zero, and this effect is not
  reliable.
\end{itemize}

To provide context, consider these economic consequences against the New
Zealand government's annual budget in the year outcomes were measured
(2021-2022) is \textbf{NZD 57,976,000,000}.

\begin{itemize}
\tightlist
\item
  \textbf{The expected gain from a nationwide adoption of regular
  religious service represents 4.1 percent of New Zealand's annual
  government budget 2021.}
\item
  We do not obtain a reliable effect from the loss intervention.
\end{itemize}

Thus, focusing on the individual level and aggregating effects across
the adult population, the counterfactual scenario in which all New
Zealand adults regularly attend religious services projects a
substantial increase in society-wide charitable support compared to the
status quo, one year after the intervention.

However, if New Zealand were to experience a complete cessation of
religious service attendance, we do not find evidence that the landscape
of charitable giving would change from its current state one year
later.\footnote{We emphasise that failure to rule out an effect is not
  the same as ruling it out. The relatively low levels of religious
  service attendance in New Zealand mute differences in expected giving.
  In our view, some amount of charity is always better than none. We do
  not devalue any form of charitable giving. Furthermore, our
  population-wide estimates for the aggregated effects of
  \emph{religious behaviour} do not clarify the effects of gaining or
  losing \emph{religious institutions}; our analysis reflects the
  contributions made by those participating in religious institutions.}

\subsection{Discussion}\label{discussion}

\subsubsection{Considerations}\label{considerations}

First, as stated above, our causal inferences turn on three assumptions,
which are worth revisiting:

(i). \textbf{Unmeasured confounding}: Although we employ robust methods
for causal inference, our results depend on the effectiveness of our
strategy to control for confounding. Our sensitivity analyses address
the potential impacts of unmeasured confounders. Nevertheless, the
presence and influence of such confounders are uncertain and
unverifiable from our data.

(ii). \textbf{Causal consistency}: The observed outcomes must correspond
to the counterfactual treatments contrasted. Although ``religious
service attendance'' may appear conditionally independent of the
outcomes given baseline covariates, interpreting these interventions
remains challenging. ``Religious service attendance'' varies widely,
encompassing everything from informal gatherings at homes to formal
services in cathedrals across New Zealand's religious diversity. This
type of ``treatment'' does not mirror a straightforward medical
intervention like a vaccine. The heterogeneity of ``religious service''
limits the clarity of our results, an issue no amount of data or
analysis can resolve because ``religious service'' reflects a broad
spectrum of community activities.

(iii). \textbf{Positivity}: We have confirmed that religious service
attendance varies within our sample and have used semi-parametric models
with ensemble learning and cross-validation to prevent data
over-extrapolation and model over-fitting. Conceptually, it is crucial
for valid causal inference that every potential level of ``treatment''
to religious services is realistically possible (refer to the discussion
in VanderWeele
(\citeproc{ref-vanderweele2017causaleffectsService}{2017})). Although
there are instances realised in our data of secular individuals
initiating religious service and frequent attendees stopping (refer to
Table~\ref{tbl-transition}), it might stretch credulity too far to
imagine that such changes are possible for everyone.

Second, our study confronts the spectre of \textbf{measurement error}:
Both direct and correlated measurement errors can introduce biases,
either by implying effects where none exist or by attenuating true
effects (\citeproc{ref-vanderweele2012MEASUREMENT}{VanderWeele and
Hernán 2012}). Importantly, evaluating prosociality using multiple
measures while also controlling for these measures and the treatment at
baseline helps to mitigate measurement error concerns. Nevertheless,
unknown combinations of measurement error might bias our results. The
outcomes and estimates we report here are best considered
approximations.

Third, we do not examine \textbf{treatment effect heterogeneity}:
Identifying which subgroups experience the strongest responses remains a
task for future research. Such investigations are crucial for making
informed policy decisions and tailoring advice relevant to those
subgroups of the population who might benefit most. Perhaps the most
obvious stratum is religious affiliates
(\citeproc{ref-vanderweele2017causaleffectsService}{VanderWeele 2017}).

Fourth, the \textbf{transportability of our findings remains unclear}:
New Zealand is our target population. Our findings generalise to this
population. However, the transportability of our findings to other
settings---whether our results generalise beyond our targeted New
Zealand population---remains an open question, a matter for future
investigations.

\subsubsection{Observations and
Recommendations}\label{observations-and-recommendations}

First, it is essential to notice that ``Does religion cause
prosociality?'' lacks specificity. To refine this question, we must
articulate clear causal contrasts and their scale, select specific
measures of ``prosociality,'' define our target population, gather
appropriate time-series data, and, only after causal assumptions and
identification criteria are satisfied and threats made explicit,
calculate statistical estimates. Having obtained these estimates, which
rely on assumptions, we must evaluate robustness using sensitivity
analyses (\citeproc{ref-bulbulia2022}{Bulbulia 2023};
\citeproc{ref-hernan2024WHATIF}{Hernan and Robins 2024};
\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-ogburn2021}{Ogburn and Shpitser 2021};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).

Here, we obtain statistical estimates for the causal effects of
religious service on charity and volunteering by (1) stating contrasts
for specific interventions that increase and decrease religious service
attendance across the population; (2) balancing the interventions to be
compared on baseline confounders measured one year before treatment
(including baseline measures of the treatment and outcomes) using
flexible doubly robust machine learning ensembles with cross-validation;
and (3) evaluating contrasts in expected average outcomes under
different treatments one year after treatment.

In the scientifically interesting contrast condition, `Regular vs Zero',
we find considerable social benefits of regular religious attendance for
charitable donations and volunteering. Moreover, we also find that
regular religious service enacted in contemporary New Zealand would
strongly enhance charity and volunteering above the status quo, a point
that may inform discussions among critics of religion. Conversely, the
overall social effects of altogether ceasing religious services are
minimal compared with the status quo. Were New Zealand society to
entirely forgo regular religious attendance, differences in charitable
donations and volunteering one year later are unreliable. Although we
did not investigate the long-term effects of the interventions
considered here, this finding should alleviate some concerns among those
wary of New Zealand's longstanding secular trend. Looking ahead,
\textbf{we recommend that future research distinguish between models of
treatment-gain and models of treatment-loss} (as exemplified by
(\citeproc{ref-vantongeren2020}{Van Tongeren \emph{et al.} 2020})).

Second, we caution that \textbf{classical measures of effect, such as
Cohen's \emph{D} or \(R^2\), may present a misleading indication of
practical significance.} Our study computed standardised differences in
the continuous charity and volunteering outcomes. The contrast between
regular religious service and no service yields an effect size of 0.132
{[}0.102, 0.161{]}. This effect would be categorised as a ``small''
effect by contemporary experimental conventions. Nonetheless, we project
that the difference in annual charitable donations between the regular
service condition and the status quo amounts to NZD 1638.98 versus NZD
1037.14. Not only is this effect practically significant at the
individual level, but summed over the population, the difference amounts
to 4\% of New Zealand's Annual Government Budget (2021). \textbf{We
recommend using causal inference to prioritise, evaluate, and
communicate practical effect sizes. Conventional statistical measures
should not be mistaken for metrics of practical significance.}

Third, our novel measures of prosociality---\textbf{assistance and
financial support received from one's community}---align with the
expectations of self-reported data on charitable donations and
volunteering. We detect marginal causal effects of religious service
attendance on \textbf{measures of prosocial benefit and dependence}.
Notice that just as our measures of prosocial actions
(charity/volunteering) do not capture the targets of prosocial help, our
measures of community help received (time/money) do not capture the
specific sources of help beyond the categories of ``community,''
``friends,'' and ``family''. Nevertheless, the evolutionary theories of
religious prosociality that motivate this study are grounded on
within-group cooperative benefits
(\citeproc{ref-bulbulia2012spreading}{Bulbulia 2012};
\citeproc{ref-johnson2015}{Johnson 2015};
\citeproc{ref-schloss2011evolutionary}{Schloss and Murray 2011};
\citeproc{ref-sosis2003cooperation}{Sosis and Bressler 2003};
\citeproc{ref-whitehouse2023}{Whitehouse \emph{et al.} 2023}). This
consistency between self-reported giving and help received aligns with
public data in New Zealand;\footnote{\url{https://www.charities.govt.nz/view-data/}}
where religious institutional charity accounts for 40\% of the
charitable sector (refer to (\citeproc{ref-McLeod2020}{McLeod 2020 p.
17}), and also (\citeproc{ref-brooks2004faith}{Brooks 2004};
\citeproc{ref-monsma2007religion}{Monsma 2007};
\citeproc{ref-woodyard2014doing}{Woodyard and Grable 2014})).
Additionally, religious institutions appear particularly efficient owing
to low administrative costs and high volunteer engagement
(\citeproc{ref-bekkers2011literature}{Bekkers and Wiepking 2011};
\citeproc{ref-khanna1995charity}{Khanna \emph{et al.} 1995};
\citeproc{ref-McLeod2020}{McLeod 2020 p. 26}). We note that the
community signals of religious giving are consistent with the theory
that religion promotes altruism outside families, friendships, and even
among strangers (\citeproc{ref-mccullough2020kindness}{McCullough
2020}). \textbf{In contexts where investigators are concerned about
self-presentation biases when surveying charitable donations and
volunteering, we recommend piloting and deploying measures that capture
community-received assistance.}

Fourth, our secondary analysis reveals that standard cross-sectional
regressions overstate the causal effects estimates obtained from a
conscientious application of causal methods to time-series data.
Importantly, associational models might also \emph{understate} true
causal relationships, especially if adjustments involve mediators
(\citeproc{ref-mcelreath2020}{McElreath 2020};
\citeproc{ref-westreich2013}{Westreich and Greenland 2013}). Despite
their effectiveness and relevance, causal inference methods remain
uncommon in many human sciences, including the psychological sciences,
where traditional associational methods still dominate. Transitioning to
causal data science might seem daunting. Yet, causation inherently
unfolds in time, with causes preceding effects. Estimating average
causal effects involves multi-stepped workflows and robust time-series
data (\citeproc{ref-bulbulia2023}{Bulbulia 2024c};
\citeproc{ref-neal2020introduction}{Neal 2020}). Although the need for
researchers to develop new skills imposes considerable demands, it is
encouraging that methods for causal inference have become standard in
epidemiology (\citeproc{ref-lash2020}{Lash \emph{et al.} 2020}) and are
rapidly gaining traction in economics
(\citeproc{ref-angrist2009mostly}{Angrist and Pischke 2009};
\citeproc{ref-athey2019}{Athey \emph{et al.} 2019};
\citeproc{ref-athey2021}{Athey and Wager 2021}) and political science
(\citeproc{ref-montgomery2018}{Montgomery \emph{et al.} 2018}).

Moreover, a global panel study suited for researching religion
(\citeproc{ref-johnson2022global}{Johnson and VanderWeele 2022}) offers
exciting opportunities for psychological scientists to apply causal
methods to those psychological questions at the heart of our discipline.

Also encouraging, well-designed panel studies investigating the causal
effects of religious service attendance on health that capitalise on the
affordances of time-series data provide models for studies that may
investigate the social consequences of religion (refer to Kim and
VanderWeele (\citeproc{ref-kim2019mediators}{2019})). At present, then,
the intellectual benefits of retooling would seem considerable (refer to
(\citeproc{ref-major2023exploring}{Major-Smith 2023})).

Setting intellectual benefits aside, it is vital to remember that
investigators should be able to evaluate the practical interest of their
findings coherently. Such evaluation relies on quantifying the effects
of interventions. However, associational methods cannot deliver this
understanding where causal inferential workflows are absent because
association is not guaranteed to be causation
(\citeproc{ref-westreich2013}{Westreich and Greenland 2013}). What might
be called a \textbf{practical significance gap} arises from
associational models because we cannot interpret associations as
causation unless we have obtained balance on the treatments to be
compared, know that causes in our data precede effects in time, and
ensure that identification conditions have been met. Notably, the
\textbf{practical significance gap remains for associational methods
even when they are applied to time-series data}, and even when the
associational methods are sophisticated---as in the statistical
structural equation and multilevel modelling traditions (refer to
(\citeproc{ref-hazlett2022understanding}{Hazlett and Wainstein 2022};
\citeproc{ref-vanderweele2021can}{VanderWeele 2021a})). Yet, because
investigators typically seek both scientific knowledge and practical
understanding, \textbf{we strongly recommend the broader adoption of
causal inferential methods in the psychological sciences.}

Fifth, and finally, we frame this study's contribution in light of
future horizons. This study combined robust causal methods with national
panel data to quantitatively investigate the social consequences of
religious behaviour. Using both stated and revealed indicators, we
provide evidence that religious service attendance causally affects
charitable donations and volunteering. These findings offer insights
into \emph{how much} religious service affects charity and volunteering
in New Zealand and possibly in similar cultures. We hope this research
will serve as a guide for studies in other settings.

However, even within New Zealand, much remains to be discovered. We have
not attempted to elucidate heterogeneity in the treatment effects we
observe. Nor have we investigated the pathways by which religious
service attendance affects social behaviours. A substantial body of
research has examined the psychological and cultural features through
which religious behaviours affect individuals
(\citeproc{ref-cristofori2016neural}{Cristofori \emph{et al.} 2016};
\citeproc{ref-konvalinka2011synchronized}{Konvalinka \emph{et al.}
2011}; \citeproc{ref-lang2015effects}{Lang \emph{et al.} 2015};
\citeproc{ref-mccullough2016christian}{McCullough \emph{et al.} 2016};
\citeproc{ref-norenzayan2016}{Norenzayan \emph{et al.} 2016};
\citeproc{ref-shaver2015evolution}{Shaver 2015};
\citeproc{ref-shaver2020church}{Shaver \emph{et al.} 2020};
\citeproc{ref-sosis2005does}{Sosis 2005}; \citeproc{ref-watts2016}{Watts
\emph{et al.} 2016}). Yet obtaining a causal understanding presents
conceptual, modelling, and data challenges
(\citeproc{ref-diaz2021nonparametric}{Dı́az \emph{et al.} 2021},
\citeproc{ref-Diaz2023}{2023}; \citeproc{ref-robins1992}{Robins and
Greenland 1992}; \citeproc{ref-vanderweele2015}{VanderWeele 2015}). In
the years ahead, \textbf{we recommend the wider development and
application of causal inferential methods employing repeated
measurements over more than three years to investigate variation,
interaction, and causal mediation}.

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study. Members of the NZAVS management team and research
group hold full copies of the NZAVS data. A de-identified dataset
containing only the variables analysed in this manuscript is available
upon request from the corresponding author or any member of the NZAVS
advisory board for replication or checking of any published study using
NZAVS data. The code for the analysis can be found at:
\url{https://github.com/go-bayes/models/blob/main/scripts/24-bulbulia-church-prosocial.R}.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Planck Institute for the Science of Human History. The
funders had no role in preparing the manuscript or deciding to publish
it.

\subsubsection{Author Statement}\label{author-statement}

JB conceived the study and approach. CS led NZAVS data collection. All
authors contributed to the manuscript.

\newpage{}

\subsection{Appendix A: Measures}\label{appendix-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth?'').

\paragraph{Born in New Zealand}\label{born-in-new-zealand}

\paragraph{Charitable Donations (Study 1
outcome)}\label{charitable-donations-study-1-outcome}

Using one item from Hoverd and Sibley
(\citeproc{ref-hoverd_religious_2010}{2010}), we asked participants,
``How much money have you donated to charity in the last year?''.

\paragraph{Charitable Volunteering (Study 1
outcome)}\label{charitable-volunteering-study-1-outcome}

We measured hours of volunteering using one item from Sibley \emph{et
al.} (\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
voluntary/charitable work.''

\paragraph{Children Number (waves: 1-3,
4-15)}\label{children-number-waves-1-3-4-15}

We measured the number of children using one item from Bulbulia \emph{et
al.} (\citeproc{ref-Bulbulia_2015}{2015}). We asked participants, ``How
many children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, or adopted?'' or ``How many
children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, and/or parented?'' (waves:
12-15).

\paragraph{Disability}\label{disability}

We assessed disability with a one-item indicator adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}). It asks, ``Do you have a health
condition or disability that limits you and that has lasted for 6+
months?'' (1 = Yes, 0 = No).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

We asked participants, ``What is your highest level of qualification?''.
We coded participants' highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school quals coded as Level 3, and all other ancillary
categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants, ``Are you currently employed? (This includes
self-employed or casual work)''.

\paragraph{Ethnicity}\label{ethnicity}

Based on the New Zealand Census, we asked participants, ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Fatigue}\label{fatigue}

We assessed subjective fatigue by asking participants, ``During the last
30 days, how often did \ldots{} you feel exhausted?'' Responses were
collected on an ordinal scale (0 = None of The Time, 1 = A little of The
Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\paragraph{Hours of Childcare}\label{hours-of-childcare}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Childcare}\label{hours-of-childcare-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Sleep}\label{hours-of-sleep}

Participants were asked, ``During the past month, on average, how many
hours of \emph{actual sleep} did you get per night?''.

\paragraph{Hours of Work}\label{hours-of-work}

We measured work hours using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{} working in
paid employment.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked, ``Please estimate your total household income
(before tax) for the year XXXX''. To stabilise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Kessler-6: Psychological Distress (waves:
2-3,4-15)}\label{kessler-6-psychological-distress-waves-2-34-15}

We measured psychological distress using the Kessler-6 scale
(kessler2002?), which exhibits strong diagnostic concordance for
moderate and severe psychological distress in large, crosscultural
samples (kessler2010?; prochaska2012?). Participants rated during the
past 30 days, how often did\ldots{} (1) ``\ldots{} you feel hopeless'';
(2) ``\ldots{} you feel so depressed that nothing could cheer you up'';
(3) ``\ldots{} you feel restless or fidgety''; (4)``\ldots{} you feel
that everything was an effort''; (5) ``\ldots{} you feel worthless'';
(6) '' you feel nervous?'' Ordinal response alternatives for the
Kessler-6 are: ``None of the time''; ``A little of the time''; ``Some of
the time''; ``Most of the time''; ``All of the time.''

\paragraph{Male Gender (waves: 1-15)}\label{male-gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants' personalities with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}), which consists of six dimensions and each
dimension is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I often forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{NZSEI Occupational Prestige and Status (waves:
8-15)}\label{nzsei-occupational-prestige-and-status-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017a}{Fahy
\emph{et al.} 2017a}). This index uses the income, age, and education of
a reference group, in this case the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant an NZSEI-13 score based on
their occupation.

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017b}). This index uses the income, age, and education of
a reference group, in this case, the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant an NZSEI-13 score based on
their occupation.

\paragraph{Opt-in}\label{opt-in}

The New Zealand Attitudes and Values Study allows opt-ins to the study.
Because the opt-in population may differ from those sampled randomly
from the New Zealand electoral roll; although the opt-in rate is low, we
include an indicator (yes/no) for this variable.

\paragraph{Partner (No/Yes)}\label{partner-noyes}

``What is your relationship status?'' (e.g., single, married, de-facto,
civil union, widowed, living together, etc.)

\paragraph{Politically Conservative}\label{politically-conservative}

We measured participants' political conservative orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\subparagraph{Religious Service
Attendance}\label{religious-service-attendance}

If participants answered \emph{yes} to ``Do you identify with a religion
and/or spiritual group?'' we measured their frequency of church
attendence using one item from Sibley and Bulbulia
(\citeproc{ref-sibley2012}{2012}): ``how many times did you attend a
church or place of worship in the last month?''. Those participants who
were not religious were imputed a score of ``0''.

\paragraph{Rural/Urban Codes}\label{ruralurban-codes}

Participants residence locations were coded according to a five-level
ordinal categorisation ranging from ``Urban'' to Rural, see Sibley
(\citeproc{ref-sibley2021}{2021}).

\paragraph{Short-Form Health}\label{short-form-health}

Participants' subjective health was measured using one item (``Do you
have a health condition or disability that limits you, and that has
lasted for 6+ months?''; 1 = Yes, 0 = No) adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}).

\paragraph{Sample Origin}\label{sample-origin}

Wave enrolled in NZAVS, see Sibley (\citeproc{ref-sibley2021}{2021}).

\paragraph{Support received: money (waves 10-12) (Study 4
outcomes)}\label{support-received-money-waves-10-12-study-4-outcomes}

The NZAVS has a `revealed' measure of received help and support measured
in hours of support in the previous week. The items are:

\emph{Please estimate how much help you have received from the following
sources in the last week?}

\begin{itemize}
\tightlist
\item
  \emph{family\ldots MONEY (hours)}
\item
  \emph{friends\ldots MONEY (hours)}
\item
  \emph{members of my community\ldots MONEY (hours)}
\end{itemize}

Because this measure is highly variable, we convert responses to binary
indicators: \emph{0 = none/1 any}

\paragraph{Support received: time (waves 10-13) (Study 3
outcomes)}\label{support-received-time-waves-10-13-study-3-outcomes}

\emph{Please estimate how much help you have received from the following
sources in the last week.}

\begin{itemize}
\tightlist
\item
  \emph{family\ldots TIME (hours)}
\item
  \emph{friends\ldots TIME (hours)}
\item
  \emph{members of my community\ldots TIME (hours)}
\end{itemize}

Because this measure is highly variable, we convert responses to binary
indicators: \emph{0 = none/1 any}

\paragraph{Total Siblings}\label{total-siblings}

Participants were asked the following questions related to sibling
counts:

\begin{itemize}
\tightlist
\item
  Were you the 1st born, 2nd born, or 3rd born, etc, child of your
  mother?
\item
  Do you have siblings?
\item
  How many older sisters do you have?
\item
  How many younger sisters do you have?
\item
  How many older brothers do you have?
\item
  How many younger brothers do you have?
\end{itemize}

A single score was obtained from sibling counts by summing responses to
the ``How many\ldots{}'' items. From these scores, an ordered factor was
created ranging from 0 to 7, where participants with more than 7
siblings were grouped into the highest category.

\newpage{}

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/table_baseline.rds
Object size: 18.67 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{longtable}[]{@{}ll@{}}

\caption{\label{tbl-table-demography}Baseline demographic statistics}

\tabularnewline

\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 33,198} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 51 (14) \\
Min, Max & 18, 96 \\
Q1, Q3 & 41, 61 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.37 (0.98) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.75, 6.00 \\
Unknown & 272 \\
\textbf{Born Nz} & 26,197 (79\%) \\
Unknown & 34 \\
\textbf{Children Num} & NA \\
Mean (SD) & 1.76 (1.44) \\
Min, Max & 0.00, 14.00 \\
Q1, Q3 & 0.00, 3.00 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.14 (1.04) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.50, 6.00 \\
Unknown & 266 \\
\textbf{Education Level Coarsen} & NA \\
no\_qualification & 769 (2.3\%) \\
cert\_1\_to\_4 & 11,278 (34\%) \\
cert\_5\_to\_6 & 4,281 (13\%) \\
university & 8,947 (27\%) \\
post\_grad & 3,892 (12\%) \\
masters & 2,956 (9.0\%) \\
doctorate & 891 (2.7\%) \\
Unknown & 184 \\
\textbf{Employed} & 26,379 (80\%) \\
Unknown & 26 \\
\textbf{Eth Cat} & NA \\
euro & 27,404 (83\%) \\
maori & 3,424 (10\%) \\
pacific & 707 (2.1\%) \\
asian & 1,438 (4.4\%) \\
Unknown & 225 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.88 (1.20) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 3.00, 4.75 \\
Unknown & 266 \\
\textbf{Hlth Disability} & 7,558 (23\%) \\
Unknown & 561 \\
\textbf{Hlth Fatigue} & NA \\
0 & 5,289 (16\%) \\
1 & 10,940 (33\%) \\
2 & 10,196 (31\%) \\
3 & 4,862 (15\%) \\
4 & 1,577 (4.8\%) \\
Unknown & 334 \\
\textbf{Hlth Sleep Hours} & NA \\
Mean (SD) & 6.95 (1.11) \\
Min, Max & 2.50, 16.00 \\
Q1, Q3 & 6.00, 8.00 \\
Unknown & 1,528 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.49 (1.15) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.75, 6.50 \\
Unknown & 269 \\
\textbf{Hours Children log} & NA \\
Mean (SD) & 1.10 (1.58) \\
Min, Max & 0.00, 5.13 \\
Q1, Q3 & 0.00, 2.20 \\
Unknown & 875 \\
\textbf{Hours Exercise log} & NA \\
Mean (SD) & 1.57 (0.83) \\
Min, Max & 0.00, 4.39 \\
Q1, Q3 & 1.10, 2.08 \\
Unknown & 875 \\
\textbf{Hours Housework log} & NA \\
Mean (SD) & 2.15 (0.77) \\
Min, Max & 0.00, 5.13 \\
Q1, Q3 & 1.79, 2.71 \\
Unknown & 875 \\
\textbf{Hours Work log} & NA \\
Mean (SD) & 2.64 (1.59) \\
Min, Max & 0.00, 4.62 \\
Q1, Q3 & 1.10, 3.71 \\
Unknown & 875 \\
\textbf{Household Inc log} & NA \\
Mean (SD) & 11.41 (0.76) \\
Min, Max & 0.69, 14.92 \\
Q1, Q3 & 11.00, 11.92 \\
Unknown & 1,352 \\
\textbf{Kessler6 Sum} & NA \\
Mean (SD) & 5 (4) \\
Min, Max & 0, 24 \\
Q1, Q3 & 2, 7 \\
Unknown & 297 \\
\textbf{Male} & 11,975 (36\%) \\
\textbf{Modesty} & NA \\
Mean (SD) & 6.03 (0.90) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 5.50, 6.75 \\
Unknown & 11 \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.45 (1.15) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 2.50, 4.25 \\
Unknown & 274 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.69 (2.70) \\
Min, Max & 1.00, 10.00 \\
Q1, Q3 & 2.00, 7.00 \\
Unknown & 233 \\
\textbf{Nzsei 13 l} & NA \\
Mean (SD) & 55 (16) \\
Min, Max & 10, 90 \\
Q1, Q3 & 42, 69 \\
Unknown & 172 \\
\textbf{Openness} & NA \\
Mean (SD) & 4.99 (1.12) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.25, 5.75 \\
Unknown & 267 \\
\textbf{Partner} & 24,869 (76\%) \\
Unknown & 422 \\
\textbf{Political Conservative} & NA \\
1 & 1,777 (5.6\%) \\
2 & 6,563 (21\%) \\
3 & 6,505 (20\%) \\
4 & 9,373 (29\%) \\
5 & 4,813 (15\%) \\
6 & 2,378 (7.5\%) \\
7 & 483 (1.5\%) \\
Unknown & 1,306 \\
\textbf{Religion Church Round} & NA \\
0 & 27,653 (83\%) \\
1 & 1,077 (3.2\%) \\
2 & 777 (2.3\%) \\
3 & 658 (2.0\%) \\
4 & 1,729 (5.2\%) \\
5 & 336 (1.0\%) \\
6 & 226 (0.7\%) \\
7 & 74 (0.2\%) \\
8 & 668 (2.0\%) \\
\textbf{Rural Gch 2018 l} & NA \\
1 & 20,361 (62\%) \\
2 & 6,390 (19\%) \\
3 & 4,020 (12\%) \\
4 & 1,816 (5.5\%) \\
5 & 380 (1.2\%) \\
Unknown & 231 \\
\textbf{Sample Frame Opt in} & 1,107 (3.3\%) \\
\textbf{Sample Origin} & NA \\
1-2 & 2,191 (6.6\%) \\
3-3.5 & 1,664 (5.0\%) \\
4 & 1,987 (6.0\%) \\
5-6-7 & 3,203 (9.6\%) \\
8-9 & 4,264 (13\%) \\
10 & 19,889 (60\%) \\
\textbf{Short Form Health} & NA \\
Mean (SD) & 5.06 (1.16) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.33, 6.00 \\
Unknown & 5 \\
\textbf{Total Siblings} & NA \\
Mean (SD) & 2.52 (1.80) \\
Min, Max & 0.00, 23.00 \\
Q1, Q3 & 1.00, 3.00 \\
Unknown & 689 \\

\end{longtable}

Table~\ref{tbl-table-demography} baseline demographic statistics for
couples who met inclusion criteria.

\newpage{}

\subsection{Appendix C: Treatment Statistics}\label{appendix-exposures}

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/table_exposures.rds
Object size: 2.63 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{table}

\caption{\label{tbl-table-exposures-code}Exposures at baseline and
baseline + 1 (treatment) wave}

\centering{

\textbar{}\textbf{Exposure Variables by Wave} \textbar{}\textbf{2018}\\
N = 33,198 \textbar{}\textbf{2019}\\
N = 33,198 \textbar{}
\textbar:------------------------------\textbar:--------------------\textbar:--------------------\textbar{}
\textbar{}\textbf{Religion Church Round} \textbar NA \textbar NA
\textbar{} \textbar0 \textbar27,653 (83\%) \textbar28,028 (84\%)
\textbar{} \textbar1 \textbar1,077 (3.2\%) \textbar896 (2.7\%)
\textbar{} \textbar2 \textbar777 (2.3\%) \textbar737 (2.2\%) \textbar{}
\textbar3 \textbar658 (2.0\%) \textbar639 (1.9\%) \textbar{} \textbar4
\textbar1,729 (5.2\%) \textbar1,672 (5.0\%) \textbar{} \textbar5
\textbar336 (1.0\%) \textbar308 (0.9\%) \textbar{} \textbar6 \textbar226
(0.7\%) \textbar205 (0.6\%) \textbar{} \textbar7 \textbar74 (0.2\%)
\textbar68 (0.2\%) \textbar{} \textbar8 \textbar668 (2.0\%) \textbar645
(1.9\%) \textbar{} \textbar Unknown \textbar0 \textbar0 \textbar{}
\textbar{}\textbf{Alert Level Combined} \textbar NA \textbar NA
\textbar{} \textbar no\_alert \textbar33,198 (100\%) \textbar23,751
(72\%) \textbar{} \textbar early\_covid \textbar0 (0\%) \textbar3,643
(11\%) \textbar{} \textbar alert\_level\_1 \textbar0 (0\%) \textbar2,821
(8.5\%) \textbar{} \textbar alert\_level\_2 \textbar0 (0\%) \textbar836
(2.5\%) \textbar{} \textbar alert\_level\_2\_5\_3 \textbar0 (0\%)
\textbar552 (1.7\%) \textbar{} \textbar alert\_level\_4 \textbar0 (0\%)
\textbar1,595 (4.8\%) \textbar{} \textbar Unknown \textbar0 \textbar0
\textbar{}

}

\end{table}%

tbl-table-exposures-code presents baseline (NZAVS time 10) and exposure
wave (NZAVS time 11) statistics for the exposure variable: religious
service attendance (range 0-8). Responses coded as eight or above were
coded as ``8''. This decision to avoid spare treatments was based on
theoretical grounds, namely, that daily exposure would be similar in its
effects to more than daily exposure. We note that causal contrasts were
obtained for projects with either no attendance or four or more visits
per month. Hence this simplification of the measure is unlikely to
affect theoretical and practical inferences. All models adjusted for the
pandemic alert level because the treatment wave (NZAVS time 11) occurred
during New Zealand's COVID-19 pandemic. The pandemic is not a
``confounder'' because a confounder must be related to the treatment and
the outcome. At the end of the study, all participants had been exposed
to the pandemic. However, to satisfy the causal consistency assumption,
all treatments must be conditionally equivalent within levels of all
covariates (\citeproc{ref-vanderweele2013}{VanderWeele and Hernan
2013}). Because COVID affected the ability or willingness of individuals
to attend religious service, we included the lockdown condition as a
covariate (\citeproc{ref-sibley2021}{Sibley 2021}). To better enable
conditional independence within levels of the treatment variable, we
conditioned on the lead value of COVID-alert level at baseline. To
mitigate systematic biases arising from attrition and missingness, the
\texttt{lmtp} package uses inverse probability of censoring weights,
which were used when estimating the causal effects of the exposure on
the outcome.

\subsubsection{Binary Transition Table for The
Treatment}\label{binary-transition-table-for-the-treatment}

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/transition_table_binary_gain.rds
Object size: 0.00 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{longtable}[]{@{}ccc@{}}

\caption{\label{tbl-transition-tablegain}Transition table for stability
and change in regular religious service (4x per month) between baseline
and treatment wave.}

\tabularnewline

\toprule\noalign{}
From & \textgreater=4 & \textless{} 4 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textgreater=4 & \textbf{29496} & 669 \\
\textless{} 4 & 804 & \textbf{2229} \\

\end{longtable}

Table~\ref{tbl-transition-tablegain} presents a transition matrix to
evaluate treatment shifts between baseline and treatment wave. Here, we
focus on the shift from/to monthly attendance at four or more visits per
month. Entries along the diagonal (in bold) indicate the number of
individuals who \textbf{stayed} in their initial state. By contrast, the
off-diagonal shows the transitions from the initial state (bold) to
another state in the following wave (off diagonal). Thus the cell
located at the intersection of row \(i\) and column \(j\), where
\(i \neq j\), gives us the counts of individuals moving from state \(i\)
to state \(j\).

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/transition_table_binary_zero.rds
Object size: 0.00 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{longtable}[]{@{}ccc@{}}

\caption{\label{tbl-transition-tableloss}Transition table for stability
and change in zero religious service (0 x per month) between baseline
and treatment wave.}

\tabularnewline

\toprule\noalign{}
From & 0 & \textgreater{} 0 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & \textbf{26762} & 891 \\
\textgreater{} 0 & 1266 & \textbf{4279} \\

\end{longtable}

Table~\ref{tbl-transition-tableloss} presents a transition matrix to
evaluate treatment shifts between baseline and treatment wave. Here, we
focus on the shift from/to zero religious service attendance. Again,
entries along the diagonal (in bold) indicate the number of individuals
who \textbf{stayed} in their initial state. By contrast, the
off-diagonal shows the transitions from the initial state (bold) to
another state in the following wave (off diagonal). Thus the cell
located at the intersection of row \(i\) and column \(j\), where
\(i \neq j\), gives us the counts of individuals moving from state \(i\)
to state \(j\).

\subsubsection{Imbalance of Confounding Covariates
Treatments}\label{imbalance-of-confounding-covariates-treatments}

Figure~\ref{fig-match_1} shows imbalance of covariates on the treatment
at the treatment wave. The variable on which there is strongest
imbalance is the baseline measure of religious service attendance. It is
important to adjust for this measure both for confounding control and to
better estimate an incident exposure effect for the religious service at
the treatment wave (in contrast to merely estimating a prevalence
effect). See VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020}).

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/love_plot_one
Object size: 0.03 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{figure}

\centering{

\includegraphics{24_bulbulia_lmtp_coop_church_files/figure-pdf/fig-match_1-1.pdf}

}

\caption{\label{fig-match_1}This figure shows the imbalance in
covariates on the treatment}

\end{figure}%

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{verbatim}
Object read from: /Users/joseph/Library/CloudStorage/Dropbox-v-project/data/nzvs_mods/24/church-prosocial-v7/table_outcomes.rds
Object size: 9.18 MB
👍 Read operation completed successfully!
\end{verbatim}

\begin{table}

\caption{\label{tbl-table-outcomes}Outcomes at baseline and
end-of-study}

\centering{

\textbar{}\textbf{Outcome Variables by Wave} \textbar{}\textbf{2018}\\
N = 33,198 \textbar{}\textbf{2020}\\
N = 33,198 \textbar{}
\textbar:---------------------------------\textbar:--------------------\textbar:--------------------\textbar{}
\textbar{}\textbf{Annual Charity} \textbar150 (40, 500) \textbar200 (20,
600) \textbar{} \textbar Unknown \textbar1,076 \textbar6,730 \textbar{}
\textbar{}\textbf{Community Gives Money Binary} \textbar135 (0.4\%)
\textbar118 (0.4\%) \textbar{} \textbar Unknown \textbar669
\textbar6,959 \textbar{} \textbar{}\textbf{Community Gives Time Binary}
\textbar1,702 (5.2\%) \textbar1,669 (6.4\%) \textbar{} \textbar Unknown
\textbar669 \textbar6,959 \textbar{} \textbar{}\textbf{Family Gives
Money Binary} \textbar1,782 (5.5\%) \textbar1,236 (4.7\%) \textbar{}
\textbar Unknown \textbar669 \textbar6,959 \textbar{}
\textbar{}\textbf{Family Gives Time Binary} \textbar9,539 (29\%)
\textbar7,600 (29\%) \textbar{} \textbar Unknown \textbar669
\textbar6,959 \textbar{} \textbar{}\textbf{Friends Give Money Binary}
\textbar372 (1.1\%) \textbar270 (1.0\%) \textbar{} \textbar Unknown
\textbar669 \textbar6,959 \textbar{} \textbar{}\textbf{Friends Give
Time} \textbar5,765 (18\%) \textbar4,855 (19\%) \textbar{}
\textbar Unknown \textbar669 \textbar6,959 \textbar{}
\textbar{}\textbf{Sense Neighbourhood Community} \textbar NA \textbar NA
\textbar{} \textbar1 \textbar1,976 (6.0\%) \textbar1,124 (4.2\%)
\textbar{} \textbar2 \textbar4,037 (12\%) \textbar2,703 (10\%)
\textbar{} \textbar3 \textbar4,796 (15\%) \textbar3,561 (13\%)
\textbar{} \textbar4 \textbar6,840 (21\%) \textbar5,809 (22\%)
\textbar{} \textbar5 \textbar7,088 (21\%) \textbar6,477 (24\%)
\textbar{} \textbar6 \textbar5,753 (17\%) \textbar5,060 (19\%)
\textbar{} \textbar7 \textbar2,550 (7.7\%) \textbar2,104 (7.8\%)
\textbar{} \textbar Unknown \textbar158 \textbar6,360 \textbar{}
\textbar{}\textbf{Social Belonging} \textbar5.33 (4.33, 6.00)
\textbar5.33 (4.33, 6.00) \textbar{} \textbar Unknown \textbar268
\textbar6,418 \textbar{} \textbar{}\textbf{Social Support} \textbar6.33
(5.33, 7.00) \textbar6.33 (5.33, 7.00) \textbar{} \textbar Unknown
\textbar19 \textbar6,286 \textbar{} \textbar{}\textbf{Volunteering
Hours} \textbar0.00 (0.00, 1.00) \textbar0.00 (0.00, 1.00) \textbar{}
\textbar Unknown \textbar875 \textbar6,863 \textbar{}
\textbar{}\textbf{Volunteers Binary} \textbar9,443 (29\%) \textbar6,881
(26\%) \textbar{} \textbar Unknown \textbar875 \textbar6,863 \textbar{}

}

\end{table}%

Table~\ref{tbl-table-outcomes} presents baseline and end-of-study
descriptive statistics for the outcome variables.

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-angrist2009mostly}
Angrist, JD, and Pischke, J-S (2009) \emph{Mostly harmless econometrics:
An empiricist's companion}, Princeton University Press.

\bibitem[\citeproctext]{ref-athey2019}
Athey, S, Tibshirani, J, and Wager, S (2019) Generalized random forests.
\emph{The Annals of Statistics}, \textbf{47}(2), 1148--1178.
doi:\href{https://doi.org/10.1214/18-AOS1709}{10.1214/18-AOS1709}.

\bibitem[\citeproctext]{ref-athey2021}
Athey, S, and Wager, S (2021) Policy Learning With Observational Data.
\emph{Econometrica}, \textbf{89}(1), 133--161.
doi:\href{https://doi.org/10.3982/ECTA15732}{10.3982/ECTA15732}.

\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bekkers2011literature}
Bekkers, R, and Wiepking, P (2011) A literature review of empirical
studies of philanthropy: Eight mechanisms that drive charitable giving.
\emph{Nonprofit and Voluntary Sector Quarterly}, \textbf{40}(5),
924--973.

\bibitem[\citeproctext]{ref-brooks2004faith}
Brooks, AC (2004) Faith, secularism, and charity. \emph{Faith \&
Economics}, \textbf{43}(Spring), 1--8.

\bibitem[\citeproctext]{ref-bulbulia2012spreading}
Bulbulia, J (2012) Spreading order: Religion, cooperative niche
construction, and risky coordination problems. \emph{Biology \&
Philosophy}, \textbf{27}, 1--27.

\bibitem[\citeproctext]{ref-bulbulia2022}
Bulbulia, JA (2023) A workflow for causal inference in cross-cultural
psychology. \emph{Religion, Brain \& Behavior}, \textbf{13}(3),
291--306.
doi:\href{https://doi.org/10.1080/2153599X.2022.2070245}{10.1080/2153599X.2022.2070245}.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, JA (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-bulbulia2023}
Bulbulia, JA (2024c) Methods in causal inference part 1: Causal diagrams
and confounding. \emph{Evolutionary Human Sciences}, \textbf{6}.
Retrieved from \url{https://osf.io/b23k7}

\bibitem[\citeproctext]{ref-bulbulia2024swigstime}
Bulbulia, JA (2024d) Methods in causal inference part 2: Interaction,
mediation, and time-varying treatments. \emph{Evolutionary Human
Sciences}, \textbf{6}. Retrieved from
\url{https://osf.io/preprints/psyarxiv/vr268}

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, JA, Shaver, JH, Greaves, L, Sosis, R, and Sibley, CG (2015)
Religion and parental cooperation: An empirical test of slone's sexual
signaling model. In S. J. D. amd Van Slyke J., ed., \emph{The attraction
of religion: A sexual selectionist account}, Bloomsbury Press, 29--62.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: Interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.

\bibitem[\citeproctext]{ref-xgboost2023}
Chen, T, He, T, Benesty, M, \ldots{} Yuan, J (2023) \emph{Xgboost:
Extreme gradient boosting}. Retrieved from
\url{https://CRAN.R-project.org/package=xgboost}

\bibitem[\citeproctext]{ref-chen2020religious}
Chen, Y, Kim, ES, and VanderWeele, TJ (2020) Religious-service
attendance and subsequent health and well-being throughout adulthood:
Evidence from three prospective cohorts. \emph{International Journal of
Epidemiology}, \textbf{49}(6), 2030--2040.

\bibitem[\citeproctext]{ref-cristofori2016neural}
Cristofori, I, Bulbulia, J, Shaver, JH, Wilson, M, Krueger, F, and
Grafman, J (2016) Neural correlates of mystical experience.
\emph{Neuropsychologia}, \textbf{80}, 212--220.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-decoulanges1903}
De Coulanges, F (1903) \emph{La cité antique: Étude sur le culte, le
droit, les institutions de la grèce et de rome}, Hachette.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diaz2023lmtp}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2023) Nonparametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association},
\textbf{118}(542), 846--857.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diaz2021nonparametric}
Dı́az, I, Hejazi, NS, Rudolph, KE, and Der Laan, MJ van (2021)
Nonparametric efficient causal mediation with intermediate confounders.
\emph{Biometrika}, \textbf{108}(3), 627--641.

\bibitem[\citeproctext]{ref-Diaz2023}
Dı́az, I, Williams, N, and Rudolph, KE (2023) \emph{Journal of Causal
Inference}, \textbf{11}(1), 20220077.
doi:\href{https://doi.org/doi:10.1515/jci-2022-0077}{doi:10.1515/jci-2022-0077}.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017b) \emph{{N}ew {Z}ealand
socio-economic index 2013}, Wellington, New Zealand: Statistics New
Zealand-Tatauranga Aotearoa.

\bibitem[\citeproctext]{ref-fahy2017a}
Fahy, KM, Lee, A, and Milne, BJ (2017a) \emph{{N}ew {Z}ealand
socio-economic index 2013}, Wellington, New Zealand: Statistics New
Zealand-Tatauranga Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a {N}ew {Z}ealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-haneuse2013estimation}
Haneuse, S, and Rotnitzky, A (2013) Estimation of the effect of
interventions that modify the received treatment. \emph{Statistics in
Medicine}, \textbf{32}(30), 5260--5277.

\bibitem[\citeproctext]{ref-hazlett2022understanding}
Hazlett, C, and Wainstein, L (2022) Understanding, choosing, and
unifying multilevel and fixed effect approaches. \emph{Political
Analysis}, \textbf{30}(1), 46--65.

\bibitem[\citeproctext]{ref-hernan2024WHATIF}
Hernan, MA, and Robins, JM (2024) \emph{Causal inference: What if?},
Taylor \& Francis. Retrieved from
\url{https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/}

\bibitem[\citeproctext]{ref-hernan2024stating}
Hernán, MA, and Greenland, S (2024) Why stating hypotheses in grant
applications is unnecessary. \emph{JAMA}, \textbf{331}(4), 285--286.

\bibitem[\citeproctext]{ref-hernuxe1n2016}
Hernán, MA, Sauer, BC, Hernández-Díaz, S, Platt, R, and Shrier, I (2016)
Specifying a target trial prevents immortal time bias and other
self-inflicted injuries in observational analyses. \emph{Journal of
Clinical Epidemiology}, \textbf{79}, 70--75.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoverd_religious_2010}
Hoverd, WJ, and Sibley, CG (2010) Religious and denominational diversity
in {N}ew {Z}ealand 2009. \emph{New Zealand Sociology}, \textbf{25}(2),
59--87.

\bibitem[\citeproctext]{ref-huitfeldt2019collapsibility}
Huitfeldt, A, Stensrud, MJ, and Suzuki, E (2019) On the collapsibility
of measures of effect in the counterfactual causal framework.
\emph{Emerging Themes in Epidemiology}, \textbf{16}, 1--5.

\bibitem[\citeproctext]{ref-johnson2022global}
Johnson, BR, and VanderWeele, TJ (2022) The global flourishing study: A
new era for the study of well-being. \emph{International Bulletin of
Mission Research}, \textbf{46}(2), 272--275.

\bibitem[\citeproctext]{ref-johnson2005}
Johnson, DD (2005) God{'}s punishment and public goods: A test of the
supernatural punishment hypothesis in 186 world cultures. \emph{Human
Nature}, \textbf{16}, 410--446.

\bibitem[\citeproctext]{ref-johnson2015}
Johnson, DD (2015) Big gods, small wonder: Supernatural punishment
strikes back. \emph{Religion, Brain \& Behavior}, \textbf{5}(4),
290--298.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-kelly2024religiosity}
Kelly, JM, Kramer, SR, and Shariff, AF (2024) Religiosity predicts
prosociality, especially when measured by self-report: A meta-analysis
of almost 60 years of research. \emph{Psychological Bulletin},
\textbf{150}(3), 284--318.

\bibitem[\citeproctext]{ref-khanna1995charity}
Khanna, J, Posnett, J, and Sandler, T (1995) Charity donations in the
UK: New evidence based on panel data. \emph{Journal of Public
Economics}, \textbf{56}(2), 257--272.

\bibitem[\citeproctext]{ref-kim2019mediators}
Kim, ES, and VanderWeele, TJ (2019) Mediators of the association between
religious service attendance and mortality. \emph{American Journal of
Epidemiology}, \textbf{188}(1), 96--101.

\bibitem[\citeproctext]{ref-konvalinka2011synchronized}
Konvalinka, I, Xygalatas, D, Bulbulia, J, \ldots{} Roepstorff, A (2011)
Synchronized arousal between performers and related spectators in a
fire-walking ritual. \emph{Proceedings of the National Academy of
Sciences}, \textbf{108}(20), 8514--8519.

\bibitem[\citeproctext]{ref-van2012targeted}
Laan, MJ van der, and Gruber, S (2012) Targeted minimum loss based
estimation of causal effects of multiple time point interventions.
\emph{The International Journal of Biostatistics}, \textbf{8}(1).

\bibitem[\citeproctext]{ref-van2014discussion}
Laan, MJ van der, Luedtke, AR, and Dı́az, I (2014) Discussion of
identification, estimation and approximation of risk under interventions
that depend on the natural value of treatment using observational data,
by {J}essica {Y}oung, {M}iguel {H}ern{á}n, and {J}ames {R}obins.
\emph{Epidemiologic Methods}, \textbf{3}(1), 21--31.

\bibitem[\citeproctext]{ref-lang2015effects}
Lang, M, Krátkỳ, J, Shaver, JH, Jerotijević, D, and Xygalatas, D (2015)
Effects of anxiety on spontaneous ritualized behavior. \emph{Current
Biology}, \textbf{25}(14), 1892--1897.

\bibitem[\citeproctext]{ref-lash2020}
Lash, TL, Rothman, KJ, VanderWeele, TJ, and Haneuse, S (2020)
\emph{Modern epidemiology}, Wolters Kluwer. Retrieved from
\url{https://books.google.co.nz/books?id=SiTSnQEACAAJ}

\bibitem[\citeproctext]{ref-vanderweelechurchmortality}
Li, S, Stampfer, MJ, Williams, DR, and VanderWeele, TJ (2016)
{Association of Religious Service Attendance With Mortality Among
Women}. \emph{JAMA Internal Medicine}, \textbf{176}(6), 777--785.
doi:\href{https://doi.org/10.1001/jamainternmed.2016.1615}{10.1001/jamainternmed.2016.1615}.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-major2023exploring}
Major-Smith, D (2023) Exploring causality from observational data: An
example assessing whether religiosity promotes cooperation.
\emph{Evolutionary Human Sciences}, \textbf{5}, e22.

\bibitem[\citeproctext]{ref-mccullough2020kindness}
McCullough, ME (2020) \emph{The kindness of strangers: How a selfish ape
invented a new moral code}, Simon; Schuster.

\bibitem[\citeproctext]{ref-mccullough2016christian}
McCullough, ME, Swartwout, P, Shaver, JH, Carter, EC, and Sosis, R
(2016) Christian religious badges instill trust in christian and
non-christian perceivers. \emph{Psychology of Religion and
Spirituality}, \textbf{8}(2), 149.

\bibitem[\citeproctext]{ref-mcelreath2020}
McElreath, R (2020) \emph{Statistical rethinking: A {B}ayesian course
with examples in {R} and {S}tan}, CRC press.

\bibitem[\citeproctext]{ref-McLeod2020}
McLeod, J (2020) The {N}ew {Z}ealand {S}upport {R}eport: The current
state and significance of giving in {N}ew {Z}ealand and the outlook for
recipients., JBWere. Retrieved from
\url{https://www.jbwere.co.nz/media/1qudxw3q/jbwere-nz-support-report-digital.pdf}

\bibitem[\citeproctext]{ref-monsma2007religion}
Monsma, SV (2007) Religion and philanthropic giving and volunteering:
Building blocks for civic responsibility. \emph{Interdisciplinary
Journal of Research on Religion}, \textbf{3}.

\bibitem[\citeproctext]{ref-montgomery2018}
Montgomery, JM, Nyhan, B, and Torres, M (2018) How conditioning on
posttreatment variables can ruin your experiment and what to do about
It. \emph{American Journal of Political Science}, \textbf{62}(3),
760--775.
doi:\href{https://doi.org/10.1111/ajps.12357}{10.1111/ajps.12357}.

\bibitem[\citeproctext]{ref-diaz2012population}
Muñoz, ID, and Van Der Laan, M (2012) Population intervention causal
effects based on stochastic interventions. \emph{Biometrics},
\textbf{68}(2), 541--549.

\bibitem[\citeproctext]{ref-neal2020introduction}
Neal, B (2020) Introduction to causal inference from a machine learning
perspective. \emph{Course Lecture Notes (Draft)}. Retrieved from
\url{https://www.bradyneal.com/Introduction_to_Causal_Inference-Dec17_2020-Neal.pdf}

\bibitem[\citeproctext]{ref-norenzayan2016}
Norenzayan, A, Shariff, AF, Gervais, WM, \ldots{} Henrich, J (2016) The
cultural evolution of prosocial religions. \emph{Behavioral and Brain
Sciences}, \textbf{39}, e1.
doi:\href{https://doi.org/10.1017/S0140525X14001356}{10.1017/S0140525X14001356}.

\bibitem[\citeproctext]{ref-ogburn2021}
Ogburn, EL, and Shpitser, I (2021) Causal modelling: The two cultures.
\emph{Observational Studies}, \textbf{7}(1), 179--183.
doi:\href{https://doi.org/10.1353/obs.2021.0006}{10.1353/obs.2021.0006}.

\bibitem[\citeproctext]{ref-pawlikowski2019religious}
Pawlikowski, J, Białowolski, P, Węziak-Białowolska, D, and VanderWeele,
TJ (2019) Religious service attendance, health behaviors and
well-being---an outcome-wide longitudinal analysis. \emph{European
Journal of Public Health}, \textbf{29}(6), 1177--1183.

\bibitem[\citeproctext]{ref-polley2023}
Polley, E, LeDell, E, Kennedy, C, and Laan, M van der (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://CRAN.R-project.org/package=SuperLearner}

\bibitem[\citeproctext]{ref-richardson2013}
Richardson, TS, and Robins, JM (2013a) Single world intervention graphs:
A primer. In, Citeseer. Retrieved from
\url{https://core.ac.uk/display/102673558}

\bibitem[\citeproctext]{ref-richardson2013swigsprimer}
Richardson, TS, and Robins, JM (2013b) Single world intervention graphs:
A primer. In \emph{Second UAI workshop on causal structure learning,
{B}ellevue, {W}ashington}, Citeseer. Retrieved from
\url{https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=07bbcb458109d2663acc0d098e8913892389a2a7}

\bibitem[\citeproctext]{ref-richardson2023potential}
Richardson, TS, and Robins, JM (2023) Potential outcome and decision
theoretic foundations for statistical causality. \emph{Journal of Causal
Inference}, \textbf{11}(1), 20220012.

\bibitem[\citeproctext]{ref-robins1992}
Robins, JM, and Greenland, S (1992) Identifiability and exchangeability
for direct and indirect effects. \emph{Epidemiology}, \textbf{3}(2),
143--155.

\bibitem[\citeproctext]{ref-robins2010alternative}
Robins, JM, and Richardson, TS (2010) Alternative graphical causal
models and the identification of direct effects. \emph{Causality and
Psychopathology: Finding the Determinants of Disorders and Their Cures},
\textbf{84}, 103--158.

\bibitem[\citeproctext]{ref-schloss2011evolutionary}
Schloss, JP, and Murray, MJ (2011) Evolutionary accounts of belief in
supernatural punishment: A critical review. \emph{Religion, Brain \&
Behavior}, \textbf{1}(1), 46--99.

\bibitem[\citeproctext]{ref-shaver2015evolution}
Shaver, JH (2015) The evolution of stratification in fijian ritual
participation. \emph{Religion, Brain \& Behavior}, \textbf{5}(2),
101--117.

\bibitem[\citeproctext]{ref-shaver2020church}
Shaver, JH, Power, EA, Purzycki, BG, \ldots{} Bulbulia, JA (2020) Church
attendance and alloparenting: An analysis of fertility, social support
and child development among {E}nglish mothers. \emph{Philosophical
Transactions of the Royal Society B}, \textbf{375}(1805), 20190428.

\bibitem[\citeproctext]{ref-shpitser2016causal}
Shpitser, I, and Tchetgen, ET (2016) Causal inference with a graphical
hierarchy of interventions. \emph{Annals of Statistics}, \textbf{44}(6),
2433.

\bibitem[\citeproctext]{ref-sibley2012}
Sibley, C. G., and Bulbulia, JA (2012) Healing those who need healing:
How religious practice affects social belonging. \emph{Journal for the
Cognitive Science of Religion}, \textbf{1}, 29--45.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the {N}ew {Z}ealand {A}ttitudes and {V}alues
{S}tudy}}.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in {N}ew {Z}ealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-sosis2005does}
Sosis, R (2005) Does religion promote trust?: The role of signaling,
reputation, and punishment. \emph{Interdisciplinary Journal of Research
on Religion}, \textbf{1}.

\bibitem[\citeproctext]{ref-sosis2003cooperation}
Sosis, R, and Bressler, ER (2003) Cooperation and commune longevity: A
test of the costly signaling theory of religion. \emph{Cross-Cultural
Research}, \textbf{37}(2), 211--239.

\bibitem[\citeproctext]{ref-swanson1967}
Swanson, GE (1967) Religion and regime: A sociological account of the
{R}eformation.

\bibitem[\citeproctext]{ref-van2014targeted}
Van der Laan, MJ (2014) Targeted estimation of nuisance parameters to
obtain valid statistical inference. \emph{The International Journal of
Biostatistics}, \textbf{10}(1), 29--57.

\bibitem[\citeproctext]{ref-vantongeren2020}
Van Tongeren, DR, DeWall, CN, Chen, Z, Sibley, CG, and Bulbulia, J
(2020) Religious residue: Cross-cultural evidence that religious
psychology and behavior persist following deidentification.
\emph{Journal of Personality and Social Psychology}.

\bibitem[\citeproctext]{ref-vanderweele2015}
VanderWeele, TJ (2015) \emph{Explanation in causal inference: Methods
for mediation and interaction}, Oxford University Press.

\bibitem[\citeproctext]{ref-vanderweele2017causaleffectsService}
VanderWeele, TJ (2017) Causal effects of religious service attendance?
\emph{Social Psychiatry and Psychiatric Epidemiology}, \textbf{52},
1331--1336.

\bibitem[\citeproctext]{ref-vanderweele2019}
VanderWeele, TJ (2019) Principles of confounder selection.
\emph{European Journal of Epidemiology}, \textbf{34}(3), 211--219.

\bibitem[\citeproctext]{ref-vanderweele2021can}
VanderWeele, TJ (2021a) Can sophisticated study designs with regression
analyses of observational data provide causal inferences? \emph{JAMA
Psychiatry}, \textbf{78}(3), 244--246.

\bibitem[\citeproctext]{ref-vanderweele2021effectsReligiousServiceMetanalysis}
VanderWeele, TJ (2021b) Effects of religious service attendance and
religious importance on depression: Examining the meta-analytic
evidence. \emph{The International Journal for the Psychology of
Religion}, \textbf{31}(1), 21--26.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the {E}-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 1--20.

\bibitem[\citeproctext]{ref-vanderweele2012MEASUREMENT}
VanderWeele, TJ, and Hernán, MA (2012) Results on differential and
dependent measurement error of the exposure and the outcome using signed
directed acyclic graphs. \emph{American Journal of Epidemiology},
\textbf{175}(12), 1303--1310.
doi:\href{https://doi.org/10.1093/aje/kwr458}{10.1093/aje/kwr458}.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437--466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-watts2016}
Watts, J, Bulbulia, J. A., Gray, RD, and Atkinson, QD (2016) Clarity and
causality needed in claims about big gods., \textbf{39}, 41--42.
doi:\href{https://doi.org/DOI:10.1017/S0140525X15000576}{DOI:10.1017/S0140525X15000576}.

\bibitem[\citeproctext]{ref-watts2015}
Watts, J, Greenhill, SJ, Atkinson, QD, Currie, TE, Bulbulia, J, and
Gray, RD (2015) \emph{Broad supernatural punishment but not moralizing
high gods precede the evolution of political complexity in
{A}ustronesia} \emph{Proceedings of the Royal Society B: Biological
Sciences}, Vol. 282, The Royal Society, 20142556.

\bibitem[\citeproctext]{ref-westreich2013}
Westreich, D, and Greenland, S (2013) The table 2 fallacy: Presenting
and interpreting confounder and modifier coefficients. \emph{American
Journal of Epidemiology}, \textbf{177}(4), 292--298.

\bibitem[\citeproctext]{ref-wheatley1971}
Wheatley, P (1971) \emph{The pivot of the four quarters : A preliminary
enquiry into the origins and character of the ancient chinese city},
Edinburgh University Press. Retrieved from
\url{https://cir.nii.ac.jp/crid/1130000795717727104}

\bibitem[\citeproctext]{ref-whitehouse2023}
Whitehouse, H, Francois, P, Savage, PE, \ldots{} Turchin, P (2023)
Testing the big gods hypothesis with global historical data: A review
and retake. \emph{Religion, Brain \& Behavior}, \textbf{13}(2),
124--166.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{{l}mtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\bibitem[\citeproctext]{ref-woodyard2014doing}
Woodyard, A, and Grable, J (2014) Doing good and feeling well: Exploring
the relationship between charitable activity and perceived personal
wellness. \emph{VOLUNTAS: International Journal of Voluntary and
Nonprofit Organizations}, \textbf{25}, 905--928.

\bibitem[\citeproctext]{ref-Ranger2017}
Wright, MN, and Ziegler, A (2017) {ranger}: A fast implementation of
random forests for high dimensional data in {C++} and {R}. \emph{Journal
of Statistical Software}, \textbf{77}(1), 1--17.
doi:\href{https://doi.org/10.18637/jss.v077.i01}{10.18637/jss.v077.i01}.

\bibitem[\citeproctext]{ref-young2014identification}
Young, JG, Hernán, MA, and Robins, JM (2014) Identification, estimation
and approximation of risk under interventions that depend on the natural
value of treatment using observational data. \emph{Epidemiologic
Methods}, \textbf{3}(1), 1--19.

\end{CSLReferences}



\end{document}
