% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  singlecolumn]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=20mm,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/templates/latex/custom-commands.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal effect of religious service attendance on charitable donations and volunteering, minority-group-attitudes, and help-received: evidence from a national panel study},
  pdfauthor={Joseph A. Bulbulia; Chris G. Sibley},
  pdfkeywords={Causal
Inference, Charity, Church, Cooperation, Religion, Shift
Intervention, Volunteering},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal effect of religious service attendance on charitable
donations and volunteering, minority-group-attitudes, and help-received:
evidence from a national panel study}
\author{Joseph A. Bulbulia \and Chris G. Sibley}
\date{2024-02-09}

\begin{document}
\maketitle
\begin{abstract}
This study employs panel data from the New Zealand Attitudes and Values
Study, a longitudinal survey of 30,000 New Zealanders, to examine the
causal impact of religious service attendance on prosocial behaviors
across three dimensions: charitable donations and volunteering,
attitudes towards minority groups (``warmth''), and help received from
others---a novel metric. Our analysis distinguishes between the effects
of initiating weekly religious service attendance for non-attendees and
ceasing any religious participation. Additionally, we conduct a parallel
comparison with a general shifts in community social engagement to
discern the unique contributions of religious service to prosociality.
\textbf{Charitable Donations and Volunteering}: Findings indicate that
regular attendance at religious services increases annual charitable
donations by approximately \$700 per adult, without a corresponding
effect from general social engagement. Both activities, however,
similarly elevate volunteering rates. \textbf{Prejudice Reduction}:
Attendance at religious services enhances warmth towards all social
groupsl. In contrast, general social engagement only reliably improves
attitudes towards Māori, New Zealand's largest minority group.
\textbf{Help Received}: Engagement in regular religious services leads
to increased community support, but not too greater support from family
and friends. Conversely, general social engagement boosts support from
family and friends but not from the community. The discontinuation of
any religious service attendance results in reduced volunteering but
does not affect charitable donations, suggesting that religious service
may foster enduring charitable habits. In summary, acquiring religious
service attendance enhances charitable giving and reduces prejudice more
effectively than mere social engagement, with the cessation of religious
services demonstrating distinct outcomes. This supports theories
proposing that religious involvement cultivates charitable dispositions.
\end{abstract}

\subsection{Introduction}\label{introduction}

A central question in the scientific study of religion is whether
religion causes cooperation. However, to quantitatively address this
question is challenging. Core features of religion cannot are
inaccessible to experiments. In observational data, the task of
disentangling correlation from causation is formidable, for similar
reasons. Whether investigators have disentangled the specific causal
effects of religion from background influences is a question that cannot
be verified by the data. Moreover most studies that have investigated
religion, even longitudinal studies, fall back on correlational models.

Here, we leveraging the comprehensive panel data from the New Zealand
Attitudes and Values Study from over thirty thousand New Zealanders in a
nationally representative sample and use minimally restrictive, robust
statistical models to investigate the specific effects of inverventions
on religious service attendance on prosocial behaviors in three
domeains: charitable giving and volunteerism; (2) attitudes towards
minorities, and (3) the reception of aid from the community. By
distinguishing and quantifying the specific effects of commencing or
discontinuing religious service attendance and comparing these effects
to interventions on social engagement, we clarify the specific
contributions of religious involvement to prosociality across a diverse,
multi-culural western society.

Finally, we compute the economic value of religious service attendance
on prosocial behaviors. This estimation provides a concrete measure of
religious involvement's ``cash value'' in the New Zealand economy
(\citeproc{ref-bulbulia2022}{Bulbulia 2022};
\citeproc{ref-bulbulia2023a}{Bulbulia \emph{et al.} 2023};
\citeproc{ref-bulbulia2023}{Bulbulia 2023};
\citeproc{ref-hernan2023}{Hernan and Robins 2023};
\citeproc{ref-vanderweele2015}{VanderWeele 2015}))

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of The New Zealand Attitudes and Values
Study (NZAVS) is an annual longitudinal national probability panel study
of social attitudes, personality, ideology and health outcomes. The
NZAVS began in 2009. It includes questionnaire responses from more
almost 70,000 New Zealand residents. The study includes researchers from
many New Zealand universities, including the University of Auckland,
Victoria University of Wellington, the University of Canterbury, the
University of Otago, and Waikato University. Because the survey asks the
same people to respond each year, it can track subtle change in
attitudes and values over time, and is an important resource for
researchers both in New Zealand and around the world. The NZAVS is
university-based, not- for-profit and independent of political or
corporate funding.https://doi.org/10.17605/OSF.IO/75SNB

\subsubsection{Causal Contrast}\label{causal-contrast}

Here, we leverage panel data to estimate potential outcomes in a
hypothetical world in which all individuals were attend at least four
religious services per month (weekly) and contrast this estimates
against outcomes against the natural values of the treatment observed in
the data.

Thus whereas in standard causal inference, the average treatment effect
is given as a simple contrast between the entire population when set to
one of two causal contrast conditions:

\[ \text{Average Treatment Effect} = E[Y(a*)|A,L] - E[Y(a)|A,L] \]

Our casusal estimand is takes a ``shift function'' or ``modified
treatment policy'' such that:

\[ \text{Average Treatment Effect} = E[Y(a*)|\textcolor{red}{f(A)},L] - E[Y(a)|A,L] \]

Where the intervention the treatment conditoin is defined by a shift
function applied to the treatment variable, accross the entire study
population. The functional can be stated

\[f(A = a*) = \begin{cases} 4 & \text{if } A < 4  \text{ monthly religious service attendance} \\ \tilde{A} & \text{if } A \geq 4  \text{ monthly religious service attendance} \end{cases} \]

Where \(\tilde{A}\) is is computed the expected outcome when \(A\) is
set to its naturally occurring value such that

\[\tilde{A} = A|L\]

This same expression is given for the contrast condition, where
\(Y(a)|A,L\) is given as \(Y(a)|\tilde{A}|L\)

\textbf{Comparative intervention: the causal effects of socialising at
least two hours per week}

For qualitative purposes, we performed an additional set of analyses
investigating the causal effects of socialising across the three domains
of prosociality that we considered for religious service:

\[f(A) = \begin{cases} 1.4 & \text{if } A \leq 1.4 \text{ hours socialising with community} \\ A & \text{if } A >  1.4  \text{ hours socialising with community}  \end{cases} \]

Thus, we estimate outcomes in a hypothetical world in which all
individuals were attend socialise at least for at least the amount of
time that church service brings people into contact with a religious
community.

Likewise, because loss of socialising might not be equivalent to a gain
of religious service attendance, we investigated the causal effect of
losing all community socialising :

\[f(A) = 0 \] We contrasted this expected values of this shift
intervention with those of the naturally occurring expected outcome from
socialising at the observed level, again focussing on cooperative
behaviours.

We note that this contrast for socialising is does not afford a direct
comparison with religious service attendance. In particular, one of the
ways in which one socialises is by attending religious service.
Volunteering is often, although not always, a social activity. However,
these differences suggest a relatively conservative backdrop with which
to compare religious service. If religious service effects, either
positive or negative, were to appear relatively strong against this
backdrop, we might infer that the effects of religious service comprised
features unique to its religious elements.

\paragraph{Loss of religion and of
socialing}\label{loss-of-religion-and-of-socialing}

Because the gain of religion might be different from the loss of
religion, we additionally contrast the population average outcome were
everyone to stop attending monthly religious service verse the expected
outcome at the natural treatment values:

\[f(A) = 0 \]

Thus we estimated outcomes for a hypothetical world in which no
individuals attended religious service, contrasting this with expected
outcomes for the world as it observed. We conducted a parrallel analysis
for socialisation.

\subsubsection{Identification
assumptions}\label{identification-assumptions}

The objective of this study is to consistently evaluate magnitudes of
causal effects. We cannot observe interventions that did not occur. In
observational studies, investigators do not generally have the
advantages of randomisation to ensure balance across treatments in the
variables that might affect the outcomes within treatments that are
compared. Nor do investigators have the power to control the treatments
administered.

The three assumptions needed to consistently estimate causal effects
are:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal consistency}: we assume that the outcomes observed
  under the treatments in the data correspond to the potential outcomes
  to be compared, and that the potential outcomes are independent of the
  versions of treatment administered, conditional on measured
  covariates.
\item
  \textbf{Exchangeability}: we assume that, given specific observed
  covariates, the treatment assignment is independent of potential
  outcomes.
\item
  \textbf{Positivity}: we assume that every subject has a non-zero
  probability of receiving the treatment, irrespective of covariates. We
  evaluate this assumption by assessing change in the exposures.
\end{enumerate}

This causal consistency assumption cannot be verified by data. We
discuss the implications of treatment-heterogeniety in the discussion.
Nor can the conditional exchangeability assumption be verified by data.
We use sensitivity analysis to assess the robustness of our results to
unmeasured confounding. We evaluate positivity by evaluating and
reporting the number of cases in which individuals transitioned from the
state of the treatment in the baseline condition to a different state
the exposure wave.

\subsubsection{Analysis}\label{analysis}

We employ a semi-parametric estimator known as Targeted Minimum
Loss-based Estimation (TMLE), which is adept at estimating the causal
effect of modified treatment policies on outcomes over time.
Estimatation was performed using \texttt{lmtp} package
(\citeproc{ref-williams2021}{Williams and Díaz 2021}). TMLE is a robust
method that combines machine learning techniques with traditional
statistical models to estimate causal effects while providing valid
statistical uncertainty measures for these estimates.

TMLE operates through a two-step process involving both outcome and
treatment (exposure) models. Initially, it employes machine learning
algorithms to flexibly model the relationship between treatments,
covariates, and outcomes. This flexibility allows TMLE to account for
complex, high-dimensional covariate spaces without imposing restrictive
model assumptions. The outcome of this step is a set of initial
estimates for these relationships.

The second step of TMLE involves ``targeting'' these initial estimates
by incorporating information about the observed data distribution to
improve the accuracy of the causal effect estimate. This is achieved
through an iterative updating process, which adjusts the initial
estimates towards the true causal effect. This updating process is
guided by the efficient influence function, ensuring that the final TMLE
estimate is as close as possible to the true causal effect while still
being robust to model misspecification in either the outcome or
treatment model.

A central feature of TMLE is its double-robustness property, meaning
that if either the model for the treatment or the outcome is correctly
specified, the TMLE estimator will still consistently estimate the
causal effect. Additionally, TMLE uses cross-validation to avoid
overfitting and ensure that the estimator performs well in finite
samples. Each of these steps contributes to a robust methodology for
examining the \emph{causal} effects on of interventions on outcomes. The
marriage of TMLE and machine learning technologies reduces the
dependence on restrictive modelling assumptions and introduces an
additional layer of robustness. For further details see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023})

\subsubsection{Eligibility criteria for inclusion in the causal effects
of shifting to a gain of weekly religious service
attendance}\label{eligibility-criteria-for-inclusion-in-the-causal-effects-of-shifting-to-a-gain-of-weekly-religious-service-attendance}

The sample consisted of respondents to NZAVS waves 2018 (baseline), 2019
(exposure wave), and 2020 (outcome wave) (years 2018-2021) (See Appendix
A.)

\paragraph{Inclusion Criteria:}\label{inclusion-criteria}

\begin{itemize}
\tightlist
\item
  Participants who provided full information about both religious
  service attendance and hours socialising at the baseline wave (NZAVS
  time 10, years 2018-10) and exposure wave (NZAVS wave 2019-20) were
  included.
\item
  Missing data for all variables at baseline were allowed. Missing data
  at baseline were imputed through the \texttt{mice} package
  (\citeproc{ref-vanbuuren2018}{Van Buuren 2018}).
\item
  Inverse probability of censoring weights were calculated as part of
  estimation in \texttt{lmtp} to adjust for missing outcomes at NZAVS
  Time 12 (years 2020-2021, the outcome wave). This allow for adjustment
  owing to attition and loss to follow up (see details of the
  \texttt{lmtp} package (\citeproc{ref-williams2021}{Williams and Díaz
  2021}))
\end{itemize}

\subparagraph{Exluded}\label{exluded}

\begin{itemize}
\tightlist
\item
  Participants who did not respond to the religious service attendance
  question at baseline or the exposure wave.
\item
  Participants who did not respond to the hours socialising question at
  baseline or the exposure wave.
\item
  We allowed loss-to-follow up in the outcome wave (NZAVS wave 2020);
  missing values owing to attrition and non-response were were handled
  using censoring weights.
\end{itemize}

There were 32058 NZAVS participants who met these criteria.

\subsubsection{Confounding control}\label{confounding-control}

Effects should temporally succeed their causes. To circumvent reverse
causation issues, outcomes were assessed in the year succeeding
exposure, specifically the 2020 wave of the NZAVS. The causal diagram in
Figure~\ref{fig-outcomewide-dag} outlines our approach to confounding
control. We align with VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020}) in employing a \emph{modified
disjunctive cause criterion}, as follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Identify all relevant confounders}: initially, enumerate all
  covariates affecting either the exposure or the outcomes across five
  domains, or both. These factors encompass variables influencing
  exposure or outcome and variables that could be consequences of such
  factors
\item
  \textbf{Remove instrumental variables}: subsequently, remove any
  factors identified as instrumental variables---factors influencing the
  exposure but not the outcome. The inclusion of instrumental variables
  diminishes efficiency.
\item
  \textbf{Include proxy variables for unmeasured common causes}: for
  unmeasured variables affecting both exposure and outcome, attempt to
  include a proxy variable. A proxy serves as a consequent of the
  unmeasured variable.
\item
  \textbf{Control for baseline exposure}: accounting for prior exposure
  is imperative for assessing incident exposure as opposed to prevalent
  exposure. This step enhances confounding control and aids in
  sidestepping reverse causation and other unmeasured confounders. This
  ensures that any unmeasured confounder would need to affect both the
  outcome and the initial exposure, regardless of prior exposure levels,
  to account for an observed exposure-outcome association
  (\citeproc{ref-danaei2012}{Danaei \emph{et al.} 2012};
  \citeproc{ref-hernan2023}{Hernan and Robins 2023}).
\item
  \textbf{Control for baseline outcome}: controlling for the outcome at
  baseline is crucial for ruling out reverse causation. While this does
  not fully preclude reverse causation, it minimises its impact.
  Therefore, the baseline outcome, along with a comprehensive set of
  covariates, should be part of the model to render the confounding
  control assumption plausible. The baseline outcome often serves as the
  most potent confounder affecting both the exposure and subsequent
  outcome (\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.}
  2020}).
\end{enumerate}

To mitigate bias from missing data due to non-response or panel
attrition, we imputed missing values using the mice package in R
(\citeproc{ref-vanbuuren2018}{Van Buuren 2018}). To address non-response
or missingness at follow-up, we employed censoring weights, integrated
into our semi-parametric models. Valid inferences for the New Zealand
population were secured by applying post-stratification census weights
for age, European ethnicity, and gender.

\subsubsection{Study 2: socialising}\label{study-2-socialising}

\subsubsection{Multi-dimensional indicators of
prosociality}\label{multi-dimensional-indicators-of-prosociality}

We assessed well-being following VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020}) outcome-wide template.
Outcomewide studies argue that, rather than cherry-picking one or
several domains of well-being, science may advance more rapidly, and
with greater hope for replication, by assess well-being across as many
range of indicators the data may afford. To assist with interpretation,
VanderWeele \emph{et al.} (\citeproc{ref-vanderweele2020}{2020}) groups
well-being into larger dimensions of interest. Here, we identify
five-domains: health, embodied well-being, practical well-being,
reflective well-being, and social well-being (see Appendix C.)

\newpage{}

\begin{figure}

\centering{

\includegraphics[width=0.8\textwidth,height=\textheight]{man-lmtp-ow-coop-church_files/figure-pdf/fig-outcomewide-dag-1.pdf}

}

\caption{\label{fig-outcomewide-dag}Causal graph: three-wave panel
design with selection bias. By controling for confounding at baseline we
block back-door paths that might lead to an association between the
treatment and the outcome. Adding previous measurments of the exposure
and outcome at baseline further reduces confounding. Nevertheless,
because we cannot ensure all confounding paths have been blocked, we
perform sensitivity analysis. These allow us to ask, how strong would
the unmeasured confounder need to be in its association with the
treatment and the outcome to explain away the observed association.}

\end{figure}%

\newpage{}

\newpage{}

\subsection{Results}\label{results}

\subsubsection{Religious service
attendance}\label{religious-service-attendance}

\subsubsection{Change in religious service from baseline to exposure
wave}\label{change-in-religious-service-from-baseline-to-exposure-wave}

Table~\ref{tbl-transition} shows a transition matrix captures stability
and movement between monthly religious service from the baseline (NZAVS
time 10) wave and exposure wave (NZAVS time 11). Entries on the diagonal
(in bold) indicate the number of individuals who stayed in their initial
state. In contrast, the off-diagonal shows the transitions from the
initial state (bold) to another state the following wave (off diagnal).
A cell located at the intersection of row \(i\) and column \(j\), where
\(i \neq j\), shows the count of individuals moving from state \(i\) to
state \(j\).

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1196}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}@{}}
\caption{Transition matrix for change in religious service attendance
from baseline to the exposure wave}\label{tbl-transition}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 0 & \textbf{25888} & 391 & 166 & 69 & 118 & 24 & 10 & 8 & 64 \\
State 1 & 628 & \textbf{227} & 84 & 42 & 43 & 5 & 2 & 3 & 9 \\
State 2 & 227 & 93 & \textbf{181} & 100 & 93 & 12 & 11 & 2 & 19 \\
State 3 & 103 & 52 & 104 & \textbf{155} & 166 & 17 & 7 & 4 & 14 \\
State 4 & 141 & 69 & 127 & 199 & \textbf{841} & 121 & 59 & 16 & 87 \\
State 5 & 21 & 7 & 17 & 17 & 140 & \textbf{58} & 24 & 7 & 32 \\
State 6 & 14 & 5 & 12 & 16 & 82 & 21 & \textbf{27} & 5 & 35 \\
State 7 & 8 & 0 & 6 & 3 & 16 & 6 & 9 & \textbf{5} & 18 \\
State 8 & 67 & 14 & 17 & 14 & 104 & 34 & 40 & 17 & \textbf{339} \\
\end{longtable}

Table~\ref{tbl-transition-2} presents a summary of those movements at
the boundary of weekly religious service. 28,510 participants attended
religious service less than four times per-week in both the baseline
wave (NZAVS time 10) and the exposure wave (NAVS time 11); 2143
attending at least weekly in both waves. Of those who did not attend at
least least weekly at baseline, 631 initiated attendance. Of those who
attended at least weekly 774 attended less than weekly. This table is
merely to summarise the movements presented in
Table~\ref{tbl-transition}. An advantage of a shift intervention is
flexibility in imagined intervention. We do not require, for example
that the entire population shifts to for example exactly 1 x weekly
religious service attendance, and alternatively that the entire
population shifts to exactly zero religious service attendance. Rather
we compare a shift intervention in which people attend at least weekly
perhaps attending more if that is their natural level attendance,
against an intervention in which people attend at the natural level at
which they are already attending. Hence, Table~\ref{tbl-transition-2} is
for illustration.

\begin{longtable}[]{@{}ccc@{}}
\caption{Transition matrix for change in religious service attendance
from baseline to the exposure
wave}\label{tbl-transition-2}\tabularnewline
\toprule\noalign{}
From & \textless{} weekly & \textgreater= weekly \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & \textless{} weekly & \textgreater= weekly \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textless{} weekly & \textbf{28510} & 631 \\
\textgreater= weekly & 774 & \textbf{2143} \\
\end{longtable}

\subsubsection{Weekly religious service effects on charitable donations
and
volunteering}\label{weekly-religious-service-effects-on-charitable-donations-and-volunteering}

\begin{verbatim}
[1] 32058
\end{verbatim}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-coop-church_files/figure-pdf/fig-results-church-on-prosociality-1.pdf}

}

\caption{\label{fig-results-church-on-prosociality}Results for effect of
religious service on charitable donations and volunteering:
z-transformed}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4066}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1758}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0989}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0989}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0879}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1319}}@{}}

\caption{\label{tbl-results-church-on-prosociality}Table of results for
effect of religious service on charitable donations and volunteering:
data scale}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Donations: religious service \textgreater= 1 & 708.8056 & 609.4522 &
808.1590 & 1.5371 & 1.4826 \\
Volunteering: religious service \textgreater= 1 & 0.4029 & 0.2876 &
0.5182 & 1.4132 & 1.3311 \\

\end{longtable}

\subsubsection{Weekely religious service effects minority-group
prejudice/acceptance}\label{weekely-religious-service-effects-minority-group-prejudiceacceptance}

\begin{verbatim}
[1] 32058
\end{verbatim}

\begin{figure}

\centering{

\includegraphics{man-lmtp-ow-coop-church_files/figure-pdf/fig-results-church-on-prejudice-1.pdf}

}

\caption{\label{fig-results-church-on-prejudice}Results for effect of
religious service on prejudice: z-transformed outcomes}

\end{figure}%

\newpage{}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4848}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1616}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0808}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0707}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0808}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1212}}@{}}

\caption{\label{tbl-results-church-on-prejudice}Table of results for
effect of religious service on charitable donations and volunteering:
data scale}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Warm Asians: religious service \textgreater= 1 & 0.0972 & 0.0636 &
0.1308 & 1.4103 & 1.3113 \\
Warm Chinese: religious service \textgreater= 1 & 0.0679 & 0.0384 &
0.0974 & 1.3241 & 1.2280 \\
Warm Immigrants: religious service \textgreater= 1 & 0.1031 & 0.0748 &
0.1315 & 1.4271 & 1.3454 \\
Warm Indians: religious service \textgreater= 1 & 0.0857 & 0.0565 &
0.1148 & 1.3772 & 1.2886 \\
Warm Elderly: religious service \textgreater= 1 & 0.1374 & 0.1098 &
0.1650 & 1.5217 & 1.4459 \\
Warm Maori: religious service \textgreater= 1 & 0.1442 & 0.1164 & 0.1721
& 1.5401 & 1.4643 \\
Warm Mental Illness: religious service \textgreater= 1 & 0.0730 & 0.0433
& 0.1028 & 1.3396 & 1.2445 \\
Warm Muslims: religious service \textgreater= 1 & 0.0299 & -0.0002 &
0.0600 & 1.1959 & 1.0000 \\
Warm NZEuro: religious service \textgreater= 1 & 0.1174 & 0.0893 &
0.1455 & 1.4670 & 1.3881 \\
Warm Overweight: religious service \textgreater= 1 & 0.1448 & 0.1130 &
0.1767 & 1.5417 & 1.4545 \\
Warm Pacific: religious service \textgreater= 1 & 0.1237 & 0.0940 &
0.1534 & 1.4843 & 1.4011 \\
Warm Refugees: religious service \textgreater= 1 & 0.1405 & 0.1115 &
0.1694 & 1.5301 & 1.4507 \\
Perc. Religious Discrim: religious service \textgreater= 1 & 0.3712 &
0.3347 & 0.4077 & 2.1524 & 2.0512 \\

\end{longtable}

Figure~\ref{fig-results-church-on-prejudice} and
Table~\ref{tbl-results-church-on-prejudice} presents the Population
Average Treatment Effect (PATE) for the embodied domain.

For the outcome `Perc. Religious Discrim: weekly church \textgreater=
1', the PATE causal contrast is 0.371. The confidence interval ranges
from 0.335 to 0.408. The E-value for this outcome is 2.152, indicating
reliable evidence for causality.

For the outcome `Warm Overweight: weekly church \textgreater= 1', the
PATE causal contrast is 0.145. The confidence interval ranges from 0.113
to 0.177. The E-value for this outcome is 1.542, indicating reliable
evidence for causality.

For the outcome `Warm Maori: weekly church \textgreater= 1', the PATE
causal contrast is 0.144. The confidence interval ranges from 0.116 to
0.172. The E-value for this outcome is 1.54, indicating reliable
evidence for causality.

For the outcome `Warm Refugees: weekly church \textgreater= 1', the PATE
causal contrast is 0.141. The confidence interval ranges from 0.112 to
0.169. The E-value for this outcome is 1.53, indicating reliable
evidence for causality.

For the outcome `Warm Elderly: weekly church \textgreater= 1', the PATE
causal contrast is 0.137. The confidence interval ranges from 0.11 to
0.165. The E-value for this outcome is 1.522, indicating reliable
evidence for causality.

For the outcome `Warm Pacific: weekly church \textgreater= 1', the PATE
causal contrast is 0.124. The confidence interval ranges from 0.094 to
0.153. The E-value for this outcome is 1.484, indicating reliable
evidence for causality.

For the outcome `Warm NZEuro: weekly church \textgreater= 1', the PATE
causal contrast is 0.117. The confidence interval ranges from 0.089 to
0.146. The E-value for this outcome is 1.467, indicating reliable
evidence for causality.

For the outcome `Warm Immigrants: weekly church \textgreater= 1', the
PATE causal contrast is 0.103. The confidence interval ranges from 0.075
to 0.132. The E-value for this outcome is 1.427, indicating reliable
evidence for causality.

For the outcome `Warm Asians: weekly church \textgreater= 1', the PATE
causal contrast is 0.097. The confidence interval ranges from 0.064 to
0.131. The E-value for this outcome is 1.41, indicating reliable
evidence for causality.

For the outcome `Warm Indians: weekly church \textgreater= 1', the PATE
causal contrast is 0.086. The confidence interval ranges from 0.056 to
0.115. The E-value for this outcome is 1.377, indicating reliable
evidence for causality.

For the outcome `Warm Mental Illness: weekly church \textgreater= 1',
the PATE causal contrast is 0.073. The confidence interval ranges from
0.043 to 0.103. The E-value for this outcome is 1.34, indicating
reliable evidence for causality.

For the outcome `Warm Chinese: weekly church \textgreater= 1', the PATE
causal contrast is 0.068. The confidence interval ranges from 0.038 to
0.097. The E-value for this outcome is 1.324, indicating reliable
evidence for causality.

For the outcome `Warm Muslims: weekly church \textgreater= 1', the PATE
causal contrast is 0.03. The confidence interval ranges from 0 to 0.06.
The E-value for this outcome is 1.196, indicating evidence for causality
is weak.

\newpage{}

\subsubsection{Socialisation}\label{socialisation}

Table~\ref{tbl-transition-socialising} shows a transition matrix
captures the movement between weekly hours socialising during the
baseline (NZAVS time 10) wave and exposure wave (NZAVS time 11). Entries
on the diagonal (in bold) indicate the number of individuals who stayed
in their initial state. In contrast, the off-diagonal shows the
transitions from the initial state (bold) to another state the following
wave (off diagnal). Again, a cell located at the intersection of row
\(i\) and column \(j\), where \(i \neq j\), shows the count of
individuals moving from state \(i\) to state \(j\).

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1183}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1075}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0968}}@{}}
\caption{Transition matrix for change in the square of hours socialing
with community each
week}\label{tbl-transition-socialising}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 0 & \textbf{20039} & 2243 & 1192 & 221 & 25 & 12 & 7 & 3 & 6 \\
State 1 & 2288 & \textbf{1389} & 731 & 103 & 11 & 4 & 3 & 0 & 0 \\
State 2 & 1328 & 660 & \textbf{806} & 161 & 29 & 6 & 2 & 1 & 2 \\
State 3 & 236 & 101 & 151 & \textbf{76} & 17 & 5 & 1 & 0 & 0 \\
State 4 & 55 & 16 & 32 & 17 & \textbf{11} & 3 & 1 & 2 & 0 \\
State 5 & 16 & 5 & 8 & 4 & 3 & \textbf{0} & 1 & 0 & 0 \\
State 6 & 8 & 1 & 0 & 0 & 1 & 0 & \textbf{0} & 0 & 1 \\
State 7 & 3 & 1 & 1 & 1 & 0 & 0 & 0 & \textbf{0} & 0 \\
State 8 & 3 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & \textbf{1} \\
\end{longtable}

@Table~\ref{tbl-transition-socialising} presents a summary of changes in
socialising at the threshold that we compared. When shifting to
socialising at least 1.4 hours per week, we imagine `treating' 25,959
cases. Again this table is for illustration, as the the shift
intervention allows us to flexibly contrast cases without projecting the
entire population in to one or another cell.

\begin{longtable}[]{@{}ccc@{}}
\caption{Transition matrix for change in the square of hours socialing
with community each
week}\label{tbl-transition-socialising-shift}\tabularnewline
\toprule\noalign{}
From & \textless{} 1.4 weekly hours & \textgreater= 1.4 weekly hours \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & \textless{} 1.4 weekly hours & \textgreater= 1.4 weekly hours \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textless{} 1.4 weekly hours & \textbf{25959} & 2318 \\
\textgreater= 1.4 weekly hours & 2434 & \textbf{1347} \\
\end{longtable}

\subsubsection{Summary of findings}\label{summary-of-findings}

\subsubsection{Assumptions and
limitations}\label{assumptions-and-limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causality and confounding}: we employs rigorous causal
  inference techniques, but these are contingent on the assumption of no
  unmeasured confounding. (Say more about E-values\ldots)
\item
  \textbf{Measurement error}: the variables under
  consideration---exercise and sleep---are self-reported, which might
  introduce both systematic and random measurement errors. It should be
  specifically noted that the apparent modesty of the practical effects
  could arise, in part, to measurement inaccuracy. Given the limitations
  of self-report measures, the true effect sizes may differ from those
  estimated. Therefore, while the evidence does suggest a modest impact,
  the actual real-world effects may be either smaller or larger than the
  estimates suggest. Given the modest effect sizes and the limitations
  of self-report measures, future research should explore the use of
  more objective measures for variables like exercise and sleep.
  (\ldots{} etc.)
\item
  \textbf{Generalisability and transportability}: our findings should be
  interpreted within the context of the New Zealand population from
  which the data were sourced. Although the results may have broader
  relevance, direct extrapolation to different populations or
  sociocultural settings should be undertaken cautiously.
\end{enumerate}

\subsubsection{Theoretical and practical
relevance}\label{theoretical-and-practical-relevance}

\newpage{}

\subsubsection{Ethics}\label{ethics}

The NZAVS is reviewed every three years by the University of Auckland
Human Participants Ethics Committee. Our most recent ethics approval
statement is as follows: The New Zealand Attitudes and Values Study was
approved by the University of Auckland Human Participants Ethics
Committee on 26/05/2021 for six years until 26/05/2027, Reference Number
UAHPEC22576.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the TempletoReligion Trust (TRT0196; TRT0418). JB received support from
the Max Planck Institute for the Science of Human History. The funders
had no role in preparing the manuscript or the decision to publish.

\subsubsection{Author Statement}\label{author-statement}

TBA

\newpage{}

\subsection{Appendix A. Measures}\label{appendix-a.-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' age in an open-ended question (``What is your
age?'' or ``What is your date of birth'').

\paragraph{Disability (waves: 5-15)}\label{disability-waves-5-15}

We assessed disability with a one item indicator adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}), that asks ``Do you have a health
condition or disability that limits you, and that has lasted for 6+
months?'' (1 = Yes, 0 = No).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

Participants were asked ``What is your highest level of
qualification?''. We coded participans highest finished degree according
to the New Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG
codes (with overseas school quals coded as Level 3, and all other
ancillary categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants ``Are you currently employed? (This includes
self-employed or casual work)''. * note: This question disappeared in
the updated NZAVS Technical documents (Data Dictionary).

\paragraph{European (waves: 1-15)}\label{european-waves-1-15}

Participants were asked ``Which ethnic group do you belong to (NZ census
question)?'' or ``Which ethnic group(s) do you belong to? (Open-ended)''
(wave: 3). Europeans were coded as 1, whereas other ethnicities were
coded as 0.

\paragraph{Ethnicity (waves: 3)}\label{ethnicity-waves-3}

Based on the New Zealand Cencus, we asked participants ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Gender (waves: 1-15)}\label{gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked ``Please estimate your total household income
(before tax) for the year XXXX''. To stablise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Number of Children (waves: 1-3,
4-15)}\label{number-of-children-waves-1-3-4-15}

We measured number of children using one item from Bulbulia
(\citeproc{ref-Bulbulia_2015}{2015}). We asked participants ``How many
children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, or adopted?'' or ````How
many children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, and/or parented?'' (waves:
12-15).

\paragraph{Political Orientation}\label{political-orientation}

We measured participants' political orientation using a single item
adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{NZSEI-13 (waves: 8-15)}\label{nzsei-13-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017}). This index uses the income, age, and education of
a reference group, in this case the 2013 New Zealand census, to
calculate an score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

Participants were asked ``If you are a parent, what is the birth date of
your eldest child?''.

\paragraph{Living with Partner}\label{living-with-partner}

Participants were asekd ``Do you live with your partner?'' (1 = Yes, 0 =
No).

\paragraph{Living in an Urban Area (waves:
1-15)}\label{living-in-an-urban-area-waves-1-15}

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants personality with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}) which consists of six dimensions and each
dimensions is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I ften forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\subsubsection{Exposure variable}\label{exposure-variable}

HERE

\subsubsection{Health well-being
outcomes}\label{health-well-being-outcomes}

\subsubsection{Appendix B. Descriptive
Statistics}\label{appendix-b.-descriptive-statistics}

\subsubsection{Appendix D. Population Average Treatment
Effect}\label{appendix-d.-population-average-treatment-effect}

As indicated in the main manuscript, the Average Treatment Effects is
obtained by contrasting the expected outcome when a population sampled
is exposed to an exposure level, \(E[Y(A = a)]\), with the expected
outcome under a different exposure level, \(E[Y(A=a')]\).

For a binary treatment with levels \(A=0\) and \(A=1\), the Average
Treatment Effect (ATE), on the difference scale, is expressed:

\[ATE_{\text{risk difference}} = E[Y(1)|L] - E[Y(0)|L]\]

On the risk ratio scale, the ATE is expressed:

\[ATE_{\text{risk ratio}} = \frac{E[Y(1)|L]}{E[Y(0)|L]}\]

Other effect scales, such as the incidence rate ratio, incidence rate
difference, or hazard ratio, might also be of interest.

Here we estimate the Population Average Treatment Effect (PATE), which
denotes the effect the treatment would have on the New Population if
applied universally. This quantity can be expressed:

\[PATE_{\text{risk difference}} = f(E[Y(1) - Y(0)|L], W)\]

\[PATE_{\text{risk ratio}} = f\left(\frac{E[Y(1)|L]}{E[Y(0)|L]}, W\right)\]

where \(f\) is a function that incorporates post-stratification weights
\(W\) into the estimation of the expected outcomes from which we obtain
causal contrasts. Because the NZAVS is national probability sample,
i.e.~inverse probability of being sampled 1. However, to incorporate
gender, age, and ethnic differences we include post-stratification
weight into our outcome wide models.

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2022}
Bulbulia, JA (2022) A workflow for causal inference in cross-cultural
psychology. \emph{Religion, Brain \& Behavior}, \textbf{0}(0), 1--16.
doi:\href{https://doi.org/10.1080/2153599X.2022.2070245}{10.1080/2153599X.2022.2070245}.

\bibitem[\citeproctext]{ref-bulbulia2023}
Bulbulia, JA (2023) Causal diagrams (directed acyclic graphs): A
practical guide.

\bibitem[\citeproctext]{ref-bulbulia2023a}
Bulbulia, JA, Afzali, MU, Yogeeswaran, K, and Sibley, CG (2023)
Long-term causal effects of far-right terrorism in {N}ew {Z}ealand.
\emph{PNAS Nexus}, \textbf{2}(8), pgad242.

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, S, J. A. (2015) Religion and parental cooperation: An
empirical test of slone's sexual signaling model. In \&. V. S. J. Slone
D., ed., \emph{The attraction of religion: A sexual selectionist
account}, Bloomsbury Press, 29--62.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.
doi:\href{https://doi.org/10.1207/s15327752jpa8301_04}{10.1207/s15327752jpa8301\_04}.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a new zealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-hernan2023}
Hernan, MA, and Robins, JM (2023) \emph{Causal inference}, Taylor \&
Francis. Retrieved from
\url{https://books.google.co.nz/books?id=/_KnHIAAACAAJ}

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in New Zealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vanderweele2015}
VanderWeele, TJ (2015) \emph{Explanation in causal inference: Methods
for mediation and interaction}, Oxford University Press.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{Lmtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\end{CSLReferences}



\end{document}
