% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  singlecolumn]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=20mm,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal effects of religious service attendance on prosociality evidence from a national longitudinal study},
  pdfauthor={Joseph A. Bulbulia; Don E Davis; Ken Rice; Chris G. Sibley; Geoffrey Troughton},
  pdfkeywords={Causal
Inference, Charity, Church, Cooperation, Religion, Shift
Intervention, Volunteering},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal effects of religious service attendance on prosociality
evidence from a national longitudinal study}
\author{Joseph A. Bulbulia \and Don E Davis \and Ken Rice \and Chris G.
Sibley \and Geoffrey Troughton}
\date{2024-04-04}

\begin{document}
\maketitle
\begin{abstract}
The question of whether religion causes prosociality is poorly defined.
To make it precise we must state a causal contrasts of interest,
specific our measures of ``prosociality,'' and clarify the target
population for whom results are meant to generalise. Here we investigate
the causal effects of three hypothetical interventions on religious
service attendance across the New Zealand population where the levels of
intervention address different theoretical and policy questions. Study 1
investigates the effects of these pre-specified interventions on
self-reported social behaviours; Study 2 investigates effects on
perceived social connection; Study 3 investigates effects voluntary help
received from others; Study 4: investigates effects on money received
from others . Notably the measures in studies 3 and 4 avoid self
presentation bias. Overall we find evidence that religion supports
pro-social behaviours across all measurement domains of prosociality;
however, the quality and magnitude of benefit varies depending on the
estimand of interest -- whether religious service is gained or lost, and
whether the contrast condition is the status quo. Moreover magnitudes of
benefit are lower than suggested by unmodelled associations in the data.
Nevertheless, the gain of regular religious service has economic
considerable economic benefits, it's loss, deficits -- which we compute.
These findings illustrate a pathway for quantitative investigations of
the causal effects of religious behaviours using longitudinal modified
treatment policies.
\end{abstract}

\subsection{Introduction}\label{introduction}

A central question in the scientific study of religion is whether
religion causes cooperation. However, to address this question is
challenging. Most features of religion are inaccessible to experiments.
On the other hand, to quantify causality from non-experimental data
requires the appropriate modelling of time-series data. Obtaining valid
causal inferences from observational data requires a combination of rich
time-series data and robust causal inferential methods. Presently such
combinations are rare.

Perhaps more fundamental, the question of whether religion causes
prosociality is poorly defined. To make this question precise we must to
state the causal contrasts of interest, specific measures of
``prosociality,'' and the target population for whom results are meant
to generalise.

Here, we leverage comprehensive panel data from \texttt{n\_participants}
who participated in the New Zealand Attitudes and Values Study from
years 2018-2021 and measure the one-year effect of religious attendance
across four domains of prosociality. For each domain we compute three
estimands: (1) weekly (or more) religious service attendance vs zero
attendance. This estimand addresses the question: ``what would be the
difference if everyone attended weekly religious service compared with
if no-one attended?''; (2) weekly (or more) religious service attendance
vs the observed attenendance rate, which addresses the question: ``what
would be the difference if everyone in the country that was not
attending weekly religious service switched to regular attendance?'' (3)
No religious service attendance vs the observed attenendance rate, which
addresses the question: ``what would be the difference if religious
service attendance disappeared altogether?'' The first estimand holds
theoretical interest. The second estimand allows us to evaluate the
policy effect of supporting greater religious service attendance. The
second estimand allows us to evaluate the policy effect of supporting
lower religious service attendance. It is interesting to separately
investigate the social consequences of a gain and loss of religious
service attendance because these quantities and advice might differ.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of The New Zealand Attitudes and Values
Study (NZAVS), an annual longitudinal national probability panel study
of social attitudes, personality, ideology and health outcomes. The
NZAVS began in 2009. It includes questionnaire responses 72910 New
Zealand residents. Because the NZAVS follows the same people over time,
with strong retention, it can track subtle change in attitudes and
values over time. The NZAVS is university-based, not- for-profit and
independent of political or corporate funding: see:
https://doi.org/10.17605/OSF.IO/75SNB

\subsubsection{Outcome-wide measures of
prosociality}\label{outcome-wide-measures-of-prosociality}

Rather than cheery picking one or several measures of prosociality, we
adopted an unrestrictive ``outcome-wide'' approach that used a rich
array of measures to assess multiple-dimensions of a potentially
multi-dimensional construct. The measures we use to investigate this
construct:

\textbf{Study 1. Self-reported prosocial behaviours} as measured by:

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  self-reported hours of weekly volunteering;
\item
  self-reported annual charitable financial donations (dollars);
\end{enumerate}

\textbf{Study 2. Perceived social connection} as measured by:

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  social belonging (ordinal 1-7),
\item
  social support (ordinal 1-7),
\item
  neighbourhood belonging (ordinal 1-7)
\end{enumerate}

\textbf{Study 3: Reported personal help received} in the previous week
from:

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  family (yes/no)
\item
  friends (yes/no)
\item
  community (yes/no)
\end{enumerate}

\textbf{Study 4: Reported financial help received} in the previous week
from:

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  family (yes/no)
\item
  friends (yes/no)
\item
  community (yes/no)
\end{enumerate}

We note that Studies 2-4 avoid self-presentation bias by using
individuals as measures of prosociality. That is, if religious service
attendance were to induce greater within-group prosociality, then
regular religious service attendance would increase prosocial exposures.
Studies 3 and 4 are especially robust to self-presentation bias because
they rely on self-reported dependency.

\subsubsection{Causal Contrasts}\label{causal-contrasts}

To answer a causal question requires that we first state it. Here, we
ask three distinct causal questions.

Let \(A\) denote religiosu service, the treatment of inteest. We
calibrate \(f(A)\) according to following rules:

\[
f(A) = 
\begin{cases} 
a, & \text{where } a \text{ is the observed value.}\\
a^* = 4, & \text{if } a < 4 \times \text{monthly religious service attendance; otherwise, } a^* = a.\\
a' = 0, & \text{if } a > 0 \text{ and monthly religious service attendance is positive; otherwise, } a' = a. 
\end{cases}
\]

This function operates as follows:

\begin{itemize}
\item
  \textbf{for \(a\)}: \(a\) remains unchanged; estimation is performed
  for observed value.
\item
  \textbf{for \(a^*\)}: this conditionally modifies \(a\) to \(a^* = 4\)
  if \(a\) is less than four times the monthly religious service
  attendance. If \(a\) does not meet this condition, it remains
  unaltered as \(a^*\) equals \(a\). This function enforces a minimum
  threshold for \(a^*\) of religious attendance but allows those above
  this threshold to remain unchanged.
\item
  \textbf{for \(a^\prime\)}: this condition modifies \(a\) to \(a' = 0\)
  when the observed value of \(a\) is greater than 0, thus setting all
  values of religious attendance to 0.
\end{itemize}

We may now formulate our causal contrasts, \(Y(\bar{a})\) denote a
potential outcome under the treatment rule \(f(A)\); \(L\) denotes the
set of measured covariates we assume to be sufficient for confounding
control.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Our first causal question asks: ``what would be the social
  consequences of everyone attending religious service compared with
  no-one attending religious service'' which computes the following
  causal contrast (on the difference scale):
\end{enumerate}

\[ \text{Longitudinal Modified Treatment Policy}^1 = E[Y(a*,a*)|\textcolor{red}{f(A)},L] - E[Y(a^\prime,a^\prime)|\textcolor{red}{f(A)},L] \]

This causal question reflects the theoretical interest. Everyone
attending regularly vs.~non-one attending regularly.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Our second causal question asks: ``what would be the social
  consequences if everyone who was not attending weekly religious
  service in New Zealand were to do so?'' The contrast conditions for
  this estimand are given by (a) regular religious service attendance
  and (b) the status quo, which can be written:
\end{enumerate}

\[ \text{Longitudinal Modified Treatment Policy}^2 = E[Y(a*,a*)|\textcolor{red}{f(A)},L] - E[Y(a,a)|\textcolor{red}{f(A)},L] \]

This contrasts helps us to evaluate the social effects of a policy that
promoted the society-wide adoption of religious service attendance
across the contemporary target population.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  What would be the social consequences if everyone who was attending
  religious service in New Zealand were stop. The contrast conditions
  are thus no religious service attendance and the status quo, which can
  be written:
\end{enumerate}

\[ \text{Longitudinal Modified Treatment Policy}^3 = E[Y(a*,a*)|\textcolor{red}{f(A)},L] - E[Y(a,a)|\textcolor{red}{f(A)},L] \]

This contrasts helps us to evaluate the social effects of a policy that
promoted the society-wide loss of religious service attendance in the
contemporary population.

\subsubsection{Identification
assumptions}\label{identification-assumptions}

To obtain valid causal effect estimates we must satisfy three
identification assumptions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Causal consistency}: it must be credible in our study that
  each outcomes observed in the data corresponds to at least one of the
  potential outcomes to be compared. Relatedly, this assumption demands
  that potential outcomes we consider are independent of the versions of
  treatment administered, conditional on measured covariates.
\end{enumerate}

This assumption cannot be verified by data.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Conditional exchangeability}: it must be credible in our study
  that given the observed covariates, treatment assignment is
  independent of each of the potential outcomes that we consider. Put
  differently, it must be credible that our statistical models obtain
  balance in confounding co-variates in the treatments to be compared.
\end{enumerate}

To improve crediblity for this assumption we conduct analysis using
semi-parametric doubly robust estimators. Such estimators minimise
restrictive assumptions about a statisitcal model's functional form;
they are ``doubly-robust'' in the sense two models are deployed, one
that seeks to obtain balance for all confounders on the treatment, and
the other that seeks obtain balance for all confounders in the
distribution of potential outcome -- and only one of the two models
needs to be correctly estimated to consistently estimate a causal
effect.

Nevertheless, as with the causal consistency assumption, the conditional
exchangeability assumption cannot be verified by data. Hence we perform
sensitivity analyses, as described below.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Positivity}: it must be credible in our study that every
  subject has a non-zero probability of receiving the treatment,
  irrespective of their covariates. Below, we evaluate the positivity
  assumption by reporting the number of instances in which individuals
  transitioned from one state of religious service in the baseline wave
  to another state of religious service in the treatment wave.
\end{enumerate}

\subsubsection{Target Population}\label{target-population}

The target population is the population of New Zealand at the baseline
wave. Although the New Zealand Attitudes and Values Study is a national
probability study with good representation of the New Zealand population
as a whole, its coverage is not perfect. For example the study under
samples males and asians and over samples women and Māori (New Zealand's
indigenous peoples). The \texttt{lmtp} package allows us to pass survey
weights when computing marginal treatment effects; in this study we
weighted the sample to age, gender and ethnicity, following the
pre-stated protocols in Bulbulia
(\citeproc{ref-bulbulia2024PRACTICAL}{2024a}).

\subsubsection{Eligibility criteria}\label{eligibility-criteria}

\begin{itemize}
\tightlist
\item
  Enrolled in the New Zealand Attitudes and Values Study in 2018 (NZAVS
  time 10).
\item
  Missing data for all variables at baseline were allowed, and imputed
  using the \texttt{ppm} algorith from the \texttt{mice} package
  (\citeproc{ref-vanbuuren2018}{Van Buuren 2018}).
\item
  Attrition/loss to follow up was permented. Inverse probability of
  censoring weights were calculated as part of estimation in
  \texttt{lmtp} to adjust for missing outcomes at NZAVS Time 12 (years
  2020-2021, the outcome wave). See details of the \texttt{lmtp} package
  (\citeproc{ref-williams2021}{Williams and Díaz 2021}))
\end{itemize}

There were 47948 who met these criteria.

\subsubsection{Confounding control}\label{confounding-control}

We use VanderWeele \emph{et al.} (\citeproc{ref-vanderweele2020}{2020})
\emph{modified disjunctive cause criterion} in which we (1) identified
all common causes of the treatment and outcomes; (2) removed any
variables identified that might influence the exposure but not the
outcome -- instrumental variables -- because instrumental variables are
known to reduce efficiency; (3) included proxies for any unmeasured
variables affecting both exposure and outcome -- including instrumental
variables, because by the rules of d-separation, conditioning on a proxy
is akin to conditioning on its parent (in this case, a confounder) (4)
\textbf{control for baseline exposure} and (5) \textbf{control for
baseline outcome} both of which serve as proxies for unmeasured common
causes (\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).
Note that our shift interventions obtain controlled effects for
baseline-treatment and exposure wave-treatment, with the naturally
observed treatment levels being explicitly modelled from the data, see
{[}{]} for details.

\paragraph{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess sensitivity of results to unmeasured confounding, we report
VanderWeele and Ding's ``E-value'' in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). To
evaluate strength of evidence, we use the bound of the E-value's 95\%
confidence interval that is closest to 1.

\subsubsection{Analysis}\label{analysis}

We employ a semi-parametric estimator known as Targeted Minimum
Loss-based Estimation (TMLE). TMLE is a robust method that combines
machine learning techniques with traditional statistical models to
estimate causal effects while providing valid statistical uncertainty
measures for these estimates.

TMLE operates through a two-step process involving both outcome and
treatment (exposure) models. Initially, it employes machine learning
algorithms to flexibly model the relationship between treatments,
covariates, and outcomes. This flexibility allows TMLE to account for
complex, high-dimensional covariate spaces without imposing restrictive
model assumptions. The outcome of this step is a set of initial
estimates for these relationships.

The second step of TMLE involves ``targeting'' these initial estimates
by incorporating information about the observed data distribution to
improve the accuracy of the causal effect estimate. This is achieved
through an iterative updating process, which adjusts the initial
estimates towards the true causal effect. This updating process is
guided by the efficient influence function, ensuring that the final TMLE
estimate is as close as possible given the measures and data to the true
causal effect, while still being robust to model misspecification in
either the outcome model or the treatment model.

Again, a central feature of TMLE is its double-robustness property,
meaning that if either the model for the treatment or the outcome is
correctly specified, the TMLE estimator will still consistently estimate
the causal effect. Additionally, TMLE uses cross-validation to avoid
over-fitting and ensure that the estimator performs well in finite
samples. Each of these steps contributes to a robust methodology for
examining the \emph{causal} effects on of interventions on outcomes. The
marriage of TMLE and machine learning technologies reduces the
dependence on restrictive modelling assumptions and introduces an
additional layer of robustness. For further details see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023}). We performed estimation using
\texttt{lmtp} package (\citeproc{ref-williams2021}{Williams and Díaz
2021}). We used the \texttt{superlearner} library for non-parametric
estimation with the predefined libraries \texttt{SL.ranger},
\texttt{SL.glmnet}, \texttt{SL.xboost}. Graphs, tables and output reorts
were created using the \texttt{margot} package
(\citeproc{ref-margot2024}{Bulbulia 2024b}).

\newpage{}

\subsubsection{Scope of Interventions}\label{scope-of-interventions}

\subsubsection{Evidence for Change in the Treatment
Variable}\label{evidence-for-change-in-the-treatment-variable}

\subsection{Results}\label{results}

\newpage{}

\subsection{Study 1: Causal Effects of Regular Church Attendance on
Self-Reported Volunteering and Self Reported Charitable
Donations}\label{study-1-causal-effects-of-regular-church-attendance-on-self-reported-volunteering-and-self-reported-charitable-donations}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_1_1-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs universal
loss of weekly religious service on reported charitable behaviours at
the end of study. Outcomes are expressed in standard deviation units.}

\end{figure}%

\phantomsection\label{tbl_1_1}
\begin{longtable}[]{@{}lrrrrr@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs universal loss of
weekly religious service on reported charitable behaviours at the end of
study. Outcomes are expressed in standard deviation
units.}\tabularnewline
\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.17 & 0.10 & 0.25 & 1.62 & 1.41 \\
hours volunteer & 0.09 & -0.04 & 0.22 & 1.39 & 1.00 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and constrast groups for the
target population.

For the outcome `relig service: donations', the lmtp is 0.173
{[}0.097,0.25{]}. The E-value for this effect estimate is 1.617 with a
lower bound of 1.409. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.409, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.409) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: hours volunteer' is positive, however,
given the lower bound of the E-value equals 1, we infer there is no
reliable evidence for causality.

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_1_2-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs status quo on
reported charitable behaviours at the end of study. Outcomes are
expressed in standard deviation units.}

\end{figure}%

\phantomsection\label{tbl_1_2}
\begin{longtable}[]{@{}lrrrrr@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs status quo on
reported charitable behaviours at the end of study. Outcomes are
expressed in standard deviation units.}\tabularnewline
\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.10 & 0.02 & 0.17 & 1.41 & 1.15 \\
hours volunteer & 0.07 & -0.06 & 0.20 & 1.33 & 1.00 \\
\end{longtable}

For the outcome `relig service: donations', the lmtp is 0.096
{[}0.02,0.171{]}. The E-value for this effect estimate is 1.407 with a
lower bound of 1.154. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.154, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.154) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: hours volunteer', given the lower bound
of the E-value equals 1, we infer there is no reliable evidence for
causality.

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_1_3-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal loss of weekly religious service vs status quo on
reported charitable behaviours at the end of study. Outcomes are
expressed in standard deviation units.}

\end{figure}%

\phantomsection\label{tbl_1_3}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1212}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1818}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal loss of weekly religious service vs status quo on
reported charitable behaviours at the end of study. Outcomes are
expressed in standard deviation units.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & -0.077 & -0.099 & -0.056 & 1.352 & 1.285 \\
hours volunteer & -0.022 & -0.033 & -0.010 & 1.164 & 1.107 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: hours volunteer', the lmtp is -0.022
{[}-0.033,-0.01{]}. The E-value for this effect estimate is 1.164 with a
lower bound of 1.107. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.107, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.107) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: donations', the lmtp is -0.077
{[}-0.099,-0.056{]}. The E-value for this effect estimate is 1.352 with
a lower bound of 1.285. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.285, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.285) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

\newpage{}

\subsection{Study 2: Causal Effects of Regular Church Attendance on
Self-Reported Social
Connection}\label{study-2-causal-effects-of-regular-church-attendance-on-self-reported-social-connection}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_2_1-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs universal
loss of weekly religious service on perceived social connection at the
end of study. Outcomes are expressed in standard deviation units.}

\end{figure}%

\phantomsection\label{tbl_2_1}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3288}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2192}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0822}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0959}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1096}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1644}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs universal loss of
weekly religious service on perceived social connection at the end of
study. Outcomes are expressed in standard deviation
units.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
neighbourhood community & 0.03 & -0.12 & 0.18 & 1.19 & 1.0 \\
social belonging & 0.12 & 0.03 & 0.21 & 1.48 & 1.2 \\
social suport & 0.05 & -0.06 & 0.16 & 1.27 & 1.0 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: social belonging', the lmtp is 0.121
{[}0.031,0.211{]}. The E-value for this effect estimate is 1.477 with a
lower bound of 1.2. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.2, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.2) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: social suport', given the lower bound of
the E-value equals 1, we infer there is no reliable evidence for
causality.

For the outcome `relig service: neighbourhood community', given the
lower bound of the E-value equals 1, we infer there is no reliable
evidence for causality.

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_2_2-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs status quo on
perceived social connection at the end of study. Outcomes are expressed
in standard deviation units.}

\end{figure}%

\phantomsection\label{tbl_2_2}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3243}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2162}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0946}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0946}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1081}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1622}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs status quo on
perceved social connection at the end of study. Outcomes are expressed
in standard deviation units.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
neighbourhood community & 0.013 & -0.136 & 0.163 & 1.122 & 1.000 \\
social belonging & 0.108 & 0.019 & 0.197 & 1.441 & 1.155 \\
social suport & 0.039 & -0.075 & 0.153 & 1.230 & 1.000 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: social belonging', the lmtp is 0.108
{[}0.019,0.197{]}. The E-value for this effect estimate is 1.441 with a
lower bound of 1.155. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.155, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.155) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: social suport', given the lower bound of
the E-value equals 1, we infer there is no reliable evidence for
causality.

For the outcome `relig service: neighbourhood community', given the
lower bound of the E-value equals 1, we infer there is no reliable
evidence for causality. \textgreater{}

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_2_3-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal loss of weekly religious service vs status quo on
perceived social connection at the end of study. Outcomes are expressed
in standard deviation units.}

\end{figure}%

\phantomsection\label{tbl_2_3}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3243}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2162}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0946}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0946}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1081}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1622}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal loss of weekly religious service vs status quo on
perceved social connection at the end of study. Outcomes are expressed
in standard deviation units.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
neighbourhood community & -0.016 & -0.023 & -0.009 & 1.137 & 1.094 \\
social belonging & -0.013 & -0.019 & -0.006 & 1.122 & 1.087 \\
social suport & -0.011 & -0.018 & -0.004 & 1.111 & 1.073 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: social suport', the lmtp is -0.011
{[}-0.018,-0.004{]}. The E-value for this effect estimate is 1.111 with
a lower bound of 1.073. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.073, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.073) would not be sufficient to fully account for the observed
effect.Here, we find the evidence for causality is weak.

For the outcome `relig service: social belonging', the lmtp is -0.013
{[}-0.019,-0.006{]}. The E-value for this effect estimate is 1.122 with
a lower bound of 1.087. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.087, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.087) would not be sufficient to fully account for the observed
effect.Here, we find the evidence for causality is weak.

For the outcome `relig service: neighbourhood community', the lmtp is
-0.016 {[}-0.023,-0.009{]}. The E-value for this effect estimate is
1.137 with a lower bound of 1.094. In this context, if there exists an
unmeasured confounder that is associated with both the treatment and the
outcome, and this association has a risk ratio of 1.094, then it is
possible for such a confounder to negate the observed effect.
Conversely, any confounder with a weaker association (i.e., a risk ratio
of less than 1.094) would not be sufficient to fully account for the
observed effect.Here, we find the evidence for causality is weak.

\newpage{}

\subsection{Study 3: Causal Effects of Regular Church Attendance on
Support Received From Others --
Time}\label{study-3-causal-effects-of-regular-church-attendance-on-support-received-from-others-time}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_3_1-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs universal
loss of weekly religious service on volunatary help received from others
during the past week (yes/no) at the end of study. Outcomes are
expressed on the risk ratio scale.}

\end{figure}%

\phantomsection\label{tbl_3_1}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs universal loss of
weekly religious service on volunatary help received from others during
the past week (yes/no) at the end of study. Outcomes are expressed on
the risk ratio scale.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 1.17 & 1.00 & 1.37 & 1.61 & 1.00 \\
friends gives time & 1.24 & 0.98 & 1.55 & 1.77 & 1.00 \\
community gives time & 1.44 & 1.05 & 1.98 & 2.23 & 1.26 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: community gives time', the lmtp is 1.439
{[}1.046,1.979{]}. The E-value for this effect estimate is 2.234 with a
lower bound of 1.265. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.265, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.265) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: friends gives time', given the lower
bound of the E-value equals 1, we infer there is no reliable evidence
for causality.

For the outcome `relig service: family gives time', given the lower
bound of the E-value equals 1, we infer there is no reliable evidence
for causality.

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_3_2-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs status quo on
volunatary help received from others during the past week (yes/no) at
the end of study. Outcomes are expressed on the risk ratio scale.}

\end{figure}%

\phantomsection\label{tbl_3_2}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs status quo on
volunatary help received from others during the past week (yes/no) at
the end of study. Outcomes are expressed on the risk ratio
scale.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 1.140 & 0.974 & 1.335 & 1.539 & 1 \\
friends gives time & 1.192 & 0.954 & 1.490 & 1.670 & 1 \\
community gives time & 1.291 & 0.946 & 1.761 & 1.904 & 1 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: community gives time', given the lower
bound of the E-value equals 1, we infer there is no reliable evidence
for causality.

For the outcome `relig service: friends gives time', given the lower
bound of the E-value equals 1, we infer there is no reliable evidence
for causality.

For the outcome `relig service: family gives time', given the lower
bound of the E-value equals 1, we infer there is no reliable evidence
for causality.

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_3_3-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal loss of weekly religious service vs status quo on
volunatary help received from others during the past week (yes/no) at
the end of study. Outcomes are expressed on the risk ratio scale.}

\end{figure}%

\phantomsection\label{tbl_3_3}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal loss of weekly religious service vs status quo on
volunatary help received from others during the past week (yes/no) at
the end of study. Outcomes are expressed on the risk ratio
scale.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 0.976 & 0.964 & 0.987 & 1.183 & 1.129 \\
friends gives time & 0.966 & 0.950 & 0.982 & 1.226 & 1.155 \\
community gives time & 0.897 & 0.866 & 0.930 & 1.473 & 1.360 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: family gives time', the lmtp is 0.976
{[}0.964,0.987{]}. The E-value for this effect estimate is 1.183 with a
lower bound of 1.129. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.129, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.129) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: friends gives time', the lmtp is 0.966
{[}0.95,0.982{]}. The E-value for this effect estimate is 1.226 with a
lower bound of 1.155. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.155, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.155) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: community gives time', the lmtp is 0.897
{[}0.866,0.93{]}. The E-value for this effect estimate is 1.473 with a
lower bound of 1.36. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.36, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.36) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

\newpage{}

\subsection{Study 4: Causal Effects of Regular Church Attendance on
Support Received From Others --
Money}\label{study-4-causal-effects-of-regular-church-attendance-on-support-received-from-others-money}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_4_1-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs universal
loss of weekly religious service on financial help received from others
during the past week (yes/no) at the end of study. Outcomes are
expressed on the risk ratio scale.}

\end{figure}%

\phantomsection\label{tbl_4_1}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs universal loss of
weekly religious service on financial help received from others during
the past week (yes/no) at the end of study. Outcomes are expressed on
the risk ratio scale.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.66 & 1.22 & 2.25 & 2.70 & 1.74 \\
friends gives money & 2.05 & 1.32 & 3.18 & 3.52 & 1.98 \\
community gives money & 2.66 & 1.93 & 3.67 & 4.77 & 3.27 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: community gives money', the lmtp is
2.663 {[}1.932,3.671{]}. The E-value for this effect estimate is 4.767
with a lower bound of 3.274. In this context, if there exists an
unmeasured confounder that is associated with both the treatment and the
outcome, and this association has a risk ratio of 3.274, then it is
possible for such a confounder to negate the observed effect.
Conversely, any confounder with a weaker association (i.e., a risk ratio
of less than 3.274) would not be sufficient to fully account for the
observed effect.Here, we find strong evidence for causality.

For the outcome `relig service: friends gives money', the lmtp is 2.052
{[}1.323,3.184{]}. The E-value for this effect estimate is 3.521 with a
lower bound of 1.977. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.977, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.977) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: family gives money', the lmtp is 1.656
{[}1.219,2.249{]}. The E-value for this effect estimate is 2.698 with a
lower bound of 1.736. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.736, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.736) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_4_2-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal gain of weekly religious service vs status quo on
financial help received from others during the past week (yes/no) at the
end of study. Outcomes are expressed on the risk ratio scale.}

\end{figure}%

\phantomsection\label{tbl_4_2}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal gain of weekly religious service vs status quo on
financial help received from others during the past week (yes/no) at the
end of study. Outcomes are expressed on the risk ratio
scale.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.47 & 1.09 & 1.98 & 2.30 & 1.39 \\
friends gives money & 1.72 & 1.13 & 2.62 & 2.83 & 1.51 \\
community gives money & 2.04 & 1.59 & 2.62 & 3.50 & 2.56 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: community gives money', the lmtp is
2.042 {[}1.59,2.623{]}. The E-value for this effect estimate is 3.501
with a lower bound of 2.559. In this context, if there exists an
unmeasured confounder that is associated with both the treatment and the
outcome, and this association has a risk ratio of 2.559, then it is
possible for such a confounder to negate the observed effect.
Conversely, any confounder with a weaker association (i.e., a risk ratio
of less than 2.559) would not be sufficient to fully account for the
observed effect.Here, we find strong evidence for causality.

For the outcome `relig service: friends gives money', the lmtp is 1.718
{[}1.129,2.616{]}. The E-value for this effect estimate is 2.829 with a
lower bound of 1.511. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.511, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.511) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: family gives money', the lmtp is 1.467
{[}1.086,1.981{]}. The E-value for this effect estimate is 2.295 with a
lower bound of 1.392. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.392, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.392) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

\newpage{}

\begin{figure}[H]

{\centering \includegraphics{v5-man-lmtp-ow-coop-church_files/figure-pdf/fig_4_3-1.pdf}

}

\caption{Figure reports results of model estimates for the causal
effects of a universal loss of weekly religious service vs status quo on
financial help received from others during the past week (yes/no) at the
end of study. Outcomes are expressed on the risk ratio scale.}

\end{figure}%

\phantomsection\label{tbl_4_3}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}
\caption{Table reports results of model estimates for the causal effects
of a universal loss of weekly religious service vs status quo on
financial help received from others during the past week (yes/no) at the
end of study. Outcomes are expressed on the risk ratio
scale.}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 0.89 & 0.86 & 0.91 & 1.51 & 1.43 \\
friends gives money & 0.84 & 0.78 & 0.89 & 1.68 & 1.48 \\
community gives money & 0.77 & 0.67 & 0.88 & 1.93 & 1.55 \\
\end{longtable}

This longitudinal modified treatment policy computes the expected
difference in outcomes between treatment and contrast groups for the
target population.

For the outcome `relig service: family gives money', the lmtp is 0.886
{[}0.863,0.91{]}. The E-value for this effect estimate is 1.51 with a
lower bound of 1.429. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.429, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.429) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: friends gives money', the lmtp is 0.837
{[}0.784,0.894{]}. The E-value for this effect estimate is 1.677 with a
lower bound of 1.483. In this context, if there exists an unmeasured
confounder that is associated with both the treatment and the outcome,
and this association has a risk ratio of 1.483, then it is possible for
such a confounder to negate the observed effect. Conversely, any
confounder with a weaker association (i.e., a risk ratio of less than
1.483) would not be sufficient to fully account for the observed
effect.Here, we find evidence for causality.

For the outcome `relig service: community gives money', the lmtp is
0.767 {[}0.672,0.875{]}. The E-value for this effect estimate is 1.933
with a lower bound of 1.547. In this context, if there exists an
unmeasured confounder that is associated with both the treatment and the
outcome, and this association has a risk ratio of 1.547, then it is
possible for such a confounder to negate the observed effect.
Conversely, any confounder with a weaker association (i.e., a risk ratio
of less than 1.547) would not be sufficient to fully account for the
observed effect.Here, we find evidence for causality.

\subsection{Summary of findings}\label{summary-of-findings}

\subsubsection{Assumptions and
limitations}\label{assumptions-and-limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causality and confounding}: we employs rigorous causal
  inference techniques, but these are contingent on the assumption of no
  unmeasured confounding. (Say more about E-values\ldots)
\item
  \textbf{Measurement error}: the variables under
  consideration---exercise and sleep---are self-reported, which might
  introduce both systematic and random measurement errors. It should be
  specifically noted that the apparent modesty of the practical effects
  could arise, in part, to measurement inaccuracy. Given the limitations
  of self-report measures, the true effect sizes may differ from those
  estimated. Therefore, while the evidence does suggest a modest impact,
  the actual real-world effects may be either smaller or larger than the
  estimates suggest. Given the modest effect sizes and the limitations
  of self-report measures, future research should explore the use of
  more objective measures for variables like exercise and sleep.
  (\ldots{} etc.)
\item
  \textbf{Generalisability and transportability}: our findings should be
  interpreted within the context of the New Zealand population from
  which the data were sourced. Although the results may have broader
  relevance, direct extrapolation to different populations or
  sociocultural settings should be undertaken cautiously.
\end{enumerate}

\subsubsection{Theoretical and practical
relevance}\label{theoretical-and-practical-relevance}

\newpage{}

\subsubsection{Ethics}\label{ethics}

The NZAVS is reviewed every three years by the University of Auckland
Human Participants Ethics Committee. Our most recent ethics approval
statement is as follows: The New Zealand Attitudes and Values Study was
approved by the University of Auckland Human Participants Ethics
Committee on 26/05/2021 for six years until 26/05/2027, Reference Number
UAHPEC22576.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the TempletoReligion Trust (TRT0196; TRT0418). JB received support from
the Max Planck Institute for the Science of Human History. The funders
had no role in preparing the manuscript or the decision to publish.

\subsubsection{Author Statement}\label{author-statement}

TBA

\newpage{}

\subsection{Appendix A. Measures}\label{appendix-a.-measures}

\subsection{Appendix A: Measurues}\label{appendix-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth'').

\paragraph{Charitable Donations (Study 1
outcome)}\label{charitable-donations-study-1-outcome}

Using one item from Hoverd and Sibley
(\citeproc{ref-hoverd_religious_2010}{2010}), we asked participants
``How much money have you donated to charity in the last year?''.

\paragraph{Charitable Volunteering (Study 1
outcome)}\label{charitable-volunteering-study-1-outcome}

We measured hours of volunterering using one item from Sibley \emph{et
al.} (\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
voluntary/charitable work.''

\paragraph{Community: Sense of Community (Study 2
outcome)}\label{community-sense-of-community-study-2-outcome}

We measured sense of community with a single item from Sengupta \emph{et
al.} (\citeproc{ref-sengupta2013}{2013}): ``I feel a sense of community
with others in my local neighbourhood.'' Participants answered on a
scale of 1 (strongly disagree) to 7 (strongly agree).

\paragraph{Community: Felt Belongingness (Study 2
outcome)}\label{community-felt-belongingness-study-2-outcome}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (\citeproc{ref-hagerty1995}{Hagerty and Patusky
1995}): (1) ``Know that people in my life accept and value me''; (2)
``Feel like an outsider''; (3) ``Know that people around me share my
attitudes and beliefs''. Participants responded on a scale from 1 (Very
Inaccurate) to 7 (Very Accurate). The second item was reversely coded.

\paragraph{Community: Social Support (Study 2
outcome)}\label{community-social-support-study-2-outcome}

Participants' perceived social support was measured using three items
from Cutrona and Russell (\citeproc{ref-cutrona1987}{1987}) and Williams
\emph{et al.} (\citeproc{ref-williams_cyberostracism_2000}{2000}): (1)
``There are people I can depend on to help me if I really need it''; (2)
``There is no one I can turn to for guidance in times of stress''; (3)
``I know there are people I can turn to when I need help.'' Participants
indicated the extent to which they agreed with those items (1 = Strongly
Disagree to 7 = Strongly Agree). The second item was negatively worded,
so we reversely recorded the responses to this item.

\paragraph{Disability}\label{disability}

We assessed disability with a one item indicator adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}), that asks ``Do you have a health
condition or disability that limits you, and that has lasted for 6+
months?'' (1 = Yes, 0 = No).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

We asked participants, ``What is your highest level of qualification?''.
We coded participans highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school quals coded as Level 3, and all other ancillary
categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants, ``Are you currently employed? (This includes
self-employed or casual work)''. * note: This question disappeared in
the updated NZAVS Technical documents (Data Dictionary).

\paragraph{Ethnicity}\label{ethnicity}

Based on the New Zealand Census, we asked participants, ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Fatigue}\label{fatigue}

We assessed subjective fatigue by asking participants, ``During the last
30 days, how often did \ldots{} you feel exhausted?'' Responses were
collected on an ordinal scale (0 = None of The Time, 1 = A little of The
Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).

\paragraph{Gender (waves: 1-15)}\label{gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\paragraph{Has Siblings}\label{has-siblings}

``Do you have siblings?'' (\citeproc{ref-stronge2019onlychild}{Stronge
\emph{et al.} 2019})

\paragraph{Hours of Childcare}\label{hours-of-childcare}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Childcare}\label{hours-of-childcare-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stablise this indicator, we took the natural log of the response + 1.

\paragraph{Hours of Exercise}\label{hours-of-exercise-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stablise this indicator, we took the natural log of the response + 1.

\paragraph{Hours of Housework}\label{hours-of-housework-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stablise this indicator, we took the natural log of the response + 1.

\paragraph{Hours of Sleep}\label{hours-of-sleep}

Participants were asked ``During the past month, on average, how many
hours of \emph{actual sleep} did you get per night''.

\paragraph{Socialising (time 10, time
11)}\label{socialising-time-10-time-11}

As part of the time usage measures, participants were asked to state how
many hour the spent in activities related to socialising with the
following groups:

\begin{itemize}
\tightlist
\item
  Hours spent \ldots{} socialising with family
\item
  Hours spent \ldots{} socialising with friends
\item
  Hours spent \ldots{} socialising with community groups
\item
  Hours spent \ldots{} socialising with religious groups
\end{itemize}

\paragraph{Hours of Work}\label{hours-of-work}

We measured hours of work using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}):``Hours spent \ldots{} working in paid
employment.''

To stablise this indicator, we took the natural log of the response + 1.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked ``Please estimate your total household income
(before tax) for the year XXXX''. To stabilise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Living in an Urban Area (waves:
1-15)}\label{living-in-an-urban-area-waves-1-15}

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

We coded whether they were living in an urban or rural area (1 = Urban,
0 = Rural) based on the addresses provided.

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants' personalities with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}), which consists of six dimensions and each
dimension is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I often forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{Opt-in}\label{opt-in}

The New Zealand Attitudes and Values Study allows opt-ins to the study.
Because the opt-in population may differ from those sampled randomly
from the New Zealand electoral roll; although the opt-in rate is low, we
include an indicator (yes/no) for this variable.

\paragraph{NZSEI Occupational Prestige and Status (waves:
8-15)}\label{nzsei-occupational-prestige-and-status-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017a}{Fahy
\emph{et al.} 2017a}). This index uses the income, age, and education of
a reference group, in this case the 2013 New Zealand census, to
calculate an score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017b}). This index uses the income, age, and education of
a reference group, in this case, the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

--\textgreater{}

--\textgreater{}

\paragraph{Number of Children (waves: 1-3,
4-15)}\label{number-of-children-waves-1-3-4-15}

We measured the number of children using one item from Bulbulia
(\citeproc{ref-Bulbulia_2015}{2015}). We asked participants, ``How many
children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, or adopted?'' or ````How
many children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, and/or parented?'' (waves:
12-15).

\paragraph{Partner: Has}\label{partner-has}

``What is your relationship status?'' (e.g., single, married, de-facto,
civil union, widowed, living together, etc.)

\paragraph{Politically Conservative}\label{politically-conservative}

We measured participants' political conservative orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{Politically Right Wing}\label{politically-right-wing}

We measured participants' political right-wing orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically left-wing versus right-wing you see
yourself as being..''

(1 = Extremely left-wing to 7 = Extremely right-wing)

\paragraph{Short-Form Health}\label{short-form-health}

Participants' subjective health was measured using one item (``Do you
have a health condition or disability that limits you, and that has
lasted for 6+ months?''; 1 = Yes, 0 = No) adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}).

\paragraph{Support received: money (waves 10-13) (Study 4
outcomes)}\label{support-received-money-waves-10-13-study-4-outcomes}

The NZAVS has a `revealed' measure of received help and support measured
in hours of support in the previous week. The items are:

Received help and support - money - family - friends - others in my
community

\paragraph{Support received: time (waves 10-13) (Study 3
outcomes)}\label{support-received-time-waves-10-13-study-3-outcomes}

The NZAVS has a `revealed' measure of received help and support measured
in hours of support in the previous week. The items are:

Received help and support - hours - family - friends - others in my
community

\paragraph{Total Siblings}\label{total-siblings}

Participants were asked the following questions related to sibling
counts:

\begin{itemize}
\tightlist
\item
  Were you the 1st born, 2nd born, or 3rd born, etc, child of your
  mother?
\item
  Do you have siblings?
\item
  How many older sisters do you have?
\item
  How many younger sisters do you have?
\item
  How many older brothers do you have?
\item
  How many younger brothers do you have?
\end{itemize}

A single score was obtained from sibling counts by summing responses to
the ``How many\ldots{}'' items. From these scores an ordered factor was
created ranging from 0 to 7, where participants with more than 7
siblings were grouped into the highest category.

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{table}

\caption{\label{tbl-B}}

\centering{

\captionsetup{labelsep=none}

}

\end{table}%

\begin{longtable}[]{@{}ll@{}}
\caption{Baseline demography
statistics}\label{tbl-table-demography}\tabularnewline
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,948} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,948} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 49 (14) \\
Range & 18, 99 \\
IQR & 39, 60 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.35 (0.99) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.00 \\
Unknown & 452 \\
\textbf{Alert Level Combined Lead} & NA \\
no\_alert & 24,789 (71\%) \\
early\_covid & 3,902 (11\%) \\
alert\_level\_1 & 3,010 (8.7\%) \\
alert\_level\_2 & 865 (2.5\%) \\
alert\_level\_2\_5\_3 & 569 (1.6\%) \\
alert\_level\_4 & 1,648 (4.7\%) \\
Unknown & 13,165 \\
\textbf{Born Nz} & 37,082 (78\%) \\
Unknown & 585 \\
\textbf{Children Num} & NA \\
Mean (SD) & 1.74 (1.46) \\
Range & 0.00, 14.00 \\
IQR & 0.00, 3.00 \\
Unknown & 393 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.11 (1.06) \\
Range & 1.00, 7.00 \\
IQR & 4.50, 6.00 \\
Unknown & 443 \\
\textbf{Education Level Coarsen} & NA \\
no\_qualification & 1,239 (2.7\%) \\
cert\_1\_to\_4 & 16,700 (36\%) \\
cert\_5\_to\_6 & 5,969 (13\%) \\
university & 12,595 (27\%) \\
post\_grad & 5,118 (11\%) \\
masters & 3,924 (8.4\%) \\
doctorate & 1,125 (2.4\%) \\
Unknown & 1,278 \\
\textbf{Employed} & 38,024 (79\%) \\
Unknown & 107 \\
\textbf{Eth Cat} & NA \\
euro & 38,158 (81\%) \\
maori & 5,457 (12\%) \\
pacific & 1,137 (2.4\%) \\
asian & 2,543 (5.4\%) \\
Unknown & 653 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.91 (1.20) \\
Range & 1.00, 7.00 \\
IQR & 3.00, 4.75 \\
Unknown & 443 \\
\textbf{Hlth Disability} & 10,540 (22\%) \\
Unknown & 926 \\
\textbf{Hlth Fatigue} & NA \\
0 & 7,326 (15\%) \\
1 & 15,242 (32\%) \\
2 & 14,803 (31\%) \\
3 & 7,448 (16\%) \\
4 & 2,572 (5.4\%) \\
Unknown & 557 \\
\textbf{Hlth Sleep Hours} & NA \\
Mean (SD) & 6.94 (1.13) \\
Range & 2.50, 16.00 \\
IQR & 6.00, 8.00 \\
Unknown & 2,482 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.41 (1.19) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.25 \\
Unknown & 448 \\
\textbf{Hours Children log} & NA \\
Mean (SD) & 1.17 (1.61) \\
Range & 0.00, 5.13 \\
IQR & 0.00, 2.40 \\
Unknown & 1,538 \\
\textbf{Hours Community log} & NA \\
Mean (SD) & 0.34 (0.65) \\
Range & 0.00, 4.80 \\
IQR & 0.00, 0.69 \\
Unknown & 1,538 \\
\textbf{Hours Exercise log} & NA \\
Mean (SD) & 1.54 (0.85) \\
Range & 0.00, 4.39 \\
IQR & 1.10, 2.08 \\
Unknown & 1,538 \\
\textbf{Hours Family log} & NA \\
Mean (SD) & 1.61 (1.04) \\
Range & 0.00, 5.13 \\
IQR & 1.10, 2.40 \\
Unknown & 1,538 \\
\textbf{Hours Friends log} & NA \\
Mean (SD) & 1.45 (0.87) \\
Range & 0.00, 5.02 \\
IQR & 1.10, 1.95 \\
Unknown & 1,538 \\
\textbf{Hours Housework log} & NA \\
Mean (SD) & 2.14 (0.78) \\
Range & 0.00, 5.13 \\
IQR & 1.61, 2.71 \\
Unknown & 1,538 \\
\textbf{Hours Religious Community log} & NA \\
Mean (SD) & 0.17 (0.49) \\
Range & 0.00, 5.04 \\
IQR & 0.00, 0.00 \\
Unknown & 1,538 \\
\textbf{Hours Work log} & NA \\
Mean (SD) & 2.66 (1.58) \\
Range & 0.00, 4.62 \\
IQR & 1.39, 3.71 \\
Unknown & 1,538 \\
\textbf{Household Inc log} & NA \\
Mean (SD) & 11.39 (0.77) \\
Range & 0.69, 14.92 \\
IQR & 11.00, 11.92 \\
Unknown & 3,726 \\
\textbf{Kessler6 Sum} & NA \\
Mean (SD) & 5 (4) \\
Range & 0, 24 \\
IQR & 2, 8 \\
Unknown & 489 \\
\textbf{Male} & 17,779 (37\%) \\
\textbf{Modesty} & NA \\
Mean (SD) & 5.98 (0.95) \\
Range & 1.00, 7.00 \\
IQR & 5.50, 6.75 \\
Unknown & 34 \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.49 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 2.75, 4.25 \\
Unknown & 454 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.77 (2.73) \\
Range & 1.00, 10.00 \\
IQR & 2.00, 7.00 \\
Unknown & 310 \\
\textbf{Nzsei 13 l} & NA \\
Mean (SD) & 54 (17) \\
Range & 10, 90 \\
IQR & 41, 69 \\
Unknown & 676 \\
\textbf{Openness} & NA \\
Mean (SD) & 4.96 (1.12) \\
Range & 1.00, 7.00 \\
IQR & 4.25, 5.75 \\
Unknown & 445 \\
\textbf{Partner} & 34,818 (75\%) \\
Unknown & 1,539 \\
\textbf{Political Conservative} & NA \\
1 & 2,515 (5.6\%) \\
2 & 8,676 (19\%) \\
3 & 8,820 (20\%) \\
4 & 13,913 (31\%) \\
5 & 6,694 (15\%) \\
6 & 3,299 (7.4\%) \\
7 & 741 (1.7\%) \\
Unknown & 3,290 \\
\textbf{Religion Church Round} & NA \\
0 & 38,479 (83\%) \\
1 & 1,517 (3.3\%) \\
2 & 1,125 (2.4\%) \\
3 & 907 (2.0\%) \\
4 & 2,478 (5.3\%) \\
5 & 475 (1.0\%) \\
6 & 326 (0.7\%) \\
7 & 106 (0.2\%) \\
8 & 964 (2.1\%) \\
Unknown & 1,571 \\
\textbf{Rural Gch 2018 l} & NA \\
1 & 29,479 (62\%) \\
2 & 9,014 (19\%) \\
3 & 5,865 (12\%) \\
4 & 2,694 (5.7\%) \\
5 & 588 (1.2\%) \\
Unknown & 308 \\
\textbf{Sample Frame Opt in} & 1,384 (2.9\%) \\
\textbf{Sample Origin} & NA \\
1-2 & 2,970 (6.2\%) \\
3-3.5 & 2,052 (4.3\%) \\
4 & 2,700 (5.6\%) \\
5-6-7 & 4,506 (9.4\%) \\
8-9 & 5,802 (12\%) \\
10 & 29,918 (62\%) \\
\textbf{Short Form Health} & NA \\
Mean (SD) & 5.04 (1.17) \\
Range & 1.00, 7.00 \\
IQR & 4.33, 6.00 \\
Unknown & 9 \\
\textbf{Total Siblings} & NA \\
Mean (SD) & 2.55 (1.87) \\
Range & 0.00, 23.00 \\
IQR & 1.00, 3.00 \\
Unknown & 1,205 \\
\textbf{Urban} & 38,493 (81\%) \\
Unknown & 308 \\
\end{longtable}

Table~\ref{tbl-table-demography} presents baseline demographic
statistics for couples who met inclusion criteria.

\subsection{Appendix C: Treatment Statistics}\label{appendix-exposures}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4247}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}@{}}
\caption{Baseline and treatment wave descriptive
statistics}\label{tbl-table-exposures}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Religion Church Round} & NA & NA \\
0 & 38,479 (83\%) & 28,671 (84\%) \\
1 & 1,517 (3.3\%) & 916 (2.7\%) \\
2 & 1,125 (2.4\%) & 751 (2.2\%) \\
3 & 907 (2.0\%) & 651 (1.9\%) \\
4 & 2,478 (5.3\%) & 1,700 (5.0\%) \\
5 & 475 (1.0\%) & 312 (0.9\%) \\
6 & 326 (0.7\%) & 209 (0.6\%) \\
7 & 106 (0.2\%) & 71 (0.2\%) \\
8 & 964 (2.1\%) & 655 (1.9\%) \\
Unknown & 1,571 & 14,012 \\
\textbf{Alert Level Combined} & NA & NA \\
no\_alert & 47,948 (100\%) & 24,789 (71\%) \\
early\_covid & 0 (0\%) & 3,902 (11\%) \\
alert\_level\_1 & 0 (0\%) & 3,010 (8.7\%) \\
alert\_level\_2 & 0 (0\%) & 865 (2.5\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 569 (1.6\%) \\
alert\_level\_4 & 0 (0\%) & 1,648 (4.7\%) \\
Unknown & 0 & 13,165 \\
\end{longtable}

Table~\ref{tbl-table-exposures} presents baseline (NZAVS time 10) and
exposure wave (NZAVS time 11) statistics for the exposure variable:
religious service attendance (range 0-8). Responses coded as eight or
above were coded as ``8''. This decision to avoid spare treatments was
based on theoretical grounds, namel, that daily exposure would be
similar in its effects to more than daily exposure. We note that causal
contrasts were obtained for projects at either no attendance or
four-or-more visits per month. Hence this simplification of the measure
is unlikely to affect theoretical and practical inferences. Because the
treatment wave (NZAVS time 11) occurred to New Zealand's COVID-19
pandemic, all models adjusted for the pandemic alert-level. The pandemic
is a not a ``confounder'' because a confounder must be related to the
treatment and the outcome. At the end of the study, all participants had
been exposed to the pandemic. However, to satisfy the causal consistency
assumption, all treatments must be conditionally equivalent within
levels of all covariates (\citeproc{ref-vanderweele2013}{VanderWeele and
Hernan 2013}). Because COVID affected the ability or willingness of
individuals to attend religious service, we included the lockdown
condition as a covariate (\citeproc{ref-sibley2012a}{Sibley and Bulbulia
2012}). To better enable conditional independence within levels of the
treatment variable, we conditioned on the lead value of COVID-alert
level at baseline. To mitigate systematic biases arising from attrition,
and missingness, the \texttt{lmtp} package uses inverse probability of
censoring weights, which were use when estimating the causal effects of
the exposure on the outcome.

\subsubsection{Transition Table for The
Treatment}\label{transition-table-for-the-treatment}

Table~\ref{tbl-transition} shows a transition matrix that captures
stability and movement between disinhibition responses from the baseline
(NZAVS time 10) wave and exposure wave (NZAVS time 11) among all
participants who responded to the religion question at baseline and in
the following year (the censored sample). Entries on the diagonal (in
bold) indicate the number of individuals who stayed in their initial
state. In contrast, the off-diagonal shows the transitions from the
initial state (bold) to another state the following wave (off-diagonal).
A cell located at the intersection of row \(i\) and column \(j\), where
\(i \neq j\), shows the count of individuals moving from state \(i\) to
state \(j\).

\begin{longtable}[]{@{}ccc@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave. The diagonal shows stability in response. The
off-diagonal shows the number of transitions from the initial state
(bold) to another state in the following wave
(off-diagonal).}\label{tbl-transition}\tabularnewline
\toprule\noalign{}
From & Not Religious & Religious \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & Not Religious & Religious \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Not Religious & \textbf{20959} & 1183 \\
Religious & 1977 & \textbf{10624} \\
\end{longtable}

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4474}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2763}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2763}}@{}}
\caption{Outcomes measured at baseline and
end-of-study}\label{tbl-table-outcomes}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Annual Charity} & 120 (25, 500) & 200 (20, 520) \\
Unknown & 3,181 & 16,514 \\
\textbf{Community Gives Money Binary} & 205 (0.4\%) & 144 (0.5\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Community Gives Time Binary} & 2,389 (5.2\%) & 1,934 (6.2\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Family Gives Money Binary} & 2,802 (6.1\%) & 1,477 (4.7\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Family Gives Time Binary} & 13,590 (30\%) & 8,867 (29\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Friends Give Money Binary} & 589 (1.3\%) & 321 (1.0\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Friends Give Time Binary} & 8,201 (18\%) & 5,664 (18\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Sense Neighbourhood Community} & NA & NA \\
1 & 3,025 (6.3\%) & 1,383 (4.3\%) \\
2 & 5,953 (12\%) & 3,252 (10\%) \\
3 & 7,033 (15\%) & 4,283 (13\%) \\
4 & 9,911 (21\%) & 6,961 (22\%) \\
5 & 9,924 (21\%) & 7,625 (24\%) \\
6 & 8,055 (17\%) & 5,921 (19\%) \\
7 & 3,781 (7.9\%) & 2,503 (7.8\%) \\
Unknown & 266 & 16,020 \\
\textbf{Social Belonging} & 5.33 (4.33, 6.00) & 5.00 (4.33, 6.00) \\
Unknown & 450 & 16,114 \\
\textbf{Social Support} & 6.33 (5.33, 7.00) & 6.33 (5.33, 7.00) \\
Unknown & 38 & 15,919 \\
\textbf{Volunteering Hours} & 0.00 (0.00, 1.00) & 0.00 (0.00, 1.00) \\
Unknown & 1,538 & 16,738 \\
\textbf{Volunteers Binary} & 12,905 (28\%) & 8,004 (26\%) \\
Unknown & 1,538 & 16,738 \\
\end{longtable}

Table~\ref{tbl-table-outcomes} presents baseline and end-of-study
descriptive statistics for the outcome variables.

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, J (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, S, J. A. (2015) Religion and parental cooperation: An
empirical test of slone's sexual signaling model. In \&. V. S. J. Slone
D., ed., \emph{The attraction of religion: A sexual selectionist
account}, Bloomsbury Press, 29--62.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.
doi:\href{https://doi.org/10.1207/s15327752jpa8301_04}{10.1207/s15327752jpa8301\_04}.

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017b) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fahy2017a}
Fahy, KM, Lee, A, and Milne, BJ (2017a) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a new zealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-hoverd_religious_2010}
Hoverd, WJ, and Sibley, CG (2010) Religious and denominational diversity
in new zealand 2009. \emph{New Zealand Sociology}, \textbf{25}(2),
59--87.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-sengupta2013}
Sengupta, NK, Luyten, N, Greaves, LM, \ldots{} Sibley, CG (2013) Sense
of Community in New Zealand Neighbourhoods: A Multi-Level Model
Predicting Social Capital. \emph{New Zealand Journal of Psychology},
\textbf{42}(1), 36--45.

\bibitem[\citeproctext]{ref-sibley2012a}
Sibley, CG, and Bulbulia, J (2012) Faith after an earthquake: A
longitudinal study of religion and perceived health before and after the
2011 christchurch new zealand earthquake. \emph{PloS One},
\textbf{7}(12), e49648.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in New Zealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-stronge2019onlychild}
Stronge, S, Shaver, JH, Bulbulia, J, and Sibley, CG (2019) Only children
in the 21st century: Personality differences between adults with and
without siblings are very, very small. \emph{Journal of Research in
Personality}, \textbf{83}, 103868.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the e-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 120.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-williams_cyberostracism_2000}
Williams, KD, Cheung, CKT, and Choi, W (2000) Cyberostracism: Effects of
being ignored over the internet. \emph{Journal of Personality and Social
Psychology}, \textbf{79}(5), 748--762.
doi:\href{https://doi.org/10.1037/0022-3514.79.5.748}{10.1037/0022-3514.79.5.748}.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{Lmtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\end{CSLReferences}



\end{document}
