% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=20mm,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal effects of Religious Service Attendance: Evidence From A National Longitudinal Panel},
  pdfauthor={Joseph A. Bulbulia; Don E Davis; Ken Rice; Chris G. Sibley; Geoffrey Troughton},
  pdfkeywords={Causal
Inference, Charity, Church, Cooperation, Religion, Shift
Intervention, Volunteering},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal effects of Religious Service Attendance: Evidence From A
National Longitudinal Panel}
\author{Joseph A. Bulbulia \and Don E Davis \and Ken Rice \and Chris G.
Sibley \and Geoffrey Troughton}
\date{2024-04-15}

\begin{document}
\maketitle
\begin{abstract}
The question ``Does religion cause prosociality?'' lacks precision. To
ask a causal question, we must state a causal contrast for a
well-defined feature of religion, specify measures of ``prosociality'',
define our target population, obtain relevant time series data, and --
if assumptions are satisfied and causal identification criteria are met
-- compute statistical estimates. Here, we analyse three causal
interventions on religious service attendance (gain, loss, status quo)
in a national longitudinal sample of 33,198 New Zealanders over
2018-2021. Study 1 estimates the causal effects of religious service on
charitable giving and volunteering. Studies 2 and 3 estimate the causal
effects of religious service on the ``risk'' of receiving help and money
from others (measures that avoid self-presentation bias). For all
interventions, effects are considerably weaker than suggested by
cross-sectional associations. However, if all were to attend religious
service regularly, the net gain to charitable donations would amount to
4\% of the New Zealand Government's annual expenditure. This study
highlights the mission-critical importance of stating precise causal
questions and serves as a blueprint for quantitative causal studies of
cultural practices.
\end{abstract}

\subsection{Introduction}\label{introduction}

A central question in the scientific study of religion is whether
religion causes cooperation (\citeproc{ref-bulbuliaj.2013}{Bulbulia, J.
\emph{et al.} 2013}; \citeproc{ref-johnson2005}{Johnson 2005};
\citeproc{ref-norenzayan2016}{Norenzayan \emph{et al.} 2016};
\citeproc{ref-watts2016}{Watts \emph{et al.} 2016};
\citeproc{ref-watts2015}{Watts and Gray 2015}). However, to attach
magnitudes to causal effects -- for religion and other social behaviours
-- is challenging. Most features of religion are inaccessible to
randomised controlled experiments. Yet to obtain valid causal inferences
from non-experimental data requires a combination of high-resolution
time-series data and robust causal inferential methods. Few studies
combine these qualities (see Kelly \emph{et al.}
(\citeproc{ref-kelly2024religiosity}{2024}), although for indirect
causal evidence, see Sosis and Bressler
(\citeproc{ref-sosis2003cooperation}{2003}); for an appropriately
designed observational study of religious service on mental health, a
different topic, see Chen \emph{et al.}
(\citeproc{ref-chen2020religious}{2020})).

Equally fundamental, it must be acknowledged that ``does religion cause
prosociality?'' is poorly defined. To make this question precise, we
must state a causal contrast of interest, state the specific measures of
``prosociality'' to be evaluated, define the target population for whom
results are meant to generalise, obtain relevant time series data, and
-- if assumptions are satisfied and causal identification criteria are
met -- compute statistical estimates and perform sensitivity analyses
(Hernan and Robins (\citeproc{ref-hernan2024WHATIF}{2024}); Ogburn and
Shpitser (\citeproc{ref-ogburn2021}{2021}); Bulbulia
(\citeproc{ref-bulbulia2022}{2022})).

Here, we leverage comprehensive panel data from 33198 who participated
in the New Zealand Attitudes and Values Study from 2018-2021 and
investigate the effects of well-defined population-level shifts in
religious attendance across three measurement domains of pro-sociality.

Following the Neyman-Rubin causal model, we define causal effects as
quantitative contrasts of potential outcomes under different treatment
conditions in a target population (\citeproc{ref-neyman1923}{Neyman
1923}; \citeproc{ref-rubin2005}{Rubin 2005}). We express these
conditions as modified treatment policies
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-haneuse2013estimation}{Haneuse and Rotnitzky 2013};
\citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023};
\citeproc{ref-diaz2023lmtp}{Iván Díaz and Schenck 2023})

Our first causal contrast addresses the question: ``What would be the
difference on average across the population of New Zealand if everyone
attended religious service regularly (defined as at least four times per
month) compared with if no one ever attended religious service?'' This
question holds theoretical interest. It resembles a hypothetical
experiment in which everyone is randomly assigned to a regular or
zero-attendance condition.

The second causal contrast addresses the question: ``what would be the
difference, on average, across the population of New Zealand if everyone
attended religious service regularly compared with the status quo?''
Notice that this causal contrast does not require shifting people who
regularly attend religious services to zero attendance. This causal
question clarifies the implications of policies that target the
behaviours of those who do not attend regular religious service.

The third causal contrast addresses the question: ``what would be the
difference on average across the population of New Zealand if no one
attended religious service at all compared with the status quo?'' Here
the potential outcomes of interest do not require shifting who never
attend religious service. This causal question clarifies the
implications of policies that target the behaviours of those who attend
regular religious services.

Note that there are innumerably many causal contrasts we might have
considered. Those we investigate here give insights into the distinct
effect of losses and gains of religious service attendance rates across
New Zealand.

Finally, we did not set out to test a specific hypothesis but to compute
causal associations as accurately as possible, using appropriate
time-series data and robust methods for causal inference (following
Hernán and Greenland (\citeproc{ref-hernan2024stating}{2024})).

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected by the New Zealand Attitudes and Values Study
(NZAVS), an annual longitudinal national probability panel study of
social attitudes, personality, ideology and health outcomes in New
Zealand. Chris G. Sibley started the NZAVS in 2009. It has since grown
to a community of over fifty researchers. Since its inception, the NZAVS
has collected questionnaire responses from 72910 New Zealand residents.
The NZAVS is university-based, not-for-profit and independent of
political or corporate funding; see
https://doi.org/10.17605/OSF.IO/75SNB. Sample information and data
summaries are given in Appendices B-D.

\subsubsection{Treatment indicator}\label{treatment-indicator}

The NZAVS assesses religious service attendance by asking:

\begin{itemize}
\tightlist
\item
  \emph{Do you identify with a religion and/or spiritual group? If
  yes\ldots How many times did you attend a church or place of worship
  during the last month?}
\end{itemize}

We rounded values to the nearest whole number. Because the measure is
dispersed, responses over eight were assigned a value of eight (see
histograms below).

\subsubsection{Measures of prosociality}\label{measures-of-prosociality}

There are two self-reported measures of prosocial behaviour in the
NZAVS:

\textbf{Study 1. Self-reported charity} as measured by:

\begin{itemize}
\item
  Volunteering: \emph{``Please estimate how many hours you spent doing
  each of the following things last week\ldots Volunteer/charitable
  work''}
\item
  Annual charitable financial donations (dollars): \emph{``How much
  money have you donated to charity in the last year?''}
\end{itemize}

\textbf{Study 2: Help received from others in the last week: TIME}

\emph{Please estimate how much help you have received from the following
sources in the last week.}

\begin{itemize}
\tightlist
\item
  \emph{Family\ldots TIME (hours)}
\item
  \emph{Friends\ldots TIME (hours)}
\item
  \emph{Community\ldots TIME (hours)}
\end{itemize}

Because this measure was highly variable, we converted responses to
binary indicators: \emph{0 = none/ 1=any}

\textbf{Study 3: Help received from others in the last week: DOLLARS}

\emph{Please estimate how much help you have received from the following
sources in the last week.}

\begin{itemize}
\tightlist
\item
  \emph{Family\ldots MONEY (hours)}
\item
  \emph{Friends\ldots MONEY (hours)}
\item
  \emph{Community\ldots MONEY (hours)}
\end{itemize}

Because this measure was highly variable, we converted responses to
binary indicators: \emph{0 = none/ 1 = any}

We note that Studies 2 and 3 minimise self-presentation bias by using
individuals as measures of prosocial outcomes based on the following
assumption: if religious service attendance induced greater within-group
prosociality, then regular religious service attendance would increase
prosocial exposures. Self-reported dependencies are robust to directed
self-presentation bias that might induce the appearance of a causal
association between religious service attendance and prosocial
behaviour.

Full details of all these measures and all used for covariate control
are provided in \emph{Appendix A.}

\subsubsection{Causal Contrasts}\label{causal-contrasts}

We defined three targeted causal contrasts (or ``causal estimands'') in
the form of ``modified treatment policies''''

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Regular Religious Service Treatment}: treat everyone in the
  adult population with regular religious service attendance such that
  if an individual's religious service attendance is below four times
  per month, shift to four, otherwise do not shift:

  \[
  \mathbf{d}^\lambda (a_1) = \begin{cases} a_1 = 4 & \text{if $a_1$ < 4} \\ 
    a_t = a_t & \text{otherwise} \end{cases}
  \]
\item
  \textbf{Zero Religious Service Treatment}: treat everyone in the adult
  population of New Zealand with no religious service attendance, such
  that if an individual's religious service attendance is greater than
  0, shift to zero otherwise do not shift:

  \[
  \mathbf{d}^\phi (a_1) = \begin{cases} a_1 = 0 & \text{if $a_1$ > 0} \\ 
    a_t = 0 & \text{otherwise} \end{cases}
  \]
\item
  \textbf{Null model}: do not treat: compute each expected mean outcome
  at the natural value of religious service attendance corresponding to
  each individual's stated attendance frequency:

  \[
  \mathbf{d}(a_1) = \text{the observed value of $a_1$ is assumed without modification}
  \]
\end{enumerate}

From these expected average outcomes for the population for three
treatment regimes, we computed the following causal contrasts:

\textbf{Target Contrast A: `Regular vs Zero'} How much does a society
with regular religious service attendance differ in its prosocial
effects from a society with zero religious service attendance?

\[ \text{Regular Religious Service vs Zero Religious Service} = E[Y(\mathbf{d}^\lambda)- Y(\mathbf{d}^\phi)] \]

This contrast corresponds to the scientifically interesting hypothetical
experiment in which we could randomise people into regular religious
service vs.~no religious service and assess prosociality measures one
year later.

\textbf{Target Contrast A: `Regular vs NULL'}: How much does a society
with regular religious service attendance differ from its status quo?

\[ \text{Regular Religious Service vs  No Treatment} = E[Y(\mathbf{d}^\lambda)- Y(\mathbf{d})] \]

This contrast corresponds to the policy relevant hypothetical experiment
in which we randomise people into regular religious service and assess
whether it makes any difference to society as it is now. That is, if our
aim is to promote prosociality, should regular religious service be
encouraged, discouraged, or does it make no practical difference?

\textbf{Target Contrast C: `Zero vs NULL'}: How much does a society with
zero religious service attendance differ from its status quo?

\[ \text{Zero Religious Service vs No Treatment} = E[Y(\mathbf{d}^\phi)- Y(\mathbf{d})] \]

This contrast corresponds to the policy-relevant hypothetical experiment
in which we randomise people into zero religious services and assess
whether it makes any difference to society as it is now. Should the loss
of religious service be encouraged or discouraged if we aim to promote
prosociality, or does it make no practical difference?

\subsubsection{Identification
Assumptions}\label{identification-assumptions}

To consistently estimate causal effects, we rely on three key
assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal consistency:} potential outcomes must align with
  observed outcomes under the treatments in our data. Essentially, we
  assume potential outcomes do not depend on how treatment was
  administered, conditional on measured covariates.
\item
  \textbf{Exchangeability} given the observed covariates, we assume
  treatment assignment is independent of the potential outcomes to be
  contrasted and all future counterfactual responses. In simpler terms,
  this means ``no unmeasured confounding.''
\item
  \textbf{Positivity:} for unbiased estimation, every subject must have
  a non-zero chance of receiving the treatment, regardless of their
  covariate values. We evaluate this assumption in each study by
  examining changes in religious service attendance from baseline (NZAVS
  time 10) to the treatment wave (NZAVS time 11). For further discussion
  of these assumptions in the context of NZAVS studies, see
  (\citeproc{ref-bulbulia2023a}{Bulbulia \emph{et al.} 2023})
\end{enumerate}

\subsubsection{Target Population}\label{target-population}

The target population is the population of New Zealand at the baseline
wave (years 2018-2019). The New Zealand Attitudes and Values Study is a
national probability study with a good representation of the New Zealand
population. However, its coverage is not perfect. For example, the study
under-samples males and Asians and over-samples women and Māori (New
Zealand's indigenous peoples). Therefore, we pass New Zealand Census
survey weights when computing marginal treatment effects; in this study
we weighted the sample to age, gender and ethnicity. Methods for these
weights are described in {[}{]}.

\subsubsection{Eligibility criteria}\label{eligibility-criteria}

\begin{itemize}
\tightlist
\item
  Enrolled in the New Zealand Attitudes and Values Study wave 2018
  (NZAVS time 10).
\item
  No missing data about religious service attendance at baseline (NZAVS
  time 10)
\item
  Missing covariate data at baseline permitted (and imputed).
\item
  May have been lost to follow up/not responded at the end of the study.
\end{itemize}

There were 33198 who met these criteria.

\subsubsection{Causal Identification}\label{causal-identification}

\begin{table}

\caption{\label{tbl-02}Causal Single-World Intervention Graphs}

\centering{

\lmtptablethree

}

\end{table}%

Table~\ref{tbl-02} Presents a series of three Single World Intervention
Graphs that describe our identification strategy. The strategy is the
same for each function we estimate.

\subsubsection{Missing Data Handling}\label{missing-data-handling}

As mentioned, to better ensure that the analyses were robust to
potential biases introduced by missing data, we adopted the following
strategies:

\begin{itemize}
\tightlist
\item
  \textbf{Baseline missingness}: we imputed missing data to recover
  baseline missing data using the \texttt{ppm} algorithm from the
  \texttt{mice} package in R (\citeproc{ref-vanbuuren2018}{Van Buuren
  2018}).
\item
  \textbf{Outcome missingness}: We used the \texttt{lmtp} package's
  built-in censoring weighting to adjust for loss-to-follow-up/sample
  attrition (\citeproc{ref-williams2021}{Williams and Díaz 2021}).
\end{itemize}

\subsubsection{Confounding control}\label{confounding-control}

We use VanderWeele \emph{et al.} (\citeproc{ref-vanderweele2020}{2020})
\emph{modified disjunctive cause criterion} in which we (1) identified
all common causes of the treatment and outcomes; (2) removed any
variables identified that might influence the exposure but not the
outcome -- instrumental variables -- because instrumental variables are
known to reduce efficiency; (3) included proxies for any unmeasured
variables affecting both exposure and outcome -- including instrumental
variables, because by the rules of d-separation, conditioning on a proxy
is akin to conditioning on its parent (in this case, a confounder) (4)
\textbf{control for baseline exposure} and (5) \textbf{control for
baseline outcome} Both serve as proxies for unmeasured common causes
(\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).
\hyperref[appendix-demographics]{Appendix B} lists covariates we used
for confounding control. These protocols follow the advice in
(\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024a}) as prespecified
in \url{https://osf.io/ce4t9/}.

\subsubsection{Analytic Approach}\label{analytic-approach}

We employ a semi-parametric Targeted Learning, specifically a Targeted
Minimum Loss-based Estimation (TMLE) estimator. TMLE is a robust method
that combines machine learning techniques with traditional statistical
models to estimate causal effects while providing valid statistical
uncertainty measures for these estimates.

TMLE operates through a two-step process involving both the outcome and
treatment (exposure) models. Initially, it employs machine learning
algorithms to flexibly model the relationship between treatments,
covariates, and outcomes. This flexibility allows TMLE to account for
complex, high-dimensional covariate spaces without imposing restrictive
model assumptions. The outcome of this step is a set of initial
estimates for these relationships.

The second step of TMLE involves ``targeting'' these initial estimates
by incorporating information about the observed data distribution to
improve the accuracy of the causal effect estimate. This is achieved
through an iterative updating process, which adjusts the initial
estimates towards the true causal effect. This updating process is
guided by the efficient influence function, ensuring that the final TMLE
estimate is as close as possible, given the measures and data, to the
true causal effect while still being robust to model misspecification in
either the outcome model or the treatment model.

Again, a central feature of TMLE is its double-robustness property. This
means that if either the model for the treatment or the outcome is
correctly specified, the TMLE estimator will still consistently estimate
the causal effect. Additionally, TMLE uses cross-validation to avoid
over-fitting and ensure that the estimator performs well in finite
samples. Each step contributes to a robust methodology for examining the
\emph{causal} effects of interventions on outcomes. The marriage of TMLE
and machine learning technologies reduces the dependence on restrictive
modelling assumptions and introduces an additional layer of robustness.
For further details see (\citeproc{ref-duxedaz2021}{Díaz \emph{et al.}
2021}; \citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023}). We performed estimation using the
\texttt{lmtp} package (\citeproc{ref-williams2021}{Williams and Díaz
2021}). We used the \texttt{superlearner} library for non-parametric
estimation with the predefined libraries \texttt{SL.ranger},
\texttt{SL.glmnet}, and \texttt{SL.xboost}. Graphs, tables and output
reports were created using the \texttt{margot} package
(\citeproc{ref-margot2024}{Bulbulia 2024b}). All analysis methods follow
pre-stated protocols in Bulbulia
(\citeproc{ref-bulbulia2024PRACTICAL}{2024a}).

\paragraph{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess the sensitivity of results to unmeasured confounding, we
report VanderWeele and Ding's ``E-value'' in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). To
evaluate the strength of evidence, we use the bound of the E-value 95\%
confidence interval closest to 1.

\subsubsection{Scope of Interventions}\label{scope-of-interventions}

To better understand the scope of the interventions to be contrasted, we
recommend presenting histograms showing treatment instances. Below are
treatment responses in the exposure wave (baseline + 1).

The regular service intervention \(d(A=a^*)\) is shown in
Figure~\ref{fig-0up}.

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-0up-1.pdf}

}

\caption{\label{fig-0up}Figure shows a histogram of responses to
religious service frequency in the baseline + 1 wave. Responses above
eight were assigned to eight, and values were rounded to the nearest
whole number. The red dashed line shows the population average. All
responses in the gold bars are shifted to four on the ALL-GAIN
intervention. All those responses in grey (four and above) remain
unchanged}

\end{figure}%

Notably, the `regular religious service' intervention requires shifting
a considerable mass of the sample population. However, it does not
require shifting those who are attending religious service more
frequently than four times per month.

The `zero religious service' intervention \(d(A=a^\prime)\) intervention
is shown in Figure~\ref{fig-0down}

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-0down-1.pdf}

}

\caption{\label{fig-0down}Figure shows a histogram of responses to
religious service frequency in the baseline + 1 wave. Responses above
eight were assigned to eight, and values were rounded to the nearest
whole number. The red dashed line shows the population average. All
responses in the blue bars are shifted to zero on the loss intervention.
All those responses in grey (zero) remain unchanged.}

\end{figure}%

Notably, the zero religious service intervention requires shifting a
smaller proportion of the sample population than the regular religious
service intervention. Because religious service is declining in New
Zealand, zero intervention arguably holds more policy interest: the
implications of loss are relevant to a society where loss occurs.

\subsubsection{Evidence for Change in the Treatment
Variable}\label{evidence-for-change-in-the-treatment-variable}

Table~\ref{tbl-transition} clarifies the change in the treatment
variable from the baseline wave to the baseline + 1 wave across the
sample. Assessing change in a variable is essential for evaluating the
positivity assumption and recovering evidence for the incidence-effect
of the treatment variable {[}{]}.

\begin{table}

\caption{\label{tbl-placeholder}}

\centering{

\captionsetup{labelsep=none}

}

\end{table}%

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1196}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}@{}}
\caption{This transition matrix captures shifts in states across two
waves---baseline and treatment---for individuals under study. Each cell
in the matrix represents the count of individuals transitioning from one
state to another. The rows correspond to the state at baseline (From),
and the columns correspond to the state at the treatment wave (To).
\textbf{Diagonal entries} (in \textbf{bold}): these signify the number
of individuals who remained in their initial state across both waves.
\textbf{Off-diagonal entries}: these signify the transitions of
individuals from their baseline state to a different state in the
treatment wave. A higher number on the diagonal relative to the
off-diagonal entries in the same row indicates greater stability in a
state. Conversely, higher off-diagonal numbers suggest more significant
shifts from the baseline state to other
states.}\label{tbl-transition}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 0 & \textbf{26762} & 405 & 174 & 71 & 126 & 26 & 13 & 8 & 68 \\
State 1 & 647 & \textbf{235} & 85 & 44 & 46 & 5 & 2 & 3 & 10 \\
State 2 & 236 & 105 & \textbf{188} & 104 & 96 & 12 & 13 & 2 & 21 \\
State 3 & 112 & 54 & 110 & \textbf{164} & 173 & 18 & 8 & 4 & 15 \\
State 4 & 150 & 71 & 127 & 205 & \textbf{881} & 124 & 64 & 16 & 91 \\
State 5 & 24 & 7 & 17 & 17 & 145 & \textbf{61} & 25 & 7 & 33 \\
State 6 & 14 & 5 & 13 & 17 & 84 & 22 & \textbf{29} & 5 & 37 \\
State 7 & 9 & 0 & 6 & 3 & 16 & 6 & 9 & \textbf{6} & 19 \\
State 8 & 74 & 14 & 17 & 14 & 105 & 34 & 42 & 17 & \textbf{351} \\
\end{longtable}

Table~\ref{tbl-transition} presents the state change in religious
service frequency between the first and second waves. We find that state
4 (weekly attendance) and state 0 present the highest overall. However,
we also find that movement between these states reveals they are not
deterministic. States 1, 2, 3, and 5 indicate relatively frequent
movement in and out of these states, suggesting lower stability.

\newpage{}

\subsection{Results}\label{results}

\subsubsection{Study 1: Causal Effects of Regular Church Attendance on
Self-Reported Volunteering and Self-Reported Volunteering and
Donations}\label{study-1-causal-effects-of-regular-church-attendance-on-self-reported-volunteering-and-self-reported-volunteering-and-donations}

\paragraph{Regular vs Zero Causal Contrast on Donations and
Volunteering}\label{regular-vs-zero-causal-contrast-on-donations-and-volunteering}

Figure~\ref{fig-1_1} and Table~\ref{tbl-1_1} present results for the
ALL-GAIN vs.~ALL-LOSS treatment policy on self-reported volunteering and
charitable donations

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-1_1-1.pdf}

}

\caption{\label{fig-1_1}This figure reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs universal loss of weekly religious service on reported
charitable behaviours at the end of the study. Outcomes are expressed in
standard deviation units.}

\end{figure}%

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-1_1}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs universal loss of weekly religious service on reported
charitable behaviours at the end of the study. Outcomes are expressed in
standard deviation units.}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.13 & 0.10 & 0.16 & 1.51 & 1.43 \\
hours volunteer & 0.12 & 0.09 & 0.16 & 1.48 & 1.39 \\

\end{longtable}

For `donations', the effect estimate is 0.132 {[}0.102, 0.161{]}. The
E-value for this estimate is 1.507, with a lower bound of 1.426. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1.426 to
negate the observed effect. Weaker associations would not overturn it.
We infer \textbf{evidence for causality}.

The effect estimate for `hours volunteer' is 0.123 {[}0.09, 0.156{]}.
The E-value for this estimate is 1.482, with a lower bound of 1.389. We
infer \textbf{evidence for causality}.

\newpage{}

\paragraph{Regular vs Status Quo Causal Contrast on Donations and
Volunteering}\label{regular-vs-status-quo-causal-contrast-on-donations-and-volunteering}

Figure~\ref{fig-1_2} and Table~\ref{tbl-1_2} present results for the
ALL-GAIN vs.~STATUS QUO treatment policy on self-reported volunteering
and charitable donations

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-1_2-1.pdf}

}

\caption{\label{fig-1_2}This figure reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs status quo on reported charitable behaviours at the end of
the study. Outcomes are expressed in standard deviation units.}

\end{figure}%

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-1_2}Table reports results of model estimates for the
causal effects of a universal gain of weekly religious service vs status
quo on reported charitable behaviours at the end of the study. Outcomes
are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.12 & 0.10 & 0.14 & 1.48 & 1.42 \\
hours volunteer & 0.10 & 0.07 & 0.12 & 1.40 & 1.32 \\

\end{longtable}

For `donations', the effect estimate is 0.121 {[}0.102, 0.14{]}. The
E-value for this estimate is 1.477, with a lower bound of 1.422. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1.422 to
negate the observed effect. Weaker confounding would not overturn it. We
infer \textbf{evidence for causality}.

On the data scale, this intervention represents a difference of NZD
601.87 per adult per year in charitable giving.

The effect estimate for `hours volunteer' is 0.095 {[}0.066, 0.123{]}.
The E-value for this estimate is 1.404, with a lower bound of 1.317. At
this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.317 to negate the observed effect. Again, weaker confounding would not
overturn it. We infer that \textbf{the evidence for causality is not
reliable}.

On the data scale, this intervention represents a difference of NZD `r
round( sd\_volunteer * tab\_all\_prosocial\_null{[}2,1{]} * 60,
2)minutes per adult per week in charitable giving.

\newpage{}

\paragraph{Zero vs Status Quo Causal Contrast on Donations and
Volunteering}\label{zero-vs-status-quo-causal-contrast-on-donations-and-volunteering}

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-1_3-1.pdf}

}

\caption{\label{fig-1_3}Figure reports results of model estimates for
the causal effects of a universal loss of weekly religious service vs
status quo on reported charitable behaviours at the end of the study.
Outcomes are expressed in standard deviation units.}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1212}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1818}}@{}}

\caption{\label{tbl-1_3}Table reports results of model estimates for the
causal effects of a universal loss of weekly religious service vs status
quo on reported charitable behaviours at the end of the study. Outcomes
are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & -0.011 & -0.029 & 0.008 & 1.111 & 1.000 \\
hours volunteer & -0.028 & -0.042 & -0.014 & 1.189 & 1.128 \\

\end{longtable}

For `donations', the effect estimate is -0.011 {[}-0.029, 0.008{]}. The
E-value for this estimate is 1.111, with a lower bound of 1. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1 to negate
the observed effect. Weaker confounding would not overturn it. We infer
that \textbf{the evidence for causality is not reliable}.

On the data scale, this intervention represents a difference of NZD
-54.72 per adult per year in charitable giving, but again, the effect is
not reliable

The effect estimate for `hours volunteer' is -0.028 {[}-0.042,
-0.014{]}. The E-value for this estimate is 1.189, with a lower bound of
1.128. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.128 to negate the observed effect. Again, weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

On the data scale, this intervention represents a difference of -6.88 in
volunteering minutes.

\newpage{}

\subsubsection{Study 2: Causal Effects of Regular Church Attendance on
Support Received From Others --
Time}\label{study-2-causal-effects-of-regular-church-attendance-on-support-received-from-others-time}

\paragraph{Regular vs.~Zero Causal Contrast on Time Received From
Others}\label{regular-vs.-zero-causal-contrast-on-time-received-from-others}

For `community gives time', the effect estimate on the risk ratio scale
is 1.378 {[}1.231, 1.541{]}. The E-value for this estimate is 2.1, with
a lower bound of 1.764. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.764 to negate the observed effect. Weaker
associations would not overturn it. We infer \textbf{evidence for
causality}.

For `friends give time', the effect estimate risk ratio scale is 1.187
{[}1.108, 1.271{]}. The E-value for this estimate is 1.658, with a lower
bound of 1.454. At this lower bound, unmeasured confounders would need a
minimum association strength with both the intervention sequence and
outcome of 1.454 to negate the observed effect. Weaker associations
would not overturn it. We infer \textbf{evidence for causality}.

For `family gives time', the effect estimate on the risk ratio scale is
0.95 {[}0.901, 1.003{]}. The E-value for this estimate is 1.288, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker associations would
not overturn it. We infer that \textbf{the evidence for causality is not
reliable}.

\newpage{}

\paragraph{Regular vs Status Quo Causal Contrast on Time Received From
Others}\label{regular-vs-status-quo-causal-contrast-on-time-received-from-others}

For `community gives time', the effect estimate on the risk ratio scale
is 1.289 {[}1.174, 1.415{]}. The E-value for this estimate is 1.899,
with a lower bound of 1.626. Unmeasured confounders would need a minimum
association strength with the intervention sequence and outcome of 1.626
at this lower bound to negate the observed effect. Weaker confounding
would not overturn it. We infer \textbf{evidence for causality}.

For `friends gives time', the effect estimate on the risk ratio scale
1.128 {[}1.061, 1.199{]}. The E-value for this estimate is 1.508, with a
lower bound of 1.315. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1.315 to negate the observed effect. Weaker confounding
would not overturn it. We infer \textbf{evidence for causality}.

For `family gives time', the effect estimate on the risk ratio scale is
0.958 {[}0.913, 1.006{]}. The E-value for this estimate is 1.258, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker confounding would not
overturn it. We infer that \textbf{evidence for causality is not
reliable}.*

\newpage{}

\paragraph{Zero vs Status Quo Causal Contrast on Time Received From
Others}\label{zero-vs-status-quo-causal-contrast-on-time-received-from-others}

For `family gives time', the effect estimate on the risk ratio scale is
1.008 {[}0.991, 1.026{]}. The E-value for this estimate is 1.098, with a
lower bound of 1. We infer \textbf{that evidence for causality is not
reliable}.

For `friends gives time', the effect estimate on the risk ratio scale is
0.95 {[}0.928, 0.973{]}. The E-value for this estimate is 1.288, with a
lower bound of 1.197. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1.197 to negate the observed effect. Weaker confounding
would not overturn it. We infer \textbf{evidence for causality}.

For `community gives time', the effect estimate on the risk ratio scale
is 0.936 {[}0.889, 0.985{]}. The E-value for this estimate is 1.339,
with a lower bound of 1.14. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.14 to negate the observed effect. Weaker
confounding would not overturn it. We infer \textbf{evidence for
causality}.

\newpage{}

\subsubsection{Study 3: Causal Effects of Regular Church Attendance on
Support Received From Others --
Money}\label{study-3-causal-effects-of-regular-church-attendance-on-support-received-from-others-money}

\paragraph{Regular vs Zero Causal Contrast on Money Received From
Others}\label{regular-vs-zero-causal-contrast-on-money-received-from-others}

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-3_1-1.pdf}

}

\caption{\label{fig-3_1}This figure reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs universal loss of weekly religious service on financial help
received from others during the past week (yes/no) at the end of the
study. Outcomes are expressed on the risk ratio scale.}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_1}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs universal loss of weekly religious service on financial help
received from others during the past week (yes/no) at the end of the
study. Outcomes are expressed on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.14 & 1.03 & 1.26 & 1.53 & 1.20 \\
friends give money & 1.14 & 0.96 & 1.34 & 1.53 & 1.00 \\
community gives money & 1.38 & 1.11 & 1.70 & 2.10 & 1.47 \\

\end{longtable}

For `community gives money', the effect estimate on the risk ratio scale
is 1.376 {[}1.112, 1.703{]}. The E-value for this estimate is 2.095,
with a lower bound of 1.465. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.465 to negate the observed effect. Weaker
confounding would not overturn it. We infer \textbf{evidence for
causality}.

For `family gives money', the effect estimate on the risk ratio scale is
1.137 {[}1.028, 1.258{]}. The E-value for this estimate is 1.532, with a
lower bound of 1.198. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1.198 to negate the observed effect. Weaker confounding
would not overturn it. We infer \textbf{evidence for causality}.

For `friends give money', the effect estimate on the risk ratio scale is
1.137 {[}0.964, 1.342{]}. The E-value for this estimate is 1.532, with a
lower bound of 1. We infer \textbf{that evidence for causality is not
reliable}..

\newpage{}

\paragraph{Regular vs Status Quo Causal Contrast on Money Received From
Others}\label{regular-vs-status-quo-causal-contrast-on-money-received-from-others}

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-3_2-1.pdf}

}

\caption{\label{fig-3_2}Figure reports results of model estimates for
the causal effects of a universal gain of weekly religious service vs
status quo on financial help received from others during the past week
(yes/no) at the end of study. Outcomes are expressed on the risk ratio
scale.}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_2}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs status quo on financial help received from others during the
past week (yes/no) at the end of the study. Outcomes are expressed on
the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.13 & 1.04 & 1.23 & 1.51 & 1.23 \\
friends give money & 1.04 & 0.95 & 1.14 & 1.25 & 1.00 \\
community gives money & 1.25 & 1.10 & 1.43 & 1.82 & 1.43 \\

\end{longtable}

For `community gives money', the effect estimate on the risk ratio scale
is 1.254 {[}1.098, 1.432{]}. The E-value for this estimate is 1.818,
with a lower bound of 1.426. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.426 to negate the observed effect. Weaker
confounding would not overturn it. We infer \textbf{evidence for
causality}.

For `family gives money', the effect estimate on the risk ratio scale is
1.13 {[}1.037, 1.232{]}. The E-value for this estimate is 1.513, with a
lower bound of 1.233. Unmeasured confounders would need a minimum
association strength with the intervention sequence and outcome of 1.233
at this lower bound to negate the observed effect. Weaker confounding
would not overturn it. We infer \textbf{evidence for causality}.

For `friends give money', the effect estimate on the risk ratio scale is
1.041 {[}0.951, 1.139{]}. The E-value for this estimate is 1.248, with a
lower bound of 1. We infer \textbf{that evidence for causality is not
reliable}.

\newpage{}

\paragraph{Zero vs Status Quo Causal Contrast on Money Received From
Others}\label{zero-vs-status-quo-causal-contrast-on-money-received-from-others}

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-3_3-1.pdf}

}

\caption{\label{fig-3_3}Figure reports results of model estimates for
the causal effects of a universal loss of weekly religious service vs
status quo on financial help received from others during the past week
(yes/no) at the end of study. Outcomes are expressed on the risk ratio
scale.}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_3}Table reports results of model estimates for the
causal effects of a universal loss of weekly religious service vs status
quo on financial help received from others during the past week (yes/no)
at the end of study. Outcomes are expressed on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 0.99 & 0.95 & 1.03 & 1.09 & 1 \\
friends gives money & 0.92 & 0.81 & 1.04 & 1.41 & 1 \\
community gives money & 0.91 & 0.80 & 1.04 & 1.43 & 1 \\

\end{longtable}

For `family gives money', the effect estimate on the risk ratio scale is
0.993 {[}0.953, 1.035{]}. The E-value for this estimate is 1.091, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{that evidence for causality is not
reliable}.

For `friends gives money', the effect estimate on the risk ratio scale
is 0.915 {[}0.809, 1.036{]}. The E-value for this estimate is 1.412,
with a lower bound of 1. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1 to negate the observed effect. Weaker
confounding would not overturn it. We infer \textbf{that evidence for
causality is not reliable}.

For `community gives money', the effect estimate on the risk ratio scale
is 0.911 {[}0.796, 1.042{]}. The E-value for this estimate is 1.425,
with a lower bound of 1. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1 to negate the observed effect. Weaker
confounding would not overturn it. We infer \textbf{that evidence for
causality is not reliable}.

\subsubsection{Causal Inference Results Compared with Cross-Sectional
Regressions}\label{causal-inference-results-compared-with-cross-sectional-regressions}

We performed a cross-sectional analysis in which we estimated the
relationship between religious service attendance and volunteering using
data from the baseline wave. We included all regression covariates from
the causal models (including sample weights), except the baseline
outcome. The coefficient for religious service attendance in this model,
which represents the change in expectation from a one-unit change in the
predictor, is b = 0.31; (95\% CI 0.28, 0.34). To obtain the monthly
rate, we multiplied this estimate by 4.2 to yield 77.95. This amount is
2.58 than we infer from the `regular religious service attendance' vs
`zero religious service attendance' causal contrast. The regression
overstates the relationship between religious service attendance and
volunteering.

We performed a cross-sectional analysis to estimate the relationship
between religious service attendance and charitable donations. We again
included all regression covariates from the causal models (including
sample weights), except the baseline outcome. The coefficient for
religious service attendance in this model, which represents the change
in expectation from a one-unit change in the predictor, is b = 451;
(95\% CI 408, 494). To obtain the monthly rate, we multiplied this
estimate by 4.2 to yield 1894.45. This amount is 2.89 than we infer from
the `regular religious service attendance' vs `zero religious service
attendance' causal contrast. Again the regression overstates the
relationship between religious service attendance and charitable
donations.

We replicated this approach for Studies 2 and 3, focussing on the
community help received estimates. To avoid the non-collapsibility of
the odds ratio, we estimated outcomes assuming a Poisson distribution,
which, if exponentiated, approximates the risk ratio.

Focussing on community time received, the change in expectation from a
one-unit change in the religious service (exponentiated is), is b =
1.17; (95\% CI 1.14, 1.19). To obtain the monthly rate, we multiplied
this estimate by 4.2 to yield a 1.921 coefficient. This amount is 1.39
than we infer from the `regular religious service attendance' vs `zero
religious service attendance' causal contrast. The regression again
overestimates the relationship between religious service attendance and
charitable donations.

Turning to community money received, the change in expectation from a
one-unit change in the religious service (exponentiated is), is b =
1.18; (95\% CI 1.08, 1.27). To obtain the monthly rate, we multiplied
this estimate by 4.2 to yield a 1.996 coefficient. This amount is 1.45
than we infer from the `regular religious service attendance' vs `zero
religious service attendance' causal contrast. The regression again
overestimates the relationship between religious service attendance and
charitable donations.

Collectively, these results reveal that cross-sectional regressions are
unreliable for estimating causal effects, in this case overstating the
causal effect we infer when combining time-series data with robust
methods.

\paragraph{What is the Economic Value of Religious Service
Attendance?}\label{what-is-the-economic-value-of-religious-service-attendance}

We may use our results to compute the approximate economic value of
religious service attendance by comparing the sums of expected donations
across New Zealand's adult population under the all-gain, all-loss, and
status quo.

We find that an increase in religious service attendance is expected to
result in an individual average donation rate of 1638.9838797,
Conversely, a decrease in religious service attendance is expected to an
average charitable donation rate of 984.5883322. The status quo is
expected to yield an average donation rate of 1037.1444977. The number
of adult residents living in New Zealand in 2021 was
\ensuremath{3.989\times 10^{6}},\footnote{\url{https://www.stats.govt.nz/information-releases/national-population-estimates-at-30-june-2021}}
Multiplying this number by the estimated rates suggests the net gain to
charity of country-wide religious service attendance compared with the
status quo is \ensuremath{2.4007373\times 10^{9}}. By contrast, the net
cost of a country-wide loss of regular religious service attendance on
charitable donations is: \ensuremath{-2.0964654\times 10^{8}}.

Putting these figures in context, the government of New Zealand's annual
budget in 2021 was \ensuremath{5.7976\times 10^{10}}.\footnote{\url{https://www.treasury.govt.nz/publications/budgets/budget-2021}}.
The expected gain from the country-wide adoption of religious service is
0.0414092 of New Zealand's annual government budget in 2021 The expected
loss from the country-wide loss of all religious services amounts to
0.0036161 of New Zealand's annual government budget in 2021.

We infer that the declining religious service in New Zealand affects
charitable giving, however, these costs sum to about 0.09 the
opportunity cost of a hypothetical New Zealand in which the population
attended religious service regularly.

\subsection{Discussion}\label{discussion}

\subsubsection{Summary of findings}\label{summary-of-findings}

First, as expected, we observed that in theoretically relevant contrast,
`regular' vs' zero' religious service attendance had stronger effects
than the policy-motivated contrast `regular' vs `status quo'.

Second, `loss' of religion does not reliably affect cooperation, except
in volunteering. This finding adds to Van Tongeren \emph{et al.}
(\citeproc{ref-vantongeren2020}{2020})'s work, showing that the losses
and gains of religious beliefs, behaviours, and affiliations must be
distinguished.

Third, we find that cross-sectional regressions overstate
effects\ldots{}

Fourth, we find corroborating evidence for the effects of religious
service attendance on charitable donations, measured by self-report data
and help-received responses. Presumably, much of this giving is to
religious institutions. Additional support for charitable giving comes
from public records, which in New Zealand must be reported because
religious institutions are charities that must report their earnings and
expenses {[}\ldots{]}. Whatever one may think of churches, New Zealand's
evidence suggests they are efficient charities.

Fourth, we find signals for family-effects in both money and time, an
effect that survives controlling for baseline family size (number of
siblings, number of children). Shaver \emph{et al.}
(\citeproc{ref-shaver2020church}{2020}) argues that a fundamental
evolutionary function of religion is to support cooperative
alloparenting. Future studies may investigate these effects.

Fifth, we find that the gain of religion has a considerable ``cash
value'' \ldots{}

\subsubsection{Limitations}\label{limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Confounding}: we employ rigorous causal inference techniques,
  which are contingent on the adequacy of our identification strategy,
  measures, and model-specification. Non-parametric causal estimation
  offers considerable advantages for modelling efficiency. Although our
  sensitivity analyses allow us to describe the amount of unmeasured
  confounding needed to explain our results, it is unclear whether such
  confounders are present and, if so, how strongly they may be related
  to the treatments and outcomes.
\item
  \textbf{Measurement error}: Direct and/or correlated measurement
  errors may lead to bias by implying true effects in their absence.
  Additionally, uncorrelated measurement errors may lead to bias by
  attenuating true results in their presence. To some extent, our method
  for evaluating causation across multiple measures of ``prosociality''
  addresses these threats. However, variability in results may arise
  from presently unknown combinations of measurement error\ldots. (say
  more)
\item
  \textbf{Model mis-specification}: possible, but better than
  regressions\ldots{}
\item
  \textbf{Treatment effect heterogeneity}: Future work must investigate
  for whom effects are most evident -- help to assess policy-relevant
  decisions.
\item
  \textbf{Potential Social Harms/Benefits not evaluated}\ldots{}
\item
  \textbf{Generalisability and transportability of findings outside of
  New Zealand}: our findings should be interpreted within the context of
  the New Zealand population from which the data were sourced and
  weighted. Although these results may have broader relevance to similar
  populations, we advise against direct extrapolation to different
  populations or sociocultural settings. Speculating\ldots{} reasonable
  to infer similar effects in countries that resemble New
  Zealand\ldots{} Future work\ldots{}
\end{enumerate}

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study (NZAVS). Full copies of the NZAVS data files are held
by members of the NZAVS management team and research group. A
de-identified dataset containing only the variables analysed in this
manuscript is available upon request from the corresponding author, or
any member of the NZAVS advisory board for the purposes of replication
or checking of any published study using NZAVS data. The code for the
analysis can be found at:
\url{https://github.com/go-bayes/models/blob/main/scripts/24-bulbulia-church-prosocial.R}.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Planck Institute for the Science of Human History. The
funders had no role in preparing the manuscript or the decision to
publish.

\subsubsection{Author Statement}\label{author-statement}

JB conceived of the study and analytic approach. CS led NZAVS data
collection. All authors contributed to the manuscript.

\newpage{}

\subsection{Appendix A: Measures}\label{appendix-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth'').

\paragraph{Charitable Donations (Study 1
outcome)}\label{charitable-donations-study-1-outcome}

Using one item from Hoverd and Sibley
(\citeproc{ref-hoverd_religious_2010}{2010}), we asked participants
``How much money have you donated to charity in the last year?''.

\paragraph{Charitable Volunteering (Study 1
outcome)}\label{charitable-volunteering-study-1-outcome}

We measured hours of volunteering using one item from Sibley \emph{et
al.} (\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
voluntary/charitable work.''

\paragraph{Community: Sense of Community (Study 2
outcome)}\label{community-sense-of-community-study-2-outcome}

We measured a sense of community with a single item from Sengupta
\emph{et al.} (\citeproc{ref-sengupta2013}{2013}): ``I feel a sense of
community with others in my local neighbourhood.'' Participants answered
on a scale of 1 (strongly disagree) to 7 (strongly agree).

\paragraph{Community: Felt Belongingness (Study 2
outcome)}\label{community-felt-belongingness-study-2-outcome}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (\citeproc{ref-hagerty1995}{Hagerty and Patusky
1995}): (1) ``Know that people in my life accept and value me''; (2)
``Feel like an outsider''; (3) ``Know that people around me share my
attitudes and beliefs''. Participants responded on a scale from 1 (Very
Inaccurate) to 7 (Very Accurate). The second item was reversely coded.

\paragraph{Community: Social Support (Study 2
outcome)}\label{community-social-support-study-2-outcome}

Participants' perceived social support was measured using three items
from Cutrona and Russell (\citeproc{ref-cutrona1987}{1987}) and Williams
\emph{et al.} (\citeproc{ref-williams_cyberostracism_2000}{2000}): (1)
``There are people I can depend on to help me if I really need it''; (2)
``There is no one I can turn to for guidance in times of stress''; (3)
``I know there are people I can turn to when I need help.'' Participants
indicated the extent to which they agreed with those items (1 = Strongly
Disagree to 7 = Strongly Agree). The second item was negatively worded,
so we reversely recorded the responses to this item.

\paragraph{Disability}\label{disability}

We assessed disability with a one item indicator adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}), that asks ``Do you have a health
condition or disability that limits you, and that has lasted for 6+
months?'' (1 = Yes, 0 = No).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

We asked participants, ``What is your highest level of qualification?''.
We coded participants' highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school quals coded as Level 3, and all other ancillary
categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants, ``Are you currently employed? (This includes
self-employed or casual work)''. * note: This question disappeared in
the updated NZAVS Technical documents (Data Dictionary).

\paragraph{Ethnicity}\label{ethnicity}

Based on the New Zealand Census, we asked participants, ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Fatigue}\label{fatigue}

We assessed subjective fatigue by asking participants, ``During the last
30 days, how often did \ldots{} you feel exhausted?'' Responses were
collected on an ordinal scale (0 = None of The Time, 1 = A little of The
Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).

\paragraph{Gender (waves: 1-15)}\label{gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\paragraph{Has Siblings}\label{has-siblings}

``Do you have siblings?'' (\citeproc{ref-stronge2019onlychild}{Stronge
\emph{et al.} 2019})

\paragraph{Hours of Childcare}\label{hours-of-childcare}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Childcare}\label{hours-of-childcare-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Sleep}\label{hours-of-sleep}

Participants were asked ``During the past month, on average, how many
hours of \emph{actual sleep} did you get per night''.

\paragraph{Socialising (time 10, time
11)}\label{socialising-time-10-time-11}

As part of the time usage measures, participants were asked to state how
many hour the spent in activities related to socialising with the
following groups:

\begin{itemize}
\tightlist
\item
  Hours spent \ldots{} socialising with family
\item
  Hours spent \ldots{} socialising with friends
\item
  Hours spent \ldots{} socialising with community groups
\end{itemize}

\paragraph{Hours of Work}\label{hours-of-work}

We measured hours of work using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}):``Hours spent \ldots{} working in paid
employment.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked ``Please estimate your total household income
(before tax) for the year XXXX''. To stabilise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Living in an Urban Area (waves:
1-15)}\label{living-in-an-urban-area-waves-1-15}

We coded whether they were living in an urban or rural area (1 = Urban,
0 = Rural) based on the addresses provided.

We coded whether they were living in an urban or rural area (1 = Urban,
0 = Rural) based on the addresses provided.

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants' personalities with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}), which consists of six dimensions and each
dimension is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I often forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{Opt-in}\label{opt-in}

The New Zealand Attitudes and Values Study allows opt-ins to the study.
Because the opt-in population may differ from those sampled randomly
from the New Zealand electoral roll; although the opt-in rate is low, we
include an indicator (yes/no) for this variable.

\paragraph{NZSEI Occupational Prestige and Status (waves:
8-15)}\label{nzsei-occupational-prestige-and-status-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017a}{Fahy
\emph{et al.} 2017a}). This index uses the income, age, and education of
a reference group, in this case the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017b}). This index uses the income, age, and education of
a reference group, in this case, the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

\paragraph{Number of Children (waves: 1-3,
4-15)}\label{number-of-children-waves-1-3-4-15}

We measured the number of children using one item from Bulbulia
(\citeproc{ref-Bulbulia_2015}{2015}). We asked participants, ``How many
children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, or adopted?'' or ````How
many children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, and/or parented?'' (waves:
12-15).

\paragraph{Partner: Has}\label{partner-has}

``What is your relationship status?'' (e.g., single, married, de-facto,
civil union, widowed, living together, etc.)

\paragraph{Politically Conservative}\label{politically-conservative}

We measured participants' political conservative orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{Politically Right Wing}\label{politically-right-wing}

We measured participants' political right-wing orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically left-wing versus right-wing you see
yourself as being..''

(1 = Extremely left-wing to 7 = Extremely right-wing)

\paragraph{Short-Form Health}\label{short-form-health}

Participants' subjective health was measured using one item (``Do you
have a health condition or disability that limits you, and that has
lasted for 6+ months?''; 1 = Yes, 0 = No) adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}).

\paragraph{Support received: money (waves 10-12) (Study 4
outcomes)}\label{support-received-money-waves-10-12-study-4-outcomes}

The NZAVS has a `revealed' measure of received help and support measured
in hours of support in the previous week. The items are:

\emph{Please estimate how much help you have received from the following
sources in the last week?}

\begin{itemize}
\tightlist
\item
  \emph{family\ldots MONEY (hours)}
\item
  \emph{friends\ldots MONEY (hours)}
\item
  \emph{members of my community\ldots MONEY (hours)}
\end{itemize}

Because this measure is highly variable, we convert responses to binary
indicators: \emph{0 = none/ 1=any}

\paragraph{Support received: time (waves 10-13) (Study 3
outcomes)}\label{support-received-time-waves-10-13-study-3-outcomes}

\emph{Please estimate how much help you have received from the following
sources in the last week?}

\begin{itemize}
\tightlist
\item
  \emph{family\ldots TIME (hours)}
\item
  \emph{friends\ldots TIME (hours)}
\item
  \emph{members of my community\ldots TIME (hours)}
\end{itemize}

Because this measure is highly variable, we convert responses to binary
indicators: \emph{0 = none/ 1=any}

\paragraph{Total Siblings}\label{total-siblings}

Participants were asked the following questions related to sibling
counts:

\begin{itemize}
\tightlist
\item
  Were you the 1st born, 2nd born, or 3rd born, etc, child of your
  mother?
\item
  Do you have siblings?
\item
  How many older sisters do you have?
\item
  How many younger sisters do you have?
\item
  How many older brothers do you have?
\item
  How many younger brothers do you have?
\end{itemize}

A single score was obtained from sibling counts by summing responses to
the ``How many\ldots{}'' items. From these scores an ordered factor was
created ranging from 0 to 7, where participants with more than 7
siblings were grouped into the highest category.

\newpage{}

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{table}

\caption{\label{tbl-B}}

\centering{

\captionsetup{labelsep=none}

}

\end{table}%

\begin{longtable}[]{@{}ll@{}}
\caption{Baseline demographic
statistics}\label{tbl-table-demography}\tabularnewline
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,948} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,948} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 49 (14) \\
Range & 18, 99 \\
IQR & 39, 60 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.35 (0.99) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.00 \\
Unknown & 452 \\
\textbf{Alert Level Combined Lead} & NA \\
no\_alert & 24,789 (71\%) \\
early\_covid & 3,902 (11\%) \\
alert\_level\_1 & 3,010 (8.7\%) \\
alert\_level\_2 & 865 (2.5\%) \\
alert\_level\_2\_5\_3 & 569 (1.6\%) \\
alert\_level\_4 & 1,648 (4.7\%) \\
Unknown & 13,165 \\
\textbf{Born Nz} & 37,082 (78\%) \\
Unknown & 585 \\
\textbf{Children Num} & NA \\
Mean (SD) & 1.74 (1.46) \\
Range & 0.00, 14.00 \\
IQR & 0.00, 3.00 \\
Unknown & 393 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.11 (1.06) \\
Range & 1.00, 7.00 \\
IQR & 4.50, 6.00 \\
Unknown & 443 \\
\textbf{Education Level Coarsen} & NA \\
no\_qualification & 1,239 (2.7\%) \\
cert\_1\_to\_4 & 16,700 (36\%) \\
cert\_5\_to\_6 & 5,969 (13\%) \\
university & 12,595 (27\%) \\
post\_grad & 5,118 (11\%) \\
masters & 3,924 (8.4\%) \\
doctorate & 1,125 (2.4\%) \\
Unknown & 1,278 \\
\textbf{Employed} & 38,024 (79\%) \\
Unknown & 107 \\
\textbf{Eth Cat} & NA \\
euro & 38,158 (81\%) \\
maori & 5,457 (12\%) \\
pacific & 1,137 (2.4\%) \\
asian & 2,543 (5.4\%) \\
Unknown & 653 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.91 (1.20) \\
Range & 1.00, 7.00 \\
IQR & 3.00, 4.75 \\
Unknown & 443 \\
\textbf{Hlth Disability} & 10,540 (22\%) \\
Unknown & 926 \\
\textbf{Hlth Fatigue} & NA \\
0 & 7,326 (15\%) \\
1 & 15,242 (32\%) \\
2 & 14,803 (31\%) \\
3 & 7,448 (16\%) \\
4 & 2,572 (5.4\%) \\
Unknown & 557 \\
\textbf{Hlth Sleep Hours} & NA \\
Mean (SD) & 6.94 (1.13) \\
Range & 2.50, 16.00 \\
IQR & 6.00, 8.00 \\
Unknown & 2,482 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.41 (1.19) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.25 \\
Unknown & 448 \\
\textbf{Hours Children log} & NA \\
Mean (SD) & 1.17 (1.61) \\
Range & 0.00, 5.13 \\
IQR & 0.00, 2.40 \\
Unknown & 1,538 \\
\textbf{Hours Community log} & NA \\
Mean (SD) & 0.34 (0.65) \\
Range & 0.00, 4.80 \\
IQR & 0.00, 0.69 \\
Unknown & 1,538 \\
\textbf{Hours Exercise log} & NA \\
Mean (SD) & 1.54 (0.85) \\
Range & 0.00, 4.39 \\
IQR & 1.10, 2.08 \\
Unknown & 1,538 \\
\textbf{Hours Family log} & NA \\
Mean (SD) & 1.61 (1.04) \\
Range & 0.00, 5.13 \\
IQR & 1.10, 2.40 \\
Unknown & 1,538 \\
\textbf{Hours Friends log} & NA \\
Mean (SD) & 1.45 (0.87) \\
Range & 0.00, 5.02 \\
IQR & 1.10, 1.95 \\
Unknown & 1,538 \\
\textbf{Hours Housework log} & NA \\
Mean (SD) & 2.14 (0.78) \\
Range & 0.00, 5.13 \\
IQR & 1.61, 2.71 \\
Unknown & 1,538 \\
\textbf{Hours Religious Community log} & NA \\
Mean (SD) & 0.17 (0.49) \\
Range & 0.00, 5.04 \\
IQR & 0.00, 0.00 \\
Unknown & 1,538 \\
\textbf{Hours Work log} & NA \\
Mean (SD) & 2.66 (1.58) \\
Range & 0.00, 4.62 \\
IQR & 1.39, 3.71 \\
Unknown & 1,538 \\
\textbf{Household Inc log} & NA \\
Mean (SD) & 11.39 (0.77) \\
Range & 0.69, 14.92 \\
IQR & 11.00, 11.92 \\
Unknown & 3,726 \\
\textbf{Kessler6 Sum} & NA \\
Mean (SD) & 5 (4) \\
Range & 0, 24 \\
IQR & 2, 8 \\
Unknown & 489 \\
\textbf{Male} & 17,779 (37\%) \\
\textbf{Modesty} & NA \\
Mean (SD) & 5.98 (0.95) \\
Range & 1.00, 7.00 \\
IQR & 5.50, 6.75 \\
Unknown & 34 \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.49 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 2.75, 4.25 \\
Unknown & 454 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.77 (2.73) \\
Range & 1.00, 10.00 \\
IQR & 2.00, 7.00 \\
Unknown & 310 \\
\textbf{Nzsei 13 l} & NA \\
Mean (SD) & 54 (17) \\
Range & 10, 90 \\
IQR & 41, 69 \\
Unknown & 676 \\
\textbf{Openness} & NA \\
Mean (SD) & 4.96 (1.12) \\
Range & 1.00, 7.00 \\
IQR & 4.25, 5.75 \\
Unknown & 445 \\
\textbf{Partner} & 34,818 (75\%) \\
Unknown & 1,539 \\
\textbf{Political Conservative} & NA \\
1 & 2,515 (5.6\%) \\
2 & 8,676 (19\%) \\
3 & 8,820 (20\%) \\
4 & 13,913 (31\%) \\
5 & 6,694 (15\%) \\
6 & 3,299 (7.4\%) \\
7 & 741 (1.7\%) \\
Unknown & 3,290 \\
\textbf{Religion Church Round} & NA \\
0 & 38,479 (83\%) \\
1 & 1,517 (3.3\%) \\
2 & 1,125 (2.4\%) \\
3 & 907 (2.0\%) \\
4 & 2,478 (5.3\%) \\
5 & 475 (1.0\%) \\
6 & 326 (0.7\%) \\
7 & 106 (0.2\%) \\
8 & 964 (2.1\%) \\
Unknown & 1,571 \\
\textbf{Rural Gch 2018 l} & NA \\
1 & 29,479 (62\%) \\
2 & 9,014 (19\%) \\
3 & 5,865 (12\%) \\
4 & 2,694 (5.7\%) \\
5 & 588 (1.2\%) \\
Unknown & 308 \\
\textbf{Sample Frame Opt in} & 1,384 (2.9\%) \\
\textbf{Sample Origin} & NA \\
1-2 & 2,970 (6.2\%) \\
3-3.5 & 2,052 (4.3\%) \\
4 & 2,700 (5.6\%) \\
5-6-7 & 4,506 (9.4\%) \\
8-9 & 5,802 (12\%) \\
10 & 29,918 (62\%) \\
\textbf{Short Form Health} & NA \\
Mean (SD) & 5.04 (1.17) \\
Range & 1.00, 7.00 \\
IQR & 4.33, 6.00 \\
Unknown & 9 \\
\textbf{Total Siblings} & NA \\
Mean (SD) & 2.55 (1.87) \\
Range & 0.00, 23.00 \\
IQR & 1.00, 3.00 \\
Unknown & 1,205 \\
\textbf{Urban} & 38,493 (81\%) \\
Unknown & 308 \\
\end{longtable}

Table~\ref{tbl-table-demography} presents baseline demographic
statistics for couples who met inclusion criteria.

\newpage{}

\subsection{Appendix C: Treatment Statistics}\label{appendix-exposures}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4247}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}@{}}
\caption{Baseline and treatment wave descriptive
statistics}\label{tbl-table-exposures}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Religion Church Round} & NA & NA \\
0 & 38,479 (83\%) & 28,671 (84\%) \\
1 & 1,517 (3.3\%) & 916 (2.7\%) \\
2 & 1,125 (2.4\%) & 751 (2.2\%) \\
3 & 907 (2.0\%) & 651 (1.9\%) \\
4 & 2,478 (5.3\%) & 1,700 (5.0\%) \\
5 & 475 (1.0\%) & 312 (0.9\%) \\
6 & 326 (0.7\%) & 209 (0.6\%) \\
7 & 106 (0.2\%) & 71 (0.2\%) \\
8 & 964 (2.1\%) & 655 (1.9\%) \\
Unknown & 1,571 & 14,012 \\
\textbf{Alert Level Combined} & NA & NA \\
no\_alert & 47,948 (100\%) & 24,789 (71\%) \\
early\_covid & 0 (0\%) & 3,902 (11\%) \\
alert\_level\_1 & 0 (0\%) & 3,010 (8.7\%) \\
alert\_level\_2 & 0 (0\%) & 865 (2.5\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 569 (1.6\%) \\
alert\_level\_4 & 0 (0\%) & 1,648 (4.7\%) \\
Unknown & 0 & 13,165 \\
\end{longtable}

Table~\ref{tbl-table-exposures} presents baseline (NZAVS time 10) and
exposure wave (NZAVS time 11) statistics for the exposure variable:
religious service attendance (range 0-8). Responses coded as eight or
above were coded as ``8''. This decision to avoid spare treatments was
based on theoretical grounds, namely, that daily exposure would be
similar in its effects to more than daily exposure. We note that causal
contrasts were obtained for projects at either no attendance or
four-or-more visits per month. Hence this simplification of the measure
is unlikely to affect theoretical and practical inferences. Because the
treatment wave (NZAVS time 11) occurred in New Zealand's COVID-19
pandemic, all models adjusted for the pandemic alert-level. The pandemic
is not a ``confounder'' because a confounder must be related to the
treatment and the outcome. At the end of the study, all participants had
been exposed to the pandemic. However, to satisfy the causal consistency
assumption, all treatments must be conditionally equivalent within
levels of all covariates (\citeproc{ref-vanderweele2013}{VanderWeele and
Hernan 2013}). Because COVID affected the ability or willingness of
individuals to attend religious service, we included the lockdown
condition as a covariate (\citeproc{ref-sibley2012a}{Sibley and Bulbulia
2012}). To better enable conditional independence within levels of the
treatment variable, we conditioned on the lead value of COVID-alert
level at baseline. To mitigate systematic biases arising from attrition,
and missingness, the \texttt{lmtp} package uses inverse probability of
censoring weights, which were used when estimating the causal effects of
the exposure on the outcome.

\subsubsection{Binary Transition Table for The
Treatment}\label{binary-transition-table-for-the-treatment}

The table presents a transition matrix to evaluate treatment shifts
between baseline and treatment wave. Here we focus on the shift from/to
monthly attendance at four or more visits per month. Entries along the
diagonal (in bold) indicate the number of individuals who
\textbf{stayed} in their initial state. By contrast, the off-diagonal
shows the transitions from the initial state (bold) to another state in
the following wave (off diagonal). Thus the cell located at the
intersection of row \(i\) and column \(j\), where \(i \neq j\), gives us
the counts of individuals moving from state \(i\) to state \(j\).

\begin{longtable}[]{@{}ccc@{}}
\toprule\noalign{}
From & \textless{} weekly & \textgreater= weekly \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textless{} weekly & \textbf{29496} & 669 \\
\textgreater= weekly & 804 & \textbf{2229} \\
\end{longtable}

\subsubsection{Imbalance of Confounding Covariates
Treatments}\label{imbalance-of-confounding-covariates-treatments}

Figure~\ref{fig-match_1} shows imbalance of covariates on the treatment
at the treatment wave

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-match_1-1.pdf}

}

\caption{\label{fig-match_1}Figure imbalance of covariates at the first
exposure (baseline) wave}

\end{figure}%

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4474}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2763}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2763}}@{}}
\caption{Outcomes measured at baseline and
end-of-study}\label{tbl-table-outcomes}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,948
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 47,948
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Annual Charity} & 120 (25, 500) & 200 (20, 520) \\
Unknown & 3,181 & 16,514 \\
\textbf{Community Gives Money Binary} & 205 (0.4\%) & 144 (0.5\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Community Gives Time Binary} & 2,389 (5.2\%) & 1,934 (6.2\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Family Gives Money Binary} & 2,802 (6.1\%) & 1,477 (4.7\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Family Gives Time Binary} & 13,590 (30\%) & 8,867 (29\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Friends Give Money Binary} & 589 (1.3\%) & 321 (1.0\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Friends Give Time Binary} & 8,201 (18\%) & 5,664 (18\%) \\
Unknown & 2,074 & 16,836 \\
\textbf{Sense Neighbourhood Community} & NA & NA \\
1 & 3,025 (6.3\%) & 1,383 (4.3\%) \\
2 & 5,953 (12\%) & 3,252 (10\%) \\
3 & 7,033 (15\%) & 4,283 (13\%) \\
4 & 9,911 (21\%) & 6,961 (22\%) \\
5 & 9,924 (21\%) & 7,625 (24\%) \\
6 & 8,055 (17\%) & 5,921 (19\%) \\
7 & 3,781 (7.9\%) & 2,503 (7.8\%) \\
Unknown & 266 & 16,020 \\
\textbf{Social Belonging} & 5.33 (4.33, 6.00) & 5.00 (4.33, 6.00) \\
Unknown & 450 & 16,114 \\
\textbf{Social Support} & 6.33 (5.33, 7.00) & 6.33 (5.33, 7.00) \\
Unknown & 38 & 15,919 \\
\textbf{Volunteering Hours} & 0.00 (0.00, 1.00) & 0.00 (0.00, 1.00) \\
Unknown & 1,538 & 16,738 \\
\textbf{Volunteers Binary} & 12,905 (28\%) & 8,004 (26\%) \\
Unknown & 1,538 & 16,738 \\
\end{longtable}

Table~\ref{tbl-table-outcomes} presents baseline and end-of-study
descriptive statistics for the outcome variables.

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, J (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-bulbulia2022}
Bulbulia, JA (2022) A workflow for causal inference in cross-cultural
psychology. \emph{Religion, Brain \& Behavior}, \textbf{0}(0), 1--16.
doi:\href{https://doi.org/10.1080/2153599X.2022.2070245}{10.1080/2153599X.2022.2070245}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-bulbulia2023a}
Bulbulia, JA, Afzali, MU, Yogeeswaran, K, and Sibley, CG (2023)
Long-term causal effects of far-right terrorism in {N}ew {Z}ealand.
\emph{PNAS Nexus}, \textbf{2}(8), pgad242.

\bibitem[\citeproctext]{ref-bulbuliaj.2013}
Bulbulia, J., Geertz, AW, Atkinson, QD, \ldots{} Wilson, DS (2013) The
cultural evolution of religion. In P. J. Richerson and M. Christiansen,
eds., Cambridge, MA: MIT press, 381404.

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, S, J. A. (2015) Religion and parental cooperation: An
empirical test of slone's sexual signaling model. In \&. V. S. J. Slone
D., ed., \emph{The attraction of religion: A sexual selectionist
account}, Bloomsbury Press, 29--62.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.
doi:\href{https://doi.org/10.1207/s15327752jpa8301_04}{10.1207/s15327752jpa8301\_04}.

\bibitem[\citeproctext]{ref-chen2020religious}
Chen, Y, Kim, ES, and VanderWeele, TJ (2020) Religious-service
attendance and subsequent health and well-being throughout adulthood:
Evidence from three prospective cohorts. \emph{International Journal of
Epidemiology}, \textbf{49}(6), 2030--2040.

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017b) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fahy2017a}
Fahy, KM, Lee, A, and Milne, BJ (2017a) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a new zealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-haneuse2013estimation}
Haneuse, S, and Rotnitzky, A (2013) Estimation of the effect of
interventions that modify the received treatment. \emph{Statistics in
Medicine}, \textbf{32}(30), 5260--5277.

\bibitem[\citeproctext]{ref-hernan2024WHATIF}
Hernan, MA, and Robins, JM (2024) \emph{Causal inference: What if?},
Taylor \& Francis. Retrieved from
\url{https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/}

\bibitem[\citeproctext]{ref-hernan2024stating}
Hernán, MA, and Greenland, S (2024) Why stating hypotheses in grant
applications is unnecessary. \emph{JAMA}, \textbf{331}(4), 285--286.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-hoverd_religious_2010}
Hoverd, WJ, and Sibley, CG (2010) Religious and denominational diversity
in new zealand 2009. \emph{New Zealand Sociology}, \textbf{25}(2),
59--87.

\bibitem[\citeproctext]{ref-diaz2023lmtp}
Iván Díaz, KLH, Nicholas Williams, and Schenck, EJ (2023) Nonparametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association},
\textbf{118}(542), 846--857.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-johnson2005}
Johnson, DD (2005) God{'}s punishment and public goods: A test of the
supernatural punishment hypothesis in 186 world cultures. \emph{Human
Nature}, \textbf{16}, 410446.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-kelly2024religiosity}
Kelly, JM, Kramer, SR, and Shariff, AF (2024) Religiosity predicts
prosociality, especially when measured by self-report: A meta-analysis
of almost 60 years of research. \emph{Psychological Bulletin}.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-neyman1923}
Neyman, JS (1923) On the application of probability theory to
agricultural experiments. Essay on principles. Section 9.(tlanslated and
edited by dm dabrowska and tp speed, statistical science (1990), 5,
465-480). \emph{Annals of Agricultural Sciences}, \textbf{10}, 151.

\bibitem[\citeproctext]{ref-norenzayan2016}
Norenzayan, A, Shariff, AF, Gervais, WM, \ldots{} Henrich, J (2016) The
cultural evolution of prosocial religions. \emph{Behavioral and Brain
Sciences}, \textbf{39}, e1.
doi:\href{https://doi.org/10.1017/S0140525X14001356}{10.1017/S0140525X14001356}.

\bibitem[\citeproctext]{ref-ogburn2021}
Ogburn, EL, and Shpitser, I (2021) Causal modelling: The two cultures.
\emph{Observational Studies}, \textbf{7}(1), 179--183.
doi:\href{https://doi.org/10.1353/obs.2021.0006}{10.1353/obs.2021.0006}.

\bibitem[\citeproctext]{ref-rubin2005}
Rubin, DB (2005) Causal inference using potential outcomes: Design,
modeling, decisions. \emph{Journal of the American Statistical
Association}, \textbf{100}(469), 322--331. Retrieved from
\url{https://www.jstor.org/stable/27590541}

\bibitem[\citeproctext]{ref-sengupta2013}
Sengupta, NK, Luyten, N, Greaves, LM, \ldots{} Sibley, CG (2013) Sense
of Community in New Zealand Neighbourhoods: A Multi-Level Model
Predicting Social Capital. \emph{New Zealand Journal of Psychology},
\textbf{42}(1), 36--45.

\bibitem[\citeproctext]{ref-shaver2020church}
Shaver, JH, Power, EA, Purzycki, BG, \ldots{} Bulbulia, JA (2020) Church
attendance and alloparenting: An analysis of fertility, social support
and child development among english mothers. \emph{Philosophical
Transactions of the Royal Society B}, \textbf{375}(1805), 20190428.

\bibitem[\citeproctext]{ref-sibley2012a}
Sibley, CG, and Bulbulia, J (2012) Faith after an earthquake: A
longitudinal study of religion and perceived health before and after the
2011 christchurch new zealand earthquake. \emph{PloS One},
\textbf{7}(12), e49648.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in New Zealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-sosis2003cooperation}
Sosis, R, and Bressler, ER (2003) Cooperation and commune longevity: A
test of the costly signaling theory of religion. \emph{Cross-Cultural
Research}, \textbf{37}(2), 211--239.

\bibitem[\citeproctext]{ref-stronge2019onlychild}
Stronge, S, Shaver, JH, Bulbulia, J, and Sibley, CG (2019) Only children
in the 21st century: Personality differences between adults with and
without siblings are very, very small. \emph{Journal of Research in
Personality}, \textbf{83}, 103868.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vantongeren2020}
Van Tongeren, DR, DeWall, CN, Chen, Z, Sibley, CG, and Bulbulia, J
(2020) Religious residue: Cross-cultural evidence that religious
psychology and behavior persist following deidentification.
\emph{Journal of Personality and Social Psychology}.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the e-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 120.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-watts2016}
Watts, J, Bulbulia, J. A., Gray, RD, and Atkinson, QD (2016) Clarity and
causality needed in claims about big gods., \textbf{39}, 4142.
doi:\href{https://doi.org/d4qp}{d4qp}.

\bibitem[\citeproctext]{ref-watts2015}
Watts, J, and Gray, R (2015) \emph{Broad supernatural punishment but not
moralising high gods precede the evolution of political complexity in
austronesia}, Victoria University Empirical Philosophy Workshop.
Wellington, New Zealand.

\bibitem[\citeproctext]{ref-williams_cyberostracism_2000}
Williams, KD, Cheung, CKT, and Choi, W (2000) Cyberostracism: Effects of
being ignored over the internet. \emph{Journal of Personality and Social
Psychology}, \textbf{79}(5), 748--762.
doi:\href{https://doi.org/10.1037/0022-3514.79.5.748}{10.1037/0022-3514.79.5.748}.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{Lmtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\end{CSLReferences}



\end{document}
