% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{tabularray}
\usepackage[normalem]{ulem}
\usepackage{graphicx}
\UseTblrLibrary{booktabs}
\UseTblrLibrary{rotating}
\UseTblrLibrary{siunitx}
\NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
\newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
\newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\let\oldtabular\tabular
\renewcommand{\tabular}{\small\oldtabular}
\setlength{\tabcolsep}{4pt}  % adjust this value as needed
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Declining Trust in Science: Longitudinal Evidence From A National Panel Study in New Zealand Years 2019-2024},
  pdfauthor={John Kerr; Chris G. Sibley; Carla Houkamau; Danny Osborne; Marc Wilson; Kumar Yogeswaaran; Joseph A. Bulbulia},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Declining Trust in Science: Longitudinal Evidence From A National
Panel Study in New Zealand Years 2019-2024}

\usepackage{academicons}
\usepackage{xcolor}

  \author{John Kerr}
            \affil{%
             \small{     University of Otago, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0000-0000-0000 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Chris G. Sibley}
            \affil{%
             \small{     School of Psychology, University of Auckland,
New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-4064-8800 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Carla Houkamau}
            \affil{%
             \small{     University of Auckland, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-3449-3726 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Danny Osborne}
            \affil{%
             \small{     School of Psychology, University of Auckland,
New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-8513-4125 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Marc Wilson}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5861-2056 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Kumar Yogeswaaran}
            \affil{%
             \small{     University of Canterbury New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-1978-5077 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Joseph A. Bulbulia}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5861-2056 }
              }
      


\date{2024-12-09}
\begin{document}
\maketitle
\begin{abstract}
The public's perception of science influences a wide range of
behaviours, from adherence to public health guidance to support for
climate action. This study uses nationally representative panel data
from New Zealand to examine changes in the value placed on science and
trust in scientists between 2019 and 2024 (\emph{N} = 42,681, New
Zealand Attitudes and Values Study). \textbf{Study 1} estimates
longitudinal trajectories for attitudes to science and scientists,
applying multiple imputation to address biases arising from systematic
attrition. \textbf{Study 2} models trust responses categorically,
distinguishing low (1--3), medium (4--5), and high (6--7) trust. Results
indicate that the value placed on science and trust in scientists rose
after New Zealand's response to COVID-19, then subsequently declined.
Categorical analysis suggests that the proportion reporting low value
placed on science remained stable, while the proportion reporting high
value decreased. For trust in scientists, low trust increased, and high
trust declined. Comparing multiply imputed outcomes with observed data
reveals that even a minimum bound of bias leads to misestimations of
approximately 2--3\% of the population for low valuations and low trust,
and 6--8\% for high valuations and high trust. These findings underscore
the importance of exercising caution when interpreting population-based
estimates of trust in science. \textbf{KEYWORDS}: \emph{Institutional
Trust}; \emph{Longitudinal}; \emph{Measurement}; \emph{Missing Data};
\emph{Political}; \emph{Values}.
\end{abstract}


\subsection{Introduction}\label{introduction}

Whether people are becoming more sceptical of science is a matter of
substantial practical interest and concern
(\citeproc{ref-kennedy2022americans}{Kennedy \emph{et al.} 2022};
\citeproc{ref-pagliaro2021trust}{Pagliaro \emph{et al.} 2021};
\citeproc{ref-sturgis2021trust}{Sturgis \emph{et al.} 2021}). Public
trust in science helps shapes behaviour from the uptake of vaccination
and other public health measures
(\citeproc{ref-rueger2021perception}{Rueger \emph{et al.} 2021}) to
support for climate action (\citeproc{ref-bogert2024effect}{Bogert
\emph{et al.} 2024}). Yet, accurately documenting trends in scientific
mistrust is challenging because individuals with lower trust in science
are less likely to participate in scientific studies, biasing results
(\citeproc{ref-kreps2020model}{Kreps and Kriner 2020};
\citeproc{ref-reif2021representative}{Reif and Guenther 2021}).

This study draws on five waves of national panel data collected between
2019 and 2024 from 42,681 participants in the New Zealand Attitudes and
Values Study (NZAVS). Focusing on a 2019 baseline cohort, we estimate
annual response trajectories for attitudes towards science and trust in
scientists. To address attrition and systematic nonresponse, we apply
multiple imputation models. By comparing the results of these adjusted
models with unadjusted models in the restricted sample, we obtain a
minimum bound for bias from differential attrition. This estimate is
useful for gauging bias from cross-sectional data.

In \textbf{Study 1a}, we examine changes in the average value placed on
science each year, comparing observed data with results that adjust for
missingness. \textbf{Study 1b} mirrors this approach for trust in
scientists, treating response as continuous variables. In \textbf{Study
2a}, we classify responses into low (1--3), medium (4--5), or high
(6--7) categories for the value placed on science, and \textbf{Study 2b}
applies the same categorical approach to trust in scientists, again
forcussing on probabilities for classification. These categorical models
enable us to capture patterns not evident from mean scores alone,
revealing potential social divisions in attitudes toward science and
scientists.

This work is descriptive and exploratory. Our primary objective is to
characterise changes in institutional trust over time, focussing on how
the value placed on science and trust in scientists evolve. By comparing
raw estimates with those adjusted for missing data, we clarify how
nonresponse can bias conclusions about trends in public trust.

\subsection{Method}\label{method}

\subsubsection{Target Population}\label{target-population}

The target population for this study comprises the cohort of New Zealand
residents in wave 2019 whose mistrust of science was not so great as to
prevent participation in the New Zealand Attitudes and Values Study
(NZAVS) that year. Our objective is to infer population dynamics for
this cohort by using responses from individuals who took part in the
NZAVS during the 2019 baseline wave, applying weights derived from the
2018 New Zealand Census to account for age, gender, and ethnicity
distributions (\citeproc{ref-sibley2021}{Sibley 2021}).

\subsubsection{Sample}\label{sample}

The NZAVS is a national probability study designed to represent the New
Zealand population accurately. Although it employs prize draws to
incentivise participation, response rates and demographic balances vary.
For example, the NZAVS tends to under-sample males and individuals of
Asian descent and to over-sample females and Māori (the Indigenous
people of New Zealand). To enhance representativeness of the target
population, we apply Census-based survey weights that adjust for age,
gender, and ethnicity (New Zealand European, Asian, Māori, Pacific),
thus improving the alignment of our sample with the national demographic
composition (\citeproc{ref-sibley2021}{Sibley 2021}).

\subsubsection{Eligibility Criteria}\label{eligibility-criteria}

To be eligible for inclusion in this study, participants needed to have
responded to the New Zealand Attitudes and Values Study Time 11, years
2019-2024. Individuals meeting this criterion were then tracked over the
baseline and the subsequent four waves, permitting missing responses in
any wave through Zealand Attitudes and Values Study Time 14, years
2022-2024. A total of 42,681 individuals satisfied these conditions and
were included in the analyses.

\hyperref[appendix-a]{Appendix A} (Table~\ref{tbl-demography}) presents
demographic characteristics of this cohort and details patterns of
missing data. \hyperref[appendix-b]{Appendix B}
(Figure~\ref{fig-timeline}) illustrates the daily data collection
periods for NZAVS waves 11--15 (2019--2024), providing additional
context for the timing of responses and potential nonresponse.

\subsection{Measures}\label{measures}

We estimated target population average responses for two indicators
attitudes to science, one that relates to the social value of science
and another that measures trust in scientists (refer to Schoor and
Schütz (\citeproc{ref-schoor2021science}{2021}) and Gundersen and Holst
(\citeproc{ref-gundersen2022science}{2022}) on the importance of these
distinctions). Item wording is as follows.

\paragraph{Social Value of Science}\label{social-value-of-science}

\emph{Our society places too much emphasis on science (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-hartman2017}{Hartman \emph{et al.} 2017}).

\paragraph{Trust in Scientists}\label{trust-in-scientists}

\emph{I have a high degree of confidence in the scientific community.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-nisbet2015}{Nisbet \emph{et al.} 2015}).

Note again that each item addresses a different attitude to science. It
is plausible that at least some who disagree with society's emphasis on
science are nevertheless trusting of scientific institutions. On the
other hand, and notably, the mistrust of scientists is an institutional
cornerstone of science. It is the solomn duty of every scientists to
doubt.

\subsubsection{Missing Data}\label{missing-data}

We face two primary challenges when estimating population-level trends.

First, although the New Zealand Attitudes and Values Study uses a
national probability sampling strategy, only about 10\% of those invited
participate. It is credible that the proportion of those who do not
value science or who mistrust scientists are under-represented in the
sample. After all, the New Zealand Attitudes and Values Study is run by
scientists aiming to foster scientific understanding. For this reason,
it is challenging to estimate mistrust of science using surveys of the
general population (\citeproc{ref-reif2021representative}{Reif and
Guenther 2021}).

Second, although the NZAVS retains between 70--80\% of its sample each
year, attrition is inevitable. It is credible that the proportion of
those who do not value science or who mistrust scientists becames
increasingly under-represented in the longitudinal sample. For this
reason, it is challenging to estimate mistrust of science in a
longitudinal cohort.

We cannot overcome the first challenge. We lack direct information about
mistrust in the population of non-participants.

However, for those who participated in 2019 but dropped out later, we
can adjust estimates under the assumption that the probability of
attrition or missing response is predictable given observed covariates,
including previous attitudes to science. Methods for multiple imputation
adjust for bias by incorporating missing data uncertainty into estimates
(\citeproc{ref-blackwell_2017_unified}{Blackwell \emph{et al.} 2017};
\citeproc{ref-bulbulia2023a}{Bulbulia \emph{et al.} 2023}).

Here, we used the \texttt{Amelia} package in R
(\citeproc{ref-amelia_2011}{Honaker \emph{et al.} 2011}) to create ten
multiply imputed datasets for the NZAVS 2019 cohort. These cover NZAVS
time 11--15 (waves 2019--2023, years 2019-2024). We treated attitudes to
science and scientists as ordinal responses bounded by 1 and 7 on the
response scale. The Amelia algorithm is designed for within-unit
imputation in repeated-measures time-series data. All covariates in
Table~\ref{tbl-demography} were included. The time variable (year) was
modelled as a cubic spline to capture non-linear trends over four years.
The code for the analysis is deposited here: (\textbf{OSF Link HERE}).

\subsubsection{Statistical Estimator}\label{statistical-estimator}

In Study 1a and Study 1b, we estimated mean responses for value placed
on science and trust in scientists over time using generalised
estimating equations (GEE). We implemented these models with the geepack
package (\citeproc{ref-geepack_2006}{Halekoh \emph{et al.} 2006}). By
specifying participant id as the clustering variable, we adjusted for
repeated observations and obtained robust standard errors
(\citeproc{ref-mcneish_2017unnecessary}{McNeish \emph{et al.} 2017}). We
weighted the data using sample weights derived from the 2018 New Zealand
Census, ensuring that our estimates reflect population-level trends. We
fitted separate models for each of the ten imputed datasets and pooled
the results using Rubin's rule, thereby incorporating uncertainty from
the missing data process into all population estimates. We generated
predicted means and their associated confidence intervals using
\texttt{ggeffects} (\citeproc{ref-ggeffects_2018}{Ludecke 2018}).

In Study 2a and Study 2b, we examined predicted probabilities of
attitudes to science and scientists in three discrete categories: low
(1--3), medium (4--5), and high (6--7). For these analyses, we employed
neural network models using the \texttt{nnet} package
(\citeproc{ref-nnet_2002}{Venables and Ripley 2002}). These models
provided category-specific probability estimates at each time point. We
applied sample weights constructed from the 2018 Census data to ensure
population representativeness, and again used Rubin's rule to combine
inferences across imputed datasets. We incorporated robust standard
errors appropriate for clustered data and produced predictions and
confidence intervals with \texttt{ggeffects}
(\citeproc{ref-ggeffects_2018}{Ludecke 2018}). The final tables and
figures were created using \texttt{tinytable}
(\citeproc{ref-tinytable_2024}{Arel-Bundock 2024}), \texttt{ggplot2}
(\citeproc{ref-ggplot2_2016}{Wickham 2016}), and \texttt{margot}
(\citeproc{ref-margot2024}{Bulbulia 2024}).

\paragraph{Attitudes to Science and Scientists: Sample Means in Retained
Sample}\label{attitudes-to-science-and-scientists-sample-means-in-retained-sample}

Figure~\ref{fig-hist-outcomes} presents histograms of attitudes to
science and scientists over time in the observed sample. As evident in
the graphs, there is increasing average value placed on science over
time in the retained sample, with a large boost evident in wave 2020
(years 2020-2021). This boost coincides with the initially popular New
Zealand COVID-19 pandemic response (\citeproc{ref-sibley2020a}{Sibley
\emph{et al.} 2020}). Similarly, in the retained sample, trust in
scientists grew, coinciding with New Zealand's COVID-19 pandemic
response, and then stabalised, before falling in the most recent wave
(years 2023-2024).

\newpage{}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-hist-outcomes-1.pdf}}

}

\caption{\label{fig-hist-outcomes}Historgram of sample attitudes to
science over time in the retained sample.}

\end{figure}%

Table~\ref{tbl-sample-continuous} present sample average responses and
categorical distributions of value placed on science and trust in
scientists across consecutive waves from 2019 to 2023, along with sample
sizes and missing data counts for the wave 2019 cohort that dropped out
or did not respond.

Although average trust levels generally increased following New
Zealand's initial response to COVID-19, we also note rising missingness
over time. This suggests that straightforward interpretations of sample
averages may be misleading, because, as noted earlier, individuals who
become more sceptical of science may be less likely to remain in the
study.

Table~\ref{tbl-sample-continuous} shows that mean value placed on
science rose from 5.56 in 2019 to 5.86 in 2023, while mean trust in
scientists increased from 5.30 to 5.55 between 2019 and 2020, stabilised
through 2022, and then declined slightly to 5.45 in 2023. These observed
increases, particularly for value placed on science following the New
Zealand COVID-19 response, appear positive. However, missing responses
grew markedly, from 563 in 2019 to 20,600 in 2023 for values of science,
and from 1,257 in 2019 to 21,177 in 2023 for trust in scientists. Yet,
as mentioned, this attrition may reflect systematic non-response related
to mistrust.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1806}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2639}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1389}}@{}}
\caption{Retained sample average response by
wave.}\label{tbl-sample-continuous}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
missing
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
missing
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{42,681} & Trust Scientists & 2019 & 5.3 & 1,257 \\
& Trust Scientists & 2020 & 5.55 & 10,172 \\
& Trust Scientists & 2021 & 5.56 & 15,519 \\
& Trust Scientists & 2022 & 5.55 & 18,949 \\
& Trust Scientists & 2023 & 5.45 & 21,177 \\
\textbf{42,681} & Values Science & 2019 & 5.56 & 563 \\
& Values Science & 2020 & 5.8 & 9,632 \\
& Values Science & 2021 & 5.84 & 15,111 \\
& Values Science & 2022 & 5.84 & 18,222 \\
& Values Science & 2023 & 5.86 & 20,600 \\
\end{longtable}

\newpage{}

\subsubsection{Sample Categorical Distributions Over
Time}\label{sample-categorical-distributions-over-time}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1983}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0690}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1379}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1379}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1379}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1379}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1379}}@{}}
\caption{Retained sample responses by wave by response category
classified as low (1-3), medium (4-5), or high
(6-7).}\label{tbl-sample-cat}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2023
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2023
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Trust Scientists} & low & 4797 (11.6\%) & 2818 (8.7\%) & 2477
(9.1\%) & 1910 (8.0\%) & 2008 (9.3\%) \\
& med & 14161 (34.2\%) & 9385 (28.9\%) & 7448 (27.4\%) & 7107 (29.9\%) &
6958 (32.4\%) \\
& high & 22466 (54.2\%) & 20306 (62.5\%) & 17237 (63.5\%) & 14715
(62.0\%) & 12538 (58.3\%) \\
\textbf{Values Science} & low & 3434 (8.2\%) & 2465 (7.5\%) & 2012
(7.3\%) & 1740 (7.1\%) & 1475 (6.7\%) \\
& med & 13210 (31.4\%) & 7855 (23.8\%) & 6223 (22.6\%) & 5720 (23.4\%) &
5128 (23.2\%) \\
& high & 25474 (60.5\%) & 22729 (68.8\%) & 19335 (70.1\%) & 16999
(69.5\%) & 15478 (70.1\%) \\
\end{longtable}

Table~\ref{tbl-sample-cat} categorises responses into low (1--3), medium
(4--5), and high (6--7) ranges. For value placed on science, the
proportion reporting low trust declined from 8.2\% in 2019 to 6.7\% in
2023, while the proportion reporting high trust rose from 60.5\% to
70.1\% over the same period. \hyperref[appendix-c]{Appendix C}
Figure~\ref{fig-alluv-science-sample} graphically displays these
transitions.

Similar patterns emerged for trust in scientists, with initial declines
in the low category and increases in the high category, followed by some
reversal in later waves. \hyperref[appendix-c]{Appendix C}
Figure~\ref{fig-alluv-scientists-sample} graphically displays these
transitions.

These shifts might convey a narrative of strengthening value of sceince
during early pandemic periods that continued to grow, with no evidence
of increasing mistrust of scientists. Yet the steady increase in missing
responses over time underscores the importance of careful
interpretation. The observed improvements in attidutes towards science
and scientists could be overstated if sceptical individuals
disproportionately discontinued their participation.

In other words, the rising average trust estimates may in part be an
artefact of differential attrition.

\newpage{}

\subsection{Results}\label{results}

\subsubsection{Multiply Imputed Full Cohort Means in Full 2019
Cohort}\label{multiply-imputed-full-cohort-means-in-full-2019-cohort}

Table~\ref{tbl-sample-means-imp} shows the estimated mean responses for
value placed on science and trust in scientists, pooled over multiple
imputations to adjust for systematic missingness. Compared with the
observed sample means, the imputed estimates suggest moderate trends.
For valuing science, the average response is higher in 2020 than in
2019, but then steadily declines from 5.7 in 2021 to 5.66 by 2023. For
trust in scientists, the average increases from 5.29 to 5.47 between
2019 and 2020 but then declines to 5.28 by 2023. These imputed estimates
reveal a less linear increase in trust than the unadjusted data might
suggest, with evidence of gradual erosion in trust in both domains over
the later waves.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3194}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1528}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1111}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1111}}@{}}
\caption{Imputed average responses for the full 2019
cohort}\label{tbl-sample-means-imp}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
lower
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
upper
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
lower
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
upper
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Trust Scientists} & 2019 & 5.29 & 5.27 & 5.3 \\
& 2020 & 5.47 & 5.45 & 5.48 \\
& 2021 & 5.43 & 5.42 & 5.45 \\
& 2022 & 5.4 & 5.38 & 5.41 \\
& 2023 & 5.28 & 5.26 & 5.29 \\
\textbf{Values Science} & 2019 & 5.56 & 5.55 & 5.57 \\
& 2020 & 5.73 & 5.71 & 5.74 \\
& 2021 & 5.7 & 5.68 & 5.71 \\
& 2022 & 5.68 & 5.66 & 5.69 \\
& 2023 & 5.66 & 5.65 & 5.67 \\
\end{longtable}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2439}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0650}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1301}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1301}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1301}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1301}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1301}}@{}}
\caption{Cohort proportions classified as low, medium, or high
(imputed)}\label{tbl-sample-cat-imp}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2023
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2023
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Values Science Factor} & low & 3529 (8.3\%) & 3503 (8.2\%) &
3649 (8.5\%) & 3701 (8.7\%) & 3657 (8.6\%) \\
& med & 13409 (31.4\%) & 11099 (26.0\%) & 11439 (26.8\%) & 11830
(27.7\%) & 12239 (28.7\%) \\
& high & 25743 (60.3\%) & 28079 (65.8\%) & 27593 (64.6\%) & 27150
(63.6\%) & 26785 (62.8\%) \\
\textbf{Trust Scientists Factor} & low & 5063 (11.9\%) & 4295 (10.1\%) &
4710 (11.0\%) & 4694 (11.0\%) & 5466 (12.8\%) \\
& med & 14632 (34.3\%) & 13175 (30.9\%) & 13148 (30.8\%) & 14106
(33.0\%) & 15016 (35.2\%) \\
& high & 22986 (53.9\%) & 25211 (59.1\%) & 24823 (58.2\%) & 23881
(56.0\%) & 22199 (52.0\%) \\
\end{longtable}

Table~\ref{tbl-sample-cat-imp} classifies imputed responses into low,
medium, and high categories. For valuing science, the proportion of
respondents reporting low trust remains relatively stable, hovering
around 8\%-9\% over time. In contrast, the initially large high-trust
category (around 60\%) rises to 65.8\% in 2020, then recedes to 62.8\%
by 2023, suggesting that some of the early gains in trust may have been
short-lived once nonresponse patterns are accounted for. For trust in
scientists, imputation indicates a somewhat different trajectory.
Initially, 11.9\% reported low trust in 2019, decreasing to 10.1\% in
2020, but this figure rises back to 12.8\% by 2023. The medium and high
categories show corresponding shifts, reflecting a more complex pattern
than the non-imputed data suggested.

\hyperref[appendix-d]{Appendix d} Figure~\ref{fig-alluv-science-imp} and
Figure~\ref{fig-alluv-scientists-imp} visually present these
transitions. Although early gains in high trust appeared promising,
shifts over time are not uniformly in one direction. Instead, the
imputed data indicate gradual redistributions of respondents across low,
medium, and high categories. Such patterns underscore the importance of
correcting for missingness before drawing conclusions about
population-level changes in trust.

\newpage{}

\subsubsection{Study 1a: Longitudinal Trajectories for Value Placed on
Science: Continuous
Analysis}\label{study-1a-longitudinal-trajectories-for-value-placed-on-science-continuous-analysis}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-science-continuous-1.pdf}}

}

\caption{\label{fig-science-continuous}(A) Predicted value of science
without adjusting for missingness (B) Predicted value of science
adjusting for missingness, with points averaged over the ten imputed
datasets (point alpha = 0.025). Note there is considerable variation of
response above and below the mean, and there is slightly higher point
density in panel (B) because we have adjusted for missingness.}

\end{figure}%

\begin{table}

\caption{\label{tbl-marginal-gee-science-observed}Predicted population
average value placed on science over time, without adjusting for missing
data.}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{ll}
\toprule
Years & Predicted (95\% CI)\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{5.52 (5.50, 5.55)}\\
1 & 5.74 (5.71, 5.76)\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{5.79 (5.77, 5.82)}\\
3 & 5.79 (5.77, 5.82)\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{5.83 (5.80, 5.86)}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

\begin{table}

\caption{\label{tbl-marginal-gee-science-imputed}Predicted population
average value placed on science over time, adjusting for missing data.}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{ll}
\toprule
Years & Predicted (95\% CI)\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{5.52 (5.38, 5.65)}\\
1 & 5.66 (5.52, 5.80)\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{5.65 (5.51, 5.78)}\\
3 & 5.62 (5.48, 5.76)\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{5.62 (5.49, 5.75)}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

Figure~\ref{fig-science-continuous} presents the predicted population
average value place on science over time. Panel \textbf{A} shows
estimates without adjusting for missing responses. Panel \textbf{B}
shows estimates that incorporate multiple imputation. These predictions,
derived from generalised estimating equations, reflect the estimated
population trajectories, either without or with adjustments for missing
responses. As shown in Table~\ref{tbl-marginal-gee-science-observed},
when missingness is not taken into account, valuing science appears to
increase steadily from the baseline period to the final wave. However,
after modelling missingness as reported in
Table~\ref{tbl-marginal-gee-science-imputed}, the predicted trajectory
suggests a more modest upward trend that does not continue to climb.
This result shows that ignoring missing responses can inflate the
perceived value of science in a longitudinal cohort.

\newpage{}

\subsubsection{Study 1b: Longitudinal Trajectories for Trust in
Scientists: Continuous
Analysis}\label{study-1b-longitudinal-trajectories-for-trust-in-scientists-continuous-analysis}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-scientists-continuous-1.pdf}}

}

\caption{\label{fig-scientists-continuous}(A) Predicted trust in
scientists without adjusting for missingness (B) Predicted trust in
scientists modelling missingness, with points averaged over the ten
imputed datasets. Points are dimmed to alpha = .025. Note there is again
considerable variation of response above and below the mean, and again
there is slightly higher point density in panel (B) because we have
adjusted for missingness.}

\end{figure}%

\begin{table}

\caption{\label{tbl-marginal-gee-scientists-observed}Predicted
population average trust in scientists over time, without adjusting for
missing data.}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{ll}
\toprule
Years & Predicted (95\% CI)\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{5.31 (5.29, 5.33)}\\
1 & 5.54 (5.52, 5.56)\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{5.57 (5.55, 5.60)}\\
3 & 5.56 (5.53, 5.58)\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{5.46 (5.43, 5.48)}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

\begin{table}

\caption{\label{tbl-marginal-gee-scietists-imputed}Predicted population
average value placed on science over time adjusting for missing data.}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{ll}
\toprule
Years & Predicted (95\% CI)\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{5.30 (5.16, 5.43)}\\
1 & 5.45 (5.31, 5.58)\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{5.43 (5.29, 5.56)}\\
3 & 5.37 (5.24, 5.51)\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{5.26 (5.13, 5.40)}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

A similar pattern emerges for trust in scientists, presented in
Figure~\ref{fig-scientists-continuous}. As shown in
Table~\ref{tbl-marginal-gee-scientists-observed}, the predicted mean
trust increases when missingness is not accounted for. Yet when we
adjust for missing data using multiple imputation, as reported in
Table~\ref{tbl-marginal-gee-scietists-imputed}, the results suggest that
the initial gains in trust may be smaller and less sustained than the
unadjusted models imply. By properly adjusting for missingness, these
analyses provide a clearer picture of true population-wide changes in
trust, rather than relying on observed data that may disproportionately
represent individuals who remain engaged in the study.

\newpage{}

\subsubsection{Study 2a: Longitudinal Trajectories for Value Placed on
Science: Categorical
Analysis}\label{study-2a-longitudinal-trajectories-for-value-placed-on-science-categorical-analysis}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-science-categorical-1.pdf}}

}

\caption{\label{fig-science-categorical}(A) Predicted probability of
classification for value placed on science without adjusting for
missingness (B) Predicted probability of classification for value placed
on science adjusting for missingness. Responses categories are low
(1-3), medium (4-5), high (6-7) on the 1-7 ordinal scale.}

\end{figure}%

\begin{table}

\caption{\label{tbl-categorical-science-observed}Predicted probability
of classification for value placed on science without adjusting for
missing responses. Responses categories are low (1-3), medium (4-5),
high (6-7).}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{lll}
\toprule
Years & Predicted (95\% CI) & Response\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.09 (0.09, 0.09)} & \cellcolor{gray!10}{low}\\
1 & 0.08 (0.08, 0.09) & low\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.08 (0.08, 0.08)} & \cellcolor{gray!10}{low}\\
3 & 0.08 (0.08, 0.08) & low\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.07 (0.07, 0.08)} & \cellcolor{gray!10}{low}\\
\addlinespace
0 & 0.32 (0.31, 0.32) & med\\
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.25 (0.24, 0.25)} & \cellcolor{gray!10}{med}\\
2 & 0.23 (0.23, 0.24) & med\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{0.24 (0.23, 0.24)} & \cellcolor{gray!10}{med}\\
4 & 0.24 (0.23, 0.24) & med\\
\addlinespace
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.59 (0.59, 0.60)} & \cellcolor{gray!10}{high}\\
1 & 0.67 (0.66, 0.67) & high\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.69 (0.68, 0.69)} & \cellcolor{gray!10}{high}\\
3 & 0.68 (0.68, 0.69) & high\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.69 (0.68, 0.70)} & \cellcolor{gray!10}{high}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

\begin{table}

\caption{\label{tbl-categorical-science-imputed}Predicted probability of
classification for value placed on science, here adjusting for missing
responses. Responses categories are low (1-3), medium (4-5), high
(6-7).}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{lll}
\toprule
Years & Predicted (95\% CI) & Response\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.09 (0.09, 0.09)} & \cellcolor{gray!10}{low}\\
1 & 0.09 (0.09, 0.09) & low\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.09 (0.09, 0.09)} & \cellcolor{gray!10}{low}\\
3 & 0.09 (0.09, 0.10) & low\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.09 (0.09, 0.09)} & \cellcolor{gray!10}{low}\\
\addlinespace
0 & 0.32 (0.31, 0.32) & med\\
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.27 (0.27, 0.28)} & \cellcolor{gray!10}{med}\\
2 & 0.27 (0.27, 0.28) & med\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{0.29 (0.28, 0.29)} & \cellcolor{gray!10}{med}\\
4 & 0.30 (0.29, 0.30) & med\\
\addlinespace
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.59 (0.58, 0.60)} & \cellcolor{gray!10}{high}\\
1 & 0.63 (0.63, 0.64) & high\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.63 (0.63, 0.64)} & \cellcolor{gray!10}{high}\\
3 & 0.62 (0.61, 0.62) & high\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.61 (0.61, 0.62)} & \cellcolor{gray!10}{high}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

Note that in Studies 1a and 1b, the response distributions are scattered
across the response scale 1-7 (refer to
Figure~\ref{fig-science-continuous}).

Figure~\ref{fig-science-categorical} displays predicted probabilities
for classification as low (1--3), medium (4--5), or high (6--7) in the
value placed in science over time.
Table~\ref{tbl-categorical-science-observed} presents these
probabilities without adjusting for missing responses. Under these
conditions, the proportion of respondents in the high category appears
to increase from the baseline and remain relatively elevated. However,
after adjusting for missingness (see
Table~\ref{tbl-categorical-science-imputed}), the predicted
probabilities show a less stable pattern, with gains in the high
category tempered and the medium category becoming more prominent. These
differences underscore that ignoring missing responses can create an
artificial appearance of stronger sustained trust.

\newpage{}

\subsubsection{Study 2b: Longitudinal Trajectories for Trust in
Scientists: Categorical
Analysis}\label{study-2b-longitudinal-trajectories-for-trust-in-scientists-categorical-analysis}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-scientists-categorical-1.pdf}}

}

\caption{\label{fig-scientists-categorical}(A) Predicted probability of
classification for trust in scientists without adjusting for missingness
(B) Predicted probability of classification for trust in scientists
adjusting for missingness. Responses categories are low (1-3), medium
(4-5), high (6-7) on the 1-7 ordinal scale.}

\end{figure}%

\begin{table}

\caption{\label{tbl-categorical-scientists-observed}Predicted
probability of classification for trust in scientists without adjusting
for missing responses. Responses categories are low (1-3), medium (4-5),
high (6-7).}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{lll}
\toprule
Years & Predicted (95\% CI) & Response\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.12 (0.11, 0.12)} & \cellcolor{gray!10}{low}\\
1 & 0.09 (0.09, 0.09) & low\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.08 (0.08, 0.08)} & \cellcolor{gray!10}{low}\\
3 & 0.08 (0.08, 0.09) & low\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.09 (0.09, 0.09)} & \cellcolor{gray!10}{low}\\
\addlinespace
0 & 0.34 (0.33, 0.34) & med\\
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.29 (0.28, 0.29)} & \cellcolor{gray!10}{med}\\
2 & 0.28 (0.28, 0.28) & med\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{0.30 (0.29, 0.30)} & \cellcolor{gray!10}{med}\\
4 & 0.33 (0.32, 0.33) & med\\
\addlinespace
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.55 (0.54, 0.55)} & \cellcolor{gray!10}{high}\\
1 & 0.62 (0.62, 0.63) & high\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.64 (0.63, 0.64)} & \cellcolor{gray!10}{high}\\
3 & 0.62 (0.61, 0.62) & high\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.58 (0.58, 0.59)} & \cellcolor{gray!10}{high}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

\begin{table}

\caption{\label{tbl-categorical-scientists-imputed}Predicted probability
of classification for trust in scientists, now adjusting for missing
responses. Responses categories are low (1-3), medium (4-5), high
(6-7).}

\centering{

\centering\begingroup\fontsize{14}{16}\selectfont

\begin{tabular}[t]{lll}
\toprule
Years & Predicted (95\% CI) & Response\\
\midrule
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.12 (0.12, 0.12)} & \cellcolor{gray!10}{low}\\
1 & 0.11 (0.10, 0.11) & low\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.11 (0.11, 0.11)} & \cellcolor{gray!10}{low}\\
3 & 0.12 (0.12, 0.12) & low\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.13 (0.13, 0.13)} & \cellcolor{gray!10}{low}\\
\addlinespace
0 & 0.34 (0.33, 0.35) & med\\
\cellcolor{gray!10}{1} & \cellcolor{gray!10}{0.31 (0.31, 0.32)} & \cellcolor{gray!10}{med}\\
2 & 0.31 (0.31, 0.32) & med\\
\cellcolor{gray!10}{3} & \cellcolor{gray!10}{0.33 (0.33, 0.34)} & \cellcolor{gray!10}{med}\\
4 & 0.35 (0.35, 0.36) & med\\
\addlinespace
\cellcolor{gray!10}{0} & \cellcolor{gray!10}{0.54 (0.53, 0.55)} & \cellcolor{gray!10}{high}\\
1 & 0.58 (0.58, 0.59) & high\\
\cellcolor{gray!10}{2} & \cellcolor{gray!10}{0.58 (0.57, 0.58)} & \cellcolor{gray!10}{high}\\
3 & 0.55 (0.54, 0.56) & high\\
\cellcolor{gray!10}{4} & \cellcolor{gray!10}{0.52 (0.51, 0.52)} & \cellcolor{gray!10}{high}\\
\bottomrule
\end{tabular}
\endgroup{}

}

\end{table}%

A similar pattern emerges for trust in scientists (see
Figure~\ref{fig-scientists-categorical}). Without adjusting for
missingness, the results (shown in
Table~\ref{tbl-categorical-scientists-observed}) suggest that the
proportion classified as high in trust remains consistently large. Once
we incorporate multiple imputation to address missing responses, as
presented in Table~\ref{tbl-categorical-scientists-imputed}, the
predicted probabilities shift. The high category becomes less dominant
over time, and more respondents fall into the medium category than would
have been inferred without proper adjustment. In other words, accounting
for nonresponse reveals a more nuanced pattern of trust that does not
simply trend upward, and this correction prevents inflated estimates of
stable or increasing trust in scientists.

\subsection{Discussion}\label{discussion}

These findings illustrate that failing to adjust for missing responses
can systematically distort estimates of public attitudes to science and
scientists. Compared to models that ignore missingness, our
imputation-adjusted analyses indicate that the unadjusted models
overestimate the proportion of the population with high trust by several
hundred thousand New Zealand adults and underestimate the proportion
with low trust by tens to hundreds of thousands. For example, when the
missing attitudes to science are not adjusted, we underestimate the
share of the population with low trust by about 82,000 people, and
simultaneously overstate the size of the high-trust group by about
330,000. Similarly, for trust in scientists, the discrepancy in the
low-trust population is about 165,000 individuals, and the high-trust
category may be inflated by about 248,000. These differences represent
substantial distortions of attitudes to science and scientists in the
general population of 4.1 million adults.

It is important to note, once again, that these are minimum bounds of
potential distortion, as we cannot measure trust among the population
who declined participation at the study's outset. Moreover, we have not
established any causal relationships. Our objective is not to identify
determinants of changing trust, but rather to describe and characterise
differences in trust distributions over time in that part of the general
population whose attitudes to science did not prevent them from
enlisting in a scientific study prior to COVID-19. Still, given that
trust in science can influence critical actions related to climate
change (\citeproc{ref-bogert2024effect}{Bogert \emph{et al.} 2024}),
vaccine uptake (\citeproc{ref-pagliaro2021trust}{Pagliaro \emph{et al.}
2021}), and following health advice
(\citeproc{ref-rueger2021perception}{Rueger \emph{et al.} 2021}),
accurately documenting trust and its temporal shifts is a pressing
concern. By accounting for missing data, we gain a clearer and more
credible picture.

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study. Members of the NZAVS management team and research
group hold full copies of the NZAVS data. A de-identified dataset
containing only the variables analysed in this manuscript is available
upon request from the corresponding author or any member of the NZAVS
advisory board for replication or checking of any published study using
NZAVS data. The code for the analysis can be found at: OSF-lINK TBA.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Plank Institute for the Science of Human History. The
funders had no role in preparing the manuscript or deciding to publish
it.

\subsubsection{Author Statement}\label{author-statement}

\textbf{TBA}: JK, CGS, DO, MW, and KY developed the measures for the New
Zealand Attitudes and Values Study. JB developed the analytic approach
and did the analysis. CGS led data collection. JB and CGS obtained the
funding. \textbf{All authors had input into the manuscript.}

\newpage{}

\subsection{Appendix A: Sample Descriptive Statistics}\label{appendix-a}

Table~\ref{tbl-demography} presents descriptive statistics for the
sample.

\begingroup\fontsize{7}{9}\selectfont
\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{llllll}

\caption{\label{tbl-demography}Demographic statistics for New Zealand
Attitudes and Values Cohort waves 2019-2023 (years 2019-2024).}

\tabularnewline

\toprule
  & 2019 & 2020 & 2021 & 2022 & 2023\\
\midrule
\endfirsthead
\multicolumn{6}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2019 & 2020 & 2021 & 2022 & 2023\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=42681)} & \cellcolor{gray!10}{(N=42681)} & \cellcolor{gray!10}{(N=42681)} & \cellcolor{gray!10}{(N=42681)} & \cellcolor{gray!10}{(N=42681)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Age}}\\
\hspace{1em}Mean (SD) & 51.6 (13.9) & 53.6 (13.6) & 54.9 (13.5) & 56.3 (13.4) & 57.3 (13.4)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{54.0 [18.0, 96.0]} & \cellcolor{gray!10}{56.0 [18.0, 96.0]} & \cellcolor{gray!10}{58.0 [19.0, 97.0]} & \cellcolor{gray!10}{59.0 [20.0, 98.0]} & \cellcolor{gray!10}{60.0 [21.0, 99.0]}\\
\hspace{1em}Missing & 0 (0\%) & 9363 (21.9\%) & 13615 (31.9\%) & 17167 (40.2\%) & 19409 (45.5\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Agreeableness}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.38 (0.983)} & \cellcolor{gray!10}{5.38 (0.981)} & \cellcolor{gray!10}{5.36 (1.00)} & \cellcolor{gray!10}{5.35 (0.993)} & \cellcolor{gray!10}{5.35 (0.999)}\\
\hspace{1em}Median [Min, Max] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{316 (0.7\%)} & \cellcolor{gray!10}{9579 (22.4\%)} & \cellcolor{gray!10}{13831 (32.4\%)} & \cellcolor{gray!10}{17261 (40.4\%)} & \cellcolor{gray!10}{19461 (45.6\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Belong}}\\
\hspace{1em}Mean (SD) & 5.09 (1.09) & 5.02 (1.11) & 5.14 (1.12) & 5.14 (1.11) & 5.20 (1.11)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]}\\
\hspace{1em}Missing & 324 (0.8\%) & 9587 (22.5\%) & 13885 (32.5\%) & 17304 (40.5\%) & 19510 (45.7\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Born NZ}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.782 (0.413)} & \cellcolor{gray!10}{0.782 (0.413)} & \cellcolor{gray!10}{0.782 (0.413)} & \cellcolor{gray!10}{0.782 (0.413)} & \cellcolor{gray!10}{0.782 (0.413)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, \vphantom{3} 1.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{77 (0.2\%)} & \cellcolor{gray!10}{77 (0.2\%)} & \cellcolor{gray!10}{77 (0.2\%)} & \cellcolor{gray!10}{77 (0.2\%)} & \cellcolor{gray!10}{77 (0.2\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Conscientiousness}}\\
\hspace{1em}Mean (SD) & 5.06 (1.07) & 5.10 (1.05) & 5.12 (1.06) & 5.12 (1.05) & 5.12 (1.05)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]}\\
\hspace{1em}Missing & 313 (0.7\%) & 9577 (22.4\%) & 13823 (32.4\%) & 17260 (40.4\%) & 19485 (45.7\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Education Level Coarsen}}\\
\cellcolor{gray!10}{\hspace{1em}no\_qualification} & \cellcolor{gray!10}{856 (2.0\%)} & \cellcolor{gray!10}{760 (1.8\%)} & \cellcolor{gray!10}{717 (1.7\%)} & \cellcolor{gray!10}{691 (1.6\%)} & \cellcolor{gray!10}{672 (1.6\%)}\\
\hspace{1em}cert\_1\_to\_4 & 13127 (30.8\%) & 12601 (29.5\%) & 12252 (28.7\%) & 12001 (28.1\%) & 11815 (27.7\%)\\
\cellcolor{gray!10}{\hspace{1em}cert\_5\_to\_6} & \cellcolor{gray!10}{5603 (13.1\%)} & \cellcolor{gray!10}{5711 (13.4\%)} & \cellcolor{gray!10}{5747 (13.5\%)} & \cellcolor{gray!10}{5807 (13.6\%)} & \cellcolor{gray!10}{5802 (13.6\%)}\\
\hspace{1em}university & 11775 (27.6\%) & 11851 (27.8\%) & 11816 (27.7\%) & 11736 (27.5\%) & 11685 (27.4\%)\\
\cellcolor{gray!10}{\hspace{1em}post\_grad} & \cellcolor{gray!10}{5361 (12.6\%)} & \cellcolor{gray!10}{5612 (13.1\%)} & \cellcolor{gray!10}{5849 (13.7\%)} & \cellcolor{gray!10}{6015 (14.1\%)} & \cellcolor{gray!10}{6079 (14.2\%)}\\
\hspace{1em}masters & 4258 (10.0\%) & 4444 (10.4\%) & 4581 (10.7\%) & 4692 (11.0\%) & 4795 (11.2\%)\\
\cellcolor{gray!10}{\hspace{1em}doctorate} & \cellcolor{gray!10}{1279 (3.0\%)} & \cellcolor{gray!10}{1336 (3.1\%)} & \cellcolor{gray!10}{1380 (3.2\%)} & \cellcolor{gray!10}{1428 (3.3\%)} & \cellcolor{gray!10}{1535 (3.6\%)}\\
\hspace{1em}Missing & 422 (1.0\%) & 366 (0.9\%) & 339 (0.8\%) & 311 (0.7\%) & 298 (0.7\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Employed}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.757 (0.429)} & \cellcolor{gray!10}{0.758 (0.429)} & \cellcolor{gray!10}{0.734 (0.442)} & \cellcolor{gray!10}{0.699 (0.459)} & \cellcolor{gray!10}{0.687 (0.464)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, \vphantom{2} 1.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{358 (0.8\%)} & \cellcolor{gray!10}{9518 (22.3\%)} & \cellcolor{gray!10}{13745 (32.2\%)} & \cellcolor{gray!10}{17308 (40.6\%)} & \cellcolor{gray!10}{19997 (46.9\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Ethnicity}}\\
\hspace{1em}euro & 34925 (81.8\%) & 34925 (81.8\%) & 34925 (81.8\%) & 34925 (81.8\%) & 34925 (81.8\%)\\
\cellcolor{gray!10}{\hspace{1em}maori} & \cellcolor{gray!10}{4695 (11.0\%)} & \cellcolor{gray!10}{4695 (11.0\%)} & \cellcolor{gray!10}{4695 (11.0\%)} & \cellcolor{gray!10}{4695 (11.0\%)} & \cellcolor{gray!10}{4695 (11.0\%)}\\
\hspace{1em}pacific & 943 (2.2\%) & 943 (2.2\%) & 943 (2.2\%) & 943 (2.2\%) & 943 (2.2\%)\\
\cellcolor{gray!10}{\hspace{1em}asian} & \cellcolor{gray!10}{1785 (4.2\%)} & \cellcolor{gray!10}{1785 (4.2\%)} & \cellcolor{gray!10}{1785 (4.2\%)} & \cellcolor{gray!10}{1785 (4.2\%)} & \cellcolor{gray!10}{1785 (4.2\%)}\\
\hspace{1em}Missing & 333 (0.8\%) & 333 (0.8\%) & 333 (0.8\%) & 333 (0.8\%) & 333 (0.8\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Extraversion}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{3.87 (1.19)} & \cellcolor{gray!10}{3.83 (1.19)} & \cellcolor{gray!10}{3.77 (1.23)} & \cellcolor{gray!10}{3.75 (1.23)} & \cellcolor{gray!10}{3.76 (1.23)}\\
\hspace{1em}Median [Min, Max] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{314 (0.7\%)} & \cellcolor{gray!10}{9577 (22.4\%)} & \cellcolor{gray!10}{13832 (32.4\%)} & \cellcolor{gray!10}{17275 (40.5\%)} & \cellcolor{gray!10}{19476 (45.6\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Honesty Humility}}\\
\hspace{1em}Mean (SD) & 5.56 (1.14) & 5.62 (1.11) & 5.68 (1.13) & 5.72 (1.12) & 5.74 (1.12)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.75 [1.00, 7.00]} & \cellcolor{gray!10}{5.75 [1.00, 7.00]} & \cellcolor{gray!10}{6.00 [1.00, 7.00]} & \cellcolor{gray!10}{6.00 [1.00, 7.00]} & \cellcolor{gray!10}{6.00 [1.00, 7.00]}\\
\hspace{1em}Missing & 323 (0.8\%) & 9587 (22.5\%) & 13816 (32.4\%) & 17253 (40.4\%) & 19452 (45.6\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Kessler Latent Anxiety}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{1.20 (0.759)} & \cellcolor{gray!10}{1.17 (0.757)} & \cellcolor{gray!10}{1.19 (0.766)} & \cellcolor{gray!10}{1.17 (0.767)} & \cellcolor{gray!10}{1.16 (0.764)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 4.00] & 1.00 [0, 4.00] & 1.00 [0, 4.00] & 1.00 [0, 4.00] & 1.00 [0, 4.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{344 (0.8\%)} & \cellcolor{gray!10}{9591 (22.5\%)} & \cellcolor{gray!10}{13814 (32.4\%)} & \cellcolor{gray!10}{17258 (40.4\%)} & \cellcolor{gray!10}{19456 (45.6\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Kessler Latent Depression}}\\
\hspace{1em}Mean (SD) & 0.596 (0.748) & 0.555 (0.726) & 0.573 (0.738) & 0.537 (0.725) & 0.530 (0.724)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0.333 [0, 4.00]} & \cellcolor{gray!10}{0.333 [0, 4.00]} & \cellcolor{gray!10}{0.333 [0, 4.00]} & \cellcolor{gray!10}{0.333 [0, 4.00]} & \cellcolor{gray!10}{0.333 [0, 4.00]}\\
\hspace{1em}Missing & 340 (0.8\%) & 9588 (22.5\%) & 13814 (32.4\%) & 17260 (40.4\%) & 19454 (45.6\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Hours Children}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{12.5 (30.9)} & \cellcolor{gray!10}{11.0 (28.8)} & \cellcolor{gray!10}{9.66 (26.2)} & \cellcolor{gray!10}{9.46 (26.1)} & \cellcolor{gray!10}{9.31 (25.8)}\\
\hspace{1em}Median [Min, Max] & 0 [0, 168] & 0 [0, 168] & 0 [0, 168] & 0 [0, 168] & 0 [0, 168]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{830 (1.9\%)} & \cellcolor{gray!10}{10233 (24.0\%)} & \cellcolor{gray!10}{14622 (34.3\%)} & \cellcolor{gray!10}{18102 (42.4\%)} & \cellcolor{gray!10}{20424 (47.9\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Hours Commute}}\\
\hspace{1em}Mean (SD) & 4.49 (6.98) & 4.42 (5.91) & 3.74 (5.40) & 4.43 (6.17) & 4.52 (6.31)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{3.00 [0, 168]} & \cellcolor{gray!10}{3.00 [0, 100]} & \cellcolor{gray!10}{2.00 [0, 100]} & \cellcolor{gray!10}{3.00 [0, 100]} & \cellcolor{gray!10}{3.00 [0, 100]}\\
\hspace{1em}Missing & 829 (1.9\%) & 10233 (24.0\%) & 14611 (34.2\%) & 18093 (42.4\%) & 20416 (47.8\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Hours Exercise}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{6.22 (8.21)} & \cellcolor{gray!10}{6.17 (7.38)} & \cellcolor{gray!10}{6.25 (7.02)} & \cellcolor{gray!10}{6.23 (7.11)} & \cellcolor{gray!10}{6.45 (7.28)}\\
\hspace{1em}Median [Min, Max] & 4.00 [0, 168] & 5.00 [0, 80.0] & 5.00 [0, 85.0] & 5.00 [0, 80.0] & 5.00 [0, 80.0]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{832 (1.9\%)} & \cellcolor{gray!10}{10233 (24.0\%)} & \cellcolor{gray!10}{14613 (34.2\%)} & \cellcolor{gray!10}{18097 (42.4\%)} & \cellcolor{gray!10}{20420 (47.8\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Hours Housework}}\\
\hspace{1em}Mean (SD) & 10.4 (9.32) & 10.9 (9.73) & 10.9 (9.30) & 11.0 (9.34) & 11.0 (8.90)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{8.00 [0, 168]} & \cellcolor{gray!10}{10.0 [0, 168]} & \cellcolor{gray!10}{10.0 [0, 168]} & \cellcolor{gray!10}{10.0 [0, 168]} & \cellcolor{gray!10}{10.0 [0, 168]}\\
\hspace{1em}Missing & 831 (1.9\%) & 10233 (24.0\%) & 14611 (34.2\%) & 18094 (42.4\%) & 20417 (47.8\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Household Inc}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{118000 (108000)} & \cellcolor{gray!10}{120000 (106000)} & \cellcolor{gray!10}{124000 (112000)} & \cellcolor{gray!10}{131000 (147000)} & \cellcolor{gray!10}{133000 (124000)}\\
\hspace{1em}Median [Min, Max] & 100000 [1.00, 4000000] & 100000 [1.00, 3000000] & 100000 [1.00, 3500000] & 100000 [1000, 7500000] & 100000 [0, 5000000]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{2039 (4.8\%)} & \cellcolor{gray!10}{10255 (24.0\%)} & \cellcolor{gray!10}{14368 (33.7\%)} & \cellcolor{gray!10}{17626 (41.3\%)} & \cellcolor{gray!10}{20296 (47.6\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Male}}\\
\hspace{1em}Mean (SD) & 0.359 (0.480) & 0.357 (0.479) & 0.355 (0.479) & 0.360 (0.480) & 0.360 (0.480)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, \vphantom{1} 1.00]}\\
\hspace{1em}Missing & 192 (0.4\%) & 9540 (22.4\%) & 13791 (32.3\%) & 17320 (40.6\%) & 19564 (45.8\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Neuroticism}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{3.50 (1.16)} & \cellcolor{gray!10}{3.46 (1.16)} & \cellcolor{gray!10}{3.41 (1.18)} & \cellcolor{gray!10}{3.36 (1.17)} & \cellcolor{gray!10}{3.34 (1.18)}\\
\hspace{1em}Median [Min, Max] & 3.50 [1.00, 7.00] & 3.50 [1.00, 7.00] & 3.25 [1.00, 7.00] & 3.25 [1.00, 7.00] & 3.25 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{315 (0.7\%)} & \cellcolor{gray!10}{9580 (22.4\%)} & \cellcolor{gray!10}{13822 (32.4\%)} & \cellcolor{gray!10}{17262 (40.4\%)} & \cellcolor{gray!10}{19469 (45.6\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Nz Dep2018}}\\
\hspace{1em}Mean (SD) & 4.75 (2.72) & 4.75 (2.73) & 4.75 (2.73) & 4.74 (2.73) & 4.74 (2.74)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{4.00 [1.00, 10.0]} & \cellcolor{gray!10}{4.00 [1.00, 10.0]} & \cellcolor{gray!10}{4.00 [1.00, 10.0]} & \cellcolor{gray!10}{4.00 [1.00, 10.0]} & \cellcolor{gray!10}{4.00 [1.00, 10.0]}\\
\hspace{1em}Missing & 328 (0.8\%) & 530 (1.2\%) & 918 (2.2\%) & 884 (2.1\%) & 932 (2.2\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Nzsei 13 L}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{55.5 (16.0)} & \cellcolor{gray!10}{55.8 (16.5)} & \cellcolor{gray!10}{56.4 (16.3)} & \cellcolor{gray!10}{56.8 (15.5)} & \cellcolor{gray!10}{56.6 (15.7)}\\
\hspace{1em}Median [Min, Max] & 59.0 [10.0, 90.0] & 60.0 [10.0, 90.0] & 61.0 [10.0, 90.0] & 60.0 [10.0, 90.0] & 60.0 [10.0, 90.0]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{335 (0.8\%)} & \cellcolor{gray!10}{3215 (7.5\%)} & \cellcolor{gray!10}{4270 (10.0\%)} & \cellcolor{gray!10}{5852 (13.7\%)} & \cellcolor{gray!10}{7166 (16.8\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Openness}}\\
\hspace{1em}Mean (SD) & 5.01 (1.11) & 5.01 (1.11) & 5.02 (1.14) & 5.01 (1.15) & 5.02 (1.16)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{5.00 [1.00, \vphantom{1} 7.00]}\\
\hspace{1em}Missing & 316 (0.7\%) & 9579 (22.4\%) & 13830 (32.4\%) & 17266 (40.5\%) & 19480 (45.6\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Parent}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.732 (0.443)} & \cellcolor{gray!10}{0.747 (0.435)} & \cellcolor{gray!10}{0.749 (0.434)} & \cellcolor{gray!10}{0.768 (0.422)} & \cellcolor{gray!10}{0.766 (0.423)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, \vphantom{1} 1.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{20 (0.0\%)} & \cellcolor{gray!10}{9363 (21.9\%)} & \cellcolor{gray!10}{13648 (32.0\%)} & \cellcolor{gray!10}{17167 (40.2\%)} & \cellcolor{gray!10}{19409 (45.5\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Partner}}\\
\hspace{1em}Mean (SD) & 0.748 (0.434) & 0.750 (0.433) & 0.752 (0.432) & 0.746 (0.436) & 0.741 (0.438)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]}\\
\hspace{1em}Missing & 786 (1.8\%) & 9844 (23.1\%) & 14248 (33.4\%) & 17869 (41.9\%) & 20144 (47.2\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Political Conservative}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{3.51 (1.41)} & \cellcolor{gray!10}{3.40 (1.36)} & \cellcolor{gray!10}{3.47 (1.35)} & \cellcolor{gray!10}{3.54 (1.40)} & \cellcolor{gray!10}{3.52 (1.41)}\\
\hspace{1em}Median [Min, Max] & 4.00 [1.00, 7.00] & 3.00 [1.00, 7.00] & 4.00 [1.00, 7.00] & 4.00 [1.00, 7.00] & 4.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{1314 (3.1\%)} & \cellcolor{gray!10}{10603 (24.8\%)} & \cellcolor{gray!10}{14894 (34.9\%)} & \cellcolor{gray!10}{18360 (43.0\%)} & \cellcolor{gray!10}{20593 (48.2\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Religion Identification Level}}\\
\hspace{1em}Mean (SD) & 2.31 (2.17) & 2.30 (2.15) & 2.27 (2.13) & 2.29 (2.16) & 2.27 (2.16)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{1.00 [1.00, 7.00]} & \cellcolor{gray!10}{1.00 [1.00, 7.00]} & \cellcolor{gray!10}{1.00 [1.00, 7.00]} & \cellcolor{gray!10}{1.00 [1.00, 7.00]} & \cellcolor{gray!10}{1.00 [1.00, 7.00]}\\
\hspace{1em}Missing & 606 (1.4\%) & 9758 (22.9\%) & 13970 (32.7\%) & 17956 (42.1\%) & 20283 (47.5\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Rural Gch 2018 Levels}}\\
\cellcolor{gray!10}{\hspace{1em}1} & \cellcolor{gray!10}{25864 (60.6\%)} & \cellcolor{gray!10}{25582 (59.9\%)} & \cellcolor{gray!10}{25109 (58.8\%)} & \cellcolor{gray!10}{24977 (58.5\%)} & \cellcolor{gray!10}{24858 (58.2\%)}\\
\hspace{1em}2 & 8164 (19.1\%) & 8195 (19.2\%) & 8189 (19.2\%) & 8223 (19.3\%) & 8254 (19.3\%)\\
\cellcolor{gray!10}{\hspace{1em}3} & \cellcolor{gray!10}{5362 (12.6\%)} & \cellcolor{gray!10}{5442 (12.8\%)} & \cellcolor{gray!10}{5477 (12.8\%)} & \cellcolor{gray!10}{5535 (13.0\%)} & \cellcolor{gray!10}{5550 (13.0\%)}\\
\hspace{1em}4 & 2461 (5.8\%) & 2476 (5.8\%) & 2500 (5.9\%) & 2557 (6.0\%) & 2578 (6.0\%)\\
\cellcolor{gray!10}{\hspace{1em}5} & \cellcolor{gray!10}{506 (1.2\%)} & \cellcolor{gray!10}{507 (1.2\%)} & \cellcolor{gray!10}{490 (1.1\%)} & \cellcolor{gray!10}{505 (1.2\%)} & \cellcolor{gray!10}{510 (1.2\%)}\\
\hspace{1em}Missing & 324 (0.8\%) & 479 (1.1\%) & 916 (2.1\%) & 884 (2.1\%) & 931 (2.2\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Right Wing Authoritarianism}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{3.17 (1.14)} & \cellcolor{gray!10}{3.25 (1.11)} & \cellcolor{gray!10}{3.33 (1.06)} & \cellcolor{gray!10}{3.30 (1.07)} & \cellcolor{gray!10}{3.22 (1.10)}\\
\hspace{1em}Median [Min, Max] & 3.17 [1.00, 7.00] & 3.17 [1.00, 7.00] & 3.33 [1.00, 7.00] & 3.33 [1.00, 7.00] & 3.17 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{46 (0.1\%)} & \cellcolor{gray!10}{9423 (22.1\%)} & \cellcolor{gray!10}{13803 (32.3\%)} & \cellcolor{gray!10}{17221 (40.3\%)} & \cellcolor{gray!10}{19494 (45.7\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Sample Frame Opt In}}\\
\hspace{1em}Mean (SD) & 0.158 (0.365) & 0.158 (0.365) & 0.158 (0.365) & 0.158 (0.365) & 0.158 (0.365)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Social Dominance Orientation}}\\
\hspace{1em}Mean (SD) & 2.22 (0.958) & 2.18 (0.949) & 2.20 (0.949) & 2.23 (0.963) & 2.23 (0.966)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{2.17 [1.00, 7.00]} & \cellcolor{gray!10}{2.00 [1.00, 7.00]} & \cellcolor{gray!10}{2.00 [1.00, 7.00]} & \cellcolor{gray!10}{2.00 [1.00, 7.00]} & \cellcolor{gray!10}{2.17 [1.00, 7.00]}\\
\hspace{1em}Missing & 16 (0.0\%) & 9383 (22.0\%) & 13647 (32.0\%) & 17171 (40.2\%) & 19432 (45.5\%)\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Short Form Health}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{4.99 (1.18)} & \cellcolor{gray!10}{5.02 (1.15)} & \cellcolor{gray!10}{4.94 (1.20)} & \cellcolor{gray!10}{4.85 (1.17)} & \cellcolor{gray!10}{4.82 (1.18)}\\
\hspace{1em}Median [Min, Max] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{10 (0.0\%)} & \cellcolor{gray!10}{9369 (22.0\%)} & \cellcolor{gray!10}{13659 (32.0\%)} & \cellcolor{gray!10}{17221 (40.3\%)} & \cellcolor{gray!10}{19495 (45.7\%)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Social Support (perceived)}}\\
\hspace{1em}Mean (SD) & 5.93 (1.15) & 5.93 (1.14) & 5.93 (1.16) & 5.96 (1.15) & 5.98 (1.15)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{6.33 [1.00, 7.00]} & \cellcolor{gray!10}{6.33 [1.00, 7.00]} & \cellcolor{gray!10}{6.33 [1.00, 7.00]} & \cellcolor{gray!10}{6.33 [1.00, 7.00]} & \cellcolor{gray!10}{6.33 [1.00, 7.00]}\\
\hspace{1em}Missing & 28 (0.1\%) & 9397 (22.0\%) & 13772 (32.3\%) & 17269 (40.5\%) & 19544 (45.8\%)\\*

\end{longtable}

\endgroup{}
\endgroup{}

\newpage{}

\subsection{Appendix B: New Zealand Attitudes and Values Study Data
Collection waves 2019-2023 (years 2019-2024)}\label{appendix-b}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-timeline-1.pdf}}

}

\caption{\label{fig-timeline}Historgram of New Zealand Attitudes and
Values Study Daily Data Collection Wave 2019 (time 11) - Wave 2023 (time
15).}

\end{figure}%

\newpage{}

\subsection{Appendix C: Alluvial Graph of Showing Categorical Responses
to Value of Science and Trust in Scientists: No Adjustment For Missing
Data.}\label{appendix-c}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-alluv-scientists-sample-1.pdf}}

}

\caption{\label{fig-alluv-scientists-sample}Alluvial plot suggests
increasing flow of value of science for the retained sample.}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-alluv-science-sample-1.pdf}}

}

\caption{\label{fig-alluv-science-sample}Alluvial plot suggests
increasing flow of trust in scientists for the retained sample.}

\end{figure}%

\newpage{}

\subsection{Appendix D: Alluvial Graphs of Showing Categorical Responses
to Social Value of Science and Trust in Scientists: Adjusting For
Missing Data.}\label{appendix-d}

Figure~\ref{fig-alluv-science-imp} and
(\citeproc{ref-g-alluv-scientists-imp}{\textbf{g-alluv-scientists-imp?}})
depict the dynamics of categorical responses for attitudes to science
and scientists. Following 2020, there is a decline in the value placed
on scientific institutions and a growth of mistrust in scientists. Our
analysis presents the a minimal bound for such mistrust because we
cannot account for the mistrust of the population who declined to
praticipate in New Zealand Attitudes and Values Study wave 2019 (time
11).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-alluv-science-imp-1.pdf}}

}

\caption{\label{fig-alluv-science-imp}Alluvial plot suggests declines in
value of science for the imputed cohort.}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-jk-growth-trust-science-T15_files/figure-pdf/fig-alluv-scientists-imp-1.pdf}}

}

\caption{\label{fig-alluv-scientists-imp}Alluvial plot suggests declines
in trust in scientists for the imputed cohort}

\end{figure}%

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-tinytable_2024}
Arel-Bundock, V (2024) \emph{Tinytable: Simple and configurable tables
in 'HTML', 'LaTeX', 'markdown', 'word', 'PNG', 'PDF', and 'typst'
formats}. Retrieved from
\url{https://CRAN.R-project.org/package=tinytable}

\bibitem[\citeproctext]{ref-blackwell_2017_unified}
Blackwell, M, Honaker, J, and King, G (2017) A unified approach to
measurement error and missing data: Overview and applications.
\emph{Sociological Methods \& Research}, \textbf{46}(3), 303--341.

\bibitem[\citeproctext]{ref-bogert2024effect}
Bogert, J, Buczny, J, Harvey, J, and Ellers, J (2024) The effect of
trust in science and media use on public belief in anthropogenic climate
change: A meta-analysis. \emph{Environmental Communication},
\textbf{18}(4), 484--509.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-bulbulia2023a}
Bulbulia, JA, Afzali, MU, Yogeeswaran, K, and Sibley, CG (2023)
Long-term causal effects of far-right terrorism in {N}ew {Z}ealand.
\emph{PNAS Nexus}, \textbf{2}(8), pgad242.

\bibitem[\citeproctext]{ref-gundersen2022science}
Gundersen, T, and Holst, C (2022) Science advice in an environment of
trust: Trusted, but not trustworthy? \emph{Social Epistemology},
\textbf{36}(5), 629--640.

\bibitem[\citeproctext]{ref-geepack_2006}
Halekoh, U, Højsgaard, S, and Yan, J (2006) The {R} package geepack for
generalized estimating equations. \emph{Journal of Statistical
Software}, \textbf{15/2}, 1--11. Retrieved from
\url{https://www.jstatsoft.org/v15/i02/}

\bibitem[\citeproctext]{ref-hartman2017}
Hartman, RO, Dieckmann, NF, Sprenger, AM, Stastny, BJ, and DeMarree, KG
(2017) Modeling attitudes toward science: Development and validation of
the credibility of science scale. \emph{Basic and Applied Social
Psychology}, \textbf{39}, 358--371.
doi:\href{https://doi.org/10.1080/01973533.2017.1372284}{10.1080/01973533.2017.1372284}.

\bibitem[\citeproctext]{ref-amelia_2011}
Honaker, J, King, G, and Blackwell, M (2011) {Amelia II}: A program for
missing data. \emph{Journal of Statistical Software}, \textbf{45}(7),
1--47.

\bibitem[\citeproctext]{ref-kennedy2022americans}
Kennedy, B, Tyson, A, and Funk, C (2022) Americans' trust in scientists,
other groups declines. \emph{Pew Research Center}, \textbf{15}.

\bibitem[\citeproctext]{ref-kreps2020model}
Kreps, SE, and Kriner, DL (2020) Model uncertainty, political
contestation, and public trust in science: Evidence from the COVID-19
pandemic. \emph{Science Advances}, \textbf{6}(43), eabd4563.

\bibitem[\citeproctext]{ref-ggeffects_2018}
Ludecke, D (2018) Ggeffects: Tidy data frames of marginal effects from
regression models. \emph{Journal of Open Source Software},
\textbf{3}(26), 772.
doi:\href{https://doi.org/10.21105/joss.00772}{10.21105/joss.00772}.

\bibitem[\citeproctext]{ref-mcneish_2017unnecessary}
McNeish, D, Stapleton, LM, and Silverman, RD (2017) On the unnecessary
ubiquity of hierarchical linear modeling. \emph{Psychological Methods},
\textbf{22}(1), 114.

\bibitem[\citeproctext]{ref-nisbet2015}
Nisbet, EC, Cooper, KE, and Garrett, RK (2015) The partisan brain: How
dissonant science messages lead conservatives and liberals to (dis)trust
science. \emph{The ANNALS of the American Academy of Political and
Social Science}, \textbf{658}(1), 36--66.
doi:\href{https://doi.org/10.1177/0002716214555474}{10.1177/0002716214555474}.

\bibitem[\citeproctext]{ref-pagliaro2021trust}
Pagliaro, S, Sacchi, S, Pacilli, MG, et al.others (2021) Trust predicts
COVID-19 prescribed and discretionary behavioral intentions in 23
countries. \emph{PloS One}, \textbf{16}(3), e0248334.

\bibitem[\citeproctext]{ref-reif2021representative}
Reif, A, and Guenther, L (2021) How representative surveys measure
public (dis) trust in science: A systematisation and analysis of survey
items and open-ended questions. \emph{Journal of Trust Research},
\textbf{11}(2), 94--118.

\bibitem[\citeproctext]{ref-rueger2021perception}
Rueger, J, Dolfsma, W, and Aalbers, R (2021) Perception of peer advice
in online health communities: Access to lay expertise. \emph{Social
Science \& Medicine}, \textbf{277}, 113117.

\bibitem[\citeproctext]{ref-schoor2021science}
Schoor, C, and Schütz, A (2021) Science-utility and science-trust
associations and how they relate to knowledge about how science works.
\emph{Plos One}, \textbf{16}(12), e0260586.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the {N}ew {Z}ealand {A}ttitudes and {V}alues
{S}tudy}}.

\bibitem[\citeproctext]{ref-sibley2020a}
Sibley, CG, Greaves, L, Satherley, N, \ldots{} al, et (2020) What
happened to people in {N}ew {Z}ealand during covid-19 home lockdown?
Institutional trust, attitudes to government, mental health and
subjective wellbeing. Retrieved from
\href{https://osf.io/e765a}{osf.io/e765a}

\bibitem[\citeproctext]{ref-sturgis2021trust}
Sturgis, P, Brunton-Smith, I, and Jackson, J (2021) Trust in science,
social consensus and vaccine confidence. \emph{Nature Human Behaviour},
\textbf{5}(11), 1528--1534.

\bibitem[\citeproctext]{ref-nnet_2002}
Venables, WN, and Ripley, BD (2002) \emph{Modern applied statistics with
s}, Fourth, New York: Springer. Retrieved from
\url{https://www.stats.ox.ac.uk/pub/MASS4/}

\bibitem[\citeproctext]{ref-ggplot2_2016}
Wickham, H (2016) \emph{ggplot2: Elegant graphics for data analysis},
Springer-Verlag New York. Retrieved from
\url{https://ggplot2.tidyverse.org}

\end{CSLReferences}




\end{document}
