% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{tabularray}
\usepackage[normalem]{ulem}
\usepackage{graphicx}
\UseTblrLibrary{booktabs}
\UseTblrLibrary{rotating}
\UseTblrLibrary{siunitx}
\NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
\newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
\newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\let\oldtabular\tabular
\renewcommand{\tabular}{\small\oldtabular}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Evidence for Declining Trust in Science From A Large National Panel Study in New Zealand (years 2019-2023)},
  pdfauthor={Authors},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Evidence for Declining Trust in Science From A Large National
Panel Study in New Zealand (years 2019-2023)}

\usepackage{academicons}
\usepackage{xcolor}

  \author{Authors}
            \affil{%
             \small{     New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0003-3169-6576 }
              }
      


\date{2024-11-11}
\begin{document}
\maketitle
\begin{abstract}
The public's perception of science has wide-ranging effects, from the
adoption public health behaviours to climate action. Here, drawing on a
nationally diverse panel study in New Zealand, we report patterns of
trust in science and trust in scientists from late 2019 to late 2023 in
a large nationally diverse cohort of (N = 42,681, New Zealand Attitudes
and Values Study). \textbf{Study 1} uses multiple imputation to examine
systematic biases from attrition in the 2019 cohort, and the need to
correct for such biases when assessing trust in science using survey
designs. \textbf{Study 2} models on average trust reponses of time,
revealing that average trust for both science and scientists increased
following the New Zealand Covid-19 pandemic response, only to
subsequently decline, with evidence for heterogeneity above and below
the mean. \textbf{Study 3} investigates proportional change across the
low, medium, and high ends of the response scale, finding evidence for
increasing mistrust at the low end and high ends of the response
spectrum. When this change is considered across the entire New Zealand
population, it indicates that nearly 60,000 New Zealanders who
previously had at least moderate trust in science may now hold a low
level of trust in it. \textbf{KEYWORDS}: \emph{Conservativism};
\emph{Institutional Trust}; \emph{Longitudinal}; \emph{Panel};
\emph{Political}; \emph{Science}.
\end{abstract}


\subsection{Introduction}\label{introduction}

Whether people are growing more sceptical of science is question of
considerable interest and concern.

To address this question, we leverage for waves of comprehensive panel
data from 42,681 participants in the New Zealand Attitudes and Values
Study, spanning the years 2019-2023.

Study 2 reports averages response among the 2019 cohort during this
period, and also stratifies responses by ethnicity, gender (binary) and
political orientation.

Study 3 investigates dynamics across the response scale, considering
dynamics at the low, medium, and high end the trust in science and trust
in scientist scales.

The aim of each study is descriptive and exploratory, without testing
specific hypotheses. Our primary objective is to outline and
characterise the patterns of change in institutional trust, focusing on
indicators of trust in science and trust in scientists.

\subsection{Method}\label{method}

\subsubsection{Target Population}\label{target-population}

The target population for this study comprises the cohort New Zealand
residents in wave 2019 whose mistrust of science would not have prevent
them from participating in New Zealand Attitudes and Values Study that
year. Here our task is to infer population dynamics for this cohort uses
responses from individuals who participated in the New Zealand Attitudes
and Values Study (NZAVS) during 2019 the baseline wave for this study,
weighted by New Zealand Census weights for age, gender, and ethnicity
(refer to Sibley (\citeproc{ref-sibley2021}{2021})).

\subsubsection{Sample}\label{sample}

The New Zealand Attitudes and Values Study is a national probability
study designed to accurately reflect the broader New Zealand population.
It uses prize draws to incentivise participation. Although the New
Zealand Attitudes and Values Study has good demographic representation
of the country as a whole, it tends to under-sample males and
individuals of Asian descent and over-sample females and Māori (the
indigenous peoples of New Zealand). To address enhance the accuracy of
our findings for the target population, we apply 2018 New Zealand Census
survey weights to the sample data. These weights adjust for variations
in age, gender, and ethnicity to better approximate the national
demographic composition (\citeproc{ref-sibley2021}{Sibley 2021}).

\subsubsection{Eligibility Criteria}\label{eligibility-criteria}

To be eligible, participants needed to respond to the New Zealand
Attitudes and Values Study Time 11, years 2019-2020. Missing responses
were permitted in the baseline wave and all follow up waves through
Zealand Attitudes and Values Study Time 14, years 2022-2023. A total of
42,681 individuals met these criteria and were included in the study.
The proportion of missing data for each variable by wave is describe in
\hyperref[appendix-a]{Appendix A} Table~\ref{tbl-baseline}.

\subsection{Measures}\label{measures}

We estimated target population average responses for two indicators of
trust in science, which for simplicity we call ``trust in science'' and
``trust in scientists.''

\paragraph{Trust Science}\label{trust-science}

\emph{Our society places too much emphasis on science (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-hartman2017}{Hartman \emph{et al.} 2017}).

\paragraph{Trust Scientists}\label{trust-scientists}

\emph{I have a high degree of confidence in the scientific community.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-nisbet2015}{Nisbet \emph{et al.} 2015}).

Note that the term ``trust in science'' a shorthand for the value one
places on society's emphasis on science. It is plausible that at least
some who disagree with society's emphasis on science are nevertheless
trusting of scientific institutions. Some might perceive that society
would be better off emphasising culture, religion, the arts, family,
sport, or other domains than science while at the same time trusting
science. We use ``trust in science'' as a convenient short-hand for a
more complex construct

\subsubsection{Study Design}\label{study-design}

In Study 1, we examine potential biases in a attrition by reporting
sample responses over time. Here we report responses in the observed
sample and compare these to multiply imputed responses for the full 2019
cohort. This study clarifies the magnitude of threat for inferences
about population-level trust in science and scientists from non-response
among those who become sceptical of science or scientists.

In Study 2, we report population-level changes in average trust in
science and scientists for the New Zealand population from late 2019 to
late 2022, adjusting for attrition bias. We analyse response patterns
for the entire population and by subgroups defined by ethnicity, binary
gender, and political conservatism. Political conservatism, a continuous
variable, was standardised, and we evaluated predicted responses at
standard deviation units of \({-1, 0, 1, 2}\), representing a spectrum
from liberal (-1 SD from the mean) to conservative (+2 SD from the
mean). These values are within the range of political conservatism
observed in the 2019 cohort data, which spans from -1.79 to 2.48
standard deviations.

In Study 3, we examined change in trust response in the wave 2019 cohort
at the low (1-3), medium (4,5), and high (6,7) end of the response scale
both in the general population and in the population as defined by
ethnicity, binary gender, and political conservativism. The purpose of
this study is to investigate how patterns of trust vary across different
levels of response -- not merely at the average response -- and to
describe variation in these patterns across demographic groups defined
by ethnicity, binary gender, and political conservatism. Here we
additionally quantify the approximate sizes of the populations that
changed in low trust.

\subsubsection{Measures}\label{measures-1}

\paragraph{Trust Science}\label{trust-science-1}

\emph{Our society places too much emphasis on science (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-hartman2017}{Hartman \emph{et al.} 2017}).

\paragraph{Trust Scientists}\label{trust-scientists-1}

\emph{I have a high degree of confidence in the scientific community.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-nisbet2015}{Nisbet \emph{et al.} 2015}).

\paragraph{Ethnicity (Categorical)}\label{ethnicity-categorical}

\emph{Which ethnic group(s) do you belong to?}

Responses were coded as follows, using New Zealand Census standards: (1
= New Zealand European, 2 = Māori, 3 = Pacific, 4 = Asian).

\paragraph{Gender (Binary Indicator)}\label{gender-binary-indicator}

\emph{What is your gender?}

Gender was assessed through an open-ended question: ``What is your
gender?.'' Female was coded as 0, Male as 1, and gender diverse as 3 (or
0.5 for responses indicating neither female nor male) following the
coding system described by Fraser et al.~(2020). For the purpose of this
analysis, we coded all participants who identified as Male as 1 and all
others as 0 (\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.}
2020}).

\paragraph{Political Conservatism}\label{political-conservatism}

\emph{Please rate how politically liberal versus conservative you see
yourself as being.}

Responses were recorded on an ordinal scale from 1 (Extremely Liberal)
to 7 (Extremely Conservative) (\citeproc{ref-jost_end_2006-1}{Jost
2006}).

\subsubsection{Missing Data}\label{missing-data}

Our objective is to estimate the population levels of trust in science
and scientists in the general New Zealand population from late 2019 to
late 2023 using data from the New Zealand Attitudes and Values Study
(NZAVS). We face two primary data challenges when estimating
population-level trends.

First, although the NZAVS is a national probability study that recruits
participants using randomised mailouts from the New Zealand Electoral
Roll, only approximately 10\% of those invited choose to participate. It
is plausible that the proportion of science sceptics is higher among
those who declined participation, as the NZAVS is conducted by
scientists with the aim of fostering scientific understanding.

Second, although the NZAVS maintains an annual retention rate between
70--80\% of its sample, attrition over time is inevitable in any
longitudinal panel. It is credible that participants who develop
scepticism towards science or scientists may be more likely to drop out,
leading to an overestimation of trust levels in the remaining sample.

Although we cannot directly address the first challenge -- we cannot
accurately estimate the density of those who mistrust science among
those who never participated in our scientific study -- the second
challenge, inferring mistrust among those participated in the New
Zealand Attitudes and Values Study in wave 2019 and subsequently
abandoned the study, can potentially be mitigated. If the probability of
missing responses, both within a wave and over time, can be assumed to
be conditionally independent given observed covariates, we can apply
multiple imputation methods to adjust for bias in attrition. This
approach allows us to systematically incorporate the uncertainty arising
from missing data into our estimates
(\citeproc{ref-blackwell_2017_unified}{Blackwell \emph{et al.} 2017};
\citeproc{ref-bulbulia2023a}{Bulbulia \emph{et al.} 2023}).

Here, we use the Amelia package in R (\citeproc{ref-amelia_2011}{Honaker
\emph{et al.} 2011}) to create ten multiply imputed datasets for the
2019 New Zealand Attitudes and Values Study cohort for waves 11-14
(years 2019-2022). Trust in science and trust in scientists responses
were treated as order and ordinal. The \texttt{Amelia} package is
purpose-built for within-unit imputation in repeated-measures
time-series data. All covariates in Table~\ref{tbl-baseline} were
included in the imputation model, and the time variable (``year'') was
modelled as a cubic spline to account for non-linear trends over the
four-year period.

\subsubsection{Statistical Estimator}\label{statistical-estimator}

In Study 1 we report the retained sample means for trust in science and
trust in scientists from New Zealand Attitudes and Values Study waves
2019-2023 (waves 11-14). We also report retained sample frequencies for
response in low, medium, and high trust over this same time-frame.

To infer target population means and frequencies in the full cohort
population, we apply Rubin's rule to pool the estimates across 10
multiply imputed datasets. This method allows us to combine
within-imputation variance and between-imputation variance to obtain
more accurate estimates and associated uncertainty, thus reflecting the
variability inherent in the imputation process.

In Study 2, we examined mean responses for trust in science and trust in
scientists in the target population over time using generalised
estimating equations (GEE), using the \texttt{geepack} package in R
(\citeproc{ref-geepack_2006}{Halekoh \emph{et al.} 2006}) and applying
Rubin's rule to pool undercertainty over our estimates. Generalised
estimating equations provide robust standard errors for clustering in
the repeated measures, with fewer assumptions than are required for
multi-level models (\citeproc{ref-mcneish_2017unnecessary}{McNeish
\emph{et al.} 2017}). We specified GEE models using participant id as
the clustering variable to adjust for repeated observations across
survey waves. To obtain inferences for the New Zealand population, we
incorporated sample weights derived from the 2018 New Zealand Census
data. We modelled responses separately for the ten imputed datasets and
then pooled uncertainty over these estimates using Rubin's rule
(employed using \texttt{ggeffect:pool\_predictions()}
(\citeproc{ref-ggeffects_2018}{Ludecke 2018})).

In Study 3, we focused the proportional change in predicted
probabilities across low, medium, and high categories of trust
responses. For this purpose, we employed neural networks using the
\texttt{nnet} package in R (\citeproc{ref-nnet_2002}{Venables and Ripley
2002}). The neural network models provided estimates of the probability
of responses falling into each category across different survey waves.
The outputs included predicted probabilities for each response category,
again pooling uncertainty over the models for each imputed dataset using
Rubin's rule. As with Study 2, we used sample weights constructed from
the 2018 New Zealand Census data to ensure that our estimates were
representative of the broader population, and cluster robust prediction
using cluster robust standard errors im \texttt{ggeffects}
(\citeproc{ref-ggeffects_2018}{Ludecke 2018}). Again we used sample
weights to adjust for any sampling biases and ensure that the analyses
produced estimates that generalise to the New Zealand adult population.
We graph the predicted means at confidence intervals using
\texttt{ggeffects}(\citeproc{ref-ggeffects_2018}{Ludecke 2018}). Tables
were created using \texttt{tinytable}
(\citeproc{ref-tinytable_2024}{Arel-Bundock 2024}); \texttt{ggplot2}
(\citeproc{ref-ggplot2_2016}{Wickham 2016}); and the \texttt{margot}
package (\citeproc{ref-margot2024}{Bulbulia 2024}).

Note than in the following we refer to results by New Zealand Attitudes
and Values Study waves, where each wave starts in October and continues
through the end of September the following year. As such, when we refer
to wave 2022, we mean the year from October 2022 through October 2023.

\subsection{Results}\label{results}

\subsubsection{Study 1: Bias in Attrition From Mistrust in Science and
Scientists}\label{study-1-bias-in-attrition-from-mistrust-in-science-and-scientists}

\paragraph{Trust Scientists: Sample Means in Retained
Sample}\label{trust-scientists-sample-means-in-retained-sample}

Figure~\ref{fig-hist-outcomes} presents histograms of trust responses
for science and scientists over time in the observed sample. As evident
in the graphs, there is increasing average trust over time, with a large
boost in trust evident in wave 2020. This boost coincides with the
initially popular New Zealand Covid-19 pandemic response
(\citeproc{ref-sibley2020a}{Sibley \emph{et al.} 2020}). In the retained
sample, there is further growth in for trust in science, and stability
in trust in scientists, following an initial boost.

\newpage{}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-hist-outcomes-1.pdf}}

}

\caption{\label{fig-hist-outcomes}}

\end{figure}%

\begin{table}

\caption{\label{tbl-sample-means}Retained sample average response}

\centering{

\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]},
cell{2}{1}={r=4,}{valign=h,cmd=\bfseries,},
cell{6}{1}={r=4,}{valign=h,cmd=\bfseries,},
column{1}={halign=l,},
column{2}={halign=l,},
column{3}={halign=l,},
column{4}={halign=l,},
}                     %% tabularray inner close
\toprule
Response & Year & mean & missing \\ \midrule %% TinyTableHeader
Trust Science & 2019 & 5.56 &    563 \\
Trust Science & 2020 & 5.8 &  9,632 \\
Trust Science & 2021 & 5.84 & 15,111 \\
Trust Science & 2022 & 5.84 & 18,221 \\
Trust Scientists & 2019 & 5.3 &  1,257 \\
Trust Scientists & 2020 & 5.55 & 10,172 \\
Trust Scientists & 2021 & 5.56 & 15,519 \\
Trust Scientists & 2022 & 5.55 & 18,948 \\
\bottomrule
\end{tblr}

}

\end{table}%

Table~\ref{tbl-sample-means} presents sample average responses for trust
in science over time. Between 2019 and 2022, the average trust levels in
both science and scientists suggests a gradient of increase. For Trust
in Science, the average score rose from 5.56 in wave 2019 to 5.84 by
2021, maintaining the same level through 2022. This indicates a steady
improvement in trust over the period in the retained sample.

For Trust in Scientists, the average response increased from 5.30 in
wave 2019 to 5.55 in wave 2020 and remained stable through waves 2021
and 2022.

However, number of respondents with unknown trust status increased
substantially over the years for both trust measures. For Trust in
Science, the count rose from 563 in wave 2019 to 18,221 in wave 2022.
Similarly, for Trust in Scientists, the unknown category grew from 1,257
in wave 2019 to 18,948 in wave 2022.

Hence, the sample data reveals both a positive trend in average trust
levels alongside a notable rise in the number of unknown responses over
the period. Of course, attrition is to be expected in a panel study.
However, we must be cautious when naively interpreting these data
because mistrust in science may be -- and credibly is -- systematically
related to panel attrition and non-response.

\paragraph{Trust Scientists Categorical Responses in Retained
Sample}\label{trust-scientists-categorical-responses-in-retained-sample}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2323}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0808}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1616}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1616}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1616}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1616}}@{}}
\caption{Retained sample proportions classified as low, medium, or
high}\label{tbl-sample-cat}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Trust Science} & low & 3434 (8.2\%) & 2465 (7.5\%) & 2012
(7.3\%) & 1740 (7.1\%) \\
& med & 13210 (31.4\%) & 7855 (23.8\%) & 6223 (22.6\%) & 5720
(23.4\%) \\
& high & 25474 (60.5\%) & 22729 (68.8\%) & 19335 (70.1\%) & 17000
(69.5\%) \\
\textbf{Trust Scientists} & low & 4797 (11.6\%) & 2818 (8.7\%) & 2477
(9.1\%) & 1910 (8.0\%) \\
& med & 14161 (34.2\%) & 9385 (28.9\%) & 7448 (27.4\%) & 7107
(29.9\%) \\
& high & 22466 (54.2\%) & 20306 (62.5\%) & 17237 (63.5\%) & 14716
(62.0\%) \\
\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-alluv-science-sample-1.pdf}}

}

\caption{\label{fig-alluv-science-sample}Alluvial plot suggests
increasing flow of trust in scientists for the retained sample.}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-alluv-scientists-sample-1.pdf}}

}

\caption{\label{fig-alluv-scientists-sample}Alluvial plot suggests
increasing flow of trust in science for the retained sample.}

\end{figure}%

Table~\ref{tbl-sample-cat} summaries responses by low (1-3), medium
(4,5) and high (6,7) levels of trust in science and in scientists as
estimated using multiple imputation for the full 2019 cohort.

For trust in science, the proportion of respondents reporting low trust
declined slightly from 8.2\% (3,434 respondents) in wave 2019 to 7.1\%
(1,740 respondents) in 2022. The medium trust category also saw a
decrease, dropping from 31.4\% (13,210 respondents) in wave 2019 to
23.4\% (5,720 respondents) in 2022. Conversely, the proportion of
respondents reporting high trust in science increased from 60.5\%
(25,474 respondents) in wave 2019 to 69.5\% (17,000 respondents) in
2022, peaking at 70.1\% (19,335 respondents) in 2021. The most
significant rise in high trust occurred between 2019 and 2020, after
which the levels remained relatively stable.
Figure~\ref{fig-alluv-science-sample} is an alluvial graph that
illustrates this upward shift in trust in science.

For trust in scientists, a similar pattern emerged. Low trust decreased
from 11.6\% (4,797 respondents) in wave 2019 to 8.0\% (1,910
respondents) in 2022. Medium trust declined from 34.2\% (14,161
respondents) in wave 2019 to 29.9\% (7,107 respondents) in 2022. High
trust in scientists increased from 54.2\% (22,466 respondents) in wave
2019 to 62.0\% (14,716 respondents) in 2022, with the largest growth
occurring between 2019 and 2020.
Figure~\ref{fig-alluv-scientists-sample} is an alluvial graph that
demonstrates this upward trend in trust in scientists.

Overall, these findings suggest that in the observed New Zealand
Attitudes and Values sample---that is, the portion of the 2019 cohort
that remained in the study and responded to trust in science
items---there was a noticeable shift towards higher levels of trust in
both science and scientists over time. This shift is characterised by
declines in low and medium trust and corresponding increases in high
trust, with the most pronounced changes observed between 2019 and 2020.

However, if those with low levels of trust in science or scientists are
more likely to abandon the panel study, then these observed responses
may overstate trust in science for the 2019 cohort. Hence, although the
data suggest a positive trend in average trust levels, an increasing
number of unknown responses implies potential bias in inferences about
the target population. That is, if we suppose, credibly, that those who
become mistrusting of science are more likely to drop out of a
scientific study, the picture of growth in trust may be overly positive.

\subsubsection{Multiply Imputed Full Cohort Means in Full 2019
Cohort}\label{multiply-imputed-full-cohort-means-in-full-2019-cohort}

\begin{table}

\caption{\label{tbl-sample-means-imp}Imputed average responses for the
full 2019 cohort}

\centering{

\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]Q[]},
cell{2}{1}={r=4,}{valign=h,cmd=\bfseries,},
cell{6}{1}={r=4,}{valign=h,cmd=\bfseries,},
column{1}={halign=l,},
column{2}={halign=l,},
column{3}={halign=l,},
column{4}={halign=l,},
column{5}={halign=l,},
column{6}={halign=l,},
}                     %% tabularray inner close
\toprule
Response & wave & estimate & se & lower & upper \\ \midrule %% TinyTableHeader
Trust Science & 2019 & 5.56 & 0.00698 & 5.54 & 5.57 \\
Trust Science & 2020 & 5.68 & 0.00706 & 5.67 & 5.7 \\
Trust Science & 2021 & 5.64 & 0.00704 & 5.63 & 5.66 \\
Trust Science & 2022 & 5.61 & 0.00712 & 5.59 & 5.62 \\
Trust Scientists & 2019 & 5.28 & 0.00727 & 5.27 & 5.3 \\
Trust Scientists & 2020 & 5.42 & 0.00709 & 5.41 & 5.44 \\
Trust Scientists & 2021 & 5.37 & 0.00727 & 5.36 & 5.39 \\
Trust Scientists & 2022 & 5.32 & 0.00715 & 5.31 & 5.34 \\
\bottomrule
\end{tblr}

}

\end{table}%

Table~\ref{tbl-sample-means-imp} presents averages pooled over the
mutiply imputed data. For Trust in Science, the imputed average slightly
increases from 5.56 in wave 2019 to 5.68 in wave 2020 and then declined
gradually to 5.64 in 2021 and 5.61 in wave 2022.

For Trust in Scientists, the average starts at 5.28 in wave 2019 rising
to to 5.42 in wave 2020, but steadily decreases to 5.37 in 2021 and
further to 5.32 by wave 2022. These patterns suggest that initial
improvements in average trust levels following the New Zealand Pandemic
response in wave 2020 were followed by a slight decrease over the
four-year period. Notably the pattern evident in the imputed dataset
differs markedly from the pattern of increasing growth evident for the
observed cohort, which suggests steady growth in trust, both for science
and scientists.

\subsubsection{Multiply Imputed Full Cohort Categorical
Responses}\label{multiply-imputed-full-cohort-categorical-responses}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-alluv-science-imp-1.pdf}}

}

\caption{\label{fig-alluv-science-imp}Alluvial plot suggests declines in
trust in science for the imputed cohort.}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-alluv-scientists-imp-1.pdf}}

}

\caption{\label{fig-alluv-scientists-imp}Alluvial plot suggests declines
in trust in scientists for the imputed cohort}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2830}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0755}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1509}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1509}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1509}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1509}}@{}}
\caption{Cohort proportions classified as low, medium, or high
(imputed)}\label{tbl-sample-cat-imp}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Response
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
2022
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Trust Science Factor} & low & 3523 (8.3\%) & 3782 (8.9\%) & 4003
(9.4\%) & 4163 (9.8\%) \\
& med & 13446 (31.5\%) & 11329 (26.5\%) & 11624 (27.2\%) & 12184
(28.5\%) \\
& high & 25712 (60.2\%) & 27570 (64.6\%) & 27054 (63.4\%) & 26334
(61.7\%) \\
\textbf{Trust Scientists Factor} & low & 5056 (11.8\%) & 4632 (10.9\%) &
5180 (12.1\%) & 5224 (12.2\%) \\
& med & 14660 (34.3\%) & 13279 (31.1\%) & 13345 (31.3\%) & 14498
(34.0\%) \\
& high & 22965 (53.8\%) & 24770 (58.0\%) & 24156 (56.6\%) & 22959
(53.8\%) \\
\end{longtable}

Table~\ref{tbl-sample-cat-imp} displays the distribution of responses
for Trust in Science and Trust in Scientists within pooling over the
tend multiply imputed datasets.

For the Trust Science Factor, the proportion of respondents reporting
low trust increased slightly from 8.3\% (3,523 respondents) in wave 2019
to 9.8\% (4,163 respondents) in 2022. Medium trust saw a decrease from
31.5\% (13,446 respondents) in wave 2019 to 28.5\% (12,184 respondents)
in 2022. High trust fluctuated over the years, increasing from 60.2\%
(25,712 respondents) in wave 2019 to 64.6\% (27,570 respondents) in wave
2020, before declining to 61.7\% (26,334 respondents) in 2022. This
trend indicates that while there was initial growth in high trust
between 2019 and 2020, this was not sustained, leading to a slight
decline in subsequent years. Figure~\ref{fig-alluv-science-imp} presents
an increasingly polarising trend for trust in science in the full wave
2019 cohort.

For the Trust Scientists Factor, low trust remained relatively stable,
starting at 11.8\% (5,056 respondents) in wave 2019 and ending at 12.2\%
(5,224 respondents) in 2022. Medium trust showed a minor decline
initially, from 34.3\% (14,660 respondents) in wave 2019 to 31.1\%
(13,279 respondents) in wave 2020, before returning to 34.0\% (14,498
respondents) in wave 2022. High trust increased from 53.8\% (22,965
respondents) in wave 2019 to 58.0\% (24,770 respondents) in wave 2020
but fell back to 53.8\% (22,959 respondents) in wave 2022, suggesting an
initial rise in trust levels that was not sustained in the long term.
Figure~\ref{fig-alluv-science-imp} presents an increasingly polarising
trend for trust in science among the full wave 2019 cohort

To quantitatively evaluate patterns of stability and change for the
population, we next report statistical models that employ all ten
multiply imputed datasets. We emphasise that purposes are descriptive
and exploratory, we do not test specific hypothesis, or address causal
theories.

\subsection{Study 2: Change in Average Trust in Science years 2019-2023
(waves
2019-2022)}\label{study-2-change-in-average-trust-in-science-years-2019-2023-waves-2019-2022}

\subsubsection{Study 2a: Average Trust in
Science}\label{study-2a-average-trust-in-science}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted population average trust in
science.}\label{tbl-marginal-gee-science}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & 5.52 & 5.38, 5.65 \\
2020 & 5.60 & 5.46, 5.74 \\
2021 & 5.58 & 5.44, 5.71 \\
2022 & 5.54 & 5.40, 5.68 \\
\end{longtable}

Table~\ref{tbl-marginal-gee-science} presents the predicted responses
for trust in science from 2019 to 2022. The highest predicted trust
level was observed in wave 2020 (5.60; 95\% CI: 5.46, 5.74), followed by
slight decreases in subsequent years.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted population average trust in
science.}\label{tbl-marginal-gee-scietists}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & 5.29 & 5.16, 5.43 \\
2020 & 5.40 & 5.26, 5.53 \\
2021 & 5.35 & 5.21, 5.49 \\
2022 & 5.29 & 5.15, 5.43 \\
\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-marginal-gee-1.pdf}}

}

\caption{\label{fig-marginal-gee}}

\end{figure}%

Table~\ref{tbl-marginal-gee-scietists} presents the predicted responses
for trust in scientists from 2019 to 2022. Again highest predicted value
was recorded in wave 2020 (5.40; 95\% CI: 5.26, 5.53), with minor
declines in 2021 and 2022.

Figure~\ref{fig-marginal-gee} graphs both results: (A) average trust in
science and (B) average trust in scientists, over time. And indicated in
the graph, there is considerable proportions of the population above and
below these average responses.

\subsubsection{Study 2b: Average Trust in Science by
Ethnicity}\label{study-2b-average-trust-in-science-by-ethnicity}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values for trust in science by
ethnicity.}\label{tbl-marginal-gee-science-eth}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: euro} \\
2019 & 5.65 & 5.54, 5.75 \\
2020 & 5.75 & 5.64, 5.86 \\
2021 & 5.69 & 5.58, 5.80 \\
2022 & 5.67 & 5.56, 5.78 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: maori} \\
2019 & 5.34 & 4.86, 5.82 \\
2020 & 5.39 & 4.89, 5.89 \\
2021 & 5.44 & 4.98, 5.91 \\
2022 & 5.31 & 4.82, 5.79 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: pacific} \\
2019 & 5.30 & 4.43, 6.16 \\
2020 & 5.22 & 4.27, 6.17 \\
2021 & 5.33 & 4.48, 6.19 \\
2022 & 5.28 & 4.34, 6.21 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: asian} \\
2019 & 5.21 & 4.67, 5.74 \\
2020 & 5.33 & 4.81, 5.85 \\
2021 & 5.30 & 4.77, 5.82 \\
2022 & 5.31 & 4.78, 5.85 \\
\end{longtable}

Table~\ref{tbl-marginal-gee-science-eth} shows the predicted responses
for trust in science over time, broken down by ethnicity. The results
indicate that the population identifying as European consistently
reported higher predicted trust levels compared to other ethnic groups,
with the peak in wave 2020 (\(5.75\), 95\% CI: \(5.64\), \(5.86\)).
Trust levels among Māori, Pacific, and Asian peoples were generally
lower and showed minor variations across the years. Māori respondents
showed predicted values ranging from \(5.34\) in wave 2019 to \(5.31\)
in 2022. The Pacific population reported fluctuating but lower trust
levels, peaking at \(5.33\) in 2021. Asians displayed modest increases,
peaking in wave 2020 at \(5.33\) (95\% CI: \(4.81\), \(5.85\)).

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of trust in scientists by
ethnicity.}\label{tbl-marginal-gee-scietists-eth}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: euro} \\
2019 & 5.39 & 5.28, 5.50 \\
2020 & 5.50 & 5.39, 5.61 \\
2021 & 5.43 & 5.31, 5.54 \\
2022 & 5.38 & 5.27, 5.49 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: maori} \\
2019 & 5.06 & 4.56, 5.56 \\
2020 & 5.19 & 4.72, 5.66 \\
2021 & 5.19 & 4.70, 5.68 \\
2022 & 5.08 & 4.59, 5.58 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: pacific} \\
2019 & 5.07 & 4.12, 6.01 \\
2020 & 5.03 & 4.10, 5.96 \\
2021 & 5.10 & 4.15, 6.05 \\
2022 & 4.95 & 4.00, 5.91 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
eth\_cat: asian} \\
2019 & 5.19 & 4.70, 5.68 \\
2020 & 5.29 & 4.79, 5.79 \\
2021 & 5.28 & 4.78, 5.79 \\
2022 & 5.20 & 4.69, 5.71 \\
\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-combo_eth_graph_gee-1.pdf}}

}

\caption{\label{fig-combo_eth_graph_gee}}

\end{figure}%

Table~\ref{tbl-marginal-gee-scietists-eth} presents the predicted values
for trust in scientists by ethnicity. Europeans again had the highest
predicted values across the time frame, peaking in wave 2020 at \(5.50\)
(95\% CI: \(5.39\), \(5.61\)). The predicted trust levels for Māori
ranged from \(5.06\) in wave 2019 to \(5.08\) in 2022, with slight
increases observed in wave 2020 and 2021. Pacific peoples showed more
variation, with the highest trust reported in 2021 at \(5.10\), while
the Asian population expressed peak trust in wave 2020 at \(5.29\).

Figure~\ref{fig-combo_eth_graph_gee} graphs the results of trust in
science and trust in scientists by ethnicity. These analyses reveal
ethnic differences, with Europeans showing consistently higher levels
compared to other groups. Again, perhaps the most striking feature is
that there is considerable proportions of the population above and below
these average responses with Ethnicities.

\subsubsection{Study 2c: Average Trust in Science by Binary
Gender}\label{study-2c-average-trust-in-science-by-binary-gender}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of trust\_science by gender
(binary)}\label{tbl-marginal-gee-science-male}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
male: not male} \\
2019 & 5.47 & 5.31, 5.64 \\
2020 & 5.60 & 5.42, 5.77 \\
2021 & 5.60 & 5.43, 5.77 \\
2022 & 5.54 & 5.38, 5.71 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
male: male} \\
2019 & 5.57 & 5.34, 5.79 \\
2020 & 5.61 & 5.38, 5.84 \\
2021 & 5.55 & 5.33, 5.77 \\
2022 & 5.54 & 5.30, 5.77 \\
\end{longtable}

Table~\ref{tbl-marginal-gee-science-male} presents predicted trust in
science over time, disaggregated by gender. Predicted trust levels for
those not identifying as male were generally stable, starting at
\(5.47\) (95\% CI: \(5.31\), \(5.64\)) in wave 2019 and peaking in wave
2020 and 2021 at \(5.60\). By wave 2022, the predicted trust level
slightly declined to \(5.54\) (95\% CI: \(5.38\), \(5.71\)).

For the population identifying as male, predicted trust started at
\(5.57\) (95\% CI: \(5.34\), \(5.79\)) in wave 2019 and showed a peak in
wave 2020 at \(5.61\) (95\% CI: \(5.38\), \(5.84\)). The levels remained
relatively stable through 2021 and 2022, with values of \(5.55\) and
\(5.54\) respectively.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of trust in scientists by gender
(binary)}\label{tbl-marginal-gee-scietists-male}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
male: not male} \\
2019 & 5.18 & 5.00, 5.36 \\
2020 & 5.35 & 5.18, 5.52 \\
2021 & 5.35 & 5.18, 5.52 \\
2022 & 5.28 & 5.11, 5.45 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
male: male} \\
2019 & 5.43 & 5.22, 5.64 \\
2020 & 5.45 & 5.23, 5.66 \\
2021 & 5.36 & 5.13, 5.59 \\
2022 & 5.29 & 5.06, 5.52 \\
\end{longtable}

Table~\ref{tbl-marginal-gee-scietists-male} presents the predicted
values for trust in scientists from 2019 to 2022, disaggregated by
gender (male and not male).

For the population identifying as not male, in wave 2019, the predicted
trust in scientists was \(5.18\) (95\% CI: \(5.00\), \(5.36\)), This
value increased to \(5.35\) (95\% CI: \(5.18\), \(5.52\)) in wave 2020
and remained stable through 2021. By wave 2022, predicted trust
decreased slightly to \(5.28\) (95\% CI: \(5.11\), \(5.45\)).

For the population identifying as male: predicted trust in scientists
was higher in wave 2019 at \(5.43\) (95\% CI: \(5.22\), \(5.64\)). This
value increased to \(5.45\) (95\% CI: \(5.23\), \(5.66\)) in wave 2020,
slightly declining to \(5.36\) (95\% CI: \(5.13\), \(5.59\)) in 2021. By
wave 2022, predicted trust continued to decrease to \(5.29\) (95\% CI:
\(5.06\), \(5.52\)).

Overall results suggest that predicted average trust levels over time
were mostly similar between genders, with evidence of converging means
over time.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-combo_male_graph_gee-1.pdf}}

}

\caption{\label{fig-combo_male_graph_gee}}

\end{figure}%

Figure~\ref{fig-combo_male_graph_gee} graphs these both. Again, we find
considerable proportions in these populations above and below the
average responses.

\subsubsection{Study 2c: Average Trust in Science by Political
Conservativism}\label{study-2c-average-trust-in-science-by-political-conservativism}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of trust\_science by political conservativism
(standard
deviations)}\label{tbl-marginal-gee-science-pols}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: -1} \\
2019 & 5.89 & 5.72, 6.07 \\
2020 & 5.93 & 5.75, 6.11 \\
2021 & 5.88 & 5.70, 6.06 \\
2022 & 5.85 & 5.66, 6.04 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: 0} \\
2019 & 5.52 & 5.38, 5.65 \\
2020 & 5.58 & 5.44, 5.71 \\
2021 & 5.57 & 5.43, 5.70 \\
2022 & 5.55 & 5.41, 5.69 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: 1} \\
2019 & 5.14 & 4.93, 5.34 \\
2020 & 5.22 & 5.01, 5.44 \\
2021 & 5.25 & 5.05, 5.45 \\
2022 & 5.25 & 5.05, 5.45 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: 2} \\
2019 & 4.76 & 4.43, 5.08 \\
2020 & 4.87 & 4.53, 5.20 \\
2021 & 4.94 & 4.62, 5.25 \\
2022 & 4.95 & 4.63, 5.27 \\
\end{longtable}

Table~\ref{tbl-marginal-gee-science-pols} presents the predicted trust
in science across different levels of political orientation, expressed
in standard deviation units (SD). The population with lower political
conservatism scores (\(-1\) SD) consistently reported the highest
predicted trust levels, starting at \(5.89\) (95\% CI: \(5.72\),
\(6.07\)) in wave 2019, peaking at \(5.93\) in wave 2020, and slightly
declining to \(5.85\) (95\% CI: \(5.66\), \(6.04\)) by wave 2022.

For the population with average political conservatism (\(0\) SD),
predicted trust levels ranged from \(5.52\) in wave 2019 to \(5.55\) in
2022, showing a small peak in wave 2020 at \(5.58\) (95\% CI: \(5.44\),
\(5.71\)). The population with higher political conservatism (\(1\) SD)
started with lower predicted trust values, beginning at \(5.14\) (95\%
CI: \(4.93\), \(5.34\)) in wave 2019 and reaching \(5.25\) (95\% CI:
\(5.05\), \(5.45\)) by wave 2022.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of trust in scientists by political
conservativism (standard deviation
units)}\label{tbl-marginal-gee-scietists-pols}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: -1} \\
2019 & 5.67 & 5.50, 5.84 \\
2020 & 5.73 & 5.55, 5.91 \\
2021 & 5.66 & 5.46, 5.86 \\
2022 & 5.62 & 5.43, 5.81 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: 0} \\
2019 & 5.29 & 5.16, 5.43 \\
2020 & 5.37 & 5.23, 5.50 \\
2021 & 5.34 & 5.21, 5.48 \\
2022 & 5.30 & 5.16, 5.43 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: 1} \\
2019 & 4.91 & 4.72, 5.11 \\
2020 & 5.01 & 4.80, 5.22 \\
2021 & 5.03 & 4.82, 5.23 \\
2022 & 4.98 & 4.78, 5.18 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
political\_conservative\_z: 2} \\
2019 & 4.54 & 4.23, 4.84 \\
2020 & 4.65 & 4.32, 4.98 \\
2021 & 4.71 & 4.38, 5.03 \\
2022 & 4.66 & 4.35, 4.98 \\
\end{longtable}

Table~\ref{tbl-marginal-gee-scietists-pols} presents the predicted trust
in scientists over time across different levels of political orientation
(in standard deviation units). The population with lower conservatism
scores (\(-1\) SD) reported the highest predicted trust levels, starting
at \(5.67\) (95\% CI: \(5.50\), \(5.84\)) in wave 2019 and peaking at
\(5.73\) (95\% CI: \(5.55\), \(5.91\)) in wave 2020. By wave 2022, trust
declined slightly to \(5.62\) (95\% CI: \(5.43\), \(5.81\)).

For those with average political orientation (\(0\) SD), predicted trust
values were lower, starting at \(5.29\) (95\% CI: \(5.16\), \(5.43\)) in
wave 2019 and peaking in wave 2020 at \(5.37\) (95\% CI: \(5.23\),
\(5.50\)). By wave 2022, trust declined to \(5.30\) (95\% CI: \(5.16\),
\(5.43\)).

Those with higher conservatism (\(1\) SD) started with even lower
predicted trust levels, beginning at \(4.91\) (95\% CI: \(4.72\),
\(5.11\)) in wave 2019 and peaking modestly at \(5.03\) (95\% CI:
\(4.82\), \(5.23\)) in 2021. By wave 2022, trust levels fell to \(4.98\)
(95\% CI: \(4.78\), \(5.18\)).

The population with the highest conservatism scores (\(2\) SD) had the
lowest trust in scientists, starting at \(4.54\) (95\% CI: \(4.23\),
\(4.84\)) in wave 2019. Their trust peaked in 2021 at \(4.71\) (95\% CI:
\(4.38\), \(5.03\)) before declining again to \(4.66\) (95\% CI:
\(4.35\), \(4.98\)) in wave 2022.

These results demonstrate a clear pattern where the population with
lower conservatism show consistently higher predicted trust in
scientists, while those with higher conservatism have lower trust
levels, with considerable stability overtime, albeit with increasing
trust on the high end of the political conservativism spectrum.

Note we caution against any causal interpretation, as those already
trusting of science or of scientists might have become increasingly
conservative, a reminder that even in longitudinal data correlation is
not causation.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-combo_pols_graph_gee-1.pdf}}

}

\caption{\label{fig-combo_pols_graph_gee}}

\end{figure}%

Figure~\ref{fig-combo_pols_graph_gee} graphs again presents predicted
trust in science trends for the population by political orientation.
Despite a broad patter of stability in average responses, we again find
considerable proportions in these populations above and below the
average responses.

\subsection{Study 3: Proportional Change in High, Medium, and Low Trust
years 2019-2023 (waves
2019-2022)}\label{study-3-proportional-change-in-high-medium-and-low-trust-years-2019-2023-waves-2019-2022}

\subsubsection{Study 3a: Categorical Trust in
Science}\label{study-3a-categorical-trust-in-science}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted population responses for categorical trust in science
(marginal).}\label{tbl-marginal-science}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
trust\_science\_factor: low} \\
2019 & 0.09 & 0.09, 0.09 \\
2020 & 0.10 & 0.10, 0.10 \\
2021 & 0.10 & 0.10, 0.10 \\
2022 & 0.11 & 0.11, 0.11 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
trust\_science\_factor: med} \\
2019 & 0.32 & 0.31, 0.33 \\
2020 & 0.28 & 0.27, 0.28 \\
2021 & 0.29 & 0.28, 0.29 \\
2022 & 0.29 & 0.29, 0.30 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
trust\_science\_factor: high} \\
2019 & 0.59 & 0.58, 0.60 \\
2020 & 0.62 & 0.61, 0.63 \\
2021 & 0.61 & 0.60, 0.62 \\
2022 & 0.60 & 0.59, 0.61 \\
\end{longtable}

Table~\ref{tbl-marginal-science} presents predicted population responses
for three categorical levels of trust in science---low, medium, and
high---across the years 2019 to 2023 (wave 2022).

in wave 2019, those with low trust reported an average predicted
probability of \(0.09\) (95\% CI: \(0.09\), \(0.09\)), with a slight
increase to \(0.11\) (95\% CI: \(0.11\), \(0.11\)) by wave 2022. This
indicates a stable, but gradually increasing, proportion of the
population maintaining low trust in science.

The medium trust group began with a predicted probability of \(0.32\)
(95\% CI: \(0.31\), \(0.33\)) in wave 2019, dropped to \(0.28\) in wave
2020 (95\% CI: \(0.27\), \(0.28\)), and remained relatively stable
through wave 2022 at \(0.29\) (95\% CI: \(0.29\), \(0.30\)). This
suggests that the proportion of individuals holding medium trust
initially decreased but stabilised in subsequent years.

For the high trust category, the highest predicted response was observed
in wave 2020 at \(0.62\) (95\% CI: \(0.61\), \(0.63\)), up from \(0.59\)
(95\% CI: \(0.58\), \(0.60\)) in wave 2019. However, the proportion
showed a slight decline by wave 2022, returning to \(0.60\) (95\% CI:
\(0.59\), \(0.61\)). This pattern may reflect transient shifts in public
confidence, potentially related to New Zealand's Covid-19 pandemic
response and its aftermath.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted population responses for categorical trust in
scientists (marginal).}\label{tbl-marginal-scietists}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
trust\_scientists\_factor: low} \\
2019 & 0.12 & 0.12, 0.12 \\
2020 & 0.11 & 0.11, 0.12 \\
2021 & 0.12 & 0.12, 0.13 \\
2022 & 0.13 & 0.13, 0.13 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
trust\_scientists\_factor: med} \\
2019 & 0.34 & 0.33, 0.35 \\
2020 & 0.32 & 0.31, 0.32 \\
2021 & 0.32 & 0.31, 0.33 \\
2022 & 0.35 & 0.34, 0.35 \\
\multicolumn{3}{@{}>{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4444} + 4\tabcolsep}@{}}{%
trust\_scientists\_factor: high} \\
2019 & 0.54 & 0.53, 0.55 \\
2020 & 0.57 & 0.56, 0.58 \\
2021 & 0.56 & 0.55, 0.56 \\
2022 & 0.53 & 0.52, 0.53 \\
\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-marginal-1.pdf}}

}

\caption{\label{fig-marginal}}

\end{figure}%

Table~\ref{tbl-marginal-scietists} presents the predicted population
responses for categorical levels of trust in scientists from 2019 to
2022.

For those with low trust in scientists, the predicted probability began
at \(0.12\) (95\% CI: \(0.12\), \(0.12\)) in wave 2019 and decreased to
\(0.11\) (95\% CI: \(0.11\), \(0.12\)) in wave 2020. This was followed
by a slight increase in subsequent years, reaching \(0.13\) (95\% CI:
\(0.13\), \(0.13\)) in 2022. These results indicate a minor, yet
consistent, rise in the proportion of the population with low trust over
this period.

The medium trust category showed initial stability, with a predicted
probability of \(0.34\) (95\% CI: \(0.33\), \(0.35\)) in wave 2019,
which dropped to \(0.32\) (95\% CI: \(0.31\), \(0.32\)) in wave 2020 and
remained relatively unchanged in 2021. By wave 2022, the probability
rose again to \(0.35\) (95\% CI: \(0.34\), \(0.35\)), indicating a
return to wave 2019 levels.

In contrast, the high trust group exhibited a different pattern.
Starting at \(0.54\) (95\% CI: \(0.53\), \(0.55\)) in wave 2019, the
predicted probability increased to a peak of \(0.57\) (95\% CI:
\(0.56\), \(0.58\)) in wave 2020. Following this peak, a gradual decline
was observed, with trust levels at \(0.56\) (95\% CI: \(0.55\),
\(0.56\)) in 2021 and \(0.53\) (95\% CI: \(0.52\), \(0.53\)) in wave
2022.

These data suggest that while the high trust group reached a temporary
peak in wave 2020, the overall trend showed slight declines in high
trust and small increases in low trust over time. The medium trust
category rebounded to its original level by wave 2022, showing more
fluctuation within the period.

As with previous findings, these observations are correlational, and
should be interpreted cautiously. Notably, the population of
conservatives and liberals was not consistent during this period. That
is, whereas some conservatives might have become more mistrusting
science, some liberals who were already trusting in science might have
become liberal. We cannot, from these observations speculate about
causation.

\subsubsection{Study 3b: Categorical Trust in Science by
Ethnicity}\label{study-3b-categorical-trust-in-science-by-ethnicity}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3194}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1389}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values for categorical trust in science by
ethnicity.}\label{tbl-science-eth}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_science\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
eth\_cat
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_science\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
eth\_cat
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & low & euro & 0.08 & 0.07, 0.08 \\
2020 & & & 0.08 & 0.08, 0.08 \\
2021 & & & 0.09 & 0.09, 0.09 \\
2022 & & & 0.09 & 0.09, 0.09 \\
2019 & & maori & 0.11 & 0.11, 0.12 \\
2020 & & & 0.13 & 0.13, 0.14 \\
2021 & & & 0.11 & 0.11, 0.12 \\
2022 & & & 0.15 & 0.14, 0.15 \\
2019 & & pacific & 0.11 & 0.10, 0.12 \\
2020 & & & 0.14 & 0.13, 0.15 \\
2021 & & & 0.12 & 0.12, 0.13 \\
2022 & & & 0.13 & 0.12, 0.14 \\
2019 & & asian & 0.13 & 0.12, 0.14 \\
2020 & & & 0.13 & 0.12, 0.13 \\
2021 & & & 0.14 & 0.13, 0.15 \\
2022 & & & 0.14 & 0.14, 0.15 \\
2019 & med & euro & 0.29 & 0.29, 0.30 \\
2020 & & & 0.25 & 0.25, 0.26 \\
2021 & & & 0.26 & 0.25, 0.27 \\
2022 & & & 0.28 & 0.27, 0.28 \\
2019 & & maori & 0.35 & 0.34, 0.37 \\
2020 & & & 0.30 & 0.29, 0.32 \\
2021 & & & 0.32 & 0.31, 0.34 \\
2022 & & & 0.32 & 0.31, 0.34 \\
2019 & & pacific & 0.38 & 0.35, 0.41 \\
2020 & & & 0.36 & 0.33, 0.39 \\
2021 & & & 0.35 & 0.32, 0.37 \\
2022 & & & 0.36 & 0.33, 0.39 \\
2019 & & asian & 0.37 & 0.36, 0.39 \\
2020 & & & 0.34 & 0.32, 0.36 \\
2021 & & & 0.33 & 0.32, 0.35 \\
2022 & & & 0.32 & 0.30, 0.33 \\
2019 & high & euro & 0.63 & 0.62, 0.64 \\
2020 & & & 0.67 & 0.66, 0.67 \\
2021 & & & 0.65 & 0.64, 0.66 \\
2022 & & & 0.64 & 0.63, 0.64 \\
2019 & & maori & 0.53 & 0.51, 0.55 \\
2020 & & & 0.56 & 0.55, 0.58 \\
2021 & & & 0.56 & 0.54, 0.58 \\
2022 & & & 0.53 & 0.51, 0.55 \\
2019 & & pacific & 0.51 & 0.47, 0.54 \\
2020 & & & 0.50 & 0.47, 0.53 \\
2021 & & & 0.53 & 0.50, 0.56 \\
2022 & & & 0.51 & 0.48, 0.54 \\
2019 & & asian & 0.50 & 0.48, 0.52 \\
2020 & & & 0.53 & 0.51, 0.55 \\
2021 & & & 0.53 & 0.51, 0.55 \\
2022 & & & 0.54 & 0.52, 0.56 \\
\end{longtable}

Table~\ref{tbl-science-eth} presents the predicted population responses
for categorical trust in science from 2019 to 2022, segmented by ethnic
populations (European, Māori, Pacific, and Asian).

For the low trust category:

The European population started with a predicted probability of \(0.08\)
(95\% CI: \(0.07\), \(0.08\)) in wave 2019. This value showed a slight
increase, reaching \(0.09\) (95\% CI: \(0.09\), \(0.09\)) by wave 2022.
The Māori population began with a higher predicted probability of
\(0.11\) (95\% CI: \(0.11\), \(0.12\)) in wave 2019, peaking at \(0.15\)
(95\% CI: \(0.14\), \(0.15\)) in wave 2022. The Pacific population
showed a similar trajectory, with a starting value of \(0.11\) (95\% CI:
\(0.10\), \(0.12\)) in wave 2019 and an increase to \(0.13\) (95\% CI:
\(0.12\), \(0.14\)) in wave 2022. The Asian population reported a higher
initial value of \(0.13\) (95\% CI: \(0.12\), \(0.14\)) in wave 2019,
remaining stable at \(0.14\) (95\% CI: \(0.14\), \(0.15\)) by wave 2022.

For the medium trust category:

The European population exhibited an initial predicted probability of
\(0.29\) (95\% CI: \(0.29\), \(0.30\)) in wave 2019. This value dipped
to \(0.25\) (95\% CI: \(0.25\), \(0.26\)) in wave 2020 before rebounding
to \(0.28\) (95\% CI: \(0.27\), \(0.28\)) by wave 2022. The Māori
population started at \(0.35\) (95\% CI: \(0.34\), \(0.37\)) in wave
2019 and showed a decrease to \(0.30\) (95\% CI: \(0.29\), \(0.32\)) in
wave 2020, stabilising at \(0.32\) (95\% CI: \(0.31\), \(0.34\)) by wave
2022. The Pacific population began with a higher probability of \(0.38\)
(95\% CI: \(0.35\), \(0.41\)) in wave 2019 and exhibited slight
fluctuations, ending at \(0.36\) (95\% CI: \(0.33\), \(0.39\)) in wave
2022. The Asian population commenced at \(0.37\) (95\% CI: \(0.36\),
\(0.39\)) in wave 2019 and gradually declined to \(0.32\) (95\% CI:
\(0.30\), \(0.33\)) by wave 2022.

In the high trust category:

The European population demonstrated an increase from \(0.63\) (95\% CI:
\(0.62\), \(0.64\)) in wave 2019 to a peak of \(0.67\) (95\% CI:
\(0.66\), \(0.67\)) in wave 2020, followed by a decline to \(0.64\)
(95\% CI: \(0.63\), \(0.64\)) in 2022. The Māori population began with a
predicted value of \(0.53\) (95\% CI: \(0.51\), \(0.55\)) in wave 2019,
peaking at \(0.56\) (95\% CI: \(0.55\), \(0.58\)) in wave 2020, and
returning to \(0.53\) (95\% CI: \(0.51\), \(0.55\)) by wave 2022. The
Pacific population started at \(0.51\) (95\% CI: \(0.47\), \(0.54\)) in
wave 2019, peaked at \(0.53\) (95\% CI: \(0.50\), \(0.56\)) in 2021, and
ended at \(0.51\) (95\% CI: \(0.48\), \(0.54\)) in 2022. The Asian
population displayed a consistent upward trend, starting at \(0.50\)
(95\% CI: \(0.48\), \(0.52\)) in wave 2019 and rising to \(0.54\) (95\%
CI: \(0.52\), \(0.56\)) by wave 2022.

These findings reveal different trends in trust across ethnic
populations, with notable peaks in trust in wave 2020, particularly for
the European and Māori populations.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3611}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1389}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of for categorical trust scientists by
ethnicity.}\label{tbl-marginal-scietists-eth}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_scientists\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
eth\_cat
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_scientists\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
eth\_cat
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & low & euro & 0.11 & 0.10, 0.11 \\
2020 & & & 0.10 & 0.10, 0.10 \\
2021 & & & 0.11 & 0.11, 0.12 \\
2022 & & & 0.11 & 0.11, 0.12 \\
2019 & & maori & 0.15 & 0.15, 0.16 \\
2020 & & & 0.14 & 0.13, 0.15 \\
2021 & & & 0.15 & 0.14, 0.16 \\
2022 & & & 0.17 & 0.16, 0.18 \\
2019 & & pacific & 0.14 & 0.13, 0.16 \\
2020 & & & 0.17 & 0.16, 0.19 \\
2021 & & & 0.17 & 0.16, 0.19 \\
2022 & & & 0.18 & 0.17, 0.20 \\
2019 & & asian & 0.13 & 0.12, 0.14 \\
2020 & & & 0.13 & 0.12, 0.13 \\
2021 & & & 0.13 & 0.12, 0.13 \\
2022 & & & 0.14 & 0.13, 0.14 \\
2019 & med & euro & 0.32 & 0.31, 0.33 \\
2020 & & & 0.29 & 0.29, 0.30 \\
2021 & & & 0.30 & 0.30, 0.31 \\
2022 & & & 0.33 & 0.32, 0.34 \\
2019 & & maori & 0.37 & 0.36, 0.39 \\
2020 & & & 0.36 & 0.35, 0.38 \\
2021 & & & 0.35 & 0.33, 0.37 \\
2022 & & & 0.37 & 0.35, 0.39 \\
2019 & & pacific & 0.39 & 0.36, 0.42 \\
2020 & & & 0.37 & 0.34, 0.40 \\
2021 & & & 0.34 & 0.31, 0.37 \\
2022 & & & 0.40 & 0.36, 0.43 \\
2019 & & asian & 0.37 & 0.36, 0.39 \\
2020 & & & 0.34 & 0.32, 0.36 \\
2021 & & & 0.35 & 0.34, 0.37 \\
2022 & & & 0.38 & 0.36, 0.40 \\
2019 & high & euro & 0.57 & 0.56, 0.58 \\
2020 & & & 0.61 & 0.60, 0.61 \\
2021 & & & 0.58 & 0.57, 0.59 \\
2022 & & & 0.56 & 0.55, 0.57 \\
2019 & & maori & 0.47 & 0.45, 0.49 \\
2020 & & & 0.49 & 0.48, 0.51 \\
2021 & & & 0.50 & 0.48, 0.52 \\
2022 & & & 0.46 & 0.44, 0.48 \\
2019 & & pacific & 0.47 & 0.44, 0.50 \\
2020 & & & 0.45 & 0.42, 0.49 \\
2021 & & & 0.49 & 0.46, 0.52 \\
2022 & & & 0.42 & 0.39, 0.46 \\
2019 & & asian & 0.50 & 0.48, 0.52 \\
2020 & & & 0.53 & 0.51, 0.55 \\
2021 & & & 0.52 & 0.50, 0.54 \\
2022 & & & 0.49 & 0.47, 0.50 \\
\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-combo_eth_graph-1.pdf}}

}

\caption{\label{fig-combo_eth_graph}}

\end{figure}%

Table~\ref{tbl-marginal-gee-scietists-eth} presents the predicted
population responses for categorical trust in scientists from 2019 to
2022, segmented by ethnic populations (European, Māori, Pacific, and
Asian).

For the low trust category:

The European population began at a predicted probability of \(0.11\)
(95\% CI: \(0.10\), \(0.11\)) in wave 2019, which decreased to \(0.10\)
(95\% CI: \(0.10\), \(0.10\)) in wave 2020 and returned to \(0.11\)
(95\% CI: \(0.11\), \(0.12\)) by wave 2022. The Māori population started
higher, at \(0.15\) (95\% CI: \(0.15\), \(0.16\)) in wave 2019, declined
to \(0.14\) (95\% CI: \(0.13\), \(0.15\)) in wave 2020, and increased to
\(0.17\) (95\% CI: \(0.16\), \(0.18\)) by wave 2022. The Pacific
population began at \(0.14\) (95\% CI: \(0.13\), \(0.16\)) in wave 2019
and rose to \(0.18\) (95\% CI: \(0.17\), \(0.20\)) by wave 2022. The
Asian population was stable over time, starting at \(0.13\) (95\% CI:
\(0.12\), \(0.14\)) in wave 2019 and slightly increasing to \(0.14\)
(95\% CI: \(0.13\), \(0.14\)) by wave 2022.

For the medium trust category:

The European population began at \(0.32\) (95\% CI: \(0.31\), \(0.33\))
in wave 2019, decreased to \(0.29\) (95\% CI: \(0.29\), \(0.30\)) in
wave 2020, and rose to \(0.33\) (95\% CI: \(0.32\), \(0.34\)) by wave
2022. The Māori population started at \(0.37\) (95\% CI: \(0.36\),
\(0.39\)) in wave 2019, remained stable through 2020 and 2021, and
returned to \(0.37\) (95\% CI: \(0.35\), \(0.39\)) by wave 2022. The
Pacific population had an initial value of \(0.39\) (95\% CI: \(0.36\),
\(0.42\)) in wave 2019 and fluctuated, reaching \(0.40\) (95\% CI:
\(0.36\), \(0.43\)) by wave 2022. The Asian population showed a slight
increase from \(0.37\) (95\% CI: \(0.36\), \(0.39\)) in wave 2019 to
\(0.38\) (95\% CI: \(0.36\), \(0.40\)) in wave 2022.

For the high trust category:

The European population's predicted probability increased from \(0.57\)
(95\% CI: \(0.56\), \(0.58\)) in wave 2019 to \(0.61\) (95\% CI:
\(0.60\), \(0.61\)) in wave 2020, before declining to \(0.56\) (95\% CI:
\(0.55\), \(0.57\)) in wave 2022. The Māori population showed an initial
predicted probability of \(0.47\) (95\% CI: \(0.45\), \(0.49\)) in wave
2019, increasing to \(0.50\) (95\% CI: \(0.48\), \(0.52\)) in 2021, and
then decreasing to \(0.46\) (95\% CI: \(0.44\), \(0.48\)) in 2022. The
Pacific population began at \(0.47\) (95\% CI: \(0.44\), \(0.50\)) in
wave 2019 and ended at \(0.42\) (95\% CI: \(0.39\), \(0.46\)) in 2022,
with a peak in 2021. The Asian population showed an upward trend,
starting at \(0.50\) (95\% CI: \(0.48\), \(0.52\)) in wave 2019 and
peaking at \(0.53\) (95\% CI: \(0.51\), \(0.55\)) in wave 2020 before a
decline to \(0.49\) (95\% CI: \(0.47\), \(0.50\)) in wave 2022.

These findings reveal varying trends in trust in scientists across
ethnic populations, with some populations exhibiting more pronounced
fluctuations than others. The European population showed the highest
increase in high trust during wave 2020, followed by a decline. The
Māori and Pacific populations displayed peaks and declines over the
period, while the Asian population were relatively stable, with
increasing in trust.

Figure~\ref{fig-combo_eth_graph} visually represents these results,
providing an overview of categorical trust in science and trust in
scientists by ethnicity.

\subsubsection{Study 3c: Categorical Trust in Science by Binary
Gender}\label{study-3c-categorical-trust-in-science-by-binary-gender}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3194}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1528}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of categorical trust in science by gender
(binary)}\label{tbl-marginal-science-male}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_science\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_science\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & low & not male & 0.09 & 0.09, 0.09 \\
2020 & & & 0.10 & 0.09, 0.10 \\
2021 & & & 0.10 & 0.09, 0.10 \\
2022 & & & 0.10 & 0.10, 0.11 \\
2019 & & male & 0.09 & 0.09, 0.09 \\
2020 & & & 0.10 & 0.10, 0.11 \\
2021 & & & 0.11 & 0.11, 0.11 \\
2022 & & & 0.11 & 0.11, 0.11 \\
2019 & med & not male & 0.34 & 0.33, 0.35 \\
2020 & & & 0.29 & 0.28, 0.30 \\
2021 & & & 0.29 & 0.28, 0.30 \\
2022 & & & 0.30 & 0.29, 0.31 \\
2019 & & male & 0.30 & 0.29, 0.31 \\
2020 & & & 0.27 & 0.26, 0.28 \\
2021 & & & 0.28 & 0.27, 0.29 \\
2022 & & & 0.29 & 0.28, 0.29 \\
2019 & high & not male & 0.57 & 0.56, 0.58 \\
2020 & & & 0.62 & 0.61, 0.63 \\
2021 & & & 0.61 & 0.60, 0.62 \\
2022 & & & 0.60 & 0.59, 0.61 \\
2019 & & male & 0.61 & 0.60, 0.62 \\
2020 & & & 0.63 & 0.62, 0.64 \\
2021 & & & 0.61 & 0.60, 0.62 \\
2022 & & & 0.60 & 0.59, 0.61 \\
\end{longtable}

Table~\ref{tbl-marginal-science-male} presents the predicted values for
categorical trust in science from 2019 to 2022, disaggregated by gender
(male and not male).

For the population identifying as not male, the predicted probability
for the low trust category started at \(0.09\) (95\% CI: \(0.09\),
\(0.09\)) in wave 2019 and increased to \(0.10\) (95\% CI: \(0.10\),
\(0.11\)) in wave 2022. For those identifying as male, the predicted
probability also began at \(0.09\) (95\% CI: \(0.09\), \(0.09\)) in wave
2019 and increased slightly to \(0.11\) (95\% CI: \(0.11\), \(0.11\)) by
wave 2022.

In the medium trust category, the not male population had a predicted
probability of \(0.34\) (95\% CI: \(0.33\), \(0.35\)) in wave 2019,
which decreased to \(0.29\) (95\% CI: \(0.28\), \(0.30\)) in wave 2020
and then increased to \(0.30\) (95\% CI: \(0.29\), \(0.31\)) by wave
2022. The male population began at a lower probability of \(0.30\) (95\%
CI: \(0.29\), \(0.31\)) in wave 2019 and showed a decline to \(0.27\)
(95\% CI: \(0.26\), \(0.28\)) in wave 2020, with a gradual increase to
\(0.29\) (95\% CI: \(0.28\), \(0.29\)) by wave 2022.

For the high trust category, the not male population started at \(0.57\)
(95\% CI: \(0.56\), \(0.58\)) in wave 2019 and peaked at \(0.62\) (95\%
CI: \(0.61\), \(0.63\)) in wave 2020, before declining to \(0.60\) (95\%
CI: \(0.59\), \(0.61\)) in wave 2022. The male population showed higher
initial trust, beginning at \(0.61\) (95\% CI: \(0.60\), \(0.62\)) in
wave 2019, peaking at \(0.63\) (95\% CI: \(0.62\), \(0.64\)) in wave
2020, and similarly declining to \(0.60\) (95\% CI: \(0.59\), \(0.61\))
by wave 2022.

These results indicate that both male and not male populations
experienced similar trends over time, with peaks in trust during wave
2020 followed by slight declines. The high trust category consistently
had the highest predicted probabilities for both populations and high
trust in science was more prevalent among those identifying as male
compared to those not identifying as male.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3611}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1528}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1806}}@{}}
\caption{Predicted values of trust in scientists by gender
(binary)}\label{tbl-marginal-scietists-male}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_scientists\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_scientists\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
male
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & low & not male & 0.13 & 0.13, 0.14 \\
2020 & & & 0.12 & 0.11, 0.12 \\
2021 & & & 0.12 & 0.12, 0.13 \\
2022 & & & 0.13 & 0.13, 0.13 \\
2019 & & male & 0.10 & 0.10, 0.10 \\
2020 & & & 0.11 & 0.11, 0.11 \\
2021 & & & 0.13 & 0.12, 0.13 \\
2022 & & & 0.13 & 0.13, 0.13 \\
2019 & med & not male & 0.36 & 0.35, 0.37 \\
2020 & & & 0.33 & 0.32, 0.34 \\
2021 & & & 0.32 & 0.32, 0.33 \\
2022 & & & 0.35 & 0.34, 0.36 \\
2019 & & male & 0.32 & 0.31, 0.33 \\
2020 & & & 0.30 & 0.29, 0.31 \\
2021 & & & 0.32 & 0.31, 0.32 \\
2022 & & & 0.34 & 0.33, 0.35 \\
2019 & high & not male & 0.51 & 0.50, 0.52 \\
2020 & & & 0.55 & 0.54, 0.56 \\
2021 & & & 0.55 & 0.54, 0.56 \\
2022 & & & 0.52 & 0.51, 0.53 \\
2019 & & male & 0.58 & 0.57, 0.59 \\
2020 & & & 0.59 & 0.58, 0.60 \\
2021 & & & 0.56 & 0.55, 0.57 \\
2022 & & & 0.53 & 0.52, 0.54 \\
\end{longtable}

Table~\ref{tbl-marginal-scietists-male} details the predicted trust in
scientists over time for male and not male population.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-combo_male_graph-1.pdf}}

}

\caption{\label{fig-combo_male_graph}}

\end{figure}%

Table~\ref{tbl-marginal-scietists-male} presents the predicted values of
trust in scientists from 2019 to 2022, disaggregated by gender (male and
not male).

For the low trust category, the population identifying as not male began
with a predicted probability of \(0.13\) (95\% CI: \(0.13\), \(0.14\))
in wave 2019, which slightly decreased to \(0.12\) (95\% CI: \(0.11\),
\(0.12\)) in wave 2020, before stabilising at \(0.13\) (95\% CI:
\(0.13\), \(0.13\)) by wave 2022. The male population started at a lower
predicted probability of \(0.10\) (95\% CI: \(0.10\), \(0.10\)) in wave
2019, which increased to \(0.13\) (95\% CI: \(0.13\), \(0.13\)) by wave
2022.

In the medium trust category, the not male population started with a
predicted probability of \(0.36\) (95\% CI: \(0.35\), \(0.37\)) in wave
2019, which decreased to \(0.33\) (95\% CI: \(0.32\), \(0.34\)) in wave
2020 and increased again to \(0.35\) (95\% CI: \(0.34\), \(0.36\)) by
wave 2022. The male population began at \(0.32\) (95\% CI: \(0.31\),
\(0.33\)) in wave 2019, saw a dip to \(0.30\) (95\% CI: \(0.29\),
\(0.31\)) in wave 2020, and ended at \(0.34\) (95\% CI: \(0.33\),
\(0.35\)) by wave 2022.

For the high trust category, the not male population had a predicted
probability of \(0.51\) (95\% CI: \(0.50\), \(0.52\)) in wave 2019,
which increased to \(0.55\) (95\% CI: \(0.54\), \(0.56\)) in wave 2020
and then decreased to \(0.52\) (95\% CI: \(0.51\), \(0.53\)) by wave
2022. The male population started higher at \(0.58\) (95\% CI: \(0.57\),
\(0.59\)) in wave 2019, peaking at \(0.59\) (95\% CI: \(0.58\),
\(0.60\)) in wave 2020, and declined to \(0.53\) (95\% CI: \(0.52\),
\(0.54\)) by wave 2022.

These data indicate that both male and not male populations experienced
similar trends, with a peak in high trust in wave 2020, followed by a
gradual decline. The male population consistently reported higher
predicted probabilities of high trust compared to the not male
population throughout the period, however in both categories responses
tended to become more similar over time.

Figure~\ref{fig-combo_male_graph} provides a visual representation of
these trends , both for categorical trust in science and trust in
scientists by binary gender.

\subsubsection{Study 3c: Categorical Trust in Science by Political
Conservativism}\label{study-3c-categorical-trust-in-science-by-political-conservativism}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0824}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2706}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3176}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1412}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1529}}@{}}
\caption{Predicted values of categorical trust in science by across the
range of political
conservativism.}\label{tbl-marginal-science-pols}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_science\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
political\_conservative\_z
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_science\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
political\_conservative\_z
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & low & -1 & 0.06 & 0.06, 0.06 \\
2020 & & & 0.07 & 0.06, 0.07 \\
2021 & & & 0.07 & 0.07, 0.07 \\
2022 & & & 0.07 & 0.07, 0.07 \\
2019 & & 0 & 0.09 & 0.09, 0.09 \\
2020 & & & 0.10 & 0.10, 0.10 \\
2021 & & & 0.10 & 0.10, 0.10 \\
2022 & & & 0.10 & 0.10, 0.10 \\
2019 & & 1 & 0.12 & 0.12, 0.13 \\
2020 & & & 0.14 & 0.13, 0.14 \\
2021 & & & 0.14 & 0.13, 0.14 \\
2022 & & & 0.14 & 0.14, 0.14 \\
2019 & & 2 & 0.16 & 0.15, 0.17 \\
2020 & & & 0.18 & 0.18, 0.19 \\
2021 & & & 0.18 & 0.17, 0.19 \\
2022 & & & 0.19 & 0.18, 0.20 \\
2019 & med & -1 & 0.23 & 0.22, 0.23 \\
2020 & & & 0.21 & 0.21, 0.22 \\
2021 & & & 0.23 & 0.22, 0.24 \\
2022 & & & 0.24 & 0.23, 0.24 \\
2019 & & 0 & 0.32 & 0.31, 0.32 \\
2020 & & & 0.28 & 0.28, 0.29 \\
2021 & & & 0.29 & 0.28, 0.29 \\
2022 & & & 0.29 & 0.29, 0.30 \\
2019 & & 1 & 0.41 & 0.40, 0.42 \\
2020 & & & 0.36 & 0.35, 0.37 \\
2021 & & & 0.35 & 0.34, 0.35 \\
2022 & & & 0.35 & 0.34, 0.36 \\
2019 & & 2 & 0.50 & 0.48, 0.52 \\
2020 & & & 0.43 & 0.41, 0.44 \\
2021 & & & 0.40 & 0.38, 0.42 \\
2022 & & & 0.40 & 0.38, 0.41 \\
2019 & high & -1 & 0.71 & 0.70, 0.72 \\
2020 & & & 0.72 & 0.71, 0.73 \\
2021 & & & 0.70 & 0.69, 0.71 \\
2022 & & & 0.69 & 0.68, 0.70 \\
2019 & & 0 & 0.59 & 0.59, 0.60 \\
2020 & & & 0.62 & 0.61, 0.63 \\
2021 & & & 0.61 & 0.61, 0.62 \\
2022 & & & 0.60 & 0.60, 0.61 \\
2019 & & 1 & 0.46 & 0.45, 0.48 \\
2020 & & & 0.51 & 0.49, 0.52 \\
2021 & & & 0.52 & 0.51, 0.53 \\
2022 & & & 0.51 & 0.50, 0.52 \\
2019 & & 2 & 0.34 & 0.33, 0.35 \\
2020 & & & 0.39 & 0.37, 0.41 \\
2021 & & & 0.42 & 0.40, 0.44 \\
2022 & & & 0.42 & 0.40, 0.43 \\
\end{longtable}

Table~\ref{tbl-marginal-science-pols} presents the predicted values of
trust in science from 2019 to 2022 across different levels of political
conservatism, expressed in standard deviation units (SD).

For the low trust category:

The population with low political conservatism (\(-1\) SD) had a
predicted probability of \(0.06\) (95\% CI: \(0.06\), \(0.06\)) in wave
2019, which increased slightly to \(0.07\) (95\% CI: \(0.07\), \(0.07\))
by wave 2022. The population at the mean (\(0\) SD) started at \(0.09\)
(95\% CI: \(0.09\), \(0.09\)) in wave 2019, peaking at \(0.10\) (95\%
CI: \(0.10\), \(0.10\)) in wave 2020 and stabilising at this level
through wave 2022. The population with higher political conservatism
(\(1\) SD) increased from \(0.12\) (95\% CI: \(0.12\), \(0.13\)) in wave
2019 to \(0.14\) (95\% CI: \(0.14\), \(0.14\)) in wave 2022. The highest
level of conservatism (\(2\) SD) had an initial value of \(0.16\) (95\%
CI: \(0.15\), \(0.17\)) in wave 2019, increasing to \(0.19\) (95\% CI:
\(0.18\), \(0.20\)) by wave 2022.

For the medium trust category:

The \(-1\) SD population started at \(0.23\) (95\% CI: \(0.22\),
\(0.23\)) in wave 2019, decreased to \(0.21\) (95\% CI: \(0.21\),
\(0.22\)) in wave 2020, and increased to \(0.24\) (95\% CI: \(0.23\),
\(0.24\)) by wave 2022. The \(0\) SD population exhibited a decrease
from \(0.32\) (95\% CI: \(0.31\), \(0.32\)) in wave 2019 to \(0.28\)
(95\% CI: \(0.28\), \(0.29\)) in wave 2020, remaining at approximately
\(0.29\) through 2022. For the \(1\) SD population, trust decreased from
\(0.41\) (95\% CI: \(0.40\), \(0.42\)) in wave 2019 to \(0.35\) (95\%
CI: \(0.34\), \(0.36\)) in 2022. The \(2\) SD population started higher
at \(0.50\) (95\% CI: \(0.48\), \(0.52\)) in wave 2019, but this value
decreased to \(0.40\) (95\% CI: \(0.38\), \(0.41\)) by wave 2022.

For the high trust category:

The \(-1\) SD population showed a high initial trust of \(0.71\) (95\%
CI: \(0.70\), \(0.72\)) in wave 2019, peaking in wave 2020 at \(0.72\)
(95\% CI: \(0.71\), \(0.73\)), and gradually decreasing to \(0.69\)
(95\% CI: \(0.68\), \(0.70\)) by wave 2022. The \(0\) SD population
started at \(0.59\) (95\% CI: \(0.59\), \(0.60\)) in wave 2019, peaking
at \(0.62\) (95\% CI: \(0.61\), \(0.63\)) in wave 2020, and stabilising
at \(0.60\) (95\% CI: \(0.60\), \(0.61\)) by wave 2022. The \(1\) SD
population increased from \(0.46\) (95\% CI: \(0.45\), \(0.48\)) in wave
2019 to \(0.51\) (95\% CI: \(0.50\), \(0.52\)) in wave 2022. The \(2\)
SD population started lower at \(0.34\) (95\% CI: \(0.33\), \(0.35\)) in
wave 2019 and increased to \(0.42\) (95\% CI: \(0.40\), \(0.43\)) by
wave 2022.

It is important to emphasise that these correlations should not be
interpreted as interactions or causal relationships. The findings
illustrate that trust in science varies by political conservatism, with
populations at lower conservatism levels (\(-1\) SD) reporting higher
predicted probabilities of high trust. Conversely, populations at higher
conservatism levels (\(2\) SD) increased in low and medium trust over
time but remained lower in high trust compared to less conservative
populations. However, these trends should be viewed cautiously, as
individuals who were initially high in trust may have shifted towards
greater political conservatism over time. This means that the
conservative cohort observed at each wave may differ, complicating
direct comparisons across time periods.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.0795}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2955}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3068}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1364}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1477}}@{}}
\caption{Predicted values of categorical trust in scientists trust in
science by across the range of political
conservativism.}\label{tbl-marginal-scietists-pols}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_scientists\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
political\_conservative\_z
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
wave
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
trust\_scientists\_factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
political\_conservative\_z
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Predicted
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
95\% CI
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2019 & low & -1 & 0.07 & 0.07, 0.08 \\
2020 & & & 0.07 & 0.07, 0.07 \\
2021 & & & 0.09 & 0.08, 0.09 \\
2022 & & & 0.08 & 0.08, 0.08 \\
2019 & & 0 & 0.11 & 0.11, 0.12 \\
2020 & & & 0.11 & 0.11, 0.11 \\
2021 & & & 0.12 & 0.12, 0.12 \\
2022 & & & 0.12 & 0.12, 0.12 \\
2019 & & 1 & 0.16 & 0.16, 0.17 \\
2020 & & & 0.16 & 0.16, 0.17 \\
2021 & & & 0.17 & 0.16, 0.17 \\
2022 & & & 0.17 & 0.17, 0.18 \\
2019 & & 2 & 0.22 & 0.21, 0.23 \\
2020 & & & 0.22 & 0.21, 0.23 \\
2021 & & & 0.21 & 0.20, 0.22 \\
2022 & & & 0.23 & 0.22, 0.24 \\
2019 & med & -1 & 0.26 & 0.25, 0.27 \\
2020 & & & 0.25 & 0.24, 0.26 \\
2021 & & & 0.26 & 0.25, 0.27 \\
2022 & & & 0.29 & 0.28, 0.30 \\
2019 & & 0 & 0.34 & 0.34, 0.35 \\
2020 & & & 0.32 & 0.32, 0.33 \\
2021 & & & 0.32 & 0.32, 0.33 \\
2022 & & & 0.35 & 0.34, 0.35 \\
2019 & & 1 & 0.42 & 0.41, 0.43 \\
2020 & & & 0.39 & 0.38, 0.40 \\
2021 & & & 0.38 & 0.37, 0.40 \\
2022 & & & 0.40 & 0.39, 0.41 \\
2019 & & 2 & 0.49 & 0.47, 0.50 \\
2020 & & & 0.45 & 0.43, 0.47 \\
2021 & & & 0.44 & 0.42, 0.46 \\
2022 & & & 0.43 & 0.42, 0.45 \\
2019 & high & -1 & 0.67 & 0.66, 0.68 \\
2020 & & & 0.68 & 0.67, 0.68 \\
2021 & & & 0.65 & 0.65, 0.66 \\
2022 & & & 0.62 & 0.61, 0.63 \\
2019 & & 0 & 0.54 & 0.54, 0.55 \\
2020 & & & 0.57 & 0.56, 0.57 \\
2021 & & & 0.56 & 0.55, 0.56 \\
2022 & & & 0.53 & 0.52, 0.54 \\
2019 & & 1 & 0.41 & 0.40, 0.42 \\
2020 & & & 0.45 & 0.43, 0.46 \\
2021 & & & 0.45 & 0.44, 0.46 \\
2022 & & & 0.43 & 0.42, 0.44 \\
2019 & & 2 & 0.29 & 0.28, 0.31 \\
2020 & & & 0.33 & 0.32, 0.35 \\
2021 & & & 0.35 & 0.33, 0.36 \\
2022 & & & 0.34 & 0.32, 0.35 \\
\end{longtable}

Table~\ref{tbl-marginal-scietists-pols}\ldots{}

Note we caution against any causal interpretation, as those already
trusting of science or of scientists might have become increasingly
conservative, a reminder that even in longitudinal data correlation is
not causation.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-kerr-growth-trust-science_files/figure-pdf/fig-combo_pols_graph_ord-1.pdf}}

}

\caption{\label{fig-combo_pols_graph_ord}}

\end{figure}%

Table~\ref{tbl-marginal-scietists-pols} presents the predicted values of
categorical trust in scientists from 2019 to 2022 across the spectrum of
political conservatism, expressed in standard deviation units (SD).

For the low trust category:

The population with low political conservatism (\(-1\) SD) had a
predicted probability starting at \(0.07\) (95\% CI: \(0.07\), \(0.08\))
in wave 2019, showing slight variations over time but ending at \(0.08\)
(95\% CI: \(0.08\), \(0.08\)) in 2022. The population at the mean (\(0\)
SD) began at \(0.11\) (95\% CI: \(0.11\), \(0.12\)) in wave 2019 and
remained stable at \(0.12\) (95\% CI: \(0.12\), \(0.12\)) through 2022.
The population with higher political conservatism (\(1\) SD) showed
consistent values starting at \(0.16\) (95\% CI: \(0.16\), \(0.17\)) in
wave 2019, with a slight increase to \(0.17\) (95\% CI: \(0.17\),
\(0.18\)) in wave 2022. The highest conservatism level (\(2\) SD) began
at \(0.22\) (95\% CI: \(0.21\), \(0.23\)) in wave 2019 and ended at
\(0.23\) (95\% CI: \(0.22\), \(0.24\)) by wave 2022.

For the medium trust category:

The \(-1\) SD population began at \(0.26\) (95\% CI: \(0.25\), \(0.27\))
in wave 2019, declining slightly to \(0.25\) (95\% CI: \(0.24\),
\(0.26\)) in wave 2020 and rising to \(0.29\) (95\% CI: \(0.28\),
\(0.30\)) by wave 2022. The \(0\) SD population showed a decrease from
\(0.34\) (95\% CI: \(0.34\), \(0.35\)) in wave 2019 to \(0.32\) (95\%
CI: \(0.32\), \(0.33\)) in wave 2020, with an increase to \(0.35\) (95\%
CI: \(0.34\), \(0.35\)) in wave 2022. The \(1\) SD population began at
\(0.42\) (95\% CI: \(0.41\), \(0.43\)) in wave 2019 and stabilised at
\(0.40\) (95\% CI: \(0.39\), \(0.41\)) by wave 2022. The \(2\) SD
population started at \(0.49\) (95\% CI: \(0.47\), \(0.50\)) in wave
2019 and declined to \(0.43\) (95\% CI: \(0.42\), \(0.45\)) by wave
2022.

For the high trust category:

The \(-1\) SD population had a high predicted probability of \(0.67\)
(95\% CI: \(0.66\), \(0.68\)) in wave 2019, peaking in wave 2020 at
\(0.68\) (95\% CI: \(0.67\), \(0.68\)), and declined to \(0.62\) (95\%
CI: \(0.61\), \(0.63\)) in wave 2022. The \(0\) SD population increased
from \(0.54\) (95\% CI: \(0.54\), \(0.55\)) in wave 2019 to \(0.57\)
(95\% CI: \(0.56\), \(0.57\)) in wave 2020, before declining to \(0.53\)
(95\% CI: \(0.52\), \(0.54\)) in 2022. The \(1\) SD population increased
from \(0.41\) (95\% CI: \(0.40\), \(0.42\)) in wave 2019 to \(0.43\)
(95\% CI: \(0.42\), \(0.44\)) in wave 2022. The \(2\) SD population
began at \(0.29\) (95\% CI: \(0.28\), \(0.31\)) in wave 2019 and
increased to \(0.34\) (95\% CI: \(0.32\), \(0.35\)) by wave 2022.

It is again important to caution against causal interpretations of these
results. Individuals with initially high trust in science or scientists
may have become more politically conservative over time. This shift
implies that the composition of the conservative population may change
over the observed period, highlighting that even in longitudinal data,
correlation does not equate to causation.

Figure~\ref{fig-combo_pols_graph_ord} visually represents the predicted
trends in categorical trust in science and scientists by political
orientation.

\subsection{Discussion}\label{discussion}

Here we examined leverage panel data from the New Zealand Attitudes and
Values Study to investigate trends in public trust toward science and
scientists in New Zealand from October 2019 (NZAVS wave 2019) to
September 2023 (NZAVS wave 2022).

\textbf{Study 1} investigated bias in attrition. By employing multiple
imputation to address missing survey responses, we discovered that the
initial pattern of increasing mistrust observed in the raw data is
inverted; whereas observed responses suggest increasing trust over time,
multiply imputed responses reveal this pattern to be an artefact of
selection bias.

\textbf{Study 2} reveals that, contrary to observed sample responses,
there was no lasting increase in trust in science or scientists in the
from wave 2021 and onward. Although there was a moderate rise in trust
in wave 2020---potentially associated with New Zealand's initially
successful response to the COVID-19 pandemic---this increase was not
sustained. From 2021, the data indicate a decline in average trust
levels across the population. Notably, the distribution of responses
shows significant variation above and below the population averages,
revealing a sizable minority of science skeptics. This suggests that
while overall trust levels may appear stable, underlying shifts within
subgroups are occurring.

\textbf{Study 3} investigated trust responses defined by low (1-3)
medium (4,5) and high (6,7) response scores. The findings indicate that
although the proportion of individuals with high trust peaked
temporarily in wave 2020, the overall trend is a gradual decline in high
trust accompanied by small but notable increases in low trust over time.
Importantly, the boost in trust following the onset of the pandemic was
confined to the high end of the trust spectrum. While low trust in
scientists decreased during New Zealand's early COVID-19 response, it
has gradually risen, reavealing a potentially complex interplay between
public events and trust dynamics, matters for future investigations.

Our findings should be interpreted cautiously as our models do not
identify causality. M

Nevertheless, our findings hold considerable practical interest,
revealing potential shifts in the underpinnings of institutional trust
in science. Converting proportional estimates for the population
suggests that in wave 2019, the population that was low in trust of
scientists numbered at least 463,457 and by the end of 2023 grew to
479,167. Those who scored low in trust in science numbered at least
325,991 resident adults. By the end of 2023, this population increased
to 384,905, gaining 58,914 people. These are sizable fractions of the
population who are weary of the emphasis placed on science in society or
of scientists.

Future research should address the root causes of this decline in trust,
and its effects on health, culture, and social cohesion.

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study. Members of the NZAVS management team and research
group hold full copies of the NZAVS data. A de-identified dataset
containing only the variables analysed in this manuscript is available
upon request from the corresponding author or any member of the NZAVS
advisory board for replication or checking of any published study using
NZAVS data. The code for the analysis can be found at: OSF-lINK TBA.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Plank Institute for the Science of Human History. The
funders had no role in preparing the manuscript or deciding to publish
it.

\subsubsection{Author Statement}\label{author-statement}

\textbf{TBA}: JK led the study. CGS led data collection. JB developed
the analytic approach and analysis\ldots(etc, etc..tba). All authors
contributed to the manuscript.

\newpage{}

\subsection{Appendix A: Sample Descriptive Statistics}\label{appendix-a}

Table~\ref{tbl-baseline} presents descriptive statistics for the sample.

\begin{longtable}[t]{lllll}

\caption{\label{tbl-baseline}Sample statistics.}

\tabularnewline

\toprule
**Variables** & **2019**  
N = 42,681 & **2020**  
N = 42,681 & **2021**  
N = 42,681 & **2022**  
N = 42,681\\
\midrule
\_\_Age\_\_ &   ~~&   ~~&   ~~& ~~\\
Mean (SD) & 52 (14) & 54 (14) & 55 (14) & 57 (13)\\
Min, Max & 18, 97 & 19, 97 & 20, 97 & 21, 98\\
Q1, Q3 & 42, 63 & 45, 64 & 47, 65 & 48, 67\\
Missing & 0 & 9,363 & 13,615 & 17,166\\
\addlinespace
\_\_Agreeableness\_\_ &   ~~&   ~~&   ~~& ~~\\
Mean (SD) & 5.38 (0.98) & 5.38 (0.98) & 5.36 (1.00) & 5.35 (0.99)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.75, 6.00 & 4.75, 6.00 & 4.75, 6.00 & 4.75, 6.00\\
Missing & 316 & 9,579 & 13,831 & 17,260\\
\addlinespace
\_\_Belong\_\_ &   ~~&   ~~&   ~~& ~~\\
Mean (SD) & 5.09 (1.09) & 5.02 (1.11) & 5.14 (1.12) & 5.14 (1.11)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.33, 6.00 & 4.33, 6.00 & 4.33, 6.00 & 4.33, 6.00\\
Missing & 324 & 9,587 & 13,885 & 17,303\\
\addlinespace
\_\_Born NZ\_\_ & 33,316 (78\%) & 33,316 (78\%) & 33,316 (78\%) & 33,316 (78\%)\\
Missing & 81 & 81 & 81 & 81\\
\_\_Conscientiousness\_\_ &   ~~&   ~~&   ~~& ~~\\
Mean (SD) & 5.06 (1.07) & 5.10 (1.05) & 5.12 (1.06) & 5.12 (1.05)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
\addlinespace
Q1, Q3 & 4.25, 5.75 & 4.50, 6.00 & 4.50, 6.00 & 4.50, 6.00\\
Missing & 313 & 9,577 & 13,823 & 17,259\\
\_\_Education Level Coarsen\_\_ &   ~~&   ~~&   ~~& ~~\\
no\_qualification & 853 (2.0\%) & 754 (1.8\%) & 706 (1.7\%) & 711 (1.7\%)\\
cert\_1\_to\_4 & 13,117 (31\%) & 12,588 (30\%) & 12,228 (29\%) & 11,989 (28\%)\\
\addlinespace
cert\_5\_to\_6 & 5,606 (13\%) & 5,714 (14\%) & 5,748 (14\%) & 5,807 (14\%)\\
university & 11,783 (28\%) & 11,856 (28\%) & 11,823 (28\%) & 11,747 (28\%)\\
post\_grad & 5,363 (13\%) & 5,614 (13\%) & 5,850 (14\%) & 5,992 (14\%)\\
masters & 4,256 (10\%) & 4,440 (10\%) & 4,579 (11\%) & 4,685 (11\%)\\
doctorate & 1,280 (3.0\%) & 1,337 (3.2\%) & 1,381 (3.3\%) & 1,426 (3.4\%)\\
\addlinespace
Missing & 423 & 378 & 366 & 324\\
\_\_Employed\_\_ & 31,856 (76\%) & 25,061 (76\%) & 21,235 (74\%) & 17,725 (71\%)\\
Missing & 550 & 9,580 & 13,942 & 17,589\\
\_\_Ethnicity\_\_ &   ~~&   ~~&   ~~& ~~\\
euro & 34,990 (83\%) & 34,990 (83\%) & 34,990 (83\%) & 34,990 (83\%)\\
\addlinespace
maori & 4,639 (11\%) & 4,639 (11\%) & 4,639 (11\%) & 4,639 (11\%)\\
pacific & 929 (2.2\%) & 929 (2.2\%) & 929 (2.2\%) & 929 (2.2\%)\\
asian & 1,770 (4.2\%) & 1,770 (4.2\%) & 1,770 (4.2\%) & 1,770 (4.2\%)\\
Missing & 353 & 353 & 353 & 353\\
\_\_Extraversion\_\_ &   ~~&   ~~&   ~~& ~~\\
\addlinespace
Mean (SD) & 3.87 (1.19) & 3.83 (1.19) & 3.77 (1.23) & 3.75 (1.23)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 3.00, 4.75 & 3.00, 4.75 & 3.00, 4.67 & 3.00, 4.50\\
Missing & 314 & 9,577 & 13,832 & 17,274\\
\_\_Honesty Humility\_\_ &   ~~&   ~~&   ~~& ~~\\
\addlinespace
Mean (SD) & 5.56 (1.14) & 5.62 (1.11) & 5.68 (1.13) & 5.72 (1.12)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.75, 6.50 & 5.00, 6.50 & 5.00, 6.67 & 5.00, 6.75\\
Missing & 323 & 9,587 & 13,816 & 17,252\\
\_\_Hours Commute\_\_ &   ~~&   ~~&   ~~& ~~\\
\addlinespace
Mean (SD) & 4.5 (7.0) & 4.4 (5.9) & 3.7 (5.4) & 4.4 (6.2)\\
Min, Max & 0.0, 168.0 & 0.0, 100.0 & 0.0, 100.0 & 0.0, 100.0\\
Q1, Q3 & 1.0, 6.0 & 1.0, 6.0 & 1.0, 5.0 & 1.0, 6.0\\
Missing & 829 & 10,233 & 14,611 & 18,092\\
\_\_Household Inc\_\_ &   ~~&   ~~&   ~~& ~~\\
\addlinespace
Mean (SD) & 117,971 (107,738) & 120,324 (106,017) & 124,450 (111,893) & 130,963 (146,750)\\
Min, Max & 1, 4,000,000 & 1, 3,000,000 & 1, 3,500,000 & 1,000, 7,500,000\\
Q1, Q3 & 55,000, 150,000 & 57,000, 150,000 & 58,000, 160,000 & 59,000, 165,000\\
Missing & 2,039 & 10,255 & 14,527 & 17,669\\
\_\_Kessler Latent Anxiety\_\_ &   ~~&   ~~&   ~~&   ~~\\
\addlinespace
Mean (SD) & 1.20 (0.76) & 1.17 (0.76) & 1.19 (0.77) & 1.17 (0.77)\\
Min, Max & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00\\
Q1, Q3 & 0.67, 1.67 & 0.67, 1.67 & 0.67, 1.67 & 0.67, 1.67\\
Missing & 344 & 9,591 & 13,814 & 17,257\\
\_\_Kessler Latent Depression\_\_ &   ~~&   ~~&   ~~&   ~~\\
\addlinespace
Mean (SD) & 0.60 (0.75) & 0.55 (0.73) & 0.57 (0.74) & 0.54 (0.72)\\
Min, Max & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00\\
Q1, Q3 & 0.00, 1.00 & 0.00, 1.00 & 0.00, 1.00 & 0.00, 1.00\\
Missing & 340 & 9,588 & 13,814 & 17,259\\
\_\_Male\_\_ & 15,228 (36\%) & 15,228 (36\%) & 15,228 (36\%) & 15,228 (36\%)\\
\addlinespace
\_\_Neuroticism\_\_ &   ~~&   ~~&   ~~&   ~~\\
Mean (SD) & 3.50 (1.16) & 3.46 (1.16) & 3.41 (1.18) & 3.36 (1.17)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 2.75, 4.25 & 2.50, 4.25 & 2.50, 4.25 & 2.50, 4.25\\
Missing & 315 & 9,580 & 13,822 & 17,261\\
\addlinespace
\_\_Nz Dep2018\_\_ &   ~~&   ~~&   ~~&   ~~\\
Mean (SD) & 4.75 (2.72) & 4.75 (2.73) & 4.75 (2.73) & 4.75 (2.73)\\
Min, Max & 1.00, 10.00 & 1.00, 10.00 & 1.00, 10.00 & 1.00, 10.00\\
Q1, Q3 & 2.00, 7.00 & 2.00, 7.00 & 2.00, 7.00 & 2.00, 7.00\\
Missing & 328 & 541 & 957 & 927\\
\addlinespace
\_\_Nzsei 13 L\_\_ &   ~~&   ~~&   ~~&   ~~\\
Mean (SD) & 56 (16) & 56 (16) & 56 (16) & 57 (15)\\
Min, Max & 10, 90 & 10, 90 & 10, 90 & 10, 90\\
Q1, Q3 & 44, 69 & 44, 70 & 45, 70 & 46, 70\\
Missing & 338 & 3,236 & 4,294 & 6,107\\
\addlinespace
\_\_Openness\_\_ &   ~~&   ~~&   ~~&   ~~\\
Mean (SD) & 5.01 (1.11) & 5.01 (1.11) & 5.02 (1.14) & 5.01 (1.15)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.25, 5.75 & 4.25, 5.75 & 4.25, 6.00 & 4.25, 6.00\\
Missing & 316 & 9,579 & 13,830 & 17,265\\
\addlinespace
\_\_Parent\_\_ & 31,213 (73\%) & 24,889 (75\%) & 21,693 (75\%) & 19,597 (77\%)\\
Missing & 20 & 9,363 & 13,752 & 17,166\\
\_\_Partner\_\_ & 31,353 (75\%) & 24,644 (75\%) & 21,377 (75\%) & 18,499 (75\%)\\
Missing & 786 & 9,844 & 14,248 & 17,868\\
\_\_Political Conservative\_\_ &   ~~&   ~~&   ~~&   ~~\\
\addlinespace
1 & 2,703 (6.5\%) & 2,289 (7.1\%) & 1,654 (6.0\%) & 1,431 (5.9\%)\\
2 & 8,734 (21\%) & 7,118 (22\%) & 6,012 (22\%) & 5,188 (21\%)\\
3 & 8,493 (21\%) & 6,944 (22\%) & 5,978 (22\%) & 4,972 (20\%)\\
4 & 11,838 (29\%) & 9,424 (29\%) & 8,268 (30\%) & 6,936 (29\%)\\
5 & 5,942 (14\%) & 4,110 (13\%) & 3,901 (14\%) & 3,577 (15\%)\\
\addlinespace
6 & 2,980 (7.2\%) & 1,788 (5.6\%) & 1,639 (5.9\%) & 1,853 (7.6\%)\\
7 & 677 (1.6\%) & 405 (1.3\%) & 335 (1.2\%) & 365 (1.5\%)\\
Missing & 1,314 & 10,603 & 14,894 & 18,359\\
\_\_Religion Identification Level\_\_ &   ~~&   ~~&   ~~&   ~~\\
1 & 29,148 (69\%) & 22,794 (69\%) & 20,119 (70\%) & 17,134 (69\%)\\
\addlinespace
2 & 1,329 (3.2\%) & 919 (2.8\%) & 765 (2.7\%) & 812 (3.3\%)\\
3 & 860 (2.0\%) & 801 (2.4\%) & 670 (2.3\%) & 558 (2.3\%)\\
4 & 1,967 (4.7\%) & 1,562 (4.7\%) & 1,322 (4.6\%) & 1,165 (4.7\%)\\
5 & 2,312 (5.5\%) & 1,882 (5.7\%) & 1,656 (5.8\%) & 1,270 (5.1\%)\\
6 & 2,040 (4.8\%) & 1,707 (5.2\%) & 1,415 (4.9\%) & 1,241 (5.0\%)\\
\addlinespace
7 & 4,419 (11\%) & 3,258 (9.9\%) & 2,764 (9.6\%) & 2,546 (10\%)\\
Missing & 606 & 9,758 & 13,970 & 17,955\\
\_\_Rural Gch 2018 Levels\_\_ &  &   ~~&   ~~&   ~~\\
1 & 25,864 (61\%) & 25,578 (61\%) & 25,088 (60\%) & 24,950 (60\%)\\
2 & 8,164 (19\%) & 8,195 (19\%) & 8,185 (20\%) & 8,220 (20\%)\\
\addlinespace
3 & 5,362 (13\%) & 5,439 (13\%) & 5,470 (13\%) & 5,529 (13\%)\\
4 & 2,461 (5.8\%) & 2,475 (5.9\%) & 2,495 (6.0\%) & 2,551 (6.1\%)\\
5 & 506 (1.2\%) & 507 (1.2\%) & 488 (1.2\%) & 504 (1.2\%)\\
Missing & 324 & 487 & 955 & 927\\
\_\_Right Wing Authoritarianism\_\_ &   ~~&   ~~&   ~~&   ~~\\
\addlinespace
Mean (SD) & 3.17 (1.14) & 3.25 (1.11) & 3.33 (1.06) & 3.30 (1.07)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 2.33, 4.00 & 2.50, 4.00 & 2.50, 4.00 & 2.50, 4.00\\
Missing & 46 & 9,423 & 13,803 & 17,220\\
\_\_Social Dominance Orientation\_\_ &   ~~&   ~~&   ~~&   ~~\\
\addlinespace
Mean (SD) & 2.22 (0.96) & 2.18 (0.95) & 2.20 (0.95) & 2.23 (0.96)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 1.50, 2.83 & 1.33, 2.83 & 1.50, 2.83 & 1.50, 2.83\\
Missing & 16 & 9,383 & 13,647 & 17,170\\
\_\_Social Support (perceived)\_\_ &   ~~&   ~~&   ~~&   ~~\\
\addlinespace
Mean (SD) & 5.93 (1.15) & 5.93 (1.14) & 5.93 (1.16) & 5.96 (1.15)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 5.33, 7.00 & 5.33, 7.00 & 5.33, 7.00 & 5.33, 7.00\\
Missing & 28 & 9,397 & 13,772 & 17,268\\
\bottomrule

\end{longtable}

Table~\ref{tbl-baseline} presents sample statistics.

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-tinytable_2024}
Arel-Bundock, V (2024) \emph{Tinytable: Simple and configurable tables
in 'HTML', 'LaTeX', 'markdown', 'word', 'PNG', 'PDF', and 'typst'
formats}. Retrieved from
\url{https://CRAN.R-project.org/package=tinytable}

\bibitem[\citeproctext]{ref-blackwell_2017_unified}
Blackwell, M, Honaker, J, and King, G (2017) A unified approach to
measurement error and missing data: Overview and applications.
\emph{Sociological Methods \& Research}, \textbf{46}(3), 303--341.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-bulbulia2023a}
Bulbulia, JA, Afzali, MU, Yogeeswaran, K, and Sibley, CG (2023)
Long-term causal effects of far-right terrorism in {N}ew {Z}ealand.
\emph{PNAS Nexus}, \textbf{2}(8), pgad242.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a {N}ew {Z}ealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-geepack_2006}
Halekoh, U, Højsgaard, S, and Yan, J (2006) The {R} package geepack for
generalized estimating equations. \emph{Journal of Statistical
Software}, \textbf{15/2}, 1--11. Retrieved from
\url{https://www.jstatsoft.org/v15/i02/}

\bibitem[\citeproctext]{ref-hartman2017}
Hartman, RO, Dieckmann, NF, Sprenger, AM, Stastny, BJ, and DeMarree, KG
(2017) Modeling attitudes toward science: Development and validation of
the credibility of science scale. \emph{Basic and Applied Social
Psychology}, \textbf{39}, 358--371.
doi:\href{https://doi.org/10.1080/01973533.2017.1372284}{10.1080/01973533.2017.1372284}.

\bibitem[\citeproctext]{ref-amelia_2011}
Honaker, J, King, G, and Blackwell, M (2011) {Amelia II}: A program for
missing data. \emph{Journal of Statistical Software}, \textbf{45}(7),
1--47.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-ggeffects_2018}
Ludecke, D (2018) Ggeffects: Tidy data frames of marginal effects from
regression models. \emph{Journal of Open Source Software},
\textbf{3}(26), 772.
doi:\href{https://doi.org/10.21105/joss.00772}{10.21105/joss.00772}.

\bibitem[\citeproctext]{ref-mcneish_2017unnecessary}
McNeish, D, Stapleton, LM, and Silverman, RD (2017) On the unnecessary
ubiquity of hierarchical linear modeling. \emph{Psychological Methods},
\textbf{22}(1), 114.

\bibitem[\citeproctext]{ref-nisbet2015}
Nisbet, EC, Cooper, KE, and Garrett, RK (2015) The partisan brain: How
dissonant science messages lead conservatives and liberals to (dis)trust
science. \emph{The ANNALS of the American Academy of Political and
Social Science}, \textbf{658}(1), 36--66.
doi:\href{https://doi.org/10.1177/0002716214555474}{10.1177/0002716214555474}.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the {N}ew {Z}ealand {A}ttitudes and {V}alues
{S}tudy}}.

\bibitem[\citeproctext]{ref-sibley2020a}
Sibley, CG, Greaves, L, Satherley, N, \ldots{} al, et (2020) What
happened to people in {N}ew {Z}ealand during covid-19 home lockdown?
Institutional trust, attitudes to government, mental health and
subjective wellbeing. Retrieved from
\href{https://osf.io/e765a}{osf.io/e765a}

\bibitem[\citeproctext]{ref-nnet_2002}
Venables, WN, and Ripley, BD (2002) \emph{Modern applied statistics with
s}, Fourth, New York: Springer. Retrieved from
\url{https://www.stats.ox.ac.uk/pub/MASS4/}

\bibitem[\citeproctext]{ref-ggplot2_2016}
Wickham, H (2016) \emph{ggplot2: Elegant graphics for data analysis},
Springer-Verlag New York. Retrieved from
\url{https://ggplot2.tidyverse.org}

\end{CSLReferences}




\end{document}
