% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  singlecolumn]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=20mm,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={One-year Causal Effect of Religious Deconversion on Political Orientation in New Zealand},
  pdfauthor={Daryl Van Tongeren; Don E Davis; Chris G. Sibley; Joseph A. Bulbulia},
  pdfkeywords={Causal Inference, Religion, Political Orientation},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{One-year Causal Effect of Religious Deconversion on Political
Orientation in New Zealand}
\author{Daryl Van Tongeren \and Don E Davis \and Chris G.
Sibley \and Joseph A. Bulbulia}
\date{2024-03-27}

\begin{document}
\maketitle
\begin{abstract}
We leverage longitudinal (panel) data from a large national probability
sample of New Zealanders to estimate three one-year causal effects of
religious disaffiliation on political conservativism and political
right-wing orientation (N = 47,202). In Study 1, we investigate the
average treatment effect of a shift from religious affiliation to
disaffiliation, contrasted with a condition in which the population was
disaffiliated at baseline and remained so. We observe that religious
disaffiliation reduces conservative/right political orientations. This
effect is considerably stronger for political conservativism than for
right-wing orientation. In Study 2, we contrast the transition to
religious disaffiliation from affiliation with constant disaffiliation.
This contrast clarifies whether recent religious disaffiliates are
subject to ``religious residue'' effects. We detect a religious residue
effect for political conservativism but not for right-wing orientation.
Overall, these findings suggest that in New Zealand, religious
disaffiliation affects political orientations by reducing conservative
and (to a lesser extent) right-wing political orientations, with some
evidence for religious residue effects for political conservativism.
\end{abstract}

\subsection{Introduction}\label{introduction}

Throughout the west, religious disaffiliation is commonplace
(\citeproc{ref-wilson2014differences}{Wilson \emph{et al.} 2014}). How
does religious disaffiliation affect political orientation? Because
correlation is not causation, this question cannot be straightforwardly
addressed with cross-sectional data.

Longitudinal (panel) data may help to clarify causation, however, only
if certain data and modelling assumptions are satisfied.

Here, we systematically investigate three distinct one-year causal
effects of religious disaffiliation on two dimensions of political
orientation. Our results draw from a national longitudinal probability
study of New Zealanders (New Zealand Attitudes and Values Study, years
2018-2021, N = 47202). To obtain valid inference, we performing
doubly-robust non-parametric estimation controlling for a rich array of
baseline confounders, including the baseline treatment and outcomes.
Finally, because confounding cannot be controlled with certainty, we
provide sensitivity analyses for unmeasured confounding.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of The New Zealand Attitudes and Values
Study (NZAVS) is an annual longitudinal national probability panel study
of social attitudes, personality, ideology and health outcomes. Chris G
Sibley started the NZAVS in 2009, and it has since grown to a community
with over sixty investigators. The NZAVS includes questionnaire
responses from a total of 72,290 New Zealand residents. The NZAVS is
university-based, not-for-profit and independent of political or
corporate funding. see \url{https://doi.org/10.17605/OSF.IO/75SNB}

\hyperref[appendix-measures]{Appendix A} provides information about the
measures used in this study.

\hyperref[appendix-demographics]{Appendix B} reports sample statistics
for all covariates at the baseline wave (NZAVS time 10, years
2018-2019).

\hyperref[appendix-exposures]{Appendix C} reports sample statistics for
the treatment at the baseline wave (NZAVS time 10, years 2018-2019) and
the treatment wave (NZAVS time 11, years 2019-2020).

\hyperref[appendix-outcomes]{Appendix D} reports reports sample
statistics for the outcomes responses at baseline (NZAVS time 10, years
2018-2019) and the outcome wave (NZAVS time 12, years 2020-2021).

\subsubsection{The Treatment/Exposure: Religious
Affiliation}\label{the-treatmentexposure-religious-affiliation}

\textbf{Study 1}: we contrast the following conditions: (1) all start as
religiously affiliated in the baseline wave and then lose their
religious affiliation in the following wave (dones); (2) all start as
religiously affiliated in the baseline wave and remain religiously
affiliated. The contrast of these conditions addresses the question:
``Does religious disaffiliation affect change in political
orientations?''

\textbf{Study 2}: we contrast the following conditions: (1) all start as
religiously affiliated in the baseline wave and then lose their
religious affiliation in the following wave (dones); (2) all start as
religiously disaffiliated in the baseline wave and then remain
religiously disaffiliated: The contrast of these conditions addresses
the question: is there a religious residue effect? see Van Tongeren
\emph{et al.} (\citeproc{ref-vantongeren2020}{2020}).

\subsubsection{Outcomes}\label{outcomes}

The New Zealand Attitudes and Values Study has two measures of political
orientation, both adapted from Jost
(\citeproc{ref-jost_end_2006-1}{2006}):

\textbf{Politically Conservative}: ``Please rate how politically liberal
versus conservative you see yourself as being.'' (1 = Extremely Liberal
to 7 = Extremely Conservative)

\textbf{Politically Right Wing}: ``Please rate how politically left-wing
versus right-wing you see yourself as being'' (1 = Extremely left-wing
to 7 = Extremely right-wing)

Outcomes under the different treatments were assessed one year after the
treatment wave.

\subsubsection{Causal Contrasts}\label{causal-contrasts}

In \textbf{Study 1}, the estimand is:

\[ 
\text{Average Treatment Effect} = E[Y(a,a^*)|\textcolor{red}{f(A)},L] -  E[Y(a, a)|\textcolor{red}{f(A)},L] 
\]

where interventions are as specified as follows:

\[
   f(A) = \begin{cases} a & \text{if religious affiliation is absent, shift to religious affiliation} \\ 
   a^* & \text{if religious affiliation is present, shift to disaffiliation} \end{cases}
   \]

In \textbf{Study 2} where shift function is specified as above:

\[
f(A) = \begin{cases} a & \text{if religious affiliation is absent, shift to religious affiliation} \\ 
   a^* & \text{if religious affiliation is present, shift to disaffiliation} \end{cases}
\]

But the estimand targets the expected difference in outcomes between
recent religious disaffiliates (dones) with the stably disaffiliated :

\[ 
\text{Average Treatment Effect} = E[Y(a,a^*)|\textcolor{red}{f(A)},L] -  E[Y(a^*, a^*)|\textcolor{red}{f(A)},L] 
\]

In both Study 1 and Study 2, we weight the causal contrasts to the New
Zealand population (age x ethnicity x gender), which is the target
population for this study.

\subsubsection{Eligibility criteria}\label{eligibility-criteria}

The sample consisted of respondents to NZAVS times 10 (baseline, years
2018-2019), time 11 (treatment wave, years 2019-2020), and time 12
(outcome wave, years 2020-2021). For sampling information please see:
Sibley (\citeproc{ref-sibley2021}{2021}).

Criteria for inclusion were: enrolled in the New Zealand Attitudes and
Values Study at Time 10 (baseline) and provided complete responses to
the religious affiliation question (``Do you identify with a religious
or spiritual group: y/n''). We allow that participants may have been
lost to follow up, and adjusted for missingness using inverse
probability of censoring model -- implemented during estimation in
\texttt{lmtp} (\citeproc{ref-williams2021}{Williams and Díaz 2021}).

There were 47202 NZAVS participants who met these criteria.

\subsubsection{Identification
Assumptions}\label{identification-assumptions}

To consistently estimate causal effects, we rely on three fundamental
assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal Consistency:} we assume the potential outcomes do not
  depend on the specific way treatment was administered, conditional on
  measured covariates (\citeproc{ref-vanderweele2009}{VanderWeele
  2009}).
\item
  \textbf{Conditional Exchangability:} we assume that given the observed
  covariates, treatment assignment is independent of potential outcomes.
  In simpler terms, we assume ``no unmeasured confounding.''
\item
  \textbf{Positivity:} we assume that every subject has a non-zero
  probability of receiving the treatments to be compared.
  \hyperref[appendix-exposures]{Appendix C} shows a change in the
  treatment variable between NZAVS Time 10 and NZAVS Time 11.
\end{enumerate}

\textbf{Considerations:}

Because unmeasured confounding cannot be verified in the data, we
perform sensitivity analysis by estimating the magnitude of unmeasured
confounding required to explain away a result (E-values), see
VanderWeele and Ding (\citeproc{ref-vanderweele2017}{2017}).

\subsubsection{Analysis}\label{analysis}

Model specification for NZAVS three-wave panel designs operate broadely
within a targeted learning framework (\citeproc{ref-duxedaz2021}{Díaz
\emph{et al.} 2021}; \citeproc{ref-vanderlaan2011}{Van Der Laan and Rose
2011}, \citeproc{ref-vanderlaan2018}{2018}) and are pre-specified in
(\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024}).

\subsubsection{Confounding Control
Strategy}\label{confounding-control-strategy}

We adopt VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020})'s \emph{minimally modified
disjunctive criteria} for confounding control.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Initial identify confounders}: using causal diagrams, we began
  by enumerating all covariates that may influence either the treatment
  (exposure) or outcomes, spanning five domains. This includes variables
  directly affecting the exposure or outcome and potential effects of
  these variables (i.e.~proxies.)
\item
  \textbf{Remove instrumental variables}: we removed variables
  identified as instrumental variables, i.e., those influencing the
  exposure but not the outcome. Their inclusion can reduce the
  efficiency of the analysis.
\item
  \textbf{Inclusion of proxy variables}: for unmeasured variables that
  affect both the exposure and outcome, include proxy variables wherever
  possible. These proxies act as indicators for the unmeasured common
  causes. \hyperref[appendix-demographics]{Appendix B} lists covariates
  we used for confounding control.
\end{enumerate}

Again, these protocols follow the advice in
(\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024}) as prespecified in
\url{https://osf.io/ce4t9/}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\item
  \textbf{Baseline exposure control}: we include baseline outcome
  measures to adjust for unmeasured confounding and obtain an incident
  exposure effect estimate (\citeproc{ref-danaei2012}{Danaei \emph{et
  al.} 2012}; \citeproc{ref-hernan2023}{Hernan and Robins 2023};
  \citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).
\item
  \textbf{Baseline outcome control}: we also include baseline measures
  of the outcome to adjust for unmeasured confounding
  (\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). This
  strategy also minimises the possibility of reverse causation.
\end{enumerate}

Thus, for any unmeasured variable to be associated with both the
treatment in the exposure wave and the outcome one year later, this
association would need to be independent of the measured baseline
responses for the treatment and the outcome as well as for the
demographic and personality covariates included in the model
(\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).

Overall, then, our approach utilises \emph{three-wave} of New Zealand
Attitudes and Values Study (NZAVS) panel data:

\begin{itemize}
\item
  \textbf{Wave 0}: the baseline wave (NZAVS Time 10, years 2018-2019)
\item
  \textbf{Wave 1}: the treatment wave (NZAVS Time 11, years 2019-2020)
\item
  \textbf{Wave 2}: and the outcome wave (NZAVS Time 12, years 2019-2020)
\end{itemize}

Because in observational studies, we cannot be confident there is no
unmeasured confounding, we perform additional sensitivity analysis using
the E-value as described below
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). For further
discussion of our three-wave confounding control strategy, see
VanderWeele \emph{et al.} (\citeproc{ref-vanderweele2020}{2020});
Bulbulia (\citeproc{ref-bulbulia2024PRACTICAL}{2024}).

\subsubsection{Missing Data}\label{missing-data}

\textbf{Handling missing data}: to better ensure that the analyses are
robust to potential biases introduced by missing data, we adopt the
following strategies:

\begin{itemize}
\item
  \textbf{Baseline missingness}: we impute missing data to recover
  baseline missing data for all variables except the treatment
  (\texttt{mice} package in R) (\citeproc{ref-vanbuuren2018}{Van Buuren
  2018}). Overall 1.6\% of responses at baseline data were missing.
\item
  \textbf{Follow-up missingness}: we used the \texttt{lmtp} package's
  built-in non-parametric inverse probability of censoring weighting
  feature to adjust for loss-to-follow-up/sample attrition
  (\citeproc{ref-williams2021}{Williams and Díaz 2021}). Note this
  includes right-censoring including for the treatment variable in the
  treatment wave, enabling us to recover a \emph{per protocol effect}
  that is more robust to informed censoring after baseline, including
  censoring of the treatment.
\end{itemize}

We obtain valid inferences for the target population - the New Zealand
general population -- by applying post-stratification census weights for
age, ethnicity, and gender using the census weights specified in Sibley
(\citeproc{ref-sibley2021}{2021}).

\paragraph{Estimator}\label{estimator}

We employ a semi-parametric estimator known as Sequentially Doubly
Robust Estimation (SDR), which can estimate the causal effect of
modified treatment policies on outcomes over time
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021}). This estimator
belongs broadly to the ``TMLE-verse'' class of doubly-robust targeted
learning framework developed by Van Der Laan and Rose
(\citeproc{ref-vanderlaan2011}{2011}); Van Der Laan and Rose
(\citeproc{ref-vanderlaan2018}{2018}). Estimation was performed using
\texttt{lmtp} package (\citeproc{ref-duxedaz2021}{Díaz \emph{et al.}
2021}; \citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023};
\citeproc{ref-williams2021}{Williams and Díaz 2021}). SDR is a robust
method that flexibly combines machine learning techniques with
traditional statistical models to estimate causal effects, while also
providing valid statistical uncertainty measures for these estimates.

SDR operates through a two-step process involving outcome and treatment
(exposure) models. Initially, it employs machine learning algorithms to
flexibly model the relationship between treatments, covariates, and
outcomes. This flexibility allows SDR to account for complex,
high-dimensional covariate spaces without imposing restrictive
parametric modelling assumptions. The outcome of this step is a set of
initial estimates for these relationships.

The second step of SDR involves ``targeting'' these initial estimates by
incorporating information about the observed data distribution to
improve the accuracy for the causal effect-estimates of interest. This
is achieved through an iterative updating process, which adjusts the
initial estimates towards the true causal effect. In targeted learning,
updating is guided by the efficient influence function, ensuring that
the final estimate is as close as possible to the true causal effect,
while remaining robust to model misspecification to either the outcome
or treatment model.

A central feature of SDR is its double-robustness property, meaning that
if either the model for the treatment or the outcome is correctly
specified, the SDR estimator will still consistently estimate the causal
effect. Additionally, SDR uses cross-validation to avoid over-fitting
and ensure that the estimator performs well in finite samples. Each of
these steps contributes to a robust methodology for examining the
\emph{causal} effects of interventions on outcomes. The marriage of SDR
and machine learning technologies reduces the dependence on restrictive
modelling assumptions and introduces an additional layer of robustness.
For further details see (\citeproc{ref-duxedaz2021}{Díaz \emph{et al.}
2021}; \citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023}).

\paragraph{Estimation}\label{estimation}

We used the \texttt{lmtp} R package to estimate treatment the causal
effects of pre-specified interventions on religious affiliation for the
two political orientation responses that the New Zealand Attitudes and
Values Study measures: political conservativism and right-wing
orientation.

As mentione, our models included an indicator for censoring in the next
wave (right-censoring), which reduces bias from loss to
follow-up/attrition conditional on measured covariates, subject to the
covariates in the model.

Again in Study 1 we contrast the following conditions:

\begin{itemize}
\item
  \textbf{TREATMENT: all start with religious affiliation and then lose
  religious affiliation (DONES)}
\item
  \textbf{CONTRAST: all start with religious affiliation and then remain
  religiously affiliated (Baseline + Treatment Dissafiliated) }
\end{itemize}

This allows us to estimate the marginal effect of disaffiliation on
dimensions of political orientation.

In Study 2, we contrast the condition of becoming disaffiliated (done)
with that of being constantly disaffiliated. This approach allows us to
evaluate the religious residue hypothesis
(\citeproc{ref-vantongeren2020}{Van Tongeren \emph{et al.} 2020}), which
predicts recent dones will be more conservative than those who have been
disaffiliated for at least two years. Note that our data do not allow us
to contrast never religious with recent religious disaffiliation because
those are not religious at baseline might have been religious before
baseline.This means that any inferred differences will be conservative
for detecting true effects.

Thus, our causal contrast compares:

\begin{itemize}
\item
  \textbf{TREATMENT: all start with religious affiliation and then lose
  religious affiliation}
\item
  \textbf{CONTRAST: all start with religious disaffiliation and then
  remain religiously disaffiliated}
\end{itemize}

\texttt{lmtp} draws on the \texttt{SuperLearner} library, which
comprises a growing set machine learning algorithms
(\citeproc{ref-SuperLearner2023}{Polley \emph{et al.} 2023}). Given the
size of the data, we used the \texttt{Ranger} estimator, which uses
causal forests to estimate effects (\citeproc{ref-Ranger2017}{Wright and
Ziegler 2017}). Causal forests excel in identifying complex, non-linear
relationships between variables without presupposing a specific model
form and thus making fewer assumptions about the underlying data
distribution.

\paragraph{Cross-Validation}\label{cross-validation}

We implemented a 10-fold cross-validation in \texttt{lmtp}
(\citeproc{ref-williams2021}{Williams and Díaz 2021}). This method
partitions the data into ten subsets of approximately equal size. During
the cross-validation process, nine subsets are used to train the model,
and the remaining subset is used for testing. This process is repeated
ten times, with each of the ten subsets used exactly once as the test
set. Using different subsets for training and validation minimises the
risk of the model over-fit. Because each observation is used for
training and validation the approach is efficient. The cross-validation
process averages over the ten model estimates.

\paragraph{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess sensitivity to unmeasured confounding, we report VanderWeele
and Ding's ``E-value'' in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). To
evaluate strength of evidence, we use the bound of the E-value's 95\%
confidence interval that is closest to 1.

\newpage{}

\subsection{Study 1: + 1 year Causal Effect of Religious Disaffiliation
on Political Orientations (Political Conservativism and Right-Wing
Orientation) in the New Zealand
Population}\label{study-1-1-year-causal-effect-of-religious-disaffiliation-on-political-orientations-political-conservativism-and-right-wing-orientation-in-the-new-zealand-population}

\begin{figure}

\centering{

\includegraphics{24-daryl-dones-pols_files/figure-pdf/fig-ate-1.pdf}

}

\caption{\label{fig-ate}Figure describing the effect of disaffiliation
on political conservativism and right-wing orientation (both
standardised) + 1 year after disaffiliation (ATE).}

\end{figure}%

\phantomsection\label{tbl-ate}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4556}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1778}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0667}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0778}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0889}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1333}}@{}}

\caption{\label{tbl-ate}Table describing the effect of disaffiliation on
political conservativism and right-wing orientation (both standardised)
+ 1 year after disaffiliation (ATE).}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Dis-affiliation Effect: Pol.Conservative & -0.19 & -0.25 & -0.14 & 1.66
& 1.51 \\
Dis-affiliation Effect: Right Wing & -0.08 & -0.14 & -0.02 & 1.36 &
1.16 \\

\end{longtable}

The Average Treatment Effect (ATE) represents the expected difference in
outcomes between treatment and control groups for the population.

For the outcome `Dis-affiliation Effect: Right Wing', the ATE is -0.08
{[}-0.14,-0.02{]}. The E-value for this effect estimate is 1.36 with a
lower bound of 1.16. At this bound, an unmeasured confounder associated
with both the treatment and outcome by a risk ratio of 1.16 each could
explain away the observed effect; weaker confounding would not. Here, we
find evidence for causality.

For the outcome `Dis-affiliation Effect: Pol.Conservative', the ATE is
-0.19 {[}-0.25,-0.14{]}. The E-value for this effect estimate is 1.66
with a lower bound of 1.51. At this bound, an unmeasured confounder
associated with both the treatment and outcome by a risk ratio of 1.51
each could explain away the observed effect; weaker confounding would
not. Here again, we find evidence for causality.

\newpage{}

\subsection{Study 2 Causal Effect of Religious Disaffiliation on
Political Conservativism and Right Wing Orientation (both outcomes were
standardised) contrasted with consistent
disaffiliation}\label{study-2-causal-effect-of-religious-disaffiliation-on-political-conservativism-and-right-wing-orientation-both-outcomes-were-standardised-contrasted-with-consistent-disaffiliation}

\begin{figure}

\centering{

\includegraphics{24-daryl-dones-pols_files/figure-pdf/fig-contrast-1.pdf}

}

\caption{\label{fig-contrast}Figure describing the effect of
disaffiliation on political conservativism and right-wing orientation
(both outcomes were standardised) contrasted with constant
dissafiliation + 1 year after treatment (ATE)}

\end{figure}%

\phantomsection\label{tbl-att}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1633}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0612}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0714}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0816}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1224}}@{}}

\caption{\label{tbl-contrast}Table describing the effect of
disaffiliation on political conservativism and right-wing orientation
(both outcomes were standardised) contrasted with the prevalence effect
of dissafiliation + 1 year after contrast (ATE)}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Dis-affiliation Contrast (ATE): Pol.Conservative & 0.07 & 0.02 & 0.12 &
1.33 & 1.11 \\
Dis-affiliation Contrast (ATE): Right Wing & 0.00 & -0.05 & 0.05 & 1.00
& 1.00 \\

\end{longtable}

For the outcome `Dis-affiliation Contrast (ATE): Pol.Conservative', the
ATE is 0.07 {[}0.02,0.12{]}. The E-value for this effect estimate is
1.33 with a lower bound of 1.11. At this bound, an unmeasured confounder
associated with both the treatment and outcome by a risk ratio of 1.11
each could explain away the observed effect; weaker confounding would
not. Here, we find some evidence for causality: a hypothetical world in
which everyone in the population was religiously affiliated and became
disaffiliated would be a world in which the population is higher in
political conservativism compared with a world in which people had not
been religiously affiliated in the first place, and remained
unaffiliated.

For the outcome `Dis-affiliation Contrast (ATE): Right Wing', given the
lower bound of the E-value equals 1, we find no reliable evidence for
causality. That is, we do not find any difference only right/left-wing
political orientation between the hypothetical world in which everyone
in the population was religiously affiliated and became disaffiliated
compared with a world in which people had not been religiously
affiliated in the first place, and remained unaffiliated.

\subsection{Discussion}\label{discussion}

\subsubsection{Religious change affects political attitudes, although
prior religious affiliation may leave a
``residue''}\label{religious-change-affects-political-attitudes-although-prior-religious-affiliation-may-leave-a-residue}

Here, we target valid inference for the causal effects of religious
disaffiliation on political attitudes by: (1) clearly specifying the
causal quantities of interest; (2) stating the assumptions required to
obtain these quantity from data; (3) providing a robust non-parametric
statistical estimator specified with minimal modelling assumptions; (4)
obtaining the relevant panel data and ordering these data such that
confounders are measured before causes and causes are measured before
their effects (\citeproc{ref-bulbulia2023}{Bulbulia 2023}).

Study 1 investigates a hypothetical treatment in which religious people
were randomised to disaffiliate (as dones) compared with a hypothetical
treatment in which they were randomised to remained religious. We
observe that the recently disaffiliated population is expected to be
less politically conservative than the consistently religious
population.

Study 2 investigates a hypothetical treatment in which religious people
were randomised to disaffiliate (as dones) compared with a hypothetical
treatment in which they were disaffiliated at baseline and remained
disaffiliated in the treatment wave. This contrast allows us to evaluate
the religious residue effect. We observe that the recently disaffiliated
population is expected to be more politically conservative than the
consistently dissafilliated population, but is not reliably different in
political right-wing orientation. This finding offers preliminarhy
evidence for a ``religious residue'' on conservativism Van Tongeren
\emph{et al.} (\citeproc{ref-vantongeren2020}{2020}).

\subsubsection{Summary}\label{summary}

This study provides robust evidence that religious disaffiliation causes
liberal political orientation. Moreover, we find evidence for a
religious residue effect such that liberal effect does not quite align
the disaffiliated with those who have been disaffilated for longer
(perhaps never affiliated). As New Zealand society grows more
disenchanted with religion, we may expect that it will grow more
disenchanted with political conservativism, at least in the near term.

Again, whether the causal effects we observe in New Zealand transport to
other societies remains unknown, and an open matter for future
investigations.

\newpage{}

\subsubsection{Ethics}\label{ethics}

The NZAVS is reviewed every three years by the University of Auckland
Human Participants Ethics Committee. Our most recent ethics approval
statement is as follows: The New Zealand Attitudes and Values Study was
approved by the University of Auckland Human Participants Ethics
Committee on 26/05/2021 for six years until 26/05/2027, Reference Number
UAHPEC22576.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religion Trust (TRT0418). JB received support from the Max
Planck Institute for the Science of Human History. The funders had no
role in preparing the manuscript or deciding to publish it.

\subsubsection{Author Statement}\label{author-statement}

TBA\ldots{} e.g.~

\begin{itemize}
\tightlist
\item
  DVT conceived of the study.
\item
  CS led NZAVS data collection.
\item
  JB developed the inferential approach and did the analysis.
\end{itemize}

\newpage{}

\subsection{References}\label{references}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, J (2024) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-bulbulia2023}
Bulbulia, JA (2023) Causal diagrams (directed acyclic graphs): A
practical guide.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.
doi:\href{https://doi.org/10.1207/s15327752jpa8301_04}{10.1207/s15327752jpa8301\_04}.

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a new zealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-hernan2023}
Hernan, MA, and Robins, JM (2023) \emph{Causal inference}, Taylor \&
Francis. Retrieved from
\url{https://books.google.co.nz/books?id=/_KnHIAAACAAJ}

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-hoverd_religious_2010}
Hoverd, WJ, and Sibley, CG (2010) Religious and denominational diversity
in new zealand 2009. \emph{New Zealand Sociology}, \textbf{25}(2),
59--87.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-SuperLearner2023}
Polley, E, LeDell, E, Kennedy, C, and van der Laan, M (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://github.com/ecpolley/SuperLearner}

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the new zealand attitudes and values study}}.

\bibitem[\citeproctext]{ref-sibley2012a}
Sibley, CG, and Bulbulia, J (2012) Faith after an earthquake: A
longitudinal study of religion and perceived health before and after the
2011 christchurch new zealand earthquake. \emph{PloS One},
\textbf{7}(12), e49648.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in New Zealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-stronge2019onlychild}
Stronge, S, Shaver, JH, Bulbulia, J, and Sibley, CG (2019) Only children
in the 21st century: Personality differences between adults with and
without siblings are very, very small. \emph{Journal of Research in
Personality}, \textbf{83}, 103868.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vanderlaan2011}
Van Der Laan, MJ, and Rose, S (2011) \emph{Targeted Learning: Causal
Inference for Observational and Experimental Data}, New York, NY:
Springer. Retrieved from
\url{https://link.springer.com/10.1007/978-1-4419-9782-1}

\bibitem[\citeproctext]{ref-vanderlaan2018}
Van Der Laan, MJ, and Rose, S (2018) \emph{Targeted Learning in Data
Science: Causal Inference for Complex Longitudinal Studies}, Cham:
Springer International Publishing. Retrieved from
\url{http://link.springer.com/10.1007/978-3-319-65304-4}

\bibitem[\citeproctext]{ref-vantongeren2020}
Van Tongeren, DR, DeWall, CN, Chen, Z, Sibley, CG, and Bulbulia, J
(2020) Religious residue: Cross-cultural evidence that religious
psychology and behavior persist following deidentification.
\emph{Journal of Personality and Social Psychology}.

\bibitem[\citeproctext]{ref-vanderweele2009}
VanderWeele, TJ (2009) Concerning the consistency assumption in causal
inference. \emph{Epidemiology}, \textbf{20}(6), 880.
doi:\href{https://doi.org/10.1097/EDE.0b013e3181bd5638}{10.1097/EDE.0b013e3181bd5638}.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the e-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 120.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437466.

\bibitem[\citeproctext]{ref-williams_cyberostracism_2000}
Williams, KD, Cheung, CKT, and Choi, W (2000) Cyberostracism: Effects of
being ignored over the internet. \emph{Journal of Personality and Social
Psychology}, \textbf{79}(5), 748--762.
doi:\href{https://doi.org/10.1037/0022-3514.79.5.748}{10.1037/0022-3514.79.5.748}.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{Lmtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\bibitem[\citeproctext]{ref-wilson2014differences}
Wilson, MS, Bulbulia, J, and Sibley, CG (2014) Differences and
similarities in religious and paranormal beliefs: A typology of distinct
faith signatures. \emph{Religion, Brain \& Behavior}, \textbf{4}(2),
104--126.

\bibitem[\citeproctext]{ref-Ranger2017}
Wright, MN, and Ziegler, A (2017) {ranger}: A fast implementation of
random forests for high dimensional data in {C++} and {R}. \emph{Journal
of Statistical Software}, \textbf{77}(1), 1--17.
doi:\href{https://doi.org/10.18637/jss.v077.i01}{10.18637/jss.v077.i01}.

\end{CSLReferences}

\newpage{}

\subsection{Appendix A: Measurues}\label{appendix-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth'').

\paragraph{Charitable Donations}\label{charitable-donations}

Using one item from Hoverd and Sibley
(\citeproc{ref-hoverd_religious_2010}{2010}), we asked participants,
``How much money have you donated to charity in the last year?''. To
stabilise this indicator, we took the natural log of the response + 1.

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

We asked participants, ``What is your highest level of qualification?''.
We coded participans highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school quals coded as Level 3, and all other ancillary
categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants, ``Are you currently employed? (This includes
self-employed or casual work)''. * note: This question disappeared in
the updated NZAVS Technical documents (Data Dictionary).

\paragraph{Ethnicity}\label{ethnicity}

Based on the New Zealand Census, we asked participants, ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Felt Belongingness}\label{felt-belongingness}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (\citeproc{ref-hagerty1995}{Hagerty and Patusky
1995}): (1) ``Know that people in my life accept and value me''; (2)
``Feel like an outsider''; (3) ``Know that people around me share my
attitudes and beliefs''. Participants responded on a scale from 1 (Very
Inaccurate) to 7 (Very Accurate). The second item was reversely coded.

\paragraph{Gender (waves: 1-15)}\label{gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\paragraph{Has Siblings}\label{has-siblings}

``Do you have siblings?'' (\citeproc{ref-stronge2019onlychild}{Stronge
\emph{et al.} 2019})

\paragraph{Hours of Childcare}\label{hours-of-childcare}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours Volunteering}\label{hours-volunteering}

We measured hours of volunteering using one item from Sibley \emph{et
al.} (\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
voluntary/charitable work.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Work}\label{hours-of-work}

We measured hours of work using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}):``Hours spent \ldots{} working in paid
employment.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked ``Please estimate your total household income
(before tax) for the year XXXX''. To stabilise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Living in an Urban Area (waves:
1-15)}\label{living-in-an-urban-area-waves-1-15}

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

We coded whether they were living in an urban or rural area (1 = Urban,
0 = Rural) based on the addresses provided.

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants' personalities with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}), which consists of six dimensions and each
dimension is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I often forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{Opt-in}\label{opt-in}

The New Zealand Attitudes and Values Study allows opt-ins to the study.
Because the opt-in population may differ from those sampled randomly
from the New Zealand electoral roll; although the opt-in rate is low, we
include an indicator (yes/no) for this variable.

\paragraph{NZSEI-13 (waves: 8-15)}\label{nzsei-13-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017}). This index uses the income, age, and education of
a reference group, in this case, the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

We asked participants, ``If you are a parent, what is the birth date of
your eldest child?''.

\paragraph{Parent (waves: 5-15)
--\textgreater{}}\label{parent-waves-5-15}

We asked participants, ``If you are a parent, what is the birth date of
your eldest child?'' or ``If you are a parent, in which year was your
eldest child born?'' (waves: 10-15). Parents were coded as 1, while the
others were coded as 0. --\textgreater{}

\paragraph{Politically Conservative}\label{politically-conservative}

We measured participants' political conservative orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{Politically Right Wing}\label{politically-right-wing}

We measured participants' political right-wing orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically left-wing versus right-wing you see
yourself as being..''

(1 = Extremely left-wing to 7 = Extremely right-wing)

\paragraph{Relationship status}\label{relationship-status}

``What is your relationship status?'' (e.g., single, married, de-facto,
civil union, widowed, living together, etc.)

\paragraph{Religion Affiliation}\label{religion-affiliation}

Participants were asked to indicate their religion identification (``Do
you identify with a religion and/or spiritual group?'') on a binary
response (1 = Yes, 0 = No). We then asked, ``What religion or spiritual
group?'' These questions are used in the New Zealand Census

\paragraph{Support}\label{support}

Participants' perceived social support was measured using three items
from Cutrona and Russell (\citeproc{ref-cutrona1987}{1987}) and Williams
\emph{et al.} (\citeproc{ref-williams_cyberostracism_2000}{2000}): (1)
``There are people I can depend on to help me if I really need it''; (2)
``There is no one I can turn to for guidance in times of stress''; (3)
``I know there are people I can turn to when I need help.'' Participants
indicated the extent to which they agreed with those items (1 = Strongly
Disagree to 7 = Strongly Agree). The second item was negatively worded,
so we reversely recorded the responses to this item.

\paragraph{Volunteers}\label{volunteers}

We asked participants,``Please estimate how many hours you spent doing
each of the following things last week'' and responded to an item
(``voluntary/charitable work'') from (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}).

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{table}

\caption{\label{tbl-B}}

\centering{

\captionsetup{labelsep=none}

}

\end{table}%

\begin{longtable}[]{@{}ll@{}}
\caption{Baseline demography
statistics}\label{tbl-table-demography}\tabularnewline
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,202} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,202} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & \\
Mean (SD) & 49 (14) \\
Range & 18, 99 \\
IQR & 39, 60 \\
\textbf{Agreeableness} & \\
Mean (SD) & 5.35 (0.99) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.00 \\
\textbf{Belong} & \\
Mean (SD) & 5.14 (1.08) \\
Range & 1.00, 7.00 \\
IQR & 4.33, 6.00 \\
\textbf{Belong Beliefs} & \\
1 & 794 (1.7\%) \\
2 & 2,011 (4.3\%) \\
3 & 4,273 (9.2\%) \\
4 & 11,673 (25\%) \\
5 & 13,505 (29\%) \\
6 & 11,659 (25\%) \\
7 & 2,769 (5.9\%) \\
\textbf{Born Nz} & 36,834 (78\%) \\
\textbf{Charity Donate log} & \\
Mean (SD) & 1.16 (1.61) \\
Range & 0.00, 5.13 \\
IQR & 0.00, 2.40 \\
\textbf{Conscientiousness} & \\
Mean (SD) & 5.11 (1.06) \\
Range & 1.00, 7.00 \\
IQR & 4.50, 6.00 \\
\textbf{Education Level Coarsen} & \\
no\_qualification & 1,217 (2.6\%) \\
cert\_1\_to\_4 & 16,581 (36\%) \\
cert\_5\_to\_6 & 5,941 (13\%) \\
university & 12,510 (27\%) \\
post\_grad & 5,099 (11\%) \\
masters & 3,901 (8.4\%) \\
doctorate & 1,120 (2.4\%) \\
\textbf{Employed} & 37,497 (80\%) \\
\textbf{Eth Cat} & \\
euro & 37,660 (81\%) \\
maori & 5,345 (11\%) \\
pacific & 1,108 (2.4\%) \\
asian & 2,466 (5.3\%) \\
\textbf{Extraversion} & \\
Mean (SD) & 3.91 (1.20) \\
Range & 1.00, 7.00 \\
IQR & 3.00, 4.75 \\
\textbf{Have Siblings} & 44,081 (95\%) \\
\textbf{Hlth Bmi} & \\
Mean (SD) & 27.2 (5.9) \\
Range & 12.3, 73.6 \\
IQR & 23.2, 30.1 \\
\textbf{Honesty Humility} & \\
Mean (SD) & 5.41 (1.18) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.25 \\
\textbf{Hours Charity log} & \\
Mean (SD) & 0.43 (0.78) \\
Range & 0.00, 4.62 \\
IQR & 0.00, 0.69 \\
\textbf{Hours Children log} & \\
Mean (SD) & 4.57 (2.50) \\
Range & 0.00, 13.12 \\
IQR & 3.26, 6.22 \\
\textbf{Hours Exercise log} & \\
Mean (SD) & 1.54 (0.85) \\
Range & 0.00, 4.39 \\
IQR & 1.10, 2.08 \\
\textbf{Hours Housework log} & \\
Mean (SD) & 2.14 (0.78) \\
Range & 0.00, 5.13 \\
IQR & 1.70, 2.71 \\
\textbf{Hours Work log} & \\
Mean (SD) & 2.66 (1.58) \\
Range & 0.00, 4.62 \\
IQR & 1.39, 3.71 \\
\textbf{Household Inc log} & \\
Mean (SD) & 11.39 (0.77) \\
Range & 0.69, 14.92 \\
IQR & 11.00, 11.92 \\
\textbf{Male} & 29,744 (63\%) \\
\textbf{Neighbourhood Community} & \\
1 & 2,973 (6.3\%) \\
2 & 5,877 (13\%) \\
3 & 6,927 (15\%) \\
4 & 9,734 (21\%) \\
5 & 9,773 (21\%) \\
6 & 7,949 (17\%) \\
7 & 3,712 (7.9\%) \\
\textbf{Neuroticism} & \\
Mean (SD) & 3.49 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 2.75, 4.25 \\
\textbf{Nz Dep2018} & \\
Mean (SD) & 4.77 (2.73) \\
Range & 1.00, 10.00 \\
IQR & 2.00, 7.00 \\
\textbf{Nzsei 13 l} & \\
Mean (SD) & 54 (17) \\
Range & 10, 90 \\
IQR & 41, 69 \\
\textbf{Openness} & \\
Mean (SD) & 4.96 (1.12) \\
Range & 1.00, 7.00 \\
IQR & 4.25, 5.75 \\
\textbf{Parent} & 33,444 (71\%) \\
\textbf{Partner} & 34,660 (75\%) \\
\textbf{Rural Gch 2018 l} & \\
1 & 29,050 (62\%) \\
2 & 8,851 (19\%) \\
3 & 5,779 (12\%) \\
4 & 2,647 (5.6\%) \\
5 & 569 (1.2\%) \\
\textbf{Sample Frame Opt in} & 1,379 (2.9\%) \\
\textbf{Support} & \\
Mean (SD) & 5.95 (1.12) \\
Range & 1.00, 7.00 \\
IQR & 5.33, 7.00 \\
\textbf{Urban} & 37,901 (81\%) \\
\end{longtable}

Table~\ref{tbl-table-demography} presents baseline demographic
statistics for couples who met inclusion criteria.

\subsection{Appendix C: Baseline and Treatment Wave Exposure
Statistics}\label{appendix-exposures}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4247}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}@{}}
\caption{Baseline and Exposure Wave
Responses}\label{tbl-table-exposures}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,202
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 47,202
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,202
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 47,202
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Alert Level Combined} & & \\
no\_alert & 47,202 (100\%) & 24,761 (71\%) \\
early\_covid & 0 (0\%) & 3,895 (11\%) \\
alert\_level\_1 & 0 (0\%) & 3,008 (8.7\%) \\
alert\_level\_2 & 0 (0\%) & 864 (2.5\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 569 (1.6\%) \\
alert\_level\_4 & 0 (0\%) & 1,646 (4.7\%) \\
Unknown & 0 & 12,459 \\
\textbf{Religious Affiliation} & 17,141 (36\%) & 11,807 (34\%) \\
Unknown & 0 & 12,459 \\
\end{longtable}

Table~\ref{tbl-table-exposures} presents baseline (NZAVS time 10) and
exposure wave (NZAVS time 11) statistics for the exposure variable:
religious affiliation (yes/no). Those who did not respond to religious
affiliation were coded as ``0''. Because the treatment wave (NZAVS time
11) occurred to New Zealand's COVID-19 pandemic, all models adjusted for
the pandemic alert-level. The pandemic is a not a ``confounder'' because
a confounder must be related to the treatment and the outcome. At the
end of the study measurement, all had been exposed to the pandemic.
However, to satisfy the causal consistency assumption, all treatments
must be conditionally equivalent within levels of all covariates
(\citeproc{ref-vanderweele2013}{VanderWeele and Hernan 2013}). Evidence
shows that dangerous natural events may affect religious affiliation
(\citeproc{ref-sibley2012a}{Sibley and Bulbulia 2012}). To better enable
conditional independence within levels of the treatment variable, we
conditioned on the lead value of COVID-alert level at baseline. To
mitigate systematic biases arising from attrition, and missingness,
\texttt{lmtp} package uses inverse probability of censoring weights,
which were use when estimating the causal effects of the exposure on the
outcome.

\subsubsection{Transition Table for The
Treatment}\label{transition-table-for-the-treatment}

Table~\ref{tbl-transition} shows a transition matrix that captures
stability and movement between disinhibition responses from the baseline
(NZAVS time 10) wave and exposure wave (NZAVS time 11) among all
participants who responded to the religion question at baseline and in
the following year (the censored sample). Entries on the diagonal (in
bold) indicate the number of individuals who stayed in their initial
state. In contrast, the off-diagonal shows the transitions from the
initial state (bold) to another state the following wave (off-diagonal).
A cell located at the intersection of row \(i\) and column \(j\), where
\(i \neq j\), shows the count of individuals moving from state \(i\) to
state \(j\).

\begin{longtable}[]{@{}ccc@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave. The diagonal shows stability in response. The
off-diagonal shows the number of transitions from the initial state
(bold) to another state in the following wave
(off-diagonal).}\label{tbl-transition}\tabularnewline
\toprule\noalign{}
From & Not Religious & Religious \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & Not Religious & Religious \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Not Religious & \textbf{20959} & 1183 \\
Religious & 1977 & \textbf{10624} \\
\end{longtable}

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4247}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}@{}}
\caption{Baseline and Outcome Wave Responses for the
Outcome}\label{tbl-table-outcomes}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,202
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 47,202
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Baseline/Outcome Variables}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 47,202
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 47,202
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Political Right Wing} & & \\
1 & 1,819 (4.1\%) & 1,293 (4.3\%) \\
2 & 6,736 (15\%) & 5,309 (18\%) \\
3 & 8,456 (19\%) & 6,226 (21\%) \\
4 & 16,288 (37\%) & 10,033 (33\%) \\
5 & 6,812 (15\%) & 4,740 (16\%) \\
6 & 3,186 (7.2\%) & 2,042 (6.8\%) \\
7 & 768 (1.7\%) & 480 (1.6\%) \\
Unknown & 3,137 & 17,079 \\
\textbf{Political Conservative} & & \\
1 & 2,510 (5.6\%) & 1,885 (6.2\%) \\
2 & 8,662 (19\%) & 6,336 (21\%) \\
3 & 8,802 (20\%) & 6,576 (21\%) \\
4 & 13,866 (31\%) & 9,552 (31\%) \\
5 & 6,679 (15\%) & 4,082 (13\%) \\
6 & 3,292 (7.4\%) & 1,793 (5.9\%) \\
7 & 736 (1.7\%) & 409 (1.3\%) \\
Unknown & 2,655 & 16,569 \\
\end{longtable}

Table~\ref{tbl-table-outcomes} presents baseline and wave 1 statistics
for the outcome variables. We see an overall shift in levels of
conservativism and right-wing political orientation. Additionally, we
observe 16,569 missing values. To mitigate systematic biases arising
from attrition and missingness, \texttt{lmtp} package uses inverse
probability of censoring weights.



\end{document}
