% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Quantifying Causal Effects of Political Conservativism on Environmental Attitudes Using National Panel Data Reveals Longitudinal Growth is Not Causation},
  pdfauthor={Inkuk E Kim; Chris G. Sibley; Joseph A. Bulbulia},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Quantifying Causal Effects of Political Conservativism on
Environmental Attitudes Using National Panel Data Reveals Longitudinal
Growth is Not Causation}

\usepackage{academicons}
\usepackage{xcolor}

  \author{Inkuk E Kim}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0003-3169-6576 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Chris G. Sibley}
            \affil{%
             \small{     School of Psychology, University of Auckland
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-4064-8800 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Joseph A. Bulbulia}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5861-2056 }
              }
      


\date{2024-11-01}
\begin{document}
\maketitle
\begin{abstract}
Whether political conservativism affects environmental attitudes is a
topic of considerable interest and ongoing debate. This question is
challenging to address because political conservativism cannot be
manipulated. Moreover, observational data, even when longitudinal, do
not clarify causality. Here, we use a three-wave outcome-wide panel of
38,000 New Zealanders (2020-2023) to estimate the causal effects of
political conservativism on a range of environmental attitudes and
behaviours. Controlling for pre-existing differences in both political
conservativism and environmental attitudes and demographic variables, we
find that the effect of political conservativism reduces acceptance of
beliefs in climate change, belief in human-caused climate change, and
climate change concern, but it does not affect perceived environmental
efficacy compared with observed attitudes. We find that a two-point
decrease in political conservatism only affects beliefs in the reality
of climate change. Here, we find that associations in the data are
misleading guides to causality. \textbf{KEYWORDS}: \emph{Causal
Inference}; \emph{Climate Change}; \emph{Conservativism};
\emph{Cross-validation}; \emph{Environmental}, \emph{Longitudinal};
\emph{Machine Learning}; \emph{Political}; \emph{Semi-parametric}.
\end{abstract}


\subsection{Introduction}\label{introduction}

A central question in political psychology is whether Political
Conservativism affects attitudes toward the environment. Causality is
difficult to establish because Political Conservativism---which involves
deeply held convictions about right and wrong---cannot be manipulated
experimentally. Observational studies, including longitudinal ones,
typically report correlations or patterns of growth. However, causal
interpretations of correlations and growth are subject to
well-understood biases.

Here, we leverage comprehensive panel data from 44,658 participants in
the New Zealand Attitudes and Values Study, spanning NZAVS time 10,
years 2018-2019, NZAVS time 11-13, years 2019-2022, and NZAVS time 14,
years 2022-2023, to quantify the effects of clearly defined
interventions in Political Conservativism across the population of New
Zealanders.

\subsection{Method}\label{method}

We define a causal effect as the difference in average outcomes between
groups of people who experience different conditions based on planned
interventions. The outcomes are measured across the whole population
after one condition and compared to outcomes measured after another
condition. These different outcomes are called ``counterfactual'' or
``potential'' outcomes because each person can only experience one
condition, so the outcome under the unexperienced condition must be
estimated.

This challenge of estimating counterfactuals is well understood in
randomised experiments. In such experiments, although we cannot observe
what would have happened if a person had received a different treatment,
random assignment ensures that the average outcomes between groups are
comparable. This allows us to reliably estimate the difference between
treatments at the population level.

However, in observational studies, where treatments are not randomised,
we must make additional assumptions and apply special methods to address
biases in manifest correlations. Such assumptions and methods aim to
\emph{balance} the groups on variables that might influence both the
treatment and the outcome (\citeproc{ref-pearl2009}{Pearl 2009a};
\citeproc{ref-robins1986}{Robins 1986}; \citeproc{ref-rubin2005}{Rubin
2005}; \citeproc{ref-neyman1923}{Splawa-Neyman 1990 (orig. 1923)};
\citeproc{ref-vanderlaan2018}{Van Der Laan and Rose 2018}). We begin our
workflow by stating the target population for whom inferences are meant
to generalise and the specific causal contrasts of interest for this
study.

\subsubsection{Sample}\label{sample}

\subsubsection{Target Population}\label{target-population}

The target population for this study comprises New Zealand residents as
represented by the New Zealand Attitudes and Values Study (NZAVS) during
NZAVS time 10, years 2018-2019 weighted by New Zealand Census weights
for age, gender, and ethnicity (refer to Sibley
(\citeproc{ref-sibley2021}{2021})). The NZAVS is a national probability
study designed to accurately reflect the broader New Zealand population.
Despite its comprehensive scope, the NZAVS has some limitations in its
demographic representation. Notably, it tends to under-sample males and
individuals of Asian descent while over-sampling females and Māori (the
indigenous peoples of New Zealand). To address these disparities and
enhance the accuracy of our findings, we apply New Zealand Census survey
weights to the sample data.

These weights adjust for variations in age, gender, and ethnicity to
better approximate the national demographic composition
(\citeproc{ref-sibley2021}{Sibley 2021}). Survey weights were integrated
into statistical models using the \texttt{weights} option in
\texttt{lmtp} (\citeproc{ref-williams2021}{Williams and Díaz 2021}),
following protocols stated in
(\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024a}).

\subsubsection{Eligibility Criteria}\label{eligibility-criteria}

To be included in the analysis of this study, participants needed to
participate in NZAVS time 10, years 2018-2019 and respond to baseline
measure of the Political Conservativism.

Missing covariate data at 2018 were permitted. The proportion of missing
data at baseline was: 1.12.

Participants may have been lost to follow-up at the end of the study if
they met eligibility criteria.

A total of 44,658 individuals met these criteria and were included in
the study.

\paragraph{Causal Estimands}\label{causal-estimands}

\begin{itemize}
\tightlist
\item
  \(A\) = intervention on population in political orientation for three
  years after baseline wave (i.e.~controlling for baseline covariates).
\item
  \(Y\) = outcome: (environment orientation dimension).
\item
  \(L\) = baseline covariates (political orientation, the baseline
  environmental attitudes, and demographic covariates).
\end{itemize}

\subsection{Intervention Types}\label{intervention-types}

We define three specific shift interventions on the Political
Conservativism` trait, which is bounded between 1 and 7:

\subsubsection{1. Gain in Political Orientation
(+1)}\label{gain-in-political-orientation-1}

We define the shift-up intervention as:

\[
a^+ = f(A) = 
\begin{cases}
A + 1, & \text{if } A + 1 \leq 7 \\
7, & \text{if } A + 1 > 7
\end{cases}
\]

This ensures that the shifted value does not exceed the maximum score of
7.

\subsubsection{2. Loss in Political Orientation
(-1)}\label{loss-in-political-orientation--1}

We define the shift-down intervention as:

\[
a^{-} = f(A) = 
\begin{cases}
A - 1, & \text{if } A - 1 \geq 1 \\
1, & \text{if } A - 1 < 1
\end{cases}
\]

This ensures that the shifted value does not go below the minimum score
of 1.

\subsubsection{3. Null (no change)}\label{null-no-change}

The null intervention leaves the exposure at its observed value:

\[
a = A
\]

\subsubsection{Potential Outcomes}\label{potential-outcomes}

For any intervention where we set the subjects political orientation to
level \(\tilde{a}\):

\begin{quote}
\(E[Y(\tilde{a})]\) denotes the potential outcome in an environmental
orientation when the population is intervened upon.
\end{quote}

\subsubsection{Assumptions}\label{assumptions}

To identify these potential outcomes, we assume conditional
exchangeability given measured covariates \(L\):

\[
\Big\{ Y(\tilde{a}) \Big\} \coprod A \mid L
\]

This means that, conditional on \(L\), the treatment assignments
\(A = \tilde{a}\) are `as good as random.' This allows us to estimate
causal effects from observed data.

\subsubsection{Causal Effects}\label{causal-effects}

We specify causal effects by contrasting potential outcomes under these
interventions, as they occurred for three years after the baseline
wave(baseline + 3 years). To ensure temporal order in causal inferences,
we measure outcomes at the end of the study (NZAVS time 14, years
2022-2023) (refer to VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020})).

\subsection{Measures}\label{measures}

\subsubsection{Exposure Variable}\label{exposure-variable}

\paragraph{Political Conservative}\label{political-conservative}

\emph{Please rate how politically liberal versus conservative you see
yourself as being.}

Ordinal response: (1 = Extremely Liberal, 7 = Extremely Conservative)
(\citeproc{ref-jost_end_2006-1}{Jost 2006})

\subsubsection{Outcome Variables}\label{outcome-variables}

\paragraph{Deny Climate Change is
Human-Caused}\label{deny-climate-change-is-human-caused}

\emph{1. Climate change is caused by humans (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-sibley2013model}{Sibley and Kurz 2013}).

\paragraph{Deny Climate Change
Concern}\label{deny-climate-change-concern}

\emph{I am deeply concerned about climate change (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree). Developed
for the NZAVS.

\paragraph{Deny Climate Change
Reality}\label{deny-climate-change-reality}

\emph{Climate change is real (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-sibley2013model}{Sibley and Kurz 2013}).

\paragraph{Deny Environmental
Efficacy}\label{deny-environmental-efficacy}

\emph{By taking personal action I believe I can make a positive
difference to environmental problems (reversed)} \emph{I feel I can make
a difference to the state of the environment (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-sharma2008we}{Sharma 2008}).

\paragraph{Dissatisfied with the New Zealand
Environment}\label{dissatisfied-with-the-new-zealand-environment}

\emph{Please rate your level of satisfaction with the following aspects
of your life and New Zealand\ldots The quality of New Zealand's natural
environment (reversed).}

Ordinal response: (0 = Completely Dissatisfied, 10 = Completely
Datisfied) (\citeproc{ref-tiliouine_measuring_2006}{Tiliouine \emph{et
al.} 2006}).

\subsubsection{Causal Assumptions}\label{causal-assumptions}

Having stated our interventions of interest, the target population for
whom generalisations apply, and our measures, we next consider whether
and how we may identify these effects using time-series data. Rather
than testing specific hypotheses, we aim to estimate these pre-specified
causal effects on the target population as accurately as possible. We
achieve this by combining detailed time-series data with robust methods
for causal inference (\citeproc{ref-hernan2024stating}{Hernán and
Greenland 2024}).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{The Causal Consistency Assumption}: The observed outcome under
  the observed political\_conservative is equal to the potential outcome
  under that exposure level.
\item
  \textbf{The Positivity Assumption}: There is a non-zero probability of
  receiving each level of political\_conservative for every combination
  of values of political\_conservative and confounders in the
  population.
\item
  \textbf{The Assumption of No Unmeasured Confounding}: All variables
  that affect both political\_conservative and the outcome have been
  measured and accounted for in the analysis.
\item
  \textbf{The Assumption of No Interference}: The potential outcomes for
  one individual are not affected by the political\_conservative status
  of other individuals.
\end{enumerate}

These assumptions are critical for the causal interpretability of our
results and should be carefully considered in light of the study design
and available data.

\subsubsection{Confounding Control}\label{confounding-control}

To address confounding in our analysis, we implement
(\citeproc{ref-vanderweele2019}{VanderWeele 2019})'s \emph{modified
disjunctive cause criterion} by following these steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Identify all common causes} of both the treatment and
  outcomes.
\item
  \textbf{Exclude instrumental variables} that affect the exposure but
  not the outcome. Instrumental variables do not contribute to
  controlling confounding and can reduce the efficiency of the
  estimates.
\item
  \textbf{Include proxies for unmeasured confounders} affecting both
  exposure and outcome. According to the principles of d-separation
  Pearl (\citeproc{ref-pearl2009a}{2009b}), using proxies allows us to
  control for their associated unmeasured confounders indirectly.
\item
  \textbf{Control for baseline Political Conservativism} and all outcome
  variables (refer to VanderWeele \emph{et al.}
  (\citeproc{ref-vanderweele2020}{2020}).)
\end{enumerate}

\hyperref[appendix-demographics]{Appendix B} details the covariates we
included for confounding control. These methods adhere to the guidelines
provided in (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024a}) and
were pre-specified in our study protocol \url{https://osf.io/ce4t9/}.

Table~\ref{tbl-swig} a schematic of our confounding control strategy. A
Single World Intervention Template is a causal graph used to generate
multiple counterfactual graphs, illustrating potential outcomes under an
intervention (\citeproc{ref-bulbulia2024swigstime}{Bulbulia 2024c};
\citeproc{ref-richardson2013swigsprimer}{Richardson and Robins 2013},
\citeproc{ref-richardson2023potential}{2023};
\citeproc{ref-robins2010alternative}{Robins and Richardson 2010}). This
table presents the confounding control strategy adopted in our five-wave
panel study.

\begin{itemize}
\tightlist
\item
  \(U\) represents unmeasured confounders.
\item
  Numerical subscripts denote time, where \(0\) is baseline, \(1\) is
  the treatment wave, and \(\tau\) is the outcome wave (end of study).
  This study includes three measurement intervals.
\item
  \(L_0\) represents all confounders measured at baseline, while \(A_1\)
  denotes the first exposure or treatment. This set includes \(A_0\)
  (baseline treatment) and all baseline outcomes, \(Y_0\).
\item
  \(A_{1:\tau - 1}\) denotes subsequent treatments. In this study, we
  intervene on Political Conservativism at \(A_1\), \(A_2\), and
  \(A_3\).
\item
  \(Y_4\) represents outcomes measured at the end of the study.
\end{itemize}

Solid arrows indicate assumed causal influences. The grey arrow reflects
the assumption that unmeasured confounding is controlled. \(L_{t-k}\)
denotes time-varying confounders that might affect both the next wave's
exposure and final outcome variables. After controlling for baseline
confounders, baseline measures of exposure, and all baseline outcomes,
we assume no further time-varying confounding
(\citeproc{ref-bulbulia2024swigstime}{Bulbulia 2024c}).

Baseline values of the treatment (\(A_0\)) and outcome (\(Y_0\)) are
included to reduce unmeasured confounding. Including these ensures that
any unmeasured confounders influencing \(A_1\) and \(Y_2\) would need to
affect them independently of their baseline states, namely \(A_0\) and
\(Y_0\).

\begin{table}

\caption{\label{tbl-swig}A Single World Intervention Template is a
causal graph that allows us to generate multiple counterfactual graphs
showing the potential outcomes under an intervention
(\citeproc{ref-richardson2013swigsprimer}{Richardson and Robins 2013},
\citeproc{ref-richardson2023potential}{2023};
\citeproc{ref-robins2010alternative}{Robins and Richardson 2010}).
present the confounding control strategy adopted in a three-wave panel
study. By including the baseline measure of the exposure and all
outcomes, for unmeasured confounders to bias the estimate of the causal
effect of the exposures and outcomes they would need to do so
independently of their measured states at baseline
(\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).}

\centering{

\tvfour

}

\end{table}%

\subsubsection{Missing Data}\label{missing-data}

To mitigate bias from missing data, we implement the following
strategies:

\textbf{Baseline missingness}: we employed the \texttt{ppm} algorithm
from the \texttt{mice} package in R (\citeproc{ref-vanbuuren2018}{Van
Buuren 2018}) to impute missing baseline data (wave NZAVS time 12, years
2020-2021). This method allowed us to reconstruct incomplete datasets by
estimating a plausible value for missing observation. Because we could
only pass one data set to the lmtp, we employed single imputation.
Approximately 1.2\% of covariate values were missing at NZAVS time 12,
years 2020-2021. We only used baseline data to impute baseline wave
missingness (refer to Zhang \emph{et al.}
(\citeproc{ref-zhang2023shouldMultipleImputation}{2023})).

\textbf{Exposure wave missingness}: even if the population in the
baseline wave corresponds to the target population, attrition between
NZAVS time 10, years 2018-2019 and NZAVS time 11-13, years 2019-2022 may
threaten generalisations to the target population. To address potential
bias from loss-to-follow up in the exposure wave we employed
non-parametric inverse-probability of censoring weights.

\textbf{Outcome missingness}: to address confounding and selection bias
arising from missing responses and panel attrition at the end of study
NZAVS time 14, years 2022-2023, we applied censoring weights obtained
using nonparametric machine learning ensembles afforded by the
\texttt{lmtp} package (and its dependencies) in R
(\citeproc{ref-williams2021}{Williams and Díaz 2021}).

\subsubsection{Statistical Estimator}\label{statistical-estimator}

\paragraph{Longitudinal Modified Treatment Policy (LMTP)
Estimator}\label{longitudinal-modified-treatment-policy-lmtp-estimator}

We perform statistical estimation using a Sequential Doubly-Robust
Estimator from the \texttt{lmtp} package, which is multiply robust for
repeated treatments across multiple waves
(\citeproc{ref-diaz2023lmtp}{Díaz \emph{et al.} 2023};
\citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023}). This estimator
is robust to misspecification in either the outcome or treatment model
over time. The lmtp package relies on the SuperLearner library,
integrating diverse machine learning algorithms
(\citeproc{ref-SuperLearner2023}{Polley \emph{et al.} 2023}). Given the
high-dimensionality of the data, we used the Ranger estimator, a
non-parametric causal forest method known for its resistance to
overfitting {[}Ranger2017{]}. All statistical models implemented a
10-fold cross-validation. SDR robust method for estimating causal
effects while providing valid statistical uncertainty measures
(\citeproc{ref-van2012targeted}{Laan and Gruber 2012};
\citeproc{ref-van2014targeted}{Van der Laan 2014}). For further
information on targeted learning using the \texttt{lmtp} package, see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023}). Graphs, tables, and output reports
are created using the \texttt{margot} package
(\citeproc{ref-margot2024}{Bulbulia 2024b}).

\subsubsection{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess the sensitivity of results to unmeasured confounding, we
report VanderWeele and Ding's E-value in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). To
evaluate the strength of evidence, we use the bound of the E-value 95\%
confidence interval closest to 1. This provides an approximate metric
for understanding the robustness of our findings in the presence of
potential unmeasured confounding.

\subsection{Results}\label{results}

\subsubsection{Descriptive Findings}\label{descriptive-findings}

Figure~\ref{fig-outcomes-time} shows the predicted means for
multi-dimensional environmental attitudes by Political Conservativism
from NZAVS time 11-13, years 2019-2022 to NZAVS time 14, years
2022-2023. For denial of human-caused climate change, climate concern,
and belief in climate change reality, there is a clear separation by
political conservatism, with conservatives expressing higher levels of
denial across these dimensions. However, even at the high end of
political conservatism, the means are relatively low, especially for
belief in climate change reality, where the conservative average is at
the midpoint of the scale (4 on a 1-7 scale). On the other hand,
conservatives tend to report greater satisfaction with the natural
environment in New Zealand, though dissatisfaction is increasing. The
separation by political conservatism is less pronounced for denial of
personal efficacy in environmental change, with those at the high end of
the political conservatism scale only slightly more inclined to deny
efficacy compared to those at the low end.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-inkuk-pol-env-long_files/figure-pdf/fig-outcomes-time-1.pdf}}

}

\caption{\label{fig-outcomes-time}}

\end{figure}%

\subsubsection{Political Conservativism measured at the Baseline Wave
(NZAVS time 10, years 2018-2019) and the Exposure Wave NZAVS time 11-13,
years
2019-2022}\label{political-conservativism-measured-at-the-baseline-wave-nzavs-time-10-years-2018-2019-and-the-exposure-wave-nzavs-time-11-13-years-2019-2022}

Figure~\ref{fig-exposure-wave} shows the distribution of the exposure
variable in the treatment wave.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-inkuk-pol-env-long_files/figure-pdf/fig-exposure-wave-1.pdf}}

}

\caption{\label{fig-exposure-wave}}

\end{figure}%

\newpage{}

\subsubsection{Evidence for Change in the Treatment
Variable}\label{evidence-for-change-in-the-treatment-variable}

Table~\ref{tbl-transition} clarifies the change in the treatment
variable from the baseline wave to the baseline + 1 wave across the
sample. Assessing change in a variable is essential for evaluating the
positivity assumption and recovering evidence for the incident exposure
effect of the treatment variable (\citeproc{ref-danaei2012}{Danaei
\emph{et al.} 2012}; \citeproc{ref-hernan2024WHATIF}{Hernan and Robins
2024}; \citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1139}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1392}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1139}}@{}}

\caption{\label{tbl-transition}Transition matrix for change in}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 1 & \textbf{2447} & 1544 & 244 & 209 & 49 & 15 & 28 \\
State 2 & 1484 & \textbf{9471} & 3794 & 1180 & 281 & 116 & 19 \\
State 3 & 226 & 3661 & \textbf{7666} & 3684 & 986 & 187 & 27 \\
State 4 & 198 & 1084 & 3570 & \textbf{13843} & 3247 & 764 & 144 \\
State 5 & 36 & 289 & 1144 & 3542 & \textbf{4867} & 1552 & 101 \\
State 6 & 25 & 113 & 216 & 904 & 1728 & \textbf{2254} & 343 \\
State 7 & 18 & 19 & 15 & 170 & 136 & 337 & \textbf{422} \\

\end{longtable}

\newpage{}

\subsection{Results}\label{results-1}

\subsubsection{Study 1: Causal effect of a one unit gain in Political
Conservativism to max 7 (on the exposure unit scale from one to seven)
vs.~no
change}\label{study-1-causal-effect-of-a-one-unit-gain-in-political-conservativism-to-max-7-on-the-exposure-unit-scale-from-one-to-seven-vs.-no-change}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3750}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2000}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0875}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0875}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1500}}@{}}

\caption{\label{tbl-1_1}Causal effect of gain in Political
Conservativism on environmental attitudes.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Humans Cause Climate Change & -0.213 & -0.306 & -0.120 & 1.723 &
1.477 \\
Climate Change Concern & -0.156 & -0.255 & -0.058 & 1.572 & 1.294 \\
Climate Change is Real & -0.134 & -0.238 & -0.031 & 1.512 & 1.198 \\
Satisfied with NZ Environment & 0.136 & 0.045 & 0.227 & 1.518 & 1.254 \\

\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-inkuk-pol-env-long_files/figure-pdf/fig-1_1-1.pdf}}

}

\caption{\label{fig-1_1}Causal effect of gain in Political
Conservativism on environmental attitudes. Contrasts are expressed in
standard deviation units.}

\end{figure}%

Table~\ref{tbl-1_1} and Figure~\ref{fig-1_1} present the comparison of
the intervention: Causal effect of a one unit gain in Political
Conservativism to max 7 (on the exposure unit scale from one to seven)
vs.~no change

\paragraph{Climate change concern}\label{climate-change-concern}

The effect estimate (rd) is -0.156 (-0.255, -0.058). On the original
scale, the estimated effect is -0.271 (-0.442, -0.1). E-value lower
bound is 1.294, indicating evidence for causality.

\paragraph{Climate change is real}\label{climate-change-is-real}

The effect estimate (rd) is -0.134 (-0.238, -0.031). On the original
scale, the estimated effect is -0.193 (-0.341, -0.044). E-value lower
bound is 1.198, indicating evidence for causality.

\paragraph{Humans cause climate
change}\label{humans-cause-climate-change}

The effect estimate (rd) is -0.213 (-0.306, -0.12). On the original
scale, the estimated effect is -0.351 (-0.505, -0.198). E-value lower
bound is 1.477, indicating evidence for causality.

\paragraph{Satisfied with nz
environment}\label{satisfied-with-nz-environment}

The effect estimate (rd) is 0.136 (0.045, 0.227). On the original scale,
the estimated effect is 0.325 (0.108, 0.543). E-value lower bound is
1.254, indicating evidence for causality.

\subsubsection{Study 2: Causal effect of decrease a one unit gain in
Political Conservativism to a minimum of 1 (on the exposure unit scale
from one to seven) vs.~no
change}\label{study-2-causal-effect-of-decrease-a-one-unit-gain-in-political-conservativism-to-a-minimum-of-1-on-the-exposure-unit-scale-from-one-to-seven-vs.-no-change}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3750}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2000}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0875}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0875}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1500}}@{}}

\caption{\label{tbl-2_1}Causal effect of loss in Political
Conservativism on environmental attitudes.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Humans Cause Climate Change & 0.272 & 0.196 & 0.348 & 1.881 & 1.678 \\
Climate Change Concern & 0.128 & 0.023 & 0.232 & 1.496 & 1.174 \\
Climate Change is Real & 0.161 & 0.087 & 0.236 & 1.585 & 1.380 \\
Satisfied with NZ Environment & 0.078 & -0.048 & 0.205 & 1.355 &
1.000 \\

\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-inkuk-pol-env-long_files/figure-pdf/fig-2_1-1.pdf}}

}

\caption{\label{fig-2_1}Causal effect of loss in Political
Conservativism on environmental attitudes. Contrasts are expressed in
standard deviation units.}

\end{figure}%

Table~\ref{tbl-2_1} and Figure~\ref{fig-2_1} present the comparison of
the intervention: Causal effect of a one unit gain in Political
Conservativism to max 7 (on the exposure unit scale from one to seven)
vs.~no change

\subsection{Discussion}\label{discussion}

Our results provide important insights into the relationship between
political conservatism and environmental attitudes in New Zealand. The
descriptive findings show a consistent separation across all domains
based on political orientation, with stronger effects observed in
certain areas, such as the denial of climate change reality and concern.
However, our causal estimates indicate that these associations do not
apply uniformly across all outcomes.

We examined two different interventions: a gain in Political
Conservativism (an increase of two points up to a maximum of 7) and a
loss in Political Conservativism (a decrease to a minimum of 1). We
contrasted these means of these shift-interventions with observed
political conservatism levels in the population. These interventions
allow us to explore both gain and loss scenarios, which are critical to
distinguish since the effects of increasing versus decreasing political
conservatism may not mirror each other.

Our findings suggest that political conservatism is causally linked to
denial of climate change reality and concern. In particular, the
evidence for causality is strong in the gain condition for denial of
climate change reality, concern, and human causation of climate change.
However, for the denial of personal environmental efficacy and
satisfaction with the New Zealand environment, the evidence for
causality is weak or unreliable.

These findings underscore the importance of distinguishing between
causal effect estimates and correlations. Although descriptive
statistics indicate associations between political conservatism and
environmental attitudes, these correlations are not the same as causal
relationships. Even when measured over time, correlations do not
necessarily imply causality.

Moreover, our study demonstrates the importance of distinguishing
between gain and loss interventions in political orientation and their
impact on environmental attitudes. The evidence supports a one-year
causal effect from the loss of political conservativism on beliefs the
climate change is human-caused, yet with no reliable evidence for change
in other dimensions of environmental belief.

Looking ahead, we recommend the wider development and application of
causal inferential methods employing repeated measurements over more
than three years to investigate variation, interaction, and causal
mediation.

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study. Members of the NZAVS management team and research
group hold full copies of the NZAVS data. A de-identified dataset
containing only the variables analysed in this manuscript is available
upon request from the corresponding author or any member of the NZAVS
advisory board for replication or checking of any published study using
NZAVS data. The code for the analysis can be found at:
\url{https://github.com/go-bayes/models/tree/main/scripts/24-POL-CONSERVE-environ}.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Planck Institute for the Science of Human History. The
funders had no role in preparing the manuscript or deciding to publish
it.

\subsubsection{Author Statement}\label{author-statement}

JB and IK conceived the study. JB developed the approach. CS led NZAVS
data collection. All authors contributed to the manuscript.

\newpage{}

\subsection{Appendix A: Measures}\label{appendix-measures-a}

Table~\ref{tbl-table-exposure} presents descriptive statistics for
baseline covariates, measure in NZAVS time 10, years 2018-2019.

\subsubsection{Covariate measures at
baseline}\label{covariate-measures-at-baseline}

\begin{longtable}[]{@{}ll@{}}

\caption{\label{tbl-table-baseline}Baseline covariates}

\tabularnewline

\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 44,658} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 49 (14) \\
Min, Max & 18, 99 \\
Q1, Q3 & 39, 60 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.35 (0.99) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.75, 6.00 \\
Unknown & 379 \\
\textbf{Alcohol Frequency} & NA \\
0 & 5,474 (13\%) \\
1 & 10,131 (23\%) \\
2 & 8,325 (19\%) \\
3 & 10,297 (24\%) \\
4 & 8,799 (20\%) \\
5 & 141 (0.3\%) \\
Unknown & 1,491 \\
\textbf{Alcohol Intensity} & NA \\
Mean (SD) & 2.17 (2.17) \\
Min, Max & 0.00, 30.00 \\
Q1, Q3 & 1.00, 3.00 \\
Unknown & 2,579 \\
\textbf{Belong} & NA \\
Mean (SD) & 5.14 (1.07) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.33, 6.00 \\
Unknown & 376 \\
\textbf{Born Nz Binary} & 34,779 (78\%) \\
Unknown & 162 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.11 (1.06) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.50, 6.00 \\
Unknown & 372 \\
\textbf{Education Level Coarsen} & NA \\
no\_qualification & 1,056 (2.4\%) \\
cert\_1\_to\_4 & 15,547 (35\%) \\
cert\_5\_to\_6 & 5,613 (13\%) \\
university & 11,940 (27\%) \\
post\_grad & 4,919 (11\%) \\
masters & 3,791 (8.6\%) \\
doctorate & 1,074 (2.4\%) \\
Unknown & 718 \\
\textbf{Employed Binary} & 35,601 (80\%) \\
Unknown & 6 \\
\textbf{Eth Cat} & NA \\
euro & 35,660 (81\%) \\
maori & 5,013 (11\%) \\
pacific & 1,042 (2.4\%) \\
asian & 2,360 (5.4\%) \\
Unknown & 583 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.91 (1.20) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 3.00, 4.75 \\
Unknown & 372 \\
\textbf{Hlth Disability Binary} & 9,792 (22\%) \\
Unknown & 858 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.41 (1.18) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.75, 6.25 \\
Unknown & 374 \\
\textbf{Hours Children} & NA \\
Mean (SD) & 14 (32) \\
Min, Max & 0, 168 \\
Q1, Q3 & 0, 10 \\
Unknown & 1,315 \\
\textbf{Hours Commute} & NA \\
Mean (SD) & 5.3 (6.4) \\
Min, Max & 0.0, 80.0 \\
Q1, Q3 & 2.0, 7.0 \\
Unknown & 1,315 \\
\textbf{Hours Exercise} & NA \\
Mean (SD) & 5.8 (7.7) \\
Min, Max & 0.0, 80.0 \\
Q1, Q3 & 2.0, 7.0 \\
Unknown & 1,315 \\
\textbf{Hours Housework} & NA \\
Mean (SD) & 10 (10) \\
Min, Max & 0, 168 \\
Q1, Q3 & 5, 14 \\
Unknown & 1,315 \\
\textbf{Household Inc} & NA \\
Mean (SD) & 115,666 (92,021) \\
Min, Max & 1, 3,005,000 \\
Q1, Q3 & 60,000, 150,000 \\
Unknown & 2,660 \\
\textbf{Kessler Latent Anxiety} & NA \\
Mean (SD) & 1.21 (0.77) \\
Min, Max & 0.00, 4.00 \\
Q1, Q3 & 0.67, 1.67 \\
Unknown & 408 \\
\textbf{Kessler Latent Depression} & NA \\
Mean (SD) & 0.58 (0.75) \\
Min, Max & 0.00, 4.00 \\
Q1, Q3 & 0.00, 1.00 \\
Unknown & 411 \\
\textbf{Log Hours Children} & NA \\
Mean (SD) & 1.17 (1.61) \\
Min, Max & 0.00, 5.13 \\
Q1, Q3 & 0.00, 2.40 \\
Unknown & 1,315 \\
\textbf{Log Hours Commute} & NA \\
Mean (SD) & 1.50 (0.83) \\
Min, Max & 0.00, 4.39 \\
Q1, Q3 & 1.10, 2.08 \\
Unknown & 1,315 \\
\textbf{Log Hours Exercise} & NA \\
Mean (SD) & 1.55 (0.84) \\
Min, Max & 0.00, 4.39 \\
Q1, Q3 & 1.10, 2.08 \\
Unknown & 1,315 \\
\textbf{Log Hours Housework} & NA \\
Mean (SD) & 2.14 (0.78) \\
Min, Max & 0.00, 5.13 \\
Q1, Q3 & 1.79, 2.71 \\
Unknown & 1,315 \\
\textbf{Log Household Inc} & NA \\
Mean (SD) & 11.40 (0.76) \\
Min, Max & 0.69, 14.92 \\
Q1, Q3 & 11.00, 11.92 \\
Unknown & 2,660 \\
\textbf{Male Binary} & 16,537 (37\%) \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.49 (1.15) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 2.75, 4.25 \\
Unknown & 379 \\
\textbf{Not Heterosexual Binary} & 2,955 (6.8\%) \\
Unknown & 1,049 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.75 (2.72) \\
Min, Max & 1.00, 10.00 \\
Q1, Q3 & 2.00, 7.00 \\
Unknown & 302 \\
\textbf{Nzsei 13 l} & NA \\
Mean (SD) & 54 (16) \\
Min, Max & 10, 90 \\
Q1, Q3 & 42, 69 \\
Unknown & 286 \\
\textbf{Openness} & NA \\
Mean (SD) & 4.97 (1.12) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.25, 5.75 \\
Unknown & 373 \\
\textbf{Parent Binary} & 31,575 (71\%) \\
\textbf{Partner Binary} & 33,520 (75\%) \\
Unknown & 81 \\
\textbf{Political Conservative} & NA \\
1 & 2,515 (5.6\%) \\
2 & 8,676 (19\%) \\
3 & 8,820 (20\%) \\
4 & 13,913 (31\%) \\
5 & 6,694 (15\%) \\
6 & 3,299 (7.4\%) \\
7 & 741 (1.7\%) \\
\textbf{Power No Control Composite} & NA \\
Mean (SD) & 2.96 (1.40) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 2.00, 4.00 \\
Unknown & 152 \\
\textbf{Religion Identification Level} & NA \\
1 & 29,645 (67\%) \\
2 & 1,716 (3.9\%) \\
3 & 1,171 (2.6\%) \\
4 & 2,106 (4.8\%) \\
5 & 2,600 (5.9\%) \\
6 & 2,246 (5.1\%) \\
7 & 4,806 (11\%) \\
Unknown & 368 \\
\textbf{Rural Gch 2018 l} & NA \\
1 & 27,661 (62\%) \\
2 & 8,292 (19\%) \\
3 & 5,414 (12\%) \\
4 & 2,468 (5.6\%) \\
5 & 523 (1.2\%) \\
Unknown & 300 \\
\textbf{Rwa} & NA \\
Mean (SD) & 3.27 (1.15) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 2.50, 4.00 \\
Unknown & 2 \\
\textbf{Sample Frame Opt in Binary} & 1,344 (3.0\%) \\
\textbf{Sdo} & NA \\
Mean (SD) & 2.31 (0.96) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 1.50, 3.00 \\
\textbf{Short Form Health} & NA \\
Mean (SD) & 5.05 (1.17) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.33, 6.00 \\
Unknown & 9 \\
\textbf{Smoker Binary} & 3,138 (7.2\%) \\
Unknown & 1,119 \\
\textbf{Support} & NA \\
Mean (SD) & 5.96 (1.12) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 5.33, 7.00 \\
Unknown & 36 \\

\end{longtable}

\newpage{}

\subsubsection{Exposure measures at baseline and exposure
waves}\label{exposure-measures-at-baseline-and-exposure-waves}

\begin{table}

\caption{\label{tbl-table-exposure}Exposure at baseline and exposure
waves}

\centering{

\centering
\begin{tabular}[t]{l|l|l|l|l}
\hline
**Exposure Variable: Political Conservative by Wave** & **2018**  
N = 44,658 & **2019**  
N = 44,658 & **2020**  
N = 44,658 & **2021**  
N = 44,658\\
\hline
\_\_Political Conservative\_\_ & NA & NA & NA & NA\\
\hline
1 & 2,515 (5.6\%) & 1,747 (5.5\%) & 1,790 (6.1\%) & 1,320 (5.3\%)\\
\hline
2 & 8,676 (19\%) & 6,430 (20\%) & 6,109 (21\%) & 5,086 (20\%)\\
\hline
3 & 8,820 (20\%) & 6,495 (20\%) & 6,282 (22\%) & 5,330 (21\%)\\
\hline
4 & 13,913 (31\%) & 9,370 (30\%) & 8,991 (31\%) & 7,694 (31\%)\\
\hline
5 & 6,694 (15\%) & 4,772 (15\%) & 3,884 (13\%) & 3,609 (14\%)\\
\hline
6 & 3,299 (7.4\%) & 2,426 (7.6\%) & 1,699 (5.8\%) & 1,535 (6.2\%)\\
\hline
7 & 741 (1.7\%) & 502 (1.6\%) & 376 (1.3\%) & 322 (1.3\%)\\
\hline
Unknown & 0 & 12,916 & 15,527 & 19,762\\
\hline
\end{tabular}

}

\end{table}%

Table~\ref{tbl-table-exposure} presents descriptive statistics for the
exposure: Political Conservativism measured in NZAVS time 10, years
2018-2019 and NZAVS time 11-13, years 2019-2022.

\newpage{}

\subsubsection{Outcome measure at baseline and exposure
waves}\label{outcome-measure-at-baseline-and-exposure-waves}

Table~\ref{tbl-table-outcomes} presents descriptive statistics for the
the outcome variables measured in NZAVS time 10, years 2018-2019 and
NZAVS time 14, years 2022-2023.

\begin{table}

\caption{\label{tbl-table-outcomes}Outcomes at baseline and
end-of-study}

\centering{

\begin{tabular}[t]{l|l|l}
\hline
**Outcome Variables by Wave** & **2018**  
N = 44,658 & **2022**  
N = 44,658\\
\hline
\_\_Env Climate Chg Cause\_\_ & NA & NA\\
\hline
1 & 1,373 (3.1\%) & 811 (3.8\%)\\
\hline
2 & 1,419 (3.2\%) & 840 (3.9\%)\\
\hline
3 & 1,779 (4.0\%) & 941 (4.4\%)\\
\hline
4 & 4,352 (9.9\%) & 2,051 (9.6\%)\\
\hline
5 & 6,441 (15\%) & 3,112 (15\%)\\
\hline
6 & 10,342 (24\%) & 5,198 (24\%)\\
\hline
7 & 18,228 (41\%) & 8,317 (39\%)\\
\hline
Unknown & 724 & 23,388\\
\hline
\_\_Env Climate Chg Concern\_\_ & NA & NA\\
\hline
1 & 1,755 (4.0\%) & 1,091 (5.1\%)\\
\hline
2 & 1,941 (4.4\%) & 1,113 (5.2\%)\\
\hline
3 & 2,514 (5.8\%) & 1,297 (6.1\%)\\
\hline
4 & 5,578 (13\%) & 2,646 (12\%)\\
\hline
5 & 8,452 (19\%) & 4,207 (20\%)\\
\hline
6 & 9,593 (22\%) & 4,708 (22\%)\\
\hline
7 & 13,849 (32\%) & 6,166 (29\%)\\
\hline
Unknown & 976 & 23,430\\
\hline
\_\_Env Climate Chg Real\_\_ & NA & NA\\
\hline
1 & 828 (1.9\%) & 513 (2.4\%)\\
\hline
2 & 771 (1.8\%) & 436 (2.0\%)\\
\hline
3 & 903 (2.1\%) & 523 (2.4\%)\\
\hline
4 & 2,797 (6.4\%) & 1,316 (6.2\%)\\
\hline
5 & 3,880 (8.8\%) & 1,823 (8.5\%)\\
\hline
6 & 8,416 (19\%) & 3,855 (18\%)\\
\hline
7 & 26,433 (60\%) & 12,925 (60\%)\\
\hline
Unknown & 630 & 23,267\\
\hline
\_\_Env Sat Nz Environment\_\_ & 6.00 (3.00, 7.00) & 5.00 (3.00, 7.00)\\
\hline
Unknown & 189 & 21,914\\
\hline
\end{tabular}

}

\end{table}%

\newpage{}

\subsection{Appendix B: Measures}\label{appendix-measures-b}

\subsubsection{Measures}\label{measures-1}

\paragraph{Age}\label{age}

\emph{What is your date of birth?}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth'').. Developed for the NZAVS.

\paragraph{Agreeableness}\label{agreeableness}

\emph{I sympathize with others' feelings.} \emph{I am not interested in
other people's problems.} \emph{I feel others' emotions.} \emph{I am not
really interested in others (reversed).}

Mini-IPIP6 Agreeableness dimension: (i) I sympathize with others'
feelings. (ii) I am not interested in other people's problems. (r) (iii)
I feel others' emotions. (iv) I am not really interested in others. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Alcohol Frequency}\label{alcohol-frequency}

\emph{``How often do you have a drink containing alcohol?''}

Participants could chose between the following responses: `(1 = Never -
I don't drink, 2 = Monthly or less, 3 = Up to 4 times a month, 4 = Up to
3 times a week, 5 = 4 or more times a week, 6 = Don't know)'
(\citeproc{ref-Ministry_of_Health_2013}{Health 2013}).

\paragraph{Alcohol Intensity}\label{alcohol-intensity}

\emph{``How many drinks containing alcohol do you have on a typical day
when drinking alcohol? (number of drinks on a typical day when
drinking)''}

Participants responded using an open-ended box
(\citeproc{ref-Ministry_of_Health_2013}{Health 2013}).

\paragraph{Belong}\label{belong}

\emph{Know that people in my life accept and value me.} \emph{Feel like
an outsider.} \emph{Know that people around me share my attitudes and
beliefs.}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (Hagerty \& Patusky, 1995): (1) ``Know that
people in my life accept and value me''; (2) ``Feel like an outsider'';
(3) ``Know that people around me share my attitudes and beliefs''.
Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very
Accurate). The second item was reversely coded
(\citeproc{ref-hagerty1995}{Hagerty and Patusky 1995}).

\paragraph{Born Nz (Binary)}\label{born-nz-binary}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).. Developed for the NZAVS.

\paragraph{Conscientiousness}\label{conscientiousness}

\emph{I get chores done right away.} \emph{I like order.} \emph{I make a
mess of things.} \emph{I often forget to put things back in their proper
place.}

Mini-IPIP6 Conscientiousness dimension: (i) I get chores done right
away. (ii) I like order. (iii) I make a mess of things. (r) (iv) I often
forget to put things back in their proper place. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Education Level Coarsen}\label{education-level-coarsen}

\emph{What is your highest level of qualification?}

We asked participants, ``What is your highest level of qualification?''.
We coded participans highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school qualifications coded as Level 3, and all other ancillary
categories coded as missing). Developed for the NZAVS.

\paragraph{Employed (Binary)}\label{employed-binary}

\emph{Are you currently employed (This includes self-employed of casual
work)?}

Binary response: (0 = No, 1 = Yes). Stats NZ Census Question.

\paragraph{Eth Cat (Categorical)}\label{eth-cat-categorical}

\emph{Which ethnic group(s) do you belong to?}

Coded string: (1 = New Zealand European; 2 = Māori; 3 = Pacific; 4 =
Asian). NZ Census coding.

\paragraph{Extraversion}\label{extraversion}

\emph{I am the life of the party.} \emph{I don't talk a lot (reversed).}
\emph{I keep in the background (reversed).} \emph{I talk to a lot of
different people at parties.}

Mini-IPIP6 Extraversion dimension: (i) I am the life of the party. (ii)
I don't talk a lot. (r) (iii) I keep in the background. (r) (iv) I talk
to a lot of different people at parties
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Hlth Disability (Binary)}\label{hlth-disability-binary}

We assessed disability with a one-item indicator adapted from Verbrugge
(1997). It asks, ``Do you have a health condition or disability that
limits you and that has lasted for 6+ months?'' (1 = Yes, 0 = No)
(\citeproc{ref-verbrugge1997}{Verbrugge 1997}).

\paragraph{Honesty Humility}\label{honesty-humility}

\emph{I feel entitled to more of everything (reversed).} \emph{I deserve
more things in life (reversed).} \emph{I deserve more things in life
(reversed).} \emph{I would get a lot of pleasure from owning expensive
luxury goods (reversed).}

Mini-IPIP6 Honesty-Humility dimension: (i) I feel entitled to more of
everything. (r) (ii) I deserve more things in life. (r) (iii) I would
like to be seen driving around in a very expensive car. (r) (iv) I would
get a lot of pleasure from owning expensive luxury goods. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Kessler Latent Anxiety}\label{kessler-latent-anxiety}

\emph{During the past 30 days, how often did\ldots you feel restless or
fidgety?} \emph{During the past 30 days, how often did\ldots you feel
that everything was an effort?} \emph{During the past 30 days, how often
did\ldots you feel nervous?}

Ordinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2=
Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time)
(\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002}).

\paragraph{Kessler Latent Depression}\label{kessler-latent-depression}

\emph{During the past 30 days, how often did\ldots you feel hopeless?}
\emph{During the past 30 days, how often did\ldots you feel so depressed
that nothing could cheer you up?} \emph{During the past 30 days, how
often did\ldots you feel you feel restless or fidgety?}

Ordinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2=
Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time)
(\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002}).

\paragraph{Log Hours Children}\label{log-hours-children}

\emph{Hours spent\ldots looking after children.}

We took the natural log of the response + 1
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Log Hours Commute}\label{log-hours-commute}

\emph{Hours spent\ldots travelling/commuting.}

We took the natural log of the response + 1.. Developed for the NZAVS.

\paragraph{Log Hours Exercise}\label{log-hours-exercise}

\emph{Hours spent\ldots exercising/physical activity.}

We took the natural log of the response + 1
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Log Hours Housework}\label{log-hours-housework}

\emph{Hours spent\ldots housework/cooking.}

We took the natural log of the response + 1
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Log Household Inc}\label{log-household-inc}

\emph{Please estimate your total household income (before tax) for the
year XXXX.}

We took the natural log of the response + 1.. Developed for the NZAVS.

\paragraph{Male (Binary)}\label{male-binary}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3 (Fraser et al.,
2020). (or 0.5 = neither female nor male). Here, we coded all those who
responded as Male as 1, and those who did not as 0
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}).

\paragraph{Neuroticism}\label{neuroticism}

\emph{I have frequent mood swings.} \emph{I am relaxed most of the time
(reversed).} \emph{I get upset easily.} \emph{I seldom feel blue
(reversed).}

Mini-IPIP6 Neuroticism dimension: (i) I have frequent mood swings. (ii)
I am relaxed most of the time. (r) (iii) I get upset easily. (iv) I
seldom feel blue. (r) (\citeproc{ref-sibley2011}{Sibley \emph{et al.}
2011}).

\paragraph{Not Heterosexual (Binary)}\label{not-heterosexual-binary}

\emph{How would you describe your sexual orientation? (e.g.,
heterosexual, homosexual, straight, gay, lesbian, bisexual, etc.)}

Open-ended question, coded as binary (not heterosexual = 1)
(\citeproc{ref-greaves2017diversity}{Greaves \emph{et al.} 2017}).

\paragraph{NZ Dep2018}\label{nz-dep2018}

\emph{New Zealand Deprivation - Decile Index - Using 2018 Census Data}

Numerical: (1-10) (\citeproc{ref-atkinson2019}{Atkinson \emph{et al.}
2019}).

\paragraph{NZsei 13}\label{nzsei-13}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (Fahy et al., 2017). This index uses
the income, age, and education of a reference group, in this case, the
2013 New Zealand census, to calculate a score for each occupational
group. Scores range from 10 (Lowest) to 90 (Highest). This list of index
scores for occupational groups was used to assign each participant a
NZSEI-13 score based on their occupation (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017}).

\paragraph{Openness}\label{openness}

\emph{I have a vivid imagination.} \emph{I have difficulty understanding
abstract ideas (reversed).} \emph{I do not have a good imagination
(reversed).} \emph{I am not interested in abstract ideas (reversed).}

Mini-IPIP6 Openness to Experience dimension: (i) I have a vivid
imagination. (ii) I have difficulty understanding abstract ideas. (r)
(iii) I do not have a good imagination. (r) (iv) I am not interested in
abstract ideas. (r) (\citeproc{ref-sibley2011}{Sibley \emph{et al.}
2011}).

\paragraph{Parent (Binary)}\label{parent-binary}

We asked participants, ``If you are a parent, what is the birth date of
your eldest child?'' or ``If you are a parent, in which year was your
eldest child born?'' (waves: 10-current). Parents were coded as 1, while
the others were coded as 0.. Developed for the NZAVS.

\paragraph{Partner (Binary)}\label{partner-binary}

\emph{What is your relationship status? (e.g., single, married,
de-facto, civil union, widowed, living together, etc.)}

Coded as binary (has partner = 1).. Developed for the NZAVS.

\paragraph{Political Conservative}\label{political-conservative-1}

\emph{Please rate how politically liberal versus conservative you see
yourself as being.}

Ordinal response: (1 = Extremely Liberal, 7 = Extremely Conservative)
(\citeproc{ref-jost_end_2006-1}{Jost 2006}).

\paragraph{Power No Control Composite}\label{power-no-control-composite}

\emph{I do not have enough power or control over important parts of my
life.} \emph{Other people have too much power or control over important
parts of my life.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-overall2016power}{Overall \emph{et al.} 2016}).

\paragraph{Religion Identification
Level}\label{religion-identification-level}

\emph{How important is your religion to how you see yourself?}

Ordinal response: (1 = Not Important, 7 = Very Important). Developed for
the NZAVS.

\paragraph{Rural Gch 2018}\label{rural-gch-2018}

\emph{High Urban Accessibility = 1, Medium Urban Accessibility = 2, Low
Urban Accessibility = 3, Remote = 4, Very Remote = 5.}

``Participants residence locations were coded according to a five-level
ordinal categorisation ranging from Urban to Rural.''
(\citeproc{ref-whitehead2023unmasking}{Whitehead \emph{et al.} 2023}).

\paragraph{Sample Frame Opt in
(Binary)}\label{sample-frame-opt-in-binary}

\emph{Participant was not randomly sampled from the New Zealand
Electoral Roll.}

Code string (Binary): (0 = No, 1 = Yes). Developed for the NZAVS.

\paragraph{Short Form Health}\label{short-form-health}

\emph{In general, would you say your health is\ldots{}}

Ordinal response: (1 = Poor, 7 = Excellent)
(\citeproc{ref-instrument1992mos}{Instrument Ware Jr and Sherbourne
1992}).

\paragraph{Smoker (Binary)}\label{smoker-binary}

\emph{Do you currently smoke tobacco cigarettes?}

Binary smoking indicator (0 = No, 1 = Yes).. Developed for NZAVS.

\paragraph{Support}\label{support}

\emph{There are people I can depend on to help me if I really need it.}
\emph{There is no one I can turn to for guidance in times of stress
(reversed).} \emph{I know there are people I can turn to when I need
help.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-cutrona1987}{Cutrona and Russell 1987}).

\paragraph{Free Speech}\label{free-speech}

\emph{Although I may disagree with the opinions that other people hold,
they should be allowed to express those views publicly.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-dore2022boundaries}{Doré \emph{et al.} 2022}).

\paragraph{Pol Politician Trust}\label{pol-politician-trust}

\emph{Politicians in New Zealand can generally be trusted.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-sibley2020a}{Sibley \emph{et al.} 2020}).

\paragraph{Police Trust}\label{police-trust}

\emph{People's basic rights are well protected by the New Zealand
Police.} \emph{There are many things about the New Zealand Police and
its policies that need to be changed (reversed).} \emph{The New Zealand
Police care about the well-being of everyone they deal with.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-tyler2005}{Tyler 2005}).

\paragraph{Trust Science Our Society Places Too Much Emphasis
Reversed}\label{trust-science-our-society-places-too-much-emphasis-reversed}

\emph{Our society places too much emphasis on science.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-hartman2017}{Hartman \emph{et al.} 2017}).

\paragraph{Deny Climate Change is Caused by
Humans}\label{deny-climate-change-is-caused-by-humans}

\emph{1. Climate change is caused by humans (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-sibley2013model}{Sibley and Kurz 2013}).

\paragraph{Deny Climate Change
Concern}\label{deny-climate-change-concern-1}

\emph{I am deeply concerned about climate change (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree). Developed
for the NZAVS.

\paragraph{Deny Climate Change is
Real}\label{deny-climate-change-is-real}

\emph{Climate change is real (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-sibley2013model}{Sibley and Kurz 2013}).

\paragraph{Deny Environmental
Efficacy}\label{deny-environmental-efficacy-1}

\emph{By taking personal action I believe I can make a positive
difference to environmental problems (reversed)} \emph{I feel I can make
a difference to the state of the environment (reversed).}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-sharma2008we}{Sharma 2008}).

\paragraph{Not Satisfied with the New Zealand
Environment}\label{not-satisfied-with-the-new-zealand-environment}

\emph{Please rate your level of satisfaction with the following aspects
of your life and New Zealand\ldots The quality of New Zealand's natural
environment (reversed).}

Ordinal response: (0 = Completely Dissatisfied, 10 = Completely
Datisfied) (\citeproc{ref-tiliouine_measuring_2006}{Tiliouine \emph{et
al.} 2006}).

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, JA (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-bulbulia2024swigstime}
Bulbulia, JA (2024c) Methods in causal inference part 2: Interaction,
mediation, and time-varying treatments. \emph{Evolutionary Human
Sciences}, \textbf{6}. Retrieved from
\url{https://osf.io/preprints/psyarxiv/vr268}

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diaz2023lmtp}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2023) Nonparametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association},
\textbf{118}(542), 846--857.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-dore2022boundaries}
Doré, N, Satherley, N, Yogeeswaran, K, Vonasch, AJ, Verkuyten, M, and
Sibley, CG (2022) Boundaries of free speech: Profiling support for
acceptance of free speech and restrictions on offensive speech.
\emph{International Journal of Public Opinion Research}, \textbf{34}(4),
edac039.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017) \emph{{N}ew {Z}ealand
socio-economic index 2013}, Wellington, New Zealand: Statistics New
Zealand-Tatauranga Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a {N}ew {Z}ealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-greaves2017diversity}
Greaves, LM, Barlow, FK, Lee, CH, et al.others (2017) The diversity and
prevalence of sexual orientation self-labels in a {N}ew {Z}ealand
national sample. \emph{Archives of Sexual Behavior}, \textbf{46},
1325--1336.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-hartman2017}
Hartman, RO, Dieckmann, NF, Sprenger, AM, Stastny, BJ, and DeMarree, KG
(2017) Modeling attitudes toward science: Development and validation of
the credibility of science scale. \emph{Basic and Applied Social
Psychology}, \textbf{39}, 358--371.
doi:\href{https://doi.org/10.1080/01973533.2017.1372284}{10.1080/01973533.2017.1372284}.

\bibitem[\citeproctext]{ref-Ministry_of_Health_2013}
Health, Ministry of (2013) \emph{The {N}ew {Z}ealand {H}ealth {S}urvey:
Content guide 2012-2013}, Princeton University Press.

\bibitem[\citeproctext]{ref-hernan2024WHATIF}
Hernan, MA, and Robins, JM (2024) \emph{Causal inference: What if?},
Taylor \& Francis. Retrieved from
\url{https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/}

\bibitem[\citeproctext]{ref-hernan2024stating}
Hernán, MA, and Greenland, S (2024) Why stating hypotheses in grant
applications is unnecessary. \emph{JAMA}, \textbf{331}(4), 285--286.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-instrument1992mos}
Instrument Ware Jr, J, and Sherbourne, C (1992) The MOS 36-item
short-form health survey (SF-36): I. Conceptual framework and item
selection. \emph{Medical Care}, \textbf{30}(6), 473--483.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-kessler2002}
Kessler, R~C, Andrews, G, Colpe, L~J, \ldots{} Zaslavsky, A~M (2002)
Short screening scales to monitor population prevalences and trends in
non-specific psychological distress. \emph{Psychological Medicine},
\textbf{32}(6), 959--976.
doi:\href{https://doi.org/10.1017/S0033291702006074}{10.1017/S0033291702006074}.

\bibitem[\citeproctext]{ref-van2012targeted}
Laan, MJ van der, and Gruber, S (2012) Targeted minimum loss based
estimation of causal effects of multiple time point interventions.
\emph{The International Journal of Biostatistics}, \textbf{8}(1).

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-overall2016power}
Overall, NC, Hammond, MD, McNulty, JK, and Finkel, EJ (2016) When power
shapes interpersonal behavior: Low relationship power predicts men's
aggressive responses to low situational power. \emph{Journal of
Personality and Social Psychology}, \textbf{111}(2), 195.

\bibitem[\citeproctext]{ref-pearl2009}
Pearl, J (2009a) \emph{\href{https://doi.org/10.1214/09-SS057}{Causal
inference in statistics: An overview}}.

\bibitem[\citeproctext]{ref-pearl2009a}
Pearl, J (2009b) \emph{Causality}, Cambridge University Press.

\bibitem[\citeproctext]{ref-SuperLearner2023}
Polley, E, LeDell, E, Kennedy, C, and van der Laan, M (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://github.com/ecpolley/SuperLearner}

\bibitem[\citeproctext]{ref-richardson2013swigsprimer}
Richardson, TS, and Robins, JM (2013) Single world intervention graphs:
A primer. In \emph{Second UAI workshop on causal structure learning,
{B}ellevue, {W}ashington}, Citeseer. Retrieved from
\url{https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=07bbcb458109d2663acc0d098e8913892389a2a7}

\bibitem[\citeproctext]{ref-richardson2023potential}
Richardson, TS, and Robins, JM (2023) Potential outcome and decision
theoretic foundations for statistical causality. \emph{Journal of Causal
Inference}, \textbf{11}(1), 20220012.

\bibitem[\citeproctext]{ref-robins1986}
Robins, J (1986) A new approach to causal inference in mortality studies
with a sustained exposure period---application to control of the healthy
worker survivor effect. \emph{Mathematical Modelling}, \textbf{7}(9-12),
1393--1512.

\bibitem[\citeproctext]{ref-robins2010alternative}
Robins, JM, and Richardson, TS (2010) Alternative graphical causal
models and the identification of direct effects. \emph{Causality and
Psychopathology: Finding the Determinants of Disorders and Their Cures},
\textbf{84}, 103--158.

\bibitem[\citeproctext]{ref-rubin2005}
Rubin, DB (2005) Causal inference using potential outcomes: Design,
modeling, decisions. \emph{Journal of the American Statistical
Association}, \textbf{100}(469), 322--331. Retrieved from
\url{https://www.jstor.org/stable/27590541}

\bibitem[\citeproctext]{ref-sharma2008we}
Sharma, SD (2008) \emph{Where do we stand?: One auckland secondary
school's journey towards environmental sustainability: A systems
approach} (PhD thesis), University of Auckland.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the {N}ew {Z}ealand {A}ttitudes and {V}alues
{S}tudy}}.

\bibitem[\citeproctext]{ref-sibley2020a}
Sibley, CG, Greaves, L, Satherley, N, \ldots{} al, et (2020) What
happened to people in {N}ew {Z}ealand during covid-19 home lockdown?
Institutional trust, attitudes to government, mental health and
subjective wellbeing. Retrieved from
\href{https://osf.io/e765a}{osf.io/e765a}

\bibitem[\citeproctext]{ref-sibley2013model}
Sibley, CG, and Kurz, T (2013) A model of climate belief profiles: How
much does it matter if people question human causation? \emph{Analyses
of Social Issues and Public Policy}, \textbf{13}(1), 245--261.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in {N}ew {Z}ealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-neyman1923}
Splawa-Neyman, J (1990 (orig. 1923)) On the application of probability
theory to agricultural experiments. Essay on principles. Section 9.
(1923). \emph{Statistical Science}, \textbf{5}(4), 465--472.

\bibitem[\citeproctext]{ref-tiliouine_measuring_2006}
Tiliouine, H, Cummins, RA, and Davern, M (2006) Measuring wellbeing in
developing countries: The case of algeria. \emph{Social Indicators
Research}, \textbf{75}, 1--30.

\bibitem[\citeproctext]{ref-tyler2005}
Tyler, TR (2005) Policing in black and white: Ethnic group differences
in trust and confidence in the police. \emph{Police Quarterly},
\textbf{8}(3), 322--342.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-van2014targeted}
Van der Laan, MJ (2014) Targeted estimation of nuisance parameters to
obtain valid statistical inference. \emph{The International Journal of
Biostatistics}, \textbf{10}(1), 29--57.

\bibitem[\citeproctext]{ref-vanderlaan2018}
Van Der Laan, MJ, and Rose, S (2018) \emph{Targeted Learning in Data
Science: Causal Inference for Complex Longitudinal Studies}, Cham:
Springer International Publishing. Retrieved from
\url{http://link.springer.com/10.1007/978-3-319-65304-4}

\bibitem[\citeproctext]{ref-vanderweele2019}
VanderWeele, TJ (2019) Principles of confounder selection.
\emph{European Journal of Epidemiology}, \textbf{34}(3), 211--219.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the {E}-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437--466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-whitehead2023unmasking}
Whitehead, J, Davie, G, Graaf, B de, \ldots{} Nixon, G (2023) Unmasking
hidden disparities: A comparative observational study examining the
impact of different rurality classifications for health research in
aotearoa new zealand. \emph{BMJ Open}, \textbf{13}(4), e067927.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{{l}mtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\bibitem[\citeproctext]{ref-zhang2023shouldMultipleImputation}
Zhang, J, Dashti, SG, Carlin, JB, Lee, KJ, and Moreno-Betancur, M (2023)
Should multiple imputation be stratified by exposure group when
estimating causal effects via outcome regression in observational
studies? \emph{BMC Medical Research Methodology}, \textbf{23}(1), 42.

\end{CSLReferences}




\end{document}
