% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal Effect of Religious Service Attendance On Fertility in an American Sample},
  pdfauthor={Radim Chvaja; John H Shaver; Joseph A. Bulbulia},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal Effect of Religious Service Attendance On Fertility in an
American Sample}

\usepackage{academicons}
\usepackage{xcolor}

  \author{Radim Chvaja}
            \affil{%
             \small{     European Research University, Masaryk
University, Faculty of Arts, University of Otago
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~000-0002-1560-1197 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{John H Shaver}
            \affil{%
             \small{     Baylor University
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-9522-4765 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Joseph A. Bulbulia}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5861-2056 }
              }
      


\date{2024-07-10}
\begin{document}
\maketitle
\begin{abstract}
Abstract here \ldots{} \textbf{KEYWORDS}: \emph{Causal Inference};
\emph{Longitudinal}; \emph{Religion}; \emph{Fertility}.
\end{abstract}

\subsection{Introduction}\label{introduction}

Humans are obligate cooperators, unable to live apart from society
(\citeproc{ref-sterelny2007social}{Sterelny, 2007}). Human societies are
characterised by intricate divisions of labour that extend beyond family
ties. These involve both direct and indirect reciprocal relationships
across multiple domains -- communal protection, building, food gathering
and hunting, commerce, tool and bush craft
(\citeproc{ref-sterelny2011hominins}{Sterelny, 2011}). It has been noted
that children rely on this cooperative framework for nearly two decades
post-birth (\citeproc{ref-gurven2006energetic}{Gurven \& Walker, 2006}),
and parents require the broader social group's support to provide for
their offspring (\citeproc{ref-shaver2019alloparenting}{Shaver et al.,
2019}). Evolutionary models of religion posit that religion evolved deep
in the human lineage to foster cooperation
(\citeproc{ref-sosis2003cooperation}{Sosis \& Bressler, 2003}) through
dedicated cognitive and cultural architectures desgined to promote
fertility (\citeproc{ref-rowthorn2011religion}{Rowthorn, 2011}).
Although cooperation is typically modelled on examples of trade and
warfar, the cooperative benefits of these systems include mate selection
(\citeproc{ref-blume2009reproductive}{Blume, 2009}), mate evaluation
(\citeproc{ref-irons2001religion}{Irons, 2001}), and collective
child-rearing (\citeproc{ref-shaver2020church}{Shaver et al., 2020}).
Indeed, the function of mate-selection and collective child rearing
might not be easily disentangled; offspring unite parents to a common
genetic fate. As such, `reproduction poses biology's most fundamental
cooperation problem' (\citeproc{ref-Bulbulia_2015}{Bulbulia et al.,
2015})

Notably, sexual signalling theory posits that differences in
reproductive potentials between males and females lead to different
valuations of traits in prospective mates. For example, it has been
proposed that males may be are more concerned about female infidelity
given that males face risks of cuckoldry, whereas and may be concerned
about resource diversion resulting from male infidelity or diminished
social prestige. This gradient evolved within humans to extend
cooperative networks beyond immediate reciprocity
(\citeproc{ref-alexander2017biology}{Alexander, 2017}). It has been
proposed that males engage in high-risk cooperation, such as hunting and
defence to obtain and signal prestige to mates
(\citeproc{ref-gurven2009men}{Gurven \& Hill, 2009}). Indeed preliminary
cross-sectional evidence suggests that highly religious males attend
religious service more frequently than highly religious females and that
church attendance is associated with greater offspring
(\citeproc{ref-Bulbulia_2015}{Bulbulia et al., 2015}). Although such
associational evidence is consistent with the predictions of both an
alloparenting model of cooperation and sexual-specific models of
cooperation, presently, we are unaware of any systematic attempt to
leverage time series data to assess whether religious behaviours cause
greater offspring.

Here, we first address this gap in understanding by quantitatively
assessing the causal effects of regular religious service attendance on
offspring in a population of {[}\textbf{describe here}{]}. Secondly, we
consider male-specific enhancements to fertility within this same
population.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected by {[}\textbf{Radim to clarify}{]}

We adopted a three-wave model for causal identification in which
baseline measures were obtained in 2003, the exposure or treatment was
measured in 2005, and the outcome, fertility was measured in 2013.
Notably we included measures of religious service in the baseline wave
(year 2003), allowing us to estimate a specific `incident exposure
effect' for religious service, rather than merely estimating the
prevalence effect (described below.)

\subsection{Baseline covariates}\label{baseline-covariates}

{[}\textbf{Radim to clarify}{]}

\begin{itemize}
\tightlist
\item
  Age: measured by {[}\textbf{Radim to clarify wording of measure}{]}
  (continuous)
\item
  Faith scale: measured by {[}\textbf{Radim to clarify the wording of
  measure}{]} (ordinal)
\item
  Female Gender: {[}\textbf{Radim to clarify the wording of measure}{]}
  (binary)
\item
  Parent Education: {[}\textbf{Radim to clarify the wording of
  measure}{]} (ordered factor)
\item
  Parent Income: {[}\textbf{Radim to clarify the wording of measure}{]}
  (continuous)
\item
  Race: {[}\textbf{Radim to clarify the wording of measure}{]} (factor)
\item
  Religious Category: {[}\textbf{Radim to clarify the wording of
  measure}{]} (factor)
\item
  Ritual Scale: {[}\textbf{Radim to clarify the wording of measure}{]}
  (ordinal)
\end{itemize}

\subsubsection{Exposure or Treatment
Variable}\label{exposure-or-treatment-variable}

We estimated causal effects by comparing two interventions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The marginal effect of religious service attendance across the entire
  sampled population.
\item
  The stratum-specific effects for females and males separately.
\end{enumerate}

We addressed four main causal questions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Population-wide effect: What would be the magnitude of the effect on
  offspring if everyone in the population attended religious services
  weekly, compared to if no one attended at all?
\item
  Female-specific effect: What is the magnitude of this effect
  (comparing regular religious service attendance to no attendance)
  among females, as proposed by cooperative-breeding models of religion?
\item
  Male-specific effect: What is the magnitude of this effect (comparing
  regular religious service attendance to no attendance) among males, as
  proposed by cooperative breeding models of religion?
\item
  Sex differences: Do the expected effects of religious service
  attendance differ between females and males, as suggested by sexual
  signalling models?
\end{enumerate}

Important note: We used the ritual scale variable at baseline for our
analysis, as it provides more detailed information than the binary
`religious service attendance at least weekly' variable.

\subsubsection{Outcome Measures}\label{outcome-measures}

Offspring measures were collected in the final study wave in 2013, eight
years after exposure and ten years after baseline. Since participants
were between 13 and 17 years old at baseline, their fertility was
assessed from 23 to 27 years old. {[}\textbf{Radim to check}{]}

We effects on the probability of having two or more children in 2013 --
or `replacement fertility'\ldots. {[}\textbf{say more}{]}.

\subsubsection{Inclusion Criteria}\label{inclusion-criteria}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Responded at baseline.
\item
  No missing data in the baseline wave for the religious service
  attendance.
\item
  Missing covariate data at baseline were permitted, handled using
  imputation in the \texttt{mice} package
  (\citeproc{ref-vanbuuren2018}{Van Buuren, 2018})
\item
  Loss-to-follow up permitted in both the exposure and outcome waves,
  handled using inverse-probability of censoring weights
  (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia, 2024a};
  \citeproc{ref-williams2021}{Williams \& Díaz, 2021}).
\end{enumerate}

Of the original 3,370 orgiginal participants, a total of 3,365
individuals met these criteria and were included in the study.

\newpage{}

\begin{longtable}[]{@{}ll@{}}

\caption{\label{tbl-table-demography}Baseline demographic statistics}

\tabularnewline

\toprule\noalign{}
\textbf{Baseline Exposure + Demographic Variables} & \textbf{N =
3,365} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
13 & 650 (19\%) \\
14 & 648 (19\%) \\
15 & 712 (21\%) \\
16 & 679 (20\%) \\
17 & 675 (20\%) \\
Unknown & 1 \\
\textbf{Faith Scale} & NA \\
1 & 236 (7.0\%) \\
2 & 378 (11\%) \\
3 & 1,077 (32\%) \\
4 & 1,025 (31\%) \\
5 & 643 (19\%) \\
Unknown & 6 \\
\textbf{Female} & 1,669 (50\%) \\
\textbf{Parent Education} & NA \\
Less than 12th grade & 282 (8.4\%) \\
High school & 767 (23\%) \\
Beyond high school & 2,311 (69\%) \\
Unknown & 5 \\
\textbf{Parent Income} & NA \\
Mean (SD) & 6 (3) \\
Range & 1, 11 \\
IQR & 4, 8 \\
Unknown & 206 \\
\textbf{Race} & NA \\
Black & 578 (17\%) \\
Hispanic & 384 (11\%) \\
Not disclosed & 21 (0.6\%) \\
Other & 173 (5.1\%) \\
White & 2,209 (66\%) \\
\textbf{Religion Cat} & NA \\
Black Protestant & 400 (12\%) \\
Catholic & 818 (24\%) \\
Conservative Protestant & 1,043 (31\%) \\
Jewish & 114 (3.4\%) \\
Mainline Protestant & 347 (10\%) \\
Mormon & 72 (2.1\%) \\
Not disclosed & 75 (2.2\%) \\
Not religious & 408 (12\%) \\
Other religion & 88 (2.6\%) \\
\textbf{Ritual Scale} & NA \\
1 & 619 (18\%) \\
2 & 527 (16\%) \\
3 & 276 (8.2\%) \\
4 & 233 (6.9\%) \\
5 & 420 (12\%) \\
6 & 763 (23\%) \\
7 & 527 (16\%) \\
\textbf{Ritual Weekly} & NA \\
0 & 2,075 (62\%) \\
1 & 1,290 (38\%) \\

\end{longtable}

Table~\ref{tbl-table-demography} reports baseline sample
characteristics.

\newpage{}

\begin{longtable}[]{@{}lll@{}}

\caption{\label{tbl-table-exposures-code}Exposures at baseline and
baseline + 1 (treatment) wave}

\tabularnewline

\toprule\noalign{}
\textbf{Exposure Variables by Wave} & \textbf{0}, N = 3,365 &
\textbf{1}, N = 3,365 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Ritual Weekly} & NA & NA \\
0 & 2,075 (62\%) & 1,861 (72\%) \\
1 & 1,290 (38\%) & 730 (28\%) \\
Unknown & 0 & 774 \\

\end{longtable}

Table~\ref{tbl-table-exposures-code} presents baseline (NZAVS time 10)
and exposure wave (NZAVS time 11) statistics for the exposure variable:
forgiveness (range 1-7). All models adjusted for the pandemic alert
level because the treatment wave (NZAVS time 11) occurred during New
Zealand's COVID-19 pandemic. The pandemic is not a ``confounder''
because a confounder must be related both to the treatment and the
outcome. At the end of the study, however, all participants had been
exposed to the global pandemic. However, to satisfy the causal
consistency assumption, all treatments must be conditionally equivalent
within levels of all covariates
(\citeproc{ref-vanderweele2013}{VanderWeele \& Hernan, 2013}). Because
COVID may have changed the quality and accessibility of forgiveness, we
included each participants lockdown condition as a covariate
(\citeproc{ref-sibley2021}{Sibley, 2021}). We employed inverse
probability of censoring weights, which were computed non-parametrically
within our statistical models using the \texttt{lmtp} package to
mitigate systematic biases arising from attrition and missingness.

\newpage{}

\begin{longtable}[]{@{}ll@{}}

\caption{\label{tbl-table-outcomes}Outcomes at baseline and
end-of-study}

\tabularnewline

\toprule\noalign{}
\textbf{Outcome Variables by Wave} & \textbf{N = 3,365} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Two or more Kids} & NA \\
0 & 1,919 (90\%) \\
1 & 222 (10\%) \\
Unknown & 1,224 \\
\textbf{Children Count} & NA \\
0 & 1,586 (74\%) \\
1 & 333 (16\%) \\
2 & 156 (7.3\%) \\
3 & 48 (2.2\%) \\
4 & 16 (0.7\%) \\
5 & 2 (\textless0.1\%) \\
Unknown & 1,224 \\

\end{longtable}

Table~\ref{tbl-table-outcomes} presents baseline and end-of-study
descriptive statistics for the outcome variables.

\newpage{}

\subsubsection{Handling Missing Data}\label{handling-missing-data}

Participants may have been lost to follow-up at the exposure wave or
outcome wave. To address bias from missing responses and attrition, we
implement the following strategies:

\textbf{Baseline missingness}: we employed the \texttt{ppm} algorithm
from the \texttt{mice} package in R (\citeproc{ref-vanbuuren2018}{Van
Buuren, 2018}) to impute missing baseline data. This method allowed us
to reconstruct incomplete datasets by estimating a plausible value for
missing observation. Because we could only pass one data set to the
\texttt{lmtp}, we employed single imputation. 1.3\% of covariate values
were missing at baseline. Eligibility for the study required fully
observed baseline treatment measures as well as treatment wave treatment
measures. Again, we only used baseline data to impute baseline
missingness (refer to Zhang et al.
(\citeproc{ref-zhang2023shouldMultipleImputation}{2023})).

\textbf{Exposure missingness}: to address bias for the target population
arising from missing values in the exposures, we used inverse
probability of censoring weights (\citeproc{ref-hernan2024WHATIF}{Hernan
\& Robins, 2024}).

\textbf{Outcome missingness}: to address confounding and selection bias
arising from missing responses and panel attrition, we applied censoring
weights obtained using nonparametric machine learning ensembles afforded
by the \texttt{lmtp} package (and its dependencies) in R
(\citeproc{ref-williams2021}{Williams \& Díaz, 2021}).

We implemented inverse probability of censoring weights to address
potential bias from loss to follow-up between the baseline and exposure
waves. The process involved the following steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  First, we used a set of baseline variables as predictors for loss to
  follow-up, excluding the outcome variable itself.
\item
  Second, we used one-hot encoding to render categorical variables
  binary. These were: `religious group affiliation', `parent education',
  and race'.
\item
  Next, we employed the SuperLearner algorithm to predict the
  probability of being lost to follow-up. Our SuperLearner ensemble
  included various machine learning methods: generalised linear models
  with regularisation (glmnet), extreme gradient boosting (xgboost),
  random forests (ranger), multivariate adaptive regression splines
  (earth), and polynomial spline regression (polymars).
\item
  The SuperLearner model was trained using 10-fold cross-validation to
  optimise prediction accuracy.
\item
  Based on the predicted probabilities, we calculated inverse
  probability weights. For participants lost to follow-up, the weight
  was one divided by their predicted probability of being lost. For
  those not lost, the weight was one divided by their predicted
  probability of not being lost.
\item
  To mitigate extreme weights, we computed stabilised weights by
  multiplying the inverse probability weights by the marginal
  probability of not being lost to follow-up.
\item
  These stabilised censoring weights were then combined with the
  original sample weights to create composite weights for subsequent
  analyses.
\item
  Participants lost to follow-up between baseline and the exposure wave
  were removed from the analysis dataset.
\end{enumerate}

Our method assumes that loss to follow-up/missing responses are `missing
at random' (MAR) conditional on the observed variables. This means that
all variables influencing dropout are captured by the variables used in
the prediction model. If there are unobserved variables influencing
dropout, some bias may remain. This approach is also subject to model
misspecification bias. However, by using SuperLearner - which combines
multiple machine learning methods -- our models can flexibly (and
non-parametrically) capture complex relationships in the data and reduce
the risk of model misspecification compared to using a single model.

\subsubsection{Causal Assumptions}\label{causal-assumptions}

To estimate causal effects reliably, our study must credibly meet three
fundamental assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal Consistency}: we assume that the potential outcomes for
  a given individual under a particular treatment correspond to the
  observed outcomes when that treatment is administered. This assumes
  that potential outcomes are solely a function of the treatment and
  measured covariates, without interference by the mode of treatment
  administration (VanderWeele (\citeproc{ref-vanderweele2009}{2009});
  VanderWeele \& Hernan (\citeproc{ref-vanderweele2013}{2013})).
\item
  \textbf{Exchangeability}: we assume that, conditional on observed
  covariates, assignment to the treatment group is independent of the
  potential outcomes; that is, we assume no unmeasured confounding
  (Hernan \& Robins (\citeproc{ref-hernan2024WHATIF}{2024}); Chatton et
  al. (\citeproc{ref-chatton2020}{2020})).
\item
  \textbf{Positivity}: we assume that within all covariate-defined
  strata necessary for achieving exchangeability, there is a non-zero
  probability of receiving each possible treatment level. The positivity
  assumption ensures that treatment effects are estimable across the
  spectrum of observed covariate combinations (Westreich \& Cole
  (\citeproc{ref-westreich2010}{2010})).
\end{enumerate}

For further discussion, see Bulbulia
(\citeproc{ref-bulbulia2023}{2024c}); Bulbulia et al.
(\citeproc{ref-bulbulia2023a}{2023}); Bulbulia
(\citeproc{ref-bulbulia2023b}{2023})

The target population for this study comprises {[}\textbf{Radim to
check}{]}

\subsubsection{Causal Identification}\label{causal-identification}

\begin{table}

\caption{\label{tbl-02}This table presents a causal diagram using
VanderWeele et al. (\citeproc{ref-vanderweele2020}{2020})'s approach for
confounding control in a three-wave panel design. By including baseline
measures of all outcomes in every model, as well as including the
baseline treatment, and a rich array of covariates, we assume may back
door paths between the treatment and outcomes will be blocked. However,
because confounding cannot be ensured, we also perform sensitivity
analyses.}

\centering{

\threevanderweeele

}

\end{table}%

To address confounding in our analysis, we implement VanderWeele
(\citeproc{ref-vanderweele2019}{2019})'s \emph{modified disjunctive
cause criterion} by following these steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Identified all common causes} of both the treatment and
  outcomes to ensure a comprehensive approach to confounding control.
\item
  \textbf{Excluded instrumental variables} that affect the exposure but
  not the outcome. Instrumental variables do not contribute to
  controlling confounding and can reduce the efficiency of the
  estimates.
\item
  \textbf{Included proxies for unmeasured confounders} affecting both
  exposure and outcome. According to the principles of d-separation,
  using proxies allows us to control for their associated unmeasured
  confounders indirectly.
\item
  \textbf{Controlled for baseline exposure} and \textbf{baseline
  outcome}. Both are used as proxies for unmeasured common causes,
  enhancing the robustness of our causal estimates.
\end{enumerate}

Table~\ref{tbl-02} presents a causal diagram describing the general
confounding control of VanderWeele et al.
(\citeproc{ref-vanderweele2020}{2020}).

These methods adhere to the guidelines provided in
(\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia, 2024a}).

\subsubsection{Statistical Estimator}\label{statistical-estimator}

We employed Targeted Maximum Likelihood Estimation (TMLE), a
double-robust method for causal inference. TMLE operates through a
two-step process that involves modeling both the outcome and treatment
(exposure).

In the first step, we used machine learning algorithms with ten-fold
cross-validation to flexibly model the relationships between treatments,
covariates, and outcomes. This approach allows us to efficiently account
for complex, high-dimensional covariate spaces without imposing
restrictive model assumptions. We used the \texttt{SuperLearner} package
(\citeproc{ref-polley2023}{Polley et al., 2023}), and implemented an
ensemble learning method combining the following algorithms:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \texttt{SL.glmnet}: for regularised linear models, managing high
  dimensionality and collinearity
  (\citeproc{ref-glmnet_use_2010}{Friedman et al., 2010};
  \citeproc{ref-glmnet_2023}{Tay et al., 2023}).
\item
  \texttt{SL.xgboost}: employing gradient boosting to capture complex
  interactions (\citeproc{ref-xgboost2023}{Chen et al., 2023}).
\item
  \texttt{SL.ranger}: random forests to handle non-linear relationships
  (\citeproc{ref-ranger_2017}{Wright \& Ziegler, 2017}).
\item
  \texttt{SL.earth}: using multivariate adaptive regression splines for
  flexible modelling (\citeproc{ref-earth_2024}{Milborrow, 2024}).
\item
  \texttt{SL.polymars}: applying polynomial spline regression for
  additional flexibility (\citeproc{ref-polspline_2024}{Kooperberg,
  2024}).
\end{enumerate}

The ensemble approach of \texttt{SuperLearner} optimally combines
predictions from these models, leveraging their strengths while
mitigating individual weaknesses.

In the second step, TMLE `targets' the initial estimates by
incorporating information about the observed data distribution,
improving the accuracy of the causal effect estimate. This targeting
step is crucial for reducing bias in the final estimate.

We implemented TMLE using the \texttt{lmtp} package, which is designed
for longitudinal causal inference. The package allows for the estimation
of causal effects under complex, time-varying treatments and confounding
(\citeproc{ref-williams2021}{Williams \& Díaz, 2021}).

To handle potential bias from loss to follow-up, we implemented inverse
probability of censoring weights. These weights were calculated using
the same \texttt{SuperLearner} ensemble to predict the probability of
being lost to follow-up based on baseline characteristics
(\citeproc{ref-hoffman2023}{Hoffman et al., 2023};
\citeproc{ref-williams2021}{Williams \& Díaz, 2021}).

For binary outcomes (having two or more children), we estimated risk
ratios. For continuous outcomes (total number of children), we estimated
additive effects. We conducted separate analyses for the overall sample
and stratified by sex to explore examine heterogeneity in treatment
effects.

This approach combines the strengths of machine learning for flexible
modelling with the statistical properties of TMLE, providing robust and
efficient estimates of causal effects while accounting for complex
confounding and loss to follow-up.

Tables and Graphs were produced using the \texttt{margot} package
(\citeproc{ref-margot2024}{Bulbulia, 2024b})

\subsubsection{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess the sensitivity of results to unmeasured confounding, we
report VanderWeele and Ding's E-value in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele \& Ding, 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden et al., 2020};
\citeproc{ref-vanderweele2020}{VanderWeele et al., 2020}). To evaluate
the strength of evidence, we use the bound of the E-value 95\%
confidence interval closest to 1. Although the E-value provides an
approximate sensitivity analysis, its interpretation is straightforward.

\subsubsection{Evidence for Change in the Treatment
Variable}\label{evidence-for-change-in-the-treatment-variable}

Table~\ref{tbl-transition} clarifies the change in the treatment
variable from the baseline wave to the baseline + 1 wave across the
sample. Assessing change in a variable is essential for evaluating the
positivity assumption and recovering evidence for the incident-exposure
effect of the treatment variable (\citeproc{ref-danaei2012}{Danaei et
al., 2012}; \citeproc{ref-hernan2024WHATIF}{Hernan \& Robins, 2024};
\citeproc{ref-vanderweele2020}{VanderWeele et al., 2020}).

\begin{longtable}[]{@{}ccc@{}}

\caption{\label{tbl-transition}This transition matrix captures shifts in
states across the treatment intervals. Each cell in the matrix
represents the count of individuals transitioning from one state to
another. The rows correspond to the treatment at baseline (From), and
the columns correspond to the state at the following wave (To).
\textbf{Diagonal entries} (in \textbf{bold}) correspond to the number of
individuals who remained in their initial state across both waves.
\textbf{Off-diagonal entries} correspond to the transitions of
individuals from their baseline state to a different state in the
treatment wave. A higher number on the diagonal relative to the
off-diagonal entries in the same row indicates greater stability in a
state. Conversely, higher off-diagonal numbers suggest more frequent
shifts from the baseline state to other states..}

\tabularnewline

\toprule\noalign{}
From & \textless{} weekly & \textgreater= weekly \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textless{} weekly & \textbf{1363} & 188 \\
\textgreater= weekly & 498 & \textbf{542} \\

\end{longtable}

\newpage{}

\subsection{Results}\label{results}

\paragraph{Population-wide effect: What would be the magnitude of effect
on the probability of two or more offspring if everyone in the
population attended religious services weekly, compared to if no one
attended at
all?}\label{population-wide-effect-what-would-be-the-magnitude-of-effect-on-the-probability-of-two-or-more-offspring-if-everyone-in-the-population-attended-religious-services-weekly-compared-to-if-no-one-attended-at-all}

The effect estimate for regular religious service on having two or more
offspring eight years later on the risk\_ratio scale is 1.622 {[}1.14,
2.306{]}. The E-value for this estimate is 2.626, with a lower bound of
1.539. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.539 to negate the observed effect. Weaker confounding would not
overturn it. Here, \textbf{there is evidence for causality}.

\paragraph{Female-specific effect: What is the magnitude of effect on
the probability of two or more offspring (comparing regular religious
service attendance to no attendance) among females, as proposed by
cooperative-breeding models of
religion?}\label{female-specific-effect-what-is-the-magnitude-of-effect-on-the-probability-of-two-or-more-offspring-comparing-regular-religious-service-attendance-to-no-attendance-among-females-as-proposed-by-cooperative-breeding-models-of-religion}

For females, the effect estimate for regular religious service on having
two or more offspring eight years later on the risk\_ratio scale is
1.303 {[}0.804, 2.112{]}. The E-value for this estimate is 1.931, with a
lower bound of 1. Here, \textbf{the evidence for causality is not
reliable}.

\paragraph{Male-specific effect: What is the magnitude of effect on the
probability of two or more offspringcomparing regular religious service
attendance to no attendance) among males, as proposed by
cooperative-breeding models of
religion?}\label{male-specific-effect-what-is-the-magnitude-of-effect-on-the-probability-of-two-or-more-offspringcomparing-regular-religious-service-attendance-to-no-attendance-among-males-as-proposed-by-cooperative-breeding-models-of-religion}

For males, the effect estimate for regular religious service on the
risk\_ratio scale is 3.142 {[}1.435, 6.878{]}. The E-value for this
estimate is 5.736, with a lower bound of 2.225. At this lower bound,
unmeasured confounders would need a minimum association strength with
both the intervention sequence and outcome of 2.225 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{the evidence for causality is strong}.

\paragraph{Sex differences: Do the expected effects of religious service
attendance on the probability of two or more offspring differ between
females and males, as suggested by sexual signalling
models?}\label{sex-differences-do-the-expected-effects-of-religious-service-attendance-on-the-probability-of-two-or-more-offspring-differ-between-females-and-males-as-suggested-by-sexual-signalling-models}

The difference in the relative risk ratio between the focal group
(males) and the reference group (females) is 2.41 with a standard error
of 0.228 and a 95\% ci of {[}1.54, 3.77{]}. We infer that males who
regularly attend religious service have a 2.41 fold-increase in the
probability of having at least two offspring in an eight year follow up
windown as compared with females.

Figure~\ref{fig-1_1} \emph{A} and Table~\ref{tbl-1_1}: describe both the
marginal and sex-specific results for the eight-year causal effect of
religious service on the probability of having two or more offspring.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4787}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1702}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0638}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0745}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0851}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1277}}@{}}

\caption{\label{tbl-1_1}This table presents the causa leffect estimates
for the population, males, and females on the probability of
replacement-level fertility eight years after `treatment'.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Weekly Religious Service Attendance: Males & 3.142 & 1.435 & 6.878 &
5.736 & 2.225 \\
Weekly Religious Service Attendance: ATE & 1.622 & 1.140 & 2.306 & 2.626
& 1.539 \\
Weekly Religious Service Attendance: Females & 1.303 & 0.804 & 2.112 &
1.931 & 1.000 \\

\end{longtable}

\newpage{}

\begin{figure}

\centering{

\includegraphics{24-radim-fertility-usa_files/figure-pdf/fig-1_1-1.pdf}

}

\caption{\label{fig-1_1}This figure presents the causa effect estimates
for the population, males, and females on the probability of
replacement-level fertility eight years after `treatement'.}

\end{figure}%

\newpage{}

Our findings may be summaries as follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Overall Effect (ATE): Regular religious service attendance is
  associated with a 62.2\% increase in the probability of having two or
  more children (RR = 1.622, 95\% CI: 1.140 to 2.306). This effect is
  statistically reliable as the confidence interval does not include 1.
  The E-vale of 1.549 suggests moderate robustness to unmeasured
  confounding.
\item
  Sex-Specific Effects:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Females: There's a 30.3\% increase in probability for females (RR =
  1.303, 95\% CI: 0.804 to 2.112), but this effect is not statistically
  reliable as the confidence interval includes 1. We cannot rule out the
  prospect that religious service attendance has no effect in the eight
  years following the regular religious service `treatment.'
\item
  Males: There's a much larger 214.2\% increase in probability for males
  (RR = 3.142, 95\% CI: 1.435 to 6.878). This effect is statistically
  reliable and considerably more robust than for females.
\end{itemize}

We infer that the causal effect of religious service attendance in the
target population (defined to be the sample population at baseline) is
considerably stronger in males than in females. Recall that the E-values
indicate the strength of unmeasured confounding needed to explain away
these effects. The male-specific result (E-value = 5.736) appears more
robust to potential unmeasured confounding than the female-specific or
overall results. This finding suggests potential sex-specific
differences in how religious service attendance relates to fertility.

In summary, regular religious service attendance causally associateed
with increased probability of having two or more children, with a
powerful effect observed in males. However, the wide confidence
intervals, especially for the sex-specific estimates, suggest some
uncertainty in the precise magnitude of these effects.

\subsection{Discussion}\label{discussion}

\subsubsection{Limitation}\label{limitation}

\begin{itemize}
\tightlist
\item
  Population. Generality?
\item
  Sample (young not much scope for religious change or for fertility)
\item
  Uncertainty in the location estimates for males (although bounded from
  zero).
\item
  Reliance on model assumptions for missingingness (MAR
  assumptions\ldots)
\end{itemize}

\subsubsection{Strengths}\label{strengths}

\begin{itemize}
\tightlist
\item
  Evidence for causal effect of religious service on fertility is
  considerable, particularly for males.
\item
  Evidence is causal.
\item
  Sensitivity analysis shows robustness to unmeasured confounding .
\end{itemize}

Future research\ldots{} etc.

\newpage{}

\subsubsection{Ethics}\label{ethics}

\emph{include}

\subsubsection{Data Availability}\label{data-availability}

The code for this analysis can be found here:
https://github.com/go-bayes/models/blob/main/scripts/24-radim-usa/jb-analysis-for-radim.R

{[}radim to provide data as ethics permits{]}

\subsubsection{Acknowledgements}\label{acknowledgements}

\emph{Authors to fill out} JS\ldots{} RC\ldots{} JB recewived support
from Templeton Religious Trust (TRT0196; TRT0418) and the Max Planck
Institute for the Science of Human History. The funders had no role in
preparing the manuscript or deciding to publish it.

\subsubsection{Author Statement}\label{author-statement}

\emph{Authors to amend}

RC conceived of the study and wrote the first draft of the manuscript,
with John Shaver advising. JB and RC did the analysis. All authors
contributed to the study.

\newpage{}

\subsection{Appendix A: Imbalance of Confounding Covariates
Treatments}\label{appendix-exposures}

Figure~\ref{fig-match_1} shows imbalance of covariates on the treatment
at the treatment wave. The variable on which there is strongest
imbalance is the baseline measure of religious service attendance. It is
important to adjust for this measure both for confounding control and to
better estimate an incident exposure effect for the religious service at
the treatment wave (in contrast to merely estimating a prevalence
effect). See VanderWeele et al. (\citeproc{ref-vanderweele2020}{2020}).

\begin{figure}

\centering{

\includegraphics{24-radim-fertility-usa_files/figure-pdf/fig-match_1-1.pdf}

}

\caption{\label{fig-match_1}This figure shows the imbalance in
covariates on the treatment}

\end{figure}%

tbl-table-exposures-code presents baseline (NZAVS time 10) and exposure
wave (NZAVS time 11) statistics for the exposure variable: weekly
religious service. Graph was produced using the \texttt{WeightIt} and
\texttt{Cobalt} packages in R (\citeproc{ref-greifer2023a}{Greifer,
2023b}, \citeproc{ref-greifer2023b}{2023a}).

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-alexander2017biology}
Alexander, R. (2017). \emph{The biology of moral systems}. Routledge.

\bibitem[\citeproctext]{ref-blume2009reproductive}
Blume, M. (2009). The reproductive benefits of religious affiliation.
\emph{The Biological Evolution of Religious Mind and Behavior},
117--126.

\bibitem[\citeproctext]{ref-bulbulia2023b}
Bulbulia, J. A. (2023). \emph{Causal diagrams (directed acyclic graphs):
A practical guide}. \url{https://osf.io/b23k7}

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, J. A. (2024a). A practical guide to causal inference in
three-wave panel studies. \emph{PsyArXiv Preprints}.
\url{https://doi.org/10.31234/osf.io/uyg3d}

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, J. A. (2024b). \emph{Margot: MARGinal observational
treatment-effects}. \url{https://doi.org/10.5281/zenodo.10907724}

\bibitem[\citeproctext]{ref-bulbulia2023}
Bulbulia, J. A. (2024c). Methods in causal inference part 1: Causal
diagrams and confounding. \emph{Evolutionary Human Sciences}, \emph{6}.

\bibitem[\citeproctext]{ref-bulbulia2023a}
Bulbulia, J. A., Afzali, M. U., Yogeeswaran, K., \& Sibley, C. G.
(2023). Long-term causal effects of far-right terrorism in {N}ew
{Z}ealand. \emph{PNAS Nexus}, \emph{2}(8), pgad242.

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, J. A., Shaver, J. H., Greaves, L., Sosis, R., \& Sibley, C. G.
(2015). Religion and parental cooperation: An empirical test of slone's
sexual signaling model. In S. J. D. amd Van Slyke J. (Ed.), \emph{The
attraction of religion: A sexual selectionist account} (pp. 29--62).
Bloomsbury Press.

\bibitem[\citeproctext]{ref-chatton2020}
Chatton, A., Le Borgne, F., Leyrat, C., Gillaizeau, F., Rousseau, C.,
Barbin, L., Laplaud, D., Léger, M., Giraudeau, B., \& Foucher, Y.
(2020). G-computation, propensity score-based methods, and targeted
maximum likelihood estimator for causal inference with different
covariates sets: a comparative simulation study. \emph{Scientific
Reports}, \emph{10}(1), 9219.
\url{https://doi.org/10.1038/s41598-020-65917-x}

\bibitem[\citeproctext]{ref-xgboost2023}
Chen, T., He, T., Benesty, M., Khotilovich, V., Tang, Y., Cho, H., Chen,
K., Mitchell, R., Cano, I., Zhou, T., Li, M., Xie, J., Lin, M., Geng,
Y., Li, Y., \& Yuan, J. (2023). \emph{Xgboost: Extreme gradient
boosting}. \url{https://CRAN.R-project.org/package=xgboost}

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G., Tavakkoli, M., \& Hernán, M. A. (2012). Bias in
observational studies of prevalent users: lessons for comparative
effectiveness research from a meta-analysis of statins. \emph{American
Journal of Epidemiology}, \emph{175}(4), 250--262.
\url{https://doi.org/10.1093/aje/kwr301}

\bibitem[\citeproctext]{ref-glmnet_use_2010}
Friedman, J., Hastie, T., \& Tibshirani, R. (2010). Regularization paths
for generalized linear models via coordinate descent. \emph{Journal of
Statistical Software}, \emph{33}(1), 1.

\bibitem[\citeproctext]{ref-greifer2023b}
Greifer, N. (2023a). \emph{Cobalt: Covariate balance tables and plots}.

\bibitem[\citeproctext]{ref-greifer2023a}
Greifer, N. (2023b). \emph{WeightIt: Weighting for covariate balance in
observational studies}.

\bibitem[\citeproctext]{ref-gurven2009men}
Gurven, M., \& Hill, K. (2009). Why do men hunt? A reevaluation of
{``man the hunter''} and the sexual division of labor. \emph{Current
Anthropology}, \emph{50}(1), 51--74.

\bibitem[\citeproctext]{ref-gurven2006energetic}
Gurven, M., \& Walker, R. (2006). Energetic demand of multiple
dependents and the evolution of slow human growth. \emph{Proceedings of
the Royal Society B: Biological Sciences}, \emph{273}(1588), 835--841.

\bibitem[\citeproctext]{ref-hernan2024WHATIF}
Hernan, M. A., \& Robins, J. M. (2024). \emph{Causal inference: What
if?} Taylor \& Francis.
\url{https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/}

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, K. L., Salazar-Barreto, D., Rudolph, K. E., \& Díaz, I. (2023).
\emph{Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures}.
\url{https://doi.org/10.48550/arXiv.2304.09460}

\bibitem[\citeproctext]{ref-irons2001religion}
Irons, W. (2001). Religion as a hard-to-fake sign of commitment.
\emph{Evolution and the Capacity for Commitment}, \emph{292309}.

\bibitem[\citeproctext]{ref-polspline_2024}
Kooperberg, C. (2024). \emph{Polspline: Polynomial spline routines}.
\url{https://CRAN.R-project.org/package=polspline}

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A., Mathur, M. B., \& VanderWeele, T. J. (2020). Conducting
sensitivity analysis for unmeasured confounding in observational studies
using e-values: The evalue package. \emph{The Stata Journal},
\emph{20}(1), 162--175.

\bibitem[\citeproctext]{ref-earth_2024}
Milborrow, S. (2024). \emph{Earth: Multivariate adaptive regression
splines}. \url{https://CRAN.R-project.org/package=earth}

\bibitem[\citeproctext]{ref-polley2023}
Polley, E., LeDell, E., Kennedy, C., \& Laan, M. van der. (2023).
\emph{SuperLearner: Super learner prediction}.
\url{https://CRAN.R-project.org/package=SuperLearner}

\bibitem[\citeproctext]{ref-rowthorn2011religion}
Rowthorn, R. (2011). Religion, fertility and genes: A dual inheritance
model. \emph{Proceedings of the Royal Society B: Biological Sciences},
\emph{278}(1717), 2519--2527.

\bibitem[\citeproctext]{ref-shaver2020church}
Shaver, J. H., Power, E. A., Purzycki, B. G., Watts, J., Sear, R.,
Shenk, M. K., Sosis, R., \& Bulbulia, J. A. (2020). Church attendance
and alloparenting: An analysis of fertility, social support and child
development among {E}nglish mothers. \emph{Philosophical Transactions of
the Royal Society B}, \emph{375}(1805), 20190428.

\bibitem[\citeproctext]{ref-shaver2019alloparenting}
Shaver, J. H., Sibley, C. G., Sosis, R., Galbraith, D., \& Bulbulia, J.
(2019). Alloparenting and religious fertility: A test of the religious
alloparenting hypothesis. \emph{Evolution and Human Behavior},
\emph{40}(3), 315--324.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, C. G. (2021). \emph{Sampling procedure and sample details for
the new zealand attitudes and values study}.
\url{https://doi.org/10.31234/osf.io/wgqvy}

\bibitem[\citeproctext]{ref-sosis2003cooperation}
Sosis, R., \& Bressler, E. R. (2003). Cooperation and commune longevity:
A test of the costly signaling theory of religion. \emph{Cross-Cultural
Research}, \emph{37}(2), 211--239.

\bibitem[\citeproctext]{ref-sterelny2007social}
Sterelny, K. (2007). Social intelligence, human intelligence and niche
construction. \emph{Philosophical Transactions of the Royal Society B:
Biological Sciences}, \emph{362}(1480), 719--730.

\bibitem[\citeproctext]{ref-sterelny2011hominins}
Sterelny, K. (2011). From hominins to humans: How sapiens became
behaviourally modern. \emph{Philosophical Transactions of the Royal
Society B: Biological Sciences}, \emph{366}(1566), 809--822.

\bibitem[\citeproctext]{ref-glmnet_2023}
Tay, J. K., Narasimhan, B., \& Hastie, T. (2023). Elastic net
regularization paths for all generalized linear models. \emph{Journal of
Statistical Software}, \emph{106}.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S. (2018). \emph{Flexible imputation of missing data}. CRC
press.

\bibitem[\citeproctext]{ref-vanderweele2009}
VanderWeele, T. J. (2009). Concerning the consistency assumption in
causal inference. \emph{Epidemiology}, \emph{20}(6), 880.
\url{https://doi.org/10.1097/EDE.0b013e3181bd5638}

\bibitem[\citeproctext]{ref-vanderweele2019}
VanderWeele, T. J. (2019). Principles of confounder selection.
\emph{European Journal of Epidemiology}, \emph{34}(3), 211--219.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, T. J., \& Ding, P. (2017). Sensitivity analysis in
observational research: Introducing the {E}-value. \emph{Annals of
Internal Medicine}, \emph{167}(4), 268--274.
\url{https://doi.org/10.7326/M16-2607}

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, T. J., \& Hernan, M. A. (2013). Causal inference under
multiple versions of treatment. \emph{Journal of Causal Inference},
\emph{1}(1), 1--20.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, T. J., Mathur, M. B., \& Chen, Y. (2020). Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \emph{35}(3), 437--466.

\bibitem[\citeproctext]{ref-westreich2010}
Westreich, D., \& Cole, S. R. (2010). Invited commentary: positivity in
practice. \emph{American Journal of Epidemiology}, \emph{171}(6).
\url{https://doi.org/10.1093/aje/kwp436}

\bibitem[\citeproctext]{ref-williams2021}
Williams, N. T., \& Díaz, I. (2021). \emph{{l}mtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
\url{https://doi.org/10.5281/zenodo.3874931}

\bibitem[\citeproctext]{ref-ranger_2017}
Wright, M. N., \& Ziegler, A. (2017). {ranger}: A fast implementation of
random forests for high dimensional data in {C++} and {R}. \emph{Journal
of Statistical Software}, \emph{77}(1), 1--17.
\url{https://doi.org/10.18637/jss.v077.i01}

\bibitem[\citeproctext]{ref-zhang2023shouldMultipleImputation}
Zhang, J., Dashti, S. G., Carlin, J. B., Lee, K. J., \& Moreno-Betancur,
M. (2023). Should multiple imputation be stratified by exposure group
when estimating causal effects via outcome regression in observational
studies? \emph{BMC Medical Research Methodology}, \emph{23}(1), 42.

\end{CSLReferences}



\end{document}
