% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%


\PassOptionsToPackage{table}{xcolor}

\documentclass[
  10pt,
  letterpaper,
]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=0.85in,left=2.75in,footskip=0.75in]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

% Use adjustwidth environment to exceed column width (see example table in text)
\usepackage{changepage}

% marvosym package for additional characters
\usepackage{marvosym}

% cite package, to clean up citations in the main text. Do not remove.
% Using natbib instead
% \usepackage{cite}

% Use nameref to cite supporting information files (see Supporting Information section for more info)
\usepackage{nameref,hyperref}

% line numbers
\usepackage[right]{lineno}

% ligatures disabled
\usepackage{microtype}
\DisableLigatures[f]{encoding = *, family = * }

% create "+" rule type for thick vertical lines
\newcolumntype{+}{!{\vrule width 2pt}}

% create \thickcline for thick horizontal lines of variable length
\newlength\savedwidth
\newcommand\thickcline[1]{%
  \noalign{\global\savedwidth\arrayrulewidth\global\arrayrulewidth 2pt}%
  \cline{#1}%
  \noalign{\vskip\arrayrulewidth}%
  \noalign{\global\arrayrulewidth\savedwidth}%
}

% \thickhline command for thick horizontal lines that span the table
\newcommand\thickhline{\noalign{\global\savedwidth\arrayrulewidth\global\arrayrulewidth 2pt}%
\hline
\noalign{\global\arrayrulewidth\savedwidth}}

% Text layout
\raggedright
\setlength{\parindent}{0.5cm}
\textwidth 5.25in 
\textheight 8.75in

% Bold the 'Figure #' in the caption and separate it from the title/caption with a period
% Captions will be left justified
\usepackage[aboveskip=1pt,labelfont=bf,labelsep=period,justification=raggedright,singlelinecheck=off]{caption}
\renewcommand{\figurename}{Fig}

% Remove brackets from numbering in List of References
\makeatletter
\renewcommand{\@biblabel}[1]{\quad#1.}
\makeatother

% Header and Footer with logo
\usepackage{lastpage,fancyhdr}
\usepackage{epstopdf}
%\pagestyle{myheadings}
\pagestyle{fancy}
\fancyhf{}
%\setlength{\headheight}{27.023pt}
%\lhead{\includegraphics[width=2.0in]{PLOS-submission.eps}}
\rfoot{\thepage/\pageref{LastPage}}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrule}{\hrule height 2pt \vspace{2mm}}
\fancyheadoffset[L]{2.25in}
\fancyfootoffset[L]{2.25in}
\lfoot{\today}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[numbers,square,comma]{natbib}
\bibliographystyle{plos2015}
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal Effects of Religious Service Attendance: Evidence Using Novel Measures From A National Longitudinal Panel},
  pdfauthor={Joseph A. Bulbulia; Don E Davis; Kenneth G. Rice; Chris G. Sibley; Geoffrey Troughton},
  pdfkeywords={Causal
Inference, Charity, Church, Cooperation, Religion, Shift
Intervention, Volunteering},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}



\begin{document}
\vspace*{0.2in}

% Title must be 250 characters or less.
\begin{flushleft}
{\Large
\textbf\newline{Causal Effects of Religious Service Attendance: Evidence
Using Novel Measures From A National Longitudinal
Panel} % Please use "sentence case" for title and headings (capitalize only the first word in a title (or heading), the first word in a subtitle (or subheading), and any proper nouns).
}
\newline
\\
% Insert author names, affiliations and corresponding author email (do not include titles, positions, or degrees).
Joseph A. Bulbulia\textsuperscript{1*}, Don E
Davis\textsuperscript{2}, Kenneth G. Rice\textsuperscript{2}, Chris G.
Sibley\textsuperscript{3}, Geoffrey Troughton\textsuperscript{4}
\\
\bigskip
\textbf{1} Victoria University of Wellington, New
Zealand, \\ \textbf{2} Georgia State University, \\ \textbf{3} School of
Psychology, University of Auckland, \\ \textbf{4} Victoria University of
Wellington, 
\bigskip

% Insert additional author notes using the symbols described below. Insert symbol callouts after author names as necessary.
% 
% Remove or comment out the author notes below if they aren't used.
%
% Primary Equal Contribution Note
\Yinyang These authors contributed equally to this work.

% Additional Equal Contribution Note
% Also use this double-dagger symbol for special authorship notes, such as senior authorship.
%\ddag These authors also contributed equally to this work.

% Current address notes
\textcurrency Current Address: Dept/Program/Center, Institution Name, City, State, Country % change symbol to "\textcurrency a" if more than one current address note
% \textcurrency b Insert second current address 
% \textcurrency c Insert third current address

% Deceased author note
\dag Deceased

% Group/Consortium Author Note
\textpilcrow Membership list can be found in the Acknowledgments section.

% Use the asterisk to denote corresponding authorship and provide email address in note below.
* joseph.bulbulia@vuw.ac.nz

\end{flushleft}

\section*{Abstract}
Causal investigations for the effects of religion on prosociality must
be precise. One must articulate a specific causal contrast for a feature
of religion, select appropriate prosociality measures, define the target
population, gather time-series data, and, only after meeting
identification assumptions, conduct statistical and sensitivity
analyses. Here, we examine three distinct interventions on religious
service attendance (increase, decrease, maintain) across a longitudinal
dataset of 33,198 New Zealanders from 2018 to 2021. Study 1 quantifies
the effect of religious service attendance on charitable contributions
and volunteerism. Studies 2 and 3 investigate the effects of religious
service on the relative risk of receiving aid and financial support from
others during the past week, employing measures designed to minimise
self-reporting bias. Across all studies, the observed effects are
substantially less pronounced than cross-sectional regressions might
imply. Nonetheless, regular attendance across the population would
enhance charitable donations by 4\% of the New Zealand Government's
annual spending. This research underscores the essential role of
formulating precise causal questions and establishes a methodological
framework for answering them in the scientific study of cultural
practices.


\linenumbers
\subsection{Introduction}\label{introduction}

A central question in the scientific study of religion is whether
religion fosters cooperation
\citep{johnson2005, norenzayan2016, bulbuliaj.2013, watts2016, watts2015, sosis2003cooperation, sibley2012a}.
However, quantifying causal effects for religion, and many other social
behaviours, presents significant challenges. Much of religion eludes
randomised experiments. Additionally, valid causal conclusions from
observational data require both high-resolution time-series data and
robust methods for causal inference. Few studies combine these
characteristics (refer to \citet{kelly2024religiosity} for a recent
research summary and \citet{chen2020religious} for a well-designed
observational study on religious service and mental health).

Moreover, the question ``Does religion cause prosociality?'' lacks
specificity. To refine this question, we must articulate clear causal
contrasts and their scale, select specific measures of ``prosociality,''
define our target population, gather appropriate time-series data, and,
assuming that causal assumptions and identification criteria are met,
calculate statistical estimates. Having obtained these estimates, which
rely on assumptions, we must evaluate robustness using sensitivity
analyses
\citep{hernan2024WHATIF, ogburn2021, bulbulia2022, linden2020EVALUE}.

Here, we use comprehensive panel data from 33,198 participants in the
New Zealand Attitudes and Values Study from 2018-2021 to quantify the
effects of clearly defined interventions in religious attendance across
the population of New Zealanders on two features of prosociality:
charitable financial donations and volunteering, measured both by
self-reported giving as well as help received.

We define causal effects as quantitative contrasts between potential
outcomes under intervention on religious service attendance, the
``treatment,'' within a specified population (see \citet{rubin2005};
\citet{neyman1923}, \citet{robins1986}; our approach is consistent with
the counterfactual approaches \citet{pearl2009},
\citet{vanderlaan2018}). We express these interventions as ``modified
treatment policies'' and obtain causal inferences by contrasting
inferred population treatment averages
\citep{haneuse2013estimation, diaz2023lmtp, díaz2021, hoffman2023}.

Our initial causal contrast investigates: ``What would be the average
difference across the New Zealand population if everyone attended
religious services regularly (at least four times per month) versus if
no one attended?'' This theoretical question simulates a hypothetical
experiment with random assignment to regular or non-attendance.

The second contrast investigates: ``What would be the average difference
across the New Zealand population if everyone attended religious
services regularly compared with maintaining the status quo?'' This
scenario does not require shifting regular attendees to non-attendance;
here, results inform practical policies targeting non-regular attendees
who might start.

The third contrast examines: ``What would be the average difference
across the New Zealand population if no one attended religious services
compared with the status quo?'' This scenario does not require shifting
those who never attend; here, results inform practical policies
targeting regular attendees who might stop.

Although the set of causal contrasts analysts might consider is
unbounded, those we have selected here specifically address scientific
and policy interests.

Consider that our approach does not focus on testing predefined
hypotheses; instead, we aim to compute causal effects with high accuracy
by combining appropriate time-series data and robust methods for causal
inference \citep{hernan2024stating}.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected by the New Zealand Attitudes and Values Study
(NZAVS), an annual longitudinal national probability panel study of
social attitudes, personality, ideology, and health outcomes in New
Zealand. Chris G. Sibley started the New Zealand Attitudes and Values
Study in 2009, which has grown to include a community of over fifty
researchers. Since its inception, The New Zealand Attitudes and Values
Study has accumulated questionnaire responses from 72,910 New Zealand
residents. The study operates independently of political or corporate
funding and is based in a university setting. Data summaries for our
study sample are found in \textbf{Appendices B-D}. For more details
about the New Zealand Attitudes and Values Study see:
\href{https://doi.org/10.17605/OSF.IO/75SNB}{OSF.IO/75SNB}.

\subsubsection{Treatment Indicator}\label{treatment-indicator}

Religious service attendance is assessed in the New Zealand Attitudes
and Values Study with the following questions:

\begin{itemize}
\tightlist
\item
  \emph{Do you identify with a religion and/or spiritual group? If
  yes\ldots How many times did you attend a church or place of worship
  during the last month?}
\end{itemize}

We rounded responses to the nearest whole number. Because there were few
responses greater than eight, we coded all above eight as eight (see
\emph{Appendix B}: we label this variable
\texttt{religion\_church\_round}). Note that contrasts with responses
greater than four were not intervened upon in the regular church service
condition; our decision was to ease the computational burden during
estimation.

\subsubsection{Measures of Prosociality}\label{measures-of-prosociality}

\textbf{Study 1: Self-reported charity} The New Zealand Attitudes and
Values Study includes two self-reported measures of pro-sociality:

\begin{itemize}
\item
  Volunteering: \emph{``Please estimate how many hours you spent doing
  each of the following things last week\ldots Volunteer/charitable
  work''}
\item
  Annual charitable financial donations: \emph{``How much money have you
  donated to charity in the last year?''}
\end{itemize}

\textbf{Study 2: Help received from others in the last week: \emph{time}
}

Participants were asked:

\emph{``Please estimate how much help you have received from the
following sources in the last week.''}

\begin{itemize}
\tightlist
\item
  \emph{Family\ldots TIME (hours)}
\item
  \emph{Friends\ldots TIME (hours)}
\item
  \emph{Community\ldots TIME (hours)}
\end{itemize}

Owing to the high variability of responses, we transformed responses
into binary indicators: \emph{0 = none/ 1 = any}.

\textbf{Study 3: Help received from others in the last week:
\emph{money} }

Similarly, participants were asked:

\emph{``Please estimate how much help you have received from the
following sources in the last week.''}

\begin{itemize}
\tightlist
\item
  \emph{Family\ldots MONEY (dollars)}
\item
  \emph{Friends\ldots MONEY (dollars)}
\item
  \emph{Community\ldots MONEY (dollars)}
\end{itemize}

These measures were also highly variable. Hence, we converted responses
to binary indicators: \emph{0 = none/ 1 = any}.

Studies 2 and 3 aim to minimise self-presentation bias by using external
measures of prosocial outcomes. We assume that if religious institutions
foster prosociality, the initiation of regular attendance --controlling
for past religious service, past measures of the prosocial outcomes, and
rich array of demographic, personality, and health measures recorded at
baseline -- will increase exposure to prosocial behaviours. These
self-reported measures of dependency on others are robust to
self-presentation biases that might associate religious service
attendance with indicators of prosociality in the absence of causation.

We provide comprehensive details of all measures in \textbf{Appendix A}.

\subsubsection{Causal Interventions}\label{causal-interventions}

We define three targeted causal contrasts (\emph{causal estimands}) as
interventions on prespecified modified treatment policies
\citep{haneuse2013estimation, diaz2021nonparametric, diaz2023lmtp}. Let
\(A_t\) denote the treatment, the monthly frequency of religious
service. There are three time points, \(t\in{0,1,2}\), where \(t=0\)
denotes the baseline wave, \(t=1\), the treatment wave, and \(t=2\) the
end of study. \(\mathbf{d}(\cdot)\) denotes a modified treatment policy
\(f_\mathbf{d}\). When a treatment is fixed to a level defined by the
treatment, perhaps contrary to the observed treatment, we use the lower
case symbol \(a_1\). In this study the functions defined by
\(f_\mathbf{d}\) are inteventions that fix \(A_1\) to \(a_1\).

We define three targeted causal contrasts (\emph{causal estimands})
using modified treatment policies as outlined in
\citep{haneuse2013estimation, diaz2021nonparametric, diaz2023lmtp}. Let
\(A_t\) represent the treatment variable, the monthly frequency of
religious service. This study has three distinct measurement intervals,
\(t \in \{0, 1, 2\}\), where \(t=0\) is the baseline wave, \(t=1\) is
the treatment wave, and \(t=2\) marks the end of the study. The notation
\(\mathbf{d}(\cdot)\) denotes to a modified treatment policy
\(f_\mathbf{d}\). When the policy prescribes a treatment level, perhaps
contrary to the observed treatment level, we denote this fixed level by
the lowercase symbol \(a_1\). In this study, the functions defined by
\(f_\mathbf{d}\) are interventions that set \(A_1\) to \(a_1\).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Regular Religious Service Treatment}: Administer regular
  religious service attendance to everyone in the adult population. If
  an individual's religious service attendance is below four times per
  month, shift to four; otherwise, maintain their current attendance:
\end{enumerate}

\[
\mathbf{d}^\lambda (a_1) = \begin{cases} 4 & \text{if } a_1 < 4 \\ 
a_1 & \text{otherwise} \end{cases}
\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Zero Religious Service Treatment}: Ensure no religious service
  attendance for everyone in the adult population of New Zealand. If an
  individual's religious service attendance is greater than zero, shift
  to zero; otherwise, make no change:
\end{enumerate}

\[
\mathbf{d}^\phi (a_1) = \begin{cases} 0 & \text{if } a_1 > 0 \\ 
a_1 & \text{otherwise} \end{cases}
\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Status Quo -- No Treatment}: Apply no treatment. Each expected
  mean outcome is calculated using the natural (observed) value of
  religious service attendance for each individual.
\end{enumerate}

\[
\mathbf{d}(a_1) = a_1
\]

\subsubsection{Causal Contrasts}\label{causal-contrasts}

From these policies, we computed the following causal contrasts.

\textbf{Target Contrast A: `Regular vs.~Zero'}: How do the prosocial
effects of a society with regular religious service attendance differ
from those of a society with zero religious service attendance?

\[ \text{Regular Religious Service vs. Zero Religious Service} = E[Y(\mathbf{d}^\lambda) - Y(\mathbf{d}^\phi)] \]

This contrast simulates a scientifically interesting hypothetical
experiment where we could randomise individuals to either regular
religious service or none, assessing the differences in prosociality
outcomes measured one year after the intervention.

\textbf{Target Contrast B: `Regular vs.~Status Quo'}: How does a society
with regular religious service attendance compare to its status quo?

\[ \text{Regular Religious Service vs. No Treatment} = E[Y(\mathbf{d}^\lambda) - Y(\mathbf{d})] \]

This contrast reflects a policy-relevant hypothetical experiment
examining the effect of transitioning people to regular religious
service, assessing whether this intervention reliably alters societal
prosociality compared to the current state.

\textbf{Target Contrast C: `Zero vs.~Status Quo'}: What are the social
consequences for society of zero religious service attendance compared
to its status quo?

\[ \text{Zero Religious Service vs. No Treatment} = E[Y(\mathbf{d}^\phi) - Y(\mathbf{d})] \]

This scenario investigates the policy implications of eliminating
religious services entirely, questioning whether such a shift would
meaningfully affect the prosocial outcomes we measure.

\subsubsection{Identification
Assumptions}\label{identification-assumptions}

To consistently estimate causal effects, we must satisfy three
assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal consistency:} potential outcomes must correspond with
  observed outcomes under the treatments in the data. Essentially, we
  assume potential outcomes do not depend on how the treatment was
  administered, conditional on measured covariates
  \citep{vanderweele2009, vanderweele2013}.
\item
  \textbf{Exchangeability} given observed covariates, we assume
  treatment assignment is independent of the potential outcomes to be
  contrasted. In other words, there is ``no unmeasured confounding''
  \citep{hernan2024WHATIF, chatton2020}.
\item
  \textbf{Positivity:} for unbiased estimation, every subject must have
  a non-zero chance of receiving the treatment, regardless of their
  covariate values \citet{westreich2010}. We evaluate this assumption in
  each study by examining changes in religious service attendance from
  baseline (NZAVS time 10) to the treatment wave (NZAVS time 11). For
  further discussion of these assumptions in the context of NZAVS
  studies, see \citet{bulbulia2023a}.
\end{enumerate}

\subsubsection{Target Population}\label{target-population}

The target population for this study comprises New Zealand residents as
represented in the baseline wave of the New Zealand Attitudes and Values
Study (NZAVS) during the years 2018-2019. The NZAVS is a national
probability study designed to reflect the broader New Zealand population
accurately. Despite its comprehensive scope, the NZAVS does have some
limitations in its demographic representation. Notably, it tends to
under-sample males and individuals of Asian descent while over-sampling
females and Māori (the indigenous peoples of New Zealand). To address
these disparities and enhance the accuracy of our findings, we apply New
Zealand Census survey weights to the sample data. These weights adjust
for variations in age, gender, and ethnicity to better approximate the
national demographic composition. Detailed methodologies related to the
application of these weights are discussed in \citet{sibley2021}.

\subsubsection{Eligibility Criteria}\label{eligibility-criteria}

To be included in the analysis of this study, participants needed to
meet the following eligibility criteria:

\begin{itemize}
\tightlist
\item
  Enrolled in the 2018 wave of the New Zealand Attitudes and Values
  Study (NZAVS time 10).
\item
  Complete data on religious service attendance at baseline (NZAVS time
  10), with no missing information in this area.
\item
  Missing covariate data at baseline were permitted and subjected to
  imputation methods to ensure comprehensive analysis.
\item
  Participants who were lost to follow-up or did not respond at the
  study's conclusion were still included in the initial sample set.
\end{itemize}

In total, 33,198 individuals fulfilled these criteria and were included
in the study.

\subsubsection{Causal Identification}\label{causal-identification}

\begin{table}

\caption{\label{tbl-02}This table presents three Single World
Intervention Graphs (SWIGs), one for each of the treatment conditions we
compare. Note that we obtain strong confounding control by including
baseline measures for both the treatments and outcomes, see
\citet{vanderweele2020}, \citet{bulbulia2024PRACTICAL}.}

\centering{

\lmtptablethree

}

\end{table}%

Table~\ref{tbl-02} presents three Single World Intervention Graphs
(SWIGs) that outline our identification strategy
\citep{robins2010alternative, richardson2013swigsprimer, shpitser2022multivariate, richardson2023nested, richardson2023potential, shpitser2016causal}.
Our approach consistently applies the same identification strategy
across all functions estimated in this study. Note that the natural
value of the treatment \(A\) is obtained from its observed instances and
baseline historical data. This method ensures that our analysis
accurately captures the causal effects of flexible treatment regimes
\citep{diaz2012population, young2014identification, diaz2021nonparametric}.

\subsubsection{Confounding Control}\label{confounding-control}

To manage confounding in our analysis, we implemented
\citet{vanderweele2019}'s \emph{modified disjunctive cause criterion} by
following these steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Identified all common causes} of both the treatment and
  outcomes to ensure a comprehensive approach to confounding control.
\item
  \textbf{Excluded instrumental variables} that affect the exposure but
  not the outcome. Instrumental variables do not contribute to
  controlling confounding and can reduce the efficiency of the
  estimates.
\item
  \textbf{Included proxies for unmeasured confounders} affecting both
  exposure and outcome. According to the principles of d-separation,
  using proxies allows us to indirectly control for their associated
  unmeasured confounders.
\item
  \textbf{Controlled for baseline exposure} and \textbf{baseline
  outcome}. Both are used as proxies for unmeasured common causes,
  enhancing the robustness of our causal estimates.
\end{enumerate}

\hyperref[appendix-demographics]{Appendix B} details the covariates we
included for confounding control. These methods adhere to the guidelines
provided in \citep{bulbulia2024PRACTICAL} and were pre-specified in our
study protocol \url{https://osf.io/ce4t9/}.

\subsubsection{Missing Data}\label{missing-data}

To mitigate the influence of missing data on our study results and
enhance the robustness of our analyses, we implemented the following
strategies:

\textbf{Baseline missingness}: we employed the \texttt{ppm} algorithm
from the \texttt{mice} package in R \citep{vanbuuren2018} to impute
missing baseline data. This method allowed us to reconstruct incomplete
datasets by estimating a plausible value for missing observation.
Because we could only pass one data set to the \texttt{lmtp}, we
employed a single imputation. About 2\% of covariate values were missing
at baseline. Eligibility for the study required fully observed baseline
treatment measures as well as treatment wave treatment measures.

\textbf{Outcome missingness}: to address confounding and selection bias
arising from missing responses and panel attrition, we applied
non-parametrically estimated censoring weights using the \texttt{lmtp}
package in R \citep{williams2021}.

\subsubsection{Statistical Estimator}\label{statistical-estimator}

We perform statistical estimation using non-parametric Targeted
Learning, specifically a Targeted Minimum Loss-based Estimation (TMLE)
estimator. TMLE is a robust method that combines machine learning
techniques with traditional statistical models to estimate causal
effects while providing valid statistical uncertainty measures for these
estimates \citep{van2014targeted, van2012targeted}.

TMLE operates through a two-step process that involves modelling both
the outcome and treatment (exposure). Initially, TMLE employs machine
learning algorithms to flexibly model the relationship between
treatments, covariates, and outcomes. This flexibility allows TMLE to
account for complex, high-dimensional covariate spaces
\emph{efficiently} without imposing restrictive model assumptions
\citep{van2014discussion, vanderlaan2011, vanderlaan2018}. The outcome
of this step is a set of initial estimates for these relationships.

The second step of TMLE involves ``targeting'' these initial estimates
by incorporating information about the observed data distribution to
improve the accuracy of the causal effect estimate. TMLE achieves this
precision through an iterative updating process, which adjusts the
initial estimates towards the true causal effect. This updating process
is guided by the efficient influence function, ensuring that the final
TMLE estimate is as close as possible, given the measures and data, to
the true causal effect while still being robust to
model-misspecification in either the outcome or the treatment model.

Again, a central feature of TMLE is its double-robustness property. If
either the treatment model or the outcome model is correctly specified,
the TMLE estimator will consistently estimate the causal effect.
Additionally, TMLE uses cross-validation to avoid over-fitting and
ensure that the estimator performs well in finite samples. Each step
contributes to a robust methodology for examining an intervention's
\emph{causal} effects on outcomes. The marriage of TMLE and machine
learning technologies reduces the dependence on restrictive modelling
assumptions and introduces an additional layer of robustness. For
further details of the specific targeted learning strategy we favour,
see \citep{hoffman2022, hoffman2023, díaz2021}. We performed estimation
using the \texttt{lmtp} package \citep{williams2021}. We used the
\texttt{superlearner} library for non-parametric estimation with the
predefined libraries \texttt{SL.ranger}, \texttt{SL.glmnet}, and
\texttt{SL.xgboost} \citep{polley2023, xgboost2023, Ranger2017}. We
created graphs, tables and output reports using the \texttt{margot}
package \citep{margot2024}. All analysis methods follow pre-stated
protocols in \citet{bulbulia2024PRACTICAL}.

\subsubsection{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess the sensitivity of results to unmeasured confounding, we
report VanderWeele and Ding's ``E-value'' in all analyses
\citep{vanderweele2017}. The E-value quantifies the minimum strength of
association (on the risk ratio scale) that an unmeasured confounder
would need to have with both the exposure and the outcome (after
considering the measured covariates) to explain away the observed
exposure-outcome association \citep{vanderweele2020, linden2020EVALUE}.
To evaluate the strength of evidence, we use the bound of the E-value
95\% confidence interval closest to 1.

\subsubsection{Scope of Interventions}\label{scope-of-interventions}

To illustrate the magnitude of the shift interventions we contrast, we
provide histograms in Fig~\ref{fig-hist}, which display the distribution
of treatment levels during the treatment wave. Fig~\ref{fig-hist}
\emph{A}: The intervention for regular religious service, represented in
these histograms, affects a larger portion of the sample compared to the
zero religious service intervention. Fig~\ref{fig-hist} \emph{B}:
presents the intervention for zero religious service. It affects a
smaller portion of the sample compared to the regular religious service
intervention. The comparative analysis of the `Regular' versus `Zero'
interventions addresses the scientifically intriguing question: what is
the effect difference in a scenario where religious service is
universally attended versus completely absent? The intervention that
increases attendance to regular service levels from the status quo
allows us to consider the potential costs and benefits of widespread
religious practice across society. The intervention that eliminates
religious service allows us to consider the potential costs and benefits
of the widespread loss of religious practice across society.

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-hist-1.pdf}

}

\caption{\label{fig-hist}This figure shows a histogram of responses to
religious service frequency in the baseline + 1 wave. Responses above
eight were assigned to eight, and values were rounded to the nearest
whole number. The red dashed line shows the population average. (A)
Responses in the gold bars are shifted to four on the Regular Religious
Service intervention. All those responses in grey (four and above)
remain unchanged. (B) On the zero intervention, responses in the blue
bars are shifted.}

\end{figure}%

\newpage{}

\subsubsection{Evidence for Change in the Treatment
Variable}\label{evidence-for-change-in-the-treatment-variable}

Table~\ref{tbl-transition} clarifies the change in the treatment
variable from the baseline wave to the baseline + 1 wave across the
sample. Assessing change in a variable is essential for evaluating the
positivity assumption and recovering evidence for the incident exposure
effect of the treatment variable
\citep{vanderweele2020, danaei2012, hernan2024WHATIF}. We find that
state 4 (weekly attendance) and state 0 present the highest overall.
However, we also find that movement between these states reveals they
are not deterministic. States 1, 2, 3, and 5 present relatively frequent
jumps in and out of these states, suggesting lower stability or
measurement error.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1196}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}
  >{\centering\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0978}}@{}}

\caption{\label{tbl-transition}This transition matrix captures stability
and change in religious service between the baseline and treatment wave.
Each cell in the matrix represents the count of individuals
transitioning from one state to another. The rows correspond to the
state at baseline (From), and the columns correspond to the state at the
treatment wave (To). \textbf{Diagonal entries} (in \textbf{bold})
signify the number of individuals who remained in their initial state
across both waves. \textbf{Off-diagonal entries} signify the transitions
of individuals from their baseline state to a different state in the
treatment wave. A higher number on the diagonal relative to the
off-diagonal entries in the same row indicates greater stability in a
state. Conversely, higher off-diagonal numbers suggest more frequent
shifts in the sample from the baseline state to other states.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 0
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 8
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 0 & \textbf{26762} & 405 & 174 & 71 & 126 & 26 & 13 & 8 & 68 \\
State 1 & 647 & \textbf{235} & 85 & 44 & 46 & 5 & 2 & 3 & 10 \\
State 2 & 236 & 105 & \textbf{188} & 104 & 96 & 12 & 13 & 2 & 21 \\
State 3 & 112 & 54 & 110 & \textbf{164} & 173 & 18 & 8 & 4 & 15 \\
State 4 & 150 & 71 & 127 & 205 & \textbf{881} & 124 & 64 & 16 & 91 \\
State 5 & 24 & 7 & 17 & 17 & 145 & \textbf{61} & 25 & 7 & 33 \\
State 6 & 14 & 5 & 13 & 17 & 84 & 22 & \textbf{29} & 5 & 37 \\
State 7 & 9 & 0 & 6 & 3 & 16 & 6 & 9 & \textbf{6} & 19 \\
State 8 & 74 & 14 & 17 & 14 & 105 & 34 & 42 & 17 & \textbf{351} \\

\end{longtable}

\newpage{}

\subsection{Results}\label{results}

\subsubsection{Study 1: Causal Effects of Regular Church Attendance on
Self-Reported Volunteering and Self-Reported Volunteering and
Donations}\label{study-1-causal-effects-of-regular-church-attendance-on-self-reported-volunteering-and-self-reported-volunteering-and-donations}

\paragraph{Regular Religious Service vs.~Zero Treatment Contrast for
Donations and
Volunteering}\label{regular-religious-service-vs.-zero-treatment-contrast-for-donations-and-volunteering}

Results for the treatment contrasts between Regular Religious Service
and Zero Religious Service, focusing on self-reported volunteering and
charitable donations, are displayed in Fig~\ref{fig-1_1} \emph{A} and
Table~\ref{tbl-1_1}. These results are measured on the difference scale.

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-1_1}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~universal loss of weekly religious service on reported
charitable behaviours at the end of the study. Contrasts are expressed
in standard deviation units.}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.132 & 0.102 & 0.161 & 1.507 & 1.426 \\
hours volunteer & 0.123 & 0.090 & 0.156 & 1.482 & 1.389 \\

\end{longtable}

For `donations', the effect estimate is 0.132 {[}0.102, 0.161{]}. The
E-value for this estimate is 1.507, with a lower bound of 1.426. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1.426 to
negate the observed effect. Weaker associations would not overturn it.
We infer \textbf{evidence for causality}. On the data scale, this
intervention represents a difference of NZD 656.58 per adult per year in
charitable giving.

The effect estimate for `hours volunteer' is 0.123 {[}0.09, 0.156{]}.
The E-value for this estimate is 1.482, with a lower bound of 1.389. We
infer \textbf{evidence for causality}. On the data scale, this
intervention represents a difference of NZD 30.21 minutes per adult per
week in charitable giving.

\paragraph{Regular Religious Service vs.~Status Quo Treatment Contrast
for Donations and
Volunteering}\label{regular-religious-service-vs.-status-quo-treatment-contrast-for-donations-and-volunteering}

Fig~\ref{fig-1_1} \emph{B} and Table~\ref{tbl-1_2} present results for
the treatment contrasts between Regular Religious Service and Status
Quo, focusing on self-reported volunteering and charitable donations.
These results are measured on the difference scale.

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-1_2}This table reports results of model estimates
for the causal effects of a universal gain of weekly religious service
vs.~the status quo on reported charitable behaviours at the end of the
study. Contrasts are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & 0.121 & 0.102 & 0.140 & 1.477 & 1.422 \\
hours volunteer & 0.095 & 0.066 & 0.123 & 1.404 & 1.317 \\

\end{longtable}

For `donations', the effect estimate is 0.121 {[}0.102, 0.14{]}. The
E-value for this estimate is 1.477, with a lower bound of 1.422. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1.422 to
negate the observed effect. Weaker confounding would not overturn it. We
infer \textbf{evidence for causality}. On the data scale, this
intervention represents a difference of NZD 601.87 per adult per year in
charitable giving.

For `hours volunteer', the effect estimate is 0.095 {[}0.066, 0.123{]}.
The E-value for this estimate is 1.404, with a lower bound of 1.317. At
this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.317 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}. On the data
scale, this intervention represents a difference of 23.33 minutes per
adult per week in charitable giving.

\paragraph{Zero Religious Service vs.~The Status Quo Treatment Contrast
for Donations and
Volunteering}\label{zero-religious-service-vs.-the-status-quo-treatment-contrast-for-donations-and-volunteering}

Fig~\ref{fig-1_1} \emph{C} and Table~\ref{tbl-1_3} present results for
the treatment contrasts between Zero Religious Service and Status Quo,
focusing on self-reported volunteering and charitable donations. These
results are measured on the difference scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2424}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1061}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1212}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1818}}@{}}

\caption{\label{tbl-1_3}This table reports the results of model
estimates for the causal effects of a universal loss of weekly religious
service vs.~the status quo on reported charitable behaviours at the end
of the study. Contrasts are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
donations & -0.011 & -0.029 & 0.008 & 1.111 & 1.000 \\
hours volunteer & -0.028 & -0.042 & -0.014 & 1.189 & 1.128 \\

\end{longtable}

For `donations', the effect estimate is -0.011 {[}-0.029, 0.008{]}. The
E-value for this estimate is 1.111, with a lower bound of 1. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1 to negate
the observed effect. Weaker confounding would not overturn it. We infer
that \textbf{the evidence for causality is not reliable}. On the data
scale, this intervention represents a difference of NZD -54.72 per adult
per year in charitable giving, but again, the effect is not reliable.

The effect estimate for `hours volunteer' is -0.028 {[}-0.042,
-0.014{]}. The E-value for this estimate is 1.189, with a lower bound of
1.128. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.128 to negate the observed effect. Again, weaker confounding would not
overturn it. We infer \textbf{evidence for causality}. On the data
scale, this intervention represents a difference of -6.88 in
volunteering minutes.

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-1_1-1.pdf}

}

\caption{\label{fig-1_1}This figure graphs the results of model
estimates for the causal effects of the three causal contrasts of
interest on reported charitable behaviours at the study's end. The
causal contrasts are: (A) Regular vs.~Zero Religious Service (B) Regular
Religious Service vs.~Status Quo; (C) Zero Religious Service vs.~Status
Quo. Contrasts are expressed in standard deviation units.}

\end{figure}%

\newpage{}

\subsubsection{Study 2: Causal Effects of Regular Church Attendance on
Support Received From Others --
Time}\label{study-2-causal-effects-of-regular-church-attendance-on-support-received-from-others-time}

\paragraph{Regular vs.~Zero Causal Treatment Contrast for Time Received
From
Others}\label{regular-vs.-zero-causal-treatment-contrast-for-time-received-from-others}

Fig~\ref{fig-study2} \emph{A} and Table~\ref{tbl-study2A} present
results for the treatment contrasts between Regular Religious Service
and Zero, focusing on voluntary help received from others during the
past week (yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}

\caption{\label{tbl-study2A}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~a universal loss of weekly religious service on voluntary
help received from others during the past week (yes/no) at the end of
the study. Contrasts are expressed on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 0.950 & 0.901 & 1.003 & 1.288 & 1.000 \\
friends give time & 1.187 & 1.108 & 1.271 & 1.658 & 1.454 \\
community gives time & 1.378 & 1.231 & 1.541 & 2.100 & 1.764 \\

\end{longtable}

For `community gives time', the effect estimate is 1.378 {[}1.231,
1.541{]}. The E-value for this estimate is 2.1, with a lower bound of
1.764. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.764 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends give time', the effect estimate is 1.187 {[}1.108,
1.271{]}. The E-value for this estimate is 1.658, with a lower bound of
1.454. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.454 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives time', the effect estimate is 0.95 {[}0.901, 1.003{]}.
The E-value for this estimate is 1.288, with a lower bound of 1. At this
lower bound, unmeasured confounders would need a minimum association
strength with both the intervention sequence and outcome of 1 to negate
the observed effect. Weaker confounding would not overturn it. We infer
\textbf{that evidence for causality is not reliable}.

\paragraph{Regular Religious Service vs.~Status Quo Treatment Contrast
for Time Received From
Others}\label{regular-religious-service-vs.-status-quo-treatment-contrast-for-time-received-from-others}

Fig~\ref{fig-study2}\emph{B} and Table~\ref{tbl-2-2} present results for
the treatment contrasts between Regular Religious Service and Status
Quo, focusing on voluntary help received from others during the past
week (yes/no). These results are measured on the risk ratio scale

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}

\caption{\label{tbl-2-2}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~the status quo on voluntary help received from others during
the past week (yes/no) at the end of the study. Contrasts are expressed
on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 0.958 & 0.913 & 1.006 & 1.258 & 1.000 \\
friends give time & 1.128 & 1.061 & 1.199 & 1.508 & 1.315 \\
community gives time & 1.289 & 1.174 & 1.415 & 1.899 & 1.626 \\

\end{longtable}

For `community gives time', the effect estimate is 1.289 {[}1.174,
1.415{]}. The E-value for this estimate is 1.899, with a lower bound of
1.626. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.626 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends gives time', the effect estimate is 1.128 {[}1.061,
1.199{]}. The E-value for this estimate is 1.508, with a lower bound of
1.315. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.315 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives time', the effect estimate is 0.958 {[}0.913,
1.006{]}. The E-value for this estimate is 1.258, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

\paragraph{Zero Religious Service vs.~Status Quo Treatment Contrast for
Time Received From
Others}\label{zero-religious-service-vs.-status-quo-treatment-contrast-for-time-received-from-others}

Fig~\ref{fig-study2} \emph{C} and Table~\ref{tbl-2_3} present results
for the treatment contrasts between Zero Religious Service and Status
Quo, focusing on voluntary help received from others during the past
week (yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2286}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1143}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1714}}@{}}

\caption{\label{tbl-2_3}This table reports results of model estimates
for the causal effects of a universal loss of weekly religious service
vs.~the status quo on voluntary help received from others during the
past week (yes/no) at the end of the study. Contrasts are expressed on
the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives time & 1.008 & 0.991 & 1.026 & 1.098 & 1.000 \\
friends give time & 0.950 & 0.928 & 0.973 & 1.288 & 1.197 \\
community gives time & 0.936 & 0.889 & 0.985 & 1.339 & 1.140 \\

\end{longtable}

For `family gives time', the effect estimate is 1.008 {[}0.991,
1.026{]}. The E-value for this estimate is 1.098, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

For `friends gives time', the effect estimate is 0.95 {[}0.928,
0.973{]}. The E-value for this estimate is 1.288, with a lower bound of
1.197. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.197 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `community gives time', the effect estimate is 0.936 {[}0.889,
0.985{]}. The E-value for this estimate is 1.339, with a lower bound of
1.14. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.14 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-study2-1.pdf}

}

\caption{\label{fig-study2}This figure reports the results of model
estimates for the three causal contrasts of interest on help received
from others during the past week (yes/no). The causal contrasts are: (A)
Regular vs.~Zero Religious Service (B) Regular Religious Service
vs.~Status Quo; (C) Zero Religious Service vs.~Status Quo. Contrasts are
expressed on the risk ratio scale.}

\end{figure}%

\newpage{}

\subsubsection{Study 3: Causal Effects of Regular Church Attendance on
Support Received From Others --
Money}\label{study-3-causal-effects-of-regular-church-attendance-on-support-received-from-others-money}

\paragraph{Regular vs.~Zero Causal Contrast on Money Received From
Others}\label{regular-vs.-zero-causal-contrast-on-money-received-from-others}

Fig~\ref{fig-study_3} \emph{A} and Table~\ref{tbl-3_1} present results
for the treatment contrasts between Regular Religious Service and Zero,
focusing on money received from others during the past week (yes/no).
These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_1}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~universal loss of weekly religious service on financial help
received from others during the past week (yes/no) at the end of the
study. Contrasts are expressed on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.137 & 1.028 & 1.258 & 1.532 & 1.198 \\
friends give money & 1.137 & 0.964 & 1.342 & 1.532 & 1.000 \\
community gives money & 1.376 & 1.112 & 1.703 & 2.095 & 1.465 \\

\end{longtable}

For `community gives money', the effect estimate is 1.376 {[}1.112,
1.703{]}. The E-value for this estimate is 2.095, with a lower bound of
1.465. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.465 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives money', the effect estimate is 1.137 {[}1.028,
1.258{]}. The E-value for this estimate is 1.532, with a lower bound of
1.198. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.198 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends give money', the effect estimate is 1.137 {[}0.964,
1.342{]}. The E-value for this estimate is 1.532, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

\paragraph{Regular vs.~Status Quo Causal Contrast on Money Received From
Others}\label{regular-vs.-status-quo-causal-contrast-on-money-received-from-others}

Fig~\ref{fig-study_3} \emph{B} and Table~\ref{tbl-3_2} present results
for the treatment contrasts between Regular Religious Service and Status
Quo, focusing on money received from others during the past week
(yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_2}This table reports the results of model
estimates for the causal effects of a universal gain of weekly religious
service vs.~the status quo on financial help received from others during
the past week (yes/no) at the end of the study. Contrasts are expressed
on the risk ratio scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 1.130 & 1.037 & 1.232 & 1.513 & 1.233 \\
friends give money & 1.041 & 0.951 & 1.139 & 1.248 & 1.000 \\
community gives money & 1.254 & 1.098 & 1.432 & 1.818 & 1.426 \\

\end{longtable}

For `community gives money', the effect estimate is 1.254 {[}1.098,
1.432{]}. The E-value for this estimate is 1.818, with a lower bound of
1.426. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.426 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `family gives money', the effect estimate is 1.13 {[}1.037,
1.232{]}. The E-value for this estimate is 1.513, with a lower bound of
1.233. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.233 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{evidence for causality}.

For `friends give money', the effect estimate is 1.041 {[}0.951,
1.139{]}. The E-value for this estimate is 1.248, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker confounding would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

\paragraph{Zero vs.~Status Quo Causal Contrast on Money Received From
Others}\label{zero-vs.-status-quo-causal-contrast-on-money-received-from-others}

Fig~\ref{fig-study_3} \emph{C} and Table~\ref{tbl-3_3} present results
for the treatment contrasts between Zero Religious Service and Status
Quo, focusing on money received from others during the past week
(yes/no). These results are measured on the risk ratio scale.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3099}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0845}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-3_3}Table reports results of model estimates for the
causal effects of a universal loss of weekly religious service vs.~the
status quo on financial help received from others during the past week
(yes/no) at the end of study. Contrasts are expressed on the risk ratio
scale.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}/E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
family gives money & 0.993 & 0.953 & 1.035 & 1.091 & 1 \\
friends gives money & 0.915 & 0.809 & 1.036 & 1.412 & 1 \\
community gives money & 0.911 & 0.796 & 1.042 & 1.425 & 1 \\

\end{longtable}

For `family gives money', the effect estimate on the risk ratio scale is
0.993 {[}0.953, 1.035{]}. The E-value for this estimate is 1.091, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{that evidence for causality is not
reliable}.

For `friends give money', the effect estimate on the risk ratio scale is
0.915 {[}0.809, 1.036{]}. The E-value for this estimate is 1.412, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker confounding would not
overturn it. We infer \textbf{that evidence for causality is not
reliable}.

For `community gives money', the effect estimate on the risk ratio scale
is 0.911 {[}0.796, 1.042{]}. The E-value for this estimate is 1.425,
with a lower bound of 1. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1 to negate the observed effect. Weaker
confounding would not overturn it. We infer \textbf{that evidence for
causality is not reliable}.

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-study_3-1.pdf}

}

\caption{\label{fig-study_3}This figure reports the results of model
estimates for the three causal contrasts of interest on help received
from others during the past week (yes/no). The causal contrasts are: (A)
Regular vs.~Zero Religious Service (B) Regular Religious Service
vs.~Status Quo; (C) Zero Religious Service vs.~Status Quo. Contrasts are
expressed on the risk ratio scale.}

\end{figure}%

\newpage{}

\subsubsection{Additional Study: Comparison of Causal Inference Results
with Cross-Sectional
Regressions}\label{additional-study-comparison-of-causal-inference-results-with-cross-sectional-regressions}

To better evaluate the contributions of our methodology to current
practice, we conducted a series of cross-sectional analyses using the
baseline wave data and quantified the statistical associations between
religious service attendance and our focal prosocial outcomes. We
included all regression covariates from the causal models (including
sample weights) for each analysis, obviously omitting the outcome
measured at baseline, i.e.~the response variable.

\textbf{Cross-sectional volunteering result}: the change in expected
hours of volunteer work for a one-unit increase in religious service
attendance is b = 0.31; (95\% CI 0.28, 0.34). Multiplying this by 4.2
gives a monthly estimate of 77.95 minutes. This result is 2.58 percent
greater than the effect estimated from the `regular vs.~zero' causal
contrast, indicating an overstatement in the regression model.

\textbf{Cross-sectional charitable donations result}: the coefficient
for religious service on annual charitable donations suggests a change
in expected donation amount per unit increase in attendance is b = 451;
(95\% CI 408, 494). When adjusted to a monthly rate by multiplying by
4.2, this value equals NZ Dollars 1894.45. It is 2.89 percent greater
than our causal contrast estimate, again indicating an overstatement by
the regression.

For Studies 2 and 3, which focus on community help received, we adjusted
our analysis for the non-collapsibility of odds ratios by assuming a
Poisson distribution for the outcome variables
\citep{huitfeldt2019collapsibility, vanderweele2020}:

\textbf{Cross-sectional community assistance received result: Time}: the
exponentiated change in expectation for a one-unit change in religious
service attendance is b = 1.17; (95\% CI 1.14, 1.19) approximate risk
rate ratio. The monthly risk ratio derived by multiplying this
coefficient by 4.2 is 1.921. This is 1.39 percent greater than the
`regular vs.~zero' causal estimate, pointing to an overestimation in the
regression.

\textbf{Cross-sectional community assistance received result:
\textless oney}: similarly, the exponentiated change for money received
yields an approximate risk ratio of b = 1.18; (95\% CI 1.08, 1.27). The
monthly risk ratio, after adjustment, is 1.996. This risk ratio is 1.45
percent greater than the causal estimate, again revealing the bias of
cross-sectional regressions.

\emph{These findings underscore that the results of cross-sectional
regressions, although suggestive, can considerably diverge from the
results obtained from the causal analysis of panel data.}

\newpage{}

\subsubsection{What is the ``Cash Value'' of Religious Service
Attendance for Charitable Donations in New
Zealand?}\label{what-is-the-cash-value-of-religious-service-attendance-for-charitable-donations-in-new-zealand}

We leveraged our findings to estimate the economic value of religious
service attendance by comparing expected donation amounts under
different scenarios--- `Regular Religious Service', `Zero Religious
Service', and the `Status Quo'.

\begin{itemize}
\tightlist
\item
  \textbf{Regular Religious Service}: an increase in religious service
  attendance correlates with an individual average donation rate of
  1638.98.
\item
  \textbf{Zero Religious Service}: a reduction in religious service
  attendance is associated with an average donation rate of 984.59.
\item
  \textbf{Status Quo}: the expected individual average donation rate is
  currently 1037.14.
\end{itemize}

With 3,989,000 adult residents in New Zealand in 2021,\footnote{\href{https://www.stats.govt.nz/information-releases/national-population-estimates-at-30-june-2021}{National
  Population Estimates at 30 June 2021}}.

\begin{itemize}
\tightlist
\item
  Multiplying adult population by the average donation sum gives a
  status quo national estimate for charitable giving of NZD
  4,137,151,460.
\item
  The net gain to charity from country-wide regular attendance at
  religious services, compared to the status quo, is NZD 2,400,739,760.
\item
  Conversely, the net cost to charity from a complete cessation of
  regular religious service attendance is NZD -209,621,950.
\end{itemize}

To provide context, consider these economic consequences against the New
Zealand national budget in year outcomes were measured (2021-2022):

\begin{itemize}
\tightlist
\item
  The gain from a nationwide adoption of regular religious service
  represents 0.041 of New Zealand's annual government budget 2021.
\item
  The loss from a nationwide discontinuation of all religious services
  constitutes 0.004 of the annual government budget.
\end{itemize}

A hypothetical scenario where the entire adult population of New Zealand
regularly attends religious services reveals a substantial amplification
of society-wide charitable support. However, even if New Zealand were to
witness a complete cessation of religious service attendance, the
landscape of charitable giving would likely remain largely unchanged
from its current state. That said, some charity is always preferable to
none. We do not diminish this giving, or its effects. Each charitable
act counts.

\subsection{Discussion}\label{discussion}

\subsubsection{Limitations}\label{limitations}

First, consider \textbf{unmeasured confounding}: although we use robust
methods for causal inference, our results are contingent upon the
adequacy of our identification strategy. We employ non-parametric causal
estimation, enhancing modelling efficiency, and our sensitivity analyses
describe the potential effects of unmeasured confounding. However, the
presence and influence of such confounders remain uncertain.

Second, \textbf{nonparametric estimation/machine learning remains
untested}: although the threat of model misspecification is greatly
diminished in non-parametric estimation, the theoretical properties of
non-parametric estimators for obtaining valid standard may affect
precision and accuracy in small samples \citep{van2014discussion}.
Against this concern, our relatively large sample size, 33,198 offers
some confidence. However, investigators should be mindful that
non-parametric estimation and machine learning are presently new and
untested areas in the psychological sciences. They should be used with
caution, particularly with small samples.

Third, consider the threat of \textbf{measurement error}: both direct
and correlated measurement errors can introduce biases, either by
implying effects where none exist or by attenuating true effects
\citep{vanderweele2012MEASUREMENT}. Although evaluating prosociality
using multiple measures helps to mitigate concerns about whether
religious service affects charitable donations and volunteering, unknown
measurement error combinations could still affect the precision of
inferences by overstating or understating true causal effects. The
outcomes and estimates we report here would be best approached as
approximations.

Fourth, we we do not examine \textbf{treatment effect heterogeneity}:
identifying which subgroups experience the strongest responses remains
an task for future research. Such investigations are crucial for making
informed policy decisions and tailoring advice relevant to those
subgroups of the population who might benefit most. Perhaps the most
obvious stratum of interest are those who already affiliate with a
religion at baseline.

Sixth, the \textbf{transportability of our findings remains unclear}:
the New Zealand population is our target population. We believe our
findings generalise to this population. The transportability of our
findings to other settings -- that is, the question of whether results
generalising beyond this target population -- remains an open question,
a matter for future investigations.

\subsubsection{Observations and
Recommendations}\label{observations-and-recommendations}

First, it is essential to understand that \textbf{different causal
questions yield different causal answers.} Our study obtains causal
effect estimates by contrasting specific interventions that increase and
decrease religious service attendance across the population balancing
confounders. On one side, the the social benefits of regular religious
attendance on prosociality are considerable. Widespread participation
could enhance charity and volunteering, a point that should shape
discussions among critics of religion. Conversely, the overall societal
impact of completely ceasing religious services is minimal. Should New
Zealand's society entirely forego regular religious attendance, we would
not anticipate significant deviations from the status quo after one
year. Although long-term effects were not investigated, this finding
might alleviate concerns among those wary of a secular shift. \textbf{We
recommend future research to distinguish between models of cultural
gains and losses} (as exemplified by \citet{vantongeren2020}). Moreover,
\textbf{researchers should clearly define, compute, and discuss
different causal contrasts according to targeted scientific and policy
goals.}

Second, we caution that traditional \textbf{measures of effect} such as
Cohen's D or \(R^2\) may give a misleading picture of a finding's
practical significance. Here, the standardized estimate for the contrast
between regular religious service and no service is 0.132 {[}0.102,
0.161{]}, which might be categorised as a `small' effect by experimental
conventions. Nonetheless, we observe that the difference in annual
charitable donations between the regular service condition and the
status quo is -- NZD 1638.98 versus NZD 1037.14. Not only is this effect
practically significant at the individual level, it amounts to over 4\%
of New Zealand's Annual Budget. \textbf{We recommend prioritising the
evaluation and communication of practical effect sizes over conventional
statistical measures.}

Third, our novel measures of prosociality---\textbf{assistance and
financial support received from one's community}--align with the
expectations of self-reported data on charitable donations and
volunteering. We detect marginal causal effects of religious service
attendance on these types of prosocial behavior compared to
non-attendance. Note that neither our measures of prosocial actions
(charity/volunteering) nor of community help received (time/money)
clarify the targets and sources of help. Nevertheless, theories of
religous prosociality are premised on within group-cooperative benefit
\citep{sosis2003cooperation, johnson2015, whitehouse2023}. This
consistency between self-reported giving and help received aligns with
public data in New Zealand;\footnote{\url{https://www.charities.govt.nz/view-data/}}
where religious institutional charity accounts for 40\% of the
charitable sector (refer to \citet{McLeod2020}, p.17, and also
\citet{brooks2004faith}; \citet{woodyard2014doing};
\citet{monsma2007religion}). Additionally, it has been suggested that
religious institutions are particularly efficient due to low
administrative costs and high volunteer engagement
\citep[26]{khanna1995charity, bekkers2011literature, McLeod2020}. We
note that the community signals of religious giving are consistent with
the theory that religion promotes altruism outside families and
friendships, and even among strangers \citep{mccullough2020kindness}.
\textbf{In contexts where investigators are concerned about presentation
bias in the self-reported donations and volunteering, consider measures
to capture community-received assistance.}

Fourth, our analysis shows that using standard cross-sectional
regressions on baseline data tends to considerably overstate the causal
effects compared to those estimated from principled applications of
methods to time-series data. It is important to note that associational
models might also understate true causal relationships, especially if
adjustments involve mediators \citep{westreich2013}. Despite their
effectiveness and relevance, however, causal inference methods are not
commonly practiced across many fields in the human sciences, where
traditional associational methods still dominate. Transitioning to
causal data science might seem daunting. Causation inherently involves
timing, with causes preceding effects, and quantifying causal effects
necessitates contrasting counterfactual states---hypothetical scenarios
that could have occurred under different conditions but did not.
Estimating average causal effects involves summaries of these
counterfactual contrasts, relying on a framework of explicit
assumptions, clear multi-stepped workflows, and, crucially, time-series
data. The need for researchers to develop new skills and the intensive
requirement for collecting time-series data have profound implications
for research design, funding, and the pace of scientific progress.
However, causal inference methods have become standard in epidemiology
and are rapidly gaining traction in economics and sociology. The
development of global panel studies suited for researching religion
\citet{johnson2022global}, reveal the potential of retooling (refer also
to \citet{major2023exploring}). \textbf{We strongly recommend broader
adoption of causal inferential methods to enhance the accuracy and
reliability of research findings in the the psychology of religion.}*

Fifth, this study is one of the first to combine robust causal methods
and national panel data to investigate the social consequences of
religion. It provides evidence that religious service attendance
causally affects charitable donations and volunteering. These findings
deepen our understanding of how much religious service affects these
activities in New Zealand and possibly in similar cultural settings. We
hope this research will serve as a template for similar studies
elsewhere. However, it goes without saying that much remains to be
discovered about the broader effects of religion on prosocial behavior,
even within New Zealand. Although quantifying the magnitudes of
charitable contributions clarifies how much religion affects prosocial
outcomes, it does not elucidate the underlying mechanisms or their
variability. A substantial amount of research has explored the
mechanisms through which religious participation influences individuals,
yet using data to clarify pathways of operation poses a considerable
conception and data challenges
\citep{robins1992, vanderweele2015, Diaz2023, diaz2021nonparametric}.
However, such challenges are theoretically surmountable using the causal
approach we have adopted and advocate for here. By carefully navigating
the uncertainties inherent in observational data and leveraging the
insights from comprehensive time-series analysis, we can achieve clearer
inferences about these mechanisms and their variations. \textbf{We
recommend a broader application of causal inferential methods across
more than three waves to elucidate the mediating mechanisms more
clearly.}

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study (NZAVS). Full copies of the NZAVS data files are held
by members of the NZAVS management team and research group. A
de-identified dataset containing only the variables analysed in this
manuscript is available upon request from the corresponding author, or
any member of the NZAVS advisory board for the purposes of replication
or checking of any published study using NZAVS data. The code for the
analysis can be found at:
\url{https://github.com/go-bayes/models/blob/main/scripts/24-bulbulia-church-prosocial.R}.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Planck Institute for the Science of Human History. The
funders had no role in preparing the manuscript or the decision to
publish.

\subsubsection{Author Statement}\label{author-statement}

JB conceived of the study and analytic approach. CS led NZAVS data
collection. All authors contributed to the manuscript.

\newpage{}

\subsection{Appendix A: Measures}\label{appendix-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth?'').

\paragraph{Born in New Zealand}\label{born-in-new-zealand}

\paragraph{Charitable Donations (Study 1
outcome)}\label{charitable-donations-study-1-outcome}

Using one item from \citet{hoverd_religious_2010}, we asked
participants, ``How much money have you donated to charity in the last
year?''.

\paragraph{Charitable Volunteering (Study 1
outcome)}\label{charitable-volunteering-study-1-outcome}

We measured hours of volunteering using one item from
\citet{sibley2011}: ``Hours spent \ldots{} voluntary/charitable work.''

\paragraph{Children Number (waves: 1-3,
4-15)}\label{children-number-waves-1-3-4-15}

We measured the number of children using one item from
\citet{Bulbulia_2015}. We asked participants, ``How many children have
you given birth to, fathered, or adopted. How many children have you
given birth to, fathered, or adopted?'' or ``How many children have you
given birth to, fathered, or adopted. How many children have you given
birth to, fathered, and/or parented?'' (waves: 12-15).

\paragraph{Disability}\label{disability}

We assessed disability with a one-item indicator adapted from
\citet{verbrugge1997}. It asks, ``Do you have a health condition or
disability that limits you and that has lasted for 6+ months?'' (1 =
Yes, 0 = No).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

We asked participants, ``What is your highest level of qualification?''.
We coded participants' highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school quals coded as Level 3, and all other ancillary
categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants, ``Are you currently employed? (This includes
self-employed or casual work)''.

\paragraph{Ethnicity}\label{ethnicity}

Based on the New Zealand Census, we asked participants, ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Fatigue}\label{fatigue}

We assessed subjective fatigue by asking participants, ``During the last
30 days, how often did \ldots{} you feel exhausted?'' Responses were
collected on an ordinal scale (0 = None of The Time, 1 = A little of The
Time, 2 = Some of The Time, 3 = Most of The Time, 4 = All of The Time).

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from \citet{campbell2004} , and \citet{sibley2011} (1 =
Strongly Disagree to 7 = Strongly Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\paragraph{Hours of Childcare}\label{hours-of-childcare}

We measured hours of exercising using one item from \citet{sibley2011}:
'Hours spent \ldots{} looking after children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework}

We measured hours of exercising using one item from \citet{sibley2011}:
``Hours spent \ldots{} housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise}

We measured hours of exercising using one item from \citet{sibley2011}:
``Hours spent \ldots{} exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Childcare}\label{hours-of-childcare-1}

We measured hours of exercising using one item from \citet{sibley2011}:
'Hours spent \ldots{} looking after children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise-1}

We measured hours of exercising using one item from \citet{sibley2011}:
``Hours spent \ldots{} exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework-1}

We measured hours of exercising using one item from \citet{sibley2011}:
``Hours spent \ldots{} housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Sleep}\label{hours-of-sleep}

Participants were asked, ``During the past month, on average, how many
hours of \emph{actual sleep} did you get per night?''.

\paragraph{Hours of Work}\label{hours-of-work}

We measured work hours using one item from \citet{sibley2011}: ``Hours
spent \ldots{} working in paid employment.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked, ``Please estimate your total household income
(before tax) for the year XXXX''. To stabilise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Kessler-6: Psychological Distress (waves:
2-3,4-15)}\label{kessler-6-psychological-distress-waves-2-34-15}

We measured psychological distress using the Kessler-6 scale
(kessler2002?), which exhibits strong diagnostic concordance for
moderate and severe psychological distress in large, crosscultural
samples (kessler2010?; prochaska2012?). Participants rated during the
past 30 days, how often did\ldots{} (1) ``\ldots{} you feel hopeless'';
(2) ``\ldots{} you feel so depressed that nothing could cheer you up'';
(3) ``\ldots{} you feel restless or fidgety''; (4)``\ldots{} you feel
that everything was an effort''; (5) ``\ldots{} you feel worthless'';
(6) '' you feel nervous?'' Ordinal response alternatives for the
Kessler-6 are: ``None of the time''; ``A little of the time''; ``Some of
the time''; ``Most of the time''; ``All of the time.''

\paragraph{Male Gender (waves: 1-15)}\label{male-gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male as 1, and gender diverse coded as 3
\citep{fraser_coding_2020}. (or 0.5 = neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants' personalities with the Mini International
Personality Item Pool 6 (Mini-IPIP6) \citep{sibley2011}, which consists
of six dimensions and each dimension is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I often forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live \citep{atkinson2019}. This score combines data
such as income, home ownership, employment, qualifications, family
structure, housing, and access to transport and communication for an
area into one deprivation score.

\paragraph{NZSEI Occupational Prestige and Status (waves:
8-15)}\label{nzsei-occupational-prestige-and-status-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) \citep{fahy2017a}. This index uses
the income, age, and education of a reference group, in this case the
2013 New Zealand census, to calculate a score for each occupational
group. Scores range from 10 (Lowest) to 90 (Highest). This list of index
scores for occupational groups was used to assign each participant an
NZSEI-13 score based on their occupation.

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) \citep{fahy2017}. This index uses the
income, age, and education of a reference group, in this case, the 2013
New Zealand census, to calculate a score for each occupational group.
Scores range from 10 (Lowest) to 90 (Highest). This list of index scores
for occupational groups was used to assign each participant an NZSEI-13
score based on their occupation.

\paragraph{Opt-in}\label{opt-in}

The New Zealand Attitudes and Values Study allows opt-ins to the study.
Because the opt-in population may differ from those sampled randomly
from the New Zealand electoral roll; although the opt-in rate is low, we
include an indicator (yes/no) for this variable.

\paragraph{Partner (No/Yes)}\label{partner-noyes}

``What is your relationship status?'' (e.g., single, married, de-facto,
civil union, widowed, living together, etc.)

\paragraph{Politically Conservative}\label{politically-conservative}

We measured participants' political conservative orientation using a
single item adapted from \citet{jost_end_2006-1}.

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\subparagraph{Religious Service
Attendance}\label{religious-service-attendance}

If participants answered \emph{yes} to ``Do you identify with a religion
and/or spiritual group?'' we measured their frequency of church
attendence using one item from \citet{sibley2012}: ``how many times did
you attend a church or place of worship in the last month?''. Those
participants who were not religious were imputed a score of ``0''.

\paragraph{Rural/Urban Codes}\label{ruralurban-codes}

Participants residence locations were coded according to a five-level
ordinal categorisation ranging from ``Urban'' to Rural, see
\citet{sibley2021}.

\paragraph{Short-Form Health}\label{short-form-health}

Participants' subjective health was measured using one item (``Do you
have a health condition or disability that limits you, and that has
lasted for 6+ months?''; 1 = Yes, 0 = No) adapted from
\citet{verbrugge1997}.

\paragraph{Sample Origin}\label{sample-origin}

Wave enrolled in NZAVS, see \citet{sibley2021}.

\paragraph{Support received: money (waves 10-12) (Study 4
outcomes)}\label{support-received-money-waves-10-12-study-4-outcomes}

The NZAVS has a `revealed' measure of received help and support measured
in hours of support in the previous week. The items are:

\emph{Please estimate how much help you have received from the following
sources in the last week?}

\begin{itemize}
\tightlist
\item
  \emph{family\ldots MONEY (hours)}
\item
  \emph{friends\ldots MONEY (hours)}
\item
  \emph{members of my community\ldots MONEY (hours)}
\end{itemize}

Because this measure is highly variable, we convert responses to binary
indicators: \emph{0 = none/1 any}

\paragraph{Support received: time (waves 10-13) (Study 3
outcomes)}\label{support-received-time-waves-10-13-study-3-outcomes}

\emph{Please estimate how much help you have received from the following
sources in the last week.}

\begin{itemize}
\tightlist
\item
  \emph{family\ldots TIME (hours)}
\item
  \emph{friends\ldots TIME (hours)}
\item
  \emph{members of my community\ldots TIME (hours)}
\end{itemize}

Because this measure is highly variable, we convert responses to binary
indicators: \emph{0 = none/1 any}

\paragraph{Total Siblings}\label{total-siblings}

Participants were asked the following questions related to sibling
counts:

\begin{itemize}
\tightlist
\item
  Were you the 1st born, 2nd born, or 3rd born, etc, child of your
  mother?
\item
  Do you have siblings?
\item
  How many older sisters do you have?
\item
  How many younger sisters do you have?
\item
  How many older brothers do you have?
\item
  How many younger brothers do you have?
\end{itemize}

A single score was obtained from sibling counts by summing responses to
the ``How many\ldots{}'' items. From these scores, an ordered factor was
created ranging from 0 to 7, where participants with more than 7
siblings were grouped into the highest category.

\newpage{}

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{longtable}[]{@{}ll@{}}

\caption{\label{tbl-table-demography}Baseline demographic statistics}

\tabularnewline

\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 33,198} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 51 (14) \\
Range & 18, 96 \\
IQR & 41, 61 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.37 (0.98) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.00 \\
Unknown & 272 \\
\textbf{Born Nz} & 26,197 (79\%) \\
Unknown & 34 \\
\textbf{Children Num} & NA \\
Mean (SD) & 1.76 (1.44) \\
Range & 0.00, 14.00 \\
IQR & 0.00, 3.00 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.14 (1.04) \\
Range & 1.00, 7.00 \\
IQR & 4.50, 6.00 \\
Unknown & 266 \\
\textbf{Education Level Coarsen} & NA \\
no\_qualification & 769 (2.3\%) \\
cert\_1\_to\_4 & 11,278 (34\%) \\
cert\_5\_to\_6 & 4,281 (13\%) \\
university & 8,947 (27\%) \\
post\_grad & 3,892 (12\%) \\
masters & 2,956 (9.0\%) \\
doctorate & 891 (2.7\%) \\
Unknown & 184 \\
\textbf{Employed} & 26,379 (80\%) \\
Unknown & 26 \\
\textbf{Eth Cat} & NA \\
euro & 27,404 (83\%) \\
maori & 3,424 (10\%) \\
pacific & 707 (2.1\%) \\
asian & 1,438 (4.4\%) \\
Unknown & 225 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.88 (1.20) \\
Range & 1.00, 7.00 \\
IQR & 3.00, 4.75 \\
Unknown & 266 \\
\textbf{Hlth Disability} & 7,558 (23\%) \\
Unknown & 561 \\
\textbf{Hlth Fatigue} & NA \\
0 & 5,289 (16\%) \\
1 & 10,940 (33\%) \\
2 & 10,196 (31\%) \\
3 & 4,862 (15\%) \\
4 & 1,577 (4.8\%) \\
Unknown & 334 \\
\textbf{Hlth Sleep Hours} & NA \\
Mean (SD) & 6.95 (1.11) \\
Range & 2.50, 16.00 \\
IQR & 6.00, 8.00 \\
Unknown & 1,528 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.49 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.50 \\
Unknown & 269 \\
\textbf{Hours Children log} & NA \\
Mean (SD) & 1.10 (1.58) \\
Range & 0.00, 5.13 \\
IQR & 0.00, 2.20 \\
Unknown & 875 \\
\textbf{Hours Exercise log} & NA \\
Mean (SD) & 1.57 (0.83) \\
Range & 0.00, 4.39 \\
IQR & 1.10, 2.08 \\
Unknown & 875 \\
\textbf{Hours Housework log} & NA \\
Mean (SD) & 2.15 (0.77) \\
Range & 0.00, 5.13 \\
IQR & 1.79, 2.71 \\
Unknown & 875 \\
\textbf{Hours Work log} & NA \\
Mean (SD) & 2.64 (1.59) \\
Range & 0.00, 4.62 \\
IQR & 1.10, 3.71 \\
Unknown & 875 \\
\textbf{Household Inc log} & NA \\
Mean (SD) & 11.41 (0.76) \\
Range & 0.69, 14.92 \\
IQR & 11.00, 11.92 \\
Unknown & 1,352 \\
\textbf{Kessler6 Sum} & NA \\
Mean (SD) & 5 (4) \\
Range & 0, 24 \\
IQR & 2, 7 \\
Unknown & 297 \\
\textbf{Male} & 11,975 (36\%) \\
\textbf{Modesty} & NA \\
Mean (SD) & 6.03 (0.90) \\
Range & 1.00, 7.00 \\
IQR & 5.50, 6.75 \\
Unknown & 11 \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.45 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 2.50, 4.25 \\
Unknown & 274 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.69 (2.70) \\
Range & 1.00, 10.00 \\
IQR & 2.00, 7.00 \\
Unknown & 233 \\
\textbf{Nzsei 13 l} & NA \\
Mean (SD) & 55 (16) \\
Range & 10, 90 \\
IQR & 42, 69 \\
Unknown & 172 \\
\textbf{Openness} & NA \\
Mean (SD) & 4.99 (1.12) \\
Range & 1.00, 7.00 \\
IQR & 4.25, 5.75 \\
Unknown & 267 \\
\textbf{Partner} & 24,869 (76\%) \\
Unknown & 422 \\
\textbf{Political Conservative} & NA \\
1 & 1,777 (5.6\%) \\
2 & 6,563 (21\%) \\
3 & 6,505 (20\%) \\
4 & 9,373 (29\%) \\
5 & 4,813 (15\%) \\
6 & 2,378 (7.5\%) \\
7 & 483 (1.5\%) \\
Unknown & 1,306 \\
\textbf{Religion Church Round} & NA \\
0 & 27,653 (83\%) \\
1 & 1,077 (3.2\%) \\
2 & 777 (2.3\%) \\
3 & 658 (2.0\%) \\
4 & 1,729 (5.2\%) \\
5 & 336 (1.0\%) \\
6 & 226 (0.7\%) \\
7 & 74 (0.2\%) \\
8 & 668 (2.0\%) \\
\textbf{Rural Gch 2018 l} & NA \\
1 & 20,361 (62\%) \\
2 & 6,390 (19\%) \\
3 & 4,020 (12\%) \\
4 & 1,816 (5.5\%) \\
5 & 380 (1.2\%) \\
Unknown & 231 \\
\textbf{Sample Frame Opt in} & 1,107 (3.3\%) \\
\textbf{Sample Origin} & NA \\
1-2 & 2,191 (6.6\%) \\
3-3.5 & 1,664 (5.0\%) \\
4 & 1,987 (6.0\%) \\
5-6-7 & 3,203 (9.6\%) \\
8-9 & 4,264 (13\%) \\
10 & 19,889 (60\%) \\
\textbf{Short Form Health} & NA \\
Mean (SD) & 5.06 (1.16) \\
Range & 1.00, 7.00 \\
IQR & 4.33, 6.00 \\
Unknown & 5 \\
\textbf{Total Siblings} & NA \\
Mean (SD) & 2.52 (1.80) \\
Range & 0.00, 23.00 \\
IQR & 1.00, 3.00 \\
Unknown & 689 \\

\end{longtable}

Table~\ref{tbl-table-demography} baseline demographic statistics for
couples who met inclusion criteria.

\newpage{}

\subsection{Appendix C: Treatment Statistics}\label{appendix-exposures}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4247}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}@{}}

\caption{\label{tbl-table-exposures-code}Exposures at baseline and
baseline + 1 (treatment) wave}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 33,198
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 33,198
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Religion Church Round} & NA & NA \\
0 & 27,653 (83\%) & 28,028 (84\%) \\
1 & 1,077 (3.2\%) & 896 (2.7\%) \\
2 & 777 (2.3\%) & 737 (2.2\%) \\
3 & 658 (2.0\%) & 639 (1.9\%) \\
4 & 1,729 (5.2\%) & 1,672 (5.0\%) \\
5 & 336 (1.0\%) & 308 (0.9\%) \\
6 & 226 (0.7\%) & 205 (0.6\%) \\
7 & 74 (0.2\%) & 68 (0.2\%) \\
8 & 668 (2.0\%) & 645 (1.9\%) \\
Unknown & 0 & 0 \\
\textbf{Alert Level Combined} & NA & NA \\
no\_alert & 33,198 (100\%) & 23,751 (72\%) \\
early\_covid & 0 (0\%) & 3,643 (11\%) \\
alert\_level\_1 & 0 (0\%) & 2,821 (8.5\%) \\
alert\_level\_2 & 0 (0\%) & 836 (2.5\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 552 (1.7\%) \\
alert\_level\_4 & 0 (0\%) & 1,595 (4.8\%) \\
Unknown & 0 & 0 \\

\end{longtable}

tbl-table-exposures-code presents baseline (NZAVS time 10) and exposure
wave (NZAVS time 11) statistics for the exposure variable: religious
service attendance (range 0-8). Responses coded as eight or above were
coded as ``8''. This decision to avoid spare treatments was based on
theoretical grounds, namely, that daily exposure would be similar in its
effects to more than daily exposure. We note that causal contrasts were
obtained for projects with either no attendance or four or more visits
per month. Hence this simplification of the measure is unlikely to
affect theoretical and practical inferences. All models adjusted for the
pandemic alert level because the treatment wave (NZAVS time 11) occurred
during New Zealand's COVID-19 pandemic. The pandemic is not a
``confounder'' because a confounder must be related to the treatment and
the outcome. At the end of the study, all participants had been exposed
to the pandemic. However, to satisfy the causal consistency assumption,
all treatments must be conditionally equivalent within levels of all
covariates \citep{vanderweele2013}. Because COVID affected the ability
or willingness of individuals to attend religious service, we included
the lockdown condition as a covariate \citep{sibley2021}. To better
enable conditional independence within levels of the treatment variable,
we conditioned on the lead value of COVID-alert level at baseline. To
mitigate systematic biases arising from attrition and missingness, the
\texttt{lmtp} package uses inverse probability of censoring weights,
which were used when estimating the causal effects of the exposure on
the outcome.

\subsubsection{Binary Transition Table for The
Treatment}\label{binary-transition-table-for-the-treatment}

\begin{longtable}[]{@{}ccc@{}}

\caption{\label{tbl-transition-tablegain}Transition table for stability
and change in regular religious service (4x per month) between baseline
and treatment wave.}

\tabularnewline

\toprule\noalign{}
From & \textgreater=4 & \textless{} 4 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textgreater=4 & \textbf{29496} & 669 \\
\textless{} 4 & 804 & \textbf{2229} \\

\end{longtable}

Table~\ref{tbl-transition-tablegain} presents a transition matrix to
evaluate treatment shifts between baseline and treatment wave. Here, we
focus on the shift from/to monthly attendance at four or more visits per
month. Entries along the diagonal (in bold) indicate the number of
individuals who \textbf{stayed} in their initial state. By contrast, the
off-diagonal shows the transitions from the initial state (bold) to
another state in the following wave (off diagonal). Thus the cell
located at the intersection of row \(i\) and column \(j\), where
\(i \neq j\), gives us the counts of individuals moving from state \(i\)
to state \(j\).

\begin{longtable}[]{@{}ccc@{}}

\caption{\label{tbl-transition-tableloss}Transition table for stability
and change in zero religious service (0 x per month) between baseline
and treatment wave.}

\tabularnewline

\toprule\noalign{}
From & 0 & \textgreater{} 0 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & \textbf{26762} & 891 \\
\textgreater{} 0 & 1266 & \textbf{4279} \\

\end{longtable}

Table~\ref{tbl-transition-tableloss} presents a transition matrix to
evaluate treatment shifts between baseline and treatment wave. Here, we
focus on the shift from/to zero religious service attendance. Again,
entries along the diagonal (in bold) indicate the number of individuals
who \textbf{stayed} in their initial state. By contrast, the
off-diagonal shows the transitions from the initial state (bold) to
another state in the following wave (off diagonal). Thus the cell
located at the intersection of row \(i\) and column \(j\), where
\(i \neq j\), gives us the counts of individuals moving from state \(i\)
to state \(j\).

\subsubsection{Imbalance of Confounding Covariates
Treatments}\label{imbalance-of-confounding-covariates-treatments}

Fig~\ref{fig-match_1} shows imbalance of covariates on the treatment at
the treatment wave. The variable on which there is strongest imbalance
is the baseline measure of religious service attendance. It is important
to adjust for this measure both for confounding control and to better
estimate an incident exposure effect for the religious service at the
treatment wave (in contrast to merely estimating a prevalence effect).
See \citet{vanderweele2020}.

\begin{figure}

\centering{

\includegraphics{v7-man-lmtp-ow-coop-church_files/figure-pdf/fig-match_1-1.pdf}

}

\caption{\label{fig-match_1}This figure shows the imbalance in
covariates on the treatment}

\end{figure}%

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4474}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2763}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2763}}@{}}

\caption{\label{tbl-table-outcomes}Outcomes at baseline and
end-of-study}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 33,198
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 33,198
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Annual Charity} & 150 (40, 500) & 200 (20, 600) \\
Unknown & 1,076 & 6,730 \\
\textbf{Community Gives Money Binary} & 135 (0.4\%) & 118 (0.4\%) \\
Unknown & 669 & 6,959 \\
\textbf{Community Gives Time Binary} & 1,702 (5.2\%) & 1,669 (6.4\%) \\
Unknown & 669 & 6,959 \\
\textbf{Family Gives Money Binary} & 1,782 (5.5\%) & 1,236 (4.7\%) \\
Unknown & 669 & 6,959 \\
\textbf{Family Gives Time Binary} & 9,539 (29\%) & 7,600 (29\%) \\
Unknown & 669 & 6,959 \\
\textbf{Friends Give Money Binary} & 372 (1.1\%) & 270 (1.0\%) \\
Unknown & 669 & 6,959 \\
\textbf{Friends Give Time} & 5,765 (18\%) & 4,855 (19\%) \\
Unknown & 669 & 6,959 \\
\textbf{Sense Neighbourhood Community} & NA & NA \\
1 & 1,976 (6.0\%) & 1,124 (4.2\%) \\
2 & 4,037 (12\%) & 2,703 (10\%) \\
3 & 4,796 (15\%) & 3,561 (13\%) \\
4 & 6,840 (21\%) & 5,809 (22\%) \\
5 & 7,088 (21\%) & 6,477 (24\%) \\
6 & 5,753 (17\%) & 5,060 (19\%) \\
7 & 2,550 (7.7\%) & 2,104 (7.8\%) \\
Unknown & 158 & 6,360 \\
\textbf{Social Belonging} & 5.33 (4.33, 6.00) & 5.33 (4.33, 6.00) \\
Unknown & 268 & 6,418 \\
\textbf{Social Support} & 6.33 (5.33, 7.00) & 6.33 (5.33, 7.00) \\
Unknown & 19 & 6,286 \\
\textbf{Volunteering Hours} & 0.00 (0.00, 1.00) & 0.00 (0.00, 1.00) \\
Unknown & 875 & 6,863 \\
\textbf{Volunteers Binary} & 9,443 (29\%) & 6,881 (26\%) \\
Unknown & 875 & 6,863 \\

\end{longtable}

Table~\ref{tbl-table-outcomes} presents baseline and end-of-study
descriptive statistics for the outcome variables.

\newpage{}

\subsection{References}\label{references}


\nolinenumbers
  \bibliography{/Users/joseph/GIT/templates/bib/references.bib}

\end{document}
