% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\let\oldtabular\tabular
\renewcommand{\tabular}{\small\oldtabular}
\setlength{\tabcolsep}{4pt}  % Adjust this value as needed
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Religious Service Attendance Increases Meaning, Gratitude, and Sexual Satisfaction (But Not Much Else) in Secular New Zealand.},
  pdfauthor={Joseph A. Bulbulia; Don E Davis; Cyrstal Park; Kenneth G. Rice; Geoffrey Troughton; Daryl Van Tongeren; Chris G. Sibley},
  pdfkeywords={Use, use},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Religious Service Attendance Increases Meaning, Gratitude, and
Sexual Satisfaction (But Not Much Else) in Secular New Zealand.}

\usepackage{academicons}
\usepackage{xcolor}

  \author{Joseph A. Bulbulia}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5861-2056 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Don E Davis}
            \affil{%
             \small{     Georgia State University, Matheny Center for
the Study of Stress, Trauma, and Resilience
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0003-3169-6576 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Cyrstal Park}
            \affil{%
             \small{     Univeristy of Conneticut, Department of
Psychological Sciences
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0001-6572-7321 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Kenneth G. Rice}
            \affil{%
             \small{     Georgia State University, Matheny Center for
the Study of Stress, Trauma, and Resilience
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-0558-2818 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Geoffrey Troughton}
            \affil{%
             \small{     School of Social and Cultural Studies, Victoria
University of Wellington
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0001-7423-0640 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Daryl Van Tongeren}
            \affil{%
             \small{     Hope College
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-1810-9448 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Chris G. Sibley}
            \affil{%
             \small{     School of Psychology, University of Auckland
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-4064-8800 }
              }
      


\date{2024-12-22}
\begin{document}
\maketitle
\begin{abstract}
We use nationally representative longitudinal data from 46,377 New
Zealanders (2018--2023) to estimate the causal effects of religious
service attendance on multiple dimensions of well-being. We compare two
hypothetical four-year scenarios: (a) everyone attends services at least
four times per month, and (b) no one attends. We adjust for baseline
covariates measured before these interventions, including baseline
service attendance and baseline measurements of multi-dimensional
well-being. We also adjust for time-varying counfounders such as
employment, disability, relationships, and parenting. We assess outcomes
in the year following these sequential treatment regimes. Using
cross-validation and doubly robust machine-learning estimators, along
with inverse probability-of-censoring weights, we find that regular
attendance increases a sense of meaning and purpose, enhances gratitude,
and, somewhat unexpectedly, improves sexual satisfaction. Effects on
mental health are modest, while effects on biological health and social
well-being are negligible or small. In a largely secular population,
attending religious services regularly boosts purpose, nurtures
gratitude, and raises sexual satisfaction, yet yields few other clear
benefits. \textbf{KEYWORDS}: \emph{Causal Inference}; \emph{Church};
\emph{Cross-validation}; \emph{Distress}; \emph{Health};
\emph{Longitudinal}; \emph{Machine Learning}; \emph{Religion};
\emph{Semi-parametric}; \emph{Targeted Learning}.
\end{abstract}


\subsection{Introduction}\label{introduction}

Religious participation is a core aspect of many cultures, and the
question of whether attending religious services influences human
well-being is longstanding (\citeproc{ref-koenig2012handbook}{Koenig
\emph{et al.} 2012}; \citeproc{ref-park2005religion}{Park 2005}). Within
religious traditions, the belief that religious practices benefit
adherents permeates theology, moral teaching, and community life, from
Buddhism's emphasis on meditation as a path to enlightenment and reduced
suffering, to Christianity's view of prayer and worship as means of
spiritual growth and divine connection, to Indigenous spiritual
practices that are seen as maintaining harmony between people, nature,
and the sacred. More recently, secular empirical research has linked
religious service attendance with multiple dimensions of well-being,
including social integration, life satisfaction, mental health, and
meaning-making (\citeproc{ref-chen2020religious}{Chen \emph{et al.}
2020}; \citeproc{ref-dunbar2021religiosity}{Dunbar 2021};
\citeproc{ref-highland2022national}{Highland \emph{et al.} 2022};
\citeproc{ref-vanderweele2022invited_church}{VanderWeele \emph{et al.}
2022}). These studies have demonstrated that, on average, individuals
who attend services report more favourable social and psychological
outcomes.

Although some studies have strengthened causal claims through
appropriate causal methods (\citeproc{ref-vanderweelechurchmortality}{Li
\emph{et al.} 2016}; \citeproc{ref-pawlikowski2019religious}{Pawlikowski
\emph{et al.} 2019};
\citeproc{ref-vanderweele2021effectsReligiousServiceMetanalysis}{VanderWeele
2021}; \citeproc{ref-vanderweele2020vchenrespond}{VanderWeele and Chen
2020}), concerns about causality persist
(\citeproc{ref-highland2019attitudes}{Highland \emph{et al.} 2019}).
Many investigations do not fully adjust for baseline health and baseline
religious service, or important confounders that shape both religious
engagement and well-being (\citeproc{ref-brown2023_church}{Brown
\emph{et al.} 2023}; \citeproc{ref-jokela2024_church}{Jokela and
Laakasuo 2024}). For example, Jokela and Laakasuo's analysis of four
U.S. cohort studies (N=6,592) found that poorer health trajectories came
before, rather than followed, religious disengagement. This suggests
that declining religious practice might track pre-existing health
problems rather than cause them. Similarly, global data from Iyer and
Rosso (N=65,564) show that frequent attenders report about five
percentage points higher life satisfaction than infrequent attenders;
however, this association could reflect unmeasured biases or reverse
causation. Chen and colleagues observe that well-being itself is
multifaceted, spanning emotional, physical, social, and psychological
domains, and that some domains -- such as meaning, purpose, and social
connection -- may be more affected than others
(\citeproc{ref-chen2022_church_longitudinal}{Chen \emph{et al.} 2022}).

Despite these efforts, many questions remain. Existing research often
relies on non-representative samples or predominantly religious
environments, seldom fully addresses time-varying confounding, and
rarely considers populations in which religious engagement is relatively
low. Brown et al.~hypothesise that community-building itself, rather
than specifically religious community-building, may drive any observed
well-being benefits. Natural-experimental evidence from New Zealand
supports this notion (\citeproc{ref-brown2023_church}{Brown \emph{et
al.} 2023}). Following the 2010--2011 Christchurch earthquakes, those
who maintained or lacked faith reported similar levels of subjective
health, whereas those who lost faith showed declines in subjective
health (\citeproc{ref-sibley2012}{Sibley and Bulbulia 2012}). These
patterns suggest that the community context -- religious or not -- may
be critical.

In sum, there is a need for studies that move beyond cross-sectional
correlations to address causation, address causation robustly, and
systematically evaluate multiple dimensions of well-being
(\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).
Without such evidence, policy, clinical, and theoretical questions about
the causal role of religious service attendance in supporting human
flourishing remain unanswered.

Here, we improve understanding by estimating the causal effects of
regular religious service attendance on multidimensional well-being
using data from a large, nationally diverse sample of New Zealanders
(baseline \(N=46,377\)) enrolled in the New Zealand Attitudes and Values
Study (NZAVS). New Zealand is characterised by high religious diversity
and secularisation. Over half the population identifies as having no
religion, while multiple religious traditions -- Christianity, Hinduism,
Islam, Buddhism, and others -- coexist
(\citeproc{ref-shaver2016religion}{Shaver \emph{et al.} 2016}). Drawing
on an informationally rich national panel study and recent innovations
in causal inference (\citeproc{ref-bulbulia2023}{Bulbulia 2024c};
\citeproc{ref-hernan2024WHATIF}{Hernan and Robins 2024};
\citeproc{ref-williams2021}{Williams and Díaz 2021}), we systematically
examine whether a settings in which the adult population attended
services regularly differs in its affects across multi-dimensional
well-being from a setting in which no-one attends. We estimation these
effects using a workflow in which non-parementric machine learning
reduces statistical modelling assumptions. We contribute to
understanding by estimating causal effects in a distinctly secular, and
culturally diverse context, and obtain generalisable inferences about
whether, and where, religious service attendance causally affects a
well-being phenotype across dimensions of biological health,
psychological health, person-focussed well-being, life-focussed
well-being and social well-being.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of the New Zealand Attitudes and Values
Study (NZAVS), an annual longitudinal national probability panel
assessing New Zealand residents' social attitudes, personality,
ideology, and health outcomes. The panel began in 2009 and has since
expanded to include over fifty researchers, with responses from 76,409
participants to date. The study operates independently of political or
corporate funding and is based at a university. It employs prize draws
to incentivise participation. The NZAVS tends to slightly under-sample
males and individuals of Asian descent and to over-sample females and
Māori (the Indigenous people of New Zealand). To enhance
representativeness of the target population, we apply Census-based
survey weights that adjust for age, gender, and ethnicity (New Zealand
European, Asian, Māori, Pacific) (\citeproc{ref-sibley2021}{Sibley
2021}). For more information about the NZAVS, visit:
\href{https://doi.org/10.17605/OSF.IO/75SNB}{OSF.IO/75SNB}. The data for
this study were obtained from the NZAVS waves 10-15 cohort, covering
years 2018-2024. Although this cohort is a national probability sample,
we weighted responses by New Zealand 2018 Census estimates (age, gender,
ethnicity) to produce results that better reflect the New Zealand
population. Information on these survey weights can be found in the
NZAVS documentation, see:
\href{https://doi.org/10.17605/OSF.IO/75SNB}{OSF.IO/75SNB}. Refer to
\hyperref[appendix-timeline]{Appendix A} for a histogram of daily
responses for this cohort.

\subsubsection{Target Population}\label{target-population}

The target population for this study comprises the cohort of New Zealand
residents in New Zealand Attitudes and Values Study wave 10 (years
2018-2019) (\citeproc{ref-sibley2021}{Sibley 2021}).

\subsubsection{Treatment Indicator}\label{treatment-indicator}

We assessed religious service attendance using the following question:

\begin{itemize}
\tightlist
\item
  \emph{Do you identify with a religion and/or spiritual group? If yes,
  how many times did you attend a church or place of worship during the
  last month?}
\end{itemize}

Responses were rounded to the nearest whole number. Because few
participants reported attending more than eight times, we capped
responses above eight at eight (see Appendix B, variable
\texttt{religion\_church\_round}). In the regular church service
condition, we did not intervene on responses greater than four to reduce
computational burdens during estimation.

\subsubsection{Outcomes}\label{outcomes}

\subsubsection{Baseline Covariates}\label{baseline-covariates}

We controlled for a broad range of baseline variables measured at Wave
10 (2018--2019) to reduce confounding by demographic, personality, and
behavioural factors (see Appendix for full measures). These included
age, gender, ethnicity, education level, personality traits
(Agreeableness, Conscientiousness, Extraversion, Honesty-Humility,
Neuroticism, and Openness), household income, employment status,
parenting status, relationship status, religious belonging, and
health-related behaviours (e.g.~smoking, alcohol use, hours spent
exercising). We also controlled for all outcome measures and for
religious service attendance at baseline to minimise reverse causation
(refer to \href{appendix-baseline}{Appendix B}).

\subsubsection{Exposure}\label{exposure}

The primary exposure was religious service attendance. We assessed how
often participants attended any church or place of worship during the
study period, creating an intervention that either shifted attendance to
at least monthly or set attendance to zero.

\subsubsection{Outcomes}\label{outcomes-1}

We categorised outcomes into five domains---health, psychological
well-being, present-reflective outcomes, life-reflective outcomes, and
social outcomes---based on validated scales and measures. Table 1
summarises each domain and its associated measures. For instance, health
outcomes included BMI and hours of sleep, whereas psychological
well-being encompassed anxiety and depression. Outcomes were
standardised where appropriate (i.e.~converted to z-scores) to
facilitate comparison.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.2787}}
  >{\raggedright\arraybackslash}p{(\linewidth - 2\tabcolsep) * \real{0.7213}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Domain
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Example Measures
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Health & BMI, Hours of Sleep, Hours of Exercise, SF-Health \\
Psychological Well-Being & Anxiety, Depression, Fatigue, Rumination \\
Present-Reflective & Body Satisfaction, Forgiveness, Self Esteem, Sexual
Satisfaction \\
Life-Reflective & Gratitude, Life Satisfaction, Meaning (Sense \&
Purpose) \\
Social & Belonging, Support, Community \\
\end{longtable}

Data summaries for all measures used in this study are provided in
\href{appendix-baseline}{Appendix B}.

\subsection{Causal Interventions}\label{causal-interventions}

When psychologists model time-series data, they often use growth models
to quantify patterns of change over time. However, many research
questions are causal: we want to know what would happen if we could
intervene on certain variables (e.g., religious service attendance). To
study these questions using observational time-series data, we must
clearly state our causal question. Here, we ask:

\begin{quote}
``What if, at each wave, we intervened to set religious service
attendance to a certain level, and then measured everyone's well-being
at the final wave?''
\end{quote}

We compare two hypothetical interventions that alter religious service
attendance over four exposure waves (Waves 1--4), with outcomes measured
at Wave 5, and controlling for a rich set of baseline covariates
measured at Wave 0. In line with the modified treatment policies
literature, we define \textbf{shift functions} to describe each regime.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Regular Religious Service Attendance}\\
  At each wave, if a person's attendance is below four times per month,
  we shift it up to four; otherwise, we leave it unchanged.
\item
  \textbf{No Religious Service Attendance}\\
  At each wave, if a person's attendance is above zero, we shift it down
  to zero; otherwise, we leave it unchanged.
\end{enumerate}

A confounder is a variable that when included in the the model, removes
any non-causal association between a `treatment' and `outcome'. Here, we
adjust for important confounders at the baseline wave (Wave 0). We also
adjust for the following time-varying confounders at each wave: physical
disability, employment, partner status, and parenting status. These
factors may, independently of baseline measurements, influence both
attendance at each wave and later outcomes.

\subsubsection{Notation}\label{notation}

\begin{itemize}
\tightlist
\item
  \(A_k\): Observed religious service attendance at Wave \(k\), for
  \(k = 1, \dots, 4\).\\
\item
  \(Y_\tau\): Outcome measured at the end of the study (Wave 5).\\
\item
  \(W_0\): Confounders measured at baseline (Wave 0).\\
\item
  \(L_k\): Time-varying confounders measured at Wave \(k\) (for
  \(k = 1, \dots, 4\)).
\end{itemize}

\subsubsection{Shift Functions}\label{shift-functions}

Let \(\boldsymbol{d}(a_k)^+\) represent the \textbf{regular attendance}
treatment sequence and \(\boldsymbol{d}(a_k)^-\) the \textbf{no
attendance} treatment sequence, where the interventions occure at each
wave \(k = 1\dots 4\). Formally:

\paragraph{\texorpdfstring{Regular Attendance Regime
\(\bigl(\boldsymbol{d}(a_k^+)\bigr)\)}{Regular Attendance Regime \textbackslash bigl(\textbackslash boldsymbol\{d\}(a\_k\^{}+)\textbackslash bigr)}}\label{regular-attendance-regime-biglboldsymbolda_kbigr}

\[
\boldsymbol{d}(a_k^+) 
\;=\; 
\begin{cases}
4, & \text{if } A_k < 4,\\[6pt]
A_k, & \text{otherwise.}
\end{cases}
\]

\paragraph{\texorpdfstring{No Attendance Regime
\(\bigl(\boldsymbol{d}(a_k^-)\bigr)\)}{No Attendance Regime \textbackslash bigl(\textbackslash boldsymbol\{d\}(a\_k\^{}-)\textbackslash bigr)}}\label{no-attendance-regime-biglboldsymbolda_k-bigr}

\[
\boldsymbol{d}(a_k^-) 
\;=\; 
\begin{cases}
0, & \text{if } A_k > 0,\\[6pt]
A_k, & \text{otherwise.}
\end{cases}
\]

Here, \(A_k\) is the observed attendance at Wave \(k\). The shift
function \(\boldsymbol{d}\) `nudges' \(A_k\) to a target level (four
times per month or zero) only if the current value is below (for regular
attendance) or above (for no attendance) that target. Across the four
waves, these shifts form a sequence \(\boldsymbol{\bar{d}}\), which
defines a complete intervention regime.

\begin{table}

\caption{\label{tbl-intervention}Causal diagrams showing sources of bias
in a three wave panel study.}

\centering{

\tvtable

}

\end{table}%

\subsubsection{Causal Contrast}\label{causal-contrast}

We compare the average well-being under the \textbf{regular attendance}
regime, \(\boldsymbol{\bar{d}}(a^+)\), to the average well-being under
the \textbf{no attendance} regime, \(\boldsymbol{\bar{d}}(a^-)\).
Specifically, the average treatment effect (ATE) is given:

\[
\text{ATE}^{\text{wellbeing}} 
\;=\; 
\mathbb{E}
\Bigl[
  Y_\tau\!\bigl(\boldsymbol{\bar{d}}(a^+)\bigr) 
  \;-\; 
  Y_\tau\!\bigl(\boldsymbol{\bar{d}}(a^-)\bigr)
\Bigr].
\]

\subsubsection{Assumptions}\label{assumptions}

To estimate this effect from observational data, we assume:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Conditional Exchangeability:} Once we condition on \(W_0\) and
  each \(L_k\), the interventions \(\boldsymbol{\bar{d}}(a^+)\) or
  \(\boldsymbol{\bar{d}}(a^-)\) are effectively random with respect to
  potential outcomes.
\item
  \textbf{Consistency:} The potential outcome under a given regime
  matches the observed outcome when that regime is actually followed.
\item
  \textbf{Positivity:} Everyone has a non-zero probability of receiving
  each level of attendance (i.e., a chance to be `shifted' up or down)
  given their covariates.
\end{enumerate}

Mathematically, for conditional exchangeability, we write:

\[
\Bigl\{
  Y\bigl(\boldsymbol{d}(a^+)\bigr), 
  \; 
  Y\bigl(\boldsymbol{d}(a^-)\bigr)
\Bigr\}
\coprod
A_k |
L_k,
W_0.
\]

Under these assumptions, our statistical models permit us to estimate
\(\text{ATE}^{\text{wellbeing}}\) from observational data. Again, that
contrast is `regularly attend religious service at least four wave'
versus `never attend religious service at least four waves'. Finally, we
define the target population as the New Zealand Population from
2019-2024, the years in which measurements were taken.

Although both growth models and causal inference methods can inform
changes over time, they focus on different questions. Growth models
quantify how individuals vary in their natural trajectories. In
contrast, causal models explicitly ask: ``What happens if we
intervene?'' By defining hypothetical interventions, adjusting for
confounders, and specifying assumptions, researchers can rigorously
address ``what if'' questions, bridging the gap between observational
data and actionable insights. This approach opens new avenues for
psychological scientists to design and evaluate interventions that might
guide policy and practice with evidence.

\subsubsection{Statistical Estimator}\label{statistical-estimator}

We estimate the causal effect of modified treatment policies over time
using a semi-parametric Sequential Doubly-Robust estimator from the
\texttt{lmtp} package (\citeproc{ref-williams2021}{Williams and Díaz
2021}). The SDR algorithm proceeds in two steps. First, machine learning
algorithms flexibly model the relationships among treatments,
covariates, and outcomes, allowing SDR to capture complex,
high-dimensional covariate structures without strict model assumptions.
This step yields an initial set of estimates
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021}). In the second
step, SDR ``targets'' these initial estimates by incorporating observed
data distribution information, improving the accuracy of the causal
effect estimate through an iterative process. The SDR estimator is
multiply robust for repeated treatments across multiple waves
(\citeproc{ref-diaz2023lmtp}{Díaz \emph{et al.} 2023};
\citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023}), improving model
robustness to misspecification in either the outcome or treatment model.
The \texttt{lmtp} package relies on the \texttt{SuperLearner} library in
R, which integrates diverse machine learning algorithms
(\citeproc{ref-SuperLearner2023}{Polley \emph{et al.} 2023b}). We used
the \texttt{SL.ranger}, \texttt{SL.glmnet}, and \texttt{SL.xgboost}
(\citeproc{ref-xgboost2023}{Chen \emph{et al.} 2023};
\citeproc{ref-polley2023}{Polley \emph{et al.} 2023a};
\citeproc{ref-Ranger2017}{Wright and Ziegler 2017}) learners.
\textbf{\texttt{SL.ranger}}: implements a random forest algorithm that
handles non-linear relationships and complex patterns, improving model
accuracy but potentially increasing variance.
\textbf{\texttt{SL.glmnet}}: provides regularised linear models that
help manage high dimensionality and collinearity, effectively reducing
model variance and improving stability. \textbf{\texttt{SL.xgboost}}:
uses gradient boosting to optimize performance and capture complex
interactions, balancing the model's ability to explore data complexities
without overfitting (\citeproc{ref-polley2023}{Polley \emph{et al.}
2023a}). The ensemble approach of \texttt{superlearner} optimally
combines predictions from these models. Graphs, tables and output
reports were created using the \texttt{margot} package
(\citeproc{ref-margot2024}{Bulbulia 2024b}). For further details of the
targeted learning using \texttt{lmtp} see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023}).

\subsection{Sensitivity Analysis}\label{sensitivity-analysis}

We perform sensitivity analyses using the E-value metric
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
represents the minimum association strength (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and outcome---after adjusting for measured covariates---to explain away
the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).

\subsection{Results}\label{results}

\subsubsection{Health}\label{health}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-church-wb-long_files/figure-pdf/fig-health-1.pdf}}

}

\caption{\label{fig-health}Health effects}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3288}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2192}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0822}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0959}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1096}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1644}}@{}}

\caption{\label{tbl-health}Health effects}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
BMI & -0.03 & -0.05 & -0.02 & 1.21 & 1.16 \\
Sleep & 0.01 & -0.01 & 0.04 & 1.12 & 1.00 \\
Hours of Exercise (log) & -0.06 & -0.09 & -0.04 & 1.31 & 1.22 \\
Short Form Health & -0.02 & -0.04 & 0.00 & 1.15 & 1.00 \\

\end{longtable}

\paragraph{Bmi}\label{bmi}

The effect estimate (rd) is -0.034 (-0.049, -0.019). On the original
scale, the estimated effect is -0.206 (-0.297, -0.115). E-value lower
bound is 1.156, indicating evidence for causality.

\paragraph{Hours of exercise (log)}\label{hours-of-exercise-log}

The effect estimate (rd) is -0.063 (-0.09, -0.036). On the original
scale, the estimated effect is -16.294 minutes (-23.021 to -9.415
minutes). E-value lower bound is 1.217, indicating evidence for
causality.

All other effect estimates presented either weak or unreliable evidence
for causality.

\newpage{}

\subsubsection{Psychological Well-Being}\label{psychological-well-being}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-church-wb-long_files/figure-pdf/fig-psych-1.pdf}}

}

\caption{\label{fig-psych}Effects on Psychological Well-Being}

\end{figure}%

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-psych}Effects on Psychological Well-Being}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Fatigue & 0.00 & -0.02 & 0.02 & 1.03 & 1.00 \\
Anxiety & -0.02 & -0.04 & 0.00 & 1.16 & 1.00 \\
Depression & -0.04 & -0.07 & -0.02 & 1.24 & 1.14 \\
Rumination & -0.02 & -0.04 & 0.01 & 1.14 & 1.00 \\

\end{longtable}

\paragraph{Depression}\label{depression}

The effect estimate (rd) is -0.042 (-0.067, -0.017). On the original
scale, the estimated effect is -0.03 (-0.048, -0.012). E-value lower
bound is 1.139, indicating evidence for causality.

All other effect estimates presented either weak or unreliable evidence
for causality.

\newpage{}

\subsubsection{Life-Focussed Well-Being}\label{life-focussed-well-being}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-church-wb-long_files/figure-pdf/fig-present-1.pdf}}

}

\caption{\label{fig-present}Effects on Person-Focussed Well-Being}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.3951}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1975}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0741}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0864}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0988}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1481}}@{}}

\caption{\label{tbl-present}Effects on Person-Focussed Well-Being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Body Satisfaction & 0.00 & -0.03 & 0.02 & 1.05 & 1.00 \\
Forgiveness & 0.01 & -0.01 & 0.04 & 1.13 & 1.00 \\
Perfectionism & -0.01 & -0.03 & 0.01 & 1.09 & 1.00 \\
PWB Standard Living & 0.05 & 0.02 & 0.07 & 1.26 & 1.18 \\
PWB Your Future Security & 0.00 & -0.02 & 0.03 & 1.04 & 1.00 \\
PWB Your Health & 0.00 & -0.03 & 0.02 & 1.06 & 1.00 \\
PWB Your Relationships & 0.01 & -0.02 & 0.03 & 1.09 & 1.00 \\
Self Control Have Lots & -0.01 & -0.04 & 0.01 & 1.13 & 1.00 \\
Self Control Wish More Reversed & -0.01 & -0.04 & 0.01 & 1.13 & 1.00 \\
Self Esteem & 0.00 & -0.02 & 0.02 & 1.00 & 1.00 \\
Sexual Satisfaction & 0.09 & 0.06 & 0.11 & 1.38 & 1.30 \\

\end{longtable}

\paragraph{Pwb standard living}\label{pwb-standard-living}

The effect estimate (rd) is 0.049 (0.024, 0.073). On the original scale,
the estimated effect is 0.102 (0.051, 0.154). E-value lower bound is
1.179, indicating evidence for causality.

\paragraph{Sexual satisfaction}\label{sexual-satisfaction}

The effect estimate (rd) is 0.085 (0.061, 0.108). On the original scale,
the estimated effect is 0.149 (0.108, 0.191). E-value lower bound is
1.304, indicating evidence for causality.

All other effect estimates presented either weak or unreliable evidence
for causality.

\newpage{}

\subsubsection{Life-Focussed
Well-Being}\label{life-focussed-well-being-1}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-church-wb-long_files/figure-pdf/fig-life-1.pdf}}

}

\caption{\label{fig-life}Effects on Life-Focussed Well-Being}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2687}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2388}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0896}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1045}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1194}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1791}}@{}}

\caption{\label{tbl-life}Effects on Life-Focussed Well-Being}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Gratitude & 0.09 & 0.06 & 0.11 & 1.38 & 1.32 \\
Life Satisfaction & -0.01 & -0.03 & 0.01 & 1.12 & 1.00 \\
Meaning: Purpose & 0.16 & 0.14 & 0.18 & 1.59 & 1.53 \\
Meaning: Sense & 0.08 & 0.06 & 0.10 & 1.36 & 1.29 \\

\end{longtable}

\paragraph{Gratitude}\label{gratitude}

The effect estimate (rd) is 0.086 (0.065, 0.106). On the original scale,
the estimated effect is 0.078 (0.06, 0.097). E-value lower bound is
1.32, indicating evidence for causality.

\paragraph{Meaning: purpose}\label{meaning-purpose}

The effect estimate (rd) is 0.163 (0.142, 0.185). On the original scale,
the estimated effect is 0.231 (0.2, 0.261). E-value lower bound is
1.533, indicating evidence for causality.

\paragraph{Meaning: sense}\label{meaning-sense}

The effect estimate (rd) is 0.081 (0.058, 0.105). On the original scale,
the estimated effect is 0.097 (0.069, 0.125). E-value lower bound is
1.292, indicating evidence for causality.

All other effect estimates presented either weak or unreliable evidence
for causality.

\newpage{}

\subsubsection{Social-Focussed
Well-Being}\label{social-focussed-well-being}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-church-wb-long_files/figure-pdf/fig-social-1.pdf}}

}

\caption{\label{fig-social}Effects on Life-Focussed Well-Being}

\end{figure}%

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-social}Effects on Social Well-Being}

\tabularnewline

\toprule\noalign{}
& E{[}Y(1){]}-E{[}Y(0){]} & 2.5 \% & 97.5 \% & E\_Value &
E\_Val\_bound \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Belonging & 0.04 & 0.01 & 0.06 & 1.22 & 1.13 \\
Community & 0.05 & 0.03 & 0.07 & 1.27 & 1.19 \\
Support & -0.01 & -0.03 & 0.01 & 1.08 & 1.00 \\

\end{longtable}

\paragraph{Belonging}\label{belonging}

The effect estimate (rd) is 0.037 (0.015, 0.059). On the original scale,
the estimated effect is 0.041 (0.016, 0.065). E-value lower bound is
1.134, indicating evidence for causality.

\paragraph{Community}\label{community}

The effect estimate (rd) is 0.052 (0.029, 0.075). On the original scale,
the estimated effect is 0.081 (0.045, 0.117). E-value lower bound is
1.191, indicating evidence for causality.

All other effect estimates presented either weak or unreliable evidence
for causality.

\newpage{}

\subsection{Discussion}\label{discussion}

Our findings suggest that regular religious service attendance can
modestly enhance meaning, gratitude, and sexual satisfaction. Yet, our
analysis also underscores the challenges of making strong causal claims
in observational settings. The absence of consistent or robust evidence
for many hypothesised effects does not mean that such effects do not
exist. Uncertainty arises not only from possible residual confounding,
but also from the likelihood that non-directed measurement error biases
effects toward the null. In other words, failures to detect a
relationship might owe to limitations in our measures rather than to a
genuine absence of effect.

A further caveat is that causal effect estimates reflect a hypothetical
scenario in which the entire target population either consistently
attends services or never attends. This population-level contrast
represents an average treatment effect; we have not examined how the
causal effects of religious service attendance vary by faith tradition,
intensity of belief, or cultural context. Such studies involve changing
the target population from everyone to members of specific population
strata or group. Moroever, at an individual level, different people will
respond differently to religious behaviours, and we assume that people
often know themselves best. Our findings project an average treatment
effect of the adult population of New Zealand, which should not be
confused with life advice.

One of our most robust findings is that religious engagement increases a
sense of meaning and sense of purpose. Why this should be so remains
speculative. Evolutionary accounts might question why, if meaning and
purpose are biologically desirable, they are not universal `default'
states of consciousness. Why would the time and material investments of
religious service attendance require our attention
(\citeproc{ref-sosis2003cooperation}{Sosis and Bressler 2003})? Some
scholars suggest that religious healing might function as a hard-to-fake
signal that validates religious commitments, rather than as an
evolutionary end in itself (\citeproc{ref-bulbulia2006nature}{Bulbulia
2006}). Any evolutionary or functional explanations for why religious
practice boosts meaning presently remains speculative, and must reckon
with the complex cultural and biological processes that have given rise
to and conserved the religions of our day.

Closely related to meaning is the finding that religious engagement
fosters gratitude. In classical Christian thought dating at least to
Aquinas, religion is framed as a virtue of justice called `piety', which
entails rightly acknowledging the sources of one's existence and
sustenance as a debt that cannot be repaid
(\citeproc{ref-bulbulia2023understanding}{Bulbulia 2023}). In a modern
idiom, one might refer to this virtue a `gratitude'. Indeed, the
rehearsal of gratitude is a prominent feature not only of Christian
religious service but of most religious traditions
(\citeproc{ref-bono2004gratitude}{Bono \emph{et al.} 2004};
\citeproc{ref-mccullough2001gratitude}{McCullough \emph{et al.} 2001}).
It has been hypothesised that active attention to gratitude in religious
faith serves to foster prosociality, which, if confirmed, would help to
explain the durability of this result to robust causal estimation
workflows that controls for confounding.

The positive causal association we observe between religious attendance
and sexual satisfaction also raises intriguing questions. Prior research
has documented associations between religiosity and marital sexual
satisfaction (\citeproc{ref-dew2020joint}{Dew \emph{et al.} 2020}),
although these studies rely on cross-sectional data and cannot reliably
infer causation. In line with that correlational literature, however, we
find that religious service attendance causes modest improvements in
sexual satisfaction, effects that remain after controlling for baseline
values of both indicators. One possible explanation is that religious
activities help align values, enhance communication, and foster stable
social support networks within couples, thereby strengthening intimacy.
Such intimacy is especially valuable for parenting---described as the
ultimate cooperation problem because it involves demanding commitments
that link biological fates
(\citeproc{ref-bulbulia2015}{\textbf{bulbulia2015?}}). Yet there may be
non-social mechanisms at work as well, and in general, the intersection
of sex and religion remains under-examined (though see
\citeproc{ref-shaver2020church}{Shaver \emph{et al.} 2020},
\citeproc{ref-shaver2024religious}{2024};
\citeproc{ref-shaver2022integrating}{Shaver and White 2022}).

In conclusion, our results indicate that religious service attendance
can enhance certain facets of well-being, particularly meaning and
purpose, gratitude, and sexual satisfaction. These findings hold even in
a secular-majority country. However, we find little evidence of broad
effects on other well-being outcomes. Future research should focus on
fine-grained analyses of heterogeneity in these effects, explore
mechanistic pathways that explain how religius service affects
well-being, and remain mindful that individual experience often resists
sweeping generalisations, whether religious or otherwise, and that such
benefits, or the absence of such benefits, will not hold for everyone
equally.

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study. Members of the NZAVS management team and research
group hold full copies of the NZAVS data. A de-identified dataset
containing only the variables analysed in this manuscript is available
upon request from the corresponding author or any member of the NZAVS
advisory board for replication or checking of any published study using
NZAVS data. The code for the analysis can be found at:
\href{https://osf.io/wgtz4/}{OSF link}.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Plank Institute for the Science of Human History.
{[}\textbf{To be filled out for all authors}{]}. The funders had no role
in preparing the manuscript or deciding to publish it.

\subsubsection{Author Statement}\label{author-statement}

All authors had input into the manuscript. JB did the analysis and
developed the approach. CGS led data collection. JB, DD, CGS, KR, at GT
obtained funding.

\newpage{}

\subsection{Appendix A: Daily Data Collection}\label{appendix-timeline}

\newpage{}

\subsection{New Zealand Attitudes and Values Study Data Collection (2018
retained cohort)}\label{appendix-daily}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-church-wb-long_files/figure-pdf/fig-timeline-1.pdf}}

}

\caption{\label{fig-timeline}Historgram of New Zealand Attitudes and
Values Study Daily Data Collection: Time 11 - Time 15.}

\end{figure}%

\newpage{}

\subsection{Appendix B: Measures and Demographic
Statistics}\label{appendix-baseline}

\subsection{Measures}\label{measures}

\subsection{Baseline Variables}\label{baseline-variables}

\paragraph{Age}\label{age}

\emph{What is your date of birth?}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth''). Developed for the NZAVS.

\paragraph{Agreeableness}\label{agreeableness}

\begin{itemize}
\tightlist
\item
  I sympathize with others' feelings.
\item
  I am not interested in other people's problems.
\item
  I feel others' emotions.
\item
  I am not really interested in others (reversed).
\end{itemize}

Mini-IPIP6 Agreeableness dimension: (i) I sympathize with others'
feelings. (ii) I am not interested in other people's problems. (r) (iii)
I feel others' emotions. (iv) I am not really interested in others. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Alcohol Frequency}\label{alcohol-frequency}

\emph{``How often do you have a drink containing alcohol?''}

Participants could chose between the following responses: `(1 = Never -
I don't drink, 2 = Monthly or less, 3 = Up to 4 times a month, 4 = Up to
3 times a week, 5 = 4 or more times a week, 6 = Don't know)'
(\citeproc{ref-Ministry_of_Health_2013}{Health 2013})

\paragraph{Alcohol Intensity}\label{alcohol-intensity}

\emph{``How many drinks containing alcohol do you have on a typical day
when drinking alcohol? (number of drinks on a typical day when
drinking)''}

Participants responded using an open-ended box.
(\citeproc{ref-Ministry_of_Health_2013}{Health 2013})

\paragraph{Belong}\label{belong}

\begin{itemize}
\tightlist
\item
  Know that people in my life accept and value me.
\item
  Feel like an outsider (reversed).
\item
  Know that people around me share my attitudes and beliefs.
\end{itemize}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (Hagerty \& Patusky, 1995): (1) ``Know that
people in my life accept and value me''; (2) ``Feel like an outsider'';
(3) ``Know that people around me share my attitudes and beliefs''.
Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very
Accurate). The second item was reversely coded.
(\citeproc{ref-hagerty1995}{Hagerty and Patusky 1995})

\paragraph{Born in NZ}\label{born-in-nz}

**

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15). Developed for the NZAVS.

\paragraph{Conscientiousness}\label{conscientiousness}

\begin{itemize}
\tightlist
\item
  I get chores done right away.
\item
  I like order.
\item
  I make a mess of things.
\item
  I often forget to put things back in their proper place.
\end{itemize}

Mini-IPIP6 Conscientiousness dimension: (i) I get chores done right
away. (ii) I like order. (iii) I make a mess of things. (r) (iv) I often
forget to put things back in their proper place. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Education Level}\label{education-level}

\emph{What is your highest level of qualification?}

We asked participants, ``What is your highest level of qualification?''.
We coded participans highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school qualifications coded as Level 3, and all other ancillary
categories coded as missing) Developed for the NZAVS.

\paragraph{Employed (binary)}\label{employed-binary}

\emph{Are you currently employed (This includes self-employed of casual
work)?}

Binary response: (0 = No, 1 = Yes) Stats NZ Census Question

\paragraph{Ethnicity}\label{ethnicity}

\emph{Which ethnic group(s) do you belong to?}

Coded string: (1 = New Zealand European; 2 = Māori; 3 = Pacific; 4 =
Asian) NZ Census coding.

\paragraph{Extraversion}\label{extraversion}

\begin{itemize}
\tightlist
\item
  I am the life of the party.
\item
  I don't talk a lot (reversed).
\item
  I keep in the background (reversed).
\item
  I talk to a lot of different people at parties.
\end{itemize}

Mini-IPIP6 Extraversion dimension: (i) I am the life of the party. (ii)
I don't talk a lot. (r) (iii) I keep in the background. (r) (iv) I talk
to a lot of different people at parties.
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Hlth Disability Binary}\label{hlth-disability-binary}

**

We assessed disability with a one-item indicator adapted from Verbrugge
(1997). It asks, ``Do you have a health condition or disability that
limits you and that has lasted for 6+ months?'' (1 = Yes, 0 = No).
(\citeproc{ref-verbrugge1997}{Verbrugge 1997})

\paragraph{Honesty Humility}\label{honesty-humility}

\begin{itemize}
\tightlist
\item
  I feel entitled to more of everything (reversed).
\item
  I deserve more things in life (reversed).
\item
  I deserve more things in life (reversed).
\item
  I would get a lot of pleasure from owning expensive luxury goods
  (reversed).
\end{itemize}

Mini-IPIP6 Honesty-Humility dimension: (i) I feel entitled to more of
everything. (r) (ii) I deserve more things in life. (r) (iii) I would
like to be seen driving around in a very expensive car. (r) (iv) I would
get a lot of pleasure from owning expensive luxury goods. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Log Hours Children}\label{log-hours-children}

\emph{Hours spent\ldots looking after children.}

We took the natural log of the response + 1.
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Log Hours Commute}\label{log-hours-commute}

\emph{Hours spent\ldots travelling/commuting.}

We took the natural log of the response + 1. Developed for the NZAVS.

\paragraph{Log Hours Exercise}\label{log-hours-exercise}

\emph{Hours spent\ldots exercising/physical activity.}

We took the natural log of the response + 1.
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Log Hours Housework}\label{log-hours-housework}

\emph{Hours spent\ldots housework/cooking.}

We took the natural log of the response + 1.
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Log Household Income}\label{log-household-income}

\emph{Please estimate your total household income (before tax) for the
year XXXX.}

We took the natural log of the response + 1. Developed for the NZAVS.

\paragraph{Male (binary)}\label{male-binary}

**

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3 (Fraser et al.,
2020). (or 0.5 = neither female nor male). Here, we coded all those who
responded as Male as 1, and those who did not as 0.
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020})

\paragraph{Neuroticism}\label{neuroticism}

\begin{itemize}
\tightlist
\item
  I have frequent mood swings.
\item
  I am relaxed most of the time (reversed).
\item
  I get upset easily.
\item
  I seldom feel blue (reversed).
\end{itemize}

Mini-IPIP6 Neuroticism dimension: (i) I have frequent mood swings. (ii)
I am relaxed most of the time. (r) (iii) I get upset easily. (iv) I
seldom feel blue. (r) (\citeproc{ref-sibley2011}{Sibley \emph{et al.}
2011})

\paragraph{Not Heterosexual Binary}\label{not-heterosexual-binary}

\emph{How would you describe your sexual orientation? (e.g.,
heterosexual, homosexual, straight, gay, lesbian, bisexual, etc.)}

Open-ended question, coded as binary (not heterosexual = 1).
(\citeproc{ref-greaves2017diversity}{Greaves \emph{et al.} 2017})

\paragraph{NZ Deprevation Index 2018}\label{nz-deprevation-index-2018}

\emph{New Zealand Deprivation - Decile Index - Using 2018 Census Data}

Numerical: (1-10) (\citeproc{ref-atkinson2019}{Atkinson \emph{et al.}
2019})

\paragraph{NZSEI (Occupational Prestige
Index)}\label{nzsei-occupational-prestige-index}

**

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (Fahy et al., 2017). This index uses
the income, age, and education of a reference group, in this case, the
2013 New Zealand census, to calculate a score for each occupational
group. Scores range from 10 (Lowest) to 90 (Highest). This list of index
scores for occupational groups was used to assign each participant a
NZSEI-13 score based on their occupation. (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017})

\paragraph{Openness}\label{openness}

\begin{itemize}
\tightlist
\item
  I have a vivid imagination.
\item
  I have difficulty understanding abstract ideas (reversed).
\item
  I do not have a good imagination (reversed).
\item
  I am not interested in abstract ideas (reversed).
\end{itemize}

Mini-IPIP6 Openness to Experience dimension: (i) I have a vivid
imagination. (ii) I have difficulty understanding abstract ideas. (r)
(iii) I do not have a good imagination. (r) (iv) I am not interested in
abstract ideas. (r) (\citeproc{ref-sibley2011}{Sibley \emph{et al.}
2011})

\paragraph{Parent (binary)}\label{parent-binary}

**

We asked participants, ``If you are a parent, what is the birth date of
your eldest child?'' or ``If you are a parent, in which year was your
eldest child born?'' (waves: 10-current). Parents were coded as 1, while
the others were coded as 0. Developed for the NZAVS.

\paragraph{Partner Binary}\label{partner-binary}

\emph{What is your relationship status? (e.g., single, married,
de-facto, civil union, widowed, living together, etc.)}

Coded as binary (has partner = 1). Developed for the NZAVS.

\paragraph{Political Conservative}\label{political-conservative}

\emph{Please rate how politically liberal versus conservative you see
yourself as being.}

Ordinal response: (1 = Extremely Liberal, 7 = Extremely Conservative)
(\citeproc{ref-jost_end_2006-1}{Jost 2006})

\paragraph{Power No Control Composite}\label{power-no-control-composite}

\begin{itemize}
\tightlist
\item
  I do not have enough power or control over important parts of my life.
\item
  Other people have too much power or control over important parts of my
  life.
\end{itemize}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-overall2016power}{Overall \emph{et al.} 2016})

\paragraph{Rural Gch 2018 Levels}\label{rural-gch-2018-levels}

\emph{High Urban Accessibility = 1, Medium Urban Accessibility = 2, Low
Urban Accessibility = 3, Remote = 4, Very Remote = 5.}

``Participants residence locations were coded according to a five-level
ordinal categorisation ranging from Urban to Rural.''
(\citeproc{ref-whitehead2023unmasking}{Whitehead \emph{et al.} 2023})

\paragraph{Right Wing
Authoritarianism}\label{right-wing-authoritarianism}

\begin{itemize}
\tightlist
\item
  It is always better to trust the judgment of the proper authorities in
  government and religion than to listen to the noisy rabble-rousers in
  our society who are trying to create doubt in people's minds.
\item
  It would be best for everyone if the proper authorities censored
  magazines so that people could not get their hands on trashy and
  disgusting material.
\item
  Our country will be destroyed some day if we do not smash the
  perversions eating away at our moral fibre and traditional beliefs.
\item
  People should pay less attention to The Bible and other old
  traditional forms of religious guidance, and instead develop their own
  personal standards of what is moral and immoral.
\item
  Atheists and others who have rebelled against established religions
  are no doubt every bit as good and virtuous as those who attend church
  regularly.
\item
  Some of the best people in our country are those who are challenging
  our government, criticizing religion, and ignoring the ``normal way''
  things are supposed to be done (reversed).
\end{itemize}

(\citeproc{ref-altemeyer1996authoritarian}{Altemeyer 1996})

\paragraph{Sample Frame Opt-In
(binary)}\label{sample-frame-opt-in-binary}

\emph{Participant was not randomly sampled from the New Zealand
Electoral Roll.}

Code string (Binary): (0 = No, 1 = Yes) Developed for the NZAVS.

\paragraph{Social Dominance
Orientation}\label{social-dominance-orientation}

\begin{itemize}
\tightlist
\item
  It is OK if some groups have more of a chance in life than others.
\item
  Inferior groups should stay in their place.
\item
  To get ahead in life, it is sometimes okay to step on other groups.
\item
  We should have increased social equality (reversed).
\item
  It would be good if groups could be equal (reversed).
\item
  We should do what we can to equalise conditions for different groups
  (reversed).
\end{itemize}

(\citeproc{ref-sidanius1999social}{Sidanius and Pratto 1999})

\paragraph{Smoker (binary)}\label{smoker-binary}

\emph{Do you currently smoke tobacco cigarettes?}

Binary smoking indicator (0 = No, 1 = Yes). Developed for NZAVS.

\subsection{Exposure Variable}\label{exposure-variable}

\paragraph{Monthly Religious Service}\label{monthly-religious-service}

\emph{Do you identify with a religion and/or spiritual group?
-\textgreater{} How many times did you attend a church or place of
worship in the last month?}

Numerical: open-ended response (\citeproc{ref-sibley2012}{Sibley and
Bulbulia 2012})

\subsection{Outcome Variables}\label{outcome-variables}

\subsubsection{Health}\label{health-1}

\paragraph{BMI}\label{bmi-1}

\emph{What is your height? (metres)'' and ``What is your weight? (kg).}

Based on participants indication of their height and weight we
calculated the BMI by dividing the weight in kilograms by the square of
the height in meters. Developed for the NZAVS.

\paragraph{Sleep}\label{sleep}

\emph{During the past month, on average, how many hours of actual sleep
did you get per night?}

Open ended response. (\citeproc{ref-buysse1989pittsburgh}{Buysse
\emph{et al.} 1989})

\paragraph{Hours of Exercise (log)}\label{hours-of-exercise-log-1}

\emph{Hours spent\ldots exercising/physical activity.}

We took the natural log of the response + 1.
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011})

\paragraph{Short Form Health}\label{short-form-health}

\emph{In general, would you say your health is\ldots{}}

Ordinal response: (1 = Poor, 7 = Excellent)
(\citeproc{ref-instrument1992mos}{Instrument Ware Jr and Sherbourne
1992})

\subsubsection{Psychological}\label{psychological}

\paragraph{Fatigue}\label{fatigue}

\emph{During the last 30 days, how often did \ldots{} you feel
exhausted?}

Ordinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2=
Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time)
(\citeproc{ref-sibley2020}{Sibley \emph{et al.} 2020})

\paragraph{Anxiety}\label{anxiety}

\begin{itemize}
\tightlist
\item
  During the past 30 days, how often did\ldots you feel restless or
  fidgety?
\item
  During the past 30 days, how often did\ldots you feel that everything
  was an effort?
\item
  During the past 30 days, how often did\ldots you feel nervous?
\end{itemize}

Ordinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2=
Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time)
(\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002})

\paragraph{Depression}\label{depression-1}

\begin{itemize}
\tightlist
\item
  During the past 30 days, how often did\ldots you feel hopeless?
\item
  During the past 30 days, how often did\ldots you feel so depressed
  that nothing could cheer you up?
\item
  During the past 30 days, how often did\ldots you feel you feel
  restless or fidgety?
\end{itemize}

Ordinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2=
Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time)
(\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002})

\paragraph{Rumination}\label{rumination}

\emph{During the last 30 days, how often did\ldots you have negative
thoughts that repeated over and over?}

Ordinal responses: 0 = None of The Time, 1 = A little of The Time, 2 =
Some of The Time, 3 = Most of The Time, 4 = All of The Time.
(\citeproc{ref-nolen-hoeksema_effects_1993}{Nolen-hoeksema and Morrow
1993})

\subsubsection{Present Focused}\label{present-focused}

\paragraph{Bodysat}\label{bodysat}

\emph{I am satisfied with the appearance, size and shape of my body.}

Ordinal response scale (1 = Very inaccurate to 7 = Very accurate).
(\citeproc{ref-stronge2015facebook}{Stronge \emph{et al.} 2015})

\paragraph{Forgiveness}\label{forgiveness}

\begin{itemize}
\tightlist
\item
  Sometimes I can't sleep because of thinking about past wrongs I have
  suffered.
\item
  I can usually forgive and forget when someone does me wrong.
\item
  I find myself regularly thinking about past times that I have been
  wronged.
\end{itemize}

We assessed participants' forgiveness using reversed scores of a the
NZAVS ``vengeful rumination scale.'' This scale contains three items,
adapted from Caprara (\citeproc{ref-caprara_indicators_1986}{1986}) and
Berry \emph{et al.} (\citeproc{ref-berry_forgivingness_2005}{2005}), and
developed for NZAVS, ordinal response scale 1-7 (1 = Strongly Disagree
to 7 = Strongly Agree). Combines Berry \emph{et al.}
(\citeproc{ref-berry_forgivingness_2005}{2005}) and Caprara
(\citeproc{ref-caprara_indicators_1986}{1986}).

\paragraph{Perfectionism}\label{perfectionism}

\begin{itemize}
\tightlist
\item
  Doing my best never seems to be enough.
\item
  My performance rarely measures up to my standards.
\item
  I am hardly ever satisfied with my performance.
\end{itemize}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree).
(\citeproc{ref-rice_short_2014}{Rice \emph{et al.} 2014})

\paragraph{Pwb Standard Living}\label{pwb-standard-living-1}

\emph{Please rate your level of satisfaction with the following aspects
of your life\ldots Your standard of living.}

Ordinal response (0 = completely dissatisfied to 10 = completely
satisfied). (\citeproc{ref-cummins_developing_2003}{Cummins \emph{et
al.} 2003})

\paragraph{Pwb your Future Security}\label{pwb-your-future-security}

\emph{Please rate your level of satisfaction with the following aspects
of your life\ldots Your future security.}

Ordinal response (0 = completely dissatisfied to 10 = completely
satisfied). (\citeproc{ref-cummins_developing_2003}{Cummins \emph{et
al.} 2003})

\paragraph{Pwb your Health}\label{pwb-your-health}

\emph{Please rate your level of satisfaction with the following aspects
of your life\ldots Your health.}

Ordinal response (0 = completely dissatisfied to 10 = completely
satisfied). (\citeproc{ref-cummins_developing_2003}{Cummins \emph{et
al.} 2003})

\paragraph{Pwb your Relationships}\label{pwb-your-relationships}

\emph{Please rate your level of satisfaction with the following aspects
of your life\ldots Your personal relationships.}

Ordinal response (0 = completely dissatisfied to 10 = completely
satisfied). (\citeproc{ref-cummins_developing_2003}{Cummins \emph{et
al.} 2003})

\paragraph{Self Control Have Lots}\label{self-control-have-lots}

\emph{In general, I have a lot of self-control.}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree).
(\citeproc{ref-tangney_high_2004}{Tangney \emph{et al.} 2004})

\paragraph{Self Control Wish more
Reversed}\label{self-control-wish-more-reversed}

\emph{I wish I had more self-discipline.}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree).
(\citeproc{ref-tangney_high_2004}{Tangney \emph{et al.} 2004})

\paragraph{Self Esteem}\label{self-esteem}

\begin{itemize}
\tightlist
\item
  On the whole am satisfied with myself.
\item
  Take a positive attitude toward myself.
\item
  Am inclined to feel that I am a failure (reversed).
\end{itemize}

Ordinal response (1 = Very inaccurate to 7 = Very accurate).
(\citeproc{ref-Rosenberg1965}{Rosenberg 1965})

\paragraph{Sexual Satisfaction}\label{sexual-satisfaction-1}

\emph{How satisfied are you with your sex life?}

Participants were asked to report their sexual orientation; ordinal
response: 1 = Not satisfied to 7 = Very satisfied. Developed for the
NZAVS

\subsubsection{Life Focused}\label{life-focused}

\paragraph{Gratitude}\label{gratitude-1}

\begin{itemize}
\tightlist
\item
  I have much in my life to be thankful for.
\item
  When I look at the world, I don't see much to be grateful for
  (reversed).
\item
  I am grateful to a wide variety of people.
\end{itemize}

Ordinal response scale 1 = Strongly Disagree to 7 = Strongly Agree.
(\citeproc{ref-mccullough_grateful_2002}{McCullough \emph{et al.} 2002})

\paragraph{Lifesat}\label{lifesat}

\begin{itemize}
\tightlist
\item
  I am satisfied with my life.
\item
  In most ways my life is close to ideal.
\end{itemize}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree).
(\citeproc{ref-diener1985a}{Diener \emph{et al.} 1985})

\paragraph{Meaning Purpose}\label{meaning-purpose-1}

\emph{My life has a clear sense of purpose}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree).
(\citeproc{ref-steger_meaning_2006}{Steger \emph{et al.} 2006})

\paragraph{Meaning Sense}\label{meaning-sense-1}

\emph{I have a good sense of what makes my life meaningful.}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree).
(\citeproc{ref-steger_meaning_2006}{Steger \emph{et al.} 2006})

\subsubsection{Social}\label{social}

\paragraph{Belonging}\label{belonging-1}

\begin{itemize}
\tightlist
\item
  Know that people in my life accept and value me.
\item
  Feel like an outsider (reversed).
\item
  Know that people around me share my attitudes and beliefs.
\end{itemize}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (Hagerty \& Patusky, 1995): (1) ``Know that
people in my life accept and value me''; (2) ``Feel like an outsider'';
(3) ``Know that people around me share my attitudes and beliefs''.
Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very
Accurate). The second item was reversely coded.
(\citeproc{ref-hagerty1995}{Hagerty and Patusky 1995})

\paragraph{Community Belonging}\label{community-belonging}

\emph{I feel a sense of community with others in my local
neighbourhood.}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree).
(\citeproc{ref-sengupta2013}{Sengupta \emph{et al.} 2013})

\paragraph{Support}\label{support}

\begin{itemize}
\tightlist
\item
  There are people I can depend on to help me if I really need it.
\item
  There is no one I can turn to for guidance in times of stress
  (reversed).
\item
  I know there are people I can turn to when I need help.
\end{itemize}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-cutrona1987}{Cutrona and Russell 1987})

\subsubsection{Sample Demographic
Statistics}\label{sample-demographic-statistics}

\begingroup\fontsize{6}{8}\selectfont
\begingroup\fontsize{6}{8}\selectfont

\begin{longtable}[t]{lllllll}

\caption{\label{tbl-baseline}Demographic statistics for New Zealand
Attitudes and Values Cohort waves 2018.}

\tabularnewline

\toprule
  & 2018 & 2019 & 2020 & 2021 & 2022 & 2023\\
\midrule
\endfirsthead
\multicolumn{7}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2018 & 2019 & 2020 & 2021 & 2022 & 2023\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Age}}\\
\hspace{1em}Mean (SD) & 48.6 (13.9) & 51.2 (13.5) & 52.7 (13.4) & 54.0 (13.3) & 55.4 (13.2) & 56.4 (13.1)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{51.0 [18.0, 99.0]} & \cellcolor{gray!10}{54.0 [19.0, 96.0]} & \cellcolor{gray!10}{55.0 [20.0, 96.0]} & \cellcolor{gray!10}{57.0 [21.0, 97.0]} & \cellcolor{gray!10}{58.0 [22.0, 98.0]} & \cellcolor{gray!10}{59.0 [23.0, 99.0]}\\
\hspace{1em}Missing & 0 (0\%) & 12422 (26.8\%) & 15053 (32.5\%) & 19456 (42.0\%) & 22677 (48.9\%) & 25006 (53.9\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Agreeableness}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.35 (0.988)} & \cellcolor{gray!10}{5.37 (0.972)} & \cellcolor{gray!10}{5.37 (0.977)} & \cellcolor{gray!10}{5.35 (1.00)} & \cellcolor{gray!10}{5.33 (0.993)} & \cellcolor{gray!10}{5.33 (0.998)}\\
\hspace{1em}Median [Min, Max] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{400 (0.9\%)} & \cellcolor{gray!10}{12705 (27.4\%)} & \cellcolor{gray!10}{15266 (32.9\%)} & \cellcolor{gray!10}{19657 (42.4\%)} & \cellcolor{gray!10}{22777 (49.1\%)} & \cellcolor{gray!10}{25054 (54.0\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Alcohol Frequency}}\\
\hspace{1em}Mean (SD) & 2.16 (1.34) & 2.17 (1.35) & 2.18 (1.35) & 2.13 (1.38) & 2.10 (1.37) & 2.04 (1.36)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{2.00 [0, 5.00]} & \cellcolor{gray!10}{2.00 [0, 5.00]} & \cellcolor{gray!10}{2.00 [0, 5.00]} & \cellcolor{gray!10}{2.00 [0, 5.00]} & \cellcolor{gray!10}{2.00 [0, 5.00]} & \cellcolor{gray!10}{2.00 [0, 5.00]}\\
\hspace{1em}Missing & 1598 (3.4\%) & 13069 (28.2\%) & 15644 (33.7\%) & 19841 (42.8\%) & 22832 (49.2\%) & 25538 (55.1\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Alcohol Intensity}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{2.17 (2.17)} & \cellcolor{gray!10}{2.00 (1.99)} & \cellcolor{gray!10}{1.97 (1.98)} & \cellcolor{gray!10}{1.88 (1.85)} & \cellcolor{gray!10}{1.86 (1.86)} & \cellcolor{gray!10}{2.00 (1.89)}\\
\hspace{1em}Median [Min, Max] & 2.00 [0, 30.0] & 2.00 [0, 36.0] & 2.00 [0, 36.0] & 2.00 [0, 32.0] & 1.50 [0, 40.0] & 2.00 [0, 48.0]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{2751 (5.9\%)} & \cellcolor{gray!10}{13816 (29.8\%)} & \cellcolor{gray!10}{16302 (35.2\%)} & \cellcolor{gray!10}{20437 (44.1\%)} & \cellcolor{gray!10}{23607 (50.9\%)} & \cellcolor{gray!10}{27939 (60.2\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Belong}}\\
\hspace{1em}Mean (SD) & 5.14 (1.08) & 5.13 (1.07) & 5.05 (1.09) & 5.16 (1.10) & 5.16 (1.10) & 5.23 (1.10)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]}\\
\hspace{1em}Missing & 397 (0.9\%) & 12704 (27.4\%) & 15274 (32.9\%) & 19702 (42.5\%) & 22810 (49.2\%) & 25100 (54.1\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Born in NZ}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.783 (0.412)} & \cellcolor{gray!10}{0.783 (0.412)} & \cellcolor{gray!10}{0.783 (0.412)} & \cellcolor{gray!10}{0.783 (0.412)} & \cellcolor{gray!10}{0.783 (0.412)} & \cellcolor{gray!10}{0.783 (0.412)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, \vphantom{3} 1.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{152 (0.3\%)} & \cellcolor{gray!10}{152 (0.3\%)} & \cellcolor{gray!10}{152 (0.3\%)} & \cellcolor{gray!10}{152 (0.3\%)} & \cellcolor{gray!10}{152 (0.3\%)} & \cellcolor{gray!10}{152 (0.3\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Conscientiousness}}\\
\hspace{1em}Mean (SD) & 5.11 (1.06) & 5.13 (1.04) & 5.14 (1.03) & 5.15 (1.05) & 5.16 (1.04) & 5.16 (1.04)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]} & \cellcolor{gray!10}{5.25 [1.00, 7.00]}\\
\hspace{1em}Missing & 392 (0.8\%) & 12702 (27.4\%) & 15265 (32.9\%) & 19657 (42.4\%) & 22774 (49.1\%) & 25079 (54.1\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Education Level}}\\
\cellcolor{gray!10}{\hspace{1em}no\_qualification} & \cellcolor{gray!10}{1177 (2.5\%)} & \cellcolor{gray!10}{1044 (2.3\%)} & \cellcolor{gray!10}{956 (2.1\%)} & \cellcolor{gray!10}{916 (2.0\%)} & \cellcolor{gray!10}{900 (1.9\%)} & \cellcolor{gray!10}{881 (1.9\%)}\\
\hspace{1em}cert\_1\_to\_4 & 16277 (35.1\%) & 15353 (33.1\%) & 14813 (31.9\%) & 14465 (31.2\%) & 14214 (30.6\%) & 14037 (30.3\%)\\
\cellcolor{gray!10}{\hspace{1em}cert\_5\_to\_6} & \cellcolor{gray!10}{5821 (12.6\%)} & \cellcolor{gray!10}{6016 (13.0\%)} & \cellcolor{gray!10}{6116 (13.2\%)} & \cellcolor{gray!10}{6151 (13.3\%)} & \cellcolor{gray!10}{6206 (13.4\%)} & \cellcolor{gray!10}{6209 (13.4\%)}\\
\hspace{1em}university & 12311 (26.5\%) & 12529 (27.0\%) & 12585 (27.1\%) & 12572 (27.1\%) & 12495 (26.9\%) & 12448 (26.8\%)\\
\cellcolor{gray!10}{\hspace{1em}post\_grad} & \cellcolor{gray!10}{5034 (10.9\%)} & \cellcolor{gray!10}{5376 (11.6\%)} & \cellcolor{gray!10}{5655 (12.2\%)} & \cellcolor{gray!10}{5881 (12.7\%)} & \cellcolor{gray!10}{6042 (13.0\%)} & \cellcolor{gray!10}{6098 (13.1\%)}\\
\hspace{1em}masters & 3857 (8.3\%) & 4088 (8.8\%) & 4262 (9.2\%) & 4386 (9.5\%) & 4504 (9.7\%) & 4601 (9.9\%)\\
\cellcolor{gray!10}{\hspace{1em}doctorate} & \cellcolor{gray!10}{1111 (2.4\%)} & \cellcolor{gray!10}{1182 (2.5\%)} & \cellcolor{gray!10}{1227 (2.6\%)} & \cellcolor{gray!10}{1268 (2.7\%)} & \cellcolor{gray!10}{1314 (2.8\%)} & \cellcolor{gray!10}{1414 (3.0\%)}\\
\hspace{1em}Missing & 789 (1.7\%) & 789 (1.7\%) & 763 (1.6\%) & 738 (1.6\%) & 702 (1.5\%) & 689 (1.5\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Employed (binary)}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.795 (0.404)} & \cellcolor{gray!10}{0.774 (0.418)} & \cellcolor{gray!10}{0.779 (0.415)} & \cellcolor{gray!10}{0.758 (0.428)} & \cellcolor{gray!10}{0.722 (0.448)} & \cellcolor{gray!10}{0.709 (0.454)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, \vphantom{2} 1.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{11 (0.0\%)} & \cellcolor{gray!10}{12693 (27.4\%)} & \cellcolor{gray!10}{15206 (32.8\%)} & \cellcolor{gray!10}{19586 (42.2\%)} & \cellcolor{gray!10}{22816 (49.2\%)} & \cellcolor{gray!10}{25540 (55.1\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Ethnicity}}\\
\hspace{1em}euro & 36915 (79.6\%) & 36915 (79.6\%) & 36915 (79.6\%) & 36915 (79.6\%) & 36915 (79.6\%) & 36915 (79.6\%)\\
\cellcolor{gray!10}{\hspace{1em}maori} & \cellcolor{gray!10}{5311 (11.5\%)} & \cellcolor{gray!10}{5311 (11.5\%)} & \cellcolor{gray!10}{5311 (11.5\%)} & \cellcolor{gray!10}{5311 (11.5\%)} & \cellcolor{gray!10}{5311 (11.5\%)} & \cellcolor{gray!10}{5311 (11.5\%)}\\
\hspace{1em}pacific & 1109 (2.4\%) & 1109 (2.4\%) & 1109 (2.4\%) & 1109 (2.4\%) & 1109 (2.4\%) & 1109 (2.4\%)\\
\cellcolor{gray!10}{\hspace{1em}asian} & \cellcolor{gray!10}{2453 (5.3\%)} & \cellcolor{gray!10}{2453 (5.3\%)} & \cellcolor{gray!10}{2453 (5.3\%)} & \cellcolor{gray!10}{2453 (5.3\%)} & \cellcolor{gray!10}{2453 (5.3\%)} & \cellcolor{gray!10}{2453 (5.3\%)}\\
\hspace{1em}Missing & 589 (1.3\%) & 589 (1.3\%) & 589 (1.3\%) & 589 (1.3\%) & 589 (1.3\%) & 589 (1.3\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Extraversion}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{3.91 (1.20)} & \cellcolor{gray!10}{3.85 (1.19)} & \cellcolor{gray!10}{3.82 (1.19)} & \cellcolor{gray!10}{3.77 (1.23)} & \cellcolor{gray!10}{3.75 (1.23)} & \cellcolor{gray!10}{3.75 (1.23)}\\
\hspace{1em}Median [Min, Max] & 4.00 [1.00, 7.00] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00] & 3.75 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{392 (0.8\%)} & \cellcolor{gray!10}{12703 (27.4\%)} & \cellcolor{gray!10}{15263 (32.9\%)} & \cellcolor{gray!10}{19659 (42.4\%)} & \cellcolor{gray!10}{22783 (49.1\%)} & \cellcolor{gray!10}{25067 (54.1\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Hlth Disability Binary}}\\
\hspace{1em}Mean (SD) & 0.225 (0.418) & 0.234 (0.423) & 0.263 (0.440) & 0.276 (0.447) & 0.311 (0.463) & 0.321 (0.467)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, \vphantom{4} 1.00]}\\
\hspace{1em}Missing & 893 (1.9\%) & 12912 (27.8\%) & 15526 (33.5\%) & 19848 (42.8\%) & 23135 (49.9\%) & 25268 (54.5\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Honesty Humility}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.41 (1.18)} & \cellcolor{gray!10}{5.55 (1.14)} & \cellcolor{gray!10}{5.59 (1.13)} & \cellcolor{gray!10}{5.65 (1.13)} & \cellcolor{gray!10}{5.69 (1.13)} & \cellcolor{gray!10}{5.71 (1.12)}\\
\hspace{1em}Median [Min, Max] & 5.50 [1.00, 7.00] & 5.75 [1.00, 7.00] & 5.75 [1.00, 7.00] & 5.75 [1.00, 7.00] & 6.00 [1.00, 7.00] & 6.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{396 (0.9\%)} & \cellcolor{gray!10}{12705 (27.4\%)} & \cellcolor{gray!10}{15274 (32.9\%)} & \cellcolor{gray!10}{19640 (42.3\%)} & \cellcolor{gray!10}{22767 (49.1\%)} & \cellcolor{gray!10}{25049 (54.0\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Hours Children}}\\
\hspace{1em}Mean (SD) & 14.0 (32.3) & 12.9 (31.1) & 11.9 (30.0) & 10.4 (27.4) & 10.1 (27.0) & 9.97 (26.8)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0 [0, 168]} & \cellcolor{gray!10}{0 [0, 168]} & \cellcolor{gray!10}{0 [0, 168]} & \cellcolor{gray!10}{0 [0, 168]} & \cellcolor{gray!10}{0 [0, 168]} & \cellcolor{gray!10}{0 [0, 168]}\\
\hspace{1em}Missing & 1442 (3.1\%) & 13105 (28.3\%) & 15860 (34.2\%) & 20348 (43.9\%) & 23539 (50.8\%) & 25903 \vphantom{1} (55.9\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Hours Commute}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.29 (6.40)} & \cellcolor{gray!10}{4.88 (7.10)} & \cellcolor{gray!10}{4.48 (5.91)} & \cellcolor{gray!10}{3.80 (5.49)} & \cellcolor{gray!10}{4.52 (6.17)} & \cellcolor{gray!10}{4.62 (6.36)}\\
\hspace{1em}Median [Min, Max] & 4.00 [0, 80.0] & 3.00 [0, 168] & 3.00 [0, 100] & 2.00 [0, 100] & 3.00 [0, 100] & 3.00 [0, 100]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{1442 (3.1\%)} & \cellcolor{gray!10}{13104 (28.3\%)} & \cellcolor{gray!10}{15860 (34.2\%)} & \cellcolor{gray!10}{20338 (43.9\%)} & \cellcolor{gray!10}{23533 (50.7\%)} & \cellcolor{gray!10}{25897 \vphantom{1} (55.8\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Hours Exercise}}\\
\hspace{1em}Mean (SD) & 5.78 (7.70) & 6.21 (8.21) & 6.17 (7.44) & 6.20 (7.04) & 6.19 (7.12) & 6.42 (7.29)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{4.00 [0, 80.0]} & \cellcolor{gray!10}{4.00 [0, 168]} & \cellcolor{gray!10}{5.00 [0, 80.0]} & \cellcolor{gray!10}{5.00 [0, 85.0]} & \cellcolor{gray!10}{5.00 [0, 80.0]} & \cellcolor{gray!10}{5.00 [0, 80.0]}\\
\hspace{1em}Missing & 1442 (3.1\%) & 13106 (28.3\%) & 15860 (34.2\%) & 20338 (43.9\%) & 23536 (50.7\%) & 25897 \vphantom{1} (55.8\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Hours Housework}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{10.3 (10.1)} & \cellcolor{gray!10}{10.3 (9.24)} & \cellcolor{gray!10}{10.8 (9.95)} & \cellcolor{gray!10}{10.8 (9.31)} & \cellcolor{gray!10}{10.9 (9.33)} & \cellcolor{gray!10}{11.0 (8.96)}\\
\hspace{1em}Median [Min, Max] & 8.00 [0, 168] & 8.00 [0, 168] & 10.0 [0, 168] & 10.0 [0, 168] & 10.0 [0, 168] & 10.0 [0, 168]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{1442 (3.1\%)} & \cellcolor{gray!10}{13104 (28.3\%)} & \cellcolor{gray!10}{15860 (34.2\%)} & \cellcolor{gray!10}{20338 (43.9\%)} & \cellcolor{gray!10}{23532 (50.7\%)} & \cellcolor{gray!10}{25896 \vphantom{1} (55.8\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Household Income}}\\
\hspace{1em}Mean (SD) & 115000 (92100) & 120000 (110000) & 123000 (107000) & 127000 (113000) & 134000 (148000) & 136000 (125000)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{100000 [1.00, 3010000]} & \cellcolor{gray!10}{100000 [1.00, 4000000]} & \cellcolor{gray!10}{100000 [1.00, 3000000]} & \cellcolor{gray!10}{100000 [1.00, 3500000]} & \cellcolor{gray!10}{100000 [1000, 7500000]} & \cellcolor{gray!10}{110000 [0, 5000000]}\\
\hspace{1em}Missing & 2940 (6.3\%) & 13806 (29.8\%) & 15874 (34.2\%) & 20174 (43.5\%) & 23113 (49.8\%) & 25824 \vphantom{1} (55.7\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Log Hours Children}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{1.16 (1.61)} & \cellcolor{gray!10}{1.08 (1.58)} & \cellcolor{gray!10}{1.02 (1.54)} & \cellcolor{gray!10}{0.952 (1.48)} & \cellcolor{gray!10}{0.934 (1.47)} & \cellcolor{gray!10}{0.936 (1.46)}\\
\hspace{1em}Median [Min, Max] & 0 [0, 5.13] & 0 [0, 5.13] & 0 [0, 5.13] & 0 [0, 5.13] & 0 [0, 5.13] & 0 [0, 5.13]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{1442 (3.1\%)} & \cellcolor{gray!10}{13105 (28.3\%)} & \cellcolor{gray!10}{15860 (34.2\%)} & \cellcolor{gray!10}{20348 (43.9\%)} & \cellcolor{gray!10}{23539 (50.8\%)} & \cellcolor{gray!10}{25903 (55.9\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Log Hours Commute}}\\
\hspace{1em}Mean (SD) & 1.50 (0.834) & 1.40 (0.860) & 1.34 (0.863) & 1.19 (0.853) & 1.34 (0.858) & 1.36 (0.851)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{1.61 [0, 4.39]} & \cellcolor{gray!10}{1.39 [0, 5.13]} & \cellcolor{gray!10}{1.39 [0, 4.62]} & \cellcolor{gray!10}{1.10 [0, 4.62]} & \cellcolor{gray!10}{1.39 [0, 4.62]} & \cellcolor{gray!10}{1.39 [0, 4.62]}\\
\hspace{1em}Missing & 1442 (3.1\%) & 13104 (28.3\%) & 15860 (34.2\%) & 20338 (43.9\%) & 23533 (50.7\%) & 25897 (55.8\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Log Hours Exercise}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{1.54 (0.848)} & \cellcolor{gray!10}{1.63 (0.826)} & \cellcolor{gray!10}{1.62 (0.839)} & \cellcolor{gray!10}{1.64 (0.833)} & \cellcolor{gray!10}{1.63 (0.838)} & \cellcolor{gray!10}{1.67 (0.830)}\\
\hspace{1em}Median [Min, Max] & 1.61 [0, 4.39] & 1.61 [0, 5.13] & 1.79 [0, 4.39] & 1.79 [0, 4.45] & 1.79 [0, 4.39] & 1.79 [0, 4.39]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{1442 (3.1\%)} & \cellcolor{gray!10}{13106 (28.3\%)} & \cellcolor{gray!10}{15860 (34.2\%)} & \cellcolor{gray!10}{20338 (43.9\%)} & \cellcolor{gray!10}{23536 (50.7\%)} & \cellcolor{gray!10}{25897 (55.8\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Log Hours Housework}}\\
\hspace{1em}Mean (SD) & 2.14 (0.781) & 2.16 (0.756) & 2.21 (0.754) & 2.22 (0.735) & 2.23 (0.751) & 2.24 (0.739)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{2.20 [0, 5.13]} & \cellcolor{gray!10}{2.20 [0, 5.13]} & \cellcolor{gray!10}{2.40 [0, 5.13]} & \cellcolor{gray!10}{2.40 [0, 5.13]} & \cellcolor{gray!10}{2.40 [0, 5.13]} & \cellcolor{gray!10}{2.40 [0, 5.13]}\\
\hspace{1em}Missing & 1442 (3.1\%) & 13104 (28.3\%) & 15860 (34.2\%) & 20338 (43.9\%) & 23532 (50.7\%) & 25896 (55.8\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Log Household Income}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{11.4 (0.768)} & \cellcolor{gray!10}{11.4 (0.851)} & \cellcolor{gray!10}{11.4 (0.807)} & \cellcolor{gray!10}{11.5 (0.826)} & \cellcolor{gray!10}{11.5 (0.789)} & \cellcolor{gray!10}{11.5 (0.975)}\\
\hspace{1em}Median [Min, Max] & 11.5 [0.693, 14.9] & 11.5 [0.693, 15.2] & 11.5 [0.693, 14.9] & 11.5 [0.693, 15.1] & 11.5 [6.91, 15.8] & 11.6 [0, 15.4]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{2940 (6.3\%)} & \cellcolor{gray!10}{13806 (29.8\%)} & \cellcolor{gray!10}{15874 (34.2\%)} & \cellcolor{gray!10}{20174 (43.5\%)} & \cellcolor{gray!10}{23113 (49.8\%)} & \cellcolor{gray!10}{25824 (55.7\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Male (binary)}}\\
\hspace{1em}Mean (SD) & 0.371 (0.483) & 0.363 (0.481) & 0.363 (0.481) & 0.359 (0.480) & 0.365 (0.482) & 0.364 (0.481)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, \vphantom{3} 1.00]}\\
\hspace{1em}Missing & 108 (0.2\%) & 12532 (27.0\%) & 15178 (32.7\%) & 19585 (42.2\%) & 22778 (49.1\%) & 25122 (54.2\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Neuroticism}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{3.49 (1.15)} & \cellcolor{gray!10}{3.48 (1.16)} & \cellcolor{gray!10}{3.45 (1.15)} & \cellcolor{gray!10}{3.41 (1.18)} & \cellcolor{gray!10}{3.36 (1.16)} & \cellcolor{gray!10}{3.33 (1.17)}\\
\hspace{1em}Median [Min, Max] & 3.50 [1.00, 7.00] & 3.50 [1.00, 7.00] & 3.50 [1.00, 7.00] & 3.25 [1.00, 7.00] & 3.25 [1.00, 7.00] & 3.25 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{402 (0.9\%)} & \cellcolor{gray!10}{12704 (27.4\%)} & \cellcolor{gray!10}{15267 (32.9\%)} & \cellcolor{gray!10}{19651 (42.4\%)} & \cellcolor{gray!10}{22778 (49.1\%)} & \cellcolor{gray!10}{25057 (54.0\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Not Heterosexual Binary}}\\
\hspace{1em}Mean (SD) & 0.0672 (0.250) & 0.0717 (0.258) & 0.0765 (0.266) & 0.0789 (0.270) & 0.0775 (0.267) & 0.0801 (0.271)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, \vphantom{2} 1.00]}\\
\hspace{1em}Missing & 1175 (2.5\%) & 12747 (27.5\%) & 15417 (33.2\%) & 19585 (42.2\%) & 22903 (49.4\%) & 25172 (54.3\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{NZ Deprevation Index 2018}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{4.77 (2.73)} & \cellcolor{gray!10}{4.77 (2.74)} & \cellcolor{gray!10}{4.77 (2.75)} & \cellcolor{gray!10}{4.77 (2.75)} & \cellcolor{gray!10}{4.77 (2.75)} & \cellcolor{gray!10}{4.76 (2.76)}\\
\hspace{1em}Median [Min, Max] & 4.00 [1.00, 10.0] & 4.00 [1.00, 10.0] & 4.00 [1.00, 10.0] & 4.00 [1.00, 10.0] & 4.00 [1.00, 10.0] & 4.00 [1.00, 10.0]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{308 (0.7\%)} & \cellcolor{gray!10}{469 (1.0\%)} & \cellcolor{gray!10}{595 (1.3\%)} & \cellcolor{gray!10}{940 (2.0\%)} & \cellcolor{gray!10}{881 (1.9\%)} & \cellcolor{gray!10}{966 (2.1\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{NZSEI (Occupational Prestige Index)}}\\
\hspace{1em}Mean (SD) & 54.1 (16.5) & 55.1 (16.4) & 55.2 (16.7) & 55.7 (16.6) & 56.1 (15.9) & 56.0 (16.2)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{54.0 [10.0, 90.0]} & \cellcolor{gray!10}{57.0 [10.0, 90.0]} & \cellcolor{gray!10}{57.0 [10.0, 90.0]} & \cellcolor{gray!10}{60.0 [10.0, 90.0]} & \cellcolor{gray!10}{60.0 [10.0, 90.0]} & \cellcolor{gray!10}{60.0 [10.0, 90.0]}\\
\hspace{1em}Missing & 346 (0.7\%) & 4220 (9.1\%) & 5184 (11.2\%) & 6236 (13.4\%) & 7752 (16.7\%) & 9063 (19.5\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Openness}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{4.96 (1.12)} & \cellcolor{gray!10}{4.96 (1.12)} & \cellcolor{gray!10}{4.96 (1.11)} & \cellcolor{gray!10}{4.96 (1.14)} & \cellcolor{gray!10}{4.95 (1.14)} & \cellcolor{gray!10}{4.96 (1.16)}\\
\hspace{1em}Median [Min, Max] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{394 (0.8\%)} & \cellcolor{gray!10}{12704 (27.4\%)} & \cellcolor{gray!10}{15266 (32.9\%)} & \cellcolor{gray!10}{19651 (42.4\%)} & \cellcolor{gray!10}{22774 (49.1\%)} & \cellcolor{gray!10}{25072 (54.1\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Parent (binary)}}\\
\hspace{1em}Mean (SD) & 0.708 (0.455) & 0.736 (0.441) & 0.748 (0.434) & 0.747 (0.434) & 0.767 (0.423) & 0.767 (0.423)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, 1.00]} & \cellcolor{gray!10}{1.00 [0, \vphantom{1} 1.00]}\\
\hspace{1em}Missing & 0 (0\%) & 12422 (26.8\%) & 15053 (32.5\%) & 19494 (42.0\%) & 22677 (48.9\%) & 25006 (53.9\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Partner Binary}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.750 (0.433)} & \cellcolor{gray!10}{0.761 (0.426)} & \cellcolor{gray!10}{0.761 (0.426)} & \cellcolor{gray!10}{0.761 (0.427)} & \cellcolor{gray!10}{0.755 (0.430)} & \cellcolor{gray!10}{0.750 (0.433)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00] & 1.00 [0, 1.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{535 (1.2\%)} & \cellcolor{gray!10}{13004 (28.0\%)} & \cellcolor{gray!10}{15471 (33.4\%)} & \cellcolor{gray!10}{20013 (43.2\%)} & \cellcolor{gray!10}{23312 (50.3\%)} & \cellcolor{gray!10}{25651 (55.3\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Political Conservative}}\\
\hspace{1em}Mean (SD) & 3.59 (1.38) & 3.58 (1.39) & 3.47 (1.35) & 3.53 (1.34) & 3.61 (1.38) & 3.57 (1.40)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]}\\
\hspace{1em}Missing & 1902 (4.1\%) & 13491 (29.1\%) & 16285 (35.1\%) & 20637 (44.5\%) & 23810 (51.3\%) & 26087 (56.2\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Power No Control Composite}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{2.97 (1.41)} & \cellcolor{gray!10}{2.96 (1.43)} & \cellcolor{gray!10}{2.78 (1.40)} & \cellcolor{gray!10}{2.85 (1.43)} & \cellcolor{gray!10}{NA (NA)} & \cellcolor{gray!10}{NA (NA)}\\
\hspace{1em}Median [Min, Max] & 3.00 [1.00, 7.00] & 3.00 [1.00, 7.00] & 2.50 [1.00, 7.00] & 2.50 [1.00, 7.00] & NA [NA, NA] & NA [NA, NA]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{220 (0.5\%)} & \cellcolor{gray!10}{12632 (27.2\%)} & \cellcolor{gray!10}{15131 (32.6\%)} & \cellcolor{gray!10}{19999 (43.1\%)} & \cellcolor{gray!10}{46377 (100\%)} & \cellcolor{gray!10}{46377 (100\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Rural Gch 2018 Levels}}\\
\hspace{1em}High Urban Accessibility & 28607 (61.7\%) & 28312 (61.0\%) & 28008 (60.4\%) & 27584 (59.5\%) & 27501 (59.3\%) & 27306 (58.9\%)\\
\cellcolor{gray!10}{\hspace{1em}Medium Urban Accessibility} & \cellcolor{gray!10}{8695 (18.7\%)} & \cellcolor{gray!10}{8731 (18.8\%)} & \cellcolor{gray!10}{8788 (18.9\%)} & \cellcolor{gray!10}{8776 (18.9\%)} & \cellcolor{gray!10}{8812 (19.0\%)} & \cellcolor{gray!10}{8858 (19.1\%)}\\
\hspace{1em}Low Urban Accessibility & 5639 (12.2\%) & 5711 (12.3\%) & 5811 (12.5\%) & 5861 (12.6\%) & 5896 (12.7\%) & 5915 (12.8\%)\\
\cellcolor{gray!10}{\hspace{1em}Remote} & \cellcolor{gray!10}{2581 (5.6\%)} & \cellcolor{gray!10}{2608 (5.6\%)} & \cellcolor{gray!10}{2658 (5.7\%)} & \cellcolor{gray!10}{2680 (5.8\%)} & \cellcolor{gray!10}{2738 (5.9\%)} & \cellcolor{gray!10}{2777 (6.0\%)}\\
\hspace{1em}Very Remote & 549 (1.2\%) & 548 (1.2\%) & 559 (1.2\%) & 540 (1.2\%) & 552 (1.2\%) & 558 (1.2\%)\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{306 (0.7\%)} & \cellcolor{gray!10}{467 (1.0\%)} & \cellcolor{gray!10}{553 (1.2\%)} & \cellcolor{gray!10}{936 (2.0\%)} & \cellcolor{gray!10}{878 (1.9\%)} & \cellcolor{gray!10}{963 (2.1\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Right Wing Authoritarianism}}\\
\hspace{1em}Mean (SD) & 3.28 (1.15) & 3.20 (1.14) & 3.30 (1.10) & 3.36 (1.05) & 3.35 (1.07) & 3.27 (1.10)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{3.20 [1.00, 7.00]} & \cellcolor{gray!10}{3.17 [1.00, 7.00]} & \cellcolor{gray!10}{3.17 [1.00, 7.00]} & \cellcolor{gray!10}{3.33 [1.00, 7.00]} & \cellcolor{gray!10}{3.33 [1.00, 7.00]} & \cellcolor{gray!10}{3.20 [1.00, 7.00]}\\
\hspace{1em}Missing & 7 (0.0\%) & 12459 (26.9\%) & 15106 (32.6\%) & 19609 (42.3\%) & 22730 (49.0\%) & 25084 (54.1\%)\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Sample Frame Opt-In (binary)}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.0297 (0.170)} & \cellcolor{gray!10}{0.0297 (0.170)} & \cellcolor{gray!10}{0.0297 (0.170)} & \cellcolor{gray!10}{0.0297 (0.170)} & \cellcolor{gray!10}{0.0297 (0.170)} & \cellcolor{gray!10}{0.0297 (0.170)}\\
\hspace{1em}Median [Min, Max] & 0 [0, 1.00] & 0 [0, 1.00] & 0 [0, 1.00] & 0 [0, 1.00] & 0 [0, 1.00] & 0 [0, \vphantom{1} 1.00]\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Social Dominance Orientation}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{2.32 (0.961)} & \cellcolor{gray!10}{2.25 (0.950)} & \cellcolor{gray!10}{2.21 (0.945)} & \cellcolor{gray!10}{2.22 (0.944)} & \cellcolor{gray!10}{2.25 (0.957)} & \cellcolor{gray!10}{2.25 (0.961)}\\
\hspace{1em}Median [Min, Max] & 2.17 [1.00, 7.00] & 2.17 [1.00, 7.00] & 2.00 [1.00, 7.00] & 2.17 [1.00, 7.00] & 2.17 [1.00, 7.00] & 2.17 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{1 (0.0\%)} & \cellcolor{gray!10}{12435 (26.8\%)} & \cellcolor{gray!10}{15073 (32.5\%)} & \cellcolor{gray!10}{19483 (42.0\%)} & \cellcolor{gray!10}{22682 (48.9\%)} & \cellcolor{gray!10}{25025 (54.0\%)}\\
\addlinespace[0.3em]
\multicolumn{7}{l}{\textbf{Smoker (binary)}}\\
\hspace{1em}Mean (SD) & 0.0730 (0.260) & 0.0572 (0.232) & 0.0490 (0.216) & 0.0417 (0.200) & 0.0370 (0.189) & 0.0339 (0.181)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]} & \cellcolor{gray!10}{0 [0, 1.00]}\\
\hspace{1em}Missing & 1185 (2.6\%) & 12736 (27.5\%) & 15526 (33.5\%) & 19637 (42.3\%) & 22678 (48.9\%) & 25552 (55.1\%)\\*

\end{longtable}

\endgroup{}
\endgroup{}

\subsubsection{Exposure Variable: Religious Service
Attendance}\label{appendix-exposure}

(\citeproc{ref-tble-sample-exposures}{\textbf{tble-sample-exposures?}})
presents sample statistic for the exposure variable, religious service
attendance, during the baseline wave and exposure waves. This variable
was not measured in part of NZAVS time 12 (years 2020-2021) and part of
NZAVS time 13 (years 2021-2022). To address missingness, we carried the
previous observation forward, which may result in conservative causal
effect estimation, however it would be unlike to bias estimation away
from the null because the measurement error is random, and cannot be
systematically related to the outcomes.

\begingroup\fontsize{12}{14}\selectfont
\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{llllll}

\caption{\label{tbl-sample-exposures}Demographic statistics for New
Zealand Attitudes and Values Cohort waves 2018.}

\tabularnewline

\toprule
  & 2018 & 2019 & 2020 & 2021 & 2022\\
\midrule
\endfirsthead
\multicolumn{6}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2018 & 2019 & 2020 & 2021 & 2022\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)}\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Monthly Religious Service}}\\
\hspace{1em}0 & 38479 (83.0\%) & 28536 (61.5\%) & 0 (0\%) & 18913 (40.8\%) & 19781 (42.7\%)\\
\cellcolor{gray!10}{\hspace{1em}1} & \cellcolor{gray!10}{1517 (3.3\%)} & \cellcolor{gray!10}{896 (1.9\%)} & \cellcolor{gray!10}{0 (0\%)} & \cellcolor{gray!10}{87 (0.2\%)} & \cellcolor{gray!10}{628 (1.4\%)}\\
\hspace{1em}2 & 1125 (2.4\%) & 737 (1.6\%) & 0 (0\%) & 72 (0.2\%) & 523 (1.1\%)\\
\cellcolor{gray!10}{\hspace{1em}3} & \cellcolor{gray!10}{907 (2.0\%)} & \cellcolor{gray!10}{639 (1.4\%)} & \cellcolor{gray!10}{0 (0\%)} & \cellcolor{gray!10}{58 (0.1\%)} & \cellcolor{gray!10}{455 (1.0\%)}\\
\hspace{1em}4 & 2478 (5.3\%) & 1672 (3.6\%) & 0 (0\%) & 150 (0.3\%) & 1079 (2.3\%)\\
\cellcolor{gray!10}{\hspace{1em}5} & \cellcolor{gray!10}{475 (1.0\%)} & \cellcolor{gray!10}{308 (0.7\%)} & \cellcolor{gray!10}{0 (0\%)} & \cellcolor{gray!10}{24 (0.1\%)} & \cellcolor{gray!10}{171 (0.4\%)}\\
\hspace{1em}6 & 326 (0.7\%) & 205 (0.4\%) & 0 (0\%) & 23 (0.0\%) & 116 (0.3\%)\\
\cellcolor{gray!10}{\hspace{1em}7} & \cellcolor{gray!10}{106 (0.2\%)} & \cellcolor{gray!10}{68 (0.1\%)} & \cellcolor{gray!10}{0 (0\%)} & \cellcolor{gray!10}{6 (0.0\%)} & \cellcolor{gray!10}{31 (0.1\%)}\\
\hspace{1em}8 & 964 (2.1\%) & 645 (1.4\%) & 0 (0\%) & 68 (0.1\%) & 353 (0.8\%)\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{0 (0\%)} & \cellcolor{gray!10}{12671 (27.3\%)} & \cellcolor{gray!10}{46377 (100\%)} & \cellcolor{gray!10}{26976 (58.2\%)} & \cellcolor{gray!10}{23240 (50.1\%)}\\*

\end{longtable}

\endgroup{}
\endgroup{}

\newpage{}

\subsubsection{Outcome Variables}\label{appendix-outcomes}

\subsubsection{Health Outcome Variables}\label{health-outcome-variables}

\begingroup\fontsize{12}{14}\selectfont
\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{lll}

\caption{\label{tbl-sample-outcomes-health}Health variables measured at
baseline (NZAVS time 10, years 2018-2019, and time 15, years
2023-2024).}

\tabularnewline

\toprule
  & 2018 & 2023\\
\midrule
\endfirsthead
\multicolumn{3}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2018 & 2023\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Body Mass Index}}\\
\hspace{1em}Mean (SD) & 27.2 (5.87) & 27.8 (6.07)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{26.2 [12.3, 73.6]} & \cellcolor{gray!10}{26.7 [13.2, 87.4]}\\
\hspace{1em}Missing & 1171 (2.5\%) & 25123 (54.2\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Weekly Hours Sleep}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{6.94 (1.13)} & \cellcolor{gray!10}{6.93 (1.12)}\\
\hspace{1em}Median [Min, Max] & 7.00 [2.50, 16.0] & 7.00 [2.00, 16.0]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{2365 (5.1\%)} & \cellcolor{gray!10}{26025 (56.1\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Weekly Hours Excercise (log)}}\\
\hspace{1em}Mean (SD) & 1.54 (0.848) & 1.67 (0.830)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{1.61 [0, 4.39]} & \cellcolor{gray!10}{1.79 [0, 4.39]}\\
\hspace{1em}Missing & 1442 (3.1\%) & 25897 (55.8\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Short Form Health}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.04 (1.17)} & \cellcolor{gray!10}{4.84 (1.17)}\\
\hspace{1em}Median [Min, Max] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{9 (0.0\%)} & \cellcolor{gray!10}{25080 (54.1\%)}\\*

\end{longtable}

\endgroup{}
\endgroup{}

\subsubsection{Psychological Well-Being Outcome
Variables}\label{psychological-well-being-outcome-variables}

\begingroup\fontsize{12}{14}\selectfont
\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{lll}

\caption{\label{tbl-sample-outcomes-psych}Psychological well-being
variables measured at baseline (NZAVS time 10, years 2018-2019, and time
15, years 2023-2024).}

\tabularnewline

\toprule
  & 2018 & 2023\\
\midrule
\endfirsthead
\multicolumn{3}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2018 & 2023\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Fatigue}}\\
\hspace{1em}Mean (SD) & 1.64 (1.09) & 1.62 (1.07)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{2.00 [0, 4.00]} & \cellcolor{gray!10}{2.00 [0, 4.00]}\\
\hspace{1em}Missing & 500 (1.1\%) & 25117 (54.2\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Kessler 6 Anxiety}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{1.21 (0.773)} & \cellcolor{gray!10}{1.16 (0.764)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 4.00] & 1.00 [0, 4.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{437 (0.9\%)} & \cellcolor{gray!10}{25048 (54.0\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Kessler 6 Depression}}\\
\hspace{1em}Mean (SD) & 0.585 (0.753) & 0.526 (0.722)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{0.333 [0, 4.00]} & \cellcolor{gray!10}{0.333 [0, 4.00]}\\
\hspace{1em}Missing & 440 (0.9\%) & 25048 (54.0\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Rumination}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{0.847 (1.01)} & \cellcolor{gray!10}{0.759 (0.956)}\\
\hspace{1em}Median [Min, Max] & 1.00 [0, 4.00] & 0 [0, 4.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{538 (1.2\%)} & \cellcolor{gray!10}{25108 (54.1\%)}\\*

\end{longtable}

\endgroup{}
\endgroup{}

\subsubsection{Present-Focussed Well-Being
Indicators}\label{present-focussed-well-being-indicators}

\begingroup\fontsize{12}{14}\selectfont
\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{lll}

\caption{\label{tbl-sample-outcomes-present}Present-focussed well-being
variables measured at baseline (NZAVS time 10, years 2018-2019, and time
15, years 2023-2024).}

\tabularnewline

\toprule
  & 2018 & 2023\\
\midrule
\endfirsthead
\multicolumn{3}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2018 & 2023\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Body Satisifaction}}\\
\hspace{1em}Mean (SD) & 4.24 (1.70) & 4.23 (1.69)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]}\\
\hspace{1em}Missing & 537 (1.2\%) & 25931 (55.9\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Forgiveness}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.02 (1.27)} & \cellcolor{gray!10}{5.20 (1.26)}\\
\hspace{1em}Median [Min, Max] & 5.33 [1.00, 7.00] & 5.33 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{11 (0.0\%)} & \cellcolor{gray!10}{25125 (54.2\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Perfectionism}}\\
\hspace{1em}Mean (SD) & 3.18 (1.34) & 2.98 (1.40)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{3.00 [1.00, 7.00]} & \cellcolor{gray!10}{2.67 [1.00, 7.00]}\\
\hspace{1em}Missing & 6 (0.0\%) & 25174 (54.3\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Pwb Standard Living}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{7.58 (2.04)} & \cellcolor{gray!10}{7.54 (2.09)}\\
\hspace{1em}Median [Min, Max] & 8.00 [0, 10.0] & 8.00 [0, \vphantom{1} 10.0]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{174 (0.4\%)} & \cellcolor{gray!10}{25125 (54.2\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Pwb Your Future Security}}\\
\hspace{1em}Mean (SD) & 6.26 (2.35) & 6.13 (2.49)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{7.00 [0, 10.0]} & \cellcolor{gray!10}{7.00 [0, \vphantom{1} 10.0]}\\
\hspace{1em}Missing & 168 (0.4\%) & 25151 (54.2\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Pwb Your Health}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{6.76 (2.31)} & \cellcolor{gray!10}{6.54 (2.42)}\\
\hspace{1em}Median [Min, Max] & 7.00 [0, 10.0] & 7.00 [0, 10.0]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{188 (0.4\%)} & \cellcolor{gray!10}{25221 (54.4\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Pwb Your Relationships}}\\
\hspace{1em}Mean (SD) & 7.74 (2.24) & 7.66 (2.22)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{8.00 [0, 10.0]} & \cellcolor{gray!10}{8.00 [0, 10.0]}\\
\hspace{1em}Missing & 193 (0.4\%) & 25164 (54.3\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Self Control Have Lots}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.12 (1.38)} & \cellcolor{gray!10}{5.10 (1.41)}\\
\hspace{1em}Median [Min, Max] & 5.00 [1.00, 7.00] & 5.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{1261 (2.7\%)} & \cellcolor{gray!10}{26032 (56.1\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Self Control: Wish More (r)}}\\
\hspace{1em}Mean (SD) & 3.71 (1.83) & 3.87 (1.81)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{3.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]}\\
\hspace{1em}Missing & 197 (0.4\%) & 25974 (56.0\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Self Esteem}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.14 (1.28)} & \cellcolor{gray!10}{5.27 (1.30)}\\
\hspace{1em}Median [Min, Max] & 5.33 [1.00, 7.00] & 5.67 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{400 (0.9\%)} & \cellcolor{gray!10}{25104 (54.1\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Sexual Satisfaction}}\\
\hspace{1em}Mean (SD) & 4.58 (1.77) & 4.38 (1.76)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{4.00 [1.00, 7.00]}\\
\hspace{1em}Missing & 2958 (6.4\%) & 26494 (57.1\%)\\*

\end{longtable}

\endgroup{}
\endgroup{}

\subsubsection{Life-Focussed Well-Being
Indicators}\label{life-focussed-well-being-indicators}

\begingroup\fontsize{12}{14}\selectfont
\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{lll}

\caption{\label{tbl-sample-outcomes-life}Life-reflective well-being
variables measured at baseline (NZAVS time 10, years 2018-2019, and time
15, years 2023-2024).}

\tabularnewline

\toprule
  & 2018 & 2023\\
\midrule
\endfirsthead
\multicolumn{3}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2018 & 2023\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Gratitude}}\\
\hspace{1em}Mean (SD) & 5.90 (0.886) & 5.90 (0.910)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{6.00 [1.00, 7.00]} & \cellcolor{gray!10}{6.00 [1.00, \vphantom{1} 7.00]}\\
\hspace{1em}Missing & 9 (0.0\%) & 25102 (54.1\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Lifesat}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.29 (1.20)} & \cellcolor{gray!10}{5.22 (1.24)}\\
\hspace{1em}Median [Min, Max] & 5.50 [1.00, 7.00] & 5.50 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{223 (0.5\%)} & \cellcolor{gray!10}{25348 (54.7\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Meaning Purpose}}\\
\hspace{1em}Mean (SD) & 5.20 (1.42) & 5.16 (1.41)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]} & \cellcolor{gray!10}{5.00 [1.00, 7.00]}\\
\hspace{1em}Missing & 1224 (2.6\%) & 26377 (56.9\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Meaning Sense}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{5.71 (1.22)} & \cellcolor{gray!10}{5.78 (1.20)}\\
\hspace{1em}Median [Min, Max] & 6.00 [1.00, 7.00] & 6.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{160 (0.3\%)} & \cellcolor{gray!10}{26039 (56.1\%)}\\*

\end{longtable}

\endgroup{}
\endgroup{}

\subsubsection{Social Well-Being
Indicators}\label{social-well-being-indicators}

\begingroup\fontsize{12}{14}\selectfont
\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{lll}

\caption{\label{tbl-sample-outcomes-social}Life-reflective well-being
variables measured at baseline (NZAVS time 10, years 2018-2019, and time
15, years 2023-2024).}

\tabularnewline

\toprule
  & 2018 & 2023\\
\midrule
\endfirsthead
\multicolumn{3}{@{}l}{\textit{(continued)}}\\
\toprule
  & 2018 & 2023\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\cellcolor{gray!10}{} & \cellcolor{gray!10}{(N=46377)} & \cellcolor{gray!10}{(N=46377)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Belonging}}\\
\hspace{1em}Mean (SD) & 5.14 (1.08) & 5.23 (1.10)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]} & \cellcolor{gray!10}{5.33 [1.00, 7.00]}\\
\hspace{1em}Missing & 397 (0.9\%) & 25100 (54.1\%)\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Sense of Neighbourhood Community}}\\
\cellcolor{gray!10}{\hspace{1em}Mean (SD)} & \cellcolor{gray!10}{4.19 (1.67)} & \cellcolor{gray!10}{4.63 (1.56)}\\
\hspace{1em}Median [Min, Max] & 4.00 [1.00, 7.00] & 5.00 [1.00, 7.00]\\
\cellcolor{gray!10}{\hspace{1em}Missing} & \cellcolor{gray!10}{252 (0.5\%)} & \cellcolor{gray!10}{25906 (55.9\%)}\\
\addlinespace[0.3em]
\multicolumn{3}{l}{\textbf{Social Support}}\\
\hspace{1em}Mean (SD) & 5.95 (1.12) & 6.00 (1.13)\\
\cellcolor{gray!10}{\hspace{1em}Median [Min, Max]} & \cellcolor{gray!10}{6.33 [1.00, 7.00]} & \cellcolor{gray!10}{6.33 [1.00, 7.00]}\\
\hspace{1em}Missing & 37 (0.1\%) & 25133 (54.2\%)\\*

\end{longtable}

\endgroup{}
\endgroup{}

\newpage{}

\subsection{Appendix C: Confouding
Control}\label{appendix-c-confouding-control}

\begin{table}

\caption{\label{tbl-02}Causal diagrams showing sources of bias in a
three wave panel study.}

\centering{

\tvtable

}

\end{table}%

For confounding control, we employ a modified disjunctive cause
criterion (\citeproc{ref-vanderweele2019}{VanderWeele 2019}), which
involves:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Identifying all common causes of both the treatment and outcomes.
\item
  Excluding instrumental variables that affect the exposure but not the
  outcome.
\item
  Including proxies for unmeasured confounders affecting both exposure
  and outcome.
\item
  Controlling for baseline exposure and baseline outcome, serving as
  proxies for unmeasured common causes
  (\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).
\end{enumerate}

The covariates included for confounding control are detailed in
(\citeproc{ref-table-exposure}{\textbf{table-exposure?}}). This list
adheres to the guidelines provided in
(\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024a}) and were
pre-specified in our study protocol \url{https://osf.io/ce4t9/}.

Where there are multiple exposures, causal inference may be threatened
by time-varying confounding
(\citeproc{ref-bulbulia_2024_swig_time}{\textbf{bulbulia\_2024\_swig\_time?}}).

\newpage{}

\subsection{Appendix D Transition Matrix to Verify Positivity
Assumption}\label{appendix-transition}

\begin{longtable}[]{@{}cccccc@{}}
\caption{Transition Matrix Showing
Change}\label{tbl-transition}\tabularnewline
\toprule\noalign{}
From & State 0 & State 1 & State 2 & State 3 & State 4 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
From & State 0 & State 1 & State 2 & State 3 & State 4 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 0 & \textbf{40232} & 482 & 216 & 82 & 279 \\
State 1 & 672 & \textbf{246} & 92 & 45 & 73 \\
State 2 & 243 & 105 & \textbf{197} & 110 & 149 \\
State 3 & 118 & 54 & 111 & \textbf{171} & 225 \\
State 4 & 283 & 102 & 185 & 266 & \textbf{2338} \\
\end{longtable}

This transition matrix captures shifts in states across across the
treatment intervals. Each cell in the matrix represents the count of
individuals transitioning from one state to another. The rows correspond
to the treatment at baseline (From), and the columns correspond to the
state at the following wave (To). \textbf{Diagonal entries} (in
\textbf{bold}) correspond to the number of individuals who remained in
their initial state across both waves. \textbf{Off-diagonal entries}
correspond to the transitions of individuals from their baseline state
to a different state in the treatment wave. A higher number on the
diagonal relative to the off-diagonal entries in the same row indicates
greater stability in a state. Conversely, higher off-diagonal numbers
suggest more frequent shifts from the baseline state to other states.

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-altemeyer1996authoritarian}
Altemeyer, B (1996) \emph{The authoritarian spectre}, London: Harvard
University Press.

\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-berry_forgivingness_2005}
Berry, JW, Worthington Jr., EL, O'Connor, LE, Parrott III, L, and Wade,
NG (2005) Forgivingness, vengeful rumination, and affective traits.
\emph{Journal of Personality}, \textbf{73}(1), 183--226.
doi:\href{https://doi.org/10.1111/j.1467-6494.2004.00308.x}{10.1111/j.1467-6494.2004.00308.x}.

\bibitem[\citeproctext]{ref-bono2004gratitude}
Bono, G, Emmons, RA, and McCullough, ME (2004) Gratitude in practice and
the practice of gratitude. \emph{Positive Psychology in Practice},
464--481.

\bibitem[\citeproctext]{ref-brown2023_church}
Brown, JE, Van Mulukom, V, Charles, SJ, and Farias, M (2023) Do you need
religion to enjoy the benefits of church services? Social bonding,
morality and quality of life among religious and secular congregations.
\emph{Psychology of Religion and Spirituality}, \textbf{15}(2), 308.

\bibitem[\citeproctext]{ref-bulbulia2006nature}
Bulbulia, J (2006) Nature's medicine: Religiosity as an adaptation for
health and cooperation. \emph{Where God and Science Meet}, \textbf{1},
87--121.

\bibitem[\citeproctext]{ref-bulbulia2023understanding}
Bulbulia, JA (2023) Understanding the relationship between science and
religion using bayes' theorem. \emph{Studies in Christian Ethics},
\textbf{36}(4), 866--878.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, JA (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-bulbulia2023}
Bulbulia, JA (2024c) Methods in causal inference part 1: Causal diagrams
and confounding. \emph{Evolutionary Human Sciences}, \textbf{6}, e40.
doi:\href{https://doi.org/10.1017/ehs.2024.35}{10.1017/ehs.2024.35}.

\bibitem[\citeproctext]{ref-buysse1989pittsburgh}
Buysse, DJ, Reynolds III, CF, Monk, TH, Berman, SR, and Kupfer, DJ
(1989) The pittsburgh sleep quality index: A new instrument for
psychiatric practice and research. \emph{Psychiatry Research},
\textbf{28}(2), 193--213.

\bibitem[\citeproctext]{ref-caprara_indicators_1986}
Caprara, GV (1986) Indicators of aggression: The dissipation-rumination
scale. \emph{Personality and Individual Differences}, \textbf{7}(6),
763--769.
doi:\href{https://doi.org/10.1016/0191-8869(86)90074-7}{10.1016/0191-8869(86)90074-7}.

\bibitem[\citeproctext]{ref-xgboost2023}
Chen, T, He, T, Benesty, M, \ldots{} Yuan, J (2023) \emph{Xgboost:
Extreme gradient boosting}. Retrieved from
\url{https://CRAN.R-project.org/package=xgboost}

\bibitem[\citeproctext]{ref-chen2020religious}
Chen, Y, Kim, ES, and VanderWeele, TJ (2020) Religious-service
attendance and subsequent health and well-being throughout adulthood:
Evidence from three prospective cohorts. \emph{International Journal of
Epidemiology}, \textbf{49}(6), 2030--2040.

\bibitem[\citeproctext]{ref-chen2022_church_longitudinal}
Chen, Y, Weziak-Bialowolska, D, Lee, MT, Bialowolski, P, McNeely, E, and
VanderWeele, TJ (2022) Longitudinal associations between domains of
flourishing. \emph{Scientific Reports}, \textbf{12}(1), 2740.

\bibitem[\citeproctext]{ref-cummins_developing_2003}
Cummins, RA, Eckersley, R, Pallant, J, Vugt, J van, and Misajon, R
(2003) Developing a national index of subjective wellbeing: The
australian unity wellbeing index. \emph{Social Indicators Research},
\textbf{64}(2), 159--190.
doi:\href{https://doi.org/10.1023/A:1024704320683}{10.1023/A:1024704320683}.

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-dew2020joint}
Dew, JP, Uecker, JE, and Willoughby, BJ (2020) Joint religiosity and
married couples' sexual satisfaction. \emph{Psychology of Religion and
Spirituality}, \textbf{12}(2), 201.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diaz2023lmtp}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2023) Nonparametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association},
\textbf{118}(542), 846--857.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diener1985a}
Diener, E, Emmons, RA, Larsen, RJ, and Griffin, S (1985) The
Satisfaction With Life Scale. \emph{Journal of Personality Assessment},
\textbf{49}(1), 71--75.

\bibitem[\citeproctext]{ref-dunbar2021religiosity}
Dunbar, RI (2021) Religiosity and religious attendance as factors in
wellbeing and social engagement. \emph{Religion, Brain \& Behavior},
\textbf{11}(1), 17--26.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017) \emph{{N}ew {Z}ealand
socio-economic index 2013}, Wellington, New Zealand: Statistics New
Zealand-Tatauranga Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a {N}ew {Z}ealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-greaves2017diversity}
Greaves, LM, Barlow, FK, Lee, CH, et al.others (2017) The diversity and
prevalence of sexual orientation self-labels in a {N}ew {Z}ealand
national sample. \emph{Archives of Sexual Behavior}, \textbf{46},
1325--1336.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-Ministry_of_Health_2013}
Health, Ministry of (2013) \emph{The {N}ew {Z}ealand {H}ealth {S}urvey:
Content guide 2012-2013}, Princeton University Press.

\bibitem[\citeproctext]{ref-hernan2024WHATIF}
Hernan, MA, and Robins, JM (2024) \emph{Causal inference: What if?},
Taylor \& Francis. Retrieved from
\url{https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/}

\bibitem[\citeproctext]{ref-highland2019attitudes}
Highland, BR, Troughton, G, Shaver, J, Barrett, JL, Sibley, CG, and
Bulbulia, J (2019) Attitudes to religion predict warmth for muslims in
new zealand. \emph{New Zealand Journal of Psychology (Online)},
\textbf{48}(1), 122--132.

\bibitem[\citeproctext]{ref-highland2022national}
Highland, B, Worthington, EL, Davis, DE, Sibley, CG, and Bulbulia, JA
(2022) National longitudinal evidence for growth in subjective
well-being from spiritual beliefs. \emph{Journal of Health Psychology},
\textbf{27}(7), 1738--1752.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-instrument1992mos}
Instrument Ware Jr, J, and Sherbourne, C (1992) The MOS 36-item
short-form health survey (SF-36): I. Conceptual framework and item
selection. \emph{Medical Care}, \textbf{30}(6), 473--483.

\bibitem[\citeproctext]{ref-jokela2024_church}
Jokela, M, and Laakasuo, M (2024) Health trajectories of individuals who
quit active religious attendance: Analysis of four prospective cohort
studies in the united states. \emph{Social Psychiatry and Psychiatric
Epidemiology}, \textbf{59}(5), 871--878.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-kessler2002}
Kessler, R~C, Andrews, G, Colpe, L~J, \ldots{} Zaslavsky, A~M (2002)
Short screening scales to monitor population prevalences and trends in
non-specific psychological distress. \emph{Psychological Medicine},
\textbf{32}(6), 959--976.
doi:\href{https://doi.org/10.1017/S0033291702006074}{10.1017/S0033291702006074}.

\bibitem[\citeproctext]{ref-koenig2012handbook}
Koenig, HG, King, D, and Carson, VB (2012) \emph{Handbook of religion
and health}, Oxford University Press.

\bibitem[\citeproctext]{ref-vanderweelechurchmortality}
Li, S, Stampfer, MJ, Williams, DR, and VanderWeele, TJ (2016)
{Association of Religious Service Attendance With Mortality Among
Women}. \emph{JAMA Internal Medicine}, \textbf{176}(6), 777--785.
doi:\href{https://doi.org/10.1001/jamainternmed.2016.1615}{10.1001/jamainternmed.2016.1615}.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-mccullough_grateful_2002}
McCullough, ME, Emmons, RA, and Tsang, J-A (2002) The grateful
disposition: A conceptual and empirical topography. \emph{Journal of
Personality and Social Psychology}, \textbf{82}(1), 112--127.
doi:\href{https://doi.org/10.1037/0022-3514.82.1.112}{10.1037/0022-3514.82.1.112}.

\bibitem[\citeproctext]{ref-mccullough2001gratitude}
McCullough, ME, Kilpatrick, SD, Emmons, RA, and Larson, DB (2001) Is
gratitude a moral affect? \emph{Psychological Bulletin},
\textbf{127}(2), 249.

\bibitem[\citeproctext]{ref-nolen-hoeksema_effects_1993}
Nolen-hoeksema, S, and Morrow, J (1993) Effects of rumination and
distraction on naturally occurring depressed mood. \emph{Cognition and
Emotion}, \textbf{7}(6), 561--570.
doi:\href{https://doi.org/10.1080/02699939308409206}{10.1080/02699939308409206}.

\bibitem[\citeproctext]{ref-overall2016power}
Overall, NC, Hammond, MD, McNulty, JK, and Finkel, EJ (2016) When power
shapes interpersonal behavior: Low relationship power predicts men's
aggressive responses to low situational power. \emph{Journal of
Personality and Social Psychology}, \textbf{111}(2), 195.

\bibitem[\citeproctext]{ref-park2005religion}
Park, CL (2005) Religion as a meaning-making framework in coping with
life stress. \emph{Journal of Social Issues}, \textbf{61}(4), 707--729.

\bibitem[\citeproctext]{ref-pawlikowski2019religious}
Pawlikowski, J, Białowolski, P, Węziak-Białowolska, D, and VanderWeele,
TJ (2019) Religious service attendance, health behaviors and
well-being---an outcome-wide longitudinal analysis. \emph{European
Journal of Public Health}, \textbf{29}(6), 1177--1183.

\bibitem[\citeproctext]{ref-polley2023}
Polley, E, LeDell, E, Kennedy, C, and Laan, M van der (2023a)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://CRAN.R-project.org/package=SuperLearner}

\bibitem[\citeproctext]{ref-SuperLearner2023}
Polley, E, LeDell, E, Kennedy, C, and van der Laan, M (2023b)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://github.com/ecpolley/SuperLearner}

\bibitem[\citeproctext]{ref-rice_short_2014}
Rice, KG, Richardson, CME, and Tueller, S (2014) The short form of the
revised almost perfect scale. \emph{Journal of Personality Assessment},
\textbf{96}(3), 368--379.
doi:\href{https://doi.org/10.1080/00223891.2013.838172}{10.1080/00223891.2013.838172}.

\bibitem[\citeproctext]{ref-Rosenberg1965}
Rosenberg, M (1965) \emph{Society and the adolescent self-image},
Princeton, NJ: Princeton University Press.

\bibitem[\citeproctext]{ref-sengupta2013}
Sengupta, NK, Luyten, N, Greaves, LM, \ldots{} Sibley, CG (2013) Sense
of Community in {N}ew {Z}ealand Neighbourhoods: A Multi-Level Model
Predicting Social Capital. \emph{New Zealand Journal of Psychology},
\textbf{42}(1), 36--45.

\bibitem[\citeproctext]{ref-shaver2024religious}
Shaver, JH, Chvaja, R, Spake, L, \ldots{} Sosis, R (2024) Religious
involvement is associated with higher fertility and lower maternal
investment, but more alloparental support among gambian mothers.
\emph{American Journal of Human Biology}, e24144.

\bibitem[\citeproctext]{ref-shaver2020church}
Shaver, JH, Power, EA, Purzycki, BG, \ldots{} Bulbulia, JA (2020) Church
attendance and alloparenting: An analysis of fertility, social support
and child development among {E}nglish mothers. \emph{Philosophical
Transactions of the Royal Society B}, \textbf{375}(1805), 20190428.

\bibitem[\citeproctext]{ref-shaver2016religion}
Shaver, JH, Troughton, G, Sibley, CG, and Bulbulia, JA (2016) Religion
and the unmaking of prejudice toward muslims: Evidence from a large
national sample. \emph{PloS One}, \textbf{11}(3), e0150209.

\bibitem[\citeproctext]{ref-shaver2022integrating}
Shaver, J, and White, T (2022) Integrating pacific research
methodologies with western social science research methods: Quantifying
pentecostalism's effects on fijian relationality.

\bibitem[\citeproctext]{ref-sibley2012}
Sibley, C. G., and Bulbulia, JA (2012) Healing those who need healing:
How religious practice affects social belonging. \emph{Journal for the
Cognitive Science of Religion}, \textbf{1}, 29--45.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the {N}ew {Z}ealand {A}ttitudes and {V}alues
{S}tudy}}.

\bibitem[\citeproctext]{ref-sibley2020}
Sibley, CG, Afzali, MU, Satherley, N, \ldots{} others (2020) Prejudice
toward muslims in {N}ew {Z}ealand: Insights from the {N}ew {Z}ealand
{A}ttitudes and {V}alues {S}tudy. \emph{New Zealand Journal of
Psychology}, \textbf{49}(1).

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in {N}ew {Z}ealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-sidanius1999social}
Sidanius, J, and Pratto, F (1999) \emph{Social dominance: An intergroup
theory of social hierarchy and oppression}, Cambridge: Cambridge
University Press.

\bibitem[\citeproctext]{ref-sosis2003cooperation}
Sosis, R, and Bressler, ER (2003) Cooperation and commune longevity: A
test of the costly signaling theory of religion. \emph{Cross-Cultural
Research}, \textbf{37}(2), 211--239.

\bibitem[\citeproctext]{ref-steger_meaning_2006}
Steger, MF, Frazier, P, Oishi, S, and Kaler, M (2006) The meaning in
life questionnaire: Assessing the presence of and search for meaning in
life. \emph{Journal of Counseling Psychology}, \textbf{53}(1), 80--93.
doi:\href{https://doi.org/10.1037/0022-0167.53.1.80}{10.1037/0022-0167.53.1.80}.

\bibitem[\citeproctext]{ref-stronge2015facebook}
Stronge, S, Greaves, LM, Milojev, P, West-Newman, T, Barlow, FK, and
Sibley, CG (2015) Facebook is linked to body dissatisfaction: Comparing
users and non-users. \emph{Sex Roles}, \textbf{73}, 200--213.

\bibitem[\citeproctext]{ref-tangney_high_2004}
Tangney, JP, Baumeister, RF, and Boone, AL (2004) High self-control
predicts good adjustment, less pathology, better grades, and
interpersonal success. \emph{Journal of Personality}, \textbf{72}(2),
271--324.
doi:\href{https://doi.org/10.1111/j.0022-3506.2004.00263.x}{10.1111/j.0022-3506.2004.00263.x}.

\bibitem[\citeproctext]{ref-vanderweele2019}
VanderWeele, TJ (2019) Principles of confounder selection.
\emph{European Journal of Epidemiology}, \textbf{34}(3), 211--219.

\bibitem[\citeproctext]{ref-vanderweele2021effectsReligiousServiceMetanalysis}
VanderWeele, TJ (2021) Effects of religious service attendance and
religious importance on depression: Examining the meta-analytic
evidence. \emph{The International Journal for the Psychology of
Religion}, \textbf{31}(1), 21--26.

\bibitem[\citeproctext]{ref-vanderweele2022invited_church}
VanderWeele, TJ, Balboni, TA, and Koh, HK (2022) Invited commentary:
Religious service attendance and implications for clinical care,
community participation, and public health. \emph{American Journal of
Epidemiology}, \textbf{191}(1), 31--35.

\bibitem[\citeproctext]{ref-vanderweele2020vchenrespond}
VanderWeele, TJ, and Chen, Y (2020) VanderWeele and chen respond to
{``religion as a social determinant of health.''} \emph{American Journal
of Epidemiology}, \textbf{189}(12), 1464--1466.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the {E}-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437--466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-whitehead2023unmasking}
Whitehead, J, Davie, G, Graaf, B de, \ldots{} Nixon, G (2023) Unmasking
hidden disparities: A comparative observational study examining the
impact of different rurality classifications for health research in
aotearoa new zealand. \emph{BMJ Open}, \textbf{13}(4), e067927.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{{l}mtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\bibitem[\citeproctext]{ref-Ranger2017}
Wright, MN, and Ziegler, A (2017) {ranger}: A fast implementation of
random forests for high dimensional data in {C++} and {R}. \emph{Journal
of Statistical Software}, \textbf{77}(1), 1--17.
doi:\href{https://doi.org/10.18637/jss.v077.i01}{10.18637/jss.v077.i01}.

\end{CSLReferences}




\end{document}
