---
title: "Evidence for Declining Trust in Science From A Large National Panel Study in New Zealand (years 2019-2023)"
abstract: |
   The public perceptions of science has wide-ranging effects, from the adoption public health behaviours to climate action. Here, drawing on a nationally diverse panel study in New Zealand, we report attitudes to trust in the institution of science and trust in scientists from October 2019- October 2023 in a large nationally diverse cohort of (N = 42,681, New Zealand Attitudes and Values Study), using multiple imputation to address systematic bias from attrition. Study 1 focuses on average responses, revealing stability in rolling average responses over time. Study 2 focuses on the proportional change in predicted probabilities across the low, medium, and high ends of the response scale  Since 2019, the proportion of individuals in the low trust category has been slowly increasing. After the COVID pandemic, trust in the medium category declined, while trust in the high category rose. The European majority remains the most trusting of science, but the post-pandemic increase in trust is waning. Māori have lower trust in science, with a smaller post-pandemic boost that is now diminishing. Māori and Pacific peoples show the lowest levels of trust, with this mistrust growing since the pandemic. Political conservatives are also experiencing an increase in mistrust of science. Initially, men were more trusting of science, but declining trust among men, alongside rising high trust in other genders, has equalised trust levels between the sexes. Trust among political conservatives has shown a steady increase, though causality is unclear, as greater trust in science may correlate with a shift towards conservatism. Overall, these patterns indicate that, despite stable averages, there is preliminary evidence of rising mistrust in scientific institutions and scientists. 
   **KEYWORDS**: *Conservativism*; *Institutional Trust*; *Longitudinal*; *Panel*; *Political*; *Science*.
author: 
  - name: Authors (and author order TBA)
    affiliation: New Zealand
    orcid: 0000-0003-3169-6576 
editor_options: 
    chunk_output_type: console
format:
  pdf:  
    bibliography: /Users/joseph/GIT/templates/bib/references.bib
    keep-tex: true
    header-includes: |
      \input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
    pdf-engine: lualatex
    sanitise: false
    link-citations: true
    colorlinks: true
    documentclass: article
    classoption: [single column]
    lof: false
    lot: false
    geometry:
      - top=30mm
      - left=25mm
      - heightrounded
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
    template-partials: 
      - /Users/joseph/GIT/templates/quarto/title.tex
date: last-modified
execute:
  echo: false
  warning: false
  include: true
  eval: true
fontfamily: libertinus
bibliography: /Users/joseph/GIT/templates/bib/references.bib
csl: /Users/joseph/GIT/templates/csl/camb-a.csl
---

```{r}
#| label: load-libraries
#| echo: false
#| include: false
#| eval: true

library(margot)
library(tinytable)
library(kableExtra)
library(ggeffects)
library(parameters)
options(tinytable_tt_digits = 3)

library("margot")
library("glue")
library("patchwork")
library("kableExtra")
library("stringr")
library("ggplot2")
library("ggeffects")
library("parameters")
library("tinytable")

# options(tinytable_pdf_engine = "lualatex")
# options(tinytable_quarto_disable_processing = TRUE)


# path to data folder (set to path on your computer) - for pushing and pulling model results
push_mods <- here::here(
  "/Users/joseph/Library/CloudStorage/Dropbox-v-project/data/24-john-kerr-trust-science-growth"
)

tt_summary_mean_response_sample <- here_read("tt_summary_mean_response_sample")
tt_summary_mean_response_sample |> print("markdown")
tt_summary_mean_response_sample |> print("latex")
tt_summary_mean_response_sample_imp <- here_read("tt_summary_mean_response_sample_imp")
tt_summary_mean_response_sample_imp|> print("markdown")
summary_tables <- margot::here_read_qs("summary_tables", push_mods)

trust_science_marginal_gee <- here_read("trust_science_marginal_gee")
ggeffects::pool_predictions(trust_science_marginal_gee) |> print_md(  collapse_tables = FALSE)


tt_summary_mean_response_sample <- here_read("tt_summary_mean_response_sample")
tt_summary_mean_response_sample
tt_summary_mean_response_sample_imp <- here_read("tt_summary_mean_response_sample_imp")
tt_summary_mean_response_sample_imp


# alluvial plots
sankey_plot_science_sample<-  here_read_qs("sankey_plot_science_sample", push_mods)
sankey_plot_st_sample <-  here_read_qs("sankey_plot_st_sample", push_mods)


sankey_plot_science_imp<-  here_read_qs("sankey_plot_science_imp", push_mods)
sankey_plot_st_imp<-  here_read_qs("sankey_plot_st_imp", push_mods)

tt_summary_table_cat<- here_read("tt_summary_table_cat")
tt_summary_table_cat_imp <- here_read("tt_summary_table_cat_imp")
tt_summary_table_cat
tt_summary_table_cat_imp
```

#### Trust Scientists: Observed Categorical Responses



::: {#tbl-baseline}
\begin{longtable}[t]{lllll}
\toprule
**Variables** & **2019**  
N = 42,681 & **2020**  
N = 42,681 & **2021**  
N = 42,681 & **2022**  
N = 42,681\\
\midrule
\_\_Age\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 52 (14) & 54 (14) & 55 (14) & 57 (13)\\
Min, Max & 18, 97 & 19, 97 & 20, 97 & 21, 98\\
Q1, Q3 & 42, 63 & 45, 64 & 47, 65 & 48, 67\\
Missing & 0 & 9,363 & 13,615 & 17,166\\
\addlinespace
\_\_Agreeableness\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 5.38 (0.98) & 5.38 (0.98) & 5.36 (1.00) & 5.35 (0.99)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.75, 6.00 & 4.75, 6.00 & 4.75, 6.00 & 4.75, 6.00\\
Missing & 316 & 9,579 & 13,831 & 17,260\\
\addlinespace
\_\_Belong\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 5.09 (1.09) & 5.02 (1.11) & 5.14 (1.12) & 5.14 (1.11)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.33, 6.00 & 4.33, 6.00 & 4.33, 6.00 & 4.33, 6.00\\
Missing & 324 & 9,587 & 13,885 & 17,303\\
\addlinespace
\_\_Born NZ\_\_ & 33,316 (78\%) & 33,316 (78\%) & 33,316 (78\%) & 33,316 (78\%)\\
Missing & 81 & 81 & 81 & 81\\
\_\_Conscientiousness\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 5.06 (1.07) & 5.10 (1.05) & 5.12 (1.06) & 5.12 (1.05)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
\addlinespace
Q1, Q3 & 4.25, 5.75 & 4.50, 6.00 & 4.50, 6.00 & 4.50, 6.00\\
Missing & 313 & 9,577 & 13,823 & 17,259\\
\_\_Education Level Coarsen\_\_ &   ~~&   ~~&   ~~& NA\\
no\_qualification & 853 (2.0\%) & 754 (1.8\%) & 706 (1.7\%) & 711 (1.7\%)\\
cert\_1\_to\_4 & 13,117 (31\%) & 12,588 (30\%) & 12,228 (29\%) & 11,989 (28\%)\\
\addlinespace
cert\_5\_to\_6 & 5,606 (13\%) & 5,714 (14\%) & 5,748 (14\%) & 5,807 (14\%)\\
university & 11,783 (28\%) & 11,856 (28\%) & 11,823 (28\%) & 11,747 (28\%)\\
post\_grad & 5,363 (13\%) & 5,614 (13\%) & 5,850 (14\%) & 5,992 (14\%)\\
masters & 4,256 (10\%) & 4,440 (10\%) & 4,579 (11\%) & 4,685 (11\%)\\
doctorate & 1,280 (3.0\%) & 1,337 (3.2\%) & 1,381 (3.3\%) & 1,426 (3.4\%)\\
\addlinespace
Missing & 423 & 378 & 366 & 324\\
\_\_Employed\_\_ & 31,856 (76\%) & 25,061 (76\%) & 21,235 (74\%) & 17,725 (71\%)\\
Missing & 550 & 9,580 & 13,942 & 17,589\\
\_\_Ethnicity\_\_ &   ~~&   ~~&   ~~& NA\\
euro & 34,990 (83\%) & 34,990 (83\%) & 34,990 (83\%) & 34,990 (83\%)\\
\addlinespace
maori & 4,639 (11\%) & 4,639 (11\%) & 4,639 (11\%) & 4,639 (11\%)\\
pacific & 929 (2.2\%) & 929 (2.2\%) & 929 (2.2\%) & 929 (2.2\%)\\
asian & 1,770 (4.2\%) & 1,770 (4.2\%) & 1,770 (4.2\%) & 1,770 (4.2\%)\\
Missing & 353 & 353 & 353 & 353\\
\_\_Extraversion\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 3.87 (1.19) & 3.83 (1.19) & 3.77 (1.23) & 3.75 (1.23)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 3.00, 4.75 & 3.00, 4.75 & 3.00, 4.67 & 3.00, 4.50\\
Missing & 314 & 9,577 & 13,832 & 17,274\\
\_\_Honesty Humility\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 5.56 (1.14) & 5.62 (1.11) & 5.68 (1.13) & 5.72 (1.12)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.75, 6.50 & 5.00, 6.50 & 5.00, 6.67 & 5.00, 6.75\\
Missing & 323 & 9,587 & 13,816 & 17,252\\
\_\_Hours Commute\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 4.5 (7.0) & 4.4 (5.9) & 3.7 (5.4) & 4.4 (6.2)\\
Min, Max & 0.0, 168.0 & 0.0, 100.0 & 0.0, 100.0 & 0.0, 100.0\\
Q1, Q3 & 1.0, 6.0 & 1.0, 6.0 & 1.0, 5.0 & 1.0, 6.0\\
Missing & 829 & 10,233 & 14,611 & 18,092\\
\_\_Household Inc\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 117,971 (107,738) & 120,324 (106,017) & 124,450 (111,893) & 130,963 (146,750)\\
Min, Max & 1, 4,000,000 & 1, 3,000,000 & 1, 3,500,000 & 1,000, 7,500,000\\
Q1, Q3 & 55,000, 150,000 & 57,000, 150,000 & 58,000, 160,000 & 59,000, 165,000\\
Missing & 2,039 & 10,255 & 14,527 & 17,669\\
\_\_Kessler Latent Anxiety\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 1.20 (0.76) & 1.17 (0.76) & 1.19 (0.77) & 1.17 (0.77)\\
Min, Max & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00\\
Q1, Q3 & 0.67, 1.67 & 0.67, 1.67 & 0.67, 1.67 & 0.67, 1.67\\
Missing & 344 & 9,591 & 13,814 & 17,257\\
\_\_Kessler Latent Depression\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 0.60 (0.75) & 0.55 (0.73) & 0.57 (0.74) & 0.54 (0.72)\\
Min, Max & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00 & 0.00, 4.00\\
Q1, Q3 & 0.00, 1.00 & 0.00, 1.00 & 0.00, 1.00 & 0.00, 1.00\\
Missing & 340 & 9,588 & 13,814 & 17,259\\
\_\_Male\_\_ & 15,228 (36\%) & 15,228 (36\%) & 15,228 (36\%) & 15,228 (36\%)\\
\addlinespace
\_\_Neuroticism\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 3.50 (1.16) & 3.46 (1.16) & 3.41 (1.18) & 3.36 (1.17)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 2.75, 4.25 & 2.50, 4.25 & 2.50, 4.25 & 2.50, 4.25\\
Missing & 315 & 9,580 & 13,822 & 17,261\\
\addlinespace
\_\_Nz Dep2018\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 4.75 (2.72) & 4.75 (2.73) & 4.75 (2.73) & 4.75 (2.73)\\
Min, Max & 1.00, 10.00 & 1.00, 10.00 & 1.00, 10.00 & 1.00, 10.00\\
Q1, Q3 & 2.00, 7.00 & 2.00, 7.00 & 2.00, 7.00 & 2.00, 7.00\\
Missing & 328 & 541 & 957 & 927\\
\addlinespace
\_\_Nzsei 13 L\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 56 (16) & 56 (16) & 56 (16) & 57 (15)\\
Min, Max & 10, 90 & 10, 90 & 10, 90 & 10, 90\\
Q1, Q3 & 44, 69 & 44, 70 & 45, 70 & 46, 70\\
Missing & 338 & 3,236 & 4,294 & 6,107\\
\addlinespace
\_\_Openness\_\_ &   ~~&   ~~&   ~~& NA\\
Mean (SD) & 5.01 (1.11) & 5.01 (1.11) & 5.02 (1.14) & 5.01 (1.15)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 4.25, 5.75 & 4.25, 5.75 & 4.25, 6.00 & 4.25, 6.00\\
Missing & 316 & 9,579 & 13,830 & 17,265\\
\addlinespace
\_\_Parent\_\_ & 31,213 (73\%) & 24,889 (75\%) & 21,693 (75\%) & 19,597 (77\%)\\
Missing & 20 & 9,363 & 13,752 & 17,166\\
\_\_Partner\_\_ & 31,353 (75\%) & 24,644 (75\%) & 21,377 (75\%) & 18,499 (75\%)\\
Missing & 786 & 9,844 & 14,248 & 17,868\\
\_\_Political Conservative\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
1 & 2,703 (6.5\%) & 2,289 (7.1\%) & 1,654 (6.0\%) & 1,431 (5.9\%)\\
2 & 8,734 (21\%) & 7,118 (22\%) & 6,012 (22\%) & 5,188 (21\%)\\
3 & 8,493 (21\%) & 6,944 (22\%) & 5,978 (22\%) & 4,972 (20\%)\\
4 & 11,838 (29\%) & 9,424 (29\%) & 8,268 (30\%) & 6,936 (29\%)\\
5 & 5,942 (14\%) & 4,110 (13\%) & 3,901 (14\%) & 3,577 (15\%)\\
\addlinespace
6 & 2,980 (7.2\%) & 1,788 (5.6\%) & 1,639 (5.9\%) & 1,853 (7.6\%)\\
7 & 677 (1.6\%) & 405 (1.3\%) & 335 (1.2\%) & 365 (1.5\%)\\
Missing & 1,314 & 10,603 & 14,894 & 18,359\\
\_\_Religion Identification Level\_\_ &   ~~&   ~~&   ~~& NA\\
1 & 29,148 (69\%) & 22,794 (69\%) & 20,119 (70\%) & 17,134 (69\%)\\
\addlinespace
2 & 1,329 (3.2\%) & 919 (2.8\%) & 765 (2.7\%) & 812 (3.3\%)\\
3 & 860 (2.0\%) & 801 (2.4\%) & 670 (2.3\%) & 558 (2.3\%)\\
4 & 1,967 (4.7\%) & 1,562 (4.7\%) & 1,322 (4.6\%) & 1,165 (4.7\%)\\
5 & 2,312 (5.5\%) & 1,882 (5.7\%) & 1,656 (5.8\%) & 1,270 (5.1\%)\\
6 & 2,040 (4.8\%) & 1,707 (5.2\%) & 1,415 (4.9\%) & 1,241 (5.0\%)\\
\addlinespace
7 & 4,419 (11\%) & 3,258 (9.9\%) & 2,764 (9.6\%) & 2,546 (10\%)\\
Missing & 606 & 9,758 & 13,970 & 17,955\\
\_\_Rural Gch 2018 Levels\_\_ &  &   ~~&   ~~& NA\\
1 & 25,864 (61\%) & 25,578 (61\%) & 25,088 (60\%) & 24,950 (60\%)\\
2 & 8,164 (19\%) & 8,195 (19\%) & 8,185 (20\%) & 8,220 (20\%)\\
\addlinespace
3 & 5,362 (13\%) & 5,439 (13\%) & 5,470 (13\%) & 5,529 (13\%)\\
4 & 2,461 (5.8\%) & 2,475 (5.9\%) & 2,495 (6.0\%) & 2,551 (6.1\%)\\
5 & 506 (1.2\%) & 507 (1.2\%) & 488 (1.2\%) & 504 (1.2\%)\\
Missing & 324 & 487 & 955 & 927\\
\_\_Right Wing Authoritarianism\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 3.17 (1.14) & 3.25 (1.11) & 3.33 (1.06) & 3.30 (1.07)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 2.33, 4.00 & 2.50, 4.00 & 2.50, 4.00 & 2.50, 4.00\\
Missing & 46 & 9,423 & 13,803 & 17,220\\
\_\_Social Dominance Orientation\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 2.22 (0.96) & 2.18 (0.95) & 2.20 (0.95) & 2.23 (0.96)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 1.50, 2.83 & 1.33, 2.83 & 1.50, 2.83 & 1.50, 2.83\\
Missing & 16 & 9,383 & 13,647 & 17,170\\
\_\_Social Support (perceived)\_\_ &   ~~&   ~~&   ~~& NA\\
\addlinespace
Mean (SD) & 5.93 (1.15) & 5.93 (1.14) & 5.93 (1.16) & 5.96 (1.15)\\
Min, Max & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00 & 1.00, 7.00\\
Q1, Q3 & 5.33, 7.00 & 5.33, 7.00 & 5.33, 7.00 & 5.33, 7.00\\
Missing & 28 & 9,397 & 13,772 & 17,268\\
\bottomrule
\end{longtable}

Sample statistics.
:::

@tbl-baseline presents sample statistics.
