% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Causal Effects of Forgiveness on Outcomewide Flourishing: Evidence From a National Panel in New Zealand},
  pdfauthor={Richard Cowdan; Don E Davis; Pedro Antonio de la Rosa Fernández Pacheco; Chris G. Sibley; Everett Worthington; Tyler VanderWeele; Joseph A. Bulbulia},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Causal Effects of Forgiveness on Outcomewide Flourishing:
Evidence From a National Panel in New Zealand}

\usepackage{academicons}
\usepackage{xcolor}

  \author{Richard Cowdan}
            \affil{%
             \small{     Harvard University
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-7252-1361 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Don E Davis}
            \affil{%
             \small{     Georgia State University, Matheny Center for
the Study of Stress, Trauma, and Resilience
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0003-3169-6576 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Pedro Antonio de la Rosa Fernández Pacheco}
            \affil{%
             \small{     Harvard University
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-0912-7396 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Chris G. Sibley}
            \affil{%
             \small{     School of Psychology, University of Auckland
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-4064-8800 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Everett Worthington}
            \affil{%
             \small{     Virginia Commonwealth University
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5095-4588 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Tyler VanderWeele}
            \affil{%
             \small{     Harvard University
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-6112-0239 }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Joseph A. Bulbulia}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~0000-0002-5861-2056 }
              }
      


\date{2024-06-04}
\begin{document}
\maketitle
\begin{abstract}
We investigate the causal effects of forgiveness interventions on
multidimensional well-being in a longitudinal study of 33,198 New
Zealanders (years 2018 to 2021). We ask two causal questions: (1) What
would be the effects across multi-dimensional well-being if everyone
with below-average forgiveness were elevated to average levels? (2) What
would be the effects on multi-dimensional well-being if everyone were
increased by one point on a 1-7 Likert scale for forgiveness? We
discover reliable improvements across all well-being dimensions for both
interventions, with the general plus-one intervention yielding more
substantial effects. Notably, the most pronounced benefits were observed
in ego-related well-being, underscoring the considerable personal
benefits of forgiving others. \textbf{KEYWORDS}: \emph{Causal
Inference}; \emph{Longitudinal}; \emph{Religion}; \emph{Targeted
Learning}; \emph{TMLE}; \emph{Flourishing}.
\end{abstract}

\subsection{Introduction}\label{introduction}

Does forgiveness causally affect multidimensional well-being?

Despite a wealth of associational studies, national-scale causal
investigations are presently lacking. To quantitatively evaluate
causality, we must compare outcomes under different interventions or
``treatments.'' In observational studies, such comparisons are
challenging because many variables might affect whether one receives
treatment and how a subsequent outcome unfolds. A fundamental challenge
in observational studies is to ensure \emph{balance} between the
confounders within the treatment to be compared
(\citeproc{ref-shiba2021using}{Shiba and Kawahara 2021}). We call the
state of imbalance in the common causes of the treatment and outcomes
\emph{confounding}. We call a strategy for ensuring balance
\emph{confounding control.} With time-series data and sufficiently rich
measures of confounding variables or their proxies, we may more reliably
infer causality from associations in the data
(\citeproc{ref-robins1986}{Robins 1986}).

Here, we estimate the causal effects of forgiveness interventions on
multidimensional well-being indicators using comprehensive panel data
from 34,749 participants in the New Zealand Attitudes and Values Study
from 2018-2021. Our confounding control strategy adjusts for baseline
measures of forgiveness and the outcomes under investigation.

Forgiveness is a continuous variable, allowing for innumerable causal
contrasts. Which to select? We first calculate expected population
averages for each well-being outcome with two ``modified treatment
policies'' (\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021},
\citeproc{ref-diaz2023lmtp}{2023};
\citeproc{ref-haneuse2013estimation}{Haneuse and Rotnitzky 2013};
\citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023}), which we
contrast with expectations under no treatment. These interventions
assess different practical interests. Our approach is not to test
specific hypotheses but to accurately quantify effect magnitudes,
offering our results as conversation-starters that may inform clinical
and public decision-making (\citeproc{ref-hernan2024stating}{Hernán and
Greenland 2024}).

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected by the New Zealand Attitudes and Values Study
(NZAVS), an annual longitudinal national probability panel study of
social attitudes, personality, ideology, and health outcomes in New
Zealand started in 2009. Since its inception, The New Zealand Attitudes
and Values Study has accumulated questionnaire responses from 72,910 New
Zealand residents. The measures that we use in the present study were
introduced in the NZAVS 2018 wave (time 10). The study operates
independently of political or corporate funding and is based in a
university setting. Data summaries for our study sample on all measures
used in this study are found in \textbf{Appendices B-D}. For more
details about the New Zealand Attitudes and Values Study see:
\href{https://doi.org/10.17605/OSF.IO/75SNB}{OSF.IO/75SNB}.

\subsubsection{Treatment: Forgiveness}\label{treatment-forgiveness}

We assessed participants' forgiveness using reversed scores of the NZAVS
``vengeful rumination scale.'' This scale contains three items, adapted
from Caprara (\citeproc{ref-caprara_indicators_1986}{1986}) and Berry
\emph{et al.} (\citeproc{ref-berry_forgivingness_2005}{2005}), and
developed for NZAVS:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  Sometimes I can't sleep because of thinking about past wrongs I have
  suffered;
\item
  I can usually forgive and forget when someone does me wrong (reversed
  scored);
\item
  I find myself regularly thinking about past times that I have been
  wronged.
\end{enumerate}

Participants indicated their agreement with these items (1 = Strongly
Disagree to 7 = Strongly Agree).

\subsubsection{Health Outcomes Measures}\label{health-outcomes-measures}

\paragraph{Alcohol Frequency}\label{alcohol-frequency}

We measured participants' frequency of drinking alcohol using one item
adapted from Health (\citeproc{ref-Ministry_of_Health_2013}{2013}).
Participants were asked, ``How often do you have a drink containing
alcohol?'' (1 = Never - I don't drink, 2 = Monthly or less, 3 = Up to 4
times a month, 4 = Up to 3 times a week, 5 = 4 or more times a week, 6 =
Don't know).

\paragraph{Alcohol Intensity}\label{alcohol-intensity}

We measured participants' intensity of drinking alcohol using one item
adapted from Health (\citeproc{ref-Ministry_of_Health_2013}{2013}).
Participants were asked, ``How many drinks containing alcohol do you
have on a typical day when drinking alcohol? (number of drinks on a
typical day when drinking)''

\paragraph{Body Mass Index}\label{body-mass-index}

We asked participants ``What is your height? (metres)'' and ``What is
your weight? (kg)''. Based on participants indication of their height
and weight we calculated the BMI by dividing the weight in kilograms by
the square of the height in meters.

\paragraph{Hours of Exercise}\label{hours-of-exercise}

We measured hours of exercise using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

\paragraph{Hours of Sleep}\label{hours-of-sleep}

``During the past month, on average, how many hours of \emph{actual
sleep} did you get per night''.

\paragraph{Short Form Health: ``Your
Health''}\label{short-form-health-your-health}

We selected the first item from the ``Short-Form Subjective Health Scale
(General Health Perception Subscale),'' Instrument Ware Jr and
Sherbourne (\citeproc{ref-instrument1992mos}{1992}), scored ordinal
(1-7)

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ``In general, would you say your health is\ldots{}''
\item
  ``I seem to get sick a little easier than other people.'' (reversed)
\item
  ``I expect my health to get worse.'' (reversed)
\end{enumerate}

\paragraph{Smoker}\label{smoker}

We asked participants whether they are currently smoking or not (1 = Yes
or 0 = No), using a single item (``Do you currently smoke?) from Muriwai
\emph{et al.} (\citeproc{ref-muriwai_looking_2018}{2018}).

\subsubsection{Embodied Well-being
Measures}\label{embodied-well-being-measures}

\paragraph{Body Satisfaction (1 = Very inaccurate to 7 = Very
accurate)}\label{body-satisfaction-1-very-inaccurate-to-7-very-accurate}

\begin{itemize}
\tightlist
\item
  ``I am satisfied with the appearance, size and shape of my body''
\end{itemize}

From Stronge \emph{et al.} (\citeproc{ref-stronge2015facebook}{2015})

\paragraph{Fatigue (ordinal)}\label{fatigue-ordinal}

\begin{itemize}
\tightlist
\item
  ``During the last 30 days, how often did \ldots{} you feel
  exhausted?''
\end{itemize}

Ordinal responses: 0 = None of The Time, 1 = A little of The Time, 2 =
Some of The Time, 3 = Most of The Time, 4 = All of The Time.

From Sibley \emph{et al.} (\citeproc{ref-sibley2020}{2020})

\paragraph{Kessler 6 Anxiety and Kessler 6 Depression
(ordinal)}\label{kessler-6-anxiety-and-kessler-6-depression-ordinal}

We measured psychological distress using the Kessler-6 scale
(kessler2002?), which exhibits strong diagnostic concordance for
moderate and severe psychological distress in large, cross-cultural
samples (\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002};
\citeproc{ref-kessler2010}{Kessler \emph{et al.} 2010}?;
\citeproc{ref-prochaska2012}{Prochaska \emph{et al.} 2012}).

Participants rated during the past 30 days, how often did\ldots{}

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  ``\ldots{} you feel hopeless'';
\item
  ``\ldots you feel so depressed that nothing could cheer you up'';
\item
  ``\ldots you feel restless or fidgety''; (4)``\ldots you feel that
  everything was an effort'';
\item
  ``\ldots{} you feel worthless'';
\item
  ``\ldots you feel nervous?''
\end{enumerate}

Ordinal responses: 0 = None of The Time, 1 = A little of The Time, 2 =
Some of The Time, 3 = Most of The Time, 4 = All of The Time.

A two-factor model fits this scale. We describe the decomposition as:

\textbf{Kesser-6-latent-anxiety}: ``\ldots{} you feel restless or
fidgety''; '' you feel nervous?'' ``\ldots{} you feel that everything
was an effort.''

\textbf{Kesser-6-latent-anxiety}: ``\ldots{} you feel hopeless'';
``\ldots{} you feel so depressed that nothing could cheer you up'';
``\ldots{} you feel worthless.''

\paragraph{Rumination (ordinal)}\label{rumination-ordinal}

\begin{itemize}
\tightlist
\item
  ``During the last 30 days, how often did\ldots you have negative
  thoughts that repeated over and over?'' and indicated their frequency
  of rumination on an ordinal scale
\end{itemize}

From Nolen-hoeksema and Morrow
(\citeproc{ref-nolen-hoeksema_effects_1993}{1993})

Ordinal responses: 0 = None of The Time, 1 = A little of The Time, 2 =
Some of The Time, 3 = Most of The Time, 4 = All of The Time.

\paragraph{Sexual Satisfaction (1 = Not satisfied to 7 = Very
satisfied).}\label{sexual-satisfaction-1-not-satisfied-to-7-very-satisfied.}

``How satisfied are you with your sex life?'' (developed for the NZAVS).

\subsubsection{Ego-related Well-being
Measures}\label{ego-related-well-being-measures}

\paragraph{Emotional Regulation (Out of Control) (1 = Strongly Disagree
to 7 = Strongly
Agree).}\label{emotional-regulation-out-of-control-1-strongly-disagree-to-7-strongly-agree.}

We measured participants' levels of emotional regulation using three
items adapted from Gratz and Roemer
(\citeproc{ref-gratz_multidimensional_2004}{2004}) and Gross and John
(\citeproc{ref-gross_individual_2003}{2003}):

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  ``When I feel negative emotions, my emotions feel out of control.'';
\item
  ``When I feel negative emotions, I suppress or hide my emotions.'';
\item
  ``When I feel negative emotions, I change the way I think to help me
  stay calm.''
\end{enumerate}

Prior to analysis, we selected the first item from this scale.

\paragraph{Perfectionism (1 = Strongly Disagree to 7 = Strongly
Agree)}\label{perfectionism-1-strongly-disagree-to-7-strongly-agree}

We assessed participants' perfectionism using three items from Rice
\emph{et al.} (\citeproc{ref-rice_short_2014}{2014}).

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  Doing my best never seems to be enough;
\item
  My performance rarely measures up to my standards;
\item
  I am hardly ever satisfied with my performance. Participants indicated
  the extent to which they agree with these items
\end{enumerate}

\paragraph{Permeability of the Self (1 = Strongly Disagree to 7 =
Strongly
Agree)}\label{permeability-of-the-self-1-strongly-disagree-to-7-strongly-agree}

``I believe I am capable, as an individual, of improving my status in
society.''

From Tausch \emph{et al.} (\citeproc{ref-tausch2015does}{2015}).

\paragraph{Power Dependence (1 = Strongly Disagree to 7 = Strongly
Agree)}\label{power-dependence-1-strongly-disagree-to-7-strongly-agree}

Participants' Power dependence was measured using two items:

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  I do not have enough power or control over important parts of my life;
\item
  Other people have too much power or control over important parts of my
  life.
\end{enumerate}

From Overall \emph{et al.} (\citeproc{ref-overall2016power}{2016}).

We used the first of these items.

\paragraph{Self Control (has) \& Self Control (wish had more) (1 =
Strongly Disagree to 7 = Strongly
Agree).}\label{self-control-has-self-control-wish-had-more-1-strongly-disagree-to-7-strongly-agree.}

Participants were asked to indicate the extent to which they endorse the
two items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ``In general, I have a lot of self-control''
\item
  ``I wish I had more self-discipline'' from Tangney \emph{et al.}
  (\citeproc{ref-tangney_high_2004}{2004}).
\end{enumerate}

We assessed these dimensions separately.

\paragraph{Self-Esteem (1 = Very inaccurate to 7 = Very
accurate)}\label{self-esteem-1-very-inaccurate-to-7-very-accurate}

Participants were instructed to circle the number that best represents
how accurately each statement describes them. Participants responded to
the items

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ``On the whole am satisfied with myself;''
\item
  ``Take a positive attitude toward myself;''
\item
  ``Am inclined to feel that I am a failure.''
\end{enumerate}

Adapted from Rosenberg (\citeproc{ref-Rosenberg1965}{1965}).

\subsubsection{Reflective Well-being
Measures}\label{reflective-well-being-measures}

\paragraph{Gratitude (1 = Strongly Disagree to 7 = Strongly
Agree)}\label{gratitude-1-strongly-disagree-to-7-strongly-agree}

We assessed the extent to which participants have gratitude using three
items from McCullough \emph{et al.}
(\citeproc{ref-mccullough_grateful_2002}{2002}):

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  ``I have much in my life to be thankful for.'';
\item
  ``When I look at the world, I don't see much to be grateful for.'';
  (reversed)
\item
  ``I am grateful to a wide variety of people.''
\end{enumerate}

\paragraph{Life Satisfaction (1 = Strongly Disagree to 7 = Strongly
Agree)}\label{life-satisfaction-1-strongly-disagree-to-7-strongly-agree}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ``I am satisfied with my life''\\
\item
  ``In most ways my life is close to ideal''.
\end{enumerate}

From the Satisfaction with Life Scale Diener \emph{et al.}
(\citeproc{ref-diener1985a}{1985}).

\paragraph{Meaning of Life (1 = Strongly Disagree to 7 = Strongly
Agree)}\label{meaning-of-life-1-strongly-disagree-to-7-strongly-agree}

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  ``My life has a clear sense of purpose;''
\item
  ``I have a good sense of what makes my life meaningful.''
\end{enumerate}

From Steger \emph{et al.} (\citeproc{ref-steger_meaning_2006}{2006})

We assessed these dimensions separately.

\paragraph{Personal Well-being Relationships (0 = completely
dissatisfied to 10 = completely
satisfied)}\label{personal-well-being-relationships-0-completely-dissatisfied-to-10-completely-satisfied}

Participants read an instruction (``Please rate your level of
satisfaction with the following aspects of your life and New Zealand.'')
and responded to an item:

\begin{itemize}
\tightlist
\item
  ``Your relationships''
\end{itemize}

From the Australian Unity Wellbeing Index
(\citeproc{ref-cummins_developing_2003}{Cummins \emph{et al.} 2003})

\paragraph{Personal Well-being Security (0 = completely dissatisfied to
10 = completely
satisfied)}\label{personal-well-being-security-0-completely-dissatisfied-to-10-completely-satisfied}

Participants read an instruction (``Please rate your level of
satisfaction with the following aspects of your life and New Zealand.'')
and responded to an item:

\begin{itemize}
\tightlist
\item
  ``Your future security''
\end{itemize}

From the Australian Unity Wellbeing Index
(\citeproc{ref-cummins_developing_2003}{Cummins \emph{et al.} 2003}).

\paragraph{Personal Well-being Standard Living (0 = completely
dissatisfied to 10 = completely
satisfied)}\label{personal-well-being-standard-living-0-completely-dissatisfied-to-10-completely-satisfied}

Participants read an instruction (``Please rate your level of
satisfaction with the following aspects of your life and New Zealand.'')
and responded to an item:

\begin{itemize}
\tightlist
\item
  ``Your standard of living''
\end{itemize}

From the Australian Unity Wellbeing Index
(\citeproc{ref-cummins_developing_2003}{Cummins \emph{et al.} 2003}).

\paragraph{Personal Well-being Your Health (0 = completely dissatisfied
to 10 = completely
satisfied)}\label{personal-well-being-your-health-0-completely-dissatisfied-to-10-completely-satisfied}

Participants read an instruction (``Please rate your level of
satisfaction with the following aspects of your life and New Zealand.'')
and responded to an item:

\begin{itemize}
\tightlist
\item
  ``Your Health''
\end{itemize}

From the Australian Unity Wellbeing Index
(\citeproc{ref-cummins_developing_2003}{Cummins \emph{et al.} 2003}).

\subsubsection{Social Well-being Outcomes
Measures}\label{social-well-being-outcomes-measures}

\paragraph{Sense of Neighbourhood Community (1 = Strongly Disagree to 7
= Strongly
Agree)}\label{sense-of-neighbourhood-community-1-strongly-disagree-to-7-strongly-agree}

\begin{itemize}
\tightlist
\item
  ``I feel a sense of community with others in my local neighbourhood.''
\end{itemize}

Item from Sengupta \emph{et al.} (\citeproc{ref-sengupta2013}{2013})

\paragraph{Sense of Social Belonging (1 = Very Inaccurate to 7 = Very
Accurate)}\label{sense-of-social-belonging-1-very-inaccurate-to-7-very-accurate}

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  ``Know that people in my life accept and value me'';
\item
  ``Feel like an outsider'' (reversed);
\item
  ``Know that people around me share my attitudes and beliefs''.
\end{enumerate}

Adapted from the Sense of Belonging Instrument
(\citeproc{ref-hagerty1995}{Hagerty and Patusky 1995})

\paragraph{Social Support (1 = Strongly Disagree to 7 = Strongly
Agree)}\label{social-support-1-strongly-disagree-to-7-strongly-agree}

\begin{enumerate}
\def\labelenumi{(\arabic{enumi})}
\tightlist
\item
  ``There are people I can depend on to help me if I really need it;''
\item
  ``There is no one I can turn to for guidance in times of stress;''
  (reversed)
\item
  ``I know there are people I can turn to when I need help.''
\end{enumerate}

From Cutrona and Russell (\citeproc{ref-cutrona1987}{1987}) and Williams
\emph{et al.} (\citeproc{ref-williams2000cyberostracism}{2000})

\subsubsection{Causal Interventions}\label{causal-interventions}

We define three modified treatment policies (refer to Haneuse and
Rotnitzky (\citeproc{ref-haneuse2013estimation}{2013}); Dı́az \emph{et
al.} (\citeproc{ref-diaz2021nonparametric}{2021}); Díaz \emph{et al.}
(\citeproc{ref-diaz2023lmtp}{2023})). Let \(A_t\) denote the treatment
variable, representing an individual's observed level of forgiveness at
time points \(t \in \{0,1,2\}\), with \(t=0\) as the baseline, \(t=1\)
as the treatment implementation, and \(t=2\) as the end of the study.
The function \(\mathbf{g}(\cdot)\) represents a modified treatment
policy.

Interventions are conceptualised as potential modifications to the
treatment levels from those originally observed. The notation \(a_i\)
indicates the treatment level assigned under the policy function
\(\mathbf{g}\). The symbol \(\tau\) denotes the population average
treatment effect (ATE), contrasting aggregate outcomes for the
population under the interventions compared.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Therapeutic Intervention}: elevate the forgiveness levels of
  individuals below the population average to this average, while
  keeping others unchanged: \[
  a_i = \mathbf{g}^\lambda(A_i) = \begin{cases} 
  \mu_A & \text{if } A_i < \mu_A \\ 
  A_i & \text{otherwise} 
  \end{cases}
  \] where \(\mu_A\) is the population average of forgiveness, defined
  as \(\mu_A = \frac{\sum_{i=1}^n A_i}{n}\).
\item
  \textbf{General Intervention}: elevate everyone's forgiveness by one
  point on a 1-7 Likert scale, ensuring the scale maximum is not
  exceeded: \[
  a_i = \mathbf{g}^\phi(A_i) = \begin{cases} 
  A_i + 1 & \text{if } A_i < 6 \\ 
  7 & \text{otherwise} 
  \end{cases}
  \]
\item
  \textbf{Status Quo --- No Treatment}: Apply no intervention. Expected
  mean outcomes are estimated using each individual's observed level of
  forgiveness: \[
  a_i = \mathbf{g}(A_i) = A_i
  \]
\end{enumerate}

\paragraph{Causal Contrasts}\label{causal-contrasts}

These policy interventions allow us to calculate the following contrasts
between population averages under different treatment policies:

\textbf{Contrast A: Therapeutic Intervention vs.~Status Quo} \[
   \tau^{\text{therapeutic}} = \mathbb{E}[Y(\mathbf{g}^\lambda) - Y(\mathbf{g})]
   \]

\textbf{Contrast B: General Intervention vs.~Status Quo} \[
   \tau^{\text{general}} = \mathbb{E}[Y(\mathbf{g}^\phi) - Y(\mathbf{g})]
   \]

\paragraph{Assumptions for Causal
Estimation}\label{assumptions-for-causal-estimation}

To estimate causal effects reliably, our study must credibly meet three
fundamental assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal Consistency}: we assume that the potential outcomes for
  a given individual under a particular treatment correspond to the
  observed outcomes when that treatment is actually administered. This
  assumes that potential outcomes are solely a function of the treatment
  and measured covariates, without interference by the mode of treatment
  administration (VanderWeele (\citeproc{ref-vanderweele2009}{2009});
  VanderWeele and Hernan (\citeproc{ref-vanderweele2013}{2013})).
\item
  \textbf{Exchangeability}: we assume that, conditional on observed
  covariates, assignment to treatment group is independent of the
  potential outcomes; that is we assume no unmeasured confounding
  (Hernan and Robins (\citeproc{ref-hernan2024WHATIF}{2024}); Chatton
  \emph{et al.} (\citeproc{ref-chatton2020}{2020})).
\item
  \textbf{Positivity}: we assume that within all covariate-defined
  strata necessary for achieving exchangeability, there is a non-zero
  probability of receiving each possible treatment level. The positivity
  assumption ensures that treatment effects are estimable across the
  spectrum of observed covariate combinations (Westreich and Cole
  (\citeproc{ref-westreich2010}{2010})).
\end{enumerate}

\subsubsection{Target Population}\label{target-population}

The target population for this study comprises New Zealand residents as
represented in the baseline wave of the New Zealand Attitudes and Values
Study (NZAVS) during the years 2018-2019, weighted by New Zealand Census
weights for age, gender, and ethnicity (refer to Sibley
(\citeproc{ref-sibley2021}{2021})). The NZAVS is a national probability
study designed to accurately reflect the broader New Zealand population.
Despite its comprehensive scope, the NZAVS does have some limitations in
its demographic representation. Notably, it tends to under-sample males
and individuals of Asian descent while over-sampling females and Māori
(the indigenous peoples of New Zealand). To address these disparities
and enhance the accuracy of our findings, we apply New Zealand Census
survey weights to the sample data. These weights adjust for variations
in age, gender, and ethnicity to better approximate the national
demographic composition (\citeproc{ref-sibley2021}{Sibley 2021}). Survey
weights were integrated into statistical models using the
\texttt{weights} option in \texttt{lmtp}
(\citeproc{ref-williams2021}{Williams and Díaz 2021}), following
protocols stated in Bulbulia
(\citeproc{ref-bulbulia2024PRACTICAL}{2024a}).

\subsubsection{Eligibility}\label{eligibility}

\subsubsection{Inclusion Criteria}\label{inclusion-criteria}

\begin{itemize}
\tightlist
\item
  Enrolled in the 2018 wave of the New Zealand Attitudes and Values
  Study (NZAVS time 10).
\item
  Missing covariate data at baseline was permitted, and the data was
  subjected to imputation methods to reduce bias. Only information
  obtained at baseline was used for such imputation (refer to Zhang
  \emph{et al.}
  (\citeproc{ref-zhang2023shouldMultipleImputation}{2023})).
  Participants may have been lost to follow-up at the end of the study
  NZAVS time 12 if they met eligibility criteria at NZAVS time 11 (the
  treatment wave). We adjusted for attrition and non-response using
  censoring weights, described below.
\end{itemize}

\subsubsection{Exclusion Criteria}\label{exclusion-criteria}

\begin{itemize}
\tightlist
\item
  Did not answer the forgiveness question at New Zealand Attitudes and
  Values Study at time 10 (the baseline wave) and NZAVS time 11 (the
  treatment wave).
\end{itemize}

A total of 34,749 individuals met these criteria and were included in
the study.

\subsubsection{Causal Identification}\label{causal-identification}

\begin{table}

\caption{\label{tbl-02}This table presents a causal diagram using
VanderWeele \emph{et al.} (\citeproc{ref-vanderweele2020}{2020})'s
approach for confounding control in a three-wave panel design. By
including baseline measures of all outcomes in every model, as well as
including the baseline treatment, and a rich array of covariates, we
assume may back door paths between the treatment and outcomes will be
blocked. However, because confounding cannot be ensured, we also perform
sensitivity analyses.}

\centering{

\threevanderweeele

}

\end{table}%

To address confounding in our analysis, we implement VanderWeele
(\citeproc{ref-vanderweele2019}{2019})'s \emph{modified disjunctive
cause criterion} by following these steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Identified all common causes} of both the treatment and
  outcomes to ensure a comprehensive approach to confounding control.
\item
  \textbf{Excluded instrumental variables} that affect the exposure but
  not the outcome. Instrumental variables do not contribute to
  controlling confounding and can reduce the efficiency of the
  estimates.
\item
  \textbf{Included proxies for unmeasured confounders} affecting both
  exposure and outcome. According to the principles of d-separation,
  using proxies allows us to control for their associated unmeasured
  confounders indirectly.
\item
  \textbf{Controlled for baseline exposure} and \textbf{baseline
  outcome}. Both are used as proxies for unmeasured common causes,
  enhancing the robustness of our causal estimates.
\end{enumerate}

Table~\ref{tbl-02} presents a causal diagram describing the general
confounding control of VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020}).

\hyperref[appendix-demographics]{Appendix B} details the covariates we
included for confounding control. These methods adhere to the guidelines
provided in (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024a}) and
were pre-specified in our study protocol \url{https://osf.io/ce4t9/}.

\subsubsection{Missing Data}\label{missing-data}

To address bias from missing responses and attrition, we implement the
following strategies:

\textbf{Baseline missingness}: we employed the \texttt{ppm} algorithm
from the \texttt{mice} package in R (\citeproc{ref-vanbuuren2018}{Van
Buuren 2018}) to impute missing baseline data. This method allowed us to
reconstruct incomplete datasets by estimating a plausible value for
missing observation. Because we could only pass one data set to the
\texttt{lmtp}, we employed single imputation. 1.3\% of covariate values
were missing at baseline. Eligibility for the study required fully
observed baseline treatment measures as well as treatment wave treatment
measures. Again, we only used baseline data to impute baseline
missingness (refer to Zhang \emph{et al.}
(\citeproc{ref-zhang2023shouldMultipleImputation}{2023})).

\textbf{Outcome missingness}: to address confounding and selection bias
arising from missing responses and panel attrition, we applied censoring
weights obtained using nonparametric machine learning ensembles afforded
by the \texttt{lmtp} package (and its dependencies) in R
(\citeproc{ref-williams2021}{Williams and Díaz 2021}).

\subsubsection{Statistical Estimator}\label{statistical-estimator}

We perform statistical estimation using Targeted Learning (TMLE) TMLE
operates through a two-step process that involves modelling both the
outcome and treatment (exposure). In implementing TMLE, we employ
machine learning algorithms and five-fold cross-validation to flexibly
model the relationship between treatments, covariates, and outcomes.
Machine learning allows us to efficiently account for complex,
high-dimensional covariate spaces without imposing restrictive model
assumptions (\citeproc{ref-van2014discussion}{Laan \emph{et al.} 2014};
\citeproc{ref-vanderlaan2011}{Van Der Laan and Rose 2011},
\citeproc{ref-vanderlaan2018}{2018}). The outcome of this step is a set
of initial estimates for these relationships.

The second step of TMLE involves ``targeting'' these initial estimates
by incorporating information about the observed data distribution to
improve the accuracy of the causal effect estimate
(\citeproc{ref-van2014discussion}{Laan \emph{et al.} 2014}). A central
feature of TMLE is its double-robustness property. If either the
treatment model or the outcome model is correctly specified, the TMLE
estimator will consistently estimate the causal effect. Again we used
five-fold cross-validation following the protocols stated in Bulbulia
(\citeproc{ref-bulbulia2024PRACTICAL}{2024a}). We perform estimation
using the \texttt{lmtp} package (\citeproc{ref-williams2021}{Williams
and Díaz 2021}). We used the \texttt{superlearner} library for
semi-parametric estimation with the predefined libraries
\texttt{SL.ranger}, \texttt{SL.glmnet}, and \texttt{SL.xgboost}
(\citeproc{ref-xgboost2023}{Chen \emph{et al.} 2023};
\citeproc{ref-polley2023}{Polley \emph{et al.} 2023};
\citeproc{ref-Ranger2017}{Wright and Ziegler 2017}).
W\textbf{\texttt{SL.ranger}}: implements a random forest algorithm that
handles non-linear relationships and complex patterns, improving model
accuracy but potentially increasing variance.
\textbf{\texttt{SL.glmnet}}: provides regularised linear models that
help manage high dimensionality and collinearity, effectively reducing
model variance and improving stability. \textbf{\texttt{SL.xgboost}}:
uses gradient boosting to optimize performance and capture complex
interactions, balancing the model's ability to explore data complexities
without overfitting (\citeproc{ref-polley2023}{Polley \emph{et al.}
2023}). The ensemble approach of \texttt{superlearner} optimally
combines predictions from these models. Gaphs, tables and output reports
were created using the \texttt{margot} package
(\citeproc{ref-margot2024}{Bulbulia 2024b}). For further details of the
targeted learning using \texttt{lmtp} see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023}).

\subsubsection{P-Values}\label{p-values}

We reiterate that our primary interest does not lie in testing specific
hypotheses; thus, we do not report p-values or adjusted p-values.
Instead, all causal contrasts are presented with point estimates
alongside 95\% confidence intervals. This approach aims to quantify the
uncertainty associated with our estimates, conditioned on the available
data, the statistical models employed, and the validity of our causal
assumptions.

\subsubsection{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess the sensitivity of results to unmeasured confounding, we
report VanderWeele and Ding's E-value in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). To
evaluate the strength of evidence, we use the bound of the E-value 95\%
confidence interval closest to 1. Although the E-value provides an
approximate sensitivity analysis, its interpretation is straightforward.

\subsubsection{Scope of Interventions}\label{scope-of-interventions}

To illustrate the magnitude of the shift interventions we contrast, we
provide histograms in Figure~\ref{fig-hist} that display the
distribution of forgiveness during the treatment wave.
Figure~\ref{fig-hist} \emph{A}: clarifies the shift required for the
\emph{therapeutic intervention} in which all below average are shifted
to average forgiveness. Figure~\ref{fig-hist} \emph{B}: clarifies the
shift required for the \emph{general intervention} in which the entire
population is nudged upward in forgiveness by one unit on a 1-7 Likert
scale, up to the maximum value of seven.

\begin{figure}

\centering{

\includegraphics{24-rc-forgive-flourish_files/figure-pdf/fig-hist-1.pdf}

}

\caption{\label{fig-hist}Histogram of shift interventions. (A) Orange
describes those shifted in the thearapeutic intervention. All those
responses in grey (four and above) remain unchanged. (B) Gold denotes
those shifted up by less than one point in forgiveness, thus preserving
the scale's maximum value. The control for each intervention is the
status quo: no intervention.}

\end{figure}%

\newpage{}

\subsubsection{Evidence for Change in the Treatment
Variable}\label{evidence-for-change-in-the-treatment-variable}

Table~\ref{tbl-transition} clarifies the change in the treatment
variable from the baseline wave to the baseline + 1 wave across the
sample. Assessing change in a variable is essential for evaluating the
positivity assumption and recovering evidence for the incident-exposure
effect of the treatment variable (\citeproc{ref-danaei2012}{Danaei
\emph{et al.} 2012}; \citeproc{ref-hernan2024WHATIF}{Hernan and Robins
2024}; \citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1184}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1184}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1184}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1184}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1316}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1316}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1316}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1316}}@{}}

\caption{\label{tbl-transition}This transition matrix captures stability
and change in forgiveness between the baseline and treatment wave. Each
cell in the matrix represents the count of individuals transitioning
from one state to another. The rows correspond to the state at baseline
(From), and the columns correspond to the state at the treatment wave
(To). \textbf{Diagonal entries} (in \textbf{bold}) signify the number of
individuals who remained in their initial state across both waves.
\textbf{Off-diagonal entries} signify the transitions of individuals
from their baseline state to a different state in the treatment wave. A
higher number on the diagonal relative to the off-diagonal entries in
the same row indicates greater stability in a state. Conversely, higher
off-diagonal numbers suggest more frequent shifts in the sample from the
baseline state to other states.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 1 & \textbf{80} & 72 & 49 & 30 & 10 & 10 & 3 \\
State 2 & 94 & \textbf{289} & 317 & 198 & 107 & 27 & 3 \\
State 3 & 59 & 358 & \textbf{911} & 961 & 542 & 196 & 26 \\
State 4 & 31 & 222 & 920 & \textbf{1935} & 1820 & 804 & 114 \\
State 5 & 9 & 120 & 467 & 1743 & \textbf{3722} & 3013 & 485 \\
State 6 & 6 & 27 & 163 & 735 & 2637 & \textbf{5582} & 1849 \\
State 7 & 3 & 7 & 34 & 111 & 440 & 1449 & \textbf{1959} \\

\end{longtable}

\newpage{}

\subsection{Results}\label{results}

\subsubsection{Study 1: Health Outcomes}\label{study-1-health-outcomes}

\paragraph{Therapeutic Intervention}\label{therapeutic-intervention}

Figure~\ref{fig-1_1} \emph{A} and Table~\ref{tbl-1_1}. describe results
of the therapeutic forgiveness intervention on health

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3827}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1975}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0864}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0864}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0988}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1481}}@{}}

\caption{\label{tbl-1_1}This table reports the results of model
estimates for the causal effects shifting all those below average
forgiveness to average on health outcomes. The contrast condition is the
status quo (no shift). Contrasts are expressed in standard deviation
units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Short form health, your health & 0.025 & 0.018 & 0.032 & 1.176 &
1.145 \\
Hours sleep & 0.012 & 0.003 & 0.020 & 1.114 & 1.058 \\
Hours excercise & 0.002 & -0.006 & 0.011 & 1.050 & 1.000 \\
BMI & 0.000 & -0.004 & 0.004 & 1.010 & 1.000 \\
Alcohol frequency & -0.002 & -0.008 & 0.004 & 1.049 & 1.000 \\
Alcohol intensity & -0.009 & -0.017 & 0.000 & 1.098 & 1.019 \\

\end{longtable}

The Average Treatment Effect (ATE) measures the mean difference in
outcomes between treatment and contrast groups within the target
population.

For `Short form health, your health', the effect estimate on the
causal\_difference scale is 0.025 {[}0.0177, 0.0321{]}. The E-value for
this estimate is 1.176, with a lower bound of 1.1445. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.1445 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Hours sleep', the effect estimate on the causal\_difference scale
is 0.012 {[}0.0033, 0.0197{]}. The E-value for this estimate is 1.1136,
with a lower bound of 1.0578. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.0578 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality is weak}.

For `Hours excercise', the effect estimate on the causal\_difference
scale is 0.002 {[}-0.0063, 0.0113{]}. The E-value for this estimate is
1.0501, with a lower bound of 1. The \textbf{evidence for causality is
not reliable}.

For `BMI', the effect estimate on the causal\_difference scale is 0
{[}-0.0044, 0.0043{]}. The E-value for this estimate is 1.0096, with a
lower bound of 1. The \textbf{evidence for causality is not reliable}.

For `Alcohol frequency', the effect estimate on the causal\_difference
scale is -0.002 {[}-0.0083, 0.0036{]}. The E-value for this estimate is
1.049, with a lower bound of 1. The \textbf{evidence for causality is
not reliable}.

For `Alcohol intensity', the effect estimate on the causal\_difference
scale is -0.009 {[}-0.0173, -4e-04{]}. The E-value for this estimate is
1.0981, with a lower bound of 1.0192. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.0192 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality is weak}.

Finally, for `Smoker', the effect estimate on the risk\_ratio scale is
0.985 {[}0.951, 1.019{]}. The E-value for this estimate is 1.14, with a
lower bound of 1. The \textbf{evidence for causality is not reliable}.

\paragraph{General Intervention}\label{general-intervention}

Figure~\ref{fig-1_1} \emph{B} and Table~\ref{tbl-1_2} describe results
for the therapeutic forgiveness interventions

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3827}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1975}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0864}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0864}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0988}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1481}}@{}}

\caption{\label{tbl-1_2}This table reports the results of model
estimates for the causal effects shifting everyone up by one point in
forgiveness to the maximum of the range on health outcomes. The contrast
condition is the status quo (no shift). Contrasts are expressed in
standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Short form health, your health & 0.045 & 0.035 & 0.054 & 1.250 &
1.216 \\
Hours sleep & 0.019 & 0.008 & 0.029 & 1.151 & 1.088 \\
Hours excercise & 0.003 & -0.009 & 0.015 & 1.055 & 1.000 \\
Alcohol frequency & 0.002 & -0.007 & 0.010 & 1.045 & 1.000 \\
BMI & -0.002 & -0.007 & 0.004 & 1.045 & 1.000 \\
Alcohol intensity & -0.020 & -0.030 & -0.009 & 1.155 & 1.106 \\

\end{longtable}

For `Short form health, your health', the effect estimate on the
causal\_difference scale is 0.045 {[}0.035, 0.054{]}. The E-value for
this estimate is 1.25, with a lower bound of 1.216. At this lower bound,
unmeasured confounders would need a minimum association strength with
both the intervention sequence and outcome of 1.216 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Hours sleep', the effect estimate on the causal\_difference scale
is 0.019 {[}0.008, 0.029{]}. The E-value for this estimate is 1.151,
with a lower bound of 1.088. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.088 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality is weak}.

For `Hours excercise', the effect estimate on the causal\_difference
scale is 0.003 {[}-0.009, 0.015{]}. The E-value for this estimate is
1.055, with a lower bound of 1. The \textbf{evidence for causality is
not reliable}.

For `Alcohol frequency', the effect estimate on the causal\_difference
scale is 0.002 {[}-0.007, 0.01{]}. The E-value for this estimate is
1.045, with a lower bound of 1. The \textbf{evidence for causality is
not reliable}.

For `BMI', the effect estimate on the causal\_difference scale is -0.002
{[}-0.007, 0.004{]}. The E-value for this estimate is 1.045, with a
lower bound of 1. The \textbf{evidence for causality is not reliable}.

For `Alcohol intensity', the effect estimate on the causal\_difference
scale is -0.02 {[}-0.03, -0.009{]}. The E-value for this estimate is
1.155, with a lower bound of 1.106. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.106 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

Finally, for `Smoker', the effect estimate on the risk\_ratio scale is
0.985 {[}0.951, 1.019{]}. The E-value for this estimate is 1.14, with a
lower bound of 1. The \textbf{evidence for causality is not reliable}.

\begin{figure}

\centering{

\includegraphics{24-rc-forgive-flourish_files/figure-pdf/fig-1_1-1.pdf}

}

\caption{\label{fig-1_1}This figure reports the results for both the (A)
therapeutic (B) general forgiveness interventions on health outcomes.
The contrast condition is the status quo (no shift). Contrasts are
expressed in standard deviation units.}

\end{figure}%

\newpage{}

\subsubsection{Study 2: Embodied Well-Being
Outcomes}\label{study-2-embodied-well-being-outcomes}

\paragraph{Therapeutic Intervention}\label{therapeutic-intervention-1}

Figure~\ref{fig-2_1} \emph{A} and Table~\ref{tbl-2_1} describe results
for the therapeutic forgiveness interventions

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2958}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-2_1}This table reports the results of model
estimates for the causal effects shifting all those below average
forgiveness to average on embodied well-being outcomes. The contrast
condition is the status quo (no shift). Contrasts are expressed in
standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Sexual satisfaction & 0.023 & 0.016 & 0.031 & 1.168 & 1.133 \\
Body satisfaction & 0.022 & 0.014 & 0.029 & 1.164 & 1.128 \\
Fatigue & -0.024 & -0.031 & -0.016 & 1.172 & 1.138 \\
Kessler 6 anxiety & -0.038 & -0.046 & -0.031 & 1.226 & 1.197 \\
Kessler 6 depression & -0.047 & -0.055 & -0.039 & 1.257 & 1.230 \\
Rumination & -0.062 & -0.070 & -0.053 & 1.306 & 1.281 \\

\end{longtable}

For `Sexual satisfaction', the effect estimate on the causal\_difference
scale is 0.023 {[}0.016, 0.031{]}. The E-value for this estimate is
1.168, with a lower bound of 1.133. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.133 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Body satisfaction', the effect estimate on the causal\_difference
scale is 0.022 {[}0.014, 0.029{]}. The E-value for this estimate is
1.164, with a lower bound of 1.128. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.128 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Fatigue', the effect estimate on the causal\_difference scale is
-0.024 {[}-0.031, -0.016{]}. The E-value for this estimate is 1.172,
with a lower bound of 1.138. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.138 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

For `Kessler 6 anxiety', the effect estimate on the causal\_difference
scale is -0.038 {[}-0.046, -0.031{]}. The E-value for this estimate is
1.226, with a lower bound of 1.197. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.197 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Kessler 6 depression', the effect estimate on the
causal\_difference scale is -0.047 {[}-0.055, -0.039{]}. The E-value for
this estimate is 1.257, with a lower bound of 1.23. At this lower bound,
unmeasured confounders would need a minimum association strength with
both the intervention sequence and outcome of 1.23 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Rumination', the effect estimate on the causal\_difference scale is
-0.062 {[}-0.07, -0.053{]}. The E-value for this estimate is 1.306, with
a lower bound of 1.281. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.281 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

\paragraph{General Intervention}\label{general-intervention-1}

Figure~\ref{fig-2_1} \emph{B} and Table~\ref{tbl-2_2} describe results
for the general forgiveness interventions

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2958}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2254}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0986}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1127}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1690}}@{}}

\caption{\label{tbl-2_2}This table reports the results of model
estimates for the causal effects shifting everyone up by one point in
forgiveness (to the maximum of the range) on embodied well-being
outcomes. The contrast condition is the status quo (no shift). Contrasts
are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Sexual satisfaction & 0.033 & 0.022 & 0.044 & 1.208 & 1.169 \\
Body satisfaction & 0.029 & 0.019 & 0.040 & 1.192 & 1.152 \\
Fatigue & -0.001 & -0.011 & 0.010 & 1.031 & 1.000 \\
Kessler 6 depression & -0.041 & -0.051 & -0.031 & 1.237 & 1.201 \\
Kessler 6 anxiety & -0.060 & -0.070 & -0.050 & 1.300 & 1.268 \\
Rumination & -0.077 & -0.087 & -0.066 & 1.352 & 1.322 \\

\end{longtable}

For `Sexual satisfaction', the effect estimate on the causal\_difference
scale is 0.033 {[}0.022, 0.044{]}. The E-value for this estimate is
1.208, with a lower bound of 1.169. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.169 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Body satisfaction', the effect estimate on the causal\_difference
scale is 0.029 {[}0.019, 0.04{]}. The E-value for this estimate is
1.192, with a lower bound of 1.152. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.152 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Fatigue', the effect estimate on the causal\_difference scale is
-0.001 {[}-0.011, 0.01{]}. The E-value for this estimate is 1.031, with
a lower bound of 1. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1 to negate the observed effect. Weaker confounding would
not overturn it. The \textbf{evidence for causality is not reliable}.

For `Kessler 6 depression', the effect estimate on the
causal\_difference scale is -0.041 {[}-0.051, -0.031{]}. The E-value for
this estimate is 1.237, with a lower bound of 1.201. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.201 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Kessler 6 anxiety', the effect estimate on the causal\_difference
scale is -0.06 {[}-0.07, -0.05{]}. The E-value for this estimate is 1.3,
with a lower bound of 1.268. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.268 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

For `Rumination', the effect estimate on the causal\_difference scale is
-0.077 {[}-0.087, -0.066{]}. The E-value for this estimate is 1.352,
with a lower bound of 1.322. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.322 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

\begin{figure}

\centering{

\includegraphics{24-rc-forgive-flourish_files/figure-pdf/fig-2_1-1.pdf}

}

\caption{\label{fig-2_1}This figure reports the results for both the (A)
therapeutic (B) general forgiveness interventions on embodied
well-being. The contrast condition is the status quo (no shift).
Contrasts are expressed in standard deviation units.}

\end{figure}%

\newpage{}

\subsubsection{Study 3: Ego-Related Well-Being
Outcomes}\label{study-3-ego-related-well-being-outcomes}

\paragraph{Therapeutic Intervention}\label{therapeutic-intervention-2}

Figure~\ref{fig-3_1} \emph{A} and Table~\ref{tbl-3_1} describe results
for the therapeutic forgiveness interventions on ego-related well-being.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4318}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1818}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0795}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0795}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0909}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1364}}@{}}

\caption{\label{tbl-3_1}This table reports the results of model
estimates for the causal effects shifting all those below average
forgiveness to average on ego-related well-being outcomes. The contrast
condition is the status quo (no shift). Contrasts are expressed in
standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Self esteem & 0.036 & 0.029 & 0.042 & 1.219 & 1.197 \\
Self control wish more (reversed) & 0.018 & 0.011 & 0.025 & 1.146 &
1.106 \\
Self control have & 0.016 & 0.008 & 0.023 & 1.137 & 1.094 \\
Permeability self & 0.013 & 0.004 & 0.021 & 1.122 & 1.074 \\
Perfectionism & -0.039 & -0.046 & -0.032 & 1.230 & 1.208 \\
Power no control & -0.051 & -0.058 & -0.043 & 1.271 & 1.244 \\
Emotional regulation (out of control) & -0.055 & -0.063 & -0.047 & 1.284
& 1.258 \\

\end{longtable}

For `Self-esteem', the effect estimate on the causal\_difference scale
is 0.036 {[}0.029, 0.042{]}. The E-value for this estimate is 1.219,
with a lower bound of 1.197. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.197 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

For `Self-control wish more (reversed)', the effect estimate on the
causal\_difference scale is 0.018 {[}0.011, 0.025{]}. The E-value for
this estimate is 1.146, with a lower bound of 1.106. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.106 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Self-control have', the effect estimate on the causal\_difference
scale is 0.016 {[}0.008, 0.023{]}. The E-value for this estimate is
1.137, with a lower bound of 1.094. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.094 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality is weak}.

For `Permeability self', the effect estimate on the causal\_difference
scale is 0.013 {[}0.004, 0.021{]}. The E-value for this estimate is
1.122, with a lower bound of 1.074. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.074 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality is weak}.

For `Perfectionism', the effect estimate on the causal\_difference scale
is -0.039 {[}-0.046, -0.032{]}. The E-value for this estimate is 1.23,
with a lower bound of 1.208. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.208 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

For `Power no control', the effect estimate on the causal\_difference
scale is -0.051 {[}-0.058, -0.043{]}. The E-value for this estimate is
1.271, with a lower bound of 1.244. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.244 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Emotional regulation (out of control)', the effect estimate on the
causal\_difference scale is -0.055 {[}-0.063, -0.047{]}. The E-value for
this estimate is 1.284, with a lower bound of 1.258. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.258 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

\paragraph{General Intervention}\label{general-intervention-2}

Figure~\ref{fig-3_1} \emph{B} and Table~\ref{tbl-3_2} describe results
for the general forgiveness interventions on ego-related well-being

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4318}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1818}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0795}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0795}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0909}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1364}}@{}}

\caption{\label{tbl-3_2}This table reports the results of model
estimates for the causal effects shifting everyone up by one point in
forgiveness (to the maximum of the range) on ego-related well-being
outcomes. The contrast condition is the status quo (no shift). Contrasts
are expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Self esteem & 0.036 & 0.029 & 0.042 & 1.219 & 1.197 \\
Self control wish more (reversed) & 0.018 & 0.011 & 0.025 & 1.146 &
1.106 \\
Self control have & 0.016 & 0.008 & 0.023 & 1.137 & 1.094 \\
Permeability self & 0.013 & 0.004 & 0.021 & 1.122 & 1.074 \\
Perfectionism & -0.039 & -0.046 & -0.032 & 1.230 & 1.208 \\
Power no control & -0.051 & -0.058 & -0.043 & 1.271 & 1.244 \\
Emotional regulation (out of control) & -0.055 & -0.063 & -0.047 & 1.284
& 1.258 \\

\end{longtable}

For `Self esteem', the effect estimate on the causal\_difference scale
is 0.036 {[}0.029, 0.042{]}. The E-value for this estimate is 1.219,
with a lower bound of 1.197. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.197 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

For `Self control wish more (reversed)', the effect estimate on the
causal\_difference scale is 0.018 {[}0.011, 0.025{]}. The E-value for
this estimate is 1.146, with a lower bound of 1.106. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.106 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Self control have', the effect estimate on the causal\_difference
scale is 0.016 {[}0.008, 0.023{]}. The E-value for this estimate is
1.137, with a lower bound of 1.094. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.094 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality is weak}.

For `Permeability self', the effect estimate on the causal\_difference
scale is 0.013 {[}0.004, 0.021{]}. The E-value for this estimate is
1.122, with a lower bound of 1.074. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.074 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality is weak}.

For `Perfectionism', the effect estimate on the causal\_difference scale
is -0.039 {[}-0.046, -0.032{]}. The E-value for this estimate is 1.23,
with a lower bound of 1.208. At this lower bound, unmeasured confounders
would need a minimum association strength with both the intervention
sequence and outcome of 1.208 to negate the observed effect. Weaker
confounding would not overturn it. Here, \textbf{there is evidence for
causality}.

For `Power no control', the effect estimate on the causal\_difference
scale is -0.051 {[}-0.058, -0.043{]}. The E-value for this estimate is
1.271, with a lower bound of 1.244. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.244 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Emotional regulation (out of control)', the effect estimate on the
causal\_difference scale is -0.055 {[}-0.063, -0.047{]}. The E-value for
this estimate is 1.284, with a lower bound of 1.258. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.258 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

\begin{figure}

\centering{

\includegraphics{24-rc-forgive-flourish_files/figure-pdf/fig-3_1-1.pdf}

}

\caption{\label{fig-3_1}This figure reports the results for both the (A)
therapeutic (B) general forgiveness interventions on ego-related
well-being. The contrast condition is the status quo (no shift).
Contrasts are expressed in standard deviation units.}

\end{figure}%

\newpage{}

\subsubsection{Study 4: Reflective Well-Being
Outcomes}\label{study-4-reflective-well-being-outcomes}

\paragraph{Therapeutic Intervention}\label{therapeutic-intervention-3}

Figure~\ref{fig-4_1} \emph{A} and Table~\ref{tbl-4_1} describe results
for the therapeutic forgiveness interventions on reflective well-being

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5196}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1569}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0588}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0686}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1176}}@{}}

\caption{\label{tbl-4_1}This table reports the results of model
estimates for the causal effects shifting all those below average
forgiveness to average on embodied well-being outcomes. The contrast
condition is the status quo (no shift). Contrasts are expressed in
standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Gratitude & 0.037 & 0.030 & 0.045 & 1.222 & 1.193 \\
Satisfaction with life & 0.035 & 0.028 & 0.042 & 1.215 & 1.185 \\
PWB your relationships & 0.034 & 0.026 & 0.042 & 1.211 & 1.181 \\
Meaning: clear sense of purpose & 0.028 & 0.021 & 0.036 & 1.189 &
1.156 \\
Meaning: good sense of what makes my life meaningful & 0.024 & 0.016 &
0.033 & 1.172 & 1.138 \\
PWB your health & 0.022 & 0.015 & 0.030 & 1.164 & 1.128 \\
PWB your standard living & 0.019 & 0.011 & 0.027 & 1.151 & 1.112 \\
PWB your future security & 0.016 & 0.008 & 0.024 & 1.137 & 1.094 \\

\end{longtable}

For `Gratitude', the effect estimate on the causal\_difference scale is
0.037 {[}0.03, 0.045{]}. The E-value for this estimate is 1.222, with a
lower bound of 1.193. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1.193 to negate the observed effect. Weaker confounding
would not overturn it. Here, \textbf{there is evidence for causality}.

For `Satisfaction with life', the effect estimate on the
causal\_difference scale is 0.035 {[}0.028, 0.042{]}. The E-value for
this estimate is 1.215, with a lower bound of 1.185. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.185 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `PWB your relationships', the effect estimate on the
causal\_difference scale is 0.034 {[}0.026, 0.042{]}. The E-value for
this estimate is 1.211, with a lower bound of 1.181. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.181 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Meaning: clear sense of purpose', the effect estimate on the
causal\_difference scale is 0.028 {[}0.021, 0.036{]}. The E-value for
this estimate is 1.189, with a lower bound of 1.156. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.156 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Meaning: good sense of what makes my life meaningful', the effect
estimate on the causal\_difference scale is 0.024 {[}0.016, 0.033{]}.
The E-value for this estimate is 1.172, with a lower bound of 1.138. At
this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.138 to negate the observed effect. Weaker confounding would not
overturn it. Here, \textbf{there is evidence for causality}.

For `PWB your health', the effect estimate on the causal\_difference
scale is 0.022 {[}0.015, 0.03{]}. The E-value for this estimate is
1.164, with a lower bound of 1.128. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.128 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `PWB your standard living', the effect estimate on the
causal\_difference scale is 0.019 {[}0.011, 0.027{]}. The E-value for
this estimate is 1.151, with a lower bound of 1.112. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.112 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `PWB your future security', the effect estimate on the
causal\_difference scale is 0.016 {[}0.008, 0.024{]}. The E-value for
this estimate is 1.137, with a lower bound of 1.094. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.094 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality is weak}.

\paragraph{General Intervention}\label{general-intervention-3}

Figure~\ref{fig-4_1} \emph{B} and Table~\ref{tbl-4_2} describe results
for the general forgiveness interventions

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.5196}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1569}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0588}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0686}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1176}}@{}}

\caption{\label{tbl-4_2}This table reports the results of model
estimates for the causal effects shifting everyone up by one point in
forgiveness (to the maximum of the range) on reflective well-being. The
constrast condition is the status quo (no shift). Contrasts are
expressed in standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Gratitude & 0.089 & 0.076 & 0.102 & 1.387 & 1.347 \\
Satisfaction with life & 0.082 & 0.072 & 0.091 & 1.366 & 1.337 \\
Meaning: clear sense of purpose & 0.078 & 0.068 & 0.088 & 1.355 &
1.325 \\
Meaning: good sense of what makes my life meaningful & 0.061 & 0.051 &
0.072 & 1.303 & 1.271 \\
PWB your relationships & 0.053 & 0.043 & 0.064 & 1.277 & 1.244 \\
PWB your future security & 0.051 & 0.041 & 0.062 & 1.271 & 1.237 \\
PWB your standard living & 0.049 & 0.038 & 0.059 & 1.264 & 1.230 \\
PWB your health & 0.047 & 0.033 & 0.060 & 1.257 & 1.209 \\

\end{longtable}

For `Gratitude', the effect estimate on the causal\_difference scale is
0.089 {[}0.076, 0.102{]}. The E-value for this estimate is 1.387, with a
lower bound of 1.347. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1.347 to negate the observed effect. Weaker confounding
would not overturn it. Here, \textbf{there is evidence for causality}.

For `Satisfaction with life', the effect estimate on the
causal\_difference scale is 0.082 {[}0.072, 0.091{]}. The E-value for
this estimate is 1.366, with a lower bound of 1.337. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.337 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Meaning: clear sense of purpose', the effect estimate on the
causal\_difference scale is 0.078 {[}0.068, 0.088{]}. The E-value for
this estimate is 1.355, with a lower bound of 1.325. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.325 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Meaning: good sense of what makes my life meaningful', the effect
estimate on the causal\_difference scale is 0.061 {[}0.051, 0.072{]}.
The E-value for this estimate is 1.303, with a lower bound of 1.271. At
this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1.271 to negate the observed effect. Weaker confounding would not
overturn it. Here, \textbf{there is evidence for causality}.

For `PWB your relationships', the effect estimate on the
causal\_difference scale is 0.053 {[}0.043, 0.064{]}. The E-value for
this estimate is 1.277, with a lower bound of 1.244. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.244 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `PWB your future security', the effect estimate on the
causal\_difference scale is 0.051 {[}0.041, 0.062{]}. The E-value for
this estimate is 1.271, with a lower bound of 1.237. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.237 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `PWB your standard living', the effect estimate on the
causal\_difference scale is 0.049 {[}0.038, 0.059{]}. The E-value for
this estimate is 1.264, with a lower bound of 1.23. At this lower bound,
unmeasured confounders would need a minimum association strength with
both the intervention sequence and outcome of 1.23 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `PWB your health', the effect estimate on the causal\_difference
scale is 0.047 {[}0.033, 0.06{]}. The E-value for this estimate is
1.257, with a lower bound of 1.209. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.209 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

\begin{figure}

\centering{

\includegraphics{24-rc-forgive-flourish_files/figure-pdf/fig-4_1-1.pdf}

}

\caption{\label{fig-4_1}This figure reports the results for both the (A)
therapeutic (B) general forgiveness interventions on reflective
well-being. The contrast condition is the status quo (no shift).
Contrasts are expressed in standard deviation units.}

\end{figure}%

\newpage{}

\subsubsection{Study 5: Social Well-Being
Outcomes}\label{study-5-social-well-being-outcomes}

\paragraph{Therapeutic Intervention}\label{therapeutic-intervention-4}

Figure~\ref{fig-5_1} \emph{B} and Table~\ref{tbl-5_1} describe results
for the therapeutic forgiveness interventions on social well-being

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3288}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2192}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0822}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0959}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1096}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1644}}@{}}

\caption{\label{tbl-5_1}This table reports the results of model
estimates for the causal effects shifting all those below average
forgiveness to average on social well-being outcomes. The contrast
condition is the status quo (no shift). Contrasts are expressed in
standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Social belonging & 0.038 & 0.031 & 0.045 & 1.226 & 1.197 \\
Social support & 0.036 & 0.028 & 0.043 & 1.219 & 1.189 \\
Neighbourhood community & 0.013 & 0.005 & 0.021 & 1.122 & 1.074 \\

\end{longtable}

For `Social belonging', the effect estimate on the causal\_difference
scale is 0.038 {[}0.031, 0.045{]}. The E-value for this estimate is
1.226, with a lower bound of 1.197. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.197 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Social support', the effect estimate on the causal\_difference
scale is 0.036 {[}0.028, 0.043{]}. The E-value for this estimate is
1.219, with a lower bound of 1.189. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.189 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Neighbourhood community', the effect estimate on the
causal\_difference scale is 0.013 {[}0.005, 0.021{]}. The E-value for
this estimate is 1.122, with a lower bound of 1.074. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.074 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality is weak}.

\paragraph{General Intervention}\label{general-intervention-4}

Figure~\ref{fig-5_1} \emph{B} and Table~\ref{tbl-5_2} describe results
for the general forgiveness interventions on social well-being.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.3288}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2192}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0822}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0959}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1096}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1644}}@{}}

\caption{\label{tbl-5_2}This table reports the results of model
estimates for the causal effects shifting everyone up by one point in
forgiveness (to the maximum of the range) on social well-being. The
contrast condition is the status quo (no shift). Contrasts are expressed
in standard deviation units.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Neighbourhood community & 0.055 & 0.045 & 0.066 & 1.284 & 1.251 \\
Social belonging & 0.049 & 0.040 & 0.059 & 1.264 & 1.230 \\
Social support & 0.042 & 0.032 & 0.052 & 1.240 & 1.205 \\

\end{longtable}

For `Neighbourhood community', the effect estimate on the
causal\_difference scale is 0.055 {[}0.045, 0.066{]}. The E-value for
this estimate is 1.284, with a lower bound of 1.251. At this lower
bound, unmeasured confounders would need a minimum association strength
with both the intervention sequence and outcome of 1.251 to negate the
observed effect. Weaker confounding would not overturn it. Here,
\textbf{there is evidence for causality}.

For `Social belonging', the effect estimate on the causal\_difference
scale is 0.049 {[}0.04, 0.059{]}. The E-value for this estimate is
1.264, with a lower bound of 1.23. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.23 to negate the observed effect.
Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}.

For `Social support', the effect estimate on the causal\_difference
scale is 0.042 {[}0.032, 0.052{]}. The E-value for this estimate is
1.24, with a lower bound of 1.205. At this lower bound, unmeasured
confounders would need a minimum association strength with both the
intervention sequence and outcome of 1.205 to negate the observed
effect. Weaker confounding would not overturn it. Here, \textbf{there is
evidence for causality}

\begin{figure}

\centering{

\includegraphics{24-rc-forgive-flourish_files/figure-pdf/fig-5_1-1.pdf}

}

\caption{\label{fig-5_1}This figure reports the results for both the (A)
therapeutic (B) general foregiveness interventions on social well-being.
The constrast condition is the status quo (no shift). Contrasts are
expressed in standard deviation units.}

\end{figure}%

\newpage{}

\subsection{Discussion}\label{discussion}

\subsubsection{Comments}\label{comments}

\begin{itemize}
\item
  Doubly robust semi-parametric machine learning, in our experience,
  tends to shrink effect estimates to zero. Although we cannot know the
  ground truth, the world operates in small effects.
\item
  Results transport to the New Zealand Population. With assumptions,
  they might transport to other populations, however we advise caution.
\end{itemize}

\subsubsection{Observations and
Recommendations}\label{observations-and-recommendations}

\begin{itemize}
\item
  Although forgiveness is other-focussed, the strongest signals we
  detect here are for benefits to the self.
\item
  It is not the work of psychological scientists and statisticians to
  offer advice. Rather, we hope to inform clinical and public
  decision-making with evidence.
\item
  Although summing over the population we find the strongest effects for
  the general intervention, an important unresolved question is for whom
  the effects we observe here operate most most strongly.
\item
  Another open question is how forgiveness might be enabled in people, a
  matter of future research.
\end{itemize}

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study. Members of the NZAVS management team and research
group hold full copies of the NZAVS data. A de-identified dataset
containing only the variables analysed in this manuscript is available
upon request from the corresponding author or any member of the NZAVS
advisory board for replication or checking of any published study using
NZAVS data. The code for the analysis can be found at:
\url{https://github.com/go-bayes/models/blob/main/scripts/24-rc-forgive/lmpt-ow-fl-forgiveness.R}.

\subsubsection{Acknowledgements}\label{acknowledgements}

\emph{Authors to fill out}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Planck Institute for the Science of Human History. The
funders had no role in preparing the manuscript or deciding to publish
it.

\subsubsection{Author Statement}\label{author-statement}

\emph{Authors to amend}

CS led NZAVS data collection. TV conceived of the outcome-wide approach
and three-wave panel design. RC conceived of this study with input from
PF, EW, and JB. JB developed the modelling approach and did the data
analysis. All authors contributed to the manuscript.

\newpage{}

\subsection{Appendix A: Sample Characteristics}\label{appendix-measures}

The following indicators were included in all models for confounding
control. Note that baseline measurements of the outcome variables and
the baseline exposure were also included in all models for confounding
control. Responses to these indicators are reported in Appendix C and
Appendix D.

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth?'').

\paragraph{Children Number (waves: 1-3,
4-15)}\label{children-number-waves-1-3-4-15}

We measured the number of children using one item from Bulbulia \emph{et
al.} (\citeproc{ref-Bulbulia_2015}{2015}). We asked participants, ``How
many children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, or adopted?'' or ``How many
children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, and/or parented?'' (waves:
12-15).

\paragraph{Disability}\label{disability}

We assessed disability with a one-item indicator adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}). It asks, ``Do you have a health
condition or disability that limits you and that has lasted for 6+
months?'' (1 = Yes, 0 = No).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

We asked participants, ``What is your highest level of qualification?''.
We coded participants' highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school quals coded as Level 3, and all other ancillary
categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Ethnicity}\label{ethnicity}

Based on the New Zealand Census, we asked participants, ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{enumerate}
\def\labelenumi{\roman{enumi}.}
\tightlist
\item
  I want people to know that I am an important person of high status,
  (Waves: 1, 10-14)
\item
  I am an ordinary person who is no better than others.
\item
  I wouldn't want people to treat me as though I were superior to them.
\item
  I think that I am entitled to more respect than the average person is.
\end{enumerate}

\paragraph{Hours of Childcare}\label{hours-of-childcare}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Work}\label{hours-of-work}

We measured work hours using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{} working in
paid employment.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked, ``Please estimate your total household income
(before tax) for the year XXXX''. To stabilise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Male Gender (waves: 1-15)}\label{male-gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants' personalities with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}), which consists of six dimensions and each
dimension is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I often forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{NZ Deprivation Index}\label{nz-deprivation-index}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{NZSEI Occupational Prestige and
Status}\label{nzsei-occupational-prestige-and-status}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017a}{Fahy
\emph{et al.} 2017a}). This index uses the income, age, and education of
a reference group, in this case the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant an NZSEI-13 score based on
their occupation.

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017b}). This index uses the income, age, and education of
a reference group, in this case, the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant an NZSEI-13 score based on
their occupation.

\paragraph{Partner (No/Yes)}\label{partner-noyes}

``What is your relationship status?'' (e.g., single, married, de-facto,
civil union, widowed, living together, etc.)

\paragraph{Politically Conservative}\label{politically-conservative}

We measured participants' political conservative orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{Religion: Religious
Identification}\label{religion-religious-identification}

If participants answered \emph{yes} to ``Do you identify with a religion
and/or spiritual group? we asked''How important is your religion to how
you see yourself?'' (1 = Not important, 7 = Very important). Those
participants who were not religious were imputed a score of ``0''.

\paragraph{Religion: Spiritual
Identification}\label{religion-spiritual-identification}

Spiritual identification was measured using one item (``I identify as a
spiritual person.'') from Postmes \emph{et al.}
(\citeproc{ref-postmes_single-item_2013}{2013}). Participants indicated
their agreement with this item (1 = Strongly Disagree to 7 = Strongly
Agree).

\paragraph{Religious Service
Attendance}\label{religious-service-attendance}

If participants answered \emph{yes} to ``Do you identify with a religion
and/or spiritual group?'' we measured their frequency of church
attendence using one item from Sibley and Bulbulia
(\citeproc{ref-sibley2012}{2012}): ``how many times did you attend a
church or place of worship in the last month?''. Those participants who
were not religious were imputed a score of ``0''. To avoid extreme
values, those who indicated a frequency above eight were assigned a
value of eight.

\paragraph{Rural/Urban Codes}\label{ruralurban-codes}

Participants residence locations were coded according to a five-level
ordinal categorisation ranging from ``Urban'' to Rural, see Sibley
(\citeproc{ref-sibley2021}{2021}).

\paragraph{Short-Form Health}\label{short-form-health}

Participants' subjective health was measured using one item (``Do you
have a health condition or disability that limits you, and that has
lasted for 6+ months?''; 1 = Yes, 0 = No) adapted from Verbrugge
(\citeproc{ref-verbrugge1997}{1997}).

\paragraph{Sample Origin}\label{sample-origin}

Wave enrolled in NZAVS, see Sibley (\citeproc{ref-sibley2021}{2021}).

\paragraph{Total Siblings}\label{total-siblings}

Participants were asked the following questions related to sibling
counts:

\begin{itemize}
\tightlist
\item
  Were you the 1st born, 2nd born, or 3rd born, etc, child of your
  mother?
\item
  Do you have siblings?
\item
  How many older sisters do you have?
\item
  How many younger sisters do you have?
\item
  How many older brothers do you have?
\item
  How many younger brothers do you have?
\end{itemize}

A single score was obtained from sibling counts by summing responses to
the ``How many\ldots{}'' items. From these scores, an ordered factor was
created ranging from 0 to 7, where participants with more than 7
siblings were grouped into the highest category.

\newpage{}

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{longtable}[]{@{}ll@{}}

\caption{\label{tbl-table-demography}Baseline demographic statistics}

\tabularnewline

\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 34,749} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 51 (14) \\
Range & 18, 96 \\
IQR & 41, 61 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.37 (0.98) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.00 \\
Unknown & 313 \\
\textbf{Born Nz} & 27,420 (79\%) \\
Unknown & 49 \\
\textbf{Children Num} & NA \\
Mean (SD) & 1.76 (1.44) \\
Range & 0.00, 14.00 \\
IQR & 0.00, 3.00 \\
Unknown & 13 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.14 (1.04) \\
Range & 1.00, 7.00 \\
IQR & 4.50, 6.00 \\
Unknown & 306 \\
\textbf{Education Level Coarsen} & NA \\
1 & 842 (2.4\%) \\
2 & 11,863 (34\%) \\
3 & 4,491 (13\%) \\
4 & 9,321 (27\%) \\
5 & 4,021 (12\%) \\
6 & 3,036 (8.8\%) \\
7 & 916 (2.7\%) \\
Unknown & 259 \\
\textbf{Eth Cat} & NA \\
1 & 28,631 (83\%) \\
2 & 3,612 (10\%) \\
3 & 746 (2.2\%) \\
4 & 1,509 (4.4\%) \\
Unknown & 251 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.88 (1.19) \\
Range & 1.00, 7.00 \\
IQR & 3.00, 4.75 \\
Unknown & 306 \\
\textbf{Hlth Disability} & 7,891 (23\%) \\
Unknown & 600 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.48 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.50 \\
Unknown & 310 \\
\textbf{Hours Children log} & NA \\
Mean (SD) & 1.10 (1.58) \\
Range & 0.00, 5.13 \\
IQR & 0.00, 2.20 \\
Unknown & 960 \\
\textbf{Hours Housework log} & NA \\
Mean (SD) & 2.15 (0.77) \\
Range & 0.00, 5.13 \\
IQR & 1.79, 2.71 \\
Unknown & 960 \\
\textbf{Hours Work log} & NA \\
Mean (SD) & 2.64 (1.59) \\
Range & 0.00, 4.62 \\
IQR & 1.10, 3.71 \\
Unknown & 960 \\
\textbf{Household Inc log} & NA \\
Mean (SD) & 11.41 (0.76) \\
Range & 0.69, 14.92 \\
IQR & 11.00, 11.92 \\
Unknown & 1,604 \\
\textbf{Male} & 12,588 (36\%) \\
\textbf{Modesty} & NA \\
Mean (SD) & 6.02 (0.92) \\
Range & 1.00, 7.00 \\
IQR & 5.50, 6.75 \\
Unknown & 17 \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.46 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 2.50, 4.25 \\
Unknown & 315 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.70 (2.70) \\
Range & 1.00, 10.00 \\
IQR & 2.00, 7.00 \\
Unknown & 238 \\
\textbf{Nzsei13} & NA \\
Mean (SD) & 55 (16) \\
Range & 10, 90 \\
IQR & 42, 69 \\
Unknown & 371 \\
\textbf{Openness} & NA \\
Mean (SD) & 4.98 (1.12) \\
Range & 1.00, 7.00 \\
IQR & 4.25, 5.75 \\
Unknown & 308 \\
\textbf{Partner} & 25,689 (76\%) \\
Unknown & 902 \\
\textbf{Political Conservative} & NA \\
1 & 1,822 (5.6\%) \\
2 & 6,689 (20\%) \\
3 & 6,637 (20\%) \\
4 & 9,657 (30\%) \\
5 & 4,935 (15\%) \\
6 & 2,432 (7.4\%) \\
7 & 491 (1.5\%) \\
Unknown & 2,086 \\
\textbf{Religion Church Round} & NA \\
0 & 28,250 (83\%) \\
1 & 1,109 (3.3\%) \\
2 & 795 (2.3\%) \\
3 & 677 (2.0\%) \\
4 & 1,759 (5.2\%) \\
5 & 340 (1.0\%) \\
6 & 234 (0.7\%) \\
7 & 76 (0.2\%) \\
8 & 689 (2.0\%) \\
Unknown & 820 \\
\textbf{Religion Identification Level} & NA \\
1 & 23,059 (67\%) \\
2 & 1,392 (4.1\%) \\
3 & 926 (2.7\%) \\
4 & 1,597 (4.7\%) \\
5 & 2,009 (5.9\%) \\
6 & 1,703 (5.0\%) \\
7 & 3,605 (11\%) \\
Unknown & 458 \\
\textbf{Religion Spiritual Identification} & NA \\
1 & 6,002 (18\%) \\
2 & 4,794 (15\%) \\
3 & 3,244 (9.8\%) \\
4 & 4,745 (14\%) \\
5 & 4,670 (14\%) \\
6 & 4,415 (13\%) \\
7 & 5,087 (15\%) \\
Unknown & 1,792 \\
\textbf{Sample Origin} & NA \\
1-2 & 2,251 (6.5\%) \\
3-3.5 & 1,694 (4.9\%) \\
4 & 2,023 (5.8\%) \\
5-6-7 & 3,246 (9.3\%) \\
8-9 & 4,372 (13\%) \\
10 & 21,163 (61\%) \\
\textbf{Total Siblings Factor} & NA \\
0 & 1,563 (4.6\%) \\
1 & 8,758 (26\%) \\
2 & 10,046 (30\%) \\
3 & 6,438 (19\%) \\
4 & 3,332 (9.8\%) \\
5 & 1,710 (5.0\%) \\
6 & 905 (2.7\%) \\
7 & 1,250 (3.7\%) \\
Unknown & 747 \\
\textbf{Urban} & 27,922 (81\%) \\
Unknown & 236 \\

\end{longtable}

Table~\ref{tbl-table-demography} reports baseline sample
characteristics.

\newpage{}

\subsection{Appendix C: Treatment Statistics}\label{appendix-exposures}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4247}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2877}}@{}}

\caption{\label{tbl-table-exposures-code}Exposures at baseline and
baseline + 1 (treatment) wave}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 34,749
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 34,749
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Forgiveness} & 5.33 (4.33, 6.00) & 5.33 (4.33, 6.00) \\
Unknown & 0 & 0 \\
\textbf{Alert Level Combined} & NA & NA \\
no\_alert & 34,749 (100\%) & 24,767 (71\%) \\
early\_covid & 0 (0\%) & 3,898 (11\%) \\
alert\_level\_1 & 0 (0\%) & 3,004 (8.6\%) \\
alert\_level\_2 & 0 (0\%) & 864 (2.5\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 568 (1.6\%) \\
alert\_level\_4 & 0 (0\%) & 1,648 (4.7\%) \\
Unknown & 0 & 0 \\

\end{longtable}

tbl-table-exposures-code presents baseline (NZAVS time 10) and exposure
wave (NZAVS time 11) statistics for the exposure variable: forgiveness
(range 1-7). All models adjusted for the pandemic alert level because
the treatment wave (NZAVS time 11) occurred during New Zealand's
COVID-19 pandemic. The pandemic is not a ``confounder'' because a
confounder must be related both to the treatment and the outcome. At the
end of the study, however, all participants had been exposed to the
global pandemic. However, to satisfy the causal consistency assumption,
all treatments must be conditionally equivalent within levels of all
covariates (\citeproc{ref-vanderweele2013}{VanderWeele and Hernan
2013}). Because COVID may have changed the quality and accessibility of
forgiveness, we included each participants lockdown condition as a
covariate (\citeproc{ref-sibley2021}{Sibley 2021}). To mitigate
systematic biases arising from attrition and missingness, we employed
inverse probability of censoring weights, which were computed
non-parametrically within our statistical models using the \texttt{lmtp}
package.

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4615}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2692}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2692}}@{}}

\caption{\label{tbl-table-outcomes}Outcomes at baseline and
end-of-study}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 34,749
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 34,749
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Alcohol Frequency} & NA & NA \\
0 & 4,234 (13\%) & 3,702 (13\%) \\
1 & 7,706 (23\%) & 6,004 (22\%) \\
2 & 6,349 (19\%) & 5,134 (19\%) \\
3 & 8,132 (24\%) & 6,691 (24\%) \\
4 & 7,176 (21\%) & 5,885 (21\%) \\
5 & 90 (0.3\%) & 79 (0.3\%) \\
Unknown & 1,062 & 7,254 \\
\textbf{Alcohol Intensity} & 2.00 (1.00, 3.00) & 2.00 (1.00, 2.00) \\
Unknown & 1,898 & 7,838 \\
\textbf{Belong} & 5.33 (4.33, 6.00) & 5.00 (4.33, 6.00) \\
Unknown & 309 & 6,932 \\
\textbf{Bodysat} & NA & NA \\
1 & 2,357 (6.9\%) & 1,934 (7.0\%) \\
2 & 3,652 (11\%) & 3,086 (11\%) \\
3 & 5,822 (17\%) & 4,834 (17\%) \\
4 & 5,796 (17\%) & 4,840 (17\%) \\
5 & 6,685 (19\%) & 5,452 (20\%) \\
6 & 7,590 (22\%) & 5,977 (22\%) \\
7 & 2,440 (7.1\%) & 1,625 (5.9\%) \\
Unknown & 407 & 7,001 \\
\textbf{Emotion Regulation Out Control} & NA & NA \\
1 & 9,341 (27\%) & 7,570 (27\%) \\
2 & 9,908 (29\%) & 7,412 (27\%) \\
3 & 5,008 (15\%) & 3,638 (13\%) \\
4 & 4,191 (12\%) & 3,607 (13\%) \\
5 & 3,675 (11\%) & 3,434 (12\%) \\
6 & 1,674 (4.9\%) & 1,544 (5.6\%) \\
7 & 643 (1.9\%) & 572 (2.1\%) \\
Unknown & 309 & 6,972 \\
\textbf{Gratitude} & 6.00 (5.33, 6.67) & 6.00 (5.33, 6.67) \\
Unknown & 5 & 6,777 \\
\textbf{Hlth Bmi} & 26.2 (23.3, 30.1) & 26.4 (23.5, 30.4) \\
Unknown & 390 & 6,998 \\
\textbf{Hlth Fatigue} & NA & NA \\
0 & 5,543 (16\%) & 3,948 (14\%) \\
1 & 11,408 (33\%) & 9,481 (34\%) \\
2 & 10,647 (31\%) & 8,678 (31\%) \\
3 & 5,100 (15\%) & 4,338 (16\%) \\
4 & 1,671 (4.9\%) & 1,272 (4.6\%) \\
Unknown & 380 & 7,032 \\
\textbf{Hlth Sleep Hours} & 7.00 (6.00, 8.00) & 7.00 (6.00, 8.00) \\
Unknown & 1,638 & 7,700 \\
\textbf{Hours Exercise log} & 1.61 (1.10, 2.08) & 1.79 (1.10, 2.20) \\
Unknown & 960 & 7,436 \\
\textbf{Kessler Latent Anxiety} & 1.00 (0.67, 1.67) & 1.00 (0.67,
1.67) \\
Unknown & 340 & 6,934 \\
\textbf{Kessler Latent Depression} & 0.33 (0.00, 1.00) & 0.33 (0.00,
1.00) \\
Unknown & 343 & 6,931 \\
\textbf{Lifesat} & 5.50 (5.00, 6.00) & 5.50 (4.50, 6.00) \\
Unknown & 184 & 7,214 \\
\textbf{Meaning Purpose} & NA & NA \\
1 & 603 (1.8\%) & 548 (2.0\%) \\
2 & 1,238 (3.6\%) & 1,126 (4.1\%) \\
3 & 2,236 (6.6\%) & 1,969 (7.2\%) \\
4 & 4,621 (14\%) & 3,922 (14\%) \\
5 & 8,521 (25\%) & 6,914 (25\%) \\
6 & 10,770 (32\%) & 8,272 (30\%) \\
7 & 5,946 (18\%) & 4,701 (17\%) \\
Unknown & 814 & 7,297 \\
\textbf{Meaning Sense} & NA & NA \\
1 & 246 (0.7\%) & 189 (0.7\%) \\
2 & 542 (1.6\%) & 408 (1.5\%) \\
3 & 1,140 (3.3\%) & 908 (3.3\%) \\
4 & 2,668 (7.7\%) & 2,135 (7.6\%) \\
5 & 6,815 (20\%) & 5,900 (21\%) \\
6 & 13,327 (38\%) & 10,765 (39\%) \\
7 & 9,897 (29\%) & 7,610 (27\%) \\
Unknown & 114 & 6,834 \\
\textbf{Neighbourhood Community} & NA & NA \\
1 & 2,073 (6.0\%) & 1,176 (4.2\%) \\
2 & 4,207 (12\%) & 2,814 (10\%) \\
3 & 5,045 (15\%) & 3,693 (13\%) \\
4 & 7,154 (21\%) & 6,040 (22\%) \\
5 & 7,371 (21\%) & 6,709 (24\%) \\
6 & 6,027 (17\%) & 5,249 (19\%) \\
7 & 2,701 (7.8\%) & 2,201 (7.9\%) \\
Unknown & 171 & 6,867 \\
\textbf{Perfectionism} & 3.00 (2.00, 4.00) & 3.00 (2.00, 4.00) \\
Unknown & 3 & 6,770 \\
\textbf{Permeability Individual} & NA & NA \\
1 & 311 (0.9\%) & 319 (1.2\%) \\
2 & 723 (2.1\%) & 668 (2.4\%) \\
3 & 1,479 (4.4\%) & 1,389 (5.1\%) \\
4 & 5,351 (16\%) & 5,360 (20\%) \\
5 & 10,623 (31\%) & 8,494 (31\%) \\
6 & 10,533 (31\%) & 7,513 (27\%) \\
7 & 4,829 (14\%) & 3,672 (13\%) \\
Unknown & 900 & 7,334 \\
\textbf{Power No Control Composite} & 3.00 (2.00, 4.00) & 2.50 (1.50,
4.00) \\
Unknown & 177 & 6,829 \\
\textbf{Pwb Standard Living} & 8.00 (7.00, 9.00) & 8.00 (7.00, 9.00) \\
Unknown & 125 & 6,913 \\
\textbf{Pwb your Future Security} & 7.00 (5.00, 8.00) & 7.00 (5.00,
8.00) \\
Unknown & 108 & 6,852 \\
\textbf{Pwb your Health} & 7.00 (5.00, 8.00) & 7.00 (5.00, 8.00) \\
Unknown & 128 & 6,892 \\
\textbf{Pwb your Relationships} & 8.00 (7.00, 9.00) & 8.00 (7.00,
9.00) \\
Unknown & 127 & 6,886 \\
\textbf{Rumination} & NA & NA \\
0 & 17,151 (50\%) & 14,024 (51\%) \\
1 & 9,468 (28\%) & 7,812 (28\%) \\
2 & 5,355 (16\%) & 4,230 (15\%) \\
3 & 1,845 (5.4\%) & 1,376 (5.0\%) \\
4 & 521 (1.5\%) & 308 (1.1\%) \\
Unknown & 409 & 6,999 \\
\textbf{Self Control Have Lots} & NA & NA \\
1 & 431 (1.3\%) & 571 (2.0\%) \\
2 & 1,224 (3.6\%) & 1,346 (4.8\%) \\
3 & 2,903 (8.6\%) & 2,715 (9.7\%) \\
4 & 4,368 (13\%) & 4,094 (15\%) \\
5 & 8,522 (25\%) & 6,678 (24\%) \\
6 & 11,954 (35\%) & 8,841 (32\%) \\
7 & 4,498 (13\%) & 3,645 (13\%) \\
Unknown & 849 & 6,859 \\
\textbf{Self Control Wish more Reversed} & NA & NA \\
1 & 3,910 (11\%) & 2,932 (11\%) \\
2 & 5,726 (17\%) & 4,454 (16\%) \\
3 & 8,111 (23\%) & 6,741 (24\%) \\
4 & 5,288 (15\%) & 4,517 (16\%) \\
5 & 3,478 (10\%) & 2,678 (9.6\%) \\
6 & 4,966 (14\%) & 4,058 (15\%) \\
7 & 3,140 (9.1\%) & 2,515 (9.0\%) \\
Unknown & 130 & 6,854 \\
\textbf{Self Esteem} & 5.33 (4.33, 6.00) & 5.33 (4.33, 6.00) \\
Unknown & 313 & 6,936 \\
\textbf{Sexual Satisfaction} & NA & NA \\
1 & 2,454 (7.7\%) & 2,267 (8.6\%) \\
2 & 2,630 (8.2\%) & 2,338 (8.8\%) \\
3 & 3,002 (9.4\%) & 2,716 (10\%) \\
4 & 6,476 (20\%) & 6,026 (23\%) \\
5 & 6,006 (19\%) & 4,949 (19\%) \\
6 & 6,776 (21\%) & 5,017 (19\%) \\
7 & 4,537 (14\%) & 3,142 (12\%) \\
Unknown & 2,868 & 8,294 \\
\textbf{Sfhealth} & 5.00 (4.33, 6.00) & 5.00 (4.33, 6.00) \\
Unknown & 6 & 6,765 \\
\textbf{Sfhealth your Health} & NA & NA \\
1 & 225 (0.7\%) & 211 (0.8\%) \\
2 & 771 (2.3\%) & 649 (2.4\%) \\
3 & 2,096 (6.3\%) & 1,731 (6.3\%) \\
4 & 3,748 (11\%) & 3,172 (12\%) \\
5 & 8,274 (25\%) & 7,410 (27\%) \\
6 & 12,994 (39\%) & 10,464 (38\%) \\
7 & 5,286 (16\%) & 3,675 (13\%) \\
Unknown & 1,355 & 7,437 \\
\textbf{Smoker} & 2,133 (6.3\%) & 1,290 (4.7\%) \\
Unknown & 793 & 7,157 \\
\textbf{Support} & 6.33 (5.33, 7.00) & 6.33 (5.33, 7.00) \\
Unknown & 23 & 6,788 \\

\end{longtable}

Table~\ref{tbl-table-outcomes} presents baseline and end-of-study
descriptive statistics for the outcome variables.

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-berry_forgivingness_2005}
Berry, JW, Worthington Jr., EL, O'Connor, LE, Parrott III, L, and Wade,
NG (2005) Forgivingness, vengeful rumination, and affective traits.
\emph{Journal of Personality}, \textbf{73}(1), 183--226.
doi:\href{https://doi.org/10.1111/j.1467-6494.2004.00308.x}{10.1111/j.1467-6494.2004.00308.x}.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, J (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, JA, Shaver, JH, Greaves, L, Sosis, R, and Sibley, CG (2015)
Religion and parental cooperation: An empirical test of slone's sexual
signaling model. In S. J. D. amd Van Slyke J., ed., \emph{The attraction
of religion: A sexual selectionist account}, Bloomsbury Press, 29--62.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: Interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.

\bibitem[\citeproctext]{ref-caprara_indicators_1986}
Caprara, GV (1986) Indicators of aggression: The dissipation-rumination
scale. \emph{Personality and Individual Differences}, \textbf{7}(6),
763--769.
doi:\href{https://doi.org/10.1016/0191-8869(86)90074-7}{10.1016/0191-8869(86)90074-7}.

\bibitem[\citeproctext]{ref-chatton2020}
Chatton, A, Le Borgne, F, Leyrat, C, \ldots{} Foucher, Y (2020)
G-computation, propensity score-based methods, and targeted maximum
likelihood estimator for causal inference with different covariates
sets: a comparative simulation study. \emph{Scientific Reports},
\textbf{10}(1), 9219.
doi:\href{https://doi.org/10.1038/s41598-020-65917-x}{10.1038/s41598-020-65917-x}.

\bibitem[\citeproctext]{ref-xgboost2023}
Chen, T, He, T, Benesty, M, \ldots{} Yuan, J (2023) \emph{Xgboost:
Extreme gradient boosting}. Retrieved from
\url{https://CRAN.R-project.org/package=xgboost}

\bibitem[\citeproctext]{ref-cummins_developing_2003}
Cummins, RA, Eckersley, R, Pallant, J, Vugt, J van, and Misajon, R
(2003) Developing a national index of subjective wellbeing: The
australian unity wellbeing index. \emph{Social Indicators Research},
\textbf{64}(2), 159--190.
doi:\href{https://doi.org/10.1023/A:1024704320683}{10.1023/A:1024704320683}.

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diaz2023lmtp}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2023) Nonparametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association},
\textbf{118}(542), 846--857.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diener1985a}
Diener, E, Emmons, RA, Larsen, RJ, and Griffin, S (1985) The
Satisfaction With Life Scale. \emph{Journal of Personality Assessment},
\textbf{49}(1), 71--75.

\bibitem[\citeproctext]{ref-diaz2021nonparametric}
Dı́az, I, Hejazi, NS, Rudolph, KE, and Der Laan, MJ van (2021)
Nonparametric efficient causal mediation with intermediate confounders.
\emph{Biometrika}, \textbf{108}(3), 627--641.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017b) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fahy2017a}
Fahy, KM, Lee, A, and Milne, BJ (2017a) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a {N}ew {Z}ealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-gratz_multidimensional_2004}
Gratz, KL, and Roemer, L (2004) Multidimensional assessment of emotion
regulation and dysregulation: Development, factor structure, and initial
validation of the difficulties in emotion regulation scale.
\emph{Journal of Psychopathology and Behavioral Assessment},
\textbf{26}(1), 41--54.
doi:\href{https://doi.org/10.1023/B:JOBA.0000007455.08539.94}{10.1023/B:JOBA.0000007455.08539.94}.

\bibitem[\citeproctext]{ref-gross_individual_2003}
Gross, JJ, and John, OP (2003) Individual differences in two emotion
regulation processes: Implications for affect, relationships, and
well-being. \emph{Journal of Personality and Social Psychology},
\textbf{85}(2), 348--362.
doi:\href{https://doi.org/10.1037/0022-3514.85.2.348}{10.1037/0022-3514.85.2.348}.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-haneuse2013estimation}
Haneuse, S, and Rotnitzky, A (2013) Estimation of the effect of
interventions that modify the received treatment. \emph{Statistics in
Medicine}, \textbf{32}(30), 5260--5277.

\bibitem[\citeproctext]{ref-Ministry_of_Health_2013}
Health, M of (2013) \emph{The new zealand health survey: Content guide
2012-2013}, Princeton University Press.

\bibitem[\citeproctext]{ref-hernan2024WHATIF}
Hernan, MA, and Robins, JM (2024) \emph{Causal inference: What if?},
Taylor \& Francis. Retrieved from
\url{https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/}

\bibitem[\citeproctext]{ref-hernan2024stating}
Hernán, MA, and Greenland, S (2024) Why stating hypotheses in grant
applications is unnecessary. \emph{JAMA}, \textbf{331}(4), 285--286.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-instrument1992mos}
Instrument Ware Jr, J, and Sherbourne, C (1992) The MOS 36-item
short-form health survey (SF-36): I. Conceptual framework and item
selection. \emph{Medical Care}, \textbf{30}(6), 473--483.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-kessler2002}
Kessler, R~C, Andrews, G, Colpe, L~J, \ldots{} Zaslavsky, A~M (2002)
Short screening scales to monitor population prevalences and trends in
non-specific psychological distress. \emph{Psychological Medicine},
\textbf{32}(6), 959--976.
doi:\href{https://doi.org/10.1017/S0033291702006074}{10.1017/S0033291702006074}.

\bibitem[\citeproctext]{ref-kessler2010}
Kessler, RC, Green, JG, Gruber, MJ, \ldots{} Zaslavsky, AM (2010)
Screening for serious mental illness in the general population with the
K6 screening scale: results from the WHO World Mental Health (WMH)
survey initiative. \emph{International Journal of Methods in Psychiatric
Research}, \textbf{19}(S1), 4--22.
doi:\href{https://doi.org/10.1002/mpr.310}{10.1002/mpr.310}.

\bibitem[\citeproctext]{ref-van2014discussion}
Laan, MJ van der, Luedtke, AR, and Dı́az, I (2014) Discussion of
identification, estimation and approximation of risk under interventions
that depend on the natural value of treatment using observational data,
by {J}essica {Y}oung, {M}iguel {H}ern{á}n, and {J}ames {R}obins.
\emph{Epidemiologic Methods}, \textbf{3}(1), 21--31.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-mccullough_grateful_2002}
McCullough, ME, Emmons, RA, and Tsang, J-A (2002) The grateful
disposition: A conceptual and empirical topography. \emph{Journal of
Personality and Social Psychology}, \textbf{82}(1), 112--127.
doi:\href{https://doi.org/10.1037/0022-3514.82.1.112}{10.1037/0022-3514.82.1.112}.

\bibitem[\citeproctext]{ref-muriwai_looking_2018}
Muriwai, E, Houkamau, CA, and Sibley, CG (2018) Looking like a smoker, a
smokescreen to racism? Māori perceived appearance linked to smoking
status. \emph{Ethnicity \& Health}, \textbf{23}(4), 353--366.
doi:\href{https://doi.org/10.1080/13557858.2016.1263288}{10.1080/13557858.2016.1263288}.

\bibitem[\citeproctext]{ref-nolen-hoeksema_effects_1993}
Nolen-hoeksema, S, and Morrow, J (1993) Effects of rumination and
distraction on naturally occurring depressed mood. \emph{Cognition and
Emotion}, \textbf{7}(6), 561--570.
doi:\href{https://doi.org/10.1080/02699939308409206}{10.1080/02699939308409206}.

\bibitem[\citeproctext]{ref-overall2016power}
Overall, NC, Hammond, MD, McNulty, JK, and Finkel, EJ (2016) When power
shapes interpersonal behavior: Low relationship power predicts men's
aggressive responses to low situational power. \emph{Journal of
Personality and Social Psychology}, \textbf{111}(2), 195.

\bibitem[\citeproctext]{ref-polley2023}
Polley, E, LeDell, E, Kennedy, C, and Laan, M van der (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://CRAN.R-project.org/package=SuperLearner}

\bibitem[\citeproctext]{ref-postmes_single-item_2013}
Postmes, T, Haslam, SA, and Jans, L (2013) A single-item measure of
social identification: Reliability, validity, and utility. \emph{The
British Journal of Social Psychology}, \textbf{52}(4), 597--617.
doi:\href{https://doi.org/10.1111/bjso.12006}{10.1111/bjso.12006}.

\bibitem[\citeproctext]{ref-prochaska2012}
Prochaska, JJ, Sung, H-Y, Max, W, Shi, Y, and Ong, M (2012) Validity
study of the K6 scale as a measure of moderate mental distress based on
mental health treatment need and utilization: The K6 as a measure of
moderate mental distress. \emph{International Journal of Methods in
Psychiatric Research}, \textbf{21}(2), 88--97.
doi:\href{https://doi.org/10.1002/mpr.1349}{10.1002/mpr.1349}.

\bibitem[\citeproctext]{ref-rice_short_2014}
Rice, KG, Richardson, CME, and Tueller, S (2014) The short form of the
revised almost perfect scale. \emph{Journal of Personality Assessment},
\textbf{96}(3), 368--379.
doi:\href{https://doi.org/10.1080/00223891.2013.838172}{10.1080/00223891.2013.838172}.

\bibitem[\citeproctext]{ref-robins1986}
Robins, J (1986) A new approach to causal inference in mortality studies
with a sustained exposure period---application to control of the healthy
worker survivor effect. \emph{Mathematical Modelling}, \textbf{7}(9-12),
1393--1512.

\bibitem[\citeproctext]{ref-Rosenberg1965}
Rosenberg, M (1965) \emph{Society and the adolescent self-image},
Princeton, NJ: Princeton University Press.

\bibitem[\citeproctext]{ref-sengupta2013}
Sengupta, NK, Luyten, N, Greaves, LM, \ldots{} Sibley, CG (2013) Sense
of Community in New Zealand Neighbourhoods: A Multi-Level Model
Predicting Social Capital. \emph{New Zealand Journal of Psychology},
\textbf{42}(1), 36--45.

\bibitem[\citeproctext]{ref-shiba2021using}
Shiba, K, and Kawahara, T (2021) Using propensity scores for causal
inference: Pitfalls and tips. \emph{Journal of Epidemiology},
\textbf{31}(8), 457--463.

\bibitem[\citeproctext]{ref-sibley2012}
Sibley, C. G., and Bulbulia, JA (2012) Healing those who need healing:
How religious practice affects social belonging. \emph{Journal for the
Cognitive Science of Religion}, \textbf{1}, 29--45.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the new zealand attitudes and values study}}.

\bibitem[\citeproctext]{ref-sibley2020}
Sibley, CG, Afzali, MU, Satherley, N, \ldots{} others (2020) Prejudice
toward muslims in new zealand: Insights from the new zealand attitudes
and values study. \emph{New Zealand Journal of Psychology},
\textbf{49}(1).

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in New Zealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-steger_meaning_2006}
Steger, MF, Frazier, P, Oishi, S, and Kaler, M (2006) The meaning in
life questionnaire: Assessing the presence of and search for meaning in
life. \emph{Journal of Counseling Psychology}, \textbf{53}(1), 80--93.
doi:\href{https://doi.org/10.1037/0022-0167.53.1.80}{10.1037/0022-0167.53.1.80}.

\bibitem[\citeproctext]{ref-stronge2015facebook}
Stronge, S, Greaves, LM, Milojev, P, West-Newman, T, Barlow, FK, and
Sibley, CG (2015) Facebook is linked to body dissatisfaction: Comparing
users and non-users. \emph{Sex Roles}, \textbf{73}, 200--213.

\bibitem[\citeproctext]{ref-tangney_high_2004}
Tangney, JP, Baumeister, RF, and Boone, AL (2004) High self-control
predicts good adjustment, less pathology, better grades, and
interpersonal success. \emph{Journal of Personality}, \textbf{72}(2),
271--324.
doi:\href{https://doi.org/10.1111/j.0022-3506.2004.00263.x}{10.1111/j.0022-3506.2004.00263.x}.

\bibitem[\citeproctext]{ref-tausch2015does}
Tausch, N, Saguy, T, and Bryson, J (2015) How does intergroup contact
affect social change? Its impact on collective action and individual
mobility intentions among members of a disadvantaged group.
\emph{Journal of Social Issues}, \textbf{71}(3), 536--553.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vanderlaan2011}
Van Der Laan, MJ, and Rose, S (2011) \emph{Targeted Learning: Causal
Inference for Observational and Experimental Data}, New York, NY:
Springer. Retrieved from
\url{https://link.springer.com/10.1007/978-1-4419-9782-1}

\bibitem[\citeproctext]{ref-vanderlaan2018}
Van Der Laan, MJ, and Rose, S (2018) \emph{Targeted Learning in Data
Science: Causal Inference for Complex Longitudinal Studies}, Cham:
Springer International Publishing. Retrieved from
\url{http://link.springer.com/10.1007/978-3-319-65304-4}

\bibitem[\citeproctext]{ref-vanderweele2009}
VanderWeele, TJ (2009) Concerning the consistency assumption in causal
inference. \emph{Epidemiology}, \textbf{20}(6), 880.
doi:\href{https://doi.org/10.1097/EDE.0b013e3181bd5638}{10.1097/EDE.0b013e3181bd5638}.

\bibitem[\citeproctext]{ref-vanderweele2019}
VanderWeele, TJ (2019) Principles of confounder selection.
\emph{European Journal of Epidemiology}, \textbf{34}(3), 211--219.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the e-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 1--20.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437--466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-westreich2010}
Westreich, D, and Cole, SR (2010) Invited commentary: positivity in
practice. \emph{American Journal of Epidemiology}, \textbf{171}(6).
doi:\href{https://doi.org/10.1093/aje/kwp436}{10.1093/aje/kwp436}.

\bibitem[\citeproctext]{ref-williams2000cyberostracism}
Williams, KD, Cheung, CK, and Choi, W (2000) Cyberostracism: Effects of
being ignored over the internet. \emph{Journal of Personality and Social
Psychology}, \textbf{79}(5), 748.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{{l}mtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\bibitem[\citeproctext]{ref-Ranger2017}
Wright, MN, and Ziegler, A (2017) {ranger}: A fast implementation of
random forests for high dimensional data in {C++} and {R}. \emph{Journal
of Statistical Software}, \textbf{77}(1), 1--17.
doi:\href{https://doi.org/10.18637/jss.v077.i01}{10.18637/jss.v077.i01}.

\bibitem[\citeproctext]{ref-zhang2023shouldMultipleImputation}
Zhang, J, Dashti, SG, Carlin, JB, Lee, KJ, and Moreno-Betancur, M (2023)
Should multiple imputation be stratified by exposure group when
estimating causal effects via outcome regression in observational
studies? \emph{BMC Medical Research Methodology}, \textbf{23}(1), 42.

\end{CSLReferences}



\end{document}
