% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  single column]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=25mm,heightrounded,headsep=22pt,headheight=11pt,footskip=33pt,ignorehead,ignorefoot]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Does Religious Disaffiliation Causally Affect a Sense of Meaning and Purpose?: Evidence from a National Panel Study in New Zealand},
  pdfauthor={Daryl Van Tongeren; Don E Davis; Chris G. Sibley; Joseph A. Bulbulia},
  pdfkeywords={Use, use},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Does Religious Disaffiliation Causally Affect a Sense of Meaning
and Purpose?: Evidence from a National Panel Study in New Zealand}

\usepackage{academicons}
\usepackage{xcolor}

  \author{Daryl Van Tongeren}
            \affil{%
             \small{     Hope College
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~ }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Don E Davis}
            \affil{%
             \small{     Georgia State University
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~ }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Chris G. Sibley}
            \affil{%
             \small{     School of Psychology, University of Auckland
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~ }
              }
      \usepackage{academicons}
\usepackage{xcolor}

  \author{Joseph A. Bulbulia}
            \affil{%
             \small{     Victoria University of Wellington, New Zealand
          ORCID \textcolor[HTML]{A6CE39}{\aiOrcid} ~ }
              }
      


\date{2024-11-19}
\begin{document}
\maketitle
\begin{abstract}
\textbf{Question}: Does religious disaffiliation affect a sense of
meaning in life and purpose in life?

\textbf{Method}: We analyse five waves of cohort panel data from the New
Zealand Attitudes and Values Study (N = 47,202) to estimate the causal
effects of religious disaffiliation on meaning and purpose in life.

\textbf{Eligibility}: Participants were included if they completed the
baseline wave (time 0) of the New Zealand Attitudes and Values Study
Wave 10 (years 2018-2019). They may have been loss to follow-up at any
wave before the end of study NZAVS wave 14 (years 2022-2023).

\textbf{Treatment Regimes}: We estimated population average well-being
at the end of study (time 4) under three scenarios:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Steady Religious}: Start religiously affiliated at time 1 and
  remaining affiliated through times 2 and 3.
\item
  \emph{Steady Secular}: Start religiously unaffiliated at time 1 and
  remaining unaffiliated through times 2 and 3.
\item
  \emph{Done}: Start religiously affiliated at time 1 but becoming
  unaffiliated at times 2 and 3.
\end{enumerate}

\textbf{Causal contrasts}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \emph{Done vs Steady Religious}: Would those who disaffiliate have
  experienced higher meaning and purpose if they remained religiously
  affiliated?
\item
  \emph{Done vs Steady Secular}: How do disaffiliates compare to those
  who were consistently secular?
\item
  \emph{Steady Religious vs Steady Secular}: How do those who remain
  religious compare to those who remain secular?
\end{enumerate}

\textbf{Statistical Estimation}: We used semi-parametric machine
learning, controlling for time-varying confounding, and using inverse
probability of censoring weights for attrition.

\textbf{Results}: Religious disaffiliation (\emph{Done}) resulted in
lower meaning and purpose compared to \emph{Steady Religious} but was
similar to \emph{Steady Secular}.

\textbf{Importance}: These findings suggest that religious
disaffiliation may lower meaning and purpose, but levels are not worse
than those observed among individuals already unaffiliated.

\textbf{KEYWORDS}: \emph{Causal Inference}; \emph{Cross-validation};
\emph{Done}; \emph{Machine Learning}; \emph{Religion};
\emph{Semi-parametric}; \emph{Targeted Learning}; \emph{Well-Being}
\end{abstract}


\subsection{Introduction}\label{introduction}

Religious disaffiliation, described by Max Weber as ``The Disenchantment
of the World'' (\citeproc{ref-wilson2014differences}{Wilson \emph{et
al.} 2014}), defines most industrial societies
(\citeproc{ref-weber1946science}{Weber 1946}). But does such
disenchantment manifest as a diminished sense of meaning and purpose
among those who disaffiliate?

Evaluating whether religious disaffiliation causes changes in meaning
and purpose requires more than tracking disaffiliates over time. Common
causes may drive both disaffiliation and shifts in meaning. Since
randomising individuals to affiliation or disaffiliation is ethically
infeasible, methods for causal inference in observational settings offer
an alternative (\citeproc{ref-hernan2024WHATIF}{Hernan and Robins 2024};
\citeproc{ref-vanderweele2015}{VanderWeele 2015}).

We use five waves of data from the New Zealand Attitudes and Values
Study (NZAVS time 10-14, years 2018-2023, N = 47,202), a longitudinal
national probability sample, to estimate the causal effects of religious
and secular affiliation. Our target population includes New Zealand
residents from 2018--2022. By applying methods from the health sciences,
we contrast population averages under three sequential treatment regimes
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021},
\citeproc{ref-diaz2023lmtp}{2023};
\citeproc{ref-haneuse2013estimation}{Haneuse and Rotnitzky 2013};
\citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023}):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Steady Religious}: Start religiously affiliated at time 1 and
  remaining affiliated through times 2 and 3.\\
\item
  \textbf{Steady Secular}: Start unaffiliated at time 1 and remaining
  unaffiliated through times 2 and 3.\\
\item
  \textbf{Done}: Start affiliated at time 1 but becoming unaffiliated at
  times 2 and 3.
\end{enumerate}

From these regimes, we consider three theoretically interesting causal
contrasts:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Done vs Steady Religious}: Would those who disaffiliate have
  experienced higher meaning and purpose if they remained religiously
  affiliated?\\
\item
  \textbf{Done vs Steady Secular}: How do disaffiliates compare to those
  who were consistently secular?\\
\item
  \textbf{Steady Religious vs Steady Secular}: How do those who remain
  religious compare to those who remain secular?
\end{enumerate}

Our primary interest is in the first contrast: whether disaffiliates
(\emph{Dones}) experience lower meaning and purpose compared to if they
had stayed religiously affiliated. The second contrast frames these
results: do disaffiliates resemble the steadily secular? The third
contrast compares steady religious and steady secular groups to assess
the overall influence of stable religious affiliation.

These questions simulate hypothetical experiments with random assignment
to religious affiliation conditions (\citeproc{ref-hernuxe1n2016}{Hernán
\emph{et al.} 2016}). They aim to quantify how interventions on
religious affiliation might impact population averages in meaning and
purpose.

Although numerous contrasts could be considered---such as effects of
converting to or returning to religion, or short-term effects of
affiliation---this study focuses on stable interventions. We simplify
the analysis by examining religious affiliation, a widely reported
indicator, and its causal effects on meaning and purpose.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of the New Zealand Attitudes and Values
Study (NZAVS), an annual longitudinal national probability panel
assessing New Zealand residents' social attitudes, personality,
ideology, and health outcomes. The panel began in 2009 and has since
expanded to include over fifty researchers, with responses from 72,910
participants to date. The study operates independently of political or
corporate funding and is based at a university. Data summaries for all
measures used in this study are provided in \textbf{Supplemental
Appendices A}. For more information about the NZAVS, see:
\href{https://doi.org/10.17605/OSF.IO/75SNB}{OSF.IO/75SNB}. The data for
this study were obtained from the NZAVS waves 10-14 cohort, covering
2018-2023. We selected these waves because the afford the great possible
sample size.

\subsubsection{Treatment Indicator}\label{treatment-indicator}

We assessed religious service attendance using the following question:

\paragraph{Religious Affiliation
(Binary)}\label{religious-affiliation-binary}

\emph{Do you identify with a religion and/or spiritual group?}

Binary response: (0 = No, 1 = Yes) (Statistics NZ Census Question).

\subsubsection{Outcomes}\label{outcomes}

\paragraph{Meaning Purpose}\label{meaning-purpose}

\emph{My life has a clear sense of purpose}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree)
(\citeproc{ref-steger_meaning_2006}{Steger \emph{et al.} 2006}).

\paragraph{Meaning Sense}\label{meaning-sense}

\emph{I have a good sense of what makes my life meaningful.}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree)
(\citeproc{ref-steger_meaning_2006}{Steger \emph{et al.} 2006}).

\subsubsection{Identification
Assumptions}\label{identification-assumptions}

To consistently estimate a causal effect, investigators must satisfy
three assumptions (refer to Bulbulia
(\citeproc{ref-bulbulia2023}{2024c})):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Causal Consistency: potential outcomes correspond to the observed
  outcomes under the treatments in our data. We assume that conditional
  on measured covariates, potential outcomes do not depend on how the
  treatment was administered (\citeproc{ref-vanderweele2009}{VanderWeele
  2009}; \citeproc{ref-vanderweele2013}{VanderWeele and Hernan 2013}).
\item
  Conditional Exchangeability: conditional on observed covariates,
  treatment assignment is independent of the potential outcomes being
  compared (i.e.~there is no unmeasured confounding)
  (\citeproc{ref-chatton2020}{Chatton \emph{et al.} 2020};
  \citeproc{ref-hernan2024WHATIF}{Hernan and Robins 2024}).
\item
  Positivity: every individual has a non-zero probability of receiving
  each treatment level, regardless of their covariate values. We
  evaluated this by examining changes in religious service attendance
  from baseline to the treatment wave
  (\citeproc{ref-westreich2010}{Westreich and Cole 2010}).
\end{enumerate}

\subsubsection{Target Population}\label{target-population}

Our target population comprises New Zealand residents represented in the
baseline wave of the NZAVS during 2018--2019, weighted by 2018 New
Zealand Census data for age, gender, and ethnicity
(\citeproc{ref-sibley2021}{Sibley 2021}). Although the NZAVS is a
national probability study designed to reflect the broader New Zealand
population, it tends to under-sample males and individuals of Asian
descent and over-sample females and Māori (the indigenous people of New
Zealand). To address these disparities and enhance the accuracy of our
findings, we applied survey weights adjusting for age, gender, and
ethnicity. Survey weights were integrated into our statistical models
using the weights option in \texttt{lmtp}
(\citeproc{ref-williams2021}{Williams and Díaz 2021}), following
protocols described in Bulbulia
(\citeproc{ref-bulbulia2024PRACTICAL}{2024a}).

\subsubsection{Eligibility Criteria}\label{eligibility-criteria}

Participants were included in the analysis if they were enrolled in the
2018 wave of the NZAVS (Time 10). Participants with missing covariate
data at baseline were included, with missing data imputed using
information available at baseline. Participants may have been lost to
follow-up at any point after baseline. To obtain valid inference for the
population of New Zealand we included survey weights in our statistical
models. Information about these survey weights can be found in the NZAVS
documentation, see:
\href{https://doi.org/10.17605/OSF.IO/75SNB}{OSF.IO/75SNB}.

A total of 47,202 individuals met these criteria and were included in
the study.

\subsubsection{Missing Data}\label{missing-data}

We adopted the following strategies for handling missing data:

\textbf{Baseline Missingness:}: We employed the \texttt{ppm} algorithm
from the \texttt{mice} package in R (\citeproc{ref-vanbuuren2018}{Van
Buuren 2018}) to impute missing baseline data in NZAVS time 10, years
2018-2019. Missing data in this wave to 1.41 percent of the total
observations. We used only baseline data for imputation, following
(\citeproc{ref-zhang2023shouldMultipleImputation}{Zhang \emph{et al.}
2023}). Because we could only pass one data set to the \texttt{lmtp,} we
employed single imputation. Because we use semi-parametric estimation,
we were able to include indicators for each column with missing values,
to further reduce bias. This method allowed us to reconstruct an
incomplete dataset by estimating a plausible value for missing
observation at baseline.

\textbf{Exposure wave missingness}: even if the population in the
baseline wave corresponds to the target population, attrition between
NZAVS time 10, years 2018-2019 and NZAVS time 11-13, years 2019-2022 may
threaten generalisations to the target population. To address potential
bias from loss-to-follow up in the exposure wave we employed
non-parametric inverse-probability of censoring weights. We also
included indicators for time-varying confounders. Were any not observed,
but the exposure variable observed, we imputed the observation using the
previous observed value and included an missing indicator column, so
that our non-parametric machine learning algothrims could learn the
values.

\textbf{Outcome Missingness:} to account for confounding and selection
bias from missing responses and panel attrition in NZAVS time 14, years
2022-2023, we applied censoring weights obtained using nonparametric
machine learning ensembles via the \texttt{lmtp} package in R
(\citeproc{ref-williams2021}{Williams and Díaz 2021}).

\subsubsection{Confounding Control}\label{confounding-control}

To address confounding in our analysis, we implement
(\citeproc{ref-vanderweele2019}{VanderWeele 2019})'s \emph{modified
disjunctive cause criterion} by following these steps:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Exclude instrumental variables} that affect the exposure but
  not the outcome. Instrumental variables do not contribute to
  controlling confounding and can reduce the efficiency of the
  estimates.
\item
  \textbf{Include proxies for unmeasured confounders} affecting both
  exposure and outcome. According to the principles of d-separation
  Pearl (\citeproc{ref-pearl2009a}{2009}), using proxies allows us to
  control for their associated unmeasured confounders indirectly.
\item
  \textbf{Control for baseline Religious Affiliation} and all outcome
  variables (refer to VanderWeele \emph{et al.}
  (\citeproc{ref-vanderweele2020}{2020}).)
\end{enumerate}

Additionally, because the measures are repeated, there is a prospect for
time-varying confounders, which may arise after baseline control, and
associate sequential treatment variables with the outcomes at the end of
study. For each sequential treatment indicator we included measures of
parenting status, romantic partnership, employment, and health
disability, on the assumption such events might affect both religious
affiliation and indicators of meaning of purpose, or be proxies for such
common causes (\citeproc{ref-bulbulia2024swigstime}{Bulbulia 2024d};
\citeproc{ref-hernan2024WHATIF}{Hernan and Robins 2024};
\citeproc{ref-robins1986}{Robins 1986})

\hyperref[appendix-demographics]{Appendix B} presents the covariates we
included for confounding control. These methods adhere to the guidelines
provided in (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024a}).

\subsubsection{Statistical Estimator}\label{statistical-estimator}

\paragraph{Longitudinal Modified Treatment Policy (LMTP)
Estimator}\label{longitudinal-modified-treatment-policy-lmtp-estimator}

We perform statistical estimation using a Sequential Doubly-Robust
Estimator from the \texttt{lmtp} package, which is multiply robust for
repeated treatments across multiple waves
(\citeproc{ref-diaz2023lmtp}{Díaz \emph{et al.} 2023};
\citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023}). This estimator
is robust to misspecification in either the outcome or treatment model
over time. The lmtp package relies on the SuperLearner library,
integrating diverse machine learning algorithms
(\citeproc{ref-SuperLearner2023}{Polley \emph{et al.} 2023}). Given the
high-dimensionality of the data, we used the Ranger estimator, a
non-parametric causal forest method known for its resistance to
overfitting (\citeproc{ref-Ranger2017}{Wright and Ziegler 2017}). We
also employed the \texttt{SL.glment}
(\citeproc{ref-glmnet_use_2010}{Friedman \emph{et al.} 2010}). All
statistical models implemented a 10-fold cross-validation. SDR robust
method for estimating causal effects while providing valid statistical
uncertainty measures (\citeproc{ref-van2012targeted}{Laan and Gruber
2012}; \citeproc{ref-van2014targeted}{Van der Laan 2014}). For further
information on targeted learning using the \texttt{lmtp} package, see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023}). Graphs, tables, and output reports
are created using the \texttt{margot} package
(\citeproc{ref-margot2024}{Bulbulia 2024b}).

\subsubsection{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To assess the sensitivity of results to unmeasured confounding, we
report VanderWeele and Ding's E-value in all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). To
evaluate the strength of evidence, we use the bound of the E-value 95\%
confidence interval closest to 1. This provides an approximate metric
for understanding the robustness of our findings in the presence of
potential unmeasured confounding.

\subsubsection{Changes in Religious
Affiliation}\label{changes-in-religious-affiliation}

Table~\ref{tbl-transition} shows total transitions in religious service
attendance from baseline to the treatment waves. Assessing changes in
the treatment variable is essential for evaluating the positivity
assumption of causal inference, which, as stated above, requires that
every individual has a non-zero probability of receiving each treatment
level, regardless of their covariate values
(\citeproc{ref-danaei2012}{Danaei \emph{et al.} 2012};
\citeproc{ref-hernan2024WHATIF}{Hernan and Robins 2024};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}).

\begin{longtable}[]{@{}ccc@{}}

\caption{\label{tbl-transition}This transition matrix captures stability
and change in religious affiliation between states of religious
affiliation over time. Each cell in the matrix represents the count of
individuals remaining or transitioning between states, where ``0''
denotes secular affiliation and ``1'' denotes religious affiliation. The
rows correspond to these states at baseline (From), and the columns
correspond to the state at the treatment waves (To). \textbf{Diagonal
entries} (in \textbf{bold}) denote the number of instances where
individuals remained in their initial state. \textbf{Off-diagonal
entries} describe the transitions of individuals one state to another
from the baseline states through the following treatment waves.}

\tabularnewline

\toprule\noalign{}
From & State 0 & State 1 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 0 & \textbf{53650} & 3144 \\
State 1 & 4441 & \textbf{25860} \\

\end{longtable}

\newpage{}

\subsection{Results}\label{results}

\subsubsection{Conrast 1: Contrast Done Intervention with Steady
Religiously Affiliated
(control)}\label{conrast-1-contrast-done-intervention-with-steady-religiously-affiliated-control}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-daryl-done-meaning_files/figure-pdf/fig-done_vs_religious-1.pdf}}

}

\caption{\label{fig-done_vs_religious}Contrast of religious
disaffiliation (done) with steady religious affiliation on meaning and
purpose.}

\end{figure}%

\begin{table}

\caption{\label{tbl-done_vs_religious}Contrast of religious
disaffiliation (done) with steady religious affiliation on meaning and
purpose.}

\centering{

\begin{verbatim}
                E[Y(1)]-E[Y(0)]  2.5 % 97.5 % E_Value E_Val_bound
Meaning Purpose          -0.121 -0.137 -0.104   1.477       1.428
Meaning Sense            -0.096 -0.112 -0.079   1.407       1.362
\end{verbatim}

}

\end{table}%

Table~\ref{tbl-done_vs_religious} and Figure~\ref{fig-done_vs_religious}
present the comparison of the intervention: Contrast Done Intervention
with Steady Religiously Affiliated (control)

\paragraph{Meaning purpose}\label{meaning-purpose-1}

The effect estimate (rd) is -0.121 (-0.137, -0.104). On the original
scale, the estimated effect is -0.17 (-0.193, -0.147). E-value lower
bound is 1.428, indicating evidence for causality.

\paragraph{Meaning sense}\label{meaning-sense-1}

The effect estimate (rd) is -0.096 (-0.112, -0.079). On the original
scale, the estimated effect is -0.116 (-0.135, -0.096). E-value lower
bound is 1.362, indicating evidence for causality.

\subsubsection{Contrast 2: Contrast Done Intervention with Steady
Secular Affiliation
(control)}\label{contrast-2-contrast-done-intervention-with-steady-secular-affiliation-control}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-daryl-done-meaning_files/figure-pdf/fig-done-secular-1.pdf}}

}

\caption{\label{fig-done-secular}Contrast of religious affiliation
(done) with steady secular affiliation on meaning and purpose.}

\end{figure}%

\begin{table}

\caption{\label{tbl-done-secular}Contrast of religious disaffiliation
(done) with steady secular affiliation on meaning and purpose.}

\centering{

\begin{verbatim}
                E[Y(1)]-E[Y(0)]  2.5 % 97.5 % E_Value E_Val_bound
Meaning Purpose          -0.014 -0.037  0.009   1.127           1
Meaning Sense            -0.003 -0.027  0.021   1.055           1
\end{verbatim}

}

\end{table}%

Table~\ref{tbl-done-secular} and Figure~\ref{fig-done-secular} present
the comparison of the intervention: Contrast Done Intervention with
Steady Secular Affiliation (control)

No reliable causal evidence detected for the reported outcomes.

\subsubsection{Conrast 3: Contrast Steady Secular Affiliation with
Steady Religious
Affiliation}\label{conrast-3-contrast-steady-secular-affiliation-with-steady-religious-affiliation}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{24-daryl-done-meaning_files/figure-pdf/fig-secular_vs_religious-1.pdf}}

}

\caption{\label{fig-secular_vs_religious}Contrast of steady secular
affiliation with steady religious affiliation on meaning and purpose.}

\end{figure}%

\begin{table}

\caption{\label{tbl-secular_vs_religious}Contrast of steady secular
affiliation with steady religious affiliation on meaning and purpose.}

\centering{

\begin{verbatim}
                 E[Y(1)]-E[Y(0)]  2.5 % 97.5 % E_Value E_Val_bound
Meaning: Purpose          -0.107 -0.130 -0.083   1.438       1.371
Meaning: Sense            -0.093 -0.118 -0.067   1.398       1.323
\end{verbatim}

}

\end{table}%

Table~\ref{tbl-secular_vs_religious} and
Figure~\ref{fig-secular_vs_religious} present the comparison of the
intervention: Contrast Done Intervention with Steady Religiously
Affiliated (control)

\paragraph{Meaning: purpose}\label{meaning-purpose-2}

The effect estimate (rd) is -0.107 (-0.13, -0.083). On the original
scale, the estimated effect is -0.15 (-0.183, -0.117). E-value lower
bound is 1.371, indicating evidence for causality.

\paragraph{Meaning: sense}\label{meaning-sense-2}

The effect estimate (rd) is -0.093 (-0.118, -0.067). On the original
scale, the estimated effect is -0.112 (-0.143, -0.081). E-value lower
bound is 1.323, indicating evidence for causality.

\newpage{}

\subsection{Discussion}\label{discussion}

The question, ``Does religious disaffiliation affect meaning and
purpose?'' requires specificity. To interpret this question, we must
define the intervention, the time period, the outcome measures, and the
target population. We also need to assess whether the assumptions of
positivity, causal consistency, and conditional exchangeability are
plausible before conducting statistical estimation and sensitivity
analyses.

Here, we estimate New Zealand population-average responses to measures
of meaning and purpose from interventions on religious affiliation using
data from NZAVS time 10-time 14, years 2022-2023 of the New Zealand
Attitudes and Values Study. Our analysis relies on the assumption that
the modelled changes in religious affiliation status are conditionally
independent of the measured outcomes. We further assume that such
changes are possible for everyone in the study population (positivity).
Finally, we assume that -- conditional on baseline demographic measures,
religious affiliation, meaning and purpose, and time-varying factors
such as employment, parental, relationship, and disability status -- the
sequential treatment regimes are independent of potential outcomes, and
that treatment assignment in our analysis is ``as good as random.''

Under these assumptions, we find quantitative evidence supporting Max
Weber's concept of ``disenchantment'' following religious disaffiliation
(\citeproc{ref-weber1946science}{Weber 1946}). Disaffiliation is
\emph{causally associated} with lower levels of meaning and purpose
compared to remaining religiously affiliated. However, when measured
three years after disaffiliation, disaffiliates (``dones'') do not
reliably differ from their secular counterparts. Although religious
affiliation is associated with slightly higher levels of meaning and
purpose than secular affiliation, the observed effect sizes are modest,
around \(0.1\) in each comparison.

Our analysis does not account for treatment effect heterogeneity. It is
plausible that the effects of religious disaffiliation vary across
individuals. Furthermore, religious affiliation is only one dimension of
religiosity. Future research should examine the effects of religious
stability, loss, and gain across different aspects of religiosity, such
as spiritual identification, belief in a higher power, or religious
service attendance.

Although the observed effect sizes are small, their cumulative effect at
the population level might be more substantial. However, caution is
warranted in interpreting practical significance from our results. This
is a question for future research. For now, our findings align with
sociological theories of religious loss but do not suggest a widespread
disenchantment at the population level caused by disaffiliation.

Overall, although religious disaffiliation appears to diminish a sense
of meaning and purpose, disaffiliation does not suggest a crisis of
meaning across the target population. The world, as Weber described, may
indeed experience some disenchantment, but our findings indicate that
the effects are modest and far from alarming in New Zealand.

\newpage{}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Data Availability}\label{data-availability}

The data described in the paper are part of the New Zealand Attitudes
and Values Study. Members of the NZAVS management team and research
group hold full copies of the NZAVS data. A de-identified dataset
containing only the variables analysed in this manuscript is available
upon request from the corresponding author or any member of the NZAVS
advisory board for replication or checking of any published study using
NZAVS data. The code for the analysis can be found at:
\url{https://github.com/go-bayes/models/blob/main/scripts/24-bulbulia-church-prosocial.R}.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Planck Institute for the Science of Human History. The
funders had no role in preparing the manuscript or deciding to publish
it.

\subsubsection{Author Statement}\label{author-statement}

DVT suggested the topic, and developed the measures with CGS. JB
developed the analytic approach and did the analysis. All authors
contributed to the manuscript.

\newpage{}

\subsection{Appendix A: Measures}\label{appendix-measures}

\subsubsection{All Measures}\label{all-measures}

\paragraph{Age}\label{age}

\emph{What is your date of birth?}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth'').. Developed for the NZAVS.

\paragraph{Agreeableness}\label{agreeableness}

\emph{I sympathize with others' feelings.} \emph{I am not interested in
other people's problems.} \emph{I feel others' emotions.} \emph{I am not
really interested in others (reversed).}

Mini-IPIP6 Agreeableness dimension: (i) I sympathize with others'
feelings. (ii) I am not interested in other people's problems. (r) (iii)
I feel others' emotions. (iv) I am not really interested in others. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Alcohol Frequency}\label{alcohol-frequency}

\emph{``How often do you have a drink containing alcohol?''}

Participants could chose between the following responses: `(1 = Never -
I don't drink, 2 = Monthly or less, 3 = Up to 4 times a month, 4 = Up to
3 times a week, 5 = 4 or more times a week, 6 = Don't know)'
(\citeproc{ref-Ministry_of_Health_2013}{Health 2013}).

\paragraph{Alcohol Intensity}\label{alcohol-intensity}

\emph{``How many drinks containing alcohol do you have on a typical day
when drinking alcohol? (number of drinks on a typical day when
drinking)''}

Participants responded using an open-ended box
(\citeproc{ref-Ministry_of_Health_2013}{Health 2013}).

\paragraph{Belong}\label{belong}

\emph{Know that people in my life accept and value me.} \emph{Feel like
an outsider.} \emph{Know that people around me share my attitudes and
beliefs.}

We assessed felt belongingness with three items adapted from the Sense
of Belonging Instrument (Hagerty \& Patusky, 1995): (1) ``Know that
people in my life accept and value me''; (2) ``Feel like an outsider'';
(3) ``Know that people around me share my attitudes and beliefs''.
Participants responded on a scale from 1 (Very Inaccurate) to 7 (Very
Accurate). The second item was reversely coded
(\citeproc{ref-hagerty1995}{Hagerty and Patusky 1995}).

\paragraph{Born Nz (Binary)}\label{born-nz-binary}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).. Developed for the NZAVS.

\paragraph{Conscientiousness}\label{conscientiousness}

\emph{I get chores done right away.} \emph{I like order.} \emph{I make a
mess of things.} \emph{I often forget to put things back in their proper
place.}

Mini-IPIP6 Conscientiousness dimension: (i) I get chores done right
away. (ii) I like order. (iii) I make a mess of things. (r) (iv) I often
forget to put things back in their proper place. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Education Level Coarsen}\label{education-level-coarsen}

\emph{What is your highest level of qualification?}

We asked participants, ``What is your highest level of qualification?''.
We coded participans highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school qualifications coded as Level 3, and all other ancillary
categories coded as missing). Developed for the NZAVS.

\paragraph{Employed (Binary)}\label{employed-binary}

\emph{Are you currently employed (This includes self-employed of casual
work)?}

Binary response: (0 = No, 1 = Yes). Stats NZ Census Question.

\paragraph{Eth Cat (Categorical)}\label{eth-cat-categorical}

\emph{Which ethnic group(s) do you belong to?}

Coded string: (1 = New Zealand European; 2 = Māori; 3 = Pacific; 4 =
Asian). NZ Census coding.

\paragraph{Extraversion}\label{extraversion}

\emph{I am the life of the party.} \emph{I don't talk a lot (reversed).}
\emph{I keep in the background (reversed).} \emph{I talk to a lot of
different people at parties.}

Mini-IPIP6 Extraversion dimension: (i) I am the life of the party. (ii)
I don't talk a lot. (r) (iii) I keep in the background. (r) (iv) I talk
to a lot of different people at parties
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Hlth Disability (Binary)}\label{hlth-disability-binary}

We assessed disability with a one-item indicator adapted from Verbrugge
(1997). It asks, ``Do you have a health condition or disability that
limits you and that has lasted for 6+ months?'' (1 = Yes, 0 = No)
(\citeproc{ref-verbrugge1997}{Verbrugge 1997}).

\paragraph{Honesty Humility}\label{honesty-humility}

\emph{I feel entitled to more of everything (reversed).} \emph{I deserve
more things in life (reversed).} \emph{I deserve more things in life
(reversed).} \emph{I would get a lot of pleasure from owning expensive
luxury goods (reversed).}

Mini-IPIP6 Honesty-Humility dimension: (i) I feel entitled to more of
everything. (r) (ii) I deserve more things in life. (r) (iii) I would
like to be seen driving around in a very expensive car. (r) (iv) I would
get a lot of pleasure from owning expensive luxury goods. (r)
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Kessler Latent Anxiety}\label{kessler-latent-anxiety}

\emph{During the past 30 days, how often did\ldots you feel restless or
fidgety?} \emph{During the past 30 days, how often did\ldots you feel
that everything was an effort?} \emph{During the past 30 days, how often
did\ldots you feel nervous?}

Ordinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2=
Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time)
(\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002}).

\paragraph{Kessler Latent Depression}\label{kessler-latent-depression}

\emph{During the past 30 days, how often did\ldots you feel hopeless?}
\emph{During the past 30 days, how often did\ldots you feel so depressed
that nothing could cheer you up?} \emph{During the past 30 days, how
often did\ldots you feel you feel restless or fidgety?}

Ordinal response: (0 = None Of The Time; 1 = A Little Of The Time; 2=
Some Of The Time; 3 = Most Of The Time; 4 = All Of The Time)
(\citeproc{ref-kessler2002}{Kessler \emph{et al.} 2002}).

\paragraph{Log Hours Children}\label{log-hours-children}

\emph{Hours spent\ldots looking after children.}

We took the natural log of the response + 1
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Log Hours Commute}\label{log-hours-commute}

\emph{Hours spent\ldots travelling/commuting.}

We took the natural log of the response + 1.. Developed for the NZAVS.

\paragraph{Log Hours Exercise}\label{log-hours-exercise}

\emph{Hours spent\ldots exercising/physical activity.}

We took the natural log of the response + 1
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Log Hours Housework}\label{log-hours-housework}

\emph{Hours spent\ldots housework/cooking.}

We took the natural log of the response + 1
(\citeproc{ref-sibley2011}{Sibley \emph{et al.} 2011}).

\paragraph{Log Household Inc}\label{log-household-inc}

\emph{Please estimate your total household income (before tax) for the
year XXXX.}

We took the natural log of the response + 1.. Developed for the NZAVS.

\paragraph{Male (Binary)}\label{male-binary}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3 (Fraser et al.,
2020). (or 0.5 = neither female nor male). Here, we coded all those who
responded as Male as 1, and those who did not as 0
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}).

\paragraph{Neuroticism}\label{neuroticism}

\emph{I have frequent mood swings.} \emph{I am relaxed most of the time
(reversed).} \emph{I get upset easily.} \emph{I seldom feel blue
(reversed).}

Mini-IPIP6 Neuroticism dimension: (i) I have frequent mood swings. (ii)
I am relaxed most of the time. (r) (iii) I get upset easily. (iv) I
seldom feel blue. (r) (\citeproc{ref-sibley2011}{Sibley \emph{et al.}
2011}).

\paragraph{Not Heterosexual (Binary)}\label{not-heterosexual-binary}

\emph{How would you describe your sexual orientation? (e.g.,
heterosexual, homosexual, straight, gay, lesbian, bisexual, etc.)}

Open-ended question, coded as binary (not heterosexual = 1)
(\citeproc{ref-greaves2017diversity}{Greaves \emph{et al.} 2017}).

\paragraph{Nz Dep2018}\label{nz-dep2018}

\emph{New Zealand Deprivation - Decile Index - Using 2018 Census Data}

Numerical: (1-10) (\citeproc{ref-atkinson2019}{Atkinson \emph{et al.}
2019}).

\paragraph{Nzsei 13 l}\label{nzsei-13-l}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (Fahy et al., 2017). This index uses
the income, age, and education of a reference group, in this case, the
2013 New Zealand census, to calculate a score for each occupational
group. Scores range from 10 (Lowest) to 90 (Highest). This list of index
scores for occupational groups was used to assign each participant a
NZSEI-13 score based on their occupation (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017}).

\paragraph{Openness}\label{openness}

\emph{I have a vivid imagination.} \emph{I have difficulty understanding
abstract ideas (reversed).} \emph{I do not have a good imagination
(reversed).} \emph{I am not interested in abstract ideas (reversed).}

Mini-IPIP6 Openness to Experience dimension: (i) I have a vivid
imagination. (ii) I have difficulty understanding abstract ideas. (r)
(iii) I do not have a good imagination. (r) (iv) I am not interested in
abstract ideas. (r) (\citeproc{ref-sibley2011}{Sibley \emph{et al.}
2011}).

\paragraph{Parent (Binary)}\label{parent-binary}

We asked participants, ``If you are a parent, what is the birth date of
your eldest child?'' or ``If you are a parent, in which year was your
eldest child born?'' (waves: 10-current). Parents were coded as 1, while
the others were coded as 0.. Developed for the NZAVS.

\paragraph{Partner (Binary)}\label{partner-binary}

\emph{What is your relationship status? (e.g., single, married,
de-facto, civil union, widowed, living together, etc.)}

Coded as binary (has partner = 1).. Developed for the NZAVS.

\paragraph{Political Conservative}\label{political-conservative}

\emph{Please rate how politically liberal versus conservative you see
yourself as being.}

Ordinal response: (1 = Extremely Liberal, 7 = Extremely Conservative)
(\citeproc{ref-jost_end_2006-1}{Jost 2006}).

\paragraph{Power No Control Composite}\label{power-no-control-composite}

\emph{I do not have enough power or control over important parts of my
life.} \emph{Other people have too much power or control over important
parts of my life.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-overall2016power}{Overall \emph{et al.} 2016}).

\paragraph{Rural Gch 2018 l}\label{rural-gch-2018-l}

\emph{High Urban Accessibility = 1, Medium Urban Accessibility = 2, Low
Urban Accessibility = 3, Remote = 4, Very Remote = 5.}

``Participants residence locations were coded according to a five-level
ordinal categorisation ranging from Urban to Rural.''
(\citeproc{ref-whitehead2023unmasking}{Whitehead \emph{et al.} 2023}).

\paragraph{Sample Frame Opt in
(Binary)}\label{sample-frame-opt-in-binary}

\emph{Participant was not randomly sampled from the New Zealand
Electoral Roll.}

Code string (Binary): (0 = No, 1 = Yes). Developed for the NZAVS.

\paragraph{Short Form Health}\label{short-form-health}

\emph{In general, would you say your health is\ldots{}}

Ordinal response: (1 = Poor, 7 = Excellent)
(\citeproc{ref-instrument1992mos}{Instrument Ware Jr and Sherbourne
1992}).

\paragraph{Smoker (Binary)}\label{smoker-binary}

\emph{Do you currently smoke tobacco cigarettes?}

Binary smoking indicator (0 = No, 1 = Yes).. Developed for NZAVS.

\paragraph{Support}\label{support}

\emph{There are people I can depend on to help me if I really need it.}
\emph{There is no one I can turn to for guidance in times of stress
(reversed).} \emph{I know there are people I can turn to when I need
help.}

Ordinal response: (1 = Strongly Disagree, 7 = Strongly Agree)
(\citeproc{ref-cutrona1987}{Cutrona and Russell 1987}).

\paragraph{Religion Religious (Binary)}\label{religion-religious-binary}

\emph{Do you identify with a religion and/or spiritual group?}

Binary response: (0 = No, 1 = Yes). Stats NZ Census Question.

\paragraph{Meaning Purpose}\label{meaning-purpose-3}

\emph{My life has a clear sense of purpose}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree)
(\citeproc{ref-steger_meaning_2006}{Steger \emph{et al.} 2006}).

\paragraph{Meaning Sense}\label{meaning-sense-3}

\emph{I have a good sense of what makes my life meaningful.}

Ordinal response (1 = Strongly Disagree to 7 = Strongly Agree)
(\citeproc{ref-steger_meaning_2006}{Steger \emph{et al.} 2006}).

\newpage{}

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{longtable}[]{@{}ll@{}}
\caption{Baseline demographic
statistics}\label{tbl-table-demography}\tabularnewline
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,202} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 47,202} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 49 (14) \\
Min, Max & 18, 99 \\
Q1, Q3 & 39, 60 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.35 (0.99) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.75, 6.00 \\
Unknown & 429 \\
\textbf{Alcohol Frequency} & NA \\
0 & 5,857 (13\%) \\
1 & 10,746 (24\%) \\
2 & 8,735 (19\%) \\
3 & 10,826 (24\%) \\
4 & 9,258 (20\%) \\
5 & 157 (0.3\%) \\
Unknown & 1,623 \\
\textbf{Alcohol Intensity} & NA \\
Mean (SD) & 2.17 (2.17) \\
Min, Max & 0.00, 30.00 \\
Q1, Q3 & 1.00, 3.00 \\
Unknown & 2,813 \\
\textbf{Belong} & NA \\
Mean (SD) & 5.14 (1.08) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.33, 6.00 \\
Unknown & 426 \\
\textbf{Born Nz Binary} & 36,834 (78\%) \\
Unknown & 162 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.11 (1.06) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.50, 6.00 \\
Unknown & 420 \\
\textbf{Education Level Coarsen} & NA \\
no\_qualification & 1,217 (2.6\%) \\
cert\_1\_to\_4 & 16,581 (36\%) \\
cert\_5\_to\_6 & 5,941 (13\%) \\
university & 12,510 (27\%) \\
post\_grad & 5,099 (11\%) \\
masters & 3,901 (8.4\%) \\
doctorate & 1,120 (2.4\%) \\
Unknown & 833 \\
\textbf{Employed Binary} & 37,497 (80\%) \\
Unknown & 67 \\
\textbf{Eth Cat} & NA \\
euro & 37,660 (81\%) \\
maori & 5,345 (11\%) \\
pacific & 1,108 (2.4\%) \\
asian & 2,466 (5.3\%) \\
Unknown & 623 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.91 (1.20) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 3.00, 4.75 \\
Unknown & 420 \\
\textbf{Hlth Disability Binary} & 10,399 (22\%) \\
Unknown & 903 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.41 (1.18) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.75, 6.25 \\
Unknown & 425 \\
\textbf{Hours Children} & NA \\
Mean (SD) & 14 (32) \\
Min, Max & 0, 168 \\
Q1, Q3 & 0, 10 \\
Unknown & 1,476 \\
\textbf{Hours Commute} & NA \\
Mean (SD) & 5.3 (6.4) \\
Min, Max & 0.0, 80.0 \\
Q1, Q3 & 2.0, 7.0 \\
Unknown & 1,476 \\
\textbf{Hours Exercise} & NA \\
Mean (SD) & 6 (8) \\
Min, Max & 0, 80 \\
Q1, Q3 & 2, 7 \\
Unknown & 1,476 \\
\textbf{Hours Housework} & NA \\
Mean (SD) & 10 (10) \\
Min, Max & 0, 168 \\
Q1, Q3 & 5, 14 \\
Unknown & 1,476 \\
\textbf{Household Inc} & NA \\
Mean (SD) & 115,092 (92,493) \\
Min, Max & 1, 3,005,000 \\
Q1, Q3 & 60,000, 150,000 \\
Unknown & 3,082 \\
\textbf{Kessler Latent Anxiety} & NA \\
Mean (SD) & 1.21 (0.77) \\
Min, Max & 0.00, 4.00 \\
Q1, Q3 & 0.67, 1.67 \\
Unknown & 467 \\
\textbf{Kessler Latent Depression} & NA \\
Mean (SD) & 0.59 (0.75) \\
Min, Max & 0.00, 4.00 \\
Q1, Q3 & 0.00, 1.00 \\
Unknown & 470 \\
\textbf{Log Hours Children} & NA \\
Mean (SD) & 1.16 (1.61) \\
Min, Max & 0.00, 5.13 \\
Q1, Q3 & 0.00, 2.40 \\
Unknown & 1,476 \\
\textbf{Log Hours Commute} & NA \\
Mean (SD) & 1.50 (0.83) \\
Min, Max & 0.00, 4.39 \\
Q1, Q3 & 1.10, 2.08 \\
Unknown & 1,476 \\
\textbf{Log Hours Exercise} & NA \\
Mean (SD) & 1.54 (0.85) \\
Min, Max & 0.00, 4.39 \\
Q1, Q3 & 1.10, 2.08 \\
Unknown & 1,476 \\
\textbf{Log Hours Housework} & NA \\
Mean (SD) & 2.14 (0.78) \\
Min, Max & 0.00, 5.13 \\
Q1, Q3 & 1.70, 2.71 \\
Unknown & 1,476 \\
\textbf{Log Household Inc} & NA \\
Mean (SD) & 11.39 (0.77) \\
Min, Max & 0.69, 14.92 \\
Q1, Q3 & 11.00, 11.92 \\
Unknown & 3,082 \\
\textbf{Male Binary} & 17,458 (37\%) \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.49 (1.15) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 2.75, 4.25 \\
Unknown & 431 \\
\textbf{Not Heterosexual Binary} & 3,055 (6.7\%) \\
Unknown & 1,779 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.77 (2.73) \\
Min, Max & 1.00, 10.00 \\
Q1, Q3 & 2.00, 7.00 \\
Unknown & 308 \\
\textbf{Nzsei 13 l} & NA \\
Mean (SD) & 54 (17) \\
Min, Max & 10, 90 \\
Q1, Q3 & 41, 69 \\
Unknown & 479 \\
\textbf{Openness} & NA \\
Mean (SD) & 4.96 (1.12) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.25, 5.75 \\
Unknown & 423 \\
\textbf{Parent Binary} & 33,444 (71\%) \\
\textbf{Partner Binary} & 34,660 (75\%) \\
Unknown & 1,026 \\
\textbf{Political Conservative} & NA \\
1 & 2,510 (5.6\%) \\
2 & 8,662 (19\%) \\
3 & 8,802 (20\%) \\
4 & 13,866 (31\%) \\
5 & 6,679 (15\%) \\
6 & 3,292 (7.4\%) \\
7 & 736 (1.7\%) \\
Unknown & 2,655 \\
\textbf{Power No Control Composite} & NA \\
Mean (SD) & 2.97 (1.42) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 2.00, 4.00 \\
Unknown & 251 \\
\textbf{Rural Gch 2018 l} & NA \\
1 & 29,050 (62\%) \\
2 & 8,851 (19\%) \\
3 & 5,779 (12\%) \\
4 & 2,647 (5.6\%) \\
5 & 569 (1.2\%) \\
Unknown & 306 \\
\textbf{Sample Frame Opt in Binary} & 1,379 (2.9\%) \\
\textbf{Short Form Health} & NA \\
Mean (SD) & 5.04 (1.17) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 4.33, 6.00 \\
Unknown & 9 \\
\textbf{Smoker Binary} & 3,363 (7.3\%) \\
Unknown & 1,200 \\
\textbf{Support} & NA \\
Mean (SD) & 5.95 (1.12) \\
Min, Max & 1.00, 7.00 \\
Q1, Q3 & 5.33, 7.00 \\
Unknown & 37 \\
\end{longtable}

Table~\ref{tbl-table-demography} baseline demographic statistics for
participants who met inclusion criteria.

\newpage{}

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, JA (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-bulbulia2023}
Bulbulia, JA (2024c) Methods in causal inference part 1: Causal diagrams
and confounding. \emph{Evolutionary Human Sciences}, \textbf{6}, e40.
doi:\href{https://doi.org/10.1017/ehs.2024.35}{10.1017/ehs.2024.35}.

\bibitem[\citeproctext]{ref-bulbulia2024swigstime}
Bulbulia, JA (2024d) Methods in causal inference part 2: Interaction,
mediation, and time-varying treatments. \emph{Evolutionary Human
Sciences}, \textbf{6}, e41.
doi:\href{https://doi.org/10.1017/ehs.2024.32}{10.1017/ehs.2024.32}.

\bibitem[\citeproctext]{ref-chatton2020}
Chatton, A, Le Borgne, F, Leyrat, C, \ldots{} Foucher, Y (2020)
G-computation, propensity score-based methods, and targeted maximum
likelihood estimator for causal inference with different covariates
sets: a comparative simulation study. \emph{Scientific Reports},
\textbf{10}(1), 9219.
doi:\href{https://doi.org/10.1038/s41598-020-65917-x}{10.1038/s41598-020-65917-x}.

\bibitem[\citeproctext]{ref-cutrona1987}
Cutrona, CE, and Russell, DW (1987) The provisions of social
relationships and adaptation to stress. \emph{Advances in Personal
Relationships}, \textbf{1}, 37--67.

\bibitem[\citeproctext]{ref-danaei2012}
Danaei, G, Tavakkoli, M, and Hernán, MA (2012) Bias in observational
studies of prevalent users: lessons for comparative effectiveness
research from a meta-analysis of statins. \emph{American Journal of
Epidemiology}, \textbf{175}(4), 250--262.
doi:\href{https://doi.org/10.1093/aje/kwr301}{10.1093/aje/kwr301}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-diaz2023lmtp}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2023) Nonparametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association},
\textbf{118}(542), 846--857.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017) \emph{{N}ew {Z}ealand
socio-economic index 2013}, Wellington, New Zealand: Statistics New
Zealand-Tatauranga Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a {N}ew {Z}ealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-glmnet_use_2010}
Friedman, J, Hastie, T, and Tibshirani, R (2010) Regularization paths
for generalized linear models via coordinate descent. \emph{Journal of
Statistical Software}, \textbf{33}(1), 1.

\bibitem[\citeproctext]{ref-greaves2017diversity}
Greaves, LM, Barlow, FK, Lee, CH, et al.others (2017) The diversity and
prevalence of sexual orientation self-labels in a {N}ew {Z}ealand
national sample. \emph{Archives of Sexual Behavior}, \textbf{46},
1325--1336.

\bibitem[\citeproctext]{ref-hagerty1995}
Hagerty, BMK, and Patusky, K (1995) Developing a Measure Of Sense of
Belonging: \emph{Nursing Research}, \textbf{44}(1), 9--13.
doi:\href{https://doi.org/10.1097/00006199-199501000-00003}{10.1097/00006199-199501000-00003}.

\bibitem[\citeproctext]{ref-haneuse2013estimation}
Haneuse, S, and Rotnitzky, A (2013) Estimation of the effect of
interventions that modify the received treatment. \emph{Statistics in
Medicine}, \textbf{32}(30), 5260--5277.

\bibitem[\citeproctext]{ref-Ministry_of_Health_2013}
Health, Ministry of (2013) \emph{The {N}ew {Z}ealand {H}ealth {S}urvey:
Content guide 2012-2013}, Princeton University Press.

\bibitem[\citeproctext]{ref-hernan2024WHATIF}
Hernan, MA, and Robins, JM (2024) \emph{Causal inference: What if?},
Taylor \& Francis. Retrieved from
\url{https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/}

\bibitem[\citeproctext]{ref-hernuxe1n2016}
Hernán, MA, Sauer, BC, Hernández-Díaz, S, Platt, R, and Shrier, I (2016)
Specifying a target trial prevents immortal time bias and other
self-inflicted injuries in observational analyses. \emph{Journal of
Clinical Epidemiology}, \textbf{79}, 70--75.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-instrument1992mos}
Instrument Ware Jr, J, and Sherbourne, C (1992) The MOS 36-item
short-form health survey (SF-36): I. Conceptual framework and item
selection. \emph{Medical Care}, \textbf{30}(6), 473--483.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-kessler2002}
Kessler, R~C, Andrews, G, Colpe, L~J, \ldots{} Zaslavsky, A~M (2002)
Short screening scales to monitor population prevalences and trends in
non-specific psychological distress. \emph{Psychological Medicine},
\textbf{32}(6), 959--976.
doi:\href{https://doi.org/10.1017/S0033291702006074}{10.1017/S0033291702006074}.

\bibitem[\citeproctext]{ref-van2012targeted}
Laan, MJ van der, and Gruber, S (2012) Targeted minimum loss based
estimation of causal effects of multiple time point interventions.
\emph{The International Journal of Biostatistics}, \textbf{8}(1).

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-overall2016power}
Overall, NC, Hammond, MD, McNulty, JK, and Finkel, EJ (2016) When power
shapes interpersonal behavior: Low relationship power predicts men's
aggressive responses to low situational power. \emph{Journal of
Personality and Social Psychology}, \textbf{111}(2), 195.

\bibitem[\citeproctext]{ref-pearl2009a}
Pearl, J (2009) \emph{Causality}, Cambridge University Press.

\bibitem[\citeproctext]{ref-SuperLearner2023}
Polley, E, LeDell, E, Kennedy, C, and van der Laan, M (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://github.com/ecpolley/SuperLearner}

\bibitem[\citeproctext]{ref-robins1986}
Robins, J (1986) A new approach to causal inference in mortality studies
with a sustained exposure period---application to control of the healthy
worker survivor effect. \emph{Mathematical Modelling}, \textbf{7}(9-12),
1393--1512.

\bibitem[\citeproctext]{ref-sibley2021}
Sibley, CG (2021)
\emph{\href{https://doi.org/10.31234/osf.io/wgqvy}{Sampling procedure
and sample details for the {N}ew {Z}ealand {A}ttitudes and {V}alues
{S}tudy}}.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in {N}ew {Z}ealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-steger_meaning_2006}
Steger, MF, Frazier, P, Oishi, S, and Kaler, M (2006) The meaning in
life questionnaire: Assessing the presence of and search for meaning in
life. \emph{Journal of Counseling Psychology}, \textbf{53}(1), 80--93.
doi:\href{https://doi.org/10.1037/0022-0167.53.1.80}{10.1037/0022-0167.53.1.80}.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-van2014targeted}
Van der Laan, MJ (2014) Targeted estimation of nuisance parameters to
obtain valid statistical inference. \emph{The International Journal of
Biostatistics}, \textbf{10}(1), 29--57.

\bibitem[\citeproctext]{ref-vanderweele2009}
VanderWeele, TJ (2009) Concerning the consistency assumption in causal
inference. \emph{Epidemiology}, \textbf{20}(6), 880.
doi:\href{https://doi.org/10.1097/EDE.0b013e3181bd5638}{10.1097/EDE.0b013e3181bd5638}.

\bibitem[\citeproctext]{ref-vanderweele2015}
VanderWeele, TJ (2015) \emph{Explanation in causal inference: Methods
for mediation and interaction}, Oxford University Press.

\bibitem[\citeproctext]{ref-vanderweele2019}
VanderWeele, TJ (2019) Principles of confounder selection.
\emph{European Journal of Epidemiology}, \textbf{34}(3), 211--219.

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the {E}-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 1--20.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437--466.

\bibitem[\citeproctext]{ref-verbrugge1997}
Verbrugge, LM (1997) A global disability indicator. \emph{Journal of
Aging Studies}, \textbf{11}(4), 337--362.
doi:\href{https://doi.org/10.1016/S0890-4065(97)90026-8}{10.1016/S0890-4065(97)90026-8}.

\bibitem[\citeproctext]{ref-weber1946science}
Weber, M (1946) Science as a vocation. In \emph{Science and the quest
for reality}, Springer, 382--394.

\bibitem[\citeproctext]{ref-westreich2010}
Westreich, D, and Cole, SR (2010) Invited commentary: positivity in
practice. \emph{American Journal of Epidemiology}, \textbf{171}(6).
doi:\href{https://doi.org/10.1093/aje/kwp436}{10.1093/aje/kwp436}.

\bibitem[\citeproctext]{ref-whitehead2023unmasking}
Whitehead, J, Davie, G, Graaf, B de, \ldots{} Nixon, G (2023) Unmasking
hidden disparities: A comparative observational study examining the
impact of different rurality classifications for health research in
aotearoa new zealand. \emph{BMJ Open}, \textbf{13}(4), e067927.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{{l}mtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\bibitem[\citeproctext]{ref-wilson2014differences}
Wilson, MS, Bulbulia, J, and Sibley, CG (2014) Differences and
similarities in religious and paranormal beliefs: A typology of distinct
faith signatures. \emph{Religion, Brain \& Behavior}, \textbf{4}(2),
104--126.

\bibitem[\citeproctext]{ref-Ranger2017}
Wright, MN, and Ziegler, A (2017) {ranger}: A fast implementation of
random forests for high dimensional data in {C++} and {R}. \emph{Journal
of Statistical Software}, \textbf{77}(1), 1--17.
doi:\href{https://doi.org/10.18637/jss.v077.i01}{10.18637/jss.v077.i01}.

\bibitem[\citeproctext]{ref-zhang2023shouldMultipleImputation}
Zhang, J, Dashti, SG, Carlin, JB, Lee, KJ, and Moreno-Betancur, M (2023)
Should multiple imputation be stratified by exposure group when
estimating causal effects via outcome regression in observational
studies? \emph{BMC Medical Research Methodology}, \textbf{23}(1), 42.

\end{CSLReferences}




\end{document}
