% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  singlecolumn]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage[]{libertinus}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=30mm,left=20mm,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={How Would a Change in My Perfectionism Affect My Partner's Relationship Attitudes? A National Longitudinal Causal Investigation in Romantic Couples},
  pdfauthor={Aaron T. McLaughlin; Ken Rice; Hannah Weststone; Don E Davis; Chris G. Sibley; Joseph A. Bulbulia},
  pdfkeywords={Causal Inference, Perfectionism, Relationships, Dyads},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{How Would a Change in My Perfectionism Affect My Partner's
Relationship Attitudes? A National Longitudinal Causal Investigation in
Romantic Couples}
\author{Aaron T. McLaughlin \and Ken Rice \and Hannah Weststone \and Don
E Davis \and Chris G. Sibley \and Joseph A. Bulbulia}
\date{2024-04-11}

\begin{document}
\maketitle
\begin{abstract}
Perfectionism can build us up and tear us down. However, its effects on
romantic relationships remain unclear. Here, we use combine rigorous
methods for causal inference with national-scale panel data (N = 1860
participants in 930 couples, New Zealand Attitudes and Values Study
years 2018-2021) to quantitatively investigate how shifts up and down in
a focal agent's perfectionism affect their partner's (1) relationship
satisfaction (2) perceived conflict within the relationship (3) sexual
satisfaction. All models controlled for both focal agent and
partner-relationship perceptions at baseline and for demographic and
personality measures again for both focal agent and partner. We computed
pre-specified interventions for shifts up and down in focal agent
perfectionism. We find that a hypothetical intervention that increases
perfectionism by two units on a 1-7 Likert scale increases
partner-perceived conflict and decreases sexual satisfaction but does
not substantially affect partner relationship satisfaction at the end of
the study. An intervention that decreases perfectionism by two units
across the population of couples is expected to increase partner sexual
satisfaction and weakly decrease partner-perceived conflict, without
evidence for effects on relationship satisfaction. Let go of
perfectionism to improve your love life.
\end{abstract}

\subsection{Introduction}\label{introduction}

A central question in the psychology of perfection research is how it
causally affects the qualities of romantic relationships.

\subsection{Method}\label{method}

\subsubsection{Sample}\label{sample}

Data were collected as part of The New Zealand Attitudes and Values
Study (NZAVS) is an annual longitudinal national probability panel study
of social attitudes, personality, ideology and health outcomes. The
NZAVS is university-based, not-for-profit and independent of political
or corporate funding.https://doi.org/10.17605/OSF.IO/75SNB. The NZAVS
began in 2009. It includes questionnaire responses from 72910 Zealand
residents. Through a combination of random sampling and study-opt-in, a
total of 930 have participated in the NZAVS since 2009. Of those, 930
participated in NZAVS wave 2018 and we eligible for this study.

\hyperref[appendix-measures]{Appendix A} provides statistical
information about the measures used in this study.

\hyperref[appendix-demographics]{Appendix B} provides information about
demographic covariates used for confounding control (NZAVS time 10,
years 2018-2019).

\hyperref[appendix-exposures]{Appendix C} provides information about the
treatment responses at baseline (NZAVS time 10) and in the treatment
wave (NZAVS time 11, years 2019-2020).

\hyperref[appendix-outcomes]{Appendix D} provides information about
about the outcome variables responses at baseline (NZAVS time 10) and in
the treatment wave (NZAVS time 12, years 2020-2021).

\subsubsection{Eligibility criteria}\label{eligibility-criteria}

The sample consisted of respondents to NZAVS times 10 (baseline, years
2018-2019), time 11 (treatment wave, years 2019-2020), and time 12
(outcome wave) (years 2020-2021).

\paragraph{Included}\label{included}

\begin{itemize}
\tightlist
\item
  Participants who were identified as being in couples.\\
\item
  Participants who provided full information to the perfectionism
  measure at baseline
\end{itemize}

\subparagraph{Excluded}\label{excluded}

\begin{itemize}
\tightlist
\item
  Participants who had missing responses to the perfectionism at
  baseline.
\item
  We allowed loss-to-follow-up in the following waves (NZAVS wave 2019,
  years 2019-2020, and NZAVS wave 2020, years 2020 - 2021)
\item
  Missing responses at baseline for all variables except the treatment
  were permitted and imputed using the ppm algorithm of the
  \texttt{mice} package (\citeproc{ref-vanbuuren2018}{Van Buuren 2018}).
\item
  Inverse probability of censoring weights were calculated for those
  lost to follow up as part of estimation in \texttt{lmtp} to adjust for
  missing outcomes at NZAVS Time 12 (years 2020-2021, the outcome wave
  (\citeproc{ref-williams2021}{Williams and Díaz 2021}))
\end{itemize}

There were 1860 NZAVS participants in 930 couples who met these
criteria.

\subsubsection{Causal Contrast}\label{causal-contrast}

Here, we leverage panel data to estimate potential outcomes in a
hypothetical world where partners in couples were shifted up or down by
two points on a 1-7 scale for perfectionism.

Our causal estimand takes a ``shift function'' or ``modified treatment
policy'', where the interventions take the form of interventions defined
by the following functions:

\begin{itemize}
\item
  \textbf{Shift up by +2 points up to the maximum of the scale range:}
  \[
   \mathbf{d}^\lambda (a_t) = \begin{cases} a_t + 2 & \text{if $a_t$ < 5} \\ 
  a_t = 7 & \text{otherwise} \end{cases}
   \]
\item
  \textbf{Shift down by -2 points up to the minimum of the scale range}
  \[
   \mathbf{d}^\phi (a_t) = \begin{cases} a_t - 2 & \text{if $a_t$ > 3} \\ 
  a_t = 1 & \text{otherwise} \end{cases}
   \]
\item
  \textbf{No intervention} \[
   \mathbf{d}(a_t) = \text{the observed value of $a_t$ is assumed with out modification}
   \]
\end{itemize}

Thus our contrasts were given by the interventions:

\begin{itemize}
\tightlist
\item
  \textbf{increase +2 function}: increases the treatment variable by one
  unit, capped at the maximum observed score.
\item
  \textbf{decrease -2 function}: decreases the treatment variable by one
  unit, floored at the minimum observed score.
\item
  \textbf{`null' model:} the null model was specified identically to the
  treatment effect models in terms of the included covariates, outcome
  variable, and model structure but without applying any shift to the
  treatment variable.
\end{itemize}

A gain contrast was obtained by contrasting the +2 function against the
null model:

\[ \text{Longitudinal Motified Treatment Policy: shift up} = E[Y(\mathbf{d}^\lambda)- Y(\mathbf{d})] \]

A loss contrast was obtained by contrasting the -2 function against the
null model:

\[ \text{Longitudinal Motified Treatment Policy: shift down} = E[Y(\mathbf{d}^\phi)- Y(\mathbf{d})] \]

By estimating a model under the assumption of no change in the treatment
status, we obtained clear baselines against which the effects of the
hypothetical interventions on perfectionism be assessed, as measured by
\emph{parnter outcomes}.

\subsubsection{Identification
Assumptions}\label{identification-assumptions}

To consistently estimate causal effects, we rely on three key
assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Causal consistency:} potential outcomes must align with
  observed outcomes under the treatments in our data. Essentially, we
  assume potential outcomes do not depend on the specific way treatment
  was administered as long as we consider measured covariates.
\item
  \textbf{Strong sequential randomization} given the observed
  covariates, we assume treatment assignment is independent both of the
  potential outcomes to be contrasted and all future counterfactual
  responses (see {[}{]}). In simpler terms, this means ``no unmeasured
  confounding'' in each sequential treatment at
  \(\bar{A}_\tau: t \in 1\dots \tau\).
\item
  \textbf{Positivity:} for unbiased estimation, every subject must have
  a non-zero chance of receiving the treatment, regardless of their
  covariate values. We evaluate this assumption in each study by
  examining changes in perfectionism ``treatments'' from baseline (NZAVS
  time 10) to the treatment wave (NZAVS time 11). It is the initiation
  of a shift in perfectionism whose causal effect we seek to quantify
\end{enumerate}

\subsubsection{Confounding Control
Strategy}\label{confounding-control-strategy}

We followed VanderWeele \emph{et al.}
(\citeproc{ref-vanderweele2020}{2020})'s \emph{minimally modified
disjunctive criteria} for confounding control.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Initial identify confounders}: using causal diagrams, we began
  by enumerating all covariates that may influence either the treatment
  (exposure) or outcomes, spanning five domains. This includes variables
  directly affecting the exposure or outcome and potential consequences
  of these variables (i.e.~proxies.)
\item
  \textbf{Remove instrumental variables}: we removed variables that are
  identified as instrumental variables, i.e., those influencing the
  exposure but not the outcome. Their inclusion can reduce the
  efficiency of the analysis.
\item
  \textbf{Include of proxy variables}: for unmeasured variables that
  affect both the exposure and outcome, include proxy variables wherever
  possible. These proxies act as indicators for the unmeasured common
  causes. \hyperref[appendix-demographics]{Appendix B} lists covariates
  we used for confounding control. These protocols follow the advice in
  (\citeproc{ref-bulbulia2024PRACTICAL}{Bulbulia 2024a}) as prespecified
  in \url{https://osf.io/ce4t9/}.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Baseline outcome control}: we also included baseline measures
  of the outcome to adjust for unmeasured confounding
  (\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). This
  strategy also minimises the possibility of reverse causation.
\end{enumerate}

Additionally, we adopted the following confounding-control strategies:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
  \textbf{Partner's covariates}: because the effect of changes in one
  individual's variables on their partner's outcomes is assessed, we
  include baseline measures for the partner's covariates, as we as the
  focal partner. Additionally, we clustered individuals with their
  dyadic partnerships, which helps adjust for unmeasured features that
  might affect results.
\item
  \textbf{Handling missing data}: as mentioned, to better ensure that
  the analyses were robust to potential biases introduced by missing
  data, we adopted the following strategies:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  \textbf{Baseline missingness}: we imputed missing data to recover
  baseline missing data (\texttt{mice} package in R)
  (\citeproc{ref-vanbuuren2018}{Van Buuren 2018}).
\item
  \textbf{Follow-up missingness}: We used the \texttt{lmtp} package's
  built-in censoring weighting to adjust for loss-to-follow-up/sample
  attrition (\citeproc{ref-williams2021}{Williams and Díaz 2021}).
\end{itemize}

\paragraph{Estimator}\label{estimator}

We employ a semi-parametric estimator known as Targeted Minimum
Loss-based Estimation (TMLE), which is able to estimate the causal
effect of modified treatment policies on outcomes over time
(\citeproc{ref-vanderlaan2011}{Van Der Laan and Rose 2011},
\citeproc{ref-vanderlaan2018}{2018}). Estimation was performed using
\texttt{lmtp} package (\citeproc{ref-duxedaz2021}{Díaz \emph{et al.}
2021}; \citeproc{ref-hoffman2023}{Hoffman \emph{et al.} 2023};
\citeproc{ref-williams2021}{Williams and Díaz 2021}). TMLE is a robust
method that combines machine learning techniques with traditional
statistical models to estimate causal effects while providing valid
statistical uncertainty measures for these estimates.

TMLE operates through a two-step process involving outcome and treatment
(exposure) models. Initially, it employs machine learning algorithms to
flexibly model the relationship between treatments, covariates, and
outcomes. This flexibility allows TMLE to account for complex,
high-dimensional covariate spaces without imposing restrictive model
assumptions. The outcome of this step is a set of initial estimates for
these relationships.

The second step of TMLE involves ``targeting'' these initial estimates
by incorporating information about the observed data distribution to
improve the accuracy of the causal effect estimate. This is achieved
through an iterative updating process, which adjusts the initial
estimates towards the true causal effect. This updating process is
guided by the efficient influence function, ensuring that the final TMLE
estimate is as close as possible to the true causal effect while
remaining robust to model misspecification in either the outcome or
treatment model.

A central feature of TMLE is its double-robustness property, meaning
that if either the model for the treatment or the outcome is correctly
specified, the TMLE estimator will still consistently estimate the
causal effect. Additionally, TMLE uses cross-validation to avoid
overfitting and ensure that the estimator performs well in finite
samples. Each of these steps contributes to a robust methodology for
examining the \emph{causal} effects of interventions on outcomes. The
marriage of TMLE and machine learning technologies reduces the
dependence on restrictive modelling assumptions and introduces an
additional layer of robustness. For further details see
(\citeproc{ref-duxedaz2021}{Díaz \emph{et al.} 2021};
\citeproc{ref-hoffman2022}{Hoffman \emph{et al.} 2022},
\citeproc{ref-hoffman2023}{2023})

\paragraph{Estimation}\label{estimation}

\texttt{lmtp} draws on the the \texttt{SuperLearner} library, which
comprises various machine learning algorithms
(\citeproc{ref-SuperLearner2023}{Polley \emph{et al.} 2023}). Given the
relatively sample (N=1070) we used the \texttt{Ranger} and
\texttt{randomForest} estimators - both causal forest estimators -- a
subset of non-parametric estimators distinguished by their resilience
against overfitting {[}Ranger2017; randomForest2002{]}. Causal forests
excel in identifying complex, non-linear relationships between variables
without presupposing a specific model form and thus making fewer
assumptions about the underlying data distribution.

Importantly, members of relationship pairs were identified using the
\texttt{lmtp} function and by setting \texttt{id\ =}, the character
string used to identify each dyad member.

Graphs, tables and reports were produced using the \texttt{margot}
package (\citeproc{ref-margot2024}{Bulbulia 2024b})

\paragraph{Cross-Validation}\label{cross-validation}

We implemented a 10-fold cross-validation. This method partitions the
data into ten subsets of approximately equal size. During the
cross-validation process, nine subsets are used to train the model, and
the remaining subset is used for testing. This process is repeated ten
times, with each of the ten subsets used exactly once as the test set.
Using different subsets for training and validation minimises the risk
of the model being overly complex and fitting the noise in the training
dataset, which can lead to poor performance on new data. Moreover, each
observation is used for training and validation, which is particularly
beneficial in scenarios where the amount of data is limited. The
cross-validation process results in ten estimates of model accuracy,
which can be averaged to provide a more comprehensive measure of model
performance.

\paragraph{Sensitivity Analysis Using the
E-value}\label{sensitivity-analysis-using-the-e-value}

To measure sensitivity to unmeasured confounding, we report VanderWeele
and Ding's ``E-value'' for all analyses
(\citeproc{ref-vanderweele2017}{VanderWeele and Ding 2017}). The E-value
quantifies the minimum strength of association (on the risk ratio scale)
that an unmeasured confounder would need to have with both the exposure
and the outcome (after considering the measured covariates) to explain
away the observed exposure-outcome association
(\citeproc{ref-linden2020EVALUE}{Linden \emph{et al.} 2020};
\citeproc{ref-vanderweele2020}{VanderWeele \emph{et al.} 2020}). For
example, if the E-value were 1.3, it would mean an unmeasured confounder
associated with both the treatment and outcome by a risk ratio of 1.3
each (or 30\% increase in risk) could explain away the observed effect.
Weaker confounding would not suffice. We also report the bound of the
E-value closest to 1. If the lower bound of the CI were 1.1, to explain
away the result, the strength of an unmeasured confounder in its
association with both the treatment and the outcome would need to be at
least 1.1 on the risk ratio scale (or a 10\% increase in risk) to
explain away the result (\citeproc{ref-vanderweele2017}{VanderWeele and
Ding 2017}).

\subsection{Results}\label{results}

\subsubsection{Data Exploration}\label{data-exploration}

\paragraph{Histogram of Exposure}\label{histogram-of-exposure}

\begin{figure}

\centering{

\includegraphics{24-aaron-dyads-perfectionism-relationship-quality_files/figure-pdf/fig-histogram-1.pdf}

}

\caption{\label{fig-histogram}Histogram of the treatment variable
(possible response scale = 1-7)}

\end{figure}%

Figure~\ref{fig-histogram} presents a histogram of the treatment
variable in the wave following baseline (NZAVS wave 2019). Shift
interventions in this study target the causal effect of either moving
two units up on the perfectionism response scale, or by moving two units
down. Because the scale is bounded by 1 and 7, those within the top of
the scale range (indicated by gold) were exposed to a level of
perfectionism less than two during the gain intervention; likewise,
those within the bottom two units of the scale were exposed to a level
of perfectionism lower than two in the loss intervention.

\subsection{Study 1: Causal Effects of Gains in Perfection on Partner
Relationship
Perceptions}\label{study-1-causal-effects-of-gains-in-perfection-on-partner-relationship-perceptions}

\subsubsection{Imbalance of Confounding Covariates
Treatments}\label{imbalance-of-confounding-covariates-treatments}

Figure~\ref{fig-match_base} shows the imbalance of covariates on the
standard deviation change in the treatment condition at the baseline
wave.

\begin{figure}

\centering{

\includegraphics{24-aaron-dyads-perfectionism-relationship-quality_files/figure-pdf/fig-match_base-1.pdf}

}

\caption{\label{fig-match_base}Figure imbalance of covariates at the
first exposure (baseline) wave}

\end{figure}%

We offer the following evaluation of this imbalance (to follow)

Strong over-representation in high-perfectionism for - both anxiety and
depression features of Kessler 6 anxiety - neuroticism - relationship
conflict

Under-representation in - body satisfaction - conscientiousness - sexual
satisfaction - partner sexual satisfaction

Results would be biased to the extent that these features cause both
perfectionism and the outcomes (partner responses). For this reason, we
must adjust for them.

\paragraph{Transition table}\label{transition-table}

Table~\ref{tbl-transition} presents a transition matrix that captures
state shifts across the treatment intervals. Each cell in the matrix
represents the count of individuals transitioning from one state to
another. The rows correspond to the treatment at baseline (From), and
the columns correspond to the state at the following wave (To).
\textbf{Diagonal entries} (in \textbf{bold}) correspond to the number of
individuals who remained in their initial state across both waves.
\textbf{Off-diagonal entries} correspond to the transitions of
individuals from their baseline state to a different state in the
treatment wave. A higher number on the diagonal relative to the
off-diagonal entries in the same row indicates greater stability in a
state. Conversely, higher off-diagonal numbers suggest more frequent
shifts from the baseline state to other states. Overall the matrix
suggests relatively strong stability and few instances of extreme
shifts.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}@{}}
\caption{Transition matrix for change in treatment from baseline to the
treatment wave (values rounded to nearest whole
number)}\label{tbl-transition}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
From
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
State 7
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
State 1 & \textbf{76} & 48 & 19 & 5 & 0 & 0 & 0 \\
State 2 & 74 & \textbf{193} & 80 & 28 & 5 & 1 & 0 \\
State 3 & 16 & 96 & \textbf{127} & 71 & 19 & 4 & 1 \\
State 4 & 6 & 27 & 84 & \textbf{96} & 51 & 13 & 1 \\
State 5 & 1 & 9 & 16 & 42 & \textbf{48} & 29 & 2 \\
State 6 & 0 & 0 & 3 & 8 & 11 & \textbf{19} & 5 \\
State 7 & 0 & 0 & 0 & 1 & 4 & 6 & \textbf{7} \\
\end{longtable}

\subsubsection{Results Study 1: Effects of Gain in Perfectionism on
Partner Relationship
Attitudes}\label{results-study-1-effects-of-gain-in-perfectionism-on-partner-relationship-attitudes}

Figure~\ref{fig-results-gain} and Table~\ref{tbl-results-gain} present
the results of the study investigating the one year causal effect of a
two point decrease in perfectionism across the stratum of the New
Zealand Population represented in the New Zealand Attitudes and Values
study at the baseline wave (2018-2019)

\begin{figure}

\centering{

\includegraphics{24-aaron-dyads-perfectionism-relationship-quality_files/figure-pdf/fig-results-gain-1.pdf}

}

\caption{\label{fig-results-gain}This figure describes the causal
effects of two-point GAIN of perfection on PARTNER relationship
attitudes at the end of study. Outcomes are z-transformed.}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4096}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1928}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0723}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0843}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0964}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1446}}@{}}

\caption{\label{tbl-results-gain}This table describes the causal effects
of two-point GAIN of perfection on PARTNER relationship attitudes at the
end of study. Outcomes are z-transformed.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
partner relationship satisfaction & -0.04 & -0.10 & 0.01 & 1.24 &
1.00 \\
partner perceived conflict & 0.09 & 0.02 & 0.16 & 1.40 & 1.15 \\
partner sexual satisfaction & -0.07 & -0.13 & -0.01 & 1.33 & 1.12 \\

\end{longtable}

A Longitudinal Modified Treatment Policy (LMTP) calculates the expected
outcome difference between treatment and contrast groups for a specified
population, focusing on longitudinal data.

For `partner perceived conflict', the lmtp effect estimate is 0.092
{[}0.02, 0.164{]}. The E-value for this estimate is 1.395, with a lower
bound of 1.153. At this lower bound, unmeasured confounders would need a
minimum association strength with both the intervention sequence and
outcome of 1.153 to negate the observed effect. Weaker associations
would not overturn it. We infer \textbf{evidence for causality}.

For `partner relationship satisfaction', the lmtp effect estimate is
-0.041 {[}-0.095, 0.013{]}. The E-value for this estimate is 1.237, with
a lower bound of 1. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1 to negate the observed effect. Weaker associations
would not overturn it. We infer \textbf{that evidence for causality is
not reliable}.

For `partner sexual satisfaction', the lmtp effect estimate is -0.069
{[}-0.126, -0.011{]}. The E-value for this estimate is 1.327, with a
lower bound of 1.118. At this lower bound, unmeasured confounders would
need a minimum association strength with both the intervention sequence
and outcome of 1.118 to negate the observed effect. Weaker associations
would not overturn it. We infer \textbf{evidence for causality}.

\newpage{}

\subsubsection{Results Study 2: Effects of Loss in Perfectionism on
Partner Relationship
Attitudes}\label{results-study-2-effects-of-loss-in-perfectionism-on-partner-relationship-attitudes}

Figure~\ref{fig-results-loss} and Table~\ref{tbl-results-loss} present
the results of the study investigating the one year causal effect of a
two point decrease in perfectionism across the stratum of the New
Zealand Population represented in the New Zealand Attitudes and Values
study at the baseline wave (2018-2019)

\begin{figure}

\centering{

\includegraphics{24-aaron-dyads-perfectionism-relationship-quality_files/figure-pdf/fig-results-loss-1.pdf}

}

\caption{\label{fig-results-loss}This figure describes the causal
effects of two-point LOSS of perfection on PARTNER relationship
attitudes at the end of study. Outcomes are z-transformed.}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4096}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1928}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0723}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0843}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0964}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1446}}@{}}

\caption{\label{tbl-results-loss}This table describes the causal effects
of a two-point loss of perfection on partner relationship attitudes at
the end of the study. Outcomes are z-transformed.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E{[}Y(1){]}-E{[}Y(0){]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
97.5 \%
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
E\_Val\_bound
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
partner relationship satisfaction & 0.01 & -0.05 & 0.08 & 1.13 & 1.00 \\
partner perceived conflict & -0.04 & -0.12 & 0.04 & 1.23 & 1.00 \\
partner sexual satisfaction & 0.15 & 0.07 & 0.23 & 1.55 & 1.32 \\

\end{longtable}

For `partner sexual satisfaction', the effect estimate is 0.147
{[}0.067, 0.226{]}. The E-value for this estimate is 1.548, with a lower
bound of 1.321. At this lower bound, unmeasured confounders would need a
minimum association strength with both the intervention sequence and
outcome of 1.321 to negate the observed effect. Weaker associations
would not overturn it. We infer \textbf{evidence for causality}.

The effect estimate for `partner relationship satisfaction' is 0.015
{[}-0.052, 0.081{]}. The E-value for this estimate is 1.132, with a
lower bound of 1. At this lower bound, unmeasured confounders would need
a minimum association strength with both the intervention sequence and
outcome of 1 to negate the observed effect. Weaker associations would
not overturn it. We infer \textbf{that evidence for causality is not
reliable}.

The effect estimate for `partner perceived conflict' is -0.04 {[}-0.121,
0.04{]}. The E-value for this estimate is 1.233, with a lower bound of
1. At this lower bound, unmeasured confounders would need a minimum
association strength with both the intervention sequence and outcome of
1 to negate the observed effect. Weaker associations would not overturn
it. We infer \textbf{that evidence for causality is not reliable}.

\subsection{Discussion}\label{discussion}

\subsubsection{Perfectionism GAIN}\label{perfectionism-gain}

\textbf{Partner perceived conflict}: a two-point ``gain'' in
perfectionism is expected to yield a slight increase in average partner
perceived conflict (b = 0.092 {[}0.02, 0.164{]}). The corresponding
E-value of 1.395 suggests that any unmeasured confounder would need a
minimum association strength of at least 1.395 (or 1.153 at the interval
closest to 1) to invalidate the observed result. This suggests modest
robustness to potential unmeasured confounding supporting a causal
relationship.

\textbf{Partner Sexual Satisfaction}: a two-point ``gain'' in
perfectionism is expected to yield reduced partner sexual satisfaction,
with an effect estimate of b = -0.069 {[}-0.126, -0.011{]}. The
robustness of this finding is indicated by an E-value of 1.327,
indicating that unmeasured confounders would require a relatively strong
association with both the intervention sequence and outcome to negate
the observed causal effect.

\textbf{Partner Relationship Satisfaction}: no evidence for a reliable
effect from this shift intervention.

\subsubsection{Loss of Perfectionism}\label{loss-of-perfectionism}

\textbf{Partner Sexual Satisfaction:} The LMTP effect estimate for a
two-point decrease in perfectionism on partner sexual satisfaction is
the \textbf{most robust} result we observed in this study -- with an
estimate of b = 0.147 {[}0.067, 0.226{]}. The robustness of this finding
is supported by an E-value of 1.548, indicating that a substantial
strength of association by unmeasured confounders would be required to
negate the observed causal effect. This suggests that interventions
leading to reduced perfectionism can benefit aspects of intimate
relationships.

Our analysis of \textbf{Partner Relationship Satisfaction} and
\textbf{Partner Perceived Conflict} does offer evidence that a loss of
perfectionism makes a reliable difference, on average, to these
parameters.

\paragraph{Strengths of Study}\label{strengths-of-study}

\begin{itemize}
\tightlist
\item
  Time-series data with which to evaluate causal effects
\item
  Clearly defined causal questions with appropriate causal control.
\item
  Unrestrictive modelling assumptions (i.e.~about functional form.)
\item
  \ldots{}
\end{itemize}

\paragraph{Future directions}\label{future-directions}

\begin{itemize}
\tightlist
\item
  Time in relationships -- habituation? etc\ldots{}
\item
  Gender differences and heterogeneity
\item
  The shift we assess here -- two units down -- is a strong
  intervention. This helps us to evaluate a theoretical question
  comparable to an experiment. However, whether the insights we obtain
  here have practical applications relies on whether interventions can
  shift people up or down by two points on the perfectionism scale.
\item
  Results might not generalise to other countries\ldots{}
\end{itemize}

\subsubsection{Ethics}\label{ethics}

The University of Auckland Human Participants Ethics Committee reviews
the NZAVS every three years. Our most recent ethics approval statement
is as follows: The New Zealand Attitudes and Values Study was approved
by the University of Auckland Human Participants Ethics Committee on
26/05/2021 for six years until 26/05/2027, Reference Number UAHPEC22576.

\subsubsection{Acknowledgements}\label{acknowledgements}

The New Zealand Attitudes and Values Study is supported by a grant from
the Templeton Religious Trust (TRT0196; TRT0418). JB received support
from the Max Planck Institute for the Science of Human History. The
funders had no role in preparing the manuscript or deciding to publish
it.

\subsubsection{Author Statement}\label{author-statement}

\begin{itemize}
\tightlist
\item
  AM, KR, DD, HW conceived of the study.
\item
  JB conceived of an analytic approach and did the analysis.
\item
  CS led NZAVS data collection.
\item
  All authors contributed to the manuscript.
\end{itemize}

\newpage{}

\subsection{Appendix A: Measures}\label{appendix-measures}

\paragraph{Age (waves: 1-15)}\label{age-waves-1-15}

We asked participants' ages in an open-ended question (``What is your
age?'' or ``What is your date of birth'').

--\textgreater{}

--\textgreater{}

\paragraph{Body Satisfaction}\label{body-satisfaction}

We measured body satisfaction with one item from Stronge \emph{et al.}
(\citeproc{ref-stronge_facebook_2015}{2015}): ``I am satisfied with the
appearance, size and shape of my body'', which participants rated from 1
(very inaccurate) to 7 (very accurate).

\paragraph{Education Attainment (waves: 1,
4-15)}\label{education-attainment-waves-1-4-15}

We asked participants, ``What is your highest level of qualification?''.
We coded participants' highest finished degree according to the New
Zealand Qualifications Authority. Ordinal-Rank 0-10 NZREG codes (with
overseas school quals coded as Level 3, and all other ancillary
categories coded as missing)
See:https://www.nzqa.govt.nz/assets/Studying-in-NZ/New-Zealand-Qualification-Framework/requirements-nzqf.pdf

\paragraph{Employment (waves: 1-3,
4-11)}\label{employment-waves-1-3-4-11}

We asked participants, ``Are you currently employed? (This includes
self-employed or casual work)''. * note: This question disappeared in
the updated NZAVS Technical documents (Data Dictionary).

\paragraph{Ethnicity}\label{ethnicity}

Based on the New Zealand Census, we asked participants, ``Which ethnic
group(s) do you belong to?''. The responses were: (1) New Zealand
European; (2) Māori; (3) Samoan; (4) Cook Island Māori; (5) Tongan; (6)
Niuean; (7) Chinese; (8) Indian; (9) Other such as DUTCH, JAPANESE,
TOKELAUAN. Please state:. We coded their answers into four groups:
Maori, Pacific, Asian, and Euro (except for Time 3, which used an
open-ended measure).

\paragraph{Gender (waves: 1-15)}\label{gender-waves-1-15}

We asked participants' gender in an open-ended question: ``what is your
gender?'' or ``Are you male or female?'' (waves: 1-5). Female was coded
as 0, Male was coded as 1, and gender diverse coded as 3
(\citeproc{ref-fraser_coding_2020}{Fraser \emph{et al.} 2020}). (or 0.5
= neither female nor male)

Here, we coded all those who responded as Male as 1, and those who did
not as 0.

\paragraph{Honesty-Humility-Modesty Facet (waves:
10-14)}\label{honesty-humility-modesty-facet-waves-10-14}

Participants indicated the extent to which they agree with the following
four statements from Campbell \emph{et al.}
(\citeproc{ref-campbell2004}{2004}) , and Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}) (1 = Strongly Disagree to 7 = Strongly
Agree)

\begin{verbatim}
i.  I want people to know that I am an important person of high status, (Waves: 1, 10-14)
ii. I am an ordinary person who is no better than others.
iii. I wouldn't want people to treat me as though I were superior to them.
iv. I think that I am entitled to more respect than the average person is.
\end{verbatim}

\paragraph{Has Siblings}\label{has-siblings}

``Do you have siblings?'' (\citeproc{ref-stronge2019onlychild}{Stronge
\emph{et al.} 2019})

\paragraph{Hours of Childcare}\label{hours-of-childcare}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Childcare}\label{hours-of-childcare-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): 'Hours spent \ldots{} looking after
children.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Exercise}\label{hours-of-exercise-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
exercising/physical activity''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Housework}\label{hours-of-housework-1}

We measured hours of exercising using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}): ``Hours spent \ldots{}
housework/cooking''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Hours of Sleep}\label{hours-of-sleep}

Participants were asked ``During the past month, on average, how many
hours of \emph{actual sleep} did you get per night''.

\paragraph{Socialising (time 10, time
11)}\label{socialising-time-10-time-11}

As part of the time usage measures, participants were asked to state how
many hour the spent in activities related to socialising with the
following groups:

\begin{itemize}
\tightlist
\item
  Hours spent \ldots{} socialising with family
\item
  Hours spent \ldots{} socialising with friends
\item
  Hours spent \ldots{} socialising with community groups
\end{itemize}

\paragraph{Hours of Work}\label{hours-of-work}

We measured hours of work using one item from Sibley \emph{et al.}
(\citeproc{ref-sibley2011}{2011}):``Hours spent \ldots{} working in paid
employment.''

To stabilise this indicator, we took the natural log of the response +
1.

\paragraph{Income (waves: 1-3, 4-15)}\label{income-waves-1-3-4-15}

Participants were asked ``Please estimate your total household income
(before tax) for the year XXXX''. To stabilise this indicator, we first
took the natural log of the response + 1, and then centred and
standardised the log-transformed indicator.

\paragraph{Living in an Urban Area (waves:
1-15)}\label{living-in-an-urban-area-waves-1-15}

We coded whether they are living in an urban or rural area (1 = Urban, 0
= Rural) based on the addresses provided.

We coded whether they were living in an urban or rural area (1 = Urban,
0 = Rural) based on the addresses provided.

\paragraph{Mini-IPIP 6 (waves:
1-3,4-15)}\label{mini-ipip-6-waves-1-34-15}

We measured participants' personalities with the Mini International
Personality Item Pool 6 (Mini-IPIP6) (\citeproc{ref-sibley2011}{Sibley
\emph{et al.} 2011}), which consists of six dimensions and each
dimension is measured with four items:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  agreeableness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I sympathize with others' feelings.
  \item
    I am not interested in other people's problems. (r)
  \item
    I feel others' emotions.
  \item
    I am not really interested in others. (r)
  \end{enumerate}
\item
  conscientiousness,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I get chores done right away.
  \item
    I like order.
  \item
    I make a mess of things. (r)
  \item
    I often forget to put things back in their proper place. (r)
  \end{enumerate}
\item
  extraversion,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I am the life of the party.
  \item
    I don't talk a lot. (r)
  \item
    I keep in the background. (r)
  \item
    I talk to a lot of different people at parties.
  \end{enumerate}
\item
  honesty-humility,

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I feel entitled to more of everything. (r)
  \item
    I deserve more things in life. (r)
  \item
    I would like to be seen driving around in a very expensive car. (r)
  \item
    I would get a lot of pleasure from owning expensive luxury goods.
    (r)
  \end{enumerate}
\item
  neuroticism, and

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have frequent mood swings.
  \item
    I am relaxed most of the time. (r)
  \item
    I get upset easily.
  \item
    I seldom feel blue. (r)
  \end{enumerate}
\item
  openness to experience

  \begin{enumerate}
  \def\labelenumii{\roman{enumii}.}
  \tightlist
  \item
    I have a vivid imagination.
  \item
    I have difficulty understanding abstract ideas. (r)
  \item
    I do not have a good imagination. (r)
  \item
    I am not interested in abstract ideas. (r)
  \end{enumerate}
\end{enumerate}

Each dimension was assessed with four items and participants rated the
accuracy of each item as it applies to them from 1 (Very Inaccurate) to
7 (Very Accurate). Items marked with (r) are reverse coded.

\paragraph{NZ-Born (waves: 1-2,4-15)}\label{nz-born-waves-1-24-15}

We asked participants, ``Which country were you born in?'' or ``Where
were you born? (please be specific, e.g., which town/city?)'' (waves:
6-15).

\paragraph{NZ Deprivation Index (waves:
1-15)}\label{nz-deprivation-index-waves-1-15}

We used the NZ Deprivation Index to assign each participant a score
based on where they live (\citeproc{ref-atkinson2019}{Atkinson \emph{et
al.} 2019}). This score combines data such as income, home ownership,
employment, qualifications, family structure, housing, and access to
transport and communication for an area into one deprivation score.

\paragraph{Opt-in}\label{opt-in}

The New Zealand Attitudes and Values Study allows opt-ins to the study.
Because the opt-in population may differ from those sampled randomly
from the New Zealand electoral roll; although the opt-in rate is low, we
include an indicator (yes/no) for this variable.

\paragraph{NZSEI Occupational Prestige and Status (waves:
8-15)}\label{nzsei-occupational-prestige-and-status-waves-8-15}

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017a}{Fahy
\emph{et al.} 2017a}). This index uses the income, age, and education of
a reference group, in this case the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

We assessed occupational prestige and status using the New Zealand
Socio-economic Index 13 (NZSEI-13) (\citeproc{ref-fahy2017}{Fahy
\emph{et al.} 2017b}). This index uses the income, age, and education of
a reference group, in this case, the 2013 New Zealand census, to
calculate a score for each occupational group. Scores range from 10
(Lowest) to 90 (Highest). This list of index scores for occupational
groups was used to assign each participant a NZSEI-13 score based on
their occupation.

\paragraph{Number of Children (waves: 1-3,
4-15)}\label{number-of-children-waves-1-3-4-15}

We measured the number of children using one item from Bulbulia
(\citeproc{ref-Bulbulia_2015}{2015}). We asked participants, ``How many
children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, or adopted?'' or ````How
many children have you given birth to, fathered, or adopted. How many
children have you given birth to, fathered, and/or parented?'' (waves:
12-15).

\paragraph{Perfectionism}\label{perfectionism}

We assessed participants' perfectionism using three items from Rice
\emph{et al.} (\citeproc{ref-rice_short_2014}{2014}): (1) Doing my best
never seems to be enough; (2) My performance rarely measures up to my
standards; (3) I am hardly ever satisfied with my performance.
Participants indicated the extent to which they agree with these items
(1 = Strongly Disagree to 7 = Strongly Agree).

\paragraph{Politically Conservative}\label{politically-conservative}

We measured participants' political conservative orientation using a
single item adapted from Jost (\citeproc{ref-jost_end_2006-1}{2006}).

``Please rate how politically liberal versus conservative you see
yourself as being.''

(1 = Extremely Liberal to 7 = Extremely Conservative)

\paragraph{Religion: Frequency of Religious Service
Attendance}\label{religion-frequency-of-religious-service-attendance}

If participants answered \emph{yes} to ``Do you identify with a religion
and/or spiritual group?'' we measured their frequency of church
attendence using one item from Sibley (\citeproc{ref-sibley2012}{2012}):
``how many times did you attend a church or place of worship in the last
month?''. Those participants who were not religious were imputed a score
of ``0''. Here we used a binary indicator of religious service where 1 =
``yes''.

\paragraph{Sample Opt-in}\label{sample-opt-in}

The New Zealand Attitudes and Values Study allows opt-ins to the study.
Because the opt-in population may differ from those sampled randomly
from the New Zealand electoral roll; although the opt-in rate is low, we
include an indicator (yes/no) for this variable.

\paragraph{Sample Origin}\label{sample-origin}

NZAVS wave participant joined.

\subsection{Appendix B. Baseline Demographic
Statistics}\label{appendix-demographics}

\begin{table}

\caption{\label{tbl-B}}

\centering{

\captionsetup{labelsep=none}

}

\end{table}%

\begin{longtable}[]{@{}ll@{}}
\caption{Baseline demographic
statistics}\label{tbl-table-demography}\tabularnewline
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 1,860} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\textbf{Exposure + Demographic Variables} & \textbf{N = 1,860} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Age} & NA \\
Mean (SD) & 51 (12) \\
Range & 19, 90 \\
IQR & 42, 60 \\
\textbf{Agreeableness} & NA \\
Mean (SD) & 5.27 (1.03) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.00 \\
Unknown & 9 \\
\textbf{Bodysat} & NA \\
1 & 105 (5.7\%) \\
2 & 175 (9.5\%) \\
3 & 312 (17\%) \\
4 & 307 (17\%) \\
5 & 360 (20\%) \\
6 & 448 (24\%) \\
7 & 135 (7.3\%) \\
Unknown & 18 \\
\textbf{Born Nz} & 1,415 (77\%) \\
Unknown & 15 \\
\textbf{Children Num} & NA \\
0 & 414 (22\%) \\
1 & 164 (8.9\%) \\
2 & 729 (39\%) \\
3 & 366 (20\%) \\
4 & 120 (6.5\%) \\
5 & 37 (2.0\%) \\
6 & 12 (0.6\%) \\
7 & 3 (0.2\%) \\
8 & 3 (0.2\%) \\
Unknown & 12 \\
\textbf{Conscientiousness} & NA \\
Mean (SD) & 5.12 (1.03) \\
Range & 1.00, 7.00 \\
IQR & 4.50, 6.00 \\
Unknown & 9 \\
\textbf{Education Level Coarsen} & NA \\
no\_qualification & 24 (1.3\%) \\
cert\_1\_to\_4 & 574 (32\%) \\
cert\_5\_to\_6 & 223 (12\%) \\
university & 513 (28\%) \\
post\_grad & 232 (13\%) \\
masters & 189 (10\%) \\
doctorate & 62 (3.4\%) \\
Unknown & 43 \\
\textbf{Employed} & 1,540 (83\%) \\
Unknown & 3 \\
\textbf{Eth Cat} & NA \\
euro & 1,549 (84\%) \\
maori & 165 (9.0\%) \\
pacific & 36 (2.0\%) \\
asian & 86 (4.7\%) \\
Unknown & 24 \\
\textbf{Extraversion} & NA \\
Mean (SD) & 3.87 (1.19) \\
Range & 1.00, 7.00 \\
IQR & 3.00, 4.75 \\
Unknown & 9 \\
\textbf{Has Siblings} & 1,736 (95\%) \\
Unknown & 39 \\
\textbf{Hlth Disability} & 350 (19\%) \\
Unknown & 39 \\
\textbf{Honesty Humility} & NA \\
Mean (SD) & 5.45 (1.16) \\
Range & 1.00, 7.00 \\
IQR & 4.75, 6.25 \\
Unknown & 9 \\
\textbf{Hours Children log} & NA \\
Mean (SD) & 1.18 (1.58) \\
Range & 0.00, 5.13 \\
IQR & 0.00, 2.40 \\
Unknown & 52 \\
\textbf{Hours Exercise log} & NA \\
Mean (SD) & 1.56 (0.83) \\
Range & 0.00, 4.39 \\
IQR & 1.10, 2.08 \\
Unknown & 52 \\
\textbf{Hours Housework log} & NA \\
Mean (SD) & 2.12 (0.76) \\
Range & 0.00, 4.72 \\
IQR & 1.61, 2.71 \\
Unknown & 52 \\
\textbf{Hours Work log} & NA \\
Mean (SD) & 2.81 (1.51) \\
Range & 0.00, 4.39 \\
IQR & 2.40, 3.83 \\
Unknown & 52 \\
\textbf{Household Inc log} & NA \\
Mean (SD) & 11.63 (0.65) \\
Range & 9.21, 13.59 \\
IQR & 11.24, 12.07 \\
Unknown & 45 \\
\textbf{Kessler Latent Anxiety} & NA \\
Mean (SD) & 1.15 (0.74) \\
Range & 0.00, 4.00 \\
IQR & 0.67, 1.67 \\
Unknown & 11 \\
\textbf{Kessler Latent Depression} & NA \\
Mean (SD) & 0.49 (0.68) \\
Range & 0.00, 4.00 \\
IQR & 0.00, 0.67 \\
Unknown & 11 \\
\textbf{Male} & 904 (49\%) \\
\textbf{Modesty} & NA \\
Mean (SD) & 6.01 (0.94) \\
Range & 1.00, 7.00 \\
IQR & 5.50, 6.75 \\
\textbf{Neuroticism} & NA \\
Mean (SD) & 3.39 (1.15) \\
Range & 1.00, 7.00 \\
IQR & 2.50, 4.25 \\
Unknown & 9 \\
\textbf{Nz Dep2018} & NA \\
Mean (SD) & 4.48 (2.60) \\
Range & 1.00, 10.00 \\
IQR & 2.00, 6.00 \\
Unknown & 2 \\
\textbf{Nzsei 13 l} & NA \\
Mean (SD) & 56 (16) \\
Range & 10, 90 \\
IQR & 44, 69 \\
Unknown & 14 \\
\textbf{Openness} & NA \\
Mean (SD) & 5.00 (1.13) \\
Range & 1.50, 7.00 \\
IQR & 4.25, 6.00 \\
Unknown & 9 \\
\textbf{Parent} & 1,434 (78\%) \\
Unknown & 12 \\
\textbf{Perfectionism} & NA \\
Mean (SD) & 3.09 (1.33) \\
Range & 1.00, 7.00 \\
IQR & 2.00, 4.00 \\
\textbf{Political Conservative} & NA \\
1 & 105 (6.0\%) \\
2 & 384 (22\%) \\
3 & 379 (21\%) \\
4 & 468 (27\%) \\
5 & 270 (15\%) \\
6 & 125 (7.1\%) \\
7 & 32 (1.8\%) \\
Unknown & 97 \\
\textbf{Religion Church Binary} & 302 (17\%) \\
Unknown & 51 \\
\textbf{Rural Gch 2018 l} & NA \\
1 & 1,147 (62\%) \\
2 & 368 (20\%) \\
3 & 244 (13\%) \\
4 & 82 (4.4\%) \\
5 & 17 (0.9\%) \\
Unknown & 2 \\
\textbf{Sample Frame Opt in} & 99 (5.3\%) \\
\textbf{Sample Origin} & NA \\
1-2 & 71 (3.8\%) \\
3-3.5 & 111 (6.0\%) \\
4 & 77 (4.1\%) \\
5-6-7 & 190 (10\%) \\
8-9 & 218 (12\%) \\
10 & 1,193 (64\%) \\
\end{longtable}

Table~\ref{tbl-table-demography} presents baseline demographic
statistics for couples who met inclusion criteria.

\subsection{Appendix C: Treatment Statistics}\label{appendix-exposures}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4366}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2817}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2817}}@{}}
\caption{Baseline and treatment wave descriptive
statistics}\label{tbl-table-exposures}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,860
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 1,860
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Exposure Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,860
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2019}, N = 1,860
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Perfectionism} & 3.00 (2.00, 4.00) & 3.00 (2.00, 4.00) \\
Unknown & 0 & 508 \\
\textbf{Alert Level Combined} & NA & NA \\
no\_alert & 1,860 (100\%) & 1,027 (76\%) \\
early\_covid & 0 (0\%) & 123 (9.1\%) \\
alert\_level\_1 & 0 (0\%) & 100 (7.4\%) \\
alert\_level\_2 & 0 (0\%) & 32 (2.4\%) \\
alert\_level\_2\_5\_3 & 0 (0\%) & 21 (1.6\%) \\
alert\_level\_4 & 0 (0\%) & 49 (3.6\%) \\
Unknown & 0 & 508 \\
\end{longtable}

Table~\ref{tbl-table-exposures} presents baseline (NZAVS time 10) and
exposure wave (NZAVS time 11) statistics for the exposure variable:
perfectionism (range 1-7). Because the treatment wave (NZAVS time 11)
occurred in New Zealand's COVID-19 pandemic, all models adjusted for the
pandemic alert-level. The pandemic is not a ``confounder'' because a
confounder must be related to the treatment and the outcome. At the end
of the study, all participants had been exposed to the pandemic.
However, to satisfy the causal consistency assumption, all treatments
must be conditionally equivalent within levels of all covariates
(\citeproc{ref-vanderweele2013}{VanderWeele and Hernan 2013}). Because
COVID affected the ability or willingness of individuals to attend
religious service, we included the lockdown condition as a covariate
(\citeproc{ref-sibley2012a}{Sibley and Bulbulia 2012}). To better enable
conditional independence within levels of the treatment variable, we
conditioned on the value of COVID-alert level at the second wave. To
mitigate systematic biases arising from attrition and missingness, the
\texttt{lmtp} package uses inverse probability of censoring weights,
which were used when estimating the causal effects of the exposure on
the outcome.

\subsection{Appendix D: Baseline and End of Study Outcome
Statistics}\label{appendix-outcomes}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4286}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2857}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2857}}@{}}
\caption{Outcomes measured at baseline and
end-of-study}\label{tbl-table-outcomes}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,860
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 1,860
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{Outcome Variables by Wave}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2018}, N = 1,860
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
\textbf{2020}, N = 1,860
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Conflict in Relationship} & NA & NA \\
1 & 169 (9.8\%) & 128 (9.4\%) \\
2 & 800 (46\%) & 611 (45\%) \\
3 & 272 (16\%) & 219 (16\%) \\
4 & 232 (13\%) & 186 (14\%) \\
5 & 158 (9.1\%) & 167 (12\%) \\
6 & 76 (4.4\%) & 45 (3.3\%) \\
7 & 21 (1.2\%) & 7 (0.5\%) \\
Unknown & 132 & 497 \\
\textbf{Sat Relationship} & NA & NA \\
1 & 8 (0.5\%) & 4 (0.3\%) \\
2 & 17 (1.0\%) & 14 (1.0\%) \\
3 & 34 (2.0\%) & 33 (2.4\%) \\
4 & 66 (3.8\%) & 52 (3.8\%) \\
5 & 176 (10\%) & 155 (11\%) \\
6 & 603 (35\%) & 498 (37\%) \\
7 & 829 (48\%) & 605 (44\%) \\
Unknown & 127 & 499 \\
\textbf{Sexual Satisfaction} & NA & NA \\
1 & 88 (5.1\%) & 84 (6.1\%) \\
2 & 140 (8.1\%) & 119 (8.6\%) \\
3 & 137 (7.9\%) & 129 (9.4\%) \\
4 & 297 (17\%) & 257 (19\%) \\
5 & 342 (20\%) & 318 (23\%) \\
6 & 455 (26\%) & 299 (22\%) \\
7 & 273 (16\%) & 172 (12\%) \\
Unknown & 128 & 482 \\
\end{longtable}

Table~\ref{tbl-table-outcomes} presents baseline and end-of-study
descriptive statistics for the outcome variables.

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-atkinson2019}
Atkinson, J, Salmond, C, and Crampton, P (2019) \emph{NZDep2018 index of
deprivation, user{'}s manual.}, Wellington.

\bibitem[\citeproctext]{ref-bulbulia2024PRACTICAL}
Bulbulia, J (2024a) A practical guide to causal inference in three-wave
panel studies. \emph{PsyArXiv Preprints}.
doi:\href{https://doi.org/10.31234/osf.io/uyg3d}{10.31234/osf.io/uyg3d}.

\bibitem[\citeproctext]{ref-margot2024}
Bulbulia, JA (2024b) \emph{Margot: MARGinal observational
treatment-effects}.
doi:\href{https://doi.org/10.5281/zenodo.10907724}{10.5281/zenodo.10907724}.

\bibitem[\citeproctext]{ref-Bulbulia_2015}
Bulbulia, S, J. A. (2015) Religion and parental cooperation: An
empirical test of slone's sexual signaling model. In \&. V. S. J. Slone
D., ed., \emph{The attraction of religion: A sexual selectionist
account}, Bloomsbury Press, 29--62.

\bibitem[\citeproctext]{ref-campbell2004}
Campbell, WK, Bonacci, AM, Shelton, J, Exline, JJ, and Bushman, BJ
(2004) Psychological entitlement: interpersonal consequences and
validation of a self-report measure. \emph{Journal of Personality
Assessment}, \textbf{83}(1), 29--45.
doi:\href{https://doi.org/10.1207/s15327752jpa8301_04}{10.1207/s15327752jpa8301\_04}.

\bibitem[\citeproctext]{ref-duxedaz2021}
Díaz, I, Williams, N, Hoffman, KL, and Schenck, EJ (2021) Non-parametric
causal effects based on longitudinal modified treatment policies.
\emph{Journal of the American Statistical Association}.
doi:\href{https://doi.org/10.1080/01621459.2021.1955691}{10.1080/01621459.2021.1955691}.

\bibitem[\citeproctext]{ref-fahy2017}
Fahy, KM, Lee, A, and Milne, BJ (2017b) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fahy2017a}
Fahy, KM, Lee, A, and Milne, BJ (2017a) \emph{New Zealand socio-economic
index 2013}, Wellington, New Zealand: Statistics New Zealand-Tatauranga
Aotearoa.

\bibitem[\citeproctext]{ref-fraser_coding_2020}
Fraser, G, Bulbulia, J, Greaves, LM, Wilson, MS, and Sibley, CG (2020)
Coding responses to an open-ended gender measure in a new zealand
national sample. \emph{The Journal of Sex Research}, \textbf{57}(8),
979--986.
doi:\href{https://doi.org/10.1080/00224499.2019.1687640}{10.1080/00224499.2019.1687640}.

\bibitem[\citeproctext]{ref-hoffman2023}
Hoffman, KL, Salazar-Barreto, D, Rudolph, KE, and Díaz, I (2023)
Introducing longitudinal modified treatment policies: A unified
framework for studying complex exposures.
doi:\href{https://doi.org/10.48550/arXiv.2304.09460}{10.48550/arXiv.2304.09460}.

\bibitem[\citeproctext]{ref-hoffman2022}
Hoffman, KL, Schenck, EJ, Satlin, MJ, \ldots{} Díaz, I (2022) Comparison
of a target trial emulation framework vs cox regression to estimate the
association of corticosteroids with COVID-19 mortality. \emph{JAMA
Network Open}, \textbf{5}(10), e2234425.
doi:\href{https://doi.org/10.1001/jamanetworkopen.2022.34425}{10.1001/jamanetworkopen.2022.34425}.

\bibitem[\citeproctext]{ref-jost_end_2006-1}
Jost, JT (2006) The end of the end of ideology. \emph{American
Psychologist}, \textbf{61}(7), 651--670.
doi:\href{https://doi.org/10.1037/0003-066X.61.7.651}{10.1037/0003-066X.61.7.651}.

\bibitem[\citeproctext]{ref-linden2020EVALUE}
Linden, A, Mathur, MB, and VanderWeele, TJ (2020) Conducting sensitivity
analysis for unmeasured confounding in observational studies using
e-values: The evalue package. \emph{The Stata Journal}, \textbf{20}(1),
162--175.

\bibitem[\citeproctext]{ref-SuperLearner2023}
Polley, E, LeDell, E, Kennedy, C, and van der Laan, M (2023)
\emph{SuperLearner: Super learner prediction}. Retrieved from
\url{https://github.com/ecpolley/SuperLearner}

\bibitem[\citeproctext]{ref-rice_short_2014}
Rice, KG, Richardson, CME, and Tueller, S (2014) The short form of the
revised almost perfect scale. \emph{Journal of Personality Assessment},
\textbf{96}(3), 368--379.
doi:\href{https://doi.org/10.1080/00223891.2013.838172}{10.1080/00223891.2013.838172}.

\bibitem[\citeproctext]{ref-sibley2012}
Sibley, \&B, C. G. (2012) Healing those who need healing: How religious
practice affects social belonging. \emph{Journal for the Cognitive
Science of Religion}, \textbf{1}, 29--45.

\bibitem[\citeproctext]{ref-sibley2012a}
Sibley, CG, and Bulbulia, J (2012) Faith after an earthquake: A
longitudinal study of religion and perceived health before and after the
2011 christchurch new zealand earthquake. \emph{PloS One},
\textbf{7}(12), e49648.

\bibitem[\citeproctext]{ref-sibley2011}
Sibley, CG, Luyten, N, Purnomo, M, \ldots{} Robertson, A (2011) The
Mini-IPIP6: Validation and extension of a short measure of the Big-Six
factors of personality in New Zealand. \emph{New Zealand Journal of
Psychology}, \textbf{40}(3), 142--159.

\bibitem[\citeproctext]{ref-stronge_facebook_2015}
Stronge, S, Greaves, LM, Milojev, P, West-Newman, T, Barlow, FK, and
Sibley, CG (2015) Facebook is linked to body dissatisfaction: Comparing
users and non-users. \emph{Sex Roles: A Journal of Research},
\textbf{73}(5), 200--213.
doi:\href{https://doi.org/10.1007/s11199-015-0517-6}{10.1007/s11199-015-0517-6}.

\bibitem[\citeproctext]{ref-stronge2019onlychild}
Stronge, S, Shaver, JH, Bulbulia, J, and Sibley, CG (2019) Only children
in the 21st century: Personality differences between adults with and
without siblings are very, very small. \emph{Journal of Research in
Personality}, \textbf{83}, 103868.

\bibitem[\citeproctext]{ref-vanbuuren2018}
Van Buuren, S (2018) \emph{Flexible imputation of missing data}, CRC
press.

\bibitem[\citeproctext]{ref-vanderlaan2011}
Van Der Laan, MJ, and Rose, S (2011) \emph{Targeted Learning: Causal
Inference for Observational and Experimental Data}, New York, NY:
Springer. Retrieved from
\url{https://link.springer.com/10.1007/978-1-4419-9782-1}

\bibitem[\citeproctext]{ref-vanderlaan2018}
Van Der Laan, MJ, and Rose, S (2018) \emph{Targeted Learning in Data
Science: Causal Inference for Complex Longitudinal Studies}, Cham:
Springer International Publishing. Retrieved from
\url{http://link.springer.com/10.1007/978-3-319-65304-4}

\bibitem[\citeproctext]{ref-vanderweele2017}
VanderWeele, TJ, and Ding, P (2017) Sensitivity analysis in
observational research: Introducing the e-value. \emph{Annals of
Internal Medicine}, \textbf{167}(4), 268--274.
doi:\href{https://doi.org/10.7326/M16-2607}{10.7326/M16-2607}.

\bibitem[\citeproctext]{ref-vanderweele2013}
VanderWeele, TJ, and Hernan, MA (2013) Causal inference under multiple
versions of treatment. \emph{Journal of Causal Inference},
\textbf{1}(1), 120.

\bibitem[\citeproctext]{ref-vanderweele2020}
VanderWeele, TJ, Mathur, MB, and Chen, Y (2020) Outcome-wide
longitudinal designs for causal inference: A new template for empirical
studies. \emph{Statistical Science}, \textbf{35}(3), 437466.

\bibitem[\citeproctext]{ref-williams2021}
Williams, NT, and Díaz, I (2021) \emph{Lmtp: Non-parametric causal
effects of feasible interventions based on modified treatment policies}.
doi:\href{https://doi.org/10.5281/zenodo.3874931}{10.5281/zenodo.3874931}.

\end{CSLReferences}



\end{document}
