---
title: 'Supplementary files for "Methods in Causal Inference Part 2: Interaction, Mediation, and Time-Varying Treatments"'
author: 
  - name: Joseph A. Bulbulia
    affiliation: Victoria University of Wellington, New Zealand
    orcid: 0000-0002-5861-2056
    email: joseph.bulbulia@vuw.ac.nz
    corresponding: no
editor_options: 
  chunk_output_type: console
format:
  pdf:
    sanitise: true
    keep-tex: true
    link-citations: true
    colorlinks: true
    documentclass: article
    classoption: [single column]
    lof: false
    lot: true
    toc: true
    toc-depth: 2
    geometry:
      - top=30mm
      - left=25mm
      - heightrounded
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
    template-partials: 
      - /Users/joseph/GIT/templates/quarto/title.tex
    header-includes:
      - \input{/Users/joseph/GIT/latex/latex-for-quarto.tex}
date: last-modified
execute:
  echo: false
  warning: false
  include: true
  eval: true
fontfamily: libertinus
bibliography: /Users/joseph/GIT/templates/bib/references.bib
csl: /Users/joseph/GIT/templates/csl/camb-a.csl
---


{{< pagebreak >}}
## S1. Glossary {#id-app-a}
::: {#tbl-experiments}
```{=latex}
\glossaryTerms
```
Glossary
:::
{{< pagebreak >}}

## S2. Single World Intervention Graphs Eludicate Complex Identification Problems {#id-app-b}
::: {#tbl-pearltable}
```{=latex}
\pearltable
```
On the limitations of causal directed acyclic graphs compared to Single World Intervention Graphs. 
:::

According to @pearl2009a, example 11.3.3. $Y(x_0, x_1)$ is not independent of $X_1$ given Z and $X_0$.  Template $\mathcal{G}_2$ and Single World Intervention Graphs $\mathcal{G}_2-6$ examine counterfactual independence. Counterfactual nodes are obtained by node-splitting. $\rightarrowlightgray$ denotes a backdoor path that is closed when a treatment is fixed. $\rightarrowcyan$ highlights identifying paths for $X_0 = x_0$ and $X_1 = x_1$. @robins2010alternative uses a variation of $\mathcal{G}_2$ to show that there is sequential exchangeability of $X_t \forall t: Y(x_1, x_0)\coprod X_0$ (unconditionally) and $Y(x_1, x_0)\coprod X_1(x_0) | Z(x_0), X_0$. By causal consistency $Z(x_0) = Z|X_0 = x_0$. Single world interventions $\mathcal{G}_{3-6}$ make this sequential exchangeability clear (refer to @richardson2013). Such clarity is, in my view, an excellent reason to use Single World Intervention Graphs.

{{< pagebreak >}}
## S3. Richardson and Robin's Extended Dynamic G-formula {#id-app-c}


@richardson2013 propose an extension of @robins1986's dynamic g-formula for identifying causality under dynamic treatment regimes. Here, I reproduce the key details of their identification algorithm. I refer readers to @richardson2013 for the full algorithm and its proofs.

First, define the set of counterfactual variables in our dynamic Single World Intervention Graph (or Template):

$\mathbb{A}^+(\mathbf{g})$: denotes the set of modified treatment variables under a dynamic regime 
$\mathbb{V}(\mathbf{g})$: denotes the set of counterfactual nodes following treatments.
$\mathbb{W}(\mathbf{g})$: denotes the combined set of all counterfactual variables under a dynamic regime corresponding to Table 12 $\mathbf{G}_4$ in the main article.

@richardson2013 define this set as follows:

$$
\mathbb{W}(\mathbf{g}) \equiv \mathbb{A}^+(\mathbf{g}) \cup \mathbb{V}(\mathbf{g})
$$

Next, at each intervention node $t$, our task is to find all ancestors of $Y(\mathbf{g})$ in $\mathbb{W}(\mathbf{g})$ that are not in the set of current or past treatment covariates. @richardson2013 define this set as follows:

$$
\mathbb{Z}_t(\mathbf{g}) \equiv \text{an}_{\mathcal{G}(\mathbf{g})}(Y(\mathbf{g})) \setminus (\mathbb{L}_t(\mathbf{g}) \cup \mathbb{A}_t(\mathbf{g}) \cup \mathbb{A}^+(\mathbf{g}))
$$

Third, our task is to map $\mathbb{Z}$ to a new Single World Intervention Graph $\mathcal{G}(\mathbf{a}^*)$, where the intervention $\mathbf{a}^*$ is a specific value of $A = a$ assigned under $f^g(\cdot)$. 

This new `dSWIG` or `dynamic Single World Intervention Graph` $\mathcal{G}(\mathbf{a}^*)$ is simply the original dSWIG $\mathcal{G}(\mathbf{g})$ with the dashed arrows removed. 

Fourth, our task is to ensure conditional independence of the treatment $A_t = a^*$ with members of the set $\mathbb{Z}_t$, for all $\mathbf{a}^*$ (fixed nodes) and all time points $t \in 1...\tau$, where $\tau$ is the end of the study. @richardson2013 define this set as follows:

$$
\mathbb{Z}_t(\mathbf{a}^*) \coprod I(A_t(\mathbf{a}^*) = a^*_t) \mid \bar{\mathbb{L}}_t(\mathbf{a}^*), \bar{\mathbb{A}}_{t-1}(\mathbf{a}^*) = \bar{\mathbf{a}^*}_{t-1}
$$

where the authors use $I$ to denote the indicator function:

$$
I(A_k(\mathbf{a}^*) = a^*_t) = 
\begin{cases} 
1 & \text{if } A_k(\mathbf{a}^*) = a^*_t, \\
0 & \text{otherwise}.
\end{cases}
$$

where:

- **$\mathbb{Z}_t(\mathbf{a}^*)$**: denotes the subset of vertices in $\mathcal{G}(\mathbf{a}^*)$ corresponding to $\mathbb{Z}_t(\mathbf{g})$.
- **$A_t(\mathbf{a}^*) = a^*_t$**: denotes the specific value of the treatment variable at time $t$ under the intervention $\mathbf{a}^*$.
- **$\bar{\mathbb{L}}_t(\mathbf{a}^*)$**: denotes the set of covariates up to time $t$ under the intervention $\mathbf{a}^*$.
- **$\bar{\mathbb{A}}_{t-1}(\mathbf{a}^*)$**: denotes the set of past treatment variables up to time $t-1$ under the intervention $\mathbf{a}^*$.

In the example describe in the main article Table 12 $\mathcal{G}_4$, $\mathbb{Z}_t(\mathbf{g})$, we apply @richardson2013's dynamic extended g-formula, and obtain:

$$
\begin{aligned}
\mathbb{Z}(\mathbf{g}) &= \{A_1, L_1(\mathbf{g}), A_1(\mathbf{g}), A_2(\mathbf{g}), Y(\mathbf{g})\} \\
\mathbb{Z}_1(\mathbf{g}) &= \{A_1(\mathbf{g}), L_1(\mathbf{g}), Y(\mathbf{g})\} \\
\mathbb{Z}_2(\mathbf{g}) &= \{Y(\mathbf{g})\}
\end{aligned}
$$

Then we check conditional independencies for each treatment in the main manuscript Table 12 $\mathcal{G}_4$ (which is Table 12 $\mathcal{G}_5$ without the dashed green arrows). We inspect this template and learn the dynamic treatment strategy under consideration is not identified.


{{< pagebreak >}}

## S4. Structural Causal Models and Shift interventions

Below is @díaz2021's formulation of @pearl2009a's mathematical representation of a structural causal model with non-independent errors. I present @díaz2021's formulation because it allows us to present a structural causal model for dynamic treatment strategies @richardson2013, also known as longitudinal modified treatment policies @hoffman2023. Note further that @richardson2013 develop their account of time-varying treatments using structural causal models. The difference is that on the potential outcome framework, identification does not rely on non-independent error terms or so-called 'cross-world' assumptions [@richardson2013, pp. 60-84]. 

Following Díaz, we begin by defining the sequence of variables in our model:

$$
S_i= (W, Y_0, L_1, A_1, L_2, A_2, ..., L_\tau, A_\tau, Y_{\tau}) \sim \mathbf{P}
$$
  
where $S_i$ is a sample from the distribution $\mathbf{P}$ and includes baseline covariates $W$, intermediate outcomes $L_t$, treatments $A_t$, and final outcomes $Y_{\tau}$ over time periods $t = 1, 2, \ldots, \tau$.

We define the final outcome:

$$
Y = A_{\tau + 1}
$$


We define the history of all variables up to treatment $A_t$ as:
   
$$
H_t = (\bar{A}_{t-1}, \bar{L}_t)
$$

Here, $\bar{A}_{t-1}$ represents the history of treatments up to time $t-1$, and $\bar{L}_t$ represents the history of intermediate outcomes up to time $t$.


We define the vector of exogenous variables (error terms). Note on Pearl's structural causal model account, but not the potential outcomes framework, the error terms must always be independent:

$$
U = (U_{L,t}, U_{A,t}, U_{Y}: t \in \{1 \dots \tau\})
$$

Where $U$ describes the set of exogenous variables affecting $L_t$, $A_t$, and $Y$.


We assume the following deterministic functions for the intermediate outcomes, treatments, and final outcome:
   
1. For intermediate outcomes:

$$
L_t = f_{L_t}(A_{t-1}, H_{t-1}, U_{L,t})
$$

2. For treatments:
   
$$
A_t = f_{A_t}(H_t, U_{A,t})
$$

3. For the final outcome:

$$
Y = f_{Y}(A_{\tau}, H_{\tau}, U_{Y})
$$


Longitudinal modified treatment policies (LMTPs) are defined as functions that assign treatments flexibly based on individual co-variate histories. Note that where there are multiple treatments, these histories will be partially counterfactual. 
   
We replace the deterministic function for treatments:

$$
A_t = f_{A_t}(H_t, U_{A,t})
$$

With the intervention function:

$$
A(\mathbf{g}_t)
$$


On the structural causal model account, this intervention produces counterfactual histories given:

$$
L_t(\bar{A}(\mathbf{g})_{t-1}) = f_{L_t}(A(\mathbf{g})_{t-1}, H_{t-1}(\bar{A}(\mathbf{g})_{t-2}), U_{L,t})
$$


For treatments, the counterfactual variable $A_t(\bar{A}^\mathbf{g}_{t-1})$ is defined as the natural value of the treatment, i.e., the value of the treatment that would have been observed at time $t$ under the intervention history leading up to it at $t-1$, and then discontinued:

$$
A_t(\bar{A}^\mathbf{g}_{t-1}) = f_{A_t}(H_t(\bar{A}^\mathbf{g}_{t-1}), H_{t-1}(\bar{A}^\mathbf{g}_{t-2}), U_{L,t})
$$

When all variables are intervened on, the counterfactual final outcome is:

$$
Y(\bar{A}^\mathbf{g}) = f_Y(A^\mathbf{g}_\tau, H_\tau(\bar{A}^\mathbf{g}_{\tau-1}), U_{Y})
$$

@williams2021 have developed the lmtp package in R for estimating time-varying treatments with time-varying confounding. Among the many excellent features of their software is that it uses semi-parametric estimators, which can be specified from the @SuperLearner2023 library. Readers working with `lmtp` might find the following collection of tools useful for evaluating assumptions, creating graphical outputs and tables, and automating reporting: @margot2024.


{{< pagebreak >}}

## References

::: {#refs}
:::




